.changeset/few-candles-perform.md
packages/swagger-editor/src/components/SwaggerEditor/SwaggerEditor.vue

Previously, the state was kept in storage but only restored onMount. This caused bugs, e.g. resetting the content  when changing tabs.
This PR stores the content from local storage in the the `currentExample` ref which we already introduced anyway. This seems to work better.

fix: keep swagger editor state

---

packages/api-client/src/components/ApiClient/AddressBar.vue
packages/api-client/src/components/ApiClient/Request/Request.vue
packages/api-reference/src/components/ApiReference.vue
packages/api-reference/src/components/Card/CardContent.vue
packages/api-reference/src/components/Content/Introduction/ClientSelector.vue
packages/api-reference/src/components/Content/Introduction/Introduction.vue
packages/swagger-editor/src/components/SwaggerEditor/SwaggerEditor.vue
packages/swagger-editor/src/components/SwaggerEditor/SwaggerEditorHeader.vue
packages/themes/src/presets/alternate.css
packages/use-codemirror/src/components/CodeMirror/CodeMirror.vue

A handful of small fixes
- client libraries background broke when added a mobile fix it needs to be transparent
- client libraries more icon is broken
- just now alignment
- checkbox active
- swagger file alignment
- remove unused mobile media query (scalar-api-client__codemirror__wrapper)
- remove unused border left and right on mobile

references themes and color bugs

---

packages/api-reference/src/components/ApiReference.vue

Before
https://github.com/scalar/scalar/assets/6201407/f533b53b-b7f4-44b0-a1e7-05b7f866e629
After

remove grid from mobile reference as it breaks layout

---

.changeset/cuddly-insects-design.md
packages/api-reference/src/components/DarkModeToggle.vue

this breaks SSG before, we need to be using a ref.
We also should think about a way to ensure document deploys in internal repo are less fragile

fix: wrap watchEffect onMounted for dark light toggle until we use refs

---

packages/api-reference/src/components/ApiReference.vue
packages/api-reference/src/components/Card/Card.vue
packages/api-reference/src/components/Card/CardFooter.vue
packages/api-reference/src/components/Card/CardHeader.vue
packages/api-reference/src/components/Content/EndpointsOverview.vue
packages/api-reference/src/components/Content/Introduction/Introduction.vue
packages/api-reference/src/components/Content/MarkdownRenderer.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/ExampleRequest.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/ExampleResponses/ExampleResponses.vue
packages/use-toasts/src/FlowToast.vue

height of example request example responses can overflows viewport

---

.changeset/beige-ears-bake.md
packages/api-reference/src/index.ts

Now we can use our wonderful SearchModal outside the APIReferences :)

fix: add SearchModal to exports

---

.changeset/fuzzy-rivers-jump.md
packages/api-reference/src/components/ApiReference.vue
packages/api-reference/src/components/Content/Introduction/BaseUrl.vue
packages/api-reference/src/types.ts

Reactivity is hard. The servers are in an array inside a reactive object. We need to make sure the array is always present, otherwise the Swagger editor would keep the url of the previously added spec when the new spec doesn’t have servers.

fix: make the base urls reactive

---

.changeset/thick-jobs-wonder.md
packages/api-reference/src/components/Content/Introduction/Introduction.vue

The description loading placeholder was even shown when a spec file without a description was loaded.
This PR makes sure the description place holder is only shown when there’s no spec file loaded.

fix: don’t always show the description loading placeholder

---

.changeset/sharp-kangaroos-jam.md
packages/api-reference/index.html
packages/api-reference/vite.standalone.config.ts
packages/swagger-editor/src/components/SwaggerEditor/SwaggerEditor.vue
projects/web/src/pages/StartPage.vue

With #166 we introduced a regression which made the ApiReference not show the initial content. This PR fixes it by passing the initial content to the parser, not just to the SwaggerEditor CodeMirror instance.

fix: fastify plugin does not show content

---

.changeset/perfect-melons-hear.md
.changeset/rare-lobsters-sparkle.md
.changeset/slow-panthers-sit.md
packages/api-client-proxy/src/createApiClientProxy.ts
packages/api-reference/src/components/ApiReference.vue
packages/swagger-editor/src/components/SwaggerEditor/GettingStarted.vue
packages/swagger-editor/src/components/SwaggerEditor/SwaggerEditor.vue
packages/swagger-editor/src/components/SwaggerEditor/SwaggerEditorHeader.vue
packages/swagger-editor/src/components/SwaggerEditor/fetchSpecFromUrl.ts
packages/swagger-editor/src/types.ts

People were confused when they clicked on import URL or upload file and they saw the empty editor. This PR opens the import url modal or the file dialog. 💅 
https://github.com/scalar/scalar/assets/1577992/6b25b2aa-6e80-434a-8713-489e1f7e697b

feat: import URL & upload file in getting started open the modal/dialog

---

.github/workflows/ci.yml
.gitignore
package.json
pnpm-lock.yaml
turbo.json

This PR adds turborepo. Turborepo tries to run tasks in parallel as much as possible and caches the results. Makes builds and CI extremely fast.
GitHub Actions is down from 5m to 1m. And there’s still a lot more potential, but let’s further improve it in a separate PR.
**Performance**
Full build locally (without Turborepo):
80s
Initial build with Turborepo:
30s
Cached build with Turborepo:
0.2s :exploding_head:
Full build in CI without Turborepo:
95s
Initial build in CI with Turborepo:
35s :exploding_head:
Cached build in CI with Turborepo:
5s :exploding_head: :exploding_head: :exploding_head:

chore: add turborepo

---

packages/api-reference/src/components/Content/Content.vue
packages/api-reference/src/components/Sidebar.vue

This PR optimizes the layout for specs with just one default tag:
* No folder item in the sidebar
* No endpoints overview

feat: improve layout for specs with one tag

---

.changeset/beige-chairs-march.md
packages/api-reference/src/components/Sidebar.vue

Let’s say there are only h2 or h3 in the description, let’s find out and just use the highest level that was used and put all headings of that level in the sidebar.
Example: https://github.com/aolabsai/archs/blob/main/core_api.yaml

feat: show headings with lower depth in the sidebar

---

.changeset/wise-radios-explode.md
packages/api-reference/src/components/Sidebar.vue
packages/api-reference/src/helpers/getHeadingsFromMarkdown.ts
packages/api-reference/vite.config.ts

In #233 I broke SSG. This PR externalizes the new Markdown plugin to not break SSG. :)

fix: externalize markdown plugin to not break SSG

---

lefthook.yml

The linting Git hook took like 50s or so. 🤡 I’ve changed the hook to only lint staged files, which just takes a few ms (depending on how many files are staged).

chore: make the linting git hook only fix staged files

---

.changeset/short-doors-laugh.md
packages/api-reference/src/components/ApiReference.vue

Fix references not respecting height on mobile Safari

---

.changeset/five-crews-mix.md
.changeset/healthy-moons-refuse.md
.changeset/pink-ravens-live.md
packages/swagger-editor/src/components/SwaggerEditor/SwaggerEditor.vue
packages/swagger-parser/README.md
packages/swagger-parser/src/helpers/analyze.test.ts
packages/swagger-parser/src/helpers/analyze.ts
packages/swagger-parser/src/helpers/index.ts
packages/swagger-parser/src/helpers/parse.test.ts
packages/swagger-parser/src/helpers/parse.ts
packages/swagger-parser/src/helpers/preflight.test.ts
packages/swagger-parser/src/helpers/preflight.ts
packages/swagger-parser/src/index.ts
packages/swagger-parser/src/types.ts

**analyze()**
This PR introduces a tiny `analyze` helper function which returns a few basic stats about the given spec. The current aim is to make testing of specs easier. I think we’ll extend the anaylze function to return more stats soon.
**preflight()**
This PR adds a `preflight` helper function which analyzes an unparsed spec. It’s faster, but inaccurate. 
**parse instead of parseSwaggerFile**
It also renames `parseSwaggerFile` to just `parse`. It felt wrong to name other helper files `somethingSwaggerFile()`. And it‘s not even expecting a file, just the content.

feat: add analyse helper to return stats about specs

---

packages/api-reference/src/helpers/generateResponseContent.ts

Depending on the schema, the example responses generator ran into infinite loops. This PR fixes it. 🌟

fix: avoid inifinite loops in example responses

---

packages/api-reference/src/components/Content/ReferenceEndpoint/Copy.vue

Before rendering example responses, check whether the operation has example responses. :)

fix: check if the endpoint has example responses

---

packages/api-client/src/components/ApiClient/RequestMethodSelect.vue
packages/api-client/src/fixtures/httpRequestMethods.ts
packages/api-client/src/fixtures/index.ts
packages/api-client/src/helpers/normalizeRequestMethod.ts
packages/swagger-parser/src/fixtures/httpRequestMethods.ts
packages/swagger-parser/src/fixtures/index.ts
packages/swagger-parser/src/helpers/parse.ts

The path object item has more keys than just request methods:
https://spec.openapis.org/oas/v3.1.0#pathItemObject
Let’s not iterate over the other keys.

fix: render valid request methods only

---

packages/api-reference/package.json
packages/api-reference/src/components/Icon/SvgRenderer.ts
packages/api-reference/vite.config.ts
pnpm-lock.yaml

Let’s switch from xmldom to the successor @xmldom/xmldom. 👍 
> Since version 0.7.0 this package is published to npm as [@xmldom/xmldom](https://www.npmjs.com/package/@xmldom/xmldom) and no longer as [xmldom](https://www.npmjs.com/package/xmldom), because https://github.com/xmldom/xmldom/issues/271.
Source: https://github.com/xmldom/xmldom#xmldomxmldom

chore: switch from xmldom to @xmldom/xmldom, fix #252

---

.changeset/great-lamps-switch.md
package.json
packages/swagger-parser/src/helpers/parse.test.ts
packages/swagger-parser/tests/fixtures/shopware.json
pnpm-lock.yaml

The recent version of @apidevtools/swagger-parser runs into a timeout with some (not all) large files. As described here:
https://github.com/APIDevTools/swagger-parser/issues/221
The mentioned workaround (pinning @apidevtools/json-schema-ref-parser to 9.0.7) seems to work just fine. I’ve added a test to make sure we don’t reintroduce the regression.

fix: hanging parser

---

.changeset/sharp-icons-decide.md
packages/api-client/src/helpers/generateRequest.ts
packages/api-client/src/helpers/generateRequestBody.test.ts
packages/api-client/src/helpers/generateRequestBody.ts
packages/api-client/src/types.ts

If a user has JSON schema for a request body, we populate it in the api client.
If they dont we set an empty object

feat: add requestbody to api client if json schema available

---

.changeset/sixty-tips-warn.md
packages/api-reference/src/components/Content/Content.vue

fix: default show endpoint when tags have one endpoint

---

.changeset/proud-dogs-tie.md
packages/api-reference/src/components/Sidebar.vue

handles the edge case where people have no operations for a tag

fix: add null check to tag operations in sidebar

---

packages/swagger-parser/src/helpers/analyze.test.ts
packages/swagger-parser/src/helpers/parse.ts

We can remove tags that have no operations, it's default for what most swagger/oas doc tools use and I think that makes sense.
I couldnt imagine the need for a tag with no endpoints, let me know if you disagree :)

fix: filter out tags with no operations

---

.changeset/strong-glasses-collect.md
packages/api-reference/src/components/Content/Introduction/Introduction.vue
packages/api-reference/src/components/Content/MarkdownRenderer.vue

In #247 I introduced a tiny regression. Specs without a description showed the loading skeleton forever. This PR fixes it.

fix: deal with empty descriptions

---

.changeset/grumpy-plants-retire.md
packages/api-reference/src/components/Content/Models.vue
packages/api-reference/src/components/Content/Schema.vue
packages/api-reference/src/components/Content/SchemaProperty.vue
packages/api-reference/src/components/Content/ShowMoreButton.vue
packages/api-reference/src/components/Sidebar.vue
packages/api-reference/src/helpers/getModelSectionId.ts
packages/api-reference/src/helpers/hasModels.ts

This PR adds models ("schemas") from the spec file as a separate section.
* Models are listed after all operations
* Max. 3 models are rendered
* When the sidebar folder is toggled or the "show more" button has been clicked, all models are rendered
* Models are listed in the sidebar
This PR comes with a new `Schema` component, which already has a great support for everything defined in the OpenAPI specification, including the `oneOf`, `anyOf` … rules.
**Examples**

feat: show models

---

.changeset/young-cycles-laugh.md
packages/api-reference/src/helpers/generateResponseContent.test.ts
packages/api-reference/src/helpers/generateResponseContent.ts

Some schemas provide a `default` value. With this PR it’s used for the example responses, if it’s available:

feat: use ‘default’ for example responses

---

.changeset/khaki-keys-rush.md
packages/api-reference/src/components/Content/ReferenceEndpoint/ExampleRequest.vue

With this PR the example request body is added to the example request generator:

feat: add request body to example request

---

.changeset/clean-worms-beam.md
packages/api-client/src/components/ApiClient/AddressBar.vue
packages/api-client/src/components/ApiClient/ApiClient.vue
packages/api-client/src/components/ApiClient/Request/Request.vue
packages/api-client/src/components/ApiClient/Request/RequestAuth.vue
packages/api-client/src/components/ApiClient/Request/RequestHeaders.vue
packages/api-client/src/components/ApiClient/RequestHistory.vue
packages/api-client/src/components/ApiClient/Response/Response.vue
packages/api-client/src/components/CollapsibleSection/CollapsibleSection.vue
packages/api-client/src/components/Grid/Grid.vue
packages/api-client/src/components/SimpleTable/SimpleCell.vue
packages/api-client/src/components/SimpleTable/SimpleRow.vue
packages/api-client/src/components/SimpleTable/SimpleTable.vue
packages/api-reference/src/components/Card/Card.vue
packages/api-reference/src/components/Card/CardHeader.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/ExampleRequest.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/ExampleResponses/ExampleResponses.vue
packages/api-reference/src/components/MobileHeader.vue
packages/api-reference/src/components/SearchModal.vue
packages/api-reference/src/components/Sidebar.vue

so much polish done by the wonderful @cameronrohani 
```
mobile header broken (missing background and border bottom) 
mobile header missing night mode toggle 
mobile tabs overflow doesn't scroll + word breaks 
inconsistent table styles across client 
remove dashed border for empty states where there's no table / code block going in to
more consistent buttons in client
Temp remove client topbar border (until we make it an actual input)
hide overflow from search
move language selector to bottom left of cards on mobile
```

Mobile improvements and layout fixes + consitency improvements

---

packages/api-client/src/components/ApiClient/Response/Response.vue
packages/api-client/src/helpers/sendRequest.ts

Direct request responses look different than responses received via a
proxy. Transform direct responses to look more like proxied responses
after they are received.
Updates #312

fix: handle both direct and proxied responses

---

.changeset/silver-terms-prove.md
packages/api-client/src/components/ApiClient/AddressBar.vue

We had the idea to shorten the URL on small screens, but what we did was actually overwriting the URL. That doesn’t work. :) I disabled dit for now, we need to find a rendering-based solution.

fix: don’t overwrite the URL on small screens

---

.changeset/red-buses-call.md
packages/api-reference/src/helpers/generateResponseContent.test.ts
packages/api-reference/src/helpers/generateResponseContent.ts

With this PR the min value for numbers is used as the default when generating example responses. 🤓

feat: use min value as the default for numbers

---

.changeset/long-lobsters-yawn.md
packages/api-reference/src/components/Sidebar.vue

This should fix an error with some specs having tags without operations.

fix: optional chain

---

.changeset/few-boxes-swim.md
packages/api-reference/src/components/Content/Content.vue
packages/api-reference/src/components/Content/EndpointsOverview.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/ReferenceEndpoint.vue
packages/api-reference/src/components/SearchModal.vue
packages/api-reference/src/components/Sidebar.vue
packages/api-reference/src/helpers/getModelSectionId.ts
packages/api-reference/src/helpers/getOperationSectionId.ts
packages/api-reference/src/helpers/getTagSectionId.ts

This PR prefixes all operation section ids with their parent tag. This makes it possible to distinguish which operation should be active, if the operation has multiple tags and is listed in multiple places.

DOC-1162 fix: active state for operations with multiple tags

---

packages/api-reference/src/components/ApiReference.vue

Oops, my debug output slipped through. Let’s remove it quickly.

chore: remove debug output

---

packages/api-reference/src/components/ApiReference.vue

In #236 I’ve added the deprecated props, which by default fallback to false and are then considered to be set. Eventually `showSidebar` was `false`.
With this PR the default for those deprecated boolean props is `undefined`. This should fix the bug and the sidebar should appear again. 🥵

fix: use undefined as the default for deprecated props

---

.changeset/honest-keys-hear.md
packages/swagger-editor/src/components/SwaggerEditor/SwaggerEditorAIWriter.vue
packages/swagger-editor/src/components/SwaggerEditor/TheHuman.vue

fix heading and inputs

---

.changeset/fast-wolves-mate.md
packages/api-reference/src/components/ApiReference.vue

I’ve added a regression in #362. I didn’t want to load the swagger editor if it’s not used, but that also means the spec isn’t parsed … because currently the swagger editor is responsible for the parsing.

hotfix: load swagger editor in readonly mode

---

.changeset/young-eels-dress.md
packages/api-reference/src/components/ApiReference.vue
packages/swagger-editor/src/components/SwaggerEditor/SwaggerEditor.vue

Wow, another regression from #362. The spec URL was fetched and stored in a ref, but the wrong ref was passed to the editor. This is the fix:
```diff
-:value="parsedSpecRef"
+:value="rawSpecRef"
```
Everything else cleans up the messy data flow just a little bit. Hopefully I didn’t introduce a new regression. Looks like it’s time to refactor the reference <> swagger editor <> parser data flow. 😵‍💫

hotfix: import spec from url

---

.changeset/nervous-queens-attend.md
packages/api-client/src/components/ApiClient/Request/Request.vue
packages/api-client/src/components/SimpleTable/SimpleCell.vue
packages/api-client/src/components/SimpleTable/SimpleRow.vue
packages/api-client/src/components/SimpleTable/SimpleTable.vue
packages/api-reference/src/components/ApiReference.vue
packages/api-reference/src/components/Card/Card.vue
packages/api-reference/src/components/Card/CardContent.vue
packages/api-reference/src/components/Card/CardFooter.vue
packages/api-reference/src/components/Card/CardHeader.vue
packages/api-reference/src/components/Card/CardTab.vue
packages/api-reference/src/components/Content/Introduction/ClientSelector.vue
packages/api-reference/src/components/Content/MarkdownRenderer.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/ExampleRequest.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/ExampleResponses/ExampleResponses.vue
packages/api-reference/src/components/FlowButton.vue
packages/api-reference/src/components/Sidebar.vue
packages/api-reference/src/components/SimpleTable/SimpleCell.vue
packages/api-reference/src/components/SimpleTable/SimpleTable.vue
packages/swagger-editor/src/components/SwaggerEditor/MarkdownRenderer.vue

We're seeing some collisions with markdown + cards on users websites so I unset all markdown and prefixed cards. 
We should come up with something more robust later but this should be good for now

fix markdown collisions + prefix the card name

---

packages/api-reference/src/components/Content/MarkdownRenderer.vue

I saw some empty table headers in a spec. This PR adds CSS to hide empty table headers:
**Before**
**After**
In theory, you could have some table headers empty and some not, but this looks still okay-ish and is probably less likely than having all table headers empty.

style: hide empty table headers

---

.changeset/thin-dragons-sort.md
packages/api-reference/src/components/Content/ReferenceEndpoint/ExampleResponses/ExampleResponses.vue

I saw some empty example responses. This PR includes two related fixes:
* When there’s an example, make sure to transform it to text before passing it to CodeMirror.
* If there’s an example, don’t show the generated example.
**Before**
**After**

fix: empty example responses

---

packages/api-reference/src/components/Content/Introduction/ServerItem.vue

When variables are empty, the server url looks wrong. Let’s use the variable name as the placeholder then.
https://github.com/scalar/scalar/assets/1577992/e3c9ff1d-8b46-4ca3-937a-2bd4bc834542

feat: use variable name as placeholder for the server url

---

.changeset/great-eggs-drop.md
packages/api-client/src/components/ApiClient/AddressBar.vue
packages/api-client/src/components/ApiClient/Request/Request.vue
packages/api-client/src/components/HelpfulLink.vue

This PR fixes some minor styling issues I’ve seen in the native web view on macOS.
* The CodeMirror component wasn’t full width.
* The address bar text color was always black.
* The response status code was always blue.

fix: minor styling issues with native web view

---

.changeset/hungry-dolls-wash.md
packages/api-client-proxy/package.json
packages/api-client/package.json
packages/api-client/src/helpers/sendRequest.test.ts
packages/api-client/src/helpers/sendRequest.ts
packages/api-client/src/types.ts
pnpm-lock.yaml

This PR improves sendRequest, the heart of the API client.
* I’ve added a test using it with a proxy and made the responses with/without a proxy look similar.
* I’ve also decided to keep the response body as a string. We shouldn’t care whether the response is JSON or not, except when rendering a preview.

refactor: test send request with proxy

---

packages/api-reference/src/components/Content/SchemaProperty.vue

Before:
After: 
(scrollable ui)

property overflow fix

---

packages/api-reference/src/components/ApiClientModal.vue

client close icon

---

packages/api-reference/src/components/Icon/icons/Menu.svg

This PR adds the `Menu.svg` icon that was removed in #369 as it is still used: https://github.com/scalar/scalar/blob/9b1e2653f0c46f053681bc126dec5a631e281658/packages/api-reference/src/components/MobileHeader.vue#L15

fix: re-add missing menu icon

---

.changeset/brown-buckets-repair.md
packages/api-reference/src/components/ApiClientModal.vue
packages/api-reference/src/components/Sidebar.vue
packages/use-modal/src/components/FlowModal.vue

quick fixes for two common things I've seen 
Making our --theme-background-1 transparent (which makes search + client unusable)
And making darklight display: none;

users not using themed css fallbacks

---

.changeset/short-bottles-push.md
packages/api-reference/src/hooks/useSpec.test.ts
packages/api-reference/src/hooks/useSpec.ts

With #398 I introduced a regression: When a Swagger spec is added, and the config changes, the content is overwritten - even if there’s not configuration for it.
This PR adds a test and a fix.

fix: do not touch the content if nothing is configured

---

.github/workflows/ci.yml

CI is running on push to main, but we don’t do anything with the output, so we could also not run it on push to main. :)
It’ll still running on all PRs.

chore: don’t run ci on push to main

---

.changeset/lucky-turtles-play.md
packages/api-reference/src/components/Content/Introduction/Introduction.vue

The version field is required according to the OpenAPI spec, but the parser won’t complain. So let’s ignore it, if there’s no version defined.
We don’t need this for the OpenAPI version. The parser requires this field.
**Before**
**After**

fix: hide version if it’s not set

---

.changeset/great-panthers-help.md

This PR only includes a changeset to force a new release of @scalar/api-client-proxy. At some point the build didn’t include the types anymore, but we fixed this already. With a force released, the package should include the types again.

fix: types of @scalar/api-client-proxy

---

projects/web/src/pages/ApiReferencePage.vue

This PR fixes a warning in the reference demo. Let’s not overwrite the configuration constant, but assign the new configuration. 👍 
```
[plugin:vite:esbuild] This assignment will throw because "configuration" is a constant
50 |        _createVNode(DevToolbar, {
51 |          modelValue: configuration,
52 |          "onUpdate:modelValue": _cache[0] || (_cache[0] = ($event: any) => ((configuration) = $event))
|                                                                              ^
53 |        }, null, 8, ["modelValue"])
54 |      ]),
```

chore: don’t overwrite the configuration constant

---

package.json
packages/themes/package.json
pnpm-lock.yaml
scripts/format-package.ts
scripts/utility.ts

Took the custom formatting script from #425 and added it to the repository. 🙌
Changed some minor details and used vite-node instead of bun. I don’t really care, but vite-node is already used 7 other packages in the repository.
This PR doesn’t actually apply the formatting, we’ll do this in a separate PR when the PR list is shorter.

chore: custom package json formatting

---

.changeset/three-teachers-drum.md
packages/api-reference/src/components/ApiReference.vue
packages/swagger-editor/src/components/SwaggerEditor/SwaggerEditor.vue
projects/web/src/pages/ApiReferencePage.vue

We used to store the Swagger editor content in local storage but broke that recently. But I miss it, it made the dev cycle so much faster.
I’ve added the code to cache the content to the example and removed it from the package.
And I’ve added a `updateContent` event to the `ApiReference` component.

chore: store content in local storage

---

.changeset/rich-sheep-change.md
packages/api-reference/src/components/Content/Introduction/Description.vue

With this PR the component isn’t upset anymore when there’s no description. 😡

fix: show description only if available

---

.changeset/fair-avocados-speak.md
packages/api-client-proxy/package.json
packages/api-client-proxy/vite.config.ts
packages/echo-server/package.json
packages/echo-server/vite.config.ts

This PR fixes wrong paths for the api-client-proxy introduced in #426 and adds CommonJS builds for `@scalar/api-client-proxy` and `@scalar/echo-server`.
I’m a fan of ESM-only packages, but I needed them in another environment and using ESM-only there was just too big of a hurdle. And there are probably other people preferring CommonJS builds, too.

feat: CommonJS builds for `@scalar/api-client-proxy` and `@scalar/echo-server`

---

.changeset/slimy-cougars-give.md
packages/api-reference/src/components/Content/ReferenceEndpoint/ExampleResponses/SelectExample.vue

before if you had no key or summary it would be an empty list, now we provide a `scalarExampleName` generated to the object with the key of the example

fix: add fallback if no summary or key is provided for examples

---

.changeset/eighty-windows-develop.md
packages/api-reference/src/components/Content/ReferenceEndpoint/ReferenceEndpoint.vue
packages/api-reference/src/components/SearchModal.vue
packages/api-reference/src/components/Sidebar.vue
packages/swagger-parser/src/helpers/parse.ts

It’s somehow confusing how the fallback for the operation.name is chosen. With this PR it’s done in a single place, and the order is:
1. `operationId` or…
2. `summary` or …
3. `path`
In the SearchModal, the `path` is only added if it’s not used for the name fallback already.

chore: better fallbacks for the name

---

.changeset/red-pugs-impress.md
.changeset/thirty-terms-thank.md
packages/api-reference/src/components/ApiReference.vue
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/hooks/useParser.ts
packages/swagger-editor/src/components/SwaggerEditor/SwaggerEditor.vue
packages/swagger-editor/src/components/SwaggerEditor/SwaggerEditorGettingStarted.vue
packages/swagger-editor/src/components/SwaggerEditor/SwaggerEditorInput.vue
projects/web/src/components/DevToolbar.vue
projects/web/src/pages/ApiReferencePage.vue

WIP
We introduced a regression where loading examples created duplicate content. This PR has the following changes to fix this and related bugs.
* Fix: The editor is mounted even when another tab than 'Swagger Editor' is active (otherwise content can’t be synced in collaborative editing mode)
* Fix: Whitespace is trimmed from the content before it’s parsed.
* Refactor: The SwaggerEditor doesn’t “know” about the examples anymore, it just deals with strings. All examples have been moved to the GettingStarted component.
* Bonus: Collaborative editing can be configured in the dev toolbar now

fix: examples in collaborative editing mode

---

.changeset/two-carpets-watch.md
packages/api-client/src/helpers/sendRequest.ts
projects/web/src/pages/StandaloneApiReferencePage.vue

this fixes https://github.com/scalar/scalar/issues/440
Now when not using the proxy, we catch the error and add it to the request history. 
before:
after:

fix: show non 200 responses when not using the proxy

---

.changeset/twelve-knives-learn.md
packages/api-reference/src/components/Content/Models.vue
packages/api-reference/src/components/Content/Schema.vue

this fixes 
https://github.com/scalar/scalar/issues/449
before:
after:

fix: add fallback to name for models if no xml attribute passed

---

packages/api-reference/src/components/Content/MarkdownRenderer.vue

before:
After:
+ fix line height for headings

fix word breaks in .markdown

---

.changeset/breezy-impalas-run.md
packages/api-reference/src/components/Content/Authentication/SecurityScheme.vue

The browser had this warning:
> [DOM] Password field is not contained in a form
And this PR fixes it. With the added form tag, the auth UI should also play well with password managers.

chore: auth credentials in a form

---

.changeset/afraid-carpets-watch.md
packages/api-reference/src/components/Content/Authentication/Authentication.vue

With this PR bearer auth is taken as the default http auth method (that’s what Swagger UI does, too). E.g. this is enough:
```
"security": [
{
"http": []
}
],
```
Source: https://raw.githubusercontent.com/outline/openapi/main/spec3.json
**Before**
**After**

feat: fallback for http auth

---

.changeset/swift-peaches-hear.md
packages/api-reference/src/components/Content/Content.vue
packages/api-reference/src/types.ts

In Swagger 2.0 files servers are configured like this:
```json
{
"host": "api.example.com",
"schemes": [
"https"
]
}
```
This PR adds support for this syntax.

feat: swagger 2.0 host and schemes

---

.changeset/strange-baboons-marry.md
packages/api-reference/src/helpers/getExampleFromSchema.test.ts
packages/api-reference/src/helpers/getExampleFromSchema.ts

This PR adds support for the use of `oneOf` and `allOf` in the schema for responses.
When generating example responses from the schema, the first entry in `oneOf` is used.
For `allOf` we generated example for all given schemas and try to merge them.

feat: add support for oneOf and allOf in the response schema

---

packages/api-reference/src/components/ApiReference.vue
packages/api-reference/src/helpers/hasModels.ts
packages/api-reference/src/helpers/hasSecuritySchemes.ts
packages/api-reference/src/hooks/useSpec.test.ts

This PR makes the imports relative paths and fixes the following error:
```
projects/web dev: Error: The following dependencies are imported but could not be resolved:
projects/web dev:   src/types (imported by scalar/packages/api-reference/src/components/ApiReference.vue?id=0)
```

chore: make imports relative

---

projects/web/src/pages/ApiReferencePage.vue

With this PR the editor content of the demo is stored in local storage (again).
Makes development way easier.

chore: store api reference demo editor content in local storage

---

.changeset/calm-bats-flash.md
packages/swagger-parser/src/helpers/parse.ts

In #448 we changed the priority of what is used as the operation name for the sidebar, headings and so on. I think I made a mistake. In #448 the priority was:
1. operationId or…
2. summary or …
3. path
But the operationId is something more technical (more like a variable name) and the summary is more descriptive. Let’s change the priority to this:
1. summary or …
2. operationId or…
3. path
I tested it with a lot of specs and it improved every example I tested.

chore: use summary instead of operationId

---

.changeset/tricky-birds-give.md
packages/swagger-parser/src/helpers/parse.ts

Okay … that’s kind of a long journey. I experimented with different fallbacks for the name, but based on the user feedback I don’t think we should use the operationId as a potential fallback for the operation name.
With this PR we’re looking for the `summary` and if it’s not available, we just use the path.
That change gives users still control, but avoids confusion and the use of (in most cases technical) operationIds.

chore: do not use the operationId as name

---

packages/express-api-reference/README.md

chore: add swagger url example to the express README

---

.changeset/cyan-news-tell.md
packages/swagger-editor/package.json
packages/swagger-editor/vite.config.ts

This PR optimises the bundle size of `@scalar/swagger-editor` through externalizing dependencies.
**Before**
```
dist/index.js  2,109.06 kB │ gzip: 556.83 kB
```
**After**
```
dist/index.js  611.88 kB │ gzip: 61.61 kB
```
⚠️ This is not really helping with the bundle size you’d have in an app, because the peer dependencies will be installed separately. To be honest, this is more a theoretical optimisation than an actual benefit.
The examples make up most of the bundle size now:

chore: optimize bundle size of `@scalar/swagger-editor`

---

.changeset/unlucky-sheep-compare.md
packages/api-reference/README.md
packages/api-reference/src/components/ApiReferenceBase.vue
packages/api-reference/src/types.ts
packages/swagger-editor/src/components/SwaggerEditor/SwaggerEditor.vue
packages/swagger-editor/src/components/SwaggerEditor/SwaggerEditorHeader.vue
packages/swagger-editor/src/types.ts

needs @cameronrohani to polish it ✨ 
but now you can pass in:
```
tabs: {
initialContent: 'Swagger Editor',
available: ['Swagger Editor'],
},
```
to configure this

feat: make swagger editor tabs configurable

---

.changeset/breezy-jars-buy.md
packages/api-reference/README.md
packages/api-reference/src/components/ApiReferenceBase.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/ExampleRequest.vue
packages/api-reference/src/stores/globalStore.ts
packages/api-reference/src/types.ts
projects/web/src/components/DevToolbar.vue
projects/web/src/pages/ApiReferencePage.vue

This PR does two things:
1. The configuration is put into a global store now. So we don't need to do prop drilling all the time.
2. This feature is used to add a `withApiClient` flag to the configuration and show/hide the `Test Request` button.
https://github.com/scalar/scalar/assets/1577992/07e3239d-155f-4fd5-8439-f040c9d5dd52

feat: [DOC-1357] allow test button + api client to be disabled, fix #519

---

.changeset/tough-lobsters-obey.md
packages/api-reference/src/components/ApiReference.vue
packages/api-reference/src/components/ApiReferenceBase.vue
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/MobileHeader.vue
packages/api-reference/src/components/SearchButton.vue
packages/api-reference/src/components/SearchModal.vue
packages/api-reference/src/index.ts
packages/api-reference/src/stores/template.ts
packages/api-reference/src/types.ts
scripts/dev.sh

This exposes `referenceSlotProps` on all the slots on the `ApiReferenceBase` allowing us to externalize and control the search modal.

refactor: expose slot props for reference base component

---

.changeset/modern-ears-push.md
packages/api-reference/src/components/SearchButton.vue
packages/api-reference/src/hooks/useActive.ts

Prevents search modal hotkey from being active if the component is in a `<keepalive>`  (like our references are) but deactivated.
Before:
https://github.com/scalar/scalar/assets/6374090/41a34bbb-05dc-4c20-8bb2-7a29e6e991b4
After:
https://github.com/scalar/scalar/assets/6374090/556bae47-71f8-4bca-bbf4-4529a8a7f688

fix: only activate hotkey if component is active

---

packages/api-reference/src/helpers/getApiClientRequest.ts
packages/api-reference/src/types.ts

The API client should populate the variables with endpoint-level parameters just like it does for method-level parameters. Also, it should use the default values when provided in the spec.
Resolves #531

fix(getApiClientRequest): added missing path parameter variable and default values.

---

.changeset/clean-avocados-attend.md
packages/api-reference/src/components/Content/ReferenceEndpoint/ExampleResponses/ExampleResponses.vue
packages/api-reference/src/helpers/getApiClientRequest.test.ts
packages/api-reference/src/helpers/getApiClientRequest.ts
packages/api-reference/src/types.ts

We introduced a regression in #536: If a request didn’t have parameters it would fail and the API client wouldn’t open at all.
This PR adds a test for that regression and fixes the issue.
I’ve also made all operation properties optional. Even if that might not match the spec, our package should be flexible with the input.

fix: empty parameters break the api client

---

.github/workflows/ci.yml
.github/workflows/release.yml
packages/api-client-proxy/package.json
packages/api-client/package.json
packages/api-reference/package.json
packages/api-reference/src/hooks/useParser.test.ts
packages/echo-server/package.json
packages/fastify-api-reference/package.json
packages/swagger-editor/package.json
packages/swagger-parser/package.json
packages/use-clipboard/package.json
packages/use-codemirror/package.json
packages/use-keyboard-event/package.json
packages/use-modal/package.json
packages/use-toasts/package.json
packages/use-tooltip/package.json
projects/api-client-proxy/package.json
projects/backend/package.json
projects/echo-server/package.json
projects/fastify-api-reference/package.json

Node 18 isn’t in active support anymore. Let’s upgrade to Node 20 (LTS). 🏄

chore: upgrade to Node 20

---

.changeset/config.json
examples/api-client-proxy/package.json
examples/backend/package.json
examples/echo-server/package.json
examples/express-api-reference/package.json
examples/fastify-api-reference/package.json
examples/hono-api-reference/package.json
examples/react/package.json
examples/ssg/package.json
examples/web/package.json
scripts/dev.sh
scripts/format-package.ts

Follow up for #548, renaming @scalar-org to @scalar-examples.

chore: rename @scalar-org to @scalar-examples

---

.changeset/real-tips-walk.md
packages/api-reference/src/components/SearchButton.vue
packages/swagger-parser/src/helpers/preflight.test.ts

This PR replaces imports pointing to `src` with relative paths. I think this is bringing trouble, e.g. when cross-using the packages in the monorepo.

chore: fix relative imports

---

.changeset/olive-buckets-whisper.md
packages/api-client-proxy/vite.config.ts
packages/api-client/vite.config.ts
packages/api-reference/vite.config.ts
packages/components/vite.config.ts
packages/echo-server/vite.config.ts
packages/swagger-editor/vite.config.ts
packages/swagger-parser/vite.config.ts
packages/use-clipboard/vite.config.ts
packages/use-codemirror/vite.config.ts
packages/use-keyboard-event/vite.config.ts
packages/use-modal/vite.config.ts
packages/use-toasts/vite.config.ts
packages/use-tooltip/vite.config.ts

I saw this funny issue, where the CSS for modals is missing when using the components. 🤔 Bundling the @scalar deps fixes it. Not sure if that’s the approach, but I consider this a quickfix.
https://github.com/scalar/scalar/assets/1577992/2b04b964-92ae-498f-ab43-288d677eb3d0

chore: do not externalize @scalar deps

---

.changeset/khaki-papayas-add.md
.changeset/light-olives-hug.md
packages/api-client-proxy/src/createApiClientProxy.ts
packages/api-client/src/helpers/sendRequest.ts

now if there's any errors at the axios level we show it in the client :)
while still keeping old functionality 😎

fix: catch axios errors and show them in the response

---

.changeset/swift-points-report.md
packages/fastify-api-reference/package.json
packages/fastify-api-reference/vite.config.ts
packages/fastify-api-reference/vite.template.config.ts
packages/use-clipboard/package.json
packages/use-codemirror/package.json
packages/use-keyboard-event/package.json
packages/use-modal/package.json
packages/use-toasts/package.json
packages/use-tooltip/package.json
pnpm-lock.yaml

alright, I would LOVE assistance here on vite + rollup. But it appears in library mode vite [can't minify es builds](https://github.com/vitejs/vite/pull/6314), but jsdelivr does this automatically for our cdn.
https://cdn.jsdelivr.net/npm/@scalar/api-reference@1.2.5/+esm
When I added terser to our minification, we shaved off **800KB**!
before (**3.9MB**)[before gzip]:
after (**3.1MB**) [before gzip]:

feat: reduce fastify scalar bundle size by 800kb

---

.changeset/witty-masks-wave.md
packages/api-client-proxy/src/createApiClientProxy.test.ts
packages/api-client/src/helpers/normalizePath.test.ts
packages/api-client/src/helpers/normalizePath.ts
packages/api-client/src/helpers/sendRequest.test.ts

We normalize/format URLs and paths before sending the request and we want to trim the first trailing slash from the path when  concatenating the URL, but we don’t want that, if the path is literally just the slash. This PR fixes it.
`https://example.com/v1/` + `/posts` = `https://example.com/v1/posts`
🆕 `https://example.com/v1/` + `/` = `https://example.com/v1/`

fix: don't trim the slash when it’s the only character in the URL (fix #567)

---

.changeset/fluffy-elephants-care.md
.github/ISSUE_TEMPLATE/BUG-REPORT.yml
examples/web/src/pages/StandaloneApiReferencePage.vue
packages/api-reference/README.md
packages/api-reference/src/components/ApiReference.vue

Exposes a slot for a footer in the standalone references component
Fixes #568

feat: expose footer slot on standalone component

---

.github/workflows/lint-pr.yml
README.md

In 9 out of 10 cases the PR title are semantic (e. g. `chore: lint PR titles`). Having a standard for the PR titles helps to generate clean changelogs.
This PR adds a CI check to enforce semantic PR titles for every PR.

chore: lint PR title

---

packages/api-reference/src/components/Content/ReferenceEndpoint/RequestBodyProperties.vue
packages/api-reference/src/types.ts

When the field has enum property, Scalar should show the possible values.
resolves - #525

fix(RequestBodyProperties): handled enum type

---

.changeset/ten-points-fix.md
examples/web/src/pages/StandaloneApiReferencePage.vue
packages/api-reference/README.md
packages/api-reference/src/components/ApiReferenceBase.vue
packages/api-reference/src/types.ts

Currently, we’re adding custom CSS for all our integrations to have a branded default theme for Fastify, Platformatic, Express, Hono … and need to build the functionality for every integration. @marclave had this amazing idea to add a custom CSS attribute to the configuration object. 🤯 
This PR adds `customCss` to the configuration object, so we can add custom CSS to all the integrations easily from now on. :)

feat: set `customCss` in the configuration

---

packages/api-reference/src/components/SearchModal.vue

**Before**
Currently, the search modal shows an underline under all links.
**After**
This PR makes sure there’s no decoration for the anchors.

fix: searchModal shows underline for all links, fix #583

---

examples/web/src/pages/ApiReferencePage.vue

**Before**
changing theme does not work on the web example
**After**
changing theme now works on the web example

fix: changing theme in the example

---

.changeset/little-suns-pump.md
packages/fastify-api-reference/src/fastifyApiReference.ts
packages/fastify-api-reference/src/utils/getJavaScriptFile.ts
packages/fastify-api-reference/src/utils/index.ts
packages/fastify-api-reference/vite.config.ts

**Problem**
Currently, the fastify plugin isn’t serving the JS.
This happens because the JS is read from the node_modules folder, expecting @scalar/api-reference to be there. That’s probably an unreliable way to get the JavaScript.
**Solution**
With this PR the JavaScript is bundled with the fastify plugin again. It’s copied to the ./dist folder on build.
Still better than what we had before the refactor. No extra build step, no code duplication, no EJS template. 🎉

fix: fastify plugin doesn’t serve the JS

---

.changeset/ninety-onions-carry.md
examples/hono-api-reference/src/index.ts
packages/api-reference/src/standalone.ts
packages/hono-api-reference/src/honoApiReference.test.ts
packages/hono-api-reference/src/honoApiReference.ts

Fixes https://github.com/scalar/scalar/issues/585
Looks like there may be some issues parsing due to the escaped quotes not being unescaped. I also noticed there were different implementations from the `express` implementation, so this makes `hono` consistent with that by adding the swagger json as an embedded `application/json` script.
I also updated some typing to ensure that it's clear that the parsed json is in fact an object (rather than `any`) as it trickles down to deeper components.

fix: @scalar/hono-api-reference doesn’t use content & preparsedContent

---

.changeset/big-bulldogs-double.md
examples/web/src/pages/StandaloneApiReferencePage.vue
packages/api-reference/README.md
packages/api-reference/src/components/ApiReference.vue
packages/api-reference/src/types.ts

**Problem**
Currently, we can't get the spec programatically
This happens because we dont emit any events to listen to 
**Solution**
With this PR we can configure the references to emit up events. we dont want to always emit events cause that can be expensive to bubble up large payloads

feat: expose spec content updates

---

.changeset/thin-items-matter.md
packages/api-reference/src/components/Content/Schema.stories.ts
packages/api-reference/src/components/Content/SchemaProperty.vue

**Problem**
Currently, if there’s a oneOf rule in an array (`items`), it’s just ignored. This happens because it’s checking the property for the rule, not inside `items`. #599
With this PR the oneOf rule is detected in arrays and visualized accordingly.

fix: oneOf rule in arrays is ignored, fix #599

---

.changeset/yellow-months-remember.md
packages/api-reference/src/components/Badge/Badge.stories.ts
packages/api-reference/src/components/Badge/Badge.vue
packages/api-reference/src/components/Badge/index.ts
packages/api-reference/src/components/Content/Introduction/Introduction.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/ReferenceEndpoint.vue
packages/api-reference/src/components/Sidebar.vue
packages/api-reference/src/components/SidebarElement.vue
packages/api-reference/src/hooks/useNavigation.ts
packages/api-reference/src/types.ts

**Problem**
OpenAPI allows to mark operations as deprecated, but we don’t visualize that.
**Solution**
This PR adds styling for deprecated operations.
If someone wants to improve the design, go for it! :) @hwkr @cameronrohani 
**Preview**

style: visualize deprecated operations

---

.changeset/three-bobcats-fix.md
packages/fastify-api-reference/src/fastifyApiReference.test.ts
packages/fastify-api-reference/src/fastifyApiReference.ts

Let’s use the fastify logging facilities, instead of just console.warn.

chore: use fastify logging facilities

---

.changeset/beige-houses-taste.md
packages/fastify-api-reference/package.json
packages/fastify-api-reference/src/fastifyApiReference.ts
packages/fastify-api-reference/vite.config.ts
pnpm-lock.yaml

**Problem**
Currently, we’re forcing npm/pnpm/yarn to download terser and @scalar/api-reference when installing the fastify plugin, but those needed for development only.
**Solution**
This PR moves them to the devDependencies.

chore(fastify-api-reference): move terser and @scalar/api-reference to devDependencies

---

.changeset/cuddly-kiwis-report.md
.changeset/empty-poets-walk.md
packages/fastify-api-reference/exports.test.ts
packages/fastify-api-reference/package.json
packages/fastify-api-reference/src/fastifyApiReference.ts
packages/fastify-api-reference/vite.config.ts
pnpm-lock.yaml

**Problem**
Currently, we’re using `reply.send()`.
This works, but could break the fastify promise chain. A better approach is to use fastify-html.
**Solution**
With this PR fastify-html is added, registered (if not done already) and used.
⚠️ The CommonJS build is failing with `fastify-html`. I just disabled/removed it for now. If someone complains, I’ll look into it again.

chore: use fastify-html to send HTML

---

.changeset/eighty-pillows-mate.md
packages/api-reference/src/components/Layouts/BaseLayout.vue
packages/api-reference/src/components/Layouts/index.ts

Types the layout props and slots using a base component so you get type errors if you don't use the right props / slots.
Example if `ClassicLayout.vue` included an extraneous prop.

refactor: extract layout type into component

---

.changeset/old-cameras-smash.md
.changeset/small-sloths-shake.md
packages/api-client/src/components/ApiClient/ApiClient.vue
packages/api-reference/src/components/ApiClientModal.vue
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/swagger-editor/src/components/SwaggerEditor/SwaggerEditorHeader.vue

Puts whatever is in the references sidebar into the api client sidebar as well
Also fixes a subpixel rendering issue with the swagger editor tabs

feat: show references sidebar slot content in api client sidebar

---

.changeset/unlucky-planets-unite.md
packages/api-reference/src/components/Content/Introduction/DownloadSpec.vue

**Problem**
Currently, people are confused by the made-up spec URL.
This happens because you can’t open this in a new tab, copy the URL and it’s something else than what you configured.
**Solution**
This PR removes the made-up URL and replaces it with just a “Download OpenAPI Spec“ text.

chore: change download spec button text

---

.changeset/fast-crabs-flow.md
packages/fastify-api-reference/exports.test.ts
packages/fastify-api-reference/package.json
packages/fastify-api-reference/src/fastifyApiReference.ts
packages/fastify-api-reference/vite.config.ts
pnpm-lock.yaml

**Problem**
Currently, there’s no CommonJS build anymore, I removed it in #621. 
This happens because `fastify-html` was breaking the CommonJS build … and I thought we can just get away with removing the CommonJS build. Turns out, the fastify community still loves CommonJS and we need it. :)
**Solution**
With this PR the CommonJS build is fixed, with a dynamic `import()` instead of a regular import.
This PR also removes some unused dependencies and does some clean up.

chore: add @scalar/fastify-api-reference CommonJS build again

---

.changeset/tidy-suits-battle.md
packages/api-reference/src/helpers/getUrlFromServerState.ts

currently if a server is / or // we don't handle it being the location of the docs, throwing an error https://github.com/litestar-org/litestar/pull/2847#issuecomment-1842048832
this fixes that :)

fix: handle root path in request generation

---

.changeset/breezy-bats-brake.md
packages/api-reference/src/helpers/getUrlFromServerState.ts

**Problem**
currently double slashes if server URL is `/`
**Solution**
Now this edge case is handled properly ✨

fix: remove duplicate slash in previews for slash based servers

---

.changeset/quiet-spiders-leave.md
packages/api-client/src/components/ApiClient/Request/Request.vue
packages/api-client/src/components/ApiClient/RequestMethodSelect.vue
packages/api-client/src/components/CollapsibleSection/CollapsibleSection.vue
packages/api-client/src/components/Grid/Grid.vue
packages/api-reference/src/components/Content/Authentication/SecuritySchemeSelector.vue
packages/api-reference/src/components/Content/Introduction/ClientSelector.vue
packages/api-reference/src/components/Content/Introduction/ServerList.vue
packages/api-reference/src/components/Content/Introduction/ServerVariables.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/ExampleRequest.vue

**Problem**
Some select menu's currently don't have `appearance:none` which create a conflict when your systems preferred colour scheme doesn't match the prefers-color-scheme attribute on .dark-mode / .light-mode. 
Results in this:
**Solution**
Add appearance: none; to all select menu's

fix: select menu on chrome

---

.changeset/tasty-lemons-dance.md
packages/api-reference/src/helpers/getParametersFromOperation.test.ts
packages/api-reference/src/helpers/getParametersFromOperation.ts

**Problem**
Currently, the list of parameters becomes really long and combines parameters that are not possible to use together.
This happens because we pass all known parameters to the API client.
**Solution**
With this PR optional parameters aren’t passed to the API client. The UI only shows required parameters now.

chore: don’t pass optional parameters to the client

---

packages/api-reference/vite.config.ts

I'm not sure if this is the best way to fix this but it fixes an issue with importing theme css files

fix: dont alias themes source files

---

packages/api-client/src/helpers/prepareClientRequestConfig.test.ts
packages/api-client/src/helpers/prepareClientRequestConfig.ts

**Problem**
Currently, The `Content-Type` header is always getting overridden 
This happens because of these lines of code here 
https://github.com/scalar/scalar/blob/00c01b56b37a278083ce1bc3b38714061d154703/packages/api-client/src/helpers/prepareClientRequestConfig.ts#L33-L39
**Solution**
With this PR we only override the `Content-Type` header if it's not present in the request

fix: don't override Content-Type header when present in the request

---

.changeset/dull-mugs-knock.md
packages/api-client/src/components/ApiClient/Request/RequestCookies.vue
packages/api-client/src/components/ApiClient/Request/RequestHeaders.vue
packages/api-client/src/components/ApiClient/Request/RequestQuery.vue
packages/api-client/src/components/ApiClient/Request/RequestVariables.vue
packages/api-client/src/components/Grid/Grid.vue
packages/api-client/src/helpers/prepareClientRequestConfig.test.ts
packages/api-client/src/helpers/prepareClientRequestConfig.ts
packages/api-client/src/helpers/sendRequest.test.ts
packages/api-client/src/helpers/sendRequest.ts
packages/api-client/src/types.ts
packages/api-reference/src/helpers/generateParameters.ts
packages/api-reference/src/helpers/getApiClientRequest.ts
packages/api-reference/src/helpers/getParametersFromOperation.test.ts
packages/api-reference/src/helpers/getParametersFromOperation.ts
packages/api-reference/src/helpers/getRequestFromOperation.ts

**Problem**
Currently, there’s a checkbox to enable/disable parameters, but they are sent anyway.
This happens because we didn’t build the feature, just the UI. :)
**Solution**
With this PR the parameter type is extended to have `enabled: boolean`, by default `enabled` is set to `true` and the client will only sent what’s enabled.

feat: toggle parameters, fix #653

---

.changeset/brave-bobcats-scream.md
examples/api-client-proxy/vite.config.ts
examples/backend/vite.config.ts
examples/echo-server/vite.config.ts
examples/express-api-reference/vite.config.ts
examples/fastify-api-reference/vite.config.ts
examples/hono-api-reference/vite.config.ts
examples/react/vite.config.ts
examples/web/vite.config.ts
packages/api-client-proxy/vite.config.ts
packages/api-client/vite.config.ts
packages/api-reference/package.json
packages/api-reference/src/components/Content/Introduction/ClientSelector.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/ExampleRequest.vue
packages/api-reference/src/helpers/filterClients.ts
packages/api-reference/src/helpers/getAvailableTargets.ts
packages/api-reference/src/helpers/index.ts
packages/api-reference/src/stores/template.ts
packages/api-reference/vite.config.ts
packages/api-reference/vite.standalone.config.ts
packages/echo-server/vite.config.ts
packages/fastify-api-reference/vite.config.ts
packages/swagger-editor/vite.config.ts
packages/swagger-parser/vite.config.ts
pnpm-lock.yaml

This PR adds [our very own @scalar/snippetz library](https://github.com/scalar/snippetz) to generate code examples for undici (Node.js).

feat: add undici example requests

---

.changeset/hip-baboons-play.md
packages/api-reference/src/components/Content/ReferenceEndpoint/ParameterItem.vue
packages/api-reference/src/types.ts

**Problem**
Currently, if there’s a description in the schema we don’t show it in the ParameterItem component.
This happens because the description can be on the parameter level, or in the schema and we forgot to add the one in the schema.
**Solution**
With this PR both fields can be used.
**In the schema**
```diff
{
"schema": {
+    "description": "Page of transactions to load"
},
"name": "page",
"in": "query"
},
```
**In the parameter**
```diff
{
+  "description": "Page of transactions to load",
"schema": {
},
"name": "page",
"in": "query"
},
```

feat: show schema description in parameter item

---

.changeset/dry-days-lick.md
examples/web/src/components/DevToolbar.vue
examples/web/src/main.ts
examples/web/src/pages/ApiReferencePage.vue
examples/web/src/pages/EditableApiReferencePage.vue
examples/web/src/pages/StartPage.vue
packages/api-reference/src/components/Content/Content.vue
packages/api-reference/src/components/Content/Introduction/ClientList.vue
packages/api-reference/src/components/Content/Introduction/ClientSelector.vue
packages/api-reference/src/components/Content/Introduction/Introduction.vue
packages/api-reference/src/components/Section/SectionContainerAccordion.vue

Switches out the introduction layout for the classic layout, going to work on the language picker in another ticket.

feat: classic introduction layout

---

packages/api-reference/src/components/Content/SchemaProperty.vue

**Problem**
Currently we stack overflow on a recursive schema property
This happens because our parser just loops on it (I think)
**Solution**
With this PR we just put a temp cap on recursion level while we sort out a proper fix
To test, throw startons spec into the editor and open the models section
https://docs.starton.com/api-reference
The proper fix would be to test for recursion in the parser and just set the schema name as the type when referencing itself. I will throw up a ticket for this

fix: temp cap on schema level due to stack overflow

---

.changeset/pretty-maps-sniff.md
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/Layouts/ModernLayout.vue
packages/use-toasts/src/FlowToastContainer.vue

**Problem**
app not self contained 
if someone adds padding to the app container it is not containing the apps content 
**Solution**
add position relative to reference content + fix toast layout to left

fix: make layout self contained

---

.changeset/plenty-bees-fly.md
packages/api-reference/src/components/Layouts/ModernLayout.vue

**Problem**
When you click the sidebar on mobile, it doesnt close the sidebar
**Solution**
sidebar closes once activeitem changes

fix: mobile sidebar doesnt close on change item

---

packages/api-client/src/components/ApiClient/Request/RequestCookies.vue
packages/api-client/src/components/ApiClient/Request/RequestHeaders.vue
packages/api-client/src/components/ApiClient/Request/RequestQuery.vue
packages/api-client/src/components/ApiClient/Request/RequestVariables.vue

**Problem**
Currently, you can’t add cookies if the list is empty.
This happens because in some cases `cookies` is undefined and a `push()` to undefined fails. 
**Solution**
With this PR variables, queryStrings, headers and cookies are initialized before we try to use `push()` on it.

fix: does not add cookies

---

packages/hono-api-reference/README.md

**Problem**
Currently, on Scalar Hono API Reference Plugin README, when I click on link `Zod OpenAPI Hono`, it redirects to 404 page.
This happens because `https://hono.dev/guides/openapi` not exist anymore
**Solution**
With this PR, I change the URL from `https://hono.dev/guides/openapi` to `https://github.com/honojs/middleware/tree/main/packages/zod-openapi`

docs: Update Scalar Hono API Reference Plugin README.md on 

---

.changeset/long-spoons-pretend.md
packages/api-reference/src/index.ts

**Problem**
Currently, the @scalar/api-reference helpers aren’t exported.
Maybe this is a good thing, but I just need `openClientFor` outside of the package. A better solution would be to decouple them from the api-reference package and move them to the client …  but this PR is the quickest way to access them.
**Solution**
This PR exposes the helpers and the stores from @scalar/api-reference.

chore: export helpers

---

packages/api-reference/src/components/GettingStarted.vue
packages/components/README.md
packages/components/package.json
packages/components/postcss.config.js
packages/components/src/components/ScalarButton/ScalarButton.stories.ts
packages/components/src/components/ScalarLoading/ScalarLoading.spec.ts
packages/components/src/components/ScalarLoading/ScalarLoading.vue
packages/components/src/components/ScalarModal/ScalarModal.stories.ts
packages/components/src/components/ScalarModal/ScalarModal.vue
packages/components/src/cva.ts
packages/components/src/tailwind/tailwind.css
pnpm-lock.yaml

Prefixes all our classes with [`postcss-prefix-selector`](https://www.npmjs.com/package/postcss-prefix-selector)
Fixes #692

feat: scope all scalar components using a class prefix

---

packages/api-reference/package.json
packages/api-reference/src/components/Badge/Badge.vue
packages/api-reference/src/components/Card/CardContent.vue
packages/api-reference/src/components/Card/CardHeader.vue
packages/api-reference/src/components/Content/Authentication/Authentication.stories.ts
packages/api-reference/src/components/Content/Authentication/Authentication.vue
packages/api-reference/src/components/Content/Authentication/CardForm.vue
packages/api-reference/src/components/Content/Authentication/CardFormButton.vue
packages/api-reference/src/components/Content/Authentication/CardFormGroup.vue
packages/api-reference/src/components/Content/Authentication/CardFormTextInput.vue
packages/api-reference/src/components/Content/Authentication/SecurityScheme.vue
packages/api-reference/src/components/Content/Authentication/SecuritySchemeScopes.vue
packages/api-reference/src/components/Content/Introduction/Introduction.vue
packages/api-reference/src/stores/globalStore.ts
packages/api-reference/src/types.ts
packages/components/src/components/ScalarIcon/ScalarIcon.vue
packages/swagger-editor/src/components/ResetStyles.vue
pnpm-lock.yaml

**Problem**
Currently, there’s no support for OpenAuth 2 authentication.
This flow is way more complex than the others, but let’s start at least with something.
**Solution**
With this PR an basic interface is added to start an Open Auth2 flow, which covers at least the config from the Petstore example.
**Preview**
**Swagger UI**

chore: add an interface to start an OpenAuth2 flow, see #604

---

packages/api-client/src/components/Grid/Grid.vue
packages/api-client/src/types.ts
packages/api-reference/src/helpers/generateParameters.ts

We added support for `required` to parameters, there’s no need to pass a `customClass` anymore. :)

chore: remove customClass attribute from parameters

---

.vscode/extensions.json
.vscode/settings.json

Updates the vscode config and adds some recommended extensions
Fixes #481 
Also sets up Tailwind a bit better for the components lib:

chore: add vscode config

---

.changeset/orange-bulldogs-collect.md
packages/api-client/src/components/ApiClient/Response/ResponseBody.vue

fix: add text plain media type in response body

---

.changeset/chilly-tables-clean.md
packages/api-reference/src/components/Content/Schema.vue
packages/api-reference/src/components/DarkModeToggle.vue
packages/api-reference/src/components/SearchButton.vue
packages/swagger-editor/src/components/SwaggerEditor/HeaderTabButton.vue

fix: declare theme font for buttons and fix regressed font weight

---

packages/api-reference/src/components/Content/ReferenceEndpoint/RequestBody.vue
packages/api-reference/src/petstorev3.json

**Problem**
Currently, the request body of all other content-types are empty except `application/json`
before:
after:
In addition, I have also added `multipart/form-data` example `uploads an image using form data` in the pet
Because v-if only specifies that the body section of application/json can be displayed.
In the requestBody.content, there are content-type keys corresponding to the openapi schema, so we can directly use it to generate a select.
**Solution**
- Add dynamic content type selection for request body display
- Generate select using the key of `requestBody?.content`
- User can view the request body with a specified content-type
- Add an example of `multipart/form-data` in petstore
- Probably related to #705 and #597

feat: Add dynamic content type selection for request body

---

.changeset/clean-years-smash.md
README.md
examples/web/src/components/DevToolbar.vue
packages/api-reference/src/components/ApiReferenceBase.vue
packages/api-reference/src/hooks/useDarkModeState.ts
packages/api-reference/src/types.ts

Fixes #728 :) 
you can now set the light/dark mode through the configuration object. we also might in the future want to disable the toggle for the users who only have one theme :) 
https://github.com/scalar/scalar/assets/6176314/6ed15661-2271-4ba6-8d67-c721a11d67e5

feat: add darkmode as config property

---

.changeset/ninety-pugs-tickle.md
packages/api-client/src/components/ApiClient/Request/RequestBody.vue
packages/use-codemirror/src/components/CodeMirror/CodeMirror.vue
packages/use-codemirror/src/hooks/useCodeMirror.ts

**Problem**
Currently, the request body doesn’t reset when you navigate to a request without a request body (#730).
This happens because I watched for content changes, but ignored `null`/`undefined`/`''`. I can’t remember why I did that, but I think it was just that the `setCodeMirrorContent` helper didn’t support `undefined` or `null`.
**Solution**
With this PR the `setCodeMirrorContent` helper deals with those values and we don’t ignore them anymore.

fix: request body does not reset, fix #730

---

.changeset/few-tools-sleep.md
packages/api-reference/package.json
packages/api-reference/src/components/Content/ReferenceEndpoint/ExampleRequest.vue
packages/api-reference/src/helpers/getAvailableTargets.ts
pnpm-lock.yaml

This PR adds Node `fetch()` and JavaScript `fetch()` (they have the same syntax) examples.

feat: add fetch examples, fix #737

---

.changeset/fair-otters-visit.md
packages/api-reference/src/components/Content/SchemaProperty.vue

fix: add markdown rendering for body schema

---

.changeset/nervous-zoos-fix.md
packages/api-reference/src/components/SearchModal.vue

**Problem**
If you click on a search result from a closed section, it will not get scrolled to.
This happens because the section is not being opened.
**Solution**
With this PR we open the section on click of the search result.

fix(#755): open sections on search click

---

packages/api-reference/README.md

**Problem**
Currently, the API Reference README section header for `hiddenClients` reads `metaObject?: object`
This happens because of a typo
**Solution**
With this PR the API Reference README section header for `hiddenClients` reads `hiddenClients?: list`

docs: Fix typo in API Reference README

---

README.md

before it wasn't exactly clear on how to set the config object inline, i added a simple way of doing so with an additional script tag and setting the data attribute before loading the script. also linked petstore so people can quickly copy and paste to get a working example

chore: expand cdn documentation with simpler config setting

---

.changeset/brown-waves-report.md
packages/echo-server/src/createEchoServer.ts

With this PR the echo server responds with an empty zip file for all request URLs ending with *.zip.
Preparation for #770.

feat: return zip files from echo server, see #770

---

.changeset/six-radios-clean.md
packages/api-client/package.json
packages/api-reference/package.json
pnpm-lock.yaml

This update axios to the latest version, which also updates follow-redirects to 1.15.4. follow-redirects 1.15.4
resolves a security issue: https://nvd.nist.gov/vuln/detail/CVE-2023-26159

chore: update axios

---

.changeset/calm-ghosts-sort.md
packages/api-reference/src/components/SearchModal.vue

With this PR headings from info.description are added to the search index.
See #299

feat: add headings from the description to the search index, fix #299

---

.changeset/flat-turtles-cover.md
packages/api-reference/src/components/Content/Content.vue
packages/api-reference/src/types.ts

We’ve had support for `host` and `schemes`, but not for `basePath`. This PR adds it. The mentioned attributes keywords were used in Swagger 2.0.
Example file: https://petstore.swagger.io/ (Petstore v2)
See #745

fix: basePath (Swagger 2.0) is ignored, fix #745

---

packages/fastify-api-reference/package.json

There was a double entry of `fastify-html`, and those were not in agreement on which version should be installed.

fix: actually update fastify-html

---

.changeset/modern-bugs-accept.md
packages/api-reference/src/components/Content/ReferenceEndpoint/PathResponses/ExampleResponse.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/PathResponses/PathResponses.vue
packages/api-reference/src/components/Content/SchemaProperty.vue
packages/api-reference/src/helpers/getExampleFromSchema.test.ts
packages/api-reference/src/helpers/getExampleFromSchema.ts
packages/api-reference/src/helpers/getParametersFromOperation.ts
packages/api-reference/src/helpers/getRequestBodyFromOperation.ts

Currently, we don’t deal well with readOnly/writeOnly attributes. With this PR:
* they are labeled accordingly in the body attributes table
* readOnly attributes are not part of example requests
* writeOnly attributes are not part of example responses
**Includes id and password, labels for readOnly/writeOnly attributes**
**Includes password (writeOnly)**
**Includes id (readOnly)**

feat: show/hide readOnly/writeOnly attributes in requests/responses, fix #774

---

.changeset/large-kiwis-pretend.md
packages/api-reference/src/components/SidebarElement.vue

Clicking on the chevron of a tag, doesn’t expand/collapse the tag.
This is because handleClick is triggered twice (the button, the parent).
Adding `@click.stop` to prevent the event from bubbling up helps. :)

fix: toggle icon does not toggle, fix #805

---

.changeset/seven-lies-invite.md

Just bumping the fastify-api-reference package to update the api-client dependency, was missed in the last release.

chore: bump fastify-api-reference version to update api-client dependency

---

.changeset/rude-cameras-provide.md
packages/api-reference/src/components/SearchModal.vue

now we can use the enter key to navigate a search result :) just needed to open the tag first ✨

fix: enter key navigating search item

---

.changeset/popular-papayas-kneel.md
packages/api-reference/src/components/SearchModal.vue

When hovering the search results and then pressing the arrow keys, the list of results sticks to where it’s at.
This is because there was an @mouseover listener overwriting the selected item.
See #827

fix: search keyboard navigation doesn’t work when the mouse hovers the results, fix #827

---

.changeset/hot-knives-relax.md
packages/api-reference/src/components/Content/Authentication/SecurityScheme.vue
packages/api-reference/src/components/Content/Authentication/SecuritySchemeSelector.vue
packages/api-reference/src/components/Content/MarkdownRenderer.vue

Currently, we don't show the security scheme key and description as pointed out in https://github.com/scalar/scalar/issues/792.
This PR adds the security schema key in quotes and shows the description (if there’s one).
It’s part of the spec, so we should show it somehow, but I’m not happy with the design. Wdyt @cameronrohani?

feat: show security scheme name and description, fix #792

---

packages/api-reference/src/helpers/getUrlFromServerState.ts

**Problem**
Currently, if your `window.location.origin` doesn't end with a trailing slash and your OpenAPI docs' servers have a leading forward slash, the slash between the URL and the route is removed.
This happens because the fix for doubling up on forward slashes didn't check if there was no forward slash before removing the leading slash from the server.
**Solution**
With this PR there is now a check to see if `window.location.origin` has a trailing slash before removing the leading slash from the server.

fix: Restoring missing forward slash between URL and API routes

---

.changeset/twelve-drinks-decide.md
packages/api-reference/src/helpers/getExampleFromSchema.ts

We’ve added support for `additionalProperties`, but a valid value is `false` - which means there are no additionalProperties … This PR doesn’t add additionalProperties if it’s set to `false. :)

fix: additional properties false is ignored

---

.changeset/little-lies-film.md
packages/api-reference/src/components/Content/Introduction/Description.vue
packages/api-reference/src/components/Content/MarkdownRenderer.vue

This PR adds a `withImages` prop to the MarkdownRenderer. With this PR users can use images in the OpenAPI description field.
Based on @SebastianBienert’s PR #856

feat: description with images, see #842, fix #855

---

.changeset/tall-clouds-protect.md
packages/api-reference/src/components/Content/Schema.vue
packages/api-reference/src/components/Content/SchemaProperty.vue

There was a typo, so we didn’t show `nullable` for properties where it’s set.
And if `anyOf` is used to tell fields are nullable, the rendering is slightly improved.
**Before**
**After**

feat: nullable properties, fix #855

---

.changeset/slimy-pumpkins-retire.md
packages/api-reference/src/components/Content/ReferenceEndpoint/CustomRequestExamples.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/ReferenceEndpoint.vue
packages/api-reference/src/types.ts

This PR adds support for custom request examples.
If it’s configured, we won’t show the generated example requests.
We’re looking for the following keys:
1. `x-custom-examples` (our default)
2. `x-codeSamples` (redocly)
3. `x-code-samples` (redocly, deprecated)
Example: https://sandbox.scalar.com/e/QUbEt

feat: custom request examples

---

.changeset/twenty-cows-jog.md
packages/api-reference/src/helpers/getExampleFromSchema.test.ts
packages/api-reference/src/helpers/getExampleFromSchema.ts

Currently, we use the provided `example` in schemas to generate example payloads/responses. But not anymore! This PR checks if `examples` (with an `s`) is configured, is an array and uses the first example for our example payloads/responses.
See #867
Example: https://sandbox.scalar.com/e/YAy_o

feat: use schema examples, fix #867

---

packages/api-reference/src/components/Content/ReferenceEndpoint/ExampleRequest.vue
packages/api-reference/src/helpers/getApiClientRequest.ts
packages/api-reference/src/helpers/getRequestFromAuthentication.test.ts
packages/api-reference/src/helpers/getRequestFromAuthentication.ts

Currently, we ignore whatever is configured in `security` on the operation level. With this PR, we’ll take the configuration into account.
* When there’s nothing configured, we take the globally configured security schemes.
* When there’s an empty array `[]`, auth is optional and won’t be added to the examples.
* When there’s an array containing an empty object `{}`, auth is optional and won’t be added to the examples.
Read the OpenAPI spec here: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md
I’ve also tested Swagger UI and got the same results.
See #532, #843

feat: operation scoped security, fix #532 fix #843

---

.changeset/angry-crabs-double.md
packages/api-reference/src/components/SidebarElement.vue

This PR improves the styling of the method badge in the sidebar.
* Text doesn’t wrap anymore.
* The size of the badge (width, height, line-height) is configured in em now, so it’s relative to the font size.
* The margin is removed, it’s using `gap` now.
* The badge is set to `overflow: hidden`.
**One thing changed:**
The link and the badge were set to `flex-start`, so they were attached to the top. For long operation names the badge was still on top, I think that was expected.
Unfortunately, this required also to fix the position of the badge for one-line operation names with a `top: 3.5px;` to make it look centered. Which feels very hacky to me, and doesn’t work well with a dynamic (em) size.
That’s why I actually centered it now:
See #871

style: no text wrap for method badges, fix #871

---

.changeset/itchy-rivers-occur.md
packages/api-reference/src/components/Content/ReferenceEndpoint/EndpointDetails.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/ParameterItem.vue
packages/api-reference/src/components/Content/SchemaProperty.vue

We have this powerful `Schema` component to render schemas, but that wasn’t really used for parameters (except for objects).
With this PR it’s used for the parameters aswell. And I’ve added support for minLength, maxLength and pattern.
Schemas are complex and allow a ton of features, we’re still not 100 % feature complete, but we’re getting there … ✨
See #862

feat: better schema support for parameters, fix #862

---

.changeset/silver-actors-wonder.md
packages/api-reference/src/components/ApiReferenceBase.vue

Fixes setting the example spec on mobile.
1. To test shrink the screen to mobile size and open the [editable references](http://localhost:5050/editable-api-reference)
2. hit getting started then one of the example specs
3. they should fill the content now
Test this on main and it does not work, because `ModernLayout` doesn't do anything with the `updateContent` event
@marclave double checked and setting the rawSpec triggers a watcher which updatesContent so its safe
```ts
watch(rawSpecRef, () => {
emit('updateContent', rawSpecRef.value)
})
```

fix: example spec on mobile

---

.changeset/angry-mayflies-add.md
packages/api-reference/src/components/Content/MarkdownRenderer.vue

**Problem**
Currently, tables do not respect markdown column alignment.
This happens because align key is deprecated & some browsers potentially ignore it now. You also use `text-align: left`, but disabling that doesn't fix it so I'm not 100% sure.
**Solution**
With this PR, I add explicit column alignment rules.
Note on implementation - its not a particularly graceful solution, if loops were available with something like sass or less, or if [attr](https://developer.mozilla.org/en-US/docs/Web/CSS/attr) was [supported by browsers](https://caniuse.com/css3-attr), that would be nicer but its not a huge deal.

fix: add explicit table alignment rules

---

.github/workflows/ci.yml
.github/workflows/release.yml
packages/api-reference/package.json
packages/api-reference/vite.config.ts
pnpm-lock.yaml

Relative CI does “In-depth bundle analysis and monitoring” and could help us to keep an eye on our bundle size.
More and more users install our packages, and their users probably download the bundle probably a million times already. I think we should be careful with adding more dependencies, and should actively look for ways to reduce the bundle size.
Once the integration works, there are a few possibilities. I’m mostly looking forward to an automated PR comments with the bundle size changes. What I’ve configured for testing purposes:
* New dependencies require approval
* Duplicate dependencies, require approval.
* If the bundle grows by more than 10 kb, require approval.
* If the bundle grows by more than 2 %, the GitHub check will fail.
* If the bundle grows by less than 2 %, or even …

chore: add Relative CI to monitor the bundle size

---

.changeset/forty-garlics-exist.md
packages/api-reference/src/components/SearchModal.vue

This PR disables autocomplete, autocorrect, autocapitalize and spellcheck for the search input.
IMHO those smart features aren’t very helpful when searching in a technical reference.
See #885

fix: autocomplete for search input, fix #885

---

.changeset/slimy-paws-confess.md
packages/api-reference/src/components/Content/ReferenceEndpoint/PathResponses/ExampleResponse.vue

There was a typo within the example responses. This PR fixes it. :)
For more context, see #894.

fix: response examples with a single value do not render, fix #894

---

.changeset/late-emus-fry.md
packages/api-client/src/components/ApiClient/Request/RequestBody.vue
packages/api-client/src/components/ApiClient/Request/RequestCookies.vue
packages/api-client/src/components/ApiClient/Request/RequestHeaders.vue
packages/api-client/src/components/ApiClient/Request/RequestQuery.vue
packages/api-client/src/components/ApiClient/Request/RequestVariables.vue
packages/api-client/src/components/CollapsibleSection/CollapsibleSection.vue

**Problem**
We always show all collapsed sections even if there's no content, this can add visual clutter
https://github.com/scalar/scalar/assets/6176314/df23e939-74b8-4b9a-ad97-a0d07083105a
We don't check to see the content in the section
**Solution**
We watch to see the active request, i had to do some magic with the headlessui component. but you can't have too much magic ✨ 
We might want to have a slight placeholder to show that there's nothing in the section (i.e. No Variables)
https://github.com/scalar/scalar/assets/6176314/0ecf52b1-512a-43f7-bb09-019c6689e667

feat: add default state for api client collapsed panels

---

.changeset/moody-snails-jog.md
packages/api-reference/src/components/Content/ReferenceEndpoint/CustomRequestExamples.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/ExampleRequest.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/ReferenceEndpoint.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/TextSelect.vue

This PR improves the custom example component:
* Show path
* Show Try Request button
* Add a generic TextSelect and use it for the generated request and the custom request component
* When there’s a single entry only, just show the text
See #899, #870
Example: https://sandbox.scalar.com/e/QUbEt#tag/default/post/foobar

feat: improve custom example block, fix #899

---

.changeset/mighty-rockets-watch.md
packages/use-codemirror/src/components/CodeMirror/CodeMirror.vue

Mobile safari is cursed
https://stackoverflow.com/questions/5303263/fix-font-size-issue-on-mobile-safari-iphone-where-text-is-rendered-inconsisten

fix: don't scale codemirror text on mobile webkit

---

.changeset/tame-buses-warn.md
packages/api-reference/src/components/Content/ReferenceEndpoint/PathResponses/PathResponses.vue

Currently, we ignore the Swagger 2.0 response body. This PR fixes it.
See #912

fix: swagger 2.0 response body isn’t shown

---

packages/fastify-api-reference/src/fastifyApiReference.ts

**Problem**
Currently, the warning message is not grammatically correct.
This happens because... 🤷 
**Solution**
With this PR, the grammar is corrected.

chore(fastifyApiReference): grammar fixes in warning message

---

.changeset/good-chefs-repeat.md
packages/nextjs-api-reference/package.json

There was a typo (single pipe vs. double pipe) in the Next.js version requirement. Let’s fix this quickly!

fix: typo in Next.js version requirement, fix #938

---

.changeset/hungry-masks-grow.md
packages/api-reference/src/components/Section/Section.vue

**Problem**
Tags will auto-open as you scroll down
**Solution**
With this PR we remove that auto-open. Maybe we can add it as an option down the road when we fix performance.

fix: remove auto open tags on scroll

---

.changeset/hip-waves-watch.md
packages/api-reference/src/components/Content/ReferenceEndpoint/CustomRequestExamples.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/ExamplePicker.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/ExampleRequest.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/PathResponses/ExampleResponse.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/PathResponses/PathResponses.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/SelectExample.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/TextSelect.vue
packages/api-reference/src/helpers/getRequestBodyFromOperation.test.ts
packages/api-reference/src/helpers/getRequestBodyFromOperation.ts
packages/api-reference/src/helpers/getRequestFromOperation.ts
packages/api-reference/src/types.ts

See #764.
With this PR provided example request and responses are used for the code snippets and the example response card.
If you provide multiple examples, you’ll get a select. Here’s the full version:
Has some CSS issues, which are resolved in #810.

feat: use request and response examples, see #764

---

.changeset/eighty-ravens-mate.md
packages/api-reference/src/components/Content/ReferenceEndpoint/ReferenceEndpointAccordion.vue

fix: shrink label and not actions on mobile

---

.github/workflows/deploy-examples.yml
.github/workflows/deploy-preview-examples.yml

This PR adds a new CI workflow to create a draft deployment to Netlify when a PR contains changes to the examples site. The changes can be tested in a real deployed environment and reviewers do not need to run a local environment. 
The workflow adds the deploy preview url as a comment on the PR
This PR also renames the existing `deploy-preview` to `deploy-examples` for a clear distinction between the deploy preview and the prod deploy of the static examples site.

feat: deploy preview

---

.changeset/sour-brooms-kick.md
packages/api-client/src/components/ApiClient/ApiClient.vue
packages/api-client/src/components/HttpMethod.vue
packages/api-client/src/fixtures/httpRequestMethods.ts
packages/api-client/src/helpers/normalizeRequestMethod.ts
packages/api-client/src/index.ts
packages/api-reference/src/components/Content/EndpointsOverview.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/CustomRequestExamples.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/ExampleRequest.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/ReferenceEndpointAccordion.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/TryRequestButton.vue
packages/api-reference/src/components/SearchModal.vue
packages/api-reference/src/components/SidebarElement.vue

Creates an `HttpMethod` component which can be used to display a color coded http method label, badge or button (or whatever). Also makes is so we can render all basic http methods including `GET`, `POST`, `PUT`, `HEAD`, `DELETE`, `PATCH`, `OPTIONS`, `CONNECT` and `TRACE`.
fixes #935

feat: update components to support all basic http request methods

---

.github/workflows/deploy-examples.yml
.github/workflows/deploy-preview-examples.yml
examples/web/src/pages/ApiClientPage.vue

With this PR the deploy preview workflow will trigger on PR open as well as on push if there are changes to the UI. This PR also clarifies workflow naming, adds a header to the deploy preview comment and explicitly adds permissions although this may be unnecessary for a public repo.

fix: deploy preview workflow triggers

---

.changeset/blue-tomatoes-tan.md
.changeset/rare-moons-run.md
examples/web/src/components/DevApiClientOptions.vue
examples/web/src/components/DevReferencesOptions.vue
examples/web/src/components/DevToolbar.vue
examples/web/src/pages/ApiClientPage.vue
examples/web/src/pages/ApiReferencePage.vue
packages/api-client-proxy/src/createApiClientProxy.ts
packages/api-client/src/helpers/sendRequest.ts

This PR does 3 things:
1. Updates `sendRequest` to still parse the data correctly when Axios throws an error for a non-200 status code
2. Updates the client proxy's `Access-Control-Expose-Headers` header to only include our special scalar proxy headers rather than exposing everything (which was showing a bunch of weird headers).
3. Adds a dev toolbar to the api client dev environment to make it easier to test
fixes #939
https://github.com/scalar/scalar/assets/6374090/cf90d527-b22f-4d17-8073-52d55677d334
https://github.com/scalar/scalar/assets/6374090/4ed54f7f-e3df-487c-96aa-f07a98b0560f

fix: parse axios error responses as blobs

---

.changeset/ten-adults-film.md
packages/api-reference/src/components/SearchButton.vue

This is a span within a button so it shouldn't really have a type attribute regardless.
I'm guessing it was left there from a time when the search input was an actual input instead of a button that opened the modal.

fix: remove type="text" from the search button placeholder span

---

.github/workflows/ci.yml
.vscode/extensions.json
.vscode/settings.json
package.json
packages/components/src/components/ScalarModal/ScalarModal.spec.ts
packages/swagger-parser/src/helpers/parse.test.ts
pnpm-lock.yaml
turbo.json
vitest.workspace.ts

I just found out that vitest has a “workspaces” feature, which we could use to run the tests. The output is better than the output of `pnpm -r test`.
But one test is failing and I don’t get why. 🤔 I think the expected output isn’t really related to the test, though:
```diff
expect(wrapper.html()).toBe(
-      `
-
<div style="position: fixed; height: 0px; padding: 0px; overflow: hidden; clip: rect(0px, 0px, 0px, 0px); white-space: nowrap; border-width: 0px; display: none;"></div>`,
)
```

chore: use vitest workspaces

---

.changeset/kind-lamps-brake.md
examples/web/src/pages/ApiReferencePage.vue
packages/api-reference/README.md
packages/api-reference/src/components/ApiReferenceBase.vue
packages/api-reference/src/components/Content/Authentication/SecuritySchemeSelector.vue
packages/api-reference/src/helpers/getRequestFromAuthentication.test.ts
packages/api-reference/src/helpers/getRequestFromAuthentication.ts
packages/api-reference/src/types.ts

With this PR the authentication data can be prefilled through the universal configuration object.
```vue
<ApiReference :configuration="{
authentication: {
// The OpenAPI file has keys for all security schemes
// Which one should be used by default?
securitySchemeKey: 'petstore_auth',
// Okay, the `api_key` security scheme is of type `oAuth2`, so prefill the client id and the scopes:
oAuth2: {
clientId: 'foobar123',
// optional:
scopes: ['read:pets', 'write:pets'],
},
},
} />
````
See #984.

feat: prefill authentication, fix #984 

---

.changeset/proud-spoons-decide.md
packages/api-reference/src/helpers/getUrlFromServerState.test.ts
packages/api-reference/src/helpers/getUrlFromServerState.ts

When using
```json
{ "servers": [{ "url": "v1" }] }
```
the path should be prefixed with the `window.location.origin`, but it’s not. :) Let’s change it with this PR.
Read more in #937

fix: path is not prefixed, fix #937

---

examples/express-api-reference/src/index.ts

I was just looking for TODO comments in the code base and saw that we served a `swagger.json` in the express example, but didn’t even use it.
I consider serving an OpenAPI file best practice, so I did that and removed the TODO comment.

chore: serve OpenAPI file for express example

---

.changeset/modern-rats-lay.md
packages/api-client/src/components/ApiClient/AddressBar.vue
packages/api-client/src/components/ApiClient/RequestHistoryItem.vue
packages/use-codemirror/src/components/CodeMirror/CodeMirror.vue
packages/use-codemirror/src/hooks/variables.ts

This PR:
* removes unused CSS from the CodeMirror component
* moves CSS for the API client address bar to the address bar component
* scopes the remaining CSS

chore: clean up CodeMirror CSS

---

.github/workflows/deploy-preview-examples.yml

This PR updates the workflow triggers so deploy previews are created when there are changes to `packages/api-client` and `packages/api-reference`

chore: update deploy preview triggers

---

.changeset/itchy-spies-vanish.md
packages/api-reference/src/components/Content/Operation/CustomRequestExamples.vue

fix: wrap request HTTP type in url

---

.changeset/honest-students-cough.md
packages/api-client/src/components/ApiClient/ApiClient.vue
packages/api-client/src/components/ApiClient/Request/Request.vue
packages/api-client/src/components/ApiClient/Request/RequestBody.vue

The code was already there just the class got removed from the codemirror element

fix: set max height on request body codemirror

---

.changeset/green-badgers-swim.md
packages/api-reference/src/components/Card/CardTabHeader.vue
packages/api-reference/src/components/Content/Operation/PathResponses/PathResponses.vue

fix: tab overflow hidden

---

packages/api-reference/src/components/CodeBlock/CodeBlock.vue

Unfortunately, `prismjs` is CommonJS. This causes some issues in ESM projects requiring @scalar/api-reference:
```
import { plugins as Iw, highlightElement as jm } from "prismjs";
^^^^^^^
SyntaxError: Named export 'plugins' not found. The requested module 'prismjs' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
import pkg from 'prismjs';
const { plugins: Iw, highlightElement: jm } = pkg;
```
This PR adds the suggested fix. Let’s see if this helps. :)

fix: named exports fail in ESM

---

.changeset/ten-timers-itch.md
packages/api-reference/src/helpers/getUrlFromServerState.test.ts
packages/api-reference/src/helpers/getUrlFromServerState.ts

If an URL uses a variable instead of a static protocol (`{protocol}` vs. `http/https`), the URL is prefixed with the window.location.origin. 
This PR fixes it.
The variables are replaced first, and only then we’ll check whether it’s an absolute URL.

fix: urls with dynamic protocol are prefixed with the window location origin, fix #1035

---

.changeset/thirty-keys-tap.md
packages/api-reference/src/components/ApiReferenceBase.vue

Oops, at some point we lost the code to call a configured `onSpecUpdate` function. Let’s fix this quickly!

fix: `onSpecUpdate` isn’t called, fix #1021

---

.changeset/lucky-lobsters-cry.md
examples/web/src/pages/ApiReferencePage.vue
packages/api-reference/src/helpers/getRequestFromAuthentication.test.ts
packages/api-reference/src/helpers/getRequestFromAuthentication.ts

For basic auth we’re encoding username and password, even if both are empty. Instead of `hans:test123` the string that we encode is then just `:`.
With this PR the token is omitted if we don’t have credentials.
It’s totally valid to send just the username or just the pasword, so we’re still showing a token for `:test123` or `hans:`.

fix: basic auth shows encoded colon string, fix #1026

---

.vscode/extensions.json

The recommended vitest extension is deprecated, let’s recommend the successor. :)
https://marketplace.visualstudio.com/items?itemName=ZixuanChen.vitest-explorer

chore: recommend official vitest extension

---

.changeset/cyan-radios-invent.md
packages/fastify-api-reference/src/fastifyApiReference.test.ts
packages/fastify-api-reference/src/fastifyApiReference.ts
packages/fastify-api-reference/src/utils/getJavaScriptFile.ts

Currently, our Fastify package can’t be used in ESM envs, because I removed the node shim for `__dirname`. This PR adds a fix based on #1043 by @markusgeert.
Unfortunately, I can’t reproduce the issue _inside the dev env_ so I’m kind of blind. Let’s cross fingers this works, I’ll test it once released. 🤞

fix: fastify ESM __dirname undefined, fix #1042

---

.github/workflows/ci.yml
.github/workflows/release.yml
packages/api-reference/vite.config.ts
packages/api-reference/vite.standalone.config.ts

Currently, we’re monitoring the bundle size of the ESM build. But we’re actually more interested in the CDN/standalone build, that has **everything** included.
With this PR we’re switching to monitor the CDN/standalone build instead (which is way larger BTW).

chore: monitor CDN/standalone bundlesize (instead of ESM build)

---

packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/Content/ClientLibraries/ClientSelector.vue

change max width to 1540px for refs
change breakpoints + sizes of default theme client library icons
After:
Before:

fix: max width size and client width breakpoint & sizes

---

.changeset/lemon-waves-enjoy.md
packages/hono-api-reference/package.json

**Problem**
Only hono@v3 is specified in the peerDependencies of @scalar/hono-api-reference
**Solution**
With this PR, hono@v4 is allowed as well.

chore: allow hono@v4 as peerDependency

---

.changeset/seven-balloons-shave.md
packages/api-reference/src/components/Content/Operation/PathResponses/PathResponses.vue

Currently, when you add an encoding to the content type of the example responses, they are not shown anymore. See #920.
This PR fixes exactly this (but not more). There is probably a better solution to get “any json content type” from the object, but let’s add this pragmatic fix for now.

fix: example response with content encoding is not shown, fix #920

---

.changeset/sweet-buckets-exist.md
packages/use-codemirror/src/hooks/useCodeMirror.ts

Select all doesn’t work in CodeMirror. We’ve had a fix, I removed it in https://github.com/scalar/scalar/commit/3d712d7464894a07ee91f62416ec1ef3251a60ff and this PR adds it again. 🤡

fix: select all does not work

---

.changeset/cold-timers-remember.md
packages/api-client/src/components/ApiClient/Request/Request.vue
packages/api-client/src/components/ApiClient/Response/ResponseBody.vue

Noticed a little issue with the api-client since switching to prismjs. This PR sets a max height + little border so it matches the look of codemirror.
Before:
After:

style: set scroll and border on response body

---

.changeset/quiet-plants-ring.md
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue

fix: https://github.com/scalar/scalar/discussions/1049
Currently, when defining a `Record` as part of a request body it is possible to infinitely show child attributes.
https://github.com/scalar/scalar/assets/42624869/05b35afb-5e00-49af-9523-78fb6b2f60a7
This happens because the `SchemaProperty` component does not check if the current value is an object before rendering a child `Schema` component. 
With this PR the `SchemaProperty` is changed to only render a child schema when the current value is an object.
https://github.com/scalar/scalar/assets/42624869/f4cac496-8716-4d7e-a1c6-598bd48d3e0e

fix: stop rendering infinite child attributes

---

.changeset/green-rocks-relax.md
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue

Currently, we don’t show any indication when schema attributes are marked as deprecated. See #1052
With this PR a “deprecated“ badge is added (the same badge we use for deprecated paths) and I’ve added diagonal lines to the background. @cameronrohani Wdyt? I bet you’ll come up with something better, feel free to add to the PR.

feat: show deprecated badge for schema attributes, fix #1052

---

.prettierrc
examples/api-client-proxy/vite.config.ts
examples/echo-server/vite.config.ts
examples/express-api-reference/vite.config.ts
examples/fastify-api-reference/vite.config.ts
examples/hono-api-reference/vite.config.ts
examples/nextjs-api-reference/tsconfig.json
examples/react/vite.config.ts
examples/web/vite.config.ts
packages/api-client-proxy/vite.config.ts
packages/api-client/vite.config.ts
packages/api-reference/vite.config.ts
packages/api-reference/vite.standalone.config.ts
packages/components/.prettierrc
packages/components/.storybook/preview.ts
packages/components/src/components/ScalarButton/ScalarButton.vue
packages/components/src/components/ScalarButton/variants.ts
packages/components/src/components/ScalarIcon/ScalarIcon.vue
packages/components/src/components/ScalarIconButton/ScalarIconButton.vue
packages/components/src/components/ScalarLoading/ScalarLoading.vue
packages/components/src/components/ScalarModal/ScalarModal.vue
packages/components/src/components/ScalarTextField/ScalarTextField.vue
packages/components/src/index.ts
packages/components/tsconfig.json
packages/components/vite.config.ts
packages/echo-server/vite.config.ts
packages/fastify-api-reference/vite.config.ts
packages/swagger-editor/vite.config.ts
packages/swagger-parser/vite.config.ts

Currently, we import the source files for all @scalar dependencies. I mean that’s why we’re doing the monorepo thing, to have all in the same place and have a short dev cycle.
However, we made an exemption for @scalar/components and only included the build. If you want to see changes to @scalar/components in @scalar/api-reference you have to make a build.
And the only reason we did this, was the aliases. We once removed all aliases from all packages to avoid the trouble. With the current setup, if you import a source file from another package, the alias can’t be resolved. Because the Vite config isn’t read then.
This PR removes the alias from the components package and removes the exemption. Means, we have cross-package HMR for the components now. :)

chore: remove alias from components package

---

.changeset/selfish-pets-live.md
packages/swagger-editor/src/components/SwaggerEditor/SwaggerEditorInput.vue
packages/use-codemirror/package.json
packages/use-codemirror/src/hooks/useCodeMirror.ts
packages/use-codemirror/src/themes/index.ts
packages/use-codemirror/src/types.ts
pnpm-lock.yaml

For some reason the ::selection does not seem to accept our .dark-mode, .light-mode variables. For now we will hard code a color. 
This also adds syntax highlighting back in.

feat: Add codemirror syntax highlighting back in and move to a static color

---

.changeset/fuzzy-dolphins-try.md
packages/api-client/src/components/Grid/Grid.vue
packages/api-reference/src/components/Content/Authentication/SecurityScheme.vue
packages/api-reference/src/components/Content/Operation/ExampleRequest.vue
packages/api-reference/src/helpers/getRequestFromAuthentication.ts
packages/components/src/components/ScalarCodeBlock/ScalarCodeBlock.stories.ts
packages/components/src/components/ScalarCodeBlock/ScalarCodeBlock.vue

Currently, we’re showing all tokens/passwords/keys in plain text. See #1062.
With this PR:
* the relevant inputs become password fields
* the secret credentials are hidden in the code blocks (but still there if you copy the content)
The current approach has one downside. If someone passes "curl" or just a single letter as a token, all those are hidden in the example. The passed strings are considered secret and whenever they appear in the code block they are hidden.
But they are still visible in the API client. We could hide the `Authorization` header value always, but not everyone uses the `Authorization` header. They are plenty of alternatives (cookies, URL, other header names …).
So we could pass the credentials and just match them, but what if you change the credentials in the API …

feat: hide secret credentials, fix #1062

---

.changeset/ten-oranges-yell.md
packages/api-reference/src/components/Sidebar/SidebarElement.vue

With [the recent sidebar refactor](https://github.com/scalar/scalar/pull/1059) (changed `span` to `p`) we’ve introduced a tiny regression: deprecated operations aren't striked through in the sidebar anymore.
This PR fixes it. :)
**Example**
```json
{
"info": {
},
"paths": {
"/foobar": {
"post": {
"deprecated": true
}
}
}
}
```

fix: deprecated operations are not striked through, fix #1104

---

.changeset/strong-lobsters-juggle.md
packages/api-reference/src/components/ApiReferenceBase.vue
packages/api-reference/src/hooks/useSpec.ts

I noticed that the content wasn’t restored from local storage in dev. Turns out `configuration.spec` wasn’t reactive anymore, changes to it didn’t have any effect.
I traveled through the Git history to find out when this was introduced and it seems it was introduced with #1079, though I don't see any related change. Maybe a race condition?
Anyway, I think this PR fixes it. I’ve added a watcher for the spec configuration and added a helper method to `useSpec` to manually update the passed configuration.
I feel every watcher is introducing another problem, so I’d be open for an alternative solution that doesn’t involve a watcher. 👍

fix: content not reactive

---

packages/api-reference/src/components/Content/ClientLibraries/ClientSelector.vue

Need to change client library icons to their respective colours for a users theme 
so now you'll be able to do the following easily:
before:
after:

fix: change client library colours to be variables

---

.changeset/friendly-goats-begin.md
README.md
packages/api-reference/README.md
packages/api-reference/src/components/ApiReferenceBase.vue
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/types.ts

Once upon a time, I thought we could provide a variant of @scalar/api-reference without a parser. I thought we could just parse the specification once and pass it, to remove the parser from the package and decrease the bundle size.
Unfortunately, that’s not as easy as a I thought. There’s no way to just JSON.stringify the result of the parser, because circular references can’t be stringified.
I mean, we could kind of come up with our own format and add a light-weight parser to restore from that custom format, but that’s out of scope for now.
I don’t think anyone used the preparsed content, there was no benefit in doing it. So I’ve just removed it (without deprecating it).

chore: remove preparsed content configuration

---

.changeset/unlucky-moles-develop.md
packages/themes/src/base.css
packages/themes/src/presets/default.css

fix  #1125 
Currently, using the default theme and light mode, the request client selector options are not really readable, since the text color is dark.
This happens because the request example card always uses the `dark mode`. However, when the light mode is active, its default theme colors override the theme colors from dark mode.
With this PR, when light mode is active, the `dark color scheme`  is considered for every component that references the dark-mode CSS class.
> 🚨 I am not totally sure if this is the best approach. However, I believe that it solves the problem without regressions

fix: define color-scheme to improve request client selector readability

---

.changeset/weak-moose-clean.md
examples/cdn-api-reference/package.json
examples/fastify-api-reference/package.json
examples/nestjs-api-reference-express/package.json
examples/nestjs-api-reference-fastify/package.json
examples/nextjs-api-reference/package.json
examples/react/package.json
examples/ssg/package.json
examples/web/package.json
package.json
packages/api-client-proxy/package.json
packages/components/package.json
packages/echo-server/package.json
packages/fastify-api-reference/package.json
packages/swagger-parser/package.json
pnpm-lock.yaml

[TypeScript 5.4 is out](https://devblogs.microsoft.com/typescript/announcing-typescript-5-4/) … so let’s update, we were still on 5.2. :)
Not really necessary I guess, but it TS is failing for me every now and then (Reload VS Code FTW), so I just thought that might help.

chore: update to typescript 5.4

---

.changeset/big-walls-raise.md
packages/api-reference/src/components/Section/SectionContainer.vue

fix: duplicate border top

---

.changeset/tidy-oranges-cry.md
packages/api-reference/src/components/Content/Operation/EndpointPath.vue
packages/api-reference/src/components/Content/Operation/Operation.vue
packages/api-reference/src/components/Content/Operation/OperationAccordion.vue

now we have deprecated strike through for classic layout :)

fix: add deprecated path to classic layout

---

.github/workflows/test-ui.yml

**Problem**
Currently, the CDN UI test runs on `push:` so when there are changes in a feature branch, the test fails. 
This happens because this is a test for the live CDN and changes are not propagated here from feature branches. 
**Solution**
Only run this test on the cron schedule, not for feature branch changes. Testing on the local branch coming soon...

fix: only run cdn ci test on cron schedule

---

.changeset/wicked-jeans-rush.md
packages/api-reference/src/components/ClassicHeader.vue
packages/api-reference/src/components/Content/Content.vue
packages/api-reference/src/components/Content/Operation/OperationAccordion.vue
packages/api-reference/src/components/Section/Section.vue
packages/api-reference/src/components/Section/SectionColumn.vue
packages/api-reference/src/components/Section/SectionColumns.vue
packages/api-reference/src/components/Section/SectionContainer.vue
packages/api-reference/src/components/Section/SectionContainerAccordion.vue
packages/api-reference/src/components/Section/SectionContent.vue
packages/api-reference/src/components/ShowMoreButton.vue
packages/docusaurus/src/theme.css

Fixes docusaurus as well as sentry errors. Also replaces JS with css which is always ⚜️

style: replace resize observer with container query

---

packages/express-api-reference/README.md
packages/express-api-reference/src/expressApiReference.ts
packages/express-api-reference/test/index.test.ts
packages/hono-api-reference/README.md
packages/hono-api-reference/src/honoApiReference.test.ts
packages/hono-api-reference/src/honoApiReference.ts
packages/nestjs-api-reference/README.md
packages/nestjs-api-reference/src/nestJSApiReference.ts
packages/nestjs-api-reference/test/index.test.ts

**Problem**
The api-reference dependency may be inaccessible in other countries (e.g. China), preventing the page from rendering
Certain countries have banned certain domain names
**Solution**
Provide custom cdn options，e.g. https://fastly.jsdelivr.net/npm/@scalar/api-reference

feat: add custom CDN

---

.changeset/four-sloths-nail.md
package.json
packages/components/package.json

The cjs exports had an incorrect umd.cjs extension in the components package.

fix: component cjs export

---

.changeset/gentle-suns-tan.md
packages/themes/src/presets/bluePlanet.css
packages/themes/src/presets/mars.css

mars and blue planet need none transparent backgrounds with the theme updates

fix: mobile backgrounds for mars and blueplanet

---

.changeset/pretty-tigers-remember.md
packages/api-reference/src/helpers/getExampleFromSchema.test.ts
packages/api-reference/src/helpers/getExampleFromSchema.ts

We generate examples from schemas in a lot of places and there was a case we didn’t cover: anyOf, allOf, oneOf schemas inside of array items. 
This PR adds this.
See #1180

fix: example for array with anyOf, allOf, oneOf schemas doesn’t have a value, fix #1180

---

.github/workflows/test-api-reference-cdn.yml
tests/cdn.spec.ts

Currently, snapshot testing is failing due to differences between local and CI environment. More info here https://github.com/scalar/scalar/pull/1177

chore: revert snapshot testing

---

.changeset/happy-doors-walk.md
packages/api-reference/src/components/ApiReferenceLayout.vue

fix: add min height to classic layout

---

.changeset/angry-coats-care.md
README.md
examples/cdn-api-reference/src/public/api-reference-cdn-live.html
examples/cdn-api-reference/src/public/api-reference-cdn-localhost.html
examples/react/src/index.css
examples/react/src/main.tsx
examples/ssg/src/main.ts
examples/ssg/src/style.css
packages/api-reference/index.html
packages/express-api-reference/src/expressApiReference.ts
packages/fastify-api-reference/src/fastifyApiReference.ts
packages/hono-api-reference/src/honoApiReference.ts
packages/nestjs-api-reference/src/nestJSApiReference.ts
packages/nextjs-api-reference/src/ApiReference.ts

This PR removes `body { margin: 0 }` everywhere. It’s not needed anymore, we have this in `ApiReference.vue` now. :)
Makes the CDN example in the root README shorter. 🌟

chore: remove body margin reset everywhere, fix #1172

---

.changeset/lazy-dolphins-grow.md
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue

**Problem**
The enum definition under 'items' was omitted in the provided YAML specification. Below is a simple spec to test out:
```yaml
openapi: 3.1.0
info:
title: Enum Test
version: 0.0.1
paths:
/api:
post:
operationId: TestEnumUnderItems
summary: Test Enum Under Items
requestBody:
content:
application/json:
schema:
type: object
properties:
field_with_enum:
type: array
items:
type: string
enum:
- dog
- cat
- duck
```
The OpenAPI specification does not clearly state how enums should be handled under 'items'. However, based on my experience with other popular API documentation tools like Redocly and Element, I believe this is a potential oversight in how scalar renders the schema.
**Solution**
I tried to obtain the enumeration from both the property's value and 'items' if …

fix: enum under items is not being displayed

---

.changeset/plenty-brooms-admire.md
packages/api-reference/src/helpers/getExampleFromSchema.test.ts
packages/api-reference/src/helpers/getExampleFromSchema.ts

**Problem**
We generate examples from schemas in a lot of places and there was a case we didn’t cover: object schemas with top level anyOf, allOf, oneOf.
**Solution**
With this PR getExampleFromSchema can not handle the above properly.
See https://github.com/scalar/scalar/issues/1180.

fix: example for object with anyOf, allOf, oneOf schemas doesn’t have a value

---

.changeset/few-bottles-run.md
packages/api-reference/src/helpers/getRequestBodyFromOperation.test.ts
packages/api-reference/src/helpers/getRequestBodyFromOperation.ts

Currently, we use provided `examples`, but not `example` to prefill the API client. This PR fixes the issue that we had here.
**Example**
```json
{
"info": {
"version": "1.0"
},
"paths": {
"/api/v1/content/_media": {
"post": {
"responses": {
"default": {
"description": "default"
}
},
"content": {
"example": {
"id": "_media-698d20aa-193a-47b3-be4d-550c1aab47e7",
"fileName": "example.png"
}
}
}
}
}
}
}
}
```

fix: requestBody example is not used

---

packages/fastify-api-reference/src/fastifyApiReference.test.ts
packages/fastify-api-reference/src/fastifyApiReference.ts

**Problem**
In case Fastify is deployed at a non-root path, the initial HTML will incorrectly link the main JavaScript, causing the application to break.
The script's src is missing an optional web root variable. I've set up a proxy to Fastify at this URL: http://domain.example/something/. When I deploy Scalar Fastify in a production environment with the "docs" prefix, the main JavaScript fails to load from the correct location, leading to a blank page, even though the Fastify route to "docs" is correct.
HTML at http://domain.example/something/docs/ loads fine with a 200 OK response.
The JS file at http://domain.example/docs/@scalar/fastify-api-reference/js/browser.js is not found, resulting in a 404 error.
**Solution**
Add an optional webRoot variable in the …

fix: fastify api reference doesn’t load JS on proxied/prefixed routes

---

LICENSE

Welcome to the most important PR of the day/month/year/century? It just struck me last night, that we still have 2023 in there. :)

chore: update license year to say 2023-present

---

examples/web/src/components/DevReferencesOptions.vue

The dev toolbar still had options for collaborative editing, but all the Yjs stuff was removed a while ago, so we can safely remove this. Simplifies the code of the dev toolbar. :)

chore: remove collaborative editing logic from developer toolbar

---

.changeset/twelve-cobras-marry.md
packages/cli/src/commands/reference/ReferenceCommand.ts
packages/cli/src/utils/loadOpenApiFile.ts

Currently, the file watch (e.g. `scalar reference openapi.json --watch`) exits when the specification is invalid.
With this PR it’ll show a warning, but keeps running. Easier for local tinkering. :)
Not perfect, need to add this to more commands, but better than what we had and I’m focused on sth. else rn.

fix: cli watcher exists when specification is invalid

---

.changeset/heavy-hairs-attack.md
packages/cli/src/utils/watchFile.ts

Currently, the CLI watches for changes in process.cwd. If the file is somewhere else, file changes aren’t detected.
With this PR we’re watching the directory where the OpenAPI specification is located instead.

fix: cli does not watch files outside of cwd

---

examples/nextjs-api-reference/package.json
examples/web/src/pages/StartPage.vue

I don’t know how this happened, but I used one port twice (proxy + nextjs). This PR moves the Nextjs example to another port. :)

fix: nextjs example port blocked

---

.changeset/silent-apes-serve.md
packages/api-reference/src/components/MarkdownRenderer/MarkdownRenderer.vue

The Markdown tables needed some love!
Columns with few content are huge, though. But when we remove `table-layout: fixed;` small columns get crammed. @cameronrohani any CSS magic, that we can apply here?
**Before**
* every word breaks
* font size too high
* line height too small
**After**
* scroll if content is too wide
* smaller font size
* bigger line height

style: improve text in markdown tables

---

.changeset/big-news-begin.md
packages/cli/src/utils/loadOpenApiFile.ts

Currently, the CLI only shows "specification invalid" without further information.
With this PR the CLI outputs warnings on the console. The error messages aren’t that good and need some love, but at least it’s a hint.

feat: show warnings for invalid specifications

---

.changeset/modern-fishes-shout.md
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue

In the recent OpenAPI version, you can set `type` to an array (`['string', 'nullable]`). This PR adds support for it. And it also makes sure the old way (`nullable: true`) is rendered exactly the same way.
**Before**
**After**

feat: improve nullable types

---

.changeset/cuddly-suits-return.md
packages/api-reference/src/components/ApiReference.vue
packages/api-reference/src/components/Content/Introduction/Introduction.vue

fix: move theme flare behind all content

---

.changeset/lazy-ducks-sniff.md
packages/api-reference/src/components/Section/Section.vue

Updates our scroll alignment code to use [`scroll-margin`](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin) to line up the scroll rather than using a negative margin trick. I hadn't used it before when I first did this alignment fix but browser support seems good 🚀 
https://github.com/scalar/scalar/assets/6374090/b418a519-b4d8-4b41-979a-76a818a04f83

fix: use scroll margin instead of padding to align scroll headers

---

.changeset/dull-radios-drum.md
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue

Moves the examples below the description allowing them to be multiline.
This isn't a perfect solution but @cameronrohani want's to do an overhaul of the model design soon so this just a basic fix. If people complain about it making the page longer or whatever we can always make it fancier later.
fixes #1206

fix: allow examples to be multiline

---

.changeset/heavy-hairs-sin.md
packages/api-client/src/components/ApiClient/AddressBar.vue
packages/api-client/src/components/ApiClient/Request/Request.vue
packages/api-reference/src/components/ApiClientModal.vue

Currently, the URL in the API client isn’t editable, but sometimes people like to just jump into the address bar and change the URL (#1189).
With this PR the URL becomes editable.
We used to pass `readOnly` to the API client, that was easily removed. The address bar did update the value in the state, which isn’t easily possible though. CodeMirror is prefilled with two values (URL + path). We can’t easily update them both from one value. (Sure, we could split the string, but in OpenAPI specifications URLs can include a path … just as an example).
Also, the request name was editable then, but didn’t have any effect, so I just disabled it for now.

feat: make API client url editable, fix #1189

---

.changeset/sharp-toes-mate.md
packages/api-client/src/components/ApiClient/AddressBar.vue

We made the address bar editable in #1226. The address is actually two values (url + path), so I decided to not update the request state. Which means the updated address isn’t used for the actual request.
This PR fixes that bug, and updates the request state.
We can’t easily update two values with just one value. So I decided to reset the path then and just put everything into the `url` property.
This will bite us if we ever want to persist the api client state and switch between envs (different base urls), but it’s a pragmatic workaround for now. :)

fix: address bar changes do not effect request, fix #1189

---

examples/react/vite.config.ts
examples/web/src/pages/StartPage.vue

Just found another port that was used twice (react example + echo server). 🙈 I swear, it’s the last time I change any port.

fix: react example port blocks echo server

---

packages/cli/src/commands/mock/MockCommand.ts
packages/cli/src/commands/reference/ReferenceCommand.ts
packages/cli/src/commands/validate/ValidateCommand.ts
packages/cli/src/utils/isUrl.ts
packages/cli/src/utils/loadOpenApiFile.ts
packages/cli/src/utils/printSpecificationBanner.ts
packages/cli/src/utils/watchFile.ts

Currently, the CLI works with files only. With this PR you can pass an URL to the mock and reference command. 🤯 
```bash
scalar reference https://raw.githubusercontent.com/outline/openapi/main/spec3.json
```
```bash
scalar mock https://raw.githubusercontent.com/outline/openapi/main/spec3.json
```
You can even pass the `--watch` flag to poll the URL every few seconds. 
To test it locally, use `pnpm @scalar/cli` instead of `scalar`.

feat: URL support for the CLI

---

.changeset/selfish-buses-jump.md
packages/api-reference/src/components/ApiReference.vue
packages/api-reference/src/components/Content/ClientLibraries/ClientSelector.vue
packages/api-reference/src/components/Content/Content.vue
packages/api-reference/src/components/Content/Introduction/Introduction.vue
packages/themes/src/presets/kepler.css

With us adding container queries to replace the old javascript mobile queries we broke the rare case of people having position fixed for section flares. 
This fixes that :)

fix: section flare if position fixed

---

.changeset/lucky-goats-jam.md
packages/components/env.d.ts
packages/components/src/components/ScalarCodeBlock/ScalarCodeBlock.vue

This makes ScalarCodeblock SSR/SSG compatible. The only downside is line numbers get added on the client side but everything else is 👍🏾

fix: scalar codeblock on SSG/SSR

---

.changeset/heavy-lobsters-play.md
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue
packages/api-reference/src/components/Content/Schema/SchemaPropertyDetail.vue
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue

- Refactors the property type details into components
- Adds the option to turn on truncation for any of the type values
- Fixes a typo in `$.nullable` so that actually works now
- ~~Moves rule badges and `writeOnly` / `readOnly` labels to be right aligned (I did this by accident but I think it looks better / cleaner, we can move them back to the left if we want)~~ Ignore it being on the right in the screenshots, it's back on the left
- Adjusts the color slightly of the type details prefixes to differentiate them from the detail value (e.g. `max: 100`)
**Note:** There might be slight pixel differences due to moving from an inline layout to a flex layout but we need the flex layout for the truncation.
[Cursed Petstore Test File](https://github.com/scalar/scalar/files/14709743/petstorev3.jso …

fix: rebuild schema property details to truncate long strings

---

packages/cli/src/utils/useGivenFileOrConfiguration.ts

The build process had this warning for a while:
> @scalar/cli:build: src/utils/index.ts -> src/utils/useGivenFileOrConfiguration.ts -> src/utils/index.ts
This PR resolves the circular dependency. :)

fix: circular dependency

---

packages/api-reference/src/hooks/useSidebar.ts

The build process had this warning for a while:
> The "??" operator here will always return the left operand
This PR drops the right side. :)

fix: operator will always return left

---

package.json
packages/api-client-react/package.json
packages/api-client-react/vite.config.ts
packages/api-client/package.json
packages/api-client/vite.config.ts
packages/api-reference-react/package.json
packages/api-reference-react/vite.config.ts
packages/api-reference/package.json
packages/api-reference/vite.config.ts
packages/components/package.json
packages/components/vite.config.ts
packages/themes/package.json
packages/themes/vite.config.ts
pnpm-lock.yaml

The current css injection plugin injects the style via JS so it doesn't work on SSR.
[This new plugin](https://www.npmjs.com/package/vite-plugin-lib-inject-css) just auto imports the css file in the component so it makes SSR friendly.
```ts
import './style.css';
```
Not sure how to test this locally because of our package aliases so I'm putting up the PR to test on the preview!

feat: switched css injection plugin

---

.changeset/itchy-walls-give.md
packages/api-reference/src/components/Content/Schema/Schema.vue

feat: show description for oneOf, anyOf

---

.changeset/nine-sloths-tease.md
.changeset/rich-ants-divide.md
packages/cli/README.md
packages/cli/src/commands/format/FormatCommand.ts
packages/cli/src/commands/mock/MockCommand.ts
packages/cli/src/commands/reference/ReferenceCommand.ts
packages/cli/src/commands/validate/ValidateCommand.ts
packages/cli/src/utils/getFileOrUrl.ts
packages/cli/src/utils/isUrl.ts
packages/cli/src/utils/isYamlFileName.ts
packages/cli/src/utils/loadOpenApiFile.ts

We’ve added URL support to the CLI (eg. `scalar reference https://example.com/openapi.json`). But some features were lacking, and I didn’t update the documentation.
This PR adds some missing parts.
✨ New ✨ `pnpm validate https://example.com/openapi.json`
✨ New ✨ `pnpm format openapi.json --output openapi.yaml`
✨ New ✨ `pnpm format https://example.com/openapi.json --output openapi.yaml`

feat(cli): better url support

---

.changeset/pink-rocks-shout.md
packages/api-client-react/src/style.css
packages/api-client/src/components/ApiClient/AddressBar.vue
packages/api-reference/src/components/Content/Introduction/DownloadSpec.vue
packages/api-reference/src/components/Content/Operation/EndpointPath.vue
packages/api-reference/src/components/Content/Operation/PathResponses/PathResponses.vue
packages/api-reference/src/components/Content/Operation/TryRequestButton.vue
packages/api-reference/src/components/Sidebar/SidebarElement.vue
packages/components/src/components/ScalarIcon/icons/ChevronDown.svg
packages/components/src/components/ScalarIcon/icons/ChevronLeft.svg
packages/components/src/components/ScalarIcon/icons/ChevronRight.svg
packages/components/src/components/ScalarIcon/icons/ChevronUp.svg
packages/components/src/components/ScalarIcon/icons/arrow-chevron-down.svg
packages/components/src/components/ScalarIcon/icons/arrow-chevron-left.svg
packages/components/src/components/ScalarIcon/icons/arrow-chevron-right.svg
packages/components/src/components/ScalarIcon/icons/arrow-chevron-up.svg
packages/nextjs-api-reference/src/theme.ts
packages/themes/src/presets/alternate.css
packages/themes/src/presets/bluePlanet.css
packages/themes/src/presets/deepSpace.css
packages/themes/src/presets/default.css
packages/themes/src/presets/kepler.css
packages/themes/src/presets/mars.css
packages/themes/src/presets/purple.css
packages/themes/src/presets/saturn.css

Theme Polish
Reduce details in scalar card to prepare for future features
Sidebar active state changes:

feat: sidebar border indents + theme prep for future

---

.changeset/happy-pillows-cough.md
packages/use-codemirror/package.json
packages/use-codemirror/src/hooks/useCodeMirror.ts
pnpm-lock.yaml

tab works!
shift tab works!
if you escape you can tab normally in the page :) an AMAZING experience boost
https://github.com/scalar/scalar/assets/6176314/1b15f649-a652-4eb4-9141-be6913d232e1

feat: tab and shift+tab codemirror, and escape codeblock hotkeys

---

.changeset/hot-islands-shop.md
packages/api-client/src/helpers/normalizeUrl.test.ts
packages/api-client/src/helpers/normalizeUrl.ts

now `https://petstore3.swagger.io/API/v3/pet` will send as `https://petstore3.swagger.io/API/v3/pet` vs `https://petstore3.swagger.io/api/v3/pet`
i also wrote some tests 😏

fix: only lowercase hostname

---

package.json
tests/README.md

Currently, it can be unclear why e2e tests are failing. This PR adds documentation and related script to clear up confusion around running the Playwright e2e tests locally.

docs: install playwright and dependencies

---

.changeset/nervous-guests-judge.md
packages/api-reference/src/components/ApiReference.vue
packages/api-reference/src/components/ApiReferenceLayout.vue

**Problem**
Toast notifications are not displayed in editor view on user actions (e.g. copy clipboard...) while they are still showing up on the API reference.
**Solution**
This PR is an attempt to fix #1207 by moving the toast initialization to the layout level.

fix: toast notification doesn't show up

---

.changeset/dull-bananas-doubt.md
packages/api-reference/package.json
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/Layouts/ModernLayout.vue
packages/api-reference/src/components/MobileHeader.vue
packages/api-reference/src/hooks/useSidebar.ts

Our current JS controlled sidebar doesn't work in SSR so this uses css classses (controlled by js) to show/hide the sidebar

feat: move sidebar to css

---

packages/api-reference/src/components/MarkdownRenderer/MarkdownRenderer.vue

Okay so I did a bunch of research on this and couldn't come up with a CSS way to do what we want to do. This PR mirrors how GitHub handles tables, see [this gist](https://gist.github.com/hwkr/391f2010150c199e195ad42990d15778) as an example.
* Test file: [petstorev3.json](https://github.com/scalar/scalar/files/14764505/petstorev3.json)
I figured out a CSS solution to always have them full width but it requires squishing content to the left and setting `white-space: nowrap` to keep them from breaking.
We can use `table-layout: auto` to fill the space but it breaks out of the scroll container. We would have to add something like [rehype-wrap-all](https://github.com/florentb/rehype-wrap-all) (which doesn't seem very well supported) to add a scroll container.

fix: don't stretch markdown tables

---

.changeset/dull-bananas-doubt.md
.changeset/khaki-news-complain.md
.changeset/mean-eels-peel.md
.changeset/nervous-guests-judge.md
packages/api-client-react/CHANGELOG.md
packages/api-client-react/package.json
packages/api-client/CHANGELOG.md
packages/api-client/package.json
packages/api-reference-react/CHANGELOG.md
packages/api-reference-react/package.json
packages/api-reference/CHANGELOG.md
packages/api-reference/package.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/docusaurus/CHANGELOG.md
packages/docusaurus/package.json
packages/express-api-reference/CHANGELOG.md
packages/express-api-reference/package.json
packages/hono-api-reference/CHANGELOG.md
packages/hono-api-reference/package.json
packages/mock-server/CHANGELOG.md
packages/mock-server/package.json
packages/nestjs-api-reference/CHANGELOG.md
packages/nestjs-api-reference/package.json
packages/nextjs-api-reference/CHANGELOG.md
packages/nextjs-api-reference/package.json

We accidentally had a major version upgrade in there, this reverts it.

fix: revert major api version

---

.changeset/wild-ears-sort.md
package.json
packages/api-client/src/components/ApiClient/Request/RequestAuthentication/SecuritySchemeSelector.vue
packages/api-client/src/helpers/getRequestFromAuthentication.ts
packages/api-client/src/stores/useAuthenticationStore.ts
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/Content/Authentication/Authentication.vue
packages/api-reference/src/components/Content/Introduction/Description.vue
packages/api-reference/src/components/Content/Lazy/Lazy.vue
packages/api-reference/src/components/Content/Operation/ExampleRequest.vue
packages/api-reference/src/components/MarkdownRenderer/MarkdownRenderer.vue
packages/api-reference/src/helpers/createHash.ts
packages/api-reference/src/helpers/getApiClientRequest.ts
packages/api-reference/src/helpers/getHeadingsFromMarkdown.ts
packages/api-reference/src/helpers/index.ts
packages/api-reference/src/hooks/useNavState.ts
packages/api-reference/src/hooks/useSidebar.ts
packages/api-reference/src/types.ts
packages/oas-utils/src/index.ts
packages/oas-utils/src/ssrState.ts
packages/oas-utils/src/types.ts

The Final PR  in the SSR Prequel saga. This PR instantiates the client state from the server. This does not need to be checked, but we should just poke around and see if eveyrthing works:
- markdown
- auth
- description

feat: add SSR state to references and client

---

.changeset/olive-onions-approve.md
packages/api-reference/src/hooks/useSidebar.ts

fix  #1336  
Currently, with the api client opened, when navigating through the endpoints via sidebar the global authentication header is not sent in the request.
Probably, this pull request introduced the bug https://github.com/scalar/scalar/pull/1188.
This happens because `useSidebar` was not updated, so every time the `openClientFor` function was called, without the global security parameter being passed, the `globalSecurity` of `useOpenApiStore` was set to undefined.
With this PR, `useSidebar` has been updated so that `openClientFor` calls pass the `globalSecurity` parameter, thus preventing it from being overwritten
- Add e2e test to prevent regressions in this behavior;
- Solve this TODO https://github.com/scalar/scalar/blob/main/packages/api-reference/src/helpers/openClientFor.ts#L3 …

fix: set global security on sidebar navigation

---

.changeset/tall-guests-obey.md
packages/api-reference/src/components/Section/Section.vue

**Problem**
We remove the rest of the path on scroll (this doesn't seem to happen on local but it has for a user)
we were just passing the hash into history state
**Solution**
With this PR we create a new URL with the current href and just update the hash. This _should_ work

fix(#1339): only update hash value on scroll

---

.changeset/fuzzy-wombats-thank.md
packages/api-reference/src/components/Content/Schema/Schema.vue
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue

**Problem**
as described in #1318, the description of an object is duplicated, as seen below: 
**Solution**
this PR is an attempt to fix #1318 by introducing a function for displaying the description unless the value has properties.
after the change:

fix: descriptions repeat themselves

---

.changeset/popular-beans-matter.md
packages/api-reference/src/components/Sidebar/SidebarElement.vue

This will build the URL using the constructor then update the hash. This is only temporary, soon we will switch to vue-router.

fix(#1355): root path on sidebar items

---

.changeset/friendly-readers-tickle.md
packages/api-client/src/components/ApiClient/Request/Request.vue
packages/api-client/src/components/ApiClient/Request/RequestAuthentication/RequestAuthentication.vue
packages/api-client/src/components/ApiClient/Request/RequestCookies.vue
packages/api-client/src/helpers/getRequestFromAuthentication.ts
packages/api-client/src/stores/useAuthenticationStore.ts
packages/components/src/components/ScalarButton/variants.ts
packages/oas-utils/src/types.ts

This allows users to add basic security when the spec does not contain any. This security should also persist between requests.
Currently this PR works but is missing oAuth 2

feat: add custom security option

---

packages/docusaurus/README.md

**Problem**
The README.md for the docusaurus package has invalid usage code. The current code produces the error in the latest version of docusaurus:
```
[INFO] Starting the development server...
>  NX    => Bad Docusaurus plugin value plugins[1].
Example valid plugin config:
{
plugins: [
["@docusaurus/plugin-content-docs",options],
"./myPlugin",
["./myPlugin",{someOption: 42}],
function myPlugin() { },
[function myPlugin() { },options]
],
};
```
This happens because the plugin array expects an array with the first element as the package name, and the second element as the options.
You can also see the following TypeScript error in your IDE:
```
TS2353: Object literal may only specify known properties, and label does not exist in type
PluginModule<unknown> | …
```

docs: Update README.md for docusaurus package

---

.changeset/heavy-deers-sell.md
packages/api-reference/src/helpers/parse.ts

now you can change the names of tags with the x-displayName [extension](https://redocly.com/docs/api-reference-docs/specification-extensions/x-display-name/)
```
"tags": [
{
"x-displayName": "MARC",
"name": "pet",
"description": "Everything about your Pets",
"externalDocs": {
"description": "Find out more",
"url": "http://swagger.io"
}
},
```

feat: support x-displayName tag extension

---

.changeset/thick-lobsters-search.md
packages/api-reference/src/components/Content/ClientLibraries/ClientSelector.vue

**Problem**
documentation using light theme displays too important border radius on their code languages icon element [as seen on this documentation](https://docs.acctual.com/reference):
**Solution**
this pr decreases the border radius applied on the `.code-languages-background:before` element in order to harmonize radiuses:

fix: api reference code languages radiuses

---

.changeset/funny-gorillas-switch.md
packages/api-reference/src/components/Content/Content.vue
packages/api-reference/src/helpers/parse.ts

you can write out sections without operations

feat: support tags with no operations

---

.changeset/large-bags-end.md
packages/api-reference/src/hooks/useNavState.ts

fixes #1405 
Sometimes URL's get encoded, this will ensure selecting the correct endpoint works even if it gets encoded.

fix(#1405): decode uri component for hash values

---

.changeset/eighty-scissors-pay.md
packages/api-reference/src/components/Content/Tag/Endpoints.vue
packages/api-reference/src/components/Content/Tag/Tag.vue
packages/api-reference/src/components/Content/Tag/mutationObserver.ts

**Problem**
when a section is closed and user clicks on an operation, it opens the section and navigates toward the first operation of the list instead of the selected one.
[as seen here →](https://docs.scalar.com/project-default/version-default/reference-YCSmGxwEOVk-0oBSMCo-1#tag/store)
**Solution**
this pr is a first attempt to follow the commented instructions, in order to make sure the endpoint is accessible before navigating towards it by using the [mutation observer api](https://vueuse.org/core/useMutationObserver/) from vueuse.

fix: endpoint navigation

---

.changeset/neat-horses-allow.md
.changeset/slow-goats-confess.md
examples/web/src/pages/StandaloneApiReferencePage.vue
examples/web/src/pages/StartPage.vue
examples/web/src/routes.ts
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/Content/Introduction/Description.vue
packages/api-reference/src/components/Content/Lazy/Loading.vue
packages/api-reference/src/components/Content/Operation/ExampleRequest.vue
packages/api-reference/src/components/Section/Section.vue
packages/api-reference/src/components/Sidebar/Sidebar.vue
packages/api-reference/src/components/Sidebar/SidebarElement.vue
packages/api-reference/src/hooks/useNavState.ts
packages/api-reference/src/hooks/useSidebar.ts
packages/api-reference/src/index.ts
packages/api-reference/src/types.ts

This PR adds path routing as an option. It also adds a page to the start page for testing. Currently I have it pointing to the other PR since it builds off of it, but once its merged can re-base from main.

feat: path routing

---

.changeset/loud-glasses-hang.md
packages/use-modal/src/components/FlowModal.vue

**Problem**
in darkmode when a user open the request history modal, the header displays a background. according to #177 i believe this shouldn't be the case. hope i read you right @cameronrohani :). 
**Solution**
use inherit background in modal header for darkmode.

fix: content modal history style

---

.changeset/seven-actors-film.md
packages/api-reference/src/components/Content/Operation/PathResponses/PathResponses.vue

Fixes #1406
```json
{
"openapi": "3.0.0",
"examples": {},
"headers": {},
"parameters": {},
"requestBodies": {},
"responses": {}
},
"paths": {
"/example": {
"get": {
"summary": "Single example in `examples`",
"responses": {
"200": {
"description": "Ok",
"content": {
"schema": {
"type": "object"
},
"examples": {
"one": {
"value": {
"hello": "example nested"
}
}
}
}
}
}
}
}
},
"/example2": {
"get": {
"summary": "Multiple examples in `examples`",
"responses": {
"200": {
"description": "Ok",
"content": {
"schema": {
"type": "object"
},
"examples": {
"one": {
"value": {
"hello": "example"
}
},
"two": {
"value": {
"hello": "example"
}
}
}
}
}
}
}
}
},
"/example3": {
"get": {
"summary": "Single example",
"responses": {
"200": { …
```

fix: show example picker if the list only has one example

---

.changeset/neat-lions-yawn.md
packages/api-reference/src/components/Layouts/ModernLayout.vue

closes #1421 
I couldn't replicate the sidebar showing, but I did see the header was still there. Just hid it when `showSidebar: false`. Wanna make sure this has no knock-on effects

fix: hide header when no mobile sidebar

---

.changeset/pink-bananas-exist.md
packages/api-reference/src/components/IntersectionObserver.vue

**Problem**
when a low height element lies between two others, it is not always detected by the observer as the next one according to scroll speed is already in the viewport and therefore not highlighted in the sidebar.
https://github.com/scalar/scalar/assets/14966155/9e75c2d3-4cf5-460a-af91-3f3086fb618c
**Solution**
this pr attempt adds two methods in order to calculate a margin + set the threshold according to the element height. good scroll yall!
https://github.com/scalar/scalar/assets/14966155/dd1d921b-fdb7-46d1-b321-4833da97ed38

fix: intersection observer detection

---

.changeset/proud-suns-love.md
packages/api-reference/src/components/Content/Schema/Schema.vue

**Problem**
as highlighted by @databyjp in #1395 — schema descriptions do not render markdown.
**Solution**
this PR is a proposal to use the markdown rendering for the schema value description.

fix: object description markdown

---

.changeset/yellow-timers-grab.md
packages/api-reference/src/components/Content/Tag/Endpoints.vue

**Problem**
Currently, I can't embed images in my markdown descriptions for tag descriptions. I have UML Diagrams that describe my workflows and would like to show them there.
This happens because the markdown renderer component does use the optional prop value at this time.
**Solution**
With this PR, images will get rendered in tag descriptions when using the optional `withImages` prop value.

feat: render images in tag markdown description

---

package.json
tooling/base-docker-builder/Dockerfile

**Problem**
Base build is failing for the deployed server examples
pnpm was getting bumped to latest 9.x version and project used 8.x
**Solution**
Pin that version

fix: pin pnpm version in docker base build

---

.changeset/thin-knives-relax.md
packages/api-reference/src/components/Content/Content.vue

Swagger 2.0 has a different syntax for server URLs. It’s using a `schemes` array to provide a list of available http schemes (http, https).
Currently, we expect it to be present. Turns out, some files don’t have it.
This PR makes it optional.
**Example (with schemes)**
```json
{
"swagger": "2.0",
"info": {
"version": "1.0.7",
"title": "Swagger Petstore",
},
"host": "petstore.swagger.io",
"schemes": [
"https",
"http"
],
"paths": {}
}
```
Result: `https://petstore.swagger.io`
**Example (without schemes)**
```json
{
"swagger": "2.0",
"info": {
"version": "1.0.7",
"title": "Swagger Petstore",
},
"host": "petstore.swagger.io",
"paths": {}
}
```
Result: `http://petstore.swagger.io`

feat: use http as default scheme for Swagger 2.0 specifications, fix #1218

---

.changeset/modern-shirts-argue.md
packages/api-reference/src/components/GettingStarted.vue

**Problem**
theme from starting section are displaying raw name value
**Solution**
this displays theme name right format + fix last theme excess border / hover radiuses

fix: getting started themes

---

.changeset/silver-dingos-fold.md
packages/use-codemirror/package.json
pnpm-lock.yaml

Should fully externalize y-codemirror and yjs from the use-codemirror package

chore: Make y-codemirror external and optional

---

.changeset/spicy-bobcats-appear.md
packages/api-reference/src/components/GettingStarted.vue
packages/themes/src/index.ts

Just exposes the theme labels object so we can use it elsewhere

refactor: move theme labels to @scalar/themes

---

packages/express-api-reference/README.md

* chore: update readme for express
* Update README.md
* docs(changeset): chore: update readme

chore: update readme for express

---

README.md

Currently, I try to put the next town hall event date in the README and keep it up to date.  But it’s tedious.
Let’s just change the wording. :)

chore: remove date from townhall event

---

.changeset/tender-suns-thank.md
packages/themes/src/components/ThemeStyles.vue
packages/themes/src/index.test.ts
packages/themes/src/index.ts
packages/themes/src/presets/alternate.css
packages/themes/src/presets/bluePlanet.css
packages/themes/src/presets/deepSpace.css
packages/themes/src/presets/default.css
packages/themes/src/presets/kepler.css
packages/themes/src/presets/mars.css
packages/themes/src/presets/moon.css
packages/themes/src/presets/purple.css
packages/themes/src/presets/saturn.css
packages/themes/src/presets/solarized.css
packages/themes/vitest.config.ts

So I wasn't thinking about this at the time but we can't have the themes used in the docs site have the `@layer` declaration (at least in the theme editor). This makes the layer an option that is inject by `getThemeById` and adds some testing for it.

refactor: remove @layer from base theme files

---

.changeset/pretty-colts-leave.md
packages/api-reference/src/components/MarkdownRenderer/MarkdownRenderer.vue

fix: summary markdown, fix #1524

---

.changeset/three-plants-scream.md
packages/components/src/components/ScalarSearchResults/ScalarSearchResultItem.vue
packages/components/src/components/ScalarSearchResults/ScalarSearchResults.stories.ts

fix: truncate search results properly

---

packages/nuxt/.gitignore

chore: ignore generated files

---

.changeset/olive-wombats-join.md
README.md
packages/api-client/src/components/ApiClient/ApiClient.vue
packages/api-reference/.storybook/preview.ts
packages/api-reference/README.md
packages/api-reference/src/components/ApiClientModal.vue
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/types.ts
packages/components/.storybook/preview.ts
packages/components/README.md
packages/themes/package.json
packages/themes/src/base.css
packages/themes/src/components/DefaultFonts.vue
packages/themes/src/components/ThemeStyles.vue
packages/themes/src/fonts.css
packages/themes/vite.config.ts

Currently, we’re fetching Inter and JetBrains Mono from Google fonts - always. Even if different fonts are used or people just don’t want to use Google Fonts (see https://github.com/elysiajs/elysia-swagger/issues/104)
This happens because the CSS imports are just part of our base styles.
This PR separates the fonts from the base styles, and adds a setting to not fetch the default fonts from Google Fonts. 
Great for perf (can save 67kb, if the fonts are not used anyway), great for privacy. Enables users to self-host the fonts, or use something else, or just use the default system font stack.
```vue
<ApiReference :configuration="{
withoutDefaultFonts: true
} />
```

feat: configure whether to fetch the default fonts, fix #1471

---

packages/api-reference/src/components/Content/ClientLibraries/ClientSelector.vue

**Problem**
Currently, when user focus on "more >" text, cursor pointer appears, but select does not open on click/touch.
That happens because select's parent element has padding
**Solution**
Set select size same as parent
fix #1536

fix: update ClientSelector styles fix #1536

---

.changeset/wild-peas-fly.md
packages/themes/vite.config.ts

Because we want to use the theme css in our theme editor we need to have the line breaks in there.

fix: don't minify theme css

---

packages/mock-server/README.md

The mock server used to have a `openapi` property, but it was renamed to `specification` at some point.
This PR updates the README.

fix: mock server README example doesn’t work

---

README.md

**Problem**
Currently, `Litestar` is not listed
This happens because someone forgot to add it
**Solution**
With this PR we add Litestar, as well as adjust some grammatical issues and add GitHub's new admonition syntax for notes

docs: add litestar, fix some grammar and spacing

---

.changeset/quiet-keys-live.md
packages/api-reference/src/hooks/useSidebar.ts

Currently, the sidebar disappears if you have unused, empty tags. See #1535 for more context.
This is because we’ve had a check in place, that was wrong. It just skipped the output if the first tag doesn’t have an operation attached.
This PR fixes it. :)

fix: unused empty tags break sidebar, fix #1535

---

.changeset/smart-carrots-march.md
examples/web/src/pages/ApiReferencePage.vue
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/GettingStarted.vue

**Problem**
some themes are not selectable from the api reference editor.
**Solution**
this pr introduces the theme label value in the `changeTheme` event in order to base the theme selection on it in the app.

fix: theme not selectable in the editor

---

.changeset/long-turtles-begin.md
packages/api-reference/src/components/Content/Content.vue

this was due to loading from a file:// path

fix: avoid prepending path when running standalone from an html file without a server

---

tooling/base-docker-builder/.dockerignore

Add missing `.dockerignore` to the base builder image.

chore: add .dockerignore to base builder image

---

cloudbuild.yaml
examples/react/.dockerignore
examples/react/Dockerfile
examples/react/package.json

Containerize react example app. Adds Dockerfile and cloudbuild script. Uses `serve` package to serve the static js from the dist/ folder.

feat: containerize react example app

---

.changeset/config.json

Currently, we manually need to add a changeset for `@scalar/fastify-api-reference` to publish it with an updated version of `@scalar/api-reference`.
This is happens because the fastify package doesn’t have the core package as a direct dependency (it’s just copied in there). And my attempt to configure the release workflow accordingly didn’t have any effect.
I think I misread the documentation on “linked” packages and we actually need to configure them as “fixed” packages.
Before: https://github.com/changesets/changesets/blob/main/docs/linked-packages.md
After: https://github.com/changesets/changesets/blob/main/docs/fixed-packages.md
See #1246

chore: release `@scalar/fastify-api-reference` together with the `@scalar/api-reference`, fix #1246

---

.github/ISSUE_TEMPLATE/config.yml
README.md
packages/api-client-proxy/README.md
packages/api-client-react/README.md
packages/api-client/README.md
packages/api-reference-react/README.md
packages/api-reference/README.md
packages/cli/README.md
packages/draggable/README.md
packages/echo-server/README.md
packages/express-api-reference/README.md
packages/fastify-api-reference/README.md
packages/galaxy/README.md
packages/hono-api-reference/README.md
packages/nestjs-api-reference/README.md
packages/nextjs-api-reference/README.md
packages/nuxt/README.md
packages/themes/README.md
packages/use-codemirror/README.md
packages/use-tooltip/README.md

Currently, we’re still using the URL Discord hash URL in a lot of places.
Let’s switch to the new vanity URL. :)

chore: use new Discord URL everywhere

---

.changeset/breezy-walls-shake.md
packages/api-client/src/helpers/getRequestFromAuthentication.test.ts
packages/api-client/src/helpers/getRequestFromAuthentication.ts

Currently, if you prefill the authentication data and pass `token: null` it throws an exception.
This PR fixes it and adds a test for it.
See #1519 for more context

fix: token null throws exception, fix #1519

---

README.md

This PR adds a section about Markdown to our root README. :)
See #919

docs: add a section about Markdown, fix #919

---

cloudbuild.yaml
examples/nestjs-api-reference-express/Dockerfile

containerize nestjs express example app

chore: containerize nestjs express example app

---

packages/themes/src/fonts/inter.css

Add support for variable width inter font. Fixes DOC-1755
@tmastrom these `woff2` files need to be uploaded to the CDN: [inter-variable.zip](https://github.com/scalar/scalar/files/15180645/inter-variable.zip)
Behold, variableness 
https://github.com/scalar/scalar/assets/6374090/edf2e6fc-f9a0-4206-b054-45c2502ff1b5

refactor: switch to inter variable

---

.changeset/small-lies-exist.md
packages/api-reference/src/hooks/useSidebar.ts

Currently, we’re looking for Markdown headings in the `info.description` field and only add the lowest level (eg. h1) to the sidebar.
This PR adds the 2nd lowest level (eg. h2) to the sidebar, too.
* If there’s only one level of headings, they are all just added to the sidebar.
* If there’s two levels of headings, they will be added to the sidebar. The 2nd lowest level (eg. h2) will be nested under the lowest level (eg. h1).
* If there’s more than two levels (eg. h1, h2, h3), the highest level (eg. h3) will be ignored (for the sidebar).
See #906 for more context.

feat: add multiple levels of headings to the sidebar

---

examples/nextjs-api-reference/Dockerfile

Remove unnecessary hardcoded PORT and HOSTNAME arguments in the Dockerfile. Cloud Run will pass in and expose the necessary port.

chore: remove unnecessary port and host from dockerfile

---

.changeset/violet-bears-smile.md
examples/cdn-api-reference/src/public/api-reference-cdn-live.html
examples/cdn-api-reference/src/public/api-reference-cdn-localhost.html
examples/react/index.html
packages/api-reference/index.html
packages/cli/src/utils/getHtmlDocument.ts
packages/express-api-reference/src/expressApiReference.ts
packages/fastify-api-reference/src/fastifyApiReference.test.ts
packages/fastify-api-reference/src/fastifyApiReference.ts
packages/nestjs-api-reference/src/nestJSApiReference.ts
packages/nextjs-api-reference/src/ApiReference.ts

Currently, we’re using `API Reference` as the page title everywhere.
This PR proposes to use `Scalar API Reference` as the default (can be overwritten through configuration).
People refer to our API reference as ”Scalar”, I think it’s good to use that in the default page title.

chore: use same example page title everywhere

---

README.md
examples/cdn-api-reference/src/public/api-reference-cdn-live.html
examples/cdn-api-reference/src/public/api-reference-cdn-localhost.html
examples/react/src/App.tsx
packages/api-reference-react/README.md
packages/api-reference/src/standalone.ts
packages/express-api-reference/test/index.test.ts
packages/galaxy/README.md
packages/hono-api-reference/src/honoApiReference.test.ts
packages/nestjs-api-reference/test/index.test.ts
packages/oas-utils/src/fetch-spec.test.ts

Currently, we’re still using the petstore HTTP url in a lot of places.
This PR switches to the `@scalar/galaxy` jsdelivr URL instead. :)
I’ve also simplified the quickstart example and made a few wording changes to the root README (focusing more on OpenAPI, less on Swagger).

docs: use @scalar/galaxy instead of petstore example

---

.changeset/cyan-dolls-help.md
packages/api-reference/src/components/Content/Schema/Schema.vue

Currently, we just show “Show Child Attributes” or the property type. That can be confusing when having a list of schemas, see #1473 for more context.
This PR uses the property title if it’s available.

feat: use schema property title if available, fix #1473

---

packages/components/package.json
packages/components/src/components/ScalarDropdown/ScalarDropdown.spec.ts
packages/components/src/components/ScalarDropdown/ScalarDropdown.stories.ts
packages/components/src/components/ScalarDropdown/ScalarDropdown.vue
packages/components/src/components/ScalarDropdown/ScalarDropdownDivider.vue
packages/components/src/components/ScalarDropdown/ScalarDropdownItem.vue
packages/components/src/components/ScalarDropdown/index.ts
packages/components/src/components/ScalarFloating/ScalarFloating.spec.ts
packages/components/src/components/ScalarFloating/ScalarFloating.stories.ts
packages/components/src/components/ScalarFloating/ScalarFloating.vue
packages/components/src/components/ScalarFloating/index.ts
packages/components/src/components/ScalarFloating/types.ts
packages/components/src/components/ScalarFloating/useResizeWithTarget.spec.ts
packages/components/src/components/ScalarFloating/useResizeWithTarget.ts
packages/components/src/cva.ts
packages/components/src/tailwind/tailwind.theme.ts
pnpm-lock.yaml

feat: add context / dropdown menu to component library

---

cloudbuild.yaml
examples/express-api-reference/.dockerignore
examples/express-api-reference/Dockerfile
examples/express-api-reference/package.json
examples/express-api-reference/src/index.ts
examples/express-api-reference/tsconfig.json
packages/api-reference/src/components/GettingStarted.vue
pnpm-lock.yaml

Deploy the express api reference example using Docker and CloudBuild. This PR also updates the api reference to fetch the scalar-galaxy spec from the CDN to avoid issues in Docker with relative path imports

chore: deploy express example

---

README.md

fixed link to FastAPI integration's README

fix: wrong FastAPI README link 

---

packages/api-reference/src/components/Sidebar/SidebarElement.vue

Because handleclick wraps the whole sidebar section, `isIntersectionEnabled` was getting enabled early and was bugging out the scroll, causing the wrong sidebar elements to get selected. This PR fixes that.

fix: disable scroll observer on sidebar click

---

.changeset/six-humans-visit.md
README.md
packages/api-reference/package.json
packages/api-reference/src/standalone.spec.ts
packages/api-reference/src/standalone.ts
packages/use-toasts/package.json
pnpm-lock.yaml

Added two user-requested events to the standalone app. 
Also added some tests to util, had to use sleep as we are outside of vue and flush promises didn't work. If the sleep becomes a problem I will remove and add a better solution.
Instructions can be found [here](https://github.com/scalar/scalar/blob/321485c913239e75a2466a5eaa3c29ea379b6d52/README.md#events-beta)
closes #1340

feat: add events and tests to standalone references

---

.changeset/nice-buckets-appear.md
packages/components/src/components/ScalarDropdown/ScalarDropdown.stories.ts
packages/components/src/components/ScalarDropdown/ScalarDropdown.vue
packages/components/src/components/ScalarDropdown/index.ts
packages/components/src/components/ScalarFloating/ScalarFloating.stories.ts
packages/components/src/components/ScalarFloating/ScalarFloating.vue
packages/components/src/components/ScalarFloating/types.ts
packages/components/src/components/ScalarFloating/useResizeWithTarget.ts
packages/components/src/components/ScalarPopover/ScalarPopover.spec.ts
packages/components/src/components/ScalarPopover/ScalarPopover.stories.ts
packages/components/src/components/ScalarPopover/ScalarPopover.vue
packages/components/src/components/ScalarPopover/index.ts
packages/components/src/index.ts

Little followup PR to #1557 to add popovers and extend scalar floating a little bit for some future usage I foresee with middlewares.
Also I forgot to add the dropdown and floating components to the components export...
https://github.com/scalar/scalar/assets/6374090/18147245-1f6e-4c0f-88e4-12118e6ec8de

feat: add scalar popover

---

packages/docusaurus/README.md

There were a couple of erraneous brackets in the docusaurus package README

fix: docusaurus README example

---

examples/nestjs-api-reference-express/.dockerignore
examples/nestjs-api-reference-express/Dockerfile
examples/nestjs-api-reference-express/src/main.ts

This PR fixes the Dockerfile for the nestjs express example by allowing Cloud Run to pass in the PORT env variable. 
* streamlines and adds comments to the Dockerfile
* adds .dockerignore

fix: nestjs express example

---

examples/react/Dockerfile

Currently, react example app is not starting in Cloud Run because the image does not accept the PORT variable.

fix: react api reference example

---

examples/nestjs-api-reference-express/src/main.ts

I think we’ve remove the default port for the NestJS (with Express) example. Locally, this throws an error for me:
>  RangeError: options.port should be >= 0 and < 65536. Received type number (NaN).
This PR adds a default port (again) and should fix the error. ✌️

fix: received NaN as the port

---

packages/api-reference/src/standalone.spec.ts

The release workflow fails, because on of the tests fails in CI. It doesn’t fail locally, so it might just not wait long enough for the DOM in CI. 🤔

chore: increase wait for dom tests

---

.changeset/lazy-zebras-yell.md
packages/api-reference/src/hooks/useSidebar.ts

When using and then removing a specification from the editor heading entries are still displayed.
This PR properly resets the headings.
BTW The same issue exists for webhooks, but for a different reason. We’ll tackle this in a separate PR.

fix: sidebar headings don’t reset

---

.changeset/poor-geckos-collect.md
.github/workflows/release.yml
.npmrc

Provenance statements give a proof that our published packages are what’s in this repository. This is a typical security concern users have. That’s why I suggest to enable it for this repository. :)
Note: It might not work on the first attempt, it’s hard to test without actually releasing. If you like, I can test this on a smaller repository first.
Read more:
> You can generate provenance statements for the packages you publish. This allows you to publicly establish where a package was built and who published a package, which can increase supply-chain security for your packages.
https://docs.npmjs.com/generating-provenance-statements

ci: generate provenance statements

---

cloudbuild.yaml
examples/fastify-api-reference/.dockerignore
examples/fastify-api-reference/Dockerfile
examples/fastify-api-reference/package.json
examples/fastify-api-reference/src/index.ts
examples/fastify-api-reference/tsconfig.json
pnpm-lock.yaml

Setup fastify api reference, containerize, and add cloudbuild script to deploy example app.

feat: containerize fastify example and deploy with cloudbuild

---

.changeset/tidy-wolves-complain.md
packages/draggable/src/index.ts

Quickie, missed these types on the export

fix: export types from draggable

---

.changeset/five-weeks-shave.md
packages/api-reference/package.json
packages/api-reference/src/components/GettingStarted.vue
pnpm-lock.yaml

What if we don’t bundle the @scalar/galaxy example, but fetch it from jsdelivr? This should decrease the bundle size. 🤔

chore: fetch example specification from jsdelivr

---

packages/api-reference/README.md

Just adding a ` to fix this broken code block:
And while I’m on it, let’s remove the petstore stuff from the example. :)

fix: code block broken

---

.changeset/lovely-pears-reflect.md
packages/cli/package.json
packages/mock-server/package.json

Can't generate the provenance statement for packages without a wrong repository URL. 😬

fix: wrong repository url

---

README.md

Oops, the indentation of the table of contents in the root README is off. This PR fixes it.
I’ve also updated the content structure a little bit and rewrote the hosting paragraph. 💅

docs: update table of contents, slightly update content structure

---

.changeset/yellow-zoos-study.md
packages/api-reference/src/components/MarkdownRenderer/MarkdownRenderer.vue

fix: hide default caret on <summary> on Safari

---

.changeset/few-wombats-sort.md
packages/mock-server/src/createMockServer.ts
packages/mock-server/tests/openapi.test.ts

The mock server has an `/openapi.json` endpoint, which isn’t working very well.
[If you pass YAML, /openapi.json returns the YAML string …](https://galaxy.scalar.com/openapi.json)
Anyway, this PR makes it all awesome and even adds an `openapi.yaml` endpoint. :)

fix(mock-server): openapi.json returns yaml string

---

packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/hooks/useSidebar.ts

Since we removed the editor from @scalar/api-reference the local demo was broken. We’ve re-added Monaco a while ago, but the sidebar was empty. I’m using this a lot to play around with specifications, so I’m eager to finally fix this again. :)
This PR makes the sidebar reactive again, which fixes the local demo (the one with the editor):
http://localhost:5050/api-reference

fix: sidebar is empty locally

---

examples/web/src/pages/StartPage.vue

Two example links are broken for the `examples/web` we’re using, this PR fixes them. ✨

fix: start page links broken

---

README.md

There was a typo causing it to link to the Nest.js page instead.
**Problem**
Currently, the link labeled "Next.js API Reference" actually links to the Ne**s**t.js API Reference
This happens because there is an s where there should be an x
**Solution**
With this PR I fixed the typo.

docs: Fix Next.js API Spec Link

---

.changeset/gentle-seas-know.md
examples/web/src/pages/ApiReferenceTestPage.vue
examples/web/src/pages/ClassicApiReferencePage.vue
examples/web/src/pages/EmbeddedApiReferencePage.vue
examples/web/src/pages/StandaloneApiReferencePage.vue
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/Content/Introduction/DownloadSpec.vue
packages/api-reference/src/components/Content/Introduction/Introduction.vue
packages/api-reference/src/helpers/specDownloads.ts
packages/api-reference/src/standalone.spec.ts

**Problem**
`spec` + extension is currently used as the file name when a spec is downloaded from the reference doc, which can make it difficult to find if using multiple APIs.
**Solution**
this pr is a proposal to include the spec title in the downloaded filename.

feat: include spec title in downloaded spec filename

---

.changeset/eight-penguins-cough.md
packages/api-reference-react/package.json
packages/api-reference/package.json
packages/api-reference/src/components/MarkdownRenderer/MarkdownRenderer.vue
packages/api-reference/vite.config.ts
packages/nuxt/src/module.ts
pnpm-lock.yaml

Look what I found! We’re using highlight.js for the syntax highlighting in Markdown and it’s huge!
| Package          | Size      |
|----------------- | --------- |
| rehype-highlight | 3.54KiB   |
| highlight.js	   | 354.87KiB |
But we’re also using prismjs for code blocks. What if … we replace highlight.js with prismjs … 🤔 
EDIT: Results are in: 💥 1.77MiB (-6.4%) 💥

chore: use prism instead of highlightjs

---

tooling/base-docker-builder/Dockerfile

CI is broken, the docker build complains about a list of strings and say it can’t analyse it.
When I try it locally it bails at another point. I’m pretty confident we’re hitting a memory limit or something here.
With this PR we’re using turbo to build the packages in the Dockerfile and make sure it’s not running more than 2 processes in parallel.
Let’s try if that helps! It does locally.

fix: base docker builder hits memory limit or something

---

examples/proxy-server/README.md
examples/proxy-server/main.go

Changing the query parameter name to `scalar_url` so the proxy doesn't break with urls with a `url` query param.

chore: change url param to scalar_url in the proxy

---

.changeset/tender-masks-eat.md
packages/api-client/src/components/ApiClient/Request/Request.vue

**Problem**
request body is displayed for each http method in the api client, even though it is not useful for each of them.
**Solution**
this pr is a proposal to introduce a condition on the request body display on selected http methods.

fix: api client request body display

---

examples/proxy-server/package.json

Remove fields from package.json so the proxy is not published to npm

fix: update package.json so go proxy is not published to npm

---

.changeset/plenty-mugs-do.md
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue

Why was 'required' so AGGRESSIVE, let's fix that
Before:
After:

fix: uppercase required property

---

.changeset/flat-dots-fry.md
packages/api-reference/src/components/MarkdownRenderer/MarkdownRenderer.vue

Add styling for <sup> tag in markdown

fix: support <sup> tag in markdown

---

.changeset/late-dolphins-scream.md
packages/api-client/src/components/ApiClient/AddressBar.vue

Fixes history toggle overlapping with close button. and puts it in it's new proper location:
This fixes:
https://github.com/scalar/scalar/issues/1687

fix: history toggle location

---

.changeset/healthy-pears-build.md
packages/api-reference/src/components/ApiClientModal.vue

`@scalar/api-client` is pretty heavy. It’s the only reason we still have CodeMirror (for the request body and the address bar).
@amritk had the wonderful idea to lazy load the API client. This PR does exactly this, and the ESM build improves:
```diff
-dist/index.js 1,650.72 kB
+dist/index.js 1.60 kB
+dist/index-Bw-GQvDT.js 1,314.59 kB
```
This means:
1. The first file that needs to be loaded in ESM envs is 1kB instead of 1,600kB.
2. The biggest chunk is 1,300 kB instead of 1,600 kB.
3. Users that never open the API client, will never load the ~1,500 kB (only applies to ESM envs, like our app).
CDN users don’t benefit from the change yet, because it’s still bundling everything in one file. But at some point (once the ESM CDN build works), they'll experience the same benefits. :)

chore: lazy load API client

---

.changeset/stale-trees-own.md
packages/api-client/src/components/ApiClient/Response/Response.vue

fix: vertical alignment of client response empty state

---

.changeset/young-tigers-tickle.md
packages/api-client/src/components/ApiClient/ApiClient.vue
packages/api-reference/src/components/ApiClientModal.vue

this pr is a proposal to use the `meta + b` shortcut to toggle the api client sidebar visibility.

feat: api client toggle sidebar

---

.changeset/clean-glasses-sip.md
packages/api-client/src/components/ApiClient/AddressBar.vue

**Problem**
as highlighted by @Amorim33 and in #1687, breaking layout when url is too long.
**Solution**
this pr fixes #1687 by allowing scrolling and adding fade to long url.

fix: api client address bar url

---

packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/hooks/index.ts
packages/api-reference/src/hooks/useDeprecationWarnings.ts

Once we switch to the new proxy, we need to overwrite the old proxy URL (https://api.scalar.com/request-proxy) with the new URL (https://proxy.scalar.com) and warn users about it (affects probably everyone).
And we want to warn if a custom proxy URL is used (shouldn’t affect many people).
This PR adds the code already, but disables the messages until the proxy is ready.

chore: add deprecation warnings (still disabled)

---

examples/web/src/pages/StartPage.vue

In #659 we’ve added the URLs of the deployed examples, but I’m missing the local URLs. I love how convenient it is to open a locally running example. 
So why don’t we add both? 😊

chore: bring back local urls for development

---

packages/galaxy/README.md

There’s a typo in the @scalar/galaxy JSON url. :)

fix: galaxy latest JSON url wrong

---

.changeset/dirty-suits-beam.md
packages/api-reference/src/components/ApiClientModal.vue

Remove scale from client animation which was (most likely) giving a windows user blurry text 
Increase modal size
Create better contrast for click out areas for dark mode
Before:
After:

fix: pop up client ui / UX 

---

.changeset/proud-boxes-punch.md
packages/api-client/src/components/ApiClient/Request/RequestAuthentication/SecuritySchemeSelector.vue

**Problem**
Currently, if `securitySchemes` is defined with a single scheme, uncolored security scheme will be displayed in the API client.
Before:
After:
The issue is... the needed styles weren't applied to text if a single scheme is provided.
**Solution**
Put `.security-scheme-selector span` into a separate class, and use it for scheme labels.

fix: color single security scheme

---

.changeset/fuzzy-baboons-yell.md
examples/web/src/fixtures/emptySpec.ts
examples/web/src/pages/ApiReferencePage.vue
packages/api-reference/README.md
packages/api-reference/src/helpers/createEmptySpecification.ts
packages/api-reference/src/helpers/index.ts
packages/api-reference/src/helpers/parse.ts
packages/api-reference/src/hooks/useReactiveSpec.ts
packages/api-reference/src/types.ts
packages/nuxt/playwright.config.ts

As requested in https://github.com/scalar/scalar/discussions/1728, this PR adds the ability to hide some operations with `x-internal: true`.
I’ve added an example to the `@scalar/api-reference` README. While I was on it, I’ve added examples for `x-displayName` and `x-tagGroup` aswell.
I was also able to remove handful of `@ts-expect error` comments.

feat: hide operations with `x-internal: true`

---

packages/api-reference/src/components/Content/ClientLibraries/ClientSelector.vue
packages/api-reference/src/hooks/useHttpClients.test.ts
packages/api-reference/src/hooks/useHttpClients.ts
packages/api-reference/src/stores/useHttpClientStore.ts
packages/api-reference/src/types.ts

**Problem**
Because the "allTargets()..."-code is defined outside of the usehttpClients() hook, it will only run once (which was probably done due to performance benefits), however this breaks this feature as only the DEFAULT_EXCLUDED_CLIENTS will be applied the first time this runs, and the next time this is meant to run to filter the targets and clients based on the provided user configuration, it is not updated, aka, doesnt work, this is references in #1250.
**Solution**
This commit fixes the bug, and retains the performance benefit by caching the target list using watchEffect to only update/recompute the target list when the configuration changes.
**Further improvements** 
I'm working on an additional fix, that will add the ability to specify clients in specific targets to …

fix: non-working `hiddenClients` configuration option 

---

.changeset/wicked-shoes-switch.md
packages/api-reference/src/components/Content/Operation/OperationAccordion.vue
packages/api-reference/src/components/Sidebar/SidebarElement.vue
packages/components/src/components/ScalarIconButton/ScalarIconButton.stories.ts
packages/components/src/components/ScalarIconButton/ScalarIconButton.vue

In a previous PR I missed two instances of `sm` IconButtons. This PR adds another size instead of changing `sm`

fix: icon button sizes

---

examples/DotNet/DotNet.csproj
examples/DotNet/Program.cs
examples/DotNet/nuget.config

This PR adds a NuGet config file with a pointer to the public feed and the nightly dotnet9 feed to support resolving the required preview4 version of the Microsoft.AspNetCore.OpenApi package.
Once preview4 officially ships, we can remove the nightly feed and use the public preview.
I've also updated the sample to add the OpenAPI endpoint so now the following works:
```
$ dotnet run
...
$ curl http://localhost:5296/openapi/v1.json
{
"openapi": "3.0.1",
"info": {
"title": "DotNet | v1",
},
"paths": {
"/": {
"get": {
"tags": [
"DotNet"
],
"responses": {
"200": {
"description": "OK",
"content": {
"text/plain": {
"schema": {
"type": "string"
}
}
}
}
},
"x-aspnetcore-id": "c8e87a4f-38a7-4e29-b7f7-a40dacbb5380"
}
}
},
"tags": [
{
"name": "DotNet"
}
]
}
```

fix: add dotnet9 package feed and preivew.4 version

---

.changeset/cool-tomatoes-cheer.md
packages/api-reference/src/components/Sidebar/Sidebar.vue
packages/api-reference/src/helpers/parse.ts
packages/api-reference/src/hooks/useSidebar.ts

Currently, `x-displayName` and `x-tagGroups` don’t play well with each other, see #1719.
This PR fixes it. Instead of overwriting the name, and breaking the logic of what belongs to which tag, we’ll just keep an optional `displayTitle` which is used to overwrite `title` (if needed).
**Example**
```yaml
openapi: 3.1.0
info:
title: Tag groups example
x-tagGroups:
- name: fruits
tags:
- fruitPrice
- name: vegetables
tags:
- vegetablePrice
tags:
- name: fruitPrice
x-displayName: price
- name: vegetablePrice
x-displayName: price
paths:
'/fruit/price':
get:
tags:
- fruitPrice
summary: Get fruit price
'/vegetable/price':
get:
tags:
- vegetablePrice
summary: Get vegatable price
```
**Result**

fix: x-displayName & x-tagGroups cancel eachother out, fix #1719

---

packages/api-reference/package.json

I use `vite-bundle-analyzer` way too often to understand what’s bundled. This PR adds `pnpm analyze:standalone` as a script for convenience. :)
The script makes a build, analyzes the bundle and opens this in your browser:

chore: add bundle analyze scripts

---

.changeset/hot-needles-end.md
.changeset/ten-chicken-run.md
packages/api-reference/src/components/Content/Tag/Endpoints.vue
packages/api-reference/src/components/SearchModal.vue

I struck me in the middle of the night: I forgot to add `x-displayName` to the search modal and the tag component.
This PR fixes both issues. :)

fix(api-reference): `x-displayName` is not used in the search modal and the tag component

---

.changeset/funny-taxis-deliver.md
packages/mock-server/src/createMockServer.test.ts
packages/mock-server/src/createMockServer.ts

Currently, the `@scalar/mock-server` doesn’t allow cross origin requests.
This PR adds loose CORS headers to make development (that’s what a mock server is for) easier.

feat(mock-server): add wildcard CORS headers

---

.changeset/smart-eels-work.md
packages/api-reference/src/components/Content/Operation/PathResponses/PathResponses.vue

We’re only showing json example responses, this PR adds support for text/plain responses, too.
See #1758

feat(api-reference): show text/plain example responses, fix #1758

---

.changeset/smooth-coins-search.md
.github/workflows/validate-openapi-file.yml
packages/cli/src/commands/share/ShareCommand.ts
packages/cli/src/utils/index.ts

Currently, you can use `scalar share` to quickly create a sandbox link.
If you’d like to update an existing sandbox, there wasn't anything you could do.
With this PR the share command outputs a token, that you can use to update an existing sandbox.
**Try it**
```bash
pnpm @scalar/cli share https://cdn.jsdelivr.net/npm/@scalar/galaxy/dist/latest.json
```
**Additional improvements**
* `scalar share` works with URLs (and not just local files) now, too :)
* It’s added to CI, to push the `@scalar/galaxy` example to a sandbox
**Preview**

feat(cli): update existing sandboxes

---

.changeset/flat-eggs-sing.md
packages/api-reference/src/components/Content/ClientLibraries/ClientSelector.vue

**problem**
client selector icon depending on display size do not keep their width.
**solution**
this pr add padding and min-width on icons.

fix: client selector style

---

.changeset/honest-eyes-wonder.md
packages/themes/src/components/ResetStyles.vue

Discussed in #1762 
**Solution**
Apply `background-clip: text !important` (`!important` is required) on `input:-webkit-autofill`, so that browser indicator color is not visible.
Actually there are more solutions:
1. Use `transition: background-color 5000000s ease-in-out 0s` to delay color rendering, but it delays all background color transitions, which can introduce unnecessary headaches in the future.
2. Apply `box-shadow`, but there is no way to "clear" background color, only to replace it with another (`inherit` didn't work for me for some reason).
Tested on Mozilla Firefox 125.0 and Google Chrome 124.0.6367.118.

fix: remove yellow/blue autofill indicator

---

packages/docusaurus/README.md

Someone asked [whether it’s possible to render multiple API definitions](https://github.com/scalar/scalar/discussions/1787) with the docusaurus plugin, and yes it is!
This PR adds an example to the README.

docs(docusaurus): multiple api definitions example

---

.changeset/itchy-ants-talk.md
packages/api-reference/src/components/Content/BaseUrl/BaseUrl.vue
packages/api-reference/src/components/Content/Content.vue

When a server URL starts with a variable e.g. `{protocol}`, the URL is prepended with the current URL.
We’ve got a check for http/https and even file in place, but not for variables.
This PR extends the check to work with variables.
See #1755

fix(api-reference): server url with variable is prepended with current URL, fix #1755

---

.changeset/selfish-ghosts-leave.md
packages/api-client/package.json
packages/api-client/src/components/ApiClient/Response/ResponseBody.vue
packages/api-reference/package.json
packages/oas-utils/src/index.ts
packages/oas-utils/src/normalizeMimeType.test.ts
packages/oas-utils/src/normalizeMimeType.ts
packages/oas-utils/src/normalizeMimeTypeObject.ts
pnpm-lock.yaml

Currently, we’re only showing a response body preview for `application/json` (and very few other types), but not for variants like `application/foobar+json`.
With this PR we’re using the recently introduced `normalizeMimeType` helper (and remove the package we used before) to decide whether to render a preview.
Related: https://github.com/scalar/scalar/discussions/1742#discussioncomment-9462321

fix(api-client): doesn’t render preview for mimetype variations like `application/foobar+json`

---

packages/cli/README.md

Users might [run into issues when installing the CLI](https://github.com/scalar/scalar/issues/1786), this PR adds some information to the README to help them to find a workaround.

docs(cli): naming conflicts

---

.changeset/selfish-points-stare.md
packages/galaxy/src/specifications/3.1.yaml
packages/mock-server/src/createMockServer.test.ts
packages/mock-server/src/createMockServer.ts
packages/oas-utils/src/getExampleFromSchema.test.ts
packages/oas-utils/src/getExampleFromSchema.ts

Currently, the mock server just returns static JSON or a generated example (based on a given schema).
Requests to `/planets/{planetId}` are handled, but return a static value.
With this PR, `x-variable` is introduced as an extension to the specification, which tells the mock server to use a given variable for a property.
**Example Schema**
```yaml
Planet:
type: object
properties:
id:
type: integer
x-variable: planetId
```
**Example Response for `/planets/123`**
```json
{
"id": 123,
}
```
I consider this an experimental feature for now, so documentation yet.

feat(mock-server): dynamic values for generated examples

---

.changeset/serious-carrots-beam.md
packages/components/src/components/ScalarDropdown/ScalarDropdown.vue
packages/components/src/components/ScalarFloating/ScalarFloating.vue
packages/components/src/components/ScalarPopover/ScalarPopover.vue
packages/components/src/components/ScalarTextField/ScalarTextField.vue

Because we scope our tailwind CSS coming out of the components library all scalar components need to have the `scalar-component` class on their root element (which I forgot to do for the dropdown).
@amritk we might want to rethink at some point how were handling scoping here or if we even need to handle it anymore.

fix: add scalar component scope to missing components

---

.changeset/breezy-roses-tap.md
packages/api-reference/src/components/Content/ClientLibraries/ClientSelector.vue

**Problem**
responsive issue spotted in sandbox: 
**Solution**
this pr favor the ellipsis icon only according to the selector width:

fix: client selector responsive

---

.github/workflows/deploy-examples.yml

Remove filters from the workflow trigger to ensure the example page is deployed when changes are pushed to main

chore: deploy preview changes to main

---

packages/scalar.aspnetcore/Scalar.AspNetCore.cs
packages/scalar.aspnetcore/ScalarOptions.cs

**Problem**
Currently, there is no way to configure any of the configuration options using Scalar.AspNetCore nuget package
**Solution**
I added a new `MapScalarApiReference` extension which accepts an `Action<ScalarOptions>` which you can use to configure the options, i might have not added all the configuration but i added all of those i could find in the documentation.
There is also the `MapScalarApiReference` extension without any arguments with sensible default options
Please tell me if the code requires more features or "massaging" to get this PR merged as i would really like to use these features with the official nuget package and i think some folks as well.

feat: Adding Options to Scalar.AspNetCore

---

package.json

Currently, the tests fail in the release workflow. That’s because the proxy isn’t running there.
There’s a tiny difference in the scripts now:
* `pnpm test` run the tests locally, assumes the proxy is already running
* `pnpm test:ci` runs the tests in CI, starts the proxy and waits until it’s ready
We had `test:ci` already, but I’ve added to it in #1090.

ci(release): start proxy in release workflow

---

.changeset/little-lies-prove.md
packages/docusaurus/src/theme.css

fixes https://github.com/scalar/scalar/issues/1808
unfortunately pulling in colours from Docusaurus themes doesn't work _perfectly_ so we need to rely on our own variables for sidebar heading types

fix: remove reliance of ifm colour system for docusaurus sidebar heading type

---

.changeset/plenty-poems-scream.md
packages/api-reference/src/components/Sidebar/SidebarElement.vue

Allow text transform of tags with 
new `--scalar-tag-text-transform` variable
remove text transform from all top level items

fix: text transform on all top level sidebar items

---

README.md

We have some CSS examples in the READMEs, but it’s not very obvious that it’s CSS.
This PR wraps the CSS examples in a `style` tag, which could help to make it more obvious. :)

docs(api-reference): improve css examples

---

.github/workflows/validate-openapi-file.yml
packages/cli/README.md

We’ve recently had an issue in CI, where we’ve added a new feature to the CLI workflow, but it wasn’t available - because it used the published version on npm and not the local version.
This PR changes the CLI CI workflow to use the local CLI. This should also help to detect bugs with the CLI earlier. :)

ci: use local cli, instead of the one published on npm

---

packages/components/src/components/ScalarSearchResults/ScalarSearchResultList.vue

The new empty state for the search results shows an empty string "" when there’s nothing loaded.
Actually, I think it’s nicer to not repeat the search string anyway.
Feel free to close the PR if you disagree @cameronrohani.
**Before**
**After**

fix: search results empty state shows empty string

---

.changeset/gold-peas-report.md
packages/oas-utils/src/normalizeMimeType.ts
packages/oas-utils/src/normalizeMimeTypeObject.ts

Currently, the response body preview doesn’t show up when the content-type header isn’t set. That’s bad.
This PR makes sure it’ll still work even if the content-type header isn’t set.
See #1818

fix: response body does not show a preview when the content-type is undefined, fix #1818

---

.changeset/tough-mirrors-begin.md
packages/docusaurus/src/theme.css

fixes: https://github.com/scalar/scalar/issues/1809
Add higher precedence to our Docusaurus global theme variables
@amritk, @hwkr 
I need to do this because now Docusaurus is getting a <style> tag injected on the page which is overriding our docusaurus theme variables, I'm not sure if you're wanting to fix this another way but let's get this fix in ASAP for the time being

fix: Docusaurus preferred colour scheme refresh bug

---

.changeset/smooth-jeans-protect.md
packages/oas-utils/src/getExampleFromSchema.test.ts
packages/oas-utils/src/getExampleFromSchema.ts

**Problem**
Currently, Scalar shows a warning like this when the spec declares union types:
```
[getExampleFromSchema] Unknown property type "string,null".
```
This happens because there is no explicit support for union types in `getExampleFromSchema`. See section [7.6.1](https://json-schema.org/draft/2020-12/json-schema-core#section-7.6.1) of the JSON Schema spec for reference.
**Solution**
With this PR, `getExampleFromSchema` will understand union types and return null for nullable unions or an example for the first types otherwise. Let me know if this makes sense for you.

fix: add support for union types in getExampleFromSchema

---

.changeset/yellow-turkeys-wash.md
packages/components/src/components/ScalarButton/ScalarButton.stories.ts
packages/components/src/components/ScalarButton/ScalarButton.vue

this pr adds a type prop to the scalar button component in order to be able to use it as a `submit` action within a form for instance, along the addition of the `reset` type

feat: scalar button component type prop

---

.changeset/poor-tips-develop.md
packages/api-reference/src/helpers/parse.ts

**Problem**
Currently, OpenAPI 3.1 webhooks do not render correctly. See issue https://github.com/scalar/scalar/issues/1811
This happens because when transforming webhooks in the `parse` function from `@scalar/api-reference`, the originalWebhook variable is assigned to the `PathItem` object instead of the `Operation`, as implied by [this cast](https://github.com/scalar/scalar/blob/22bb58f97660b28a797d0d52f21c33e68fd079ab/packages/api-reference/src/helpers/parse.ts#L91-L94).
**Solution**
With this PR, the originalWebhook variable is correctly assigned to the Operation.
**Note:** the PathItem also has summary and description fields. It might be useful to fall back to them if they are missing in the operation.

fix: webhook operation parsing

---

.changeset/breezy-apples-rhyme.md
packages/api-reference/src/components/Sidebar/Sidebar.vue

fix: indentation bug on groups

---

.changeset/gentle-ducks-itch.md
packages/api-client/src/components/ApiClient/Response/ResponseBody.vue

fix: always return html vs error rendering

---

packages/api-client/src/components/ApiClient/Response/ResponseBody.vue

I feel like we shouldn't allow `any` as a variable type.

fix: don't try to access contentType value which doesn't exist

---

examples/esm-api-reference/index.html
examples/esm-api-reference/package.json
examples/esm-api-reference/src/main.ts
examples/esm-api-reference/tsconfig.build.json
examples/esm-api-reference/tsconfig.json
examples/esm-api-reference/vite.config.ts
packages/api-reference/src/components/ApiReference.vue
packages/api-reference/src/esm.ts
packages/api-reference/src/index.ts
packages/api-reference/src/integration.ts
pnpm-lock.yaml
scripts/bootstrap-package/bootstrap-package.ts

Adds an ESM integration for references. 
Improvements and Future Work:
- The mounted references are always 100% viewport height. Ideally it should be flex and just fill its parent container
- Other integrations should likely use the exported function as their main entrypoint. Standalone should only be used for the script tag integrations (and not in bundled code).

feat: create esm javascript build docs

---

packages/api-client/src/components/SimpleTable/SimpleCell.vue

> [WARNING] Unexpected "var(" [css-syntax-error]
```diff
.simple-row:first-of-type .simple-cell:first-of-type {
border-top-left-radius: var(--scalar-radius);
}
-border-top-left-radius: var(--scalar-radius);
.simple-cell a {
color: var(--scalar-color-1) !important;
}
```
👍

fix: CSS warning

---

.changeset/calm-bugs-hunt.md
packages/oas-utils/src/getExampleFromSchema.test.ts
packages/oas-utils/src/getExampleFromSchema.ts

To generate example responses, we’ll just use empty values.
As suggested in https://github.com/scalar/scalar/discussions/1825 this PR generates example values (in some cases, e.g. response examples) based on the format.

feat(oas-utils): generate random values based on the `format`

---

.changeset/neat-singers-cry.md
packages/api-reference/src/components/Content/BaseUrl/ServerItem.vue

If you click on the server URL, it’s copied to the clipboard. Even if it has variables like `https://example.com/{version}`.
With this example, we try to replace the variables first, but keep the placeholders if the variables aren’t defined.
*  `https://example.com/{foo}` (without foo) copies `https://example.com/{foo}`
*  `https://example.com/{foo}` (with foo: 123) copies `https://example.com/123`

feat: copy server url with replaced variables

---

.changeset/lazy-poems-study.md
packages/api-reference/src/components/MarkdownRenderer/MarkdownRenderer.vue

this pr adds the support of `abbr` HTML tag in api reference, as seen below:

feat: support for `<abbr />` tags, fix #1850

---

.changeset/beige-timers-report.md
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue

Currently, we don't support constants
This PR adds support for constants, and if an enum with just one possible value is given, we treat it like a const (because that’s what people where using it for).
More context in #1846
**Preview**
**Example**
```yaml
openapi: 3.1.0
info:
title: Scalar Galaxy
version: 1.0.0
components:
schemas:
Planet:
type: object
properties:
exists: 
type: string
enum: ['yes']
default: 'yes'
size: 
type: string
enum: ['huge', 'extra huge']
default: 'huge' 
shape: 
const: 'flat'
```

feat(api-reference): support for constants in schemas, fix #1846

---

.changeset/rare-lies-wink.md
packages/api-client/src/components/ApiClient/Request/RequestAuthentication/CardFormGroup.vue
packages/api-client/src/components/ApiClient/Request/RequestAuthentication/CardFormTextInput.vue
packages/api-client/src/components/ApiClient/Request/RequestAuthentication/SecuritySchemeScopes.vue

**Problem**
authentication block style is broken as seen below:
lack of specificity using `where` is not maintaining style one reference is published. this pr is a proposal to remove `where` usage in order to ensure higher style specificity.

fix: api reference auth form style

---

.changeset/big-cherries-grin.md
.changeset/fuzzy-bats-eat.md
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/docusaurus/src/theme.css

Set the Docusaurus theme variables on `<body>` instead of `.scalar-api-reference` so they apply to toasts (and anything else that's outside of that element, headless ui?) 
Also moves the references CSS variables to a `scalar-config` CSS layer so they can be overridden without using `!important`.

fix: set theme variables to Docusaurus theme at root

---

.changeset/spicy-dodos-remain.md
packages/api-client/src/helpers/getRequestFromAuthentication.ts
packages/mock-server/src/createMockServer.ts
packages/mock-server/src/utils/anyBasicAuthentication.ts
packages/mock-server/src/utils/authenticationRequired.ts
packages/mock-server/src/utils/index.ts
packages/mock-server/src/utils/isAuthenticationRequired.ts
packages/mock-server/src/utils/isBasicAuthenticationRequired.ts
packages/mock-server/tests/authentication.test.ts

I missed a way to test authentication with our mock server today.
So, I’ve had to do a little midnight hack session and … add HTTP basic authentication to the mock server. :)

feat(mock-server): http basic auth

---

.changeset/poor-ghosts-matter.md
packages/cli/package.json

Currently, users might run into conflicts with the existing `scalar` CLI that Microsoft built.
When installing, they can overwrite the other CLI and use ours as `scalar`. There’s also a note in the README on the matter. I’ve did a ton of reading, trying to find a good solution, here’s a short summary:
* We could just change the name to be something else, but I couldn’t come up with one that is as cool as `scalar`.
* We could ship executables with bun, which we’ll probably do at some point in the future, but it would require us to build/support/publish binaries for the various platforms in a convenient way, which adds a lot of complexity in multiple areas that I’d like to avoid at this point.
* We can’t hook into the install process to react to the error.
This PR suggests a pragmatic …

chore(cli): provide alternative name for the CLI

---

.changeset/funny-snakes-kick.md
CONTRIBUTING.md
packages/components/README.md
packages/components/postcss.config.js
packages/components/src/components/ScalarDropdown/ScalarDropdown.vue
packages/components/src/components/ScalarFloating/ScalarFloating.vue
packages/components/src/components/ScalarPopover/ScalarPopover.vue
packages/components/src/components/ScalarTextField/ScalarTextField.vue
packages/components/src/cva.ts
packages/components/src/tailwind/tailwind.css

So this this will unscope our components tailwind classes in favor of just putting them in a layer that's super easy to override. This means we might technically have leaky component css **but** it should never override a consuming apps classes.

refactor: remove :where prefix in favor of cascade layers

---

packages/api-reference/src/components/Content/Schema/SchemaProperty.vue

**Problem**
Currently, scalar does not have support for the [x-enumDescriptions extension](https://redocly.com/docs/api-reference-docs/specification-extensions/x-enum-descriptions/) which redocly uses to support displaying a table with individual descriptions for enum values.
This happens because there is currently no support in scalar for this extension.
**Solution**
With this PR `x-enumDescriptions` is supported and displays a table with enum value -> description mappings when populated for an enum.
***Sample***
***Example OpenAPI***
```yaml
openapi: 3.1.0
info:
title: Scalar Galaxy
version: 1.0.0
components:
schemas:
User:
type: object
properties:
status:
type: string
enum:
- ACTIVE
- INACTIVE
role:
type: string
enum:
- ADMIN
- MEMBER
x-enumDescriptions:
ADMIN: Can do …
```

feat(api-reference): support x-enumDescriptions

---

.changeset/tough-lizards-think.md
packages/api-client/src/components/ApiClient/Request/RequestAuthentication/CardFormTextInput.vue
packages/components/src/components/ScalarIcon/icons/Hide.svg
packages/components/src/components/ScalarIcon/icons/Show.svg

Fixes some icon shift for the show hide password field and updates the icon to align with our standards.
https://github.com/scalar/scalar/assets/6374090/6ddd8cbb-d8e8-4b84-8fb8-d1aa67fcddf6

fix: align show hide icons with icon standards

---

packages/cli/package.json
packages/cli/src/commands/bundle/BundleCommand.ts
packages/cli/src/commands/mock/MockCommand.ts
packages/cli/src/commands/validate/ValidateCommand.ts
packages/cli/src/utils/getHtmlDocument.ts
packages/cli/src/utils/getOperationByMethodAndPath.test.ts
packages/cli/src/utils/getOperationByMethodAndPath.ts
pnpm-lock.yaml

I was trying to resolve the CLI alias issue and saw a few minor things I’d like to clean up.
* Remove `openapi-types` as a dependency (we can use the `@scalar/openapi-parser` types instead)
* Fix the `cli:link` script for local development
* Remove an unused import

chore(cli): remove openapi-types

---

.eslintrc.cjs
packages/api-client/src/components/ApiClient/Request/RequestAuthentication/SecuritySchemeScopes.vue
packages/api-client/src/components/ApiClient/Response/Response.vue
packages/api-client/src/components/CollapsibleSection/CollapsibleSection.vue
packages/api-client/src/components/Grid/GridHeader.vue
packages/api-client/src/components/Grid/GridRowEditable.vue
packages/api-client/src/components/ScalarAsciiArt.vue
packages/api-client/src/helpers/sendRequest.test.ts
packages/api-reference/src/helpers/parse.ts
packages/play-button/src/index.ts

I just found out we removed ESLint from CI, I’m not even sure if this was intentional. Anyway, I think it’s good this way. It would have added some extra work in some PRs, without really preventing any bad errors.
That said, I feel better if we go through the errors and warnings every now and then, though. This PR fixes all ESLint errors and some of the warnings (mostly unused code or imports).
Note: It seems the play button doesn’t support the `data-proxy-url` API, because the relevant code isn’t used. I think it’s fine to remove it. It’s not mentioned in the README (for the play button), no one complained and you can always pass the proxy with the configuration object anyway.

chore: fix all linter errors

---

.changeset/big-carrots-occur.md
packages/api-reference/src/components/Section/Section.vue
packages/api-reference/src/hooks/useNavState.ts

**Problem**
webhooks sidebar heading doesn't get toggled when navigating over a webhook section, nor when we navigate toward webhook section url.
https://github.com/scalar/scalar/assets/14966155/9e08e635-be30-4a40-9896-14021ec1fd2f
**Solution**
this pr is a proposal in order to open webhooks sidebar heading group on a webhook section scroll.

fix: sidebar webhooks

---

.changeset/perfect-bags-swim.md
packages/galaxy/src/specifications/3.1.yaml

We’ve had a special case in our example: Headings inside an `<details>` tag. Which isn’t really compatible with our way to split the Markdown content in sections. Fixing it (for example adding ids to the headings, not splitting the content in sections) would make it harder to show an accurate active state in the sidebar.
This PR just removes the headings from inside the `<details>` tag. Looks the same, but isn’t anymore in the sidebar, which is actually better IMHO.

chore(galaxy): remove headings from details tag

---

packages/galaxy/package.json

This PR adds a script to preview the `@scalar/galaxy` example and watch for changes. Great to see the results right-away while editing the example specification.

chore(galaxy): add a preview script

---

tsconfig.json

Reverts the TS Config change in #1891, because CI broke with TS errors in various libraries.

chore: revert tsconfig change

---

.changeset/small-zoos-sell.md
packages/api-reference/src/components/Content/Models/ModelsAccordion.vue
packages/api-reference/src/components/Content/Schema/Schema.vue
packages/oas-utils/src/getExampleFromSchema.test.ts
packages/oas-utils/src/getExampleFromSchema.ts
packages/oas-utils/src/getRequestBodyFromOperation.test.ts
packages/oas-utils/src/getRequestBodyFromOperation.ts

Currently, we’re generating empty request bodies from the schema, which always includes all properties. Sometimes, we can prefill the fields with values, but mostly we can’t. This can be annoying when there’s a ton of optional properties (with invalid values).
With this PR only required properties and properties with an example value are added to the request body, others are omitted, as suggested in #933.
**Other changes**
* The request body didn’t show properties that have `required: true` as required (only if they were in `required: […]` one level above).
* With `additionalProperties` you can define arbitrary properties. We used to pick `someKey` as an example. I changed it to `{{key}}` because I think it’s more clear. It’s the variable syntax we use in other places already.
**Example** …

feat: do not include properties with unknown values in generated examples, fix #933

---

.changeset/honest-coats-hope.md
packages/components/src/components/ScalarDropdown/ScalarDropdownItem.vue

Create better variance between dropdown items + dropdown toggles
before:
after:

fix: update dropdown styles

---

.changeset/light-snails-bathe.md
packages/api-reference/src/components/Content/Operation/PathResponses/PathResponses.vue

Fixing issue where status codes having different example responses would cause an error.
**Problem**
Currently, an error occurs when switching between response codes with different names for examples. This is issue #1624 
This happens because the `selectedExampleKey` value isn't reset when switching tabs, which causes an error when attempting to find that value in the examples object
**Solution**
With this PR, the `selectedExampleKey` value is reset when changing tabs and the logic to determine the first example has been updated to account for a single example, a list of examples, and a object of examples (named examples).

fix: different response examples for different status codes

---

.changeset/yellow-guests-tickle.md
packages/components/src/components/ScalarListbox/ScalarListbox.vue

fix:
list box focus state now has a bg

fix: focus on scalar list box

---

.changeset/silly-beds-call.md
packages/api-reference/src/components/Content/Operation/PathResponses/PathResponses.vue

Currently, we’re always moving the `default` example response to the first position. Turns out, most people use `default` as a fallback and it doesn’t really make sense to have it as the first example response.
With this PR, all example responses are ordered alphabetically (new!) and default just comes after all numbers (new!).
Wdyt @marclave?
More context: https://github.com/scalar/scalar/discussions/1148

fix(api-reference): default example response is always the first example

---

.changeset/wet-lizards-brake.md
packages/api-client/src/components/ApiClient/Response/ResponseBody.vue

If an request fails, we just show an empty request body. With this PR the Axios error message is shown.
As an alternative, we could also add some min-height or show a special component for empty response bodies. But I’m always staring at the response body and would love to see if something goes wrong right-away.
**Before**
**After**

feat(api-client): better error output for failed requests

---

packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue

Fix https://github.com/scalar/scalar/discussions/1956
Currently, `min` and `max` equal to 0 restrictions are not rendered, also the `extrictMinimum`and `extrictMaximum`properties are not handled. 
This happens because `0` is falsy in Javascript, so the condition isn't satisfied and the min|max property is not rendered.
Also components for "extrictMinimum" and "extrictMaximum" are missing.
**Solution**
With this PR the condition to check if `value.minimum`or `value.maximum` are defined were refactored to check if the values are different from `undefined`, so "min=0" satisfies the condition.
"greater than" and "less then" schema property details were added to handle extrict minimum and maximum.
> ⚠️ "greater than" and "less than" were chose to avoid breaking changes, but it would be also …

fix: handle extrict minimum and maximum properties

---

.changeset/brave-islands-explode.md
packages/api-client/src/helpers/redirectToProxy.ts
packages/client-app/src/libs/sendRequest.ts

Currently, we just pass the request URL to the proxy (https://proxy.scalar.com?scalar_url=OUR_TARGET_URL_HERE) and this works for most cases.
It turns out, not in all cases. :) Actually we need to encode the target URL when adding it to the `scalar_url` parameter, otherwise we’ll get an error from the proxy:
**✅ Works (regular URL)**
https://proxy.scalar.com/?scalar_url=https://example.com/
**❌ Doesn’t work (has a whitespace)**
https://proxy.scalar.com/?scalar_url=https://example.com/?query=apple+banana
**✅ Works (encoded)**
https://proxy.scalar.com/?scalar_url=https%3A%2F%2Fexample.com%3Fquery%3Dapple%2Bbanana

fix(api-client): URL is not encoded when sent to the proxy

---

.changeset/great-news-grab.md
examples/web/src/App.vue
examples/web/src/style.css
packages/api-client/vite.config.ts
packages/api-reference/vite.config.ts
packages/build-tooling/src/build-options.ts

This fixes the auto importing of css. The ID's were missing per app so it thought the style was already loaded.

fix: autoimport css in standalone

---

packages/themes/src/components/ScrollbarStyles.vue

Looks like something with our changes in build tooling changed how we're parsing CSS modules and we can't use `:global` the way we were before.
We can probably change how we're doing this in the future but for now this PR fixes the regression.
https://github.com/scalar/scalar/assets/6374090/30c5ca0e-da47-46be-a75a-7744e16cf887

fix: make custom scroll :global again

---

.changeset/empty-terms-visit.md

Currently our release build is broken due to this reference to the removed `use-modal` package. This should fix it

fix: release build

---

packages/api-client-modal/src/components/ApiClientModal.vue
packages/client-app/src/views/Request/ResponseSection/ResponseSection.vue

this pr fixes api client modal scroll from being stuck as of right now by giving it a height.

fix: api client modal scroll fix

---

packages/client-app/src/components/AddressBar/AddressBar.vue

this pr updates client app address bar font style to maintain consistency and adds paste handling to fixe line breaks:
**before**
**after**

fix: api client modal address bar fix

---

package.json
packages/api-client-modal/package.json
packages/api-client-proxy/package.json
packages/api-client/package.json
packages/api-reference/package.json
packages/echo-server/package.json
packages/fastify-api-reference/package.json
packages/galaxy/package.json
packages/themes/package.json
packages/themes/src/index.test.ts
packages/themes/src/utilities/legacy.test.ts
packages/use-codemirror/package.json
packages/use-toasts/package.json
packages/use-tooltip/package.json
playwright/tsconfig.json
pnpm-lock.yaml

Breaking out some work that I did while down the rabbit hole trying to fix the the `themes` snapshot testing. 
This PR re-enables most of the themes testing except for two tests that using `toMatchFileSnapshot()` which still requires some work to fix our environment. 
Also fixes the tsconfig path in the playwright package and upgrades `@vitest/coverage-v8` to `1.6.0` fixing some peer dependency warnings.

chore: upgrade vitest coverage

---

packages/oas-utils/src/entities/workspace/server/server.ts
packages/oas-utils/src/transforms/import-spec.ts

**Problem**
openapi can have relative URLs for servers, which a good use case is for our integrations which are hosted docs on the api server
zod url doesnt allow for relative url
**Solution**
we just make sure its a valid string now

fix: zod url doesnt allow relative url for parsing

---

packages/oas-utils/src/entities/workspace/server/server.ts

variables can be nullable inside of servers :) 
https://swagger.io/docs/specification/api-host-and-base-path/

fix: allow nullable in servers as per openapi spec

---

packages/client-app/src/components/AddressBar/AddressBar.vue
packages/client-app/src/components/HttpMethod/HttpMethod.vue

Removed click events and chevron from HTTP verb
and removed the add server

fix: remove click events from http verb + adding server in address bar

---

packages/components/src/components/ScalarCodeBlock/ScalarCodeBlock.vue

fix: docusaurus pre background

---

.changeset/fifty-gorillas-smoke.md
README.md
packages/api-reference/README.md
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/Content/Content.vue
packages/api-reference/src/types.ts

if you dont have servers in your spec, and you cant update them due to build pipeline we allow you to override it :) like so
```vue
<ApiReference :configuration="{ servers: [{ url: 'https://api.scalar.com', description: 'Production server' }] } />
```

feat: add base server override

---

packages/components/src/components/ScalarCodeBlock/ScalarCodeBlock.vue

fix: wrapped code blocks

---

packages/client-app/src/views/Servers/ServerForm.vue

It’s bugging me, that the optional field is coming first. And I don’t think it’s a description, it’s more a label or something. And the placeholder wasn’t really a good fit.
**Before**
**After**

chore(client-app): switch server form fields

---

examples/proxy-server/main.go
packages/client-app/src/libs/sendRequest.ts

Since we switched to the new proxy, only some headers are shown. By default, only some headers can be accessed for cross-origin requests.
This PR adds the `Access-Control-Expose-Header` with a `*` wildcard value to allow JS to access all headers.
Read more: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#access-control-expose-headers
**Preview**
EDIT: This must be a flaky test? Can you take a look @geoffgscott?
>  FAIL  |@scalar/object-utils| src/mutator-record/mutations.test.ts > Handles history rolling > Rolls history back to initial then forward to modified state
AssertionError: expected { storage: [ { …(3) }, …(2) ], …(2) } to not deeply equal { storage: [ { …(3) }, …(2) ], …(2) }

fix(proxy-server): only some headers are shown

---

packages/client-app/src/components/AddressBar/AddressBar.vue

this pr handle how server dropdown is displayed in address bar within api client modal and client app:
`api client modal`
one server
multiple server
`client app`
one server
multiple servers

feat(client-app): client app address bar server dropdown

---

packages/client-app/src/libs/sendRequest.test.ts
packages/client-app/src/libs/sendRequest.ts
packages/client-app/src/views/Request/RequestSection/RequestPathParams.vue

fix(client-app): path variable replacement in api client modal

---

lefthook.yml
packages/build-tooling/package.json
packages/build-tooling/rollup.config.ts
packages/build-tooling/src/index.ts
packages/build-tooling/src/rollup-options.ts
packages/build-tooling/src/workspace-reload.ts
packages/client-app/vite.config.ts
pnpm-lock.yaml

Adds a vite plugin to watch for workspace file changes. When files in package `dist` folders change we restart the vite server automatically.

feat: Add vite plugin to restart dev server when workspace files change

---

packages/api-client-modal/src/api-client-modal.ts
packages/api-reference/src/components/ApiClientModal.vue
packages/api-reference/src/components/SearchButton.vue
packages/api-reference/src/components/api-client-bus.ts
packages/client-app/src/components/ScalarHotkey.vue
packages/client-app/src/components/Search/SearchButton.vue

this pr fixes the api reference search being display on hotkey pressed while api client modal is open in order to displays its own.

fix: api client modal search

---

packages/client-app/package.json
packages/client-app/src/components/HelpfulLink.vue
packages/client-app/src/libs/sendRequest.ts
packages/client-app/src/views/Request/ResponseSection/ResponseMetaInformation.vue
packages/client-app/src/views/Request/ResponseSection/ResponseSection.vue
packages/oas-utils/src/entities/workspace/spec/requests.ts
pnpm-lock.yaml

this pr adds response meta informations in the client app:

feat(client-app): client app reponse meta infos

---

README.md

Currently, the CONTRIBUTING guide is below the avatar wall. Maybe it’s a little bit too hidden there, let’s move it above avatar wall.
**Before**

docs: move contributing guide up

---

.changeset/cyan-kiwis-warn.md
packages/client-app/src/components/Sidebar/Sidebar.vue
packages/components/src/components/ScalarModal/ScalarModal.vue

this pr adds some base styles in order to fix new api client modal glitch with docusaurus:
**before**
**after**

fix(docusaurus): api client modal

---

packages/client-app/src/views/Request/RequestSection/RequestSection.vue

this pr fallbacks on 'all' section when navigating to an endpoint without body if the latter is active + displays body on delete http method.

feat(client-app): section navigation

---

.github/workflows/ci.yml

**Problem**
Currently, our CI is taking a long time.
This happens because we are testing on node 18, 20, and 21
**Solution**
With this PR we will only run testing in CI on node 18 (maintenance) and 20 (LTS)

chore: do not run ci on node 21

---

packages/api-reference/src/components/Content/ClientLibraries/ClientSelector.vue

**Problem**
Not visible client libraries select with dark theme
Bad styling for select
**Solution**
After

style: client library select dark theme fix

---

.github/workflows/release.yml

Currently, the created PRs are automatically created, but through my account. That was necessary to auto approve them, which we removed in #2087.
I think we can use the default GITHUB_TOKEN now and the PRs should be created by the GitHub bot.
Note: There’s no way to test this other than merging it. If it breaks the release workflow for some reason (I can’t think of one), just revert the PR.

ci: use GitHub bot to create PRs

---

.changeset/clean-readers-unite.md
packages/galaxy/package.json
packages/galaxy/scripts/format.sh
packages/galaxy/scripts/format.ts

Currently, we use a bash script and the CLI to build/format the `@scalar/galaxy` package. If this breaks, for some reason, it’s hard to fix and blocks CI.
This PR uses a Node script instead. If that breaks and blocks CI, it’s easy to modify.
Note: This is extracted from #2091.

chore(galaxy): use Node script instead of bash script

---

.changeset/silent-ears-play.md
packages/themes/src/presets/kepler.css

**Problem**
using rgba with opacity on the kepler theme mode cause issue on css mask usage in the api client.
**Solution**
this pr fixes #2106 by favoring hex color over rgba in the kepler theme,

fix(themes): kepler theme dark mode

---

.changeset/young-students-add.md
packages/components/src/components/ScalarCodeBlock/ScalarCodeBlock.vue

fix: docusaurus border radius

---

.changeset/gentle-horses-push.md
packages/api-reference/src/components/ApiReferenceLayout.vue

this pr disables the new api client modal in the api reference until we set the style properly in order to avoid root style overlap which are causing issues on docs.

fix(api-reference): api client modal style overlap

---

.github/workflows/release.yml

Reverts scalar/scalar#2117
Doesn’t seem to work, GitHub Actions says: `HttpError: Resource not accessible by integration`

ci: [revert] use GitHub bot to create release PRs

---

packages/client-app/src/views/Request/Request.vue

this pr conditions the hide action icon from the client app in order for it to be displayed only when used within a reference as a client modal.
**before**

fix(client-app): display hide icon in reference only

---

examples/cdn-api-reference/src/index.ts
examples/cdn-api-reference/src/public/api-reference-local.html
examples/cdn-api-reference/src/public/play-button-local.html
playwright/tests/jsdelivr.spec.ts
playwright/tests/local.spec.ts

I saw the CDN example had code to serve all static files already, so there’s no need to register all routes individually.

chore(cdn-api-reference): simplify cdn server

---

.changeset/sour-feet-applaud.md
packages/docusaurus/src/ScalarDocusaurusCommonJS.tsx
packages/docusaurus/src/index.ts

**Problem**
If you are using an older version of docusaurus it breaks our api reference react package
because we dont handle commonjs
**Solution**
we load the standalone versions since we arent doing ssr anyways :)

fix: support commonjs docusaurus builds

---

.changeset/flat-grapes-bake.md
packages/docusaurus/src/index.ts

**Problem**
we .json() so we cant load yaml
This happens because yaml cant be parsed as json
**Solution**
we just grab it as text :)

fix: dont parse json from fetch just as text

---

.changeset/hungry-guests-arrive.md
packages/api-reference/src/standalone.ts

**Problem**
you could not force initial dark mode
because lightmode was always added
**Solution**
With this PR we check config on initial set

fix: standalone always defaults to light mode

---

.changeset/green-rabbits-allow.md
packages/api-client/src/components/ApiClient/Request/Request.vue

fix: add api client right to scope

---

.github/workflows/ci.yml
.github/workflows/deploy-examples.yml
.github/workflows/deploy-preview-examples.yml
.github/workflows/release.yml
.github/workflows/test-cdn-jsdelivr.yml
.github/workflows/test-cdn-local.yml
.github/workflows/test-nuxt-integration.yml
.github/workflows/validate-openapi-file.yml

Looks like the Cache for Turborepo isn’t used anymore (since we switched to Turborepo 2?).
This PR brings it back to speed up CI. :)
It’s also nice because we’re using the official `actions/cache@v4` now.

ci: use turborepo cache again

---

packages/client-app/src/components/DataTable/DataTableCell.vue

this pr sets data table width based on its type in order to enhance style alignment on checkbox hover:

fix(client-app): data table cell checkbox width

---

README.md
documentation/nextjs.md

I was testing the Next.js integration today and used the opportunity to write a detailed integration guide.
@amritk I’m not really sure I did a good job describing what to use when, would you mind to check it’s not completely off?

docs: add a detailed Next.js integration guide

---

.github/workflows/lint-pr.yml
.github/workflows/test-cdn-jsdelivr.yml
.github/workflows/test-cdn-local.yml
.github/workflows/test-nuxt-integration.yml
examples/cdn-api-reference/src/index.ts
playwright/playwright.config.ts

The playwright workflow has a comment that indicates the Playwright binary caching doesn’t work. Let’s fix this.
With this PR browsers aren’t installed if they are cached, but required system dependencies are installed always:
```yaml
- name: Install Playwright browsers
run: npx playwright install
if: steps.playwright-cache.outputs.cache-hit != 'true'
- name: Install Playwright dependencies
run: npx playwright install-deps
```
This PR also changes the trigger for the Nuxt integration test. It’ll run on every PR now.

ci: playwright cache

---

.changeset/cyan-knives-add.md
packages/api-reference/src/hooks/useSidebar.test.ts
packages/api-reference/src/hooks/useSidebar.ts

If x-tagGroups are used, the webhooks don’t show up anymore. See #2172 for more context.
This PR adds test for `useSidebar` (finally!) and fixes the bug.
**Example Definition**
https://gist.githubusercontent.com/hkosova/e1b6ce4d72a3ec722ad4802d77f7e3e4/raw/fa790231d345af0c4779b01f6e81a7937a229030/webhooks-tag-groups.json

fix: doesn’t show webhooks when x-tagGroups are used, fix #2172

---

.changeset/gorgeous-sheep-check.md
examples/nextjs-api-reference/app/reference/route.ts
packages/nextjs-api-reference/src/ApiReference.ts

I just found out that our Next.js integration doesn’t have support for URLs as promoted in the README:
```diff
import { ApiReference } from '@scalar/nextjs-api-reference'
const config = {
spec: {
+    url: 'https://cdn.jsdelivr.net/npm/@scalar/galaxy/dist/latest.json',
},
}
export const GET = ApiReference(config)
```
This PR adds support for URLs.
Before, the plugin always passed `content`, but ignored `url`. 
This PR also adds support for YAML content, the CDN version doesn’t supports it yet though (not if it’s passed as content of the `script` tag, only if it’s in the configuration object).

feat(next): URL support

---

.changeset/blue-pillows-drop.md
examples/cdn-api-reference/src/public/api-reference-jsdelivr-json-content.html
examples/cdn-api-reference/src/public/api-reference-jsdelivr-yaml-content.html
examples/cdn-api-reference/src/public/api-reference-local-json-content.html
examples/cdn-api-reference/src/public/api-reference-local-yaml-content.html
packages/api-reference/src/standalone.ts
playwright/tests/jsdelivr.spec.ts
playwright/tests/local.spec.ts
playwright/tests/testApiReference.ts
playwright/tests/testPlayButton.ts

WIP Tests are failing. :)
I saw that the HTML API does not support YAML content inside the `<script>` tag, this PR should fix it.
I’ve added some more test cases for the various ways to pass content to the CDN build. 
Once we released this fix here, we can enable the jsdelivr test for YAML content inside the `script` tag, too.

fix(standalone): HTML API does not parse YAML content

---

packages/client-app/src/views/Request/Request.vue

currently we have to key up and key down both keys in order to toggle the sidebar, however sometimes we might keep the meta key down to have a glimpse on the navigation.
this pr is a proposal to favor useEventListener over whenever, i haven't been able to reach the same result otherwise.

feat(client-app): sidebar toggle hotkey

---

.changeset/sharp-drinks-deny.md
packages/components/src/components/ScalarIcon/ScalarIcon.vue

this pr favors shallow ref over ref usage in scalar icon component and ensures that only the reference to the icon component is reactive + fix log errors.

fix(components): scalar icon ref

---

packages/client-app/src/components/ActionModal/ActionModalRequest.vue
packages/client-app/src/components/AddressBar/AddressBar.vue

this pr fixes some outline in the client-app package.

fix(client-app): update input outline style

---

packages/client-app/src/views/Request/RequestSection/RequestBody.vue
packages/client-app/src/views/Request/RequestSection/RequestParams.vue

this pr adds back the checkbox style on data table cell component for the client app:

fix(client-app): add data table cell checkbox style back

---

examples/docusaurus/package.json
packages/docusaurus/package.json
pnpm-lock.yaml

I just saw that we’re using `tsc` only to build the `docusaurus` package. Using `tsc` the `./dist` will keep its files. This is dangerous if you’re testing locally, because you might get files that won’t exist in CI anymore.
With this PR the `./dist` folder is removed before build.

chore(docusaurus): empty folder on build

---

.github/workflows/update-contributors.yml

I just saw that our update-contributors workflow is broken for a while:
> Request failed due to following response errors:
> - Your token has not been granted the required scopes to execute this query. The 'name' field requires one of the following scopes: ['read:org'], but your token has only been granted the: ['repo'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.
I just created a new token and added a comment to the workflow for future us.

ci(update-contributors): add a comment about the token

---

packages/client-app/src/components/AddressBar/AddressBar.vue
packages/client-app/src/components/AddressBar/AddressBarHistory.vue
packages/client-app/src/store/workspace.ts
packages/object-utils/src/mutator-record/handlers.ts

I think we can make this better... but here for feedback!
some ideas:
we can also think about this post modal integration
https://github.com/scalar/scalar/assets/6176314/6e77a32f-35db-4cca-980e-790befb9fdf9

fix: bring back request history for client app

---

.changeset/silly-beds-retire.md
examples/docusaurus/docusaurus.config.ts
packages/docusaurus/src/ScalarDocusaurus.tsx
packages/docusaurus/src/ScalarDocusaurusCommonJS.tsx
packages/docusaurus/src/index.ts

We brought back the CommonJS build for Docusaurus yesterday, but I think we broke URLs.
I’ve refactored the server side function to do the following:
* Execute a callback for the content, if provided
* Delete the `spec.content` attribute from the configuration and add it as content to the script tag (good, because we just use raw JSON/YAML here):
* strings are just printed as they are
* objects are JSON.stringified
* The remaining configuration is added as an attribute
Note: With this PR URLs are fetched in the frontend, which adds support for relative URLs (see https://github.com/scalar/scalar/discussions/2171). To fetch the document on the server side, just add your fetch call to the configuration and pass the result as `spec.content`. :)
This PR also comes with examples for the various …

fix(docusaurus): doesn’t support (relative) URLs

---

.github/workflows/ci.yml

Some tasks don’t need to be run in Node 18 and 20, I think `types:check` is one of them.
With this PR it’s only executed for Node 20, not for Node 18.
As this takes ~1m it should speed up CI a little bit.

ci: type check only once

---

.changeset/fuzzy-bags-smile.md
examples/cdn-api-reference/package.json
examples/echo-server/package.json
examples/express-api-reference/package.json
examples/fastify-api-reference/package.json
examples/hono-api-reference/package.json
packages/api-client-proxy/package.json
packages/echo-server/package.json
packages/void-server/README.md
packages/void-server/example/index.ts
packages/void-server/package.json
packages/void-server/rollup.config.js
packages/void-server/src/createVoidServer.test.ts
packages/void-server/src/createVoidServer.ts
packages/void-server/src/index.ts
packages/void-server/tsconfig.build.json
packages/void-server/tsconfig.json
pnpm-lock.yaml

Hey, this PR comes with a rewrite of `@scalar/echo-server` under a new name.
`@scalar/void-server` is a HTTP request mirror. Whatever request you send, it’ll reply with all the request data. This is so, so great for testing the API client. :)
**New**
* Works with Hono, instead of Express
* New Name (will be released as `@scalar/void-server@2.0` and we’ll deprecate `@scalar/echo-server@1.x`)
* The example is in the package folder
**Special routes**
* /404 returns an error
* *.zip returns a Zip file
**Example response**
```json
{
"headers": {
"accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
"accept-encoding": "gzip, deflate, br, zstd",
"accept-language": …
```

feat: new `@scalar/void-server`

---

README.md

Oops, there are two broken links in the README. Let’s update the package table and remove swagger-editor and swagger-parser, and add a few new ones. I’ve also gone through the description and made them all shorter.
And you know? We can switch to relative links. That’s way cooler, because it points to the files in the same branch/PR then.

docs: update the package table

---

.changeset/smart-papayas-compare.md
packages/components/src/tailwind/tailwind.css

this pr adds the `:where` pseudo element to tailwind component stylesheet in order to maintain low specificity on component usages + fixes api reference style on new api client modal activation.

fix(components): tailwind specificity

---

packages/client-app/src/components/Sidebar/Sidebar.vue

this pr is a proposal to hide the client modal header in read only mode as it could be misleading:

feat(client-app): hide header in read only mode

---

.changeset/clever-mice-kick.md
packages/express-api-reference/src/expressApiReference.ts

**Problem**
When used together with security middlewares like [Helmet](https://helmetjs.github.io/) which disable content sniffing, or manually setting the header `X-Content-Type-Options` to `nosniff`, the API documentation is rendered as plain text.
`@scalar/express-api-reference` doesn't set any content-type.
**Solution**
This PR explicitly sets the content-type of the initial HTML response to `text/html`.

fix(express-api-reference): explicitly set content-type to text/html

---

.github/workflows/ci.yml
README.md
documentation/configuration.md
documentation/elysiajs.md
documentation/fastify.md
documentation/go.md
documentation/laravel-scribe.md
documentation/laravel.md
documentation/markdown.md
documentation/nitro.md
documentation/openapi.md
documentation/platformatic.md
documentation/rust.md
documentation/themes.md
examples/docusaurus/README.md
examples/proxy-server/README.md
packages/api-reference-react/README.md
packages/api-reference/README.md
packages/docusaurus/README.md
packages/fastify-api-reference/README.md
packages/nextjs-api-reference/README.md
packages/nextjs-api-reference/src/ApiReference.ts
packages/nuxt/README.md
packages/play-button/README.md
packages/scalar_fastapi/README.md
packages/void-server/README.md

Hot take: The root README is too long.
This PR moves most of the content to the package READMEs or separate Markdown files in the `documentation/` folder. The separate files need love, too, but let’s focus on the root README in this PR.
Other changes:
* I’ve updated the features list in the root README
* I’ve made the `ci.yml` name shorter, so the badge becomes smaller
Some links are broken now, because they point to `main` and the new files aren’t in `main` yet. But I think we have to use absolute URLs for Markdown files that are published on npmjs.com.
Preview: https://github.com/scalar/scalar/blob/de76754db35942c206858c2143428ceeaeb90d27/README.md

docs: trim down root README

---

.eslintrc.cjs

We recently introduced a warning for code lines and comments longer than 120 characters. 
This highlights a lot of the existing comments, and I don't think it makes much sense to manually wrap them to fit into that length. It’s just one thing that I need to manually deal with and think about, especially when updating comments and adding content somewhere before the line break.
For some coments, it doesn’t make sense to wrap them:
And if someone is annoyed by the long comments, there’s a setting in VS Code (and other editors) to automatically wrap lines.
Long code lines = complexity, long comments = valuable information.
I’d say, let’s keep the limit for the code, but not for the comments. :)

chore: remove ESLint `max-len` for comments

---

.changeset/long-radios-punch.md
packages/api-reference/src/components/Content/Operation/PathResponses/ExampleResponse.vue
packages/api-reference/src/helpers/mergeAllObjects.test.ts

this pr is a proposal to fix #2137 in order to merge objects in response example for allof items.

fix(api-reference): allof items merge objects

---

.changeset/honest-geese-chew.md
examples/web/src/pages/EmbeddedApiReferencePage.vue
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/MobileHeader.vue
packages/api-reference/src/components/Sidebar/Sidebar.vue
packages/client-app/src/App.vue
packages/docusaurus/src/theme.css

This PR allows for users to easily add custom headers and footers by removing overflow:auto from `.api-reference` and instead relying on `<html>` for scrolling
We're already had to take this approach on Docusaurus so I think it will make sense to move forward with this approach for scalar
In order to support scalar users who have hacked adding a header I created `--scalar-y-offset` which applies the offset on how far scalar is pushed down on the page and assumes that is the desired header height. I imagine we'll remove this in a few months. 
Here's how a user will add a header (I'll add an example to the CDN as soon as this gets in 😄 )

feat: allow custom header & footers

---

.changeset/six-planets-buy.md
packages/client-app/index.html
packages/client-app/src/App.vue
packages/client-app/src/components/AddressBar/AddressBar.vue
packages/client-app/src/main.ts
packages/client-app/src/views/Request/RequestSidebarItemMenu.vue
packages/components/src/components/ScalarFloating/ScalarFloating.vue
packages/components/src/components/ScalarFloating/types.ts

ScalarDropdown [merges the class onto the dropdown](https://github.com/scalar/scalar/blob/main/packages/components/src/components/ScalarDropdown/ScalarDropdown.vue#L24) so we can just add the class directly to the dropdown component.

feat(client-app): add scalar-client class to teleported dropdowns

---

.changeset/tame-pumpkins-judge.md
packages/void-server/package.json
packages/void-server/src/createVoidServer.test.ts
packages/void-server/src/createVoidServer.ts
packages/void-server/src/utils/createHtmlResponse.ts
packages/void-server/src/utils/createJsonResponse.ts
packages/void-server/src/utils/createXmlResponse.ts
packages/void-server/src/utils/createZipFileResponse.ts
packages/void-server/src/utils/getBody.ts
packages/void-server/src/utils/getRequestData.ts
packages/void-server/src/utils/index.ts
pnpm-lock.yaml

This PR adds HTML and XML responses to the `@scalar/void-server`, they come up when you request an URL that ends with `.html` or `.xml` or send an `Accept: application/xml` or `Accept: text/html` header.

feat(void): XML and HTML response

---

README.md

Some links miss the md extension. 😳

docs: update links to point to Markdown files

---

.changeset/pretty-rats-melt.md
.changeset/wild-mangos-invent.md
packages/cli/package.json
packages/cli/src/commands/init/InitCommand.ts
packages/cli/src/commands/init/init.test.ts
pnpm-lock.yaml

The `scalar init` command generates a `scalar.config.json`.  This PR extends the `scalar init` command to add the required attributes `subdomain`, an empty `guides` array and adds a `--force` flag to overwrite existing configurations without further interaction.
It’s not perfect, but one step closer to connect the CLI to docs.scalar.com.

feat(cli): add more attributes to `scalar init`

---

packages/galaxy/tsconfig.json

When I run `pnpm lint` I get:
> ESLint was configured to run on `<tsconfigRootDir>/scripts/format.ts` 
> However, that TSConfig does not include this file.
This PR adds it to the `tsconfig.json`. :)

fix(galaxy): tsconfig does not include scripts

---

packages/api-reference/src/helpers/createEmptySpecification.ts
packages/api-reference/src/helpers/getHeadingsFromMarkdown.ts
packages/api-reference/src/helpers/getModels.ts
packages/api-reference/src/helpers/isValidUrl.ts
packages/api-reference/src/helpers/openClientFor.ts
packages/api-reference/src/hooks/useDeprecationWarnings.ts
packages/api-reference/src/hooks/useRefOnMount.ts
packages/api-reference/src/hooks/useSidebar.ts
packages/api-reference/src/stores/useHttpClientStore.ts

This PR adds some of the missing JSDoc comments for exported functions in `@scalar/api-reference`. 🌟

chore: add some missing JSDoc comments

---

.eslintrc.cjs
package.json
pnpm-lock.yaml

This PR adds an ESlint plugin to warn about out exported functions without JSDoc comments. The lint script isn’t executed in CI, eventually we should add it. But for now it’s enough to help us (or at least me) to add comments where they are missing.
Once we’re done with adding a comment for all existing functions, we can add it to CI or even error on missing  JSDoc comments or apply the rule to all functions … Step by step. :)

chore: warn about missing comments for exported functions

---

packages/client-app/src/views/Request/RequestSection/RequestAuth.vue

the modal cant close cause we dont check the schema before the type! this fixes that : )

fix: add null check for schema type on request

---

packages/client-app/src/views/Request/RequestSection/RequestParams.vue

we would often end up with no ability to add an item! now if theres an item we check to see if we can add an empty row on mount :)

fix: ensure trailing empty parameter item

---

packages/client-app/src/App.vue
packages/client-app/src/store/workspace.ts
packages/client-app/src/views/Request/RequestSection/RequestAuth.vue
packages/client-app/src/views/Request/components/OAuth2.vue
packages/client-app/src/views/Request/libs/oauth2.ts
packages/oas-utils/src/entities/workspace/security/security-schemes.ts

This PR adds the client credentials oauth 2 flow. 
Test data IS enabled so you can test both authorization code flow as well as client credentials (they use the same server method now) to make sure there's no regressions
sorry @cameronrohani I ended up doing some front end... I tried to resist. We can work out any conflicts

feat: client credentials flow

---

.changeset/lazy-pumpkins-chew.md
packages/client-app/src/components/AddressBar/AddressBar.vue

this pr sets resize to the address bar server dropdown in the client app to make it wider:
**current state**

fix(client app): address bar server dropdown

---

.changeset/khaki-brooms-exist.md
packages/galaxy/src/specifications/3.1.yaml

This PR adds <https://void.scalar.com> as an alternative server URL to our OpenAPI Example.
This URL just responds with the request data and is great to play around, could be a great addition to the OpenAPI example.

feat(galaxy): add void.scalar.com as an alternative server

---

.changeset/modern-frogs-reply.md
packages/components/src/components/ScalarButton/ScalarButton.vue

this pr updates the scalar button component in order to fix the loading state:
**before** (loading markup always shown)
**after**
(is chilling)
(is loading)

fix(components): scalar button loading state

---

packages/oas-utils/src/transforms/import-spec.ts

**Problem**
Currently, if a spec has no tags we fail
This happens because although tags arent required, we dont have a createTags helper with a default
**Solution**
With this PR it creates a temporary default tag

fix: handle no tags spec import

---

.changeset/loud-taxis-crash.md
.changeset/old-kangaroos-watch.md
.changeset/selfish-keys-tap.md
packages/api-client/src/types.ts
packages/api-reference/src/components/Content/BaseUrl/BaseUrl.vue
packages/api-reference/src/components/Content/BaseUrl/ServerVariables.vue
packages/components/src/components/ScalarListbox/ScalarListbox.vue

this pr fixes the server variables style in the api reference and add back enum select:
**before**

fix(api reference): server variables style

---

packages/client-app/src/views/Request/RequestSection/RequestAuth.vue

The quickest of fixes, was showing undefined when we wanted an empty string `''`

fix: auth selector

---

packages/api-client-modal/package.json
packages/api-client-modal/src/api-client-modal.ts
packages/api-reference/package.json
packages/api-reference/src/components/ApiClientModal.vue
packages/api-reference/src/components/Content/Operation/TestRequestButton.vue
packages/api-reference/src/components/api-client-bus.ts
packages/oas-utils/src/entities/workspace/security/security-schemes.ts
pnpm-lock.yaml

Currently `useAuthStore` and the `client-app` don't match 1:1 since `useAuthStore` can only support one of each type of auth. What we do here is set every type on the `client-app` as long as value does not already exist
I would hold off on this one and merge https://github.com/scalar/scalar/pull/2258 first, then I can add password to this one and were g2g

feat: pass auth into client modal

---

examples/proxy-server/main.go

Currently, when setting Axios to `withCredentials: true` the browser complains that credentials are not allowed (requires header `Access-Control-Allow-Credentials: true`), so I added this.
But then the browser complains `Access-Control-Allow-Origin` must not be `*`, so with this PR it’s set to the origin (if available).

fix(proxy): cross-origin credentials are not allowed

---

.changeset/lovely-monkeys-deny.md
packages/api-client/src/helpers/redirectToProxy.test.ts
packages/api-client/src/helpers/redirectToProxy.ts
packages/api-client/src/helpers/sendRequest.test.ts
packages/client-app/src/libs/sendRequest.ts
packages/oas-utils/src/helpers/fetchSpecFromUrl.ts

When sending multiple query parameters, only the first one is proxied to the target URL.
This is because we used `encodeURI` instead of `encodeURIComponent` in a few places.
```js
encodeURI('https://example.com/?color=red&size=large')
// 'https://example.com/?color=red&size=large'
encodeURIComponent('https://example.com/?color=red&size=large')
// 'https%3A%2F%2Fexample.com%2F%3Fcolor%3Dred%26size%3Dlarge'
```
We’re not encoding the URL (https://… is perfectly fine for an URL), but a parameter.
**❌ encodeURI**
https://proxy.scalar.com/?scalar_url=https://void.scalar.com?foo=bar&bar=foo
**✅ encodeURIComponent**
https://proxy.scalar.com/?scalar_url=https%3A%2F%2Fvoid.scalar.com%3Ffoo%3Dbar%26bar%3Dfoo%27

fix: URL is not encoded when sent to the proxy

---

.changeset/thick-rivers-punch.md
packages/client-app/src/components/AddressBar/AddressBarHistory.vue

this pr updates the request history item style and removes italic on pathname:
**before**
**after**

fix(client-app): address bar request history items

---

.changeset/pink-badgers-raise.md
examples/cdn-api-reference/package.json
examples/docusaurus/package.json
examples/fastify-api-reference/package.json
examples/nestjs-api-reference-express/package.json
examples/nestjs-api-reference-fastify/package.json
examples/nextjs-api-reference/package.json
examples/react/package.json
examples/ssg/package.json
examples/web/package.json
package.json
packages/api-client-proxy/package.json
packages/build-tooling/package.json
packages/cli/package.json
packages/components/package.json
packages/echo-server/package.json
packages/fastify-api-reference/package.json
packages/mock-server/package.json
packages/void-server/package.json
pnpm-lock.yaml

I was doing some filtering and I realized we could use some [inferred type predicates](https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#inferred-type-predicates) from typescript 5.5
before (5.4.3):
after (5.5.2):
Also do we need typescript in every package? Or is having it in the base package.json enough?

chore: upgrade typescript

---

packages/client-app/src/components/AddressBar/AddressBar.vue
packages/client-app/src/components/SideNav/SideNav.vue
packages/client-app/src/components/Sidebar/Sidebar.vue
packages/client-app/src/components/TopNav/TopNav.vue
packages/client-app/src/constants.ts
packages/client-app/src/views/Collection/Collection.vue
packages/client-app/src/views/Components/Schemas/Schemas.vue
packages/client-app/src/views/Cookies/Cookies.vue
packages/client-app/src/views/Environment/Environment.vue
packages/client-app/src/views/Request/Request.vue
packages/client-app/src/views/Servers/Servers.vue

While there is a valid case for an object which holds classes like that, we weren't using it. It was a glorified wrapper around `flex-1`

chore: remove random themeclasses object

---

packages/client-app/src/constants.ts

This warning is driving me nuts. 🤡 Let’s disable the sidebar entry for now.

chore(client-app): disable /git-sync route

---

.changeset/purple-lions-appear.md
packages/api-reference/src/features/BaseUrl/ServerUrlSelect.vue

We don’t need to have a dropdown for a single server. :)
**Before**
**After**

style: no dropdown for a single server

---

.changeset/chilly-meals-boil.md
.changeset/fluffy-dolls-juggle.md
packages/client-app/src/components/AddressBar/AddressBarServer.vue
packages/client-app/src/views/Request/Request.vue
packages/client-app/src/views/Servers/ServerForm.vue
packages/oas-utils/src/entities/workspace/server/server.ts

This PR adds support for server variables to `@scalar/client-app`:
```js
{
"info": {
"title": "Servers with Variables",
},
"servers": [
{
"url": "https://{username}.gigantic-server.com:{port}/{basePath}",
"description": "The production API server",
"variables": {
"username": {
"default": "demo",
"description": "this value is assigned by the service provider, in this example `gigantic-server.com`"
},
"port": {
"enum": [
"8443",
"443"
],
"default": "8443"
},
"basePath": {
"default": "v2"
}
}
}
],
"paths": {}
}
```

feat(client-app): server variables

---

.changeset/brown-onions-ring.md
packages/use-tooltip/package.json
packages/use-tooltip/src/useTooltip.ts
pnpm-lock.yaml

this pr is a revert proposal of the changes that occurs in #2194 to the `use-tooltip` package. since it hasn't been used in the client app as we added a ScalarTooltip component in the `@scalar/components` package, let's revert them since it causes breaking changes.

revert(use-tooltip): dependency update

---

package.json
packages/nuxt/package.json

This is really slowing down installs. Can just be run when working on nuxt

chore: Remove nuxt prepare from install script

---

.changeset/wet-paws-lie.md
packages/client-app/src/Modal/api-client-modal.ts
packages/client-app/src/components/ActionModal/ActionModal.vue
packages/client-app/src/views/Request/Request.vue
packages/client-app/src/views/Request/RequestSidebarItem.vue
packages/client-app/src/views/Request/ResponseSection/ResponseBody.vue
packages/client-app/src/views/Request/components/OAuthScopesInput.vue
packages/oas-utils/src/entities/workspace/workspace.ts
packages/themes/src/tailwind.ts

if no html was rendered the preview would always have a white background now we take the current theme background if there's no html within the preview
before:
after:
+ some app polish

fix: empty html response show theme background + color + app polish

---

.changeset/warm-lamps-wash.md
packages/api-reference/src/components/Content/Operation/CustomRequestExamples.vue
packages/api-reference/src/components/Content/Operation/ExampleRequest.vue
packages/api-reference/src/components/Content/Operation/OperationAccordion.vue
packages/api-reference/src/components/Content/Operation/TestRequestButton.vue
packages/api-reference/src/components/Content/Tag/Endpoints.vue
packages/api-reference/src/components/HttpMethod/HttpMethod.vue
packages/api-reference/src/components/HttpMethod/constants.ts
packages/api-reference/src/components/HttpMethod/index.ts
packages/api-reference/src/components/HttpMethod/utils/isRequestMethod.ts
packages/api-reference/src/components/Sidebar/SidebarHttpBadge.vue

As we’re about to say good bye to `@scalar/api-client` v1 it’s time to remove imports to it.
This PR moves the `<HttpMethod />`, which we use in a lot of places, to `@scalar/api-reference`.
⚠️ The `TestRequestButton` had a `HttpMethod` as a wrapper. I don't think we need this anymore, or do we have different colors for the button in other/older themes? @cameronrohani

refactor: move `<HttpMethod />` component to `@scalar/api-reference`

---

.changeset/tender-papayas-rule.md
packages/api-reference/src/index.ts

We probably had a reason at some point to expose the `useApiClientStore` from `@scalar/api-reference`, but that will break soon with the new API client. So let’s remove it already, with a proper changeset.

chore: do not expose `useApiClientStore` anymore

---

.changeset/dull-peaches-greet.md
packages/api-reference/src/components/Sidebar/SidebarHttpBadge.vue

this pr sets the right font weight for the method in the api reference sidebar (700 -> 600):

fix(api-reference): sidebar font weight

---

packages/api-client/src/store/workspace.ts

this pr sets back param example values, which displays the first occurence:

fix(api-client): set param example value

---

.changeset/brave-toes-relax.md
documentation/configuration.md
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/Content/Content.vue
packages/api-reference/src/features/BaseUrl/BaseUrl.vue
packages/api-reference/src/types.ts

We somehow didn’t pass the list of servers (anymore). This passes the servers list down to the `<BaseUrl />` component as documented. :)
Based on #2272.

fix(api-reference): servers are ignored

---

.github/workflows/ci.yml

With this PR we’re going to use Node 20 by default, and release PRs will also be tested in Node 18.
This should speed up CI for all PRs, but the release PR.

ci: use Node 18 only for release PRs

---

packages/api-client/src/views/Request/RequestSidebarItem.vue

this pr updates request sidebar icon accordingly to workspace read only state:
`isReadOnly`
`!isReadOnly`

fix(client-app):  request sidebar icon

---

.changeset/early-apricots-add.md
packages/build-tooling/src/workspace-reload.ts

Allows us to specify the workspace path to allow usage in scalar-org

feat: workspace watcher prop

---

.changeset/young-toes-sit.md
packages/components/src/components/ScalarModal/ScalarModal.vue

new api client top position on mobile is too low, this pr fixes that!
before:
after:

fix: api client top position mobile

---

.changeset/twelve-spiders-sparkle.md
packages/api-reference/src/components/Content/Content.vue

fix: server description padding

---

.changeset/violet-owls-wave.md
packages/api-client/src/libs/sendRequest.ts

**Problem**
Currently, we send query param values regardless of if a value is in there or not
This happens because we send it always
**Solution**
With this PR we only send it if theres a value

fix: only send query params with a value

---

.github/workflows/ci.yml
.github/workflows/publish-on-stackblitz.yml

With this PR our packages are published on Stackblitz for all release PRs. 
This is great, because we can test the published version without publishing to npm (and all our users).
The publishing takes ~4 minutes, so I made it a separate workflow which can run in parallel to the `ci.yml`.

ci: publish packages on Stackblitz

---

.changeset/happy-taxis-join.md
packages/oas-utils/src/transforms/import-spec.ts

**Problem**
Currently, we miss path level params on import
This happens because we dont check them only operation params
**Solution**
With this PR we check both :)

fix: ensure path and operation params are merged on import

---

.changeset/young-waves-glow.md
packages/api-client/src/components/AddressBar/AddressBar.vue
packages/api-client/src/components/AddressBar/AddressBarServer.vue
packages/api-client/src/views/Request/RequestSidebarItem.vue
packages/themes/src/reset.css

this pr adds tab index to sidebar child item in order to make them focusable + custom style focus visible:

feat(api-client): tab focus style

---

.changeset/rare-kangaroos-sit.md
examples/cdn-api-reference/src/public/play-button-local.html
packages/play-button/index.html
packages/play-button/src/index.ts
playwright/tests/jsdelivr.spec.ts
playwright/tests/local.spec.ts
playwright/tests/testApiReference.ts
playwright/tests/testPlayButton.ts

The `@scalar/play-button` doesn’t support YAML (as shown in the example in the README). This PR fixes it and some more issues:
* We’ve had a `await resp.json()` in there, so it wasn’t working with anything else than JSON. We’re now just passing whatever content we receive to the `parse` function.
* To open a specified operation, it just looked in the first tag (`parsedSpec.tags?.[0]?.operations?.find(…)`), so it didn’t work for operations in other tags.
* We were looking for the specified operation on load, not on click. This broke for URLs that first need to be fetched.
* The example mentioned operationIds from the petstore example, but used the `@scalar/galaxy` example.
* The package ignored `script` tag content, this PR adds support for it.
This PR also adds basic tests for the local …

fix(play-button): does not work with yaml

---

.changeset/clean-llamas-appear.md
packages/api-client/src/App.vue

this pr adds scalar classes to headless ui root within api client package to maintain style within the workspace usage:

fix(api-client): add scalar classes to headless ui root

---

.changeset/cool-worms-lie.md
packages/void-server/src/createVoidServer.test.ts
packages/void-server/src/utils/getBody.ts

I’ve missed that feature: This PR adds support for (multipart) form data to `@scalar/void-server`, including support for for fields containing a single or multiple fields and blob requests (just a blob, nothing else).
Great help to debug the file upload.

feat(void-server): (multipart) form data

---

.changeset/mean-falcons-thank.md
packages/api-client/src/views/Cookies/Cookies.vue
packages/oas-utils/src/entities/workspace/cookie/cookie.ts

this pr fixes the zod error when adding a cookie by adding missing uid + default value to cookie schema. another take could be to use `cookieSchema.parse(deepMerge({}, payload))` vs `deepMerge(cookieSchema.parse({}), payload)` to only validate merged result and allow empty object, but i favored here adding default value to maintain code consistency.

fix(api client): add cookies

---

.changeset/dirty-parrots-sin.md
.changeset/serious-clouds-pretend.md
packages/api-client/src/components/DataTable/DataTableInput.vue
packages/api-client/src/components/DataTable/DataTableInputEnumSelect.vue
packages/api-client/src/store/workspace.ts
packages/api-client/src/views/Request/RequestSection/RequestTable.vue
packages/oas-utils/src/entities/workspace/spec/request-examples.ts

this pr adds an input enum select component to the api client package, in order to be able to select an enum value when available, along maintaining the capacity of adding our own value:

feat(api-client): data table input enum select

---

.changeset/tender-snakes-chew.md
packages/api-reference/src/components/ApiReferenceLayout.vue

This should fix #2352. Due to our new build system we must move our css imports into the `style` tags

fix: move css to style tag

---

.github/workflows/ci.yml

Something very unfortunate: I’ve recently added a new job to define the Node version matrix in #2309, but that had a bug.
The build, format:check, types:check, test:ci scripts all require the `define-matrix` job to have a correct Node version matrix output though.
In other words: Those weren‘t executed a single time since I added the `define-matrix` job 5 days ago! I don’t know how I was able to not see this, but here we are.
https://github.com/scalar/scalar/actions/runs/9713252509/job/26809641617
It shows a green checkmark in the overview, because `define-matrix` is green, but it’s actually red - which isn’t visible inside the PR. Super misleading!
This PR adds a check to make sure the node version matrix is [18, 20] or [20] and nothing else.
I consider this urgent and will skip the …

fix: build, test, format:check, types:check isn’t executed in CI

---

.changeset/thirty-donkeys-retire.md
.changeset/unlucky-islands-stare.md
packages/void-server/src/createVoidServer.test.ts
packages/void-server/src/createVoidServer.ts

I just wanted to force a JSON response, so I’ve added more file extensions to force a specific content type and refactored the routes to just use one single route for `.json`, `.html`, `.xml` and `.zip`.

feat(void-server): force JSON responses

---

.changeset/early-phones-invite.md
packages/void-server/package.json
packages/void-server/src/utils/getBody.ts
pnpm-lock.yaml

We didn’t run the tests in CI (read more in #2367), but now we do. Turns out `createVoidServer` uses `File` in Node, which isn’t available in Node 18.
This PR adds File from the `undici` package (which is what the recent Node versions use under the hood). This should make CI pass for Node 18 again, at least it does locally.

fix(void-server): Node 18 does not have File

---

.changeset/calm-suits-remain.md
packages/api-client/src/components/AddressBar/AddressBarHistory.vue

this pr adds response duration infos to the history items + a different ordering proposal as seen below:
**before**
**after**

feat(api-client): address bar history infos

---

.changeset/dirty-pumpkins-hammer.md
packages/api-client/src/components/AddressBar/AddressBarHistory.vue

this pr fixes the address bar history item informations being changed when navigating within items in the api client package, by removing the activeRequest response value being stored on click.
to date when navigating within the history, selecting an item is updating the activeRequest value and hence setting the infos towards all the items as below:
https://github.com/scalar/scalar/assets/14966155/b0344bf3-a12e-4582-9364-f698af83cc56

fix(api-client): address bar history infos

---

.changeset/clean-birds-hang.md
.changeset/kind-masks-laugh.md
.changeset/warm-pugs-mate.md
packages/api-client/src/components/TopNav/TopNavItem.vue
packages/api-client/src/store/workspace.ts
packages/api-client/src/views/Request/RequestSection/RequestTable.vue
packages/api-client/src/views/Request/RequestSection/RequestTableTooltip.vue
packages/components/src/components/ScalarTooltip/ScalarTooltip.vue
packages/oas-utils/src/entities/workspace/spec/request-examples.ts

this pr introduces type, format, and default properties for query params within a new request table tooltip component as seen below:
**before**
**after**

feat(api-client): request query params tooltip

---

.changeset/giant-suits-stare.md
.changeset/young-days-jump.md
packages/api-client/src/components/DataTable/DataTableInput.vue
packages/api-client/src/store/workspace.ts
packages/api-client/src/views/Request/RequestSection/RequestTable.vue
packages/api-client/src/views/Request/RequestSection/RequestTableTooltip.vue
packages/oas-utils/src/entities/workspace/spec/request-examples.ts

this pr adds min and max to request param items, along setting the input type as number according to item type + displaying warning for out of range value accordingly:
**tooltip**
**warning**

feat(api-client): min max request params

---

packages/scalar.aspnetcore/Scalar.AspNetCore.cs

This PR removes the additional brackets from the configuration output, which otherwise break the configuration.
See #2368
How do we test this integration? @marclave

fix(scalar.aspnetcore): additional brackets break the configuration, fix #2368

---

.github/workflows/ci.yml
.github/workflows/deploy-examples.yml
.github/workflows/deploy-preview-examples.yml
.github/workflows/publish-on-stackblitz.yml
.github/workflows/release.yml
.github/workflows/test-cdn-jsdelivr.yml
.github/workflows/test-cdn-local.yml
.github/workflows/test-nuxt-integration.yml
.github/workflows/validate-openapi-file.yml
package.json

With this PR the one job in our main GitHub Action workflow is split up into multiple jobs that all wait for a single build. That way, jobs can be run in parallel and speed up CI.
Note: This makes the ci.yml way longer (+94 LOC) and one could argue also harder to understand, but personally, I think it’s worth it. [Reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow) could help here. I’ll look into that soon.
**Additional changes**
* Every PR starts from a global Turborepo cache, but keeps its own separate cache for every PR. This should decrease the cache miss rate.
The build cache never really worked for all packages, the cache miss rate was pretty high, so this was the fastest possible run before: …

ci: cache build, run jobs in parallel ⚡

---

.changeset/polite-windows-do.md
packages/api-client/src/App.vue
packages/api-client/src/assets/tailwind.css
packages/api-client/tailwind.config.ts
packages/components/tailwind.config.ts
packages/themes/src/reset.css

This should fix the leaky reset styles that were coming out of `@scalar/api-client`. It's worth doing some testing to make sure removing the Tailwind preflight didn't break anything.

fix: remove tailwind preflight from api client app

---

.changeset/neat-plants-explode.md
packages/api-client/src/components/Search/SearchModal.vue
packages/api-client/src/views/Request/Request.vue
packages/api-reference/src/components/SearchModal.vue
packages/components/src/components/ScalarSearchResults/ScalarSearchResultItem.vue

Looks like the search modal on the client was missing a couple things. Also added a fail safe (watch) to avoid the current race condition on getting requests.
Before:
After:

fix: client search missing a few things!

---

.changeset/thick-drinks-cross.md
packages/api-client/src/views/Request/RequestSidebarItem.vue

fix: indent request sidebar highlight properly in readonly mode

---

documentation/fastify.md

**Problem**
Currently, in the Fastify documentation, the response schema for the `example-route` is defined with a status of 201. However, that route returns a status of 200. This discrepancy causes tests for that route to receive an empty object instead of the correct response.
**Solution**
With this PR, I aim to add `reply.code(201)` before sending the response object.

docs: Add reply.code in fastify example-route

---

.changeset/gold-horses-travel.md
packages/build-tooling/src/rollup-options.ts
packages/build-tooling/src/rollup-plugins/emptyOutDir.ts

With this PR our Rollup script removes the `dist/` folder by default.
Keeping the `dist/` folder can be confusing, or make you think the build works, but it maybe just kept the files from before your changes.
If - for some reason - that’s not the expected behaviour, you can disable the plugin like this:
```ts
createRollupConfig({
emptyOutDir: false,
})
```
The Rollup plugin is taken from the official Rollup repository.

chore(build-tooling): remove `dist/` folder by default

---

packages/api-client/src/libs/sendRequest.test.ts

For some reason this test is failing in Node 18 (but not Node 20). Whatever, let’s just use 127.0.0.1 instead of localhost, like we do in the other tests.

fix: can’t reach localhost

---

.changeset/loud-ties-accept.md
packages/api-client/src/views/Request/Request.vue

this pr displays request sidebar by default in workspace, while keeping it hidden in reference.

feat(api-client): show sidebar by default in workspace

---

packages/themes/src/reset.css

Turns out there was a little bit more resetting to do for the client app.
The reset on `<body>` is in a layer so it should be easy to override.

fix(themes): reset list styles and body margin

---

.changeset/plenty-plums-refuse.md
packages/api-client/src/Modal/ApiClientModal.vue

this pr adds capability to close the api client modal when pressing `esc`.

feat(api-client): modal esc

---

.changeset/brave-eels-obey.md
packages/api-client/src/views/Request/RequestSection/RequestTableTooltip.vue

this pr sets nowrap for request table tooltip component value over pre to better handle potential unsupported usage:
**before**
**after**

fix(api-client): request table tooltip value

---

.changeset/purple-cows-sniff.md
packages/api-client/src/views/Request/RequestSection/RequestTable.vue
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue

this pr normalizes the value displayed in reference / client in case we receive an array value as default, [as brought up in x](https://x.com/seancassiere/status/1809011620141748607/photo/1) and as seen below:
**before**
**after**

fix: default array value

---

.github/workflows/ci.yml
.github/workflows/deploy-examples.yml
.github/workflows/deploy-preview-examples.yml
.github/workflows/publish-on-stackblitz.yml
.github/workflows/release.yml
.github/workflows/test-cdn-jsdelivr.yml
.github/workflows/test-cdn-local.yml
.github/workflows/test-nuxt-integration.yml
.github/workflows/validate-openapi-file.yml

> Note: I tried to make small PRs, but we will only see the benefits once #2399, #2400 and #2401 are all merged.
I’ve seen the type:check job often doesn’t have cache for all the examples. My theory is that the workflows that only do `build:packages` overwrite the cache with just the packages and then jobs that start later only have that cache.
But the GitHub Action has a great feature, where you can only restore the cache, but not write to it. So this PR just restores the cache in all cases, and writes to it only in the ci.yml workflow and only in the build job.
Let’s see if we can increase the cache hit rate that way. :)

ci: only write to the turborepo cache once

---

.changeset/weak-kings-teach.md
packages/api-client/src/App.vue
packages/api-client/src/Modal/api-client-modal.ts
packages/api-client/src/components/ActionModal/ActionModalFolder.vue
packages/api-client/src/components/AddressBar/AddressBar.vue
packages/api-client/src/components/AddressBar/AddressBarServer.vue
packages/api-client/src/components/Sidebar/Sidebar.vue
packages/api-client/src/index.ts
packages/api-client/src/libs/index.ts
packages/api-client/src/libs/local-storage.ts
packages/api-client/src/router.ts
packages/api-client/src/store/workspace.ts
packages/api-client/src/views/Request/Request.vue
packages/api-client/src/views/Request/RequestSidebarItem.vue
packages/api-client/src/views/Request/ResponseSection/ResponseBody.vue
packages/api-client/src/views/Request/ResponseSection/ResponseEmpty.vue
packages/api-client/vite.config.ts
packages/api-reference/vite.config.ts
packages/oas-utils/package.json
packages/oas-utils/src/entities/workspace/workspace.ts
packages/object-utils/package.json
packages/object-utils/src/mutator-record/handlers.ts
packages/object-utils/src/mutator-record/index.ts
packages/object-utils/src/mutator-record/local-storage.ts
packages/themes/src/index.ts
pnpm-lock.yaml

Saves and loads data from localStorage. It persists now! Requires heavy testing before launch but looks ok
I ended up removing the workspace/routing from this PR, it can be added later. For now it just takes the first workspace but it will support multiple workspaces

feat(doc-1882): save client data to localStorage

---

.changeset/sharp-jeans-prove.md
packages/api-reference/src/components/Content/Introduction/Description.vue
packages/code-highlight/src/css/markdown.css
packages/docusaurus/src/theme.css

Chatted with @cameronrohani and it sounds like we want to constrain markdown images by width not height 👍

fix(api-reference): don't constrain markdown image height

---

.changeset/metal-mirrors-tickle.md
packages/api-client/src/App.vue
packages/api-client/src/components/AddressBar/AddressBarServer.vue
packages/api-client/src/views/Request/Request.vue
packages/oas-utils/src/entities/workspace/spec/requests.ts

Currently we always load the galaxy client, but now we have a ✨ drafts ✨ collection which wont be saved to the cloud, and when you initially go to the app it will have the My First Request as the default
Handled scenarios with:
- no servers 
- keep drafts collection at the bottom
some things to improve:
- make drafts have its own icon
- ensure we dont have > 1 example for each draft request since its not an openapi compliant request
- ensure Auth shows up always

feat: add empty state + drafts collection

---

.changeset/purple-poems-live.md
.changeset/seven-fireants-move.md
packages/api-client/src/components/Sidebar/Actions/SidebarListElementForm.vue
packages/components/src/components/ScalarModal/ScalarModal.vue

this pr fixes scalar modal style issues as seen below:
**before**
**after**

fix(components): scalar modal

---

.changeset/cuddly-seas-fail.md
packages/api-client/src/components/AddressBar/AddressBar.vue
packages/api-client/src/components/Sidebar/SidebarListElementActions.vue
packages/api-client/src/components/TopNav/TopNavItem.vue
packages/api-client/src/views/Request/Request.vue
packages/api-reference/src/components/Card/CardHeader.vue
packages/api-reference/src/components/Content/Operation/PathResponses/PathResponses.vue
packages/api-reference/src/components/Content/Operation/TestRequestButton.vue
packages/api-reference/src/features/ExampleRequest/ExampleRequest.vue
packages/components/package.json
packages/components/src/components/ScalarCodeBlock/ScalarCodeBlock.spec.ts
packages/components/src/components/ScalarCodeBlock/ScalarCodeBlock.vue
packages/components/src/components/ScalarCodeBlock/useClipboard.ts
packages/components/src/components/ScalarIcon/icons/Clipboard.svg
packages/components/src/components/ScalarIcon/icons/Close.svg
packages/components/src/components/ScalarIcon/icons/Play.svg
packages/components/src/components/ScalarSearchInput/ScalarSearchInput.vue
pnpm-lock.yaml

this pr is a proposal to update some icons + moves the copy action capability to the scalar codeblock component in order to make it available in both request / response examples:
nb. it does not display copy action when response value is `null`
**before**
**after**
[Uploading scalar-copy.mp4…](https://github.com/scalar/scalar/assets/14966155/d031f9f0-4915-49c3-9021-229297a478f5)

feat(api-reference): scalar icons

---

.changeset/curly-crabs-battle.md
.changeset/fresh-seals-trade.md
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/views/Request/RequestSection/RequestBody.vue
packages/use-codemirror/package.json
packages/use-codemirror/src/hooks/useCodeMirror.ts
pnpm-lock.yaml

this pr adds the lint option in use-codemirror package and enable json linter in api client request body (unstyled):

feat(use-codemirror): add json linter

---

.github/workflows/test-cdn-jsdelivr.yml
.github/workflows/test-cdn-local.yml
.github/workflows/test-nuxt-integration.yml

> Note: I tried to make small PRs, but we will only see the benefits once #2399, #2400 and #2401 are all merged.
The Cache action has a great feature: It can restore the cache for other keys, in our cases from other Playwright binaries. But that’s not really what we want, because the dependencies are incompatible then. :(
Let’s only restore the cache for the exact same Playwright version.
Oh, and getting the Playwright version didn’t work at all. This PR fixes that, too.
Extracted from #2354.

ci: do not restore cache for other playwright versions

---

.github/workflows/ci.yml
.github/workflows/deploy-examples.yml
.github/workflows/deploy-preview-examples.yml
.github/workflows/publish-on-stackblitz.yml
.github/workflows/release.yml
.github/workflows/test-cdn-jsdelivr.yml
.github/workflows/test-cdn-local.yml
.github/workflows/test-nuxt-integration.yml
.github/workflows/validate-openapi-file.yml

> Note: I tried to make small PRs, but we will only see the benefits once #2399, #2400 and #2401 are all merged.
I’ve reread the documentation on the cache action and it says:
> The cache is scoped to the key, [version](https://github.com/actions/cache?tab=readme-ov-file#cache-version), and branch. The default branch cache is available to other branches.
Soo … there’s no need to add the branch to the cache key. And we want a fresh build for different Node versions anyway, so we can remove this restore key, too.
With this PR the Turborepo cache has access to the cache of the main branch for the first run of a PR, but only to the same Node version and the same branch for the next runs.

ci: don’t scope turborepo cache to the branch

---

.changeset/famous-ducks-repair.md
.changeset/green-mirrors-roll.md
packages/api-client/src/components/DataTable/DataTableInput.vue
packages/api-client/src/components/DataTable/DataTableInputEnumSelect.vue
packages/components/src/components/ScalarDropdown/ScalarDropdownItem.vue

this pr fixes dropdown button component style issue and adds enhancements, in order to hide the `Required` hint only when the peer input is focus vs previously where both input focus (key/value) were hiding it.

fix(api-client): param components style

---

.changeset/config.json
.prettierignore

This PR adds two of our deprecated packages to the changeset ignore list. We shouldn’t bother with changesets for packages we don't release anyway.

chore: ignore changesets for deprecated packages

---

.changeset/polite-buttons-work.md
packages/api-reference/src/features/BaseUrl/ServerUrl.vue
packages/api-reference/src/features/BaseUrl/ServerUrlSelect.vue

this pr fixes long base url and make it scrollable as seen below:
**before**
**after**

fix(api-reference): long base url

---

.changeset/two-cougars-draw.md
packages/api-client-react/src/ApiClientReact.tsx
packages/api-client/README.md
packages/api-client/package.json
packages/api-client/playground/main.ts
packages/api-client/src/Modal/api-client-modal.ts
packages/api-reference/src/components/ApiClientModal.vue
packages/play-button/src/index.ts

This PR renames `createScalarApiClient` to `createApiClientModal`, and this is why:
* The method mounts a modal, which needs to be opened to be visible.
* It’s living in `packages/api-client/src/Modal/api-client-modal.ts`
* The comment says: `/** Initialize Scalar API Client Modal */`
I’d also like to propose to drop the `Scalar` in the function name, for the following reasons:
* It’s consistent with what we have already: https://gist.github.com/hanspagel/a696fa7371263dedf9f3d11f2122807c
* It’s very unlikely we run into any conflicts with `createApiClientModal`
* `createScalarApiClientModal` becomes so long, I don’t like to read it anymore
Looking for feedback!
If we’d keep the `Scalar` in the method name, I’d rename the others as following:
* `createScalarApiClientModal`
* …

chore: rename `createScalarApiClient` to `createApiClientModal` (RFC)

---

.changeset/yellow-donkeys-do.md
packages/api-reference/src/components/Content/Operation/OperationAccordion.vue

fix: update section accordian icons + stroke widths

---

.changeset/angry-kiwis-report.md
packages/api-client/src/components/AddressBar/AddressBar.vue

fixes scrollbar shown offset
before:
after:

fix(api-client): remove timeline scrollbar offset

---

.changeset/lovely-garlics-buy.md
.changeset/wild-lies-cover.md
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/components/DataTable/DataTableInput.vue
packages/api-client/src/components/DataTable/DataTableInputSelect.vue
packages/api-client/src/store/workspace.ts
packages/api-client/src/views/Request/RequestSection/RequestTable.vue
packages/oas-utils/src/entities/workspace/spec/request-examples.ts

this pr makes the previous data table input enum select more generic, add it to the code input component to bring back the enum support while bringing it to boolean type in the meantime:

feat(api-client): input select for enum and boolean
