.changeset/late-buckets-lay.md
README.md
packages/api-reference/src/standalone.ts
packages/fastify-api-reference/src/templates/render.ts

This PR adds `data-proxy-url` to the HTML API. 😎

feat: add proxy url to html api

---

packages/swagger-parser/src/helpers/parseSwaggerFile.ts

before we appended to the tags list, but we should be finding the default tag then adding to it.
There might be a more elegant way to do this so im happy to have feedback

fix: ensure default tag index is used before adding to tags

---

packages/api-reference/src/components/ApiReference.vue
packages/api-reference/src/components/Content/Content.vue
packages/api-reference/src/components/Content/EndpointsOverview.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/Copy.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/ReferenceEndpoint.vue
packages/api-reference/src/components/SearchModal.vue
packages/api-reference/src/components/Sidebar.vue

before:
after:
https://github.com/scalar/scalar/assets/6176314/641883c9-a80b-42a2-b44f-9acc62dd57b7

fix: active state in sidebar with prefix of httpVerb for all ids

---

.changeset/orange-masks-jam.md
packages/api-reference/src/components/ApiReference.vue

I _think_ all these should be updated

Rename old default variables

---

.changeset/silent-jeans-rule.md
packages/api-reference/src/components/ApiReference.vue
packages/api-reference/src/components/MobileHeader.vue
packages/api-reference/src/stores/template.ts
packages/themes/src/base.css

https://github.com/scalar/scalar/assets/6374090/171f58d7-2db1-4209-83b7-73e62cad25e8

Add mobile menu and breadcrumbs

---

.changeset/five-spiders-drum.md
packages/api-reference/src/components/SearchModal.vue
packages/swagger-editor/src/components/SwaggerEditor/GettingStarted.vue

search modal redesign + sneaky producthunt message

---

README.md

fix: add swagger editor demo to the readme

---

.changeset/soft-snakes-breathe.md
packages/api-reference/src/components/Content/MarkdownRenderer.vue

style: improve code blocks

---

.changeset/soft-lamps-agree.md
packages/api-client/src/components/ApiClient/ApiClient.vue
packages/api-client/src/components/ApiClient/Request/Request.vue
packages/api-client/src/components/ApiClient/Request/RequestHeaders.vue
packages/api-client/src/components/ApiClient/Request/RequestQuery.vue
packages/api-client/src/components/ApiClient/Request/RequestVariables.vue
packages/api-client/src/components/Grid/Grid.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/ExampleResponses/ExampleResponses.vue

we now have interactive parameters, variables and headers! Feels more like a rest api client every day now ✨

feat: add interactive params, headers and variables

---

packages/api-client/src/components/ApiClient/AddressBar.vue
packages/api-client/src/components/ApiClient/Request/Request.vue
packages/api-client/src/components/ApiClient/Request/RequestHeaders.vue
packages/api-client/src/components/ApiClient/Request/RequestQuery.vue
packages/api-client/src/components/ApiClient/Request/RequestVariables.vue
packages/api-client/src/components/CollapsibleSection/CollapsibleSection.vue
packages/api-client/src/components/Grid/Grid.vue

before:
after:
before:
after:
+ some other misc active / focus

misc client style clean ups

---

.changeset/large-turtles-worry.md
packages/api-client/src/components/ApiClient/ApiClient.vue
packages/api-reference/src/components/ApiClientModal.vue

Classic Safari 100vh bug
Fixed:

Fix scrolling for mobile API client

---

.changeset/plenty-rats-thank.md
README.md
packages/api-reference/README.md

This PR
* adds a link to the demo to the root README image.
* adds the same image to the @scalar/api-reference package README.

chore: add image to api reference package readme

---

.github/ISSUE_TEMPLATE/BUG-REPORT.yml
.github/ISSUE_TEMPLATE/config.yml

This pull request encompasses issue templates for various purposes, including `bug report`, `feature requests`, and `get help` for this repository.
closes: #18

added issue templates

---

.github/workflows/ci.yml

This PR combines all turbo tasks to a single command, which allows turborepo to further improve the performance.

chore: make CI even faster

---

.changeset/four-rice-roll.md
packages/api-client/src/components/ApiClient/ApiClient.vue
packages/use-codemirror/src/components/CodeMirror/CodeMirror.vue

This PR fixes a few minor CSS issues with the standalone API client.
* Proper box-sizing for the API Client
* Vertically center url

fix: API Client styles

---

.github/workflows/release.yml

Let’s add turborepo to the release workflow, too. ⚡

chore: make release workflow faster

---

packages/api-reference/src/components/Content/SchemaProperty.vue

[vite:css] end value has mixed support, consider using flex-end instead

chore: use flex-end instead of end

---

.changeset/fair-wombats-kiss.md
packages/api-reference/src/components/Sidebar.vue
packages/api-reference/src/components/SidebarElement.vue

Added scrolling of the sidebar stripe style
https://stripe.com/docs/api
Also feel free to remove/keep the smooth scroll over the jumpy one stripe has

feat: added sidebar scrolling

---

.changeset/odd-items-sell.md
packages/api-client/src/components/ApiClient/Response/Response.vue
packages/api-client/src/helpers/sendRequest.test.ts
packages/api-client/src/helpers/sendRequest.ts
packages/api-client/src/types.ts

This PR:
* fixes the tests
* makes sure only objects printed as JSON

fix: direct responses

---

.changeset/young-kids-battle.md
packages/api-reference/package.json
packages/api-reference/src/components/Content/MarkdownRenderer.vue
pnpm-lock.yaml

now markdown links open in new tabs ✨

fix: add target blank to markdown links

---

packages/api-reference/src/components/Section/SectionHeader.vue

This pull request adds an optional "level" prop to the section component.
closes: #310

added optional level prop to section component

---

.changeset/hot-hairs-return.md
packages/api-client/src/stores/apiClientRequestStore.ts

the browser no longer freezes when changing request history! 🥶 
https://github.com/scalar/scalar/assets/6176314/98472fd1-7843-4405-9b8e-96fbf97d44b7

fix: issue where browser froze with JSON being passed into codemirror body

---

.changeset/healthy-students-doubt.md
packages/api-client/src/components/ApiClient/Request/Request.vue
packages/api-client/src/components/ApiClient/Request/RequestAuth.vue
packages/api-client/src/components/ApiClient/Request/RequestHeaders.vue
packages/api-client/src/components/Grid/Grid.vue
packages/api-client/src/components/SimpleTable/SimpleRow.vue
packages/api-client/src/components/SimpleTable/SimpleTable.vue
packages/use-codemirror/src/components/CodeMirror/CodeMirror.vue

In preparation for auth branch... We have 3 different types of inputs across our app... Now we only have 2.5!
Before:
After:

fix: make inputs more consistent

---

packages/api-client/src/stores/apiClientStore.ts
packages/api-reference/src/components/ApiReference.vue
packages/api-reference/src/components/Content/EndpointsOverview.vue
packages/api-reference/src/components/Content/Models.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/ReferenceEndpoint.vue
packages/api-reference/src/components/IntersectionObserver.vue
packages/api-reference/src/components/Section/Section.vue

So I don't know if this is the best solution, it does add breadcrumbs though 🤷‍♀️ 
@hanspagel I'm not sure if you had a plan for this or not
https://github.com/scalar/scalar/assets/6374090/7f39ece1-9c57-493a-a72d-d45cfc6d8456

Add breadcrumbs back

---

.changeset/gold-ways-eat.md
packages/api-reference/src/components/Content/EndpointsOverview.vue
packages/api-reference/src/components/Content/Introduction/Introduction.vue
packages/api-reference/src/components/Content/Models.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/ReferenceEndpoint.vue

With this PR different heading levels are used:
- h1 title
- h2 tag
- h3 operation
- h2 model

chore: use different heading levels, fix #310

---

packages/api-reference/src/components/Content/Authentication/Authentication.vue

This PR fixes the Authentication `showSecurityScheme` check. Adds an optional chain.

fix: the showSecurityScheme authentication check

---

packages/api-client/src/components/ApiClient/Request/Request.vue
packages/api-reference/src/components/Content/Authentication/SecurityScheme.vue
packages/api-reference/src/components/Content/Authentication/SecuritySchemeSelector.vue

style auth to match auth within client

---

packages/api-reference/src/components/Sidebar.vue
packages/api-reference/src/components/SidebarElement.vue

show request type in reference sidebar

---

packages/api-reference/src/components/Content/Introduction/Introduction.vue
packages/swagger-editor/src/components/SwaggerEditor/GettingStarted.vue
packages/swagger-editor/src/components/SwaggerEditor/SwaggerEditorHeader.vue
packages/swagger-editor/src/components/SwaggerEditor/SwaggerEditorNotification.vue

clean up getting started page & move auth card down

---

README.md
packages/api-reference/README.md

Clean copy of #364 by @FotieMConstant 🙌

chore: fixed a couple typos

---

packages/api-client/src/helpers/sendRequest.test.ts
packages/api-client/src/helpers/sendRequest.ts

With this PR query strings in the URL and given query strings are merged. 💅

fix: merge query strings from URL with given query strings

---

packages/api-reference/src/components/Sidebar.vue
packages/swagger-editor/src/components/SwaggerEditor/SwaggerEditorAIWriter.vue
packages/use-codemirror/src/hooks/useCodeMirror.ts

This PR fixes a few tiny linter warnings.

chore: fix some linter warnings

---

packages/api-reference/src/components/Content/Introduction/ServerList.vue

fix active states and spacing of server list inputs

---

.changeset/bright-mangos-smile.md
packages/api-reference/src/components/Content/Introduction/ServerList.vue

remove extra borders + fix spacing when only 1 server child

---

projects/web/src/pages/ApiReferencePage.vue

😅 removing the hotkey from the demo page.

fx: remove setting search hotkey in demo page

---

packages/swagger-editor/src/components/SwaggerEditor/SwaggerEditorAIWriter.vue
packages/swagger-editor/src/components/SwaggerEditor/SwaggerEditorGettingStarted.vue
packages/swagger-editor/src/components/SwaggerEditor/SwaggerEditorHeader.vue

Move 'swagger editor' tab to be first tab + some minor improvements

spruce up getting started page

---

.changeset/forty-eels-jog.md
packages/api-client/src/components/ApiClient/RequestHistory.vue
packages/api-reference/src/components/Content/Schema.vue
packages/api-reference/src/components/SearchModal.vue

Found some misc places where --default theme was overwriting --theme, this should fix that

Make theme priority instead of default theme

---

packages/api-reference/src/helpers/deepMerge.test.ts
packages/api-reference/src/helpers/getHeadingId.test.ts
packages/api-reference/src/helpers/prettyPrintJson.test.ts
packages/api-reference/src/helpers/transformToJson.test.ts

This PR just adds a few basic tests to helpers that didn’t had any. ✅

chore: add more tests

---

.changeset/blue-lobsters-appear.md
packages/api-reference/src/components/Content/Authentication/SecuritySchemeSelector.vue
packages/api-reference/src/components/Content/Introduction/ServerList.vue

fix: don’t show a select for a single auth method

---

.changeset/red-ants-camp.md
packages/api-reference/src/components/Content/Introduction/Introduction.vue
packages/api-reference/src/types.ts

Marc cam/add oas version spec version to title

---

.changeset/tough-coats-wonder.md
packages/api-reference/src/components/ApiReferenceLayout.vue

https://github.com/scalar/scalar/assets/6374090/fb796b69-fe0a-4f1b-b8d5-ecc897bd1d7f

fix: footer behind sidebar in footer below sidebar mode

---

.prettierignore
pnpm-lock.yaml
projects/ssg/.gitignore
projects/ssg/index.html
projects/ssg/package.json
projects/ssg/src/App.vue
projects/ssg/src/main.ts
projects/ssg/src/style.css
projects/ssg/src/vite-env.d.ts
projects/ssg/tsconfig.json
projects/ssg/tsconfig.node.json
projects/ssg/vite.config.ts

We break SSG envs too often. This PR adds a SSG demo which is built in CI and should actually fail in this PR so we can test the SSG build here.
I’ll create a separate PR with the fix.
EDIT: Rebased and CI is green, awesome. ✅

chore: add SSG example

---

.changeset/young-flowers-love.md
packages/api-client-proxy/package.json
packages/api-client/package.json
packages/api-reference/package.json
packages/api-reference/src/hooks/useParser.test.ts
packages/fastify-api-reference/package.json
packages/swagger-editor/package.json
packages/swagger-parser/package.json
packages/swagger-parser/src/helpers/analyze.test.ts
packages/use-modal/src/hooks/useModal.test.ts
pnpm-lock.yaml

This PR removes unused dependencies that were found by https://www.npmjs.com/package/depcheck. 🌟

chore: remove unused packages

---

packages/hono-api-reference/README.md

This PR adds a screenshot to the Hono middleware README.

chore: add screenshot to the Hono middleware README.md

---

.changeset/fluffy-coins-fly.md
packages/api-reference/src/components/Content/ReferenceEndpoint/RequestBody.vue
packages/api-reference/src/helpers/getRequestFromOperation.ts

fix: optional chain for request bodies

---

packages/api-client-proxy/README.md
packages/api-client/README.md
packages/api-reference/README.md
packages/echo-server/README.md
packages/fastify-api-reference/README.md
packages/hono-api-reference/README.md
packages/swagger-editor/README.md
packages/swagger-parser/README.md
packages/themes/README.md
packages/use-clipboard/README.md
packages/use-codemirror/README.md
packages/use-keyboard-event/README.md
packages/use-toasts/README.md
packages/use-tooltip/README.md

The badges in all READMEs linked to … just the image URLs. This PR adds a link to npm to all badges.

chore: add link to NPM to badges

---

.changeset/chatty-beds-end.md
.changeset/pretty-dolls-scream.md
.changeset/soft-bats-drum.md
packages/api-client/src/helpers/findVariables.test.ts
packages/api-client/src/helpers/findVariables.ts
packages/api-client/src/helpers/index.ts
packages/api-reference/src/components/Content/Introduction/ServerList.vue
packages/api-reference/src/components/Content/Introduction/ServerVariables.vue
packages/api-reference/src/types.ts

With this PR variables used in server URLs are detected and inputs are rendered for them, even if they are not properly configured in the spec.
This PR also fixes a bug where single URLs didn’t had the variables inputs.

feat: detect variables in urls

---

.changeset/sour-bears-smile.md
packages/hono-api-reference/README.md

chore: update hono api reference readme image

---

.changeset/small-wolves-play.md
packages/api-client/package.json
packages/api-reference/package.json
pnpm-lock.yaml

> An issue discovered in Axios 0.8.1 through 1.5.1 inadvertently reveals the confidential XSRF-TOKEN stored in cookies by including it in the HTTP header X-XSRF-TOKEN for every request made to any host allowing attackers to view sensitive information.
Read more: https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
Fixed in 1.6.0 and above: https://github.com/axios/axios/releases/tag/v1.6.0

security: update axios froom 1.5.0 to 1.6.0

---

.changeset/perfect-suns-shop.md
packages/swagger-editor/src/components/SwaggerEditor/SwaggerEditorAIWriter.vue
packages/swagger-editor/src/components/SwaggerEditor/SwaggerEditorGettingStarted.vue
packages/swagger-editor/src/components/SwaggerEditor/TheHuman.vue
projects/web/src/components/MockFooter.vue

improve getting started page

---

.changeset/slimy-emus-train.md
packages/api-reference/src/components/Card/Card.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/ReferenceEndpoint.vue

Before:
https://github.com/scalar/scalar/assets/6201407/45d88859-fdd9-4cf4-9a81-6b9d93deeb0d
After:
Uploading after.mov…
++ improve card max height
Before:
After:

fix cards overlapping header

---

.changeset/pretty-dots-beam.md
packages/api-reference/src/components/ApiReferenceBase.vue
packages/api-reference/src/components/ApiReferenceLayout.vue
projects/web/src/pages/ApiReferencePage.vue

https://github.com/scalar/scalar/assets/6374090/0c9399a0-e00f-47ab-aaa0-f7c272818048

refactor: bring back the footer slot

---

.changeset/hot-coins-do.md
packages/api-reference/src/components/Content/Schema.vue

style: no text transform for model names

---

.changeset/selfish-candles-dress.md
packages/fastify-api-reference/README.md
packages/fastify-api-reference/src/templates/index.ejs
packages/themes/README.md
projects/fastify-api-reference/src/index.ts

With this PR a custom Fastify theme is used for the plugin. You can still use one of the other themes, but the new default is the Fastify theme.
Preview: https://fastify.apidocumentation.com/

style: custom Fastify theme

---

package.json
pnpm-lock.yaml

This PR removes Babel, because … we don’t use it. 😅

chore: remove babel

---

.changeset/strange-dogs-hope.md
packages/swagger-editor/src/components/SwaggerEditor/SwaggerEditorInput.vue

I don't know if this is important but it breaks a lot of stuff...

fix: remove empty content update

---

packages/api-reference/src/components/SearchModal.vue

Extended search functionality with models.
Resolves #298

feat(SearchModal): extend search with models

---

.changeset/selfish-baboons-impress.md
.changeset/thick-rules-explode.md
packages/api-reference/src/components/Content/ReferenceEndpoint/Copy.vue
packages/api-reference/src/hooks/useOperation.ts
packages/api-reference/src/types.ts
packages/swagger-parser/src/helpers/parse.ts

This PR keeps track of the path parameters and adds them to the parameter tables.

fix: endpoint level parameters are ignored in the UI, fix #499

---

.changeset/angry-worms-smell.md
packages/api-reference/src/components/Content/Authentication/Authentication.stories.ts
packages/api-reference/src/components/Content/Authentication/Authentication.vue
packages/api-reference/src/components/Content/Authentication/SecuritySchemeSelector.vue
packages/api-reference/src/components/Content/Content.vue
packages/api-reference/src/components/SearchModal.vue
packages/api-reference/src/components/Sidebar.vue
packages/api-reference/src/hooks/useParser.test.ts
packages/api-reference/src/hooks/useParser.ts
packages/api-reference/src/types.ts

WIP: Need to fix the TS issues.
What I changed in #489 was a mistake. This produced empty forms if "Not Authentication" is selected.
This PR adds an Authentication story 💅 and fixes it. The initial issue was actually caused by a lacking spec.
**Before**
**After**

fix: don’t show an empty form if "No Authentication" is selected

---

.changeset/four-ants-jump.md
packages/api-reference/src/components/SearchModal.vue

fix: set search modal variant

---

.changeset/early-sheep-mate.md
packages/api-reference/src/components/Section/Section.vue

https://github.com/scalar/scalar/assets/6374090/842ee77c-14b8-4d31-b668-db74263dabf0

fix: offset sections by header height for scrolling

---

examples/api-client-proxy/package.json
examples/backend/package.json
examples/echo-server/package.json
examples/express-api-reference/package.json
examples/fastify-api-reference/package.json
examples/hono-api-reference/package.json
examples/react/package.json
examples/ssg/package.json
examples/web/package.json
package.json
packages/api-client-proxy/package.json
packages/api-client/package.json
packages/api-reference/package.json
packages/components/package.json
packages/echo-server/package.json
packages/express-api-reference/package.json
packages/fastify-api-reference/package.json
packages/hono-api-reference/package.json
packages/swagger-editor/package.json
packages/swagger-parser/package.json
packages/themes/package.json
packages/use-clipboard/package.json
packages/use-codemirror/package.json
packages/use-keyboard-event/package.json
packages/use-modal/package.json
packages/use-toasts/package.json
packages/use-tooltip/package.json

This PR reorders all properties in all package.json files. 💅

chore: run custom format script

---

packages/use-clipboard/package.json
packages/use-clipboard/vite.config.ts
packages/use-codemirror/package.json
packages/use-codemirror/tsconfig.json
packages/use-codemirror/vite.config.ts
packages/use-keyboard-event/package.json
packages/use-keyboard-event/tsconfig.json
packages/use-keyboard-event/vite.config.ts
packages/use-modal/package.json
packages/use-modal/tsconfig.json
packages/use-modal/vite.config.ts
packages/use-toasts/package.json
packages/use-toasts/tsconfig.json
packages/use-toasts/vite.config.ts
packages/use-tooltip/package.json
packages/use-tooltip/tsconfig.json
packages/use-tooltip/vite.config.ts
pnpm-lock.yaml
scripts/format-package.ts

Migrates towards using peer dependencies to define externals.

feat: Initial vite config cleanup

---

.changeset/cuddly-brooms-rush.md
packages/api-reference/src/components/Sidebar.vue

fix: remove leaky header css

---

README.md

Included concise information regarding the configuration of API references in the root README file.
fixes: #482

chore: Added configuration summary to main README

---

.changeset/nervous-apricots-matter.md
packages/fastify-api-reference/src/fastifyApiReference.ts

remove console log in fastify package

chore: remove console log in fastify package

---

.changeset/sharp-horses-move.md
packages/api-reference/src/components/Content/Content.vue
packages/api-reference/src/components/Content/ModelsAccordion.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/ReferenceEndpointAccordion.vue
packages/api-reference/src/components/Content/ReferenceTagAccordion.vue
packages/api-reference/src/components/Content/Schema.vue
packages/api-reference/src/components/Content/SchemaHeading.vue
packages/api-reference/src/components/Content/SchemaProperty.vue
packages/api-reference/src/components/Section/SectionAccordion.vue
packages/api-reference/src/components/Section/SectionContainerAccordion.vue

https://github.com/scalar/scalar/assets/6374090/3d77cd89-e5ee-46f1-9e53-50915d1ec37a

feat: add accordion layout for schema models

---

packages/api-reference/src/components/SidebarElement.vue

Oops, I changed this prop
On another note, I feel like this should have triggered a type error 🤔

fix: fix incorrect class prop

---

.changeset/shiny-wombats-study.md
packages/api-reference/src/components/Card/CardContent.vue
packages/api-reference/src/components/Card/CardFooter.vue
packages/api-reference/src/components/Card/CardHeader.vue
packages/api-reference/src/components/Card/types.ts
packages/api-reference/src/components/Content/Authentication/Authentication.vue
packages/api-reference/src/components/Content/Introduction/ClientList.vue
packages/api-reference/src/components/Content/Introduction/ServerList.vue

feat: remove border from introduction card headings

---

packages/api-reference/src/components/ApiReferenceLayout.vue

fix: hotfix for position relative mobile menu

---

.changeset/six-singers-fetch.md
packages/api-reference/src/components/ApiReferenceLayout.vue

fix: update changeset for position relative mobile menu fix

---

.changeset/thirty-rules-flash.md
packages/api-reference/src/components/Card/Card.vue
packages/api-reference/src/components/Content/EndpointsOverview.vue

Added position sticky to endpoints overview
https://github.com/scalar/scalar/assets/2039539/5e383018-d9eb-4fa3-8811-d7d26cb239b8
To test you can replace the pet tag description in `fixtures/petstorev3.json` with
```json
{
"name": "pet",
"description": "Everything about your Pets Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet. Nisi anim cupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum Lorem est aliquip amet voluptate voluptate dolor minim nulla est proident. Nostrud officia pariatur ut officia. Sit irure elit esse ea nulla sunt ex occaecat reprehenderit commodo officia …
```

style: add position sticky to endpoints overview

---

packages/api-reference/src/components/ApiReferenceBase.vue
packages/swagger-editor/src/components/SwaggerEditor/SwaggerEditor.vue

There is something  very strange going on with content. I haven't found the source yet but it looks like its getting overwritten from a ref -> to a string.

fix: add ref back

---

.changeset/pink-horses-promise.md
packages/api-reference/package.json
pnpm-lock.yaml

This PR updates @scalar/snippetz. 🌐 
```diff
const { statusCode, body } = await request('https://example.com', {
method: 'POST',
headers: {
'Content-Type': 'application/json; charset=utf-8'
},
-  body: {
-    hello: 'world'
-  },
+  body: JSON.stringify({
+    hello: 'world'
+  }),
})
```

fix: add JSON.stringify to undici body

---

.changeset/empty-flies-share.md
examples/web/src/components/PageLink.vue
examples/web/src/main.ts
examples/web/src/pages/EmbeddedApiReferencePage.vue
examples/web/src/pages/StandaloneApiReferencePage.vue
examples/web/src/pages/StartPage.vue
packages/api-reference/src/components/ApiReferenceLayout.vue

fix: align mobile navigation to header

---

.changeset/dirty-pans-decide.md
packages/api-reference/src/components/Content/Content.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/EndpointDetailsCard.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/EndpointPath.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/ReferenceEndpointAccordion.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/TryRequestButton.vue
packages/api-reference/src/components/Section/SectionAccordion.vue
packages/api-reference/src/components/Section/SectionContainerAccordion.vue
packages/components/src/components/ScalarIconButton/ScalarIconButton.vue

Made classic theme more minimal
Still have some work to do but mostly there

feat: classic layout polish

---

.changeset/tall-clouds-sparkle.md
packages/api-reference/src/components/SearchModal.vue

https://github.com/scalar/scalar/assets/6374090/23cf071a-7b18-4e74-a1ec-b8245e9450a5

fix: make fuse data reactive

---

.changeset/tricky-rats-know.md
packages/api-reference/src/components/MobileHeader.vue
packages/api-reference/src/components/Sidebar.vue
packages/api-reference/src/components/SidebarElement.vue
packages/api-reference/src/components/SidebarGroup.vue

I don't think this breaks anything but worth giving a test

refactor: scope all sidebar styles

---

.changeset/cold-cherries-speak.md
packages/api-client/src/helpers/sendRequest.ts

**Problem**
we get this error for setting cookies
https://stackoverflow.com/questions/50256737/cookie-in-header-javascript-error-refused-to-set-unsafe-header-cookie
**Solution**
proper setting of cookies

fix: proper null check and proper set of cookies

---

.changeset/cyan-carrots-leave.md
packages/api-reference/src/components/Card/Card.vue
packages/api-reference/src/components/Content/Authentication/CardFormButton.vue
packages/api-reference/src/components/Content/Models.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/EndpointDetails.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/ParameterItem.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/Parameters.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/ReferenceEndpointAccordion.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/RequestBody.vue
packages/api-reference/src/components/Content/ReferenceTag.vue
packages/api-reference/src/components/Content/Schema.vue
packages/api-reference/src/components/Content/SchemaProperty.vue
packages/api-reference/src/components/Section/SectionContainer.vue
packages/api-reference/src/components/Section/SectionHeader.vue

lots of small fixes by the wonderful @cameronrohani

fix: regression UI fixes

---

README.md

[Rich Preview](https://github.com/scalar/scalar/pull/751/files?short_path=b335630)

chore: add layouts to readme

---

.changeset/quick-donuts-hear.md
packages/api-client/src/helpers/findVariables.ts
packages/api-reference/src/components/Content/ReferenceEndpoint/ExampleRequest.vue
packages/api-reference/src/components/SidebarElement.vue

I think this should fix everything?

fix: cleanup safari bugs

---

.changeset/weak-singers-leave.md
packages/api-reference/src/components/ClassicHeader.vue
packages/api-reference/src/components/Content/ReferenceEndpoint/EndpointDetailsCard.vue
packages/api-reference/src/components/Layouts/ClassicLayout.vue
packages/api-reference/src/components/SearchButton.vue
packages/api-reference/src/components/Section/Section.vue
packages/api-reference/src/components/Section/SectionAccordion.vue
packages/api-reference/src/components/Section/SectionContainerAccordion.vue

fixed some small classic layout issues around padding and custom themes

fix: classic layout fixes

---

.changeset/friendly-coats-relax.md
README.md
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/GettingStarted.vue
packages/themes/src/index.ts
packages/themes/src/presets/bluePlanet.css
packages/themes/src/presets/deepSpace.css
packages/themes/src/presets/kepler.css
packages/themes/src/presets/mars.css
packages/themes/src/presets/saturn.css

it's space time :) 
https://github.com/scalar/scalar/assets/6176314/f5b592b9-86f7-4f9d-a771-a588e28b14ca
todo:

feat: add space themes

---

packages/fastify-api-reference/package.json
packages/fastify-api-reference/src/fastifyApiReference.ts

Update to fastify-html v0.3.0

---

.changeset/purple-oranges-taste.md
packages/api-reference/src/components/SearchModal.vue

keyboard nav scrolls the selectedItem into view now ✨

feat: scroll search selected item into view with keyboard nav

---

.changeset/tall-cougars-cover.md
packages/api-reference/src/components/Content/Models.vue
packages/api-reference/src/components/Content/Schema.vue
packages/api-reference/src/components/Content/SchemaProperty.vue
packages/api-reference/src/components/SearchModal.vue
packages/api-reference/src/helpers/getExampleFromSchema.test.ts
packages/api-reference/src/helpers/getExampleFromSchema.ts
packages/api-reference/src/hooks/useSidebar.ts

Currently, we ignore `additionalProperties`.
With this PR we’re merging the regular schema with the (optional) additionalProperties and show them in the example requests/responses and in the models.
Also, I’ve seen that models can have a title. With this PR the title is used for the sidebar, the search results and the heading.
See #818.
<details>
<summary>Show Example Spec</summary>
```json
{
"info": {
"title": "Sample API",
"description": "",
"version": "1.0"        
},
"paths": {
"/beta/": {
"get": {
"tags": [
"My Tag"
],
"summary": "My Summary",
"description": "My Description",
"operationId": "get_my_stuff",
"parameters": [
{
"required": false,
"schema": {
"enum": [
"application/json",
"text/csv",
"application/csvm+json",
"*/*"
],
"title": "Accept" …
```

feat: show additionalProperties, fix #818

---

README.md

This adds Laravel Scribe to the README. :)

chore: add Laravel Scribe to the README

---

.changeset/young-humans-hope.md
packages/api-reference/src/components/Content/ReferenceEndpoint/ParameterItem.vue
packages/api-reference/src/components/Content/Schema.vue
packages/api-reference/src/components/Content/SchemaProperty.vue

All schemas are beautiful, but not all are complete. With this PR we deal better with them. 💅 
**Before**
**After**
**Example Spec**
https://sandbox.scalar.com/e/OlTLp

fix: deal with incomplete schemas

---

.github/workflows/deploy-preview.yml

With this PR, we are using a GitHub actions workflow for building and deploying Scalar previews to Netlify.

chore: github action workflow to deploy scalar preview

---

.changeset/wicked-moose-drive.md
packages/nextjs-api-reference/package.json

This should allow to install it with Next.js 14. :)

chore: allow Next.js 14

---

.changeset/gentle-buses-lie.md
packages/api-reference/src/components/Content/Authentication/Authentication.stories.ts
packages/api-reference/src/components/Content/Authentication/Authentication.vue
packages/api-reference/src/components/Content/Authentication/SecurityScheme.vue
packages/api-reference/src/components/Content/Authentication/SecuritySchemeSelector.vue
packages/api-reference/src/components/Content/Introduction/Introduction.vue
packages/api-reference/src/components/Content/Models.vue
packages/api-reference/src/components/Content/ModelsAccordion.vue
packages/api-reference/src/components/Content/SchemaHeading.vue
packages/api-reference/src/helpers/getRequestFromAuthentication.test.ts
packages/api-reference/src/helpers/getRequestFromAuthentication.ts
packages/api-reference/src/types.ts

Fortunately, this Tweet didn’t take off. Anyway, it’s time to improve the types, at least a bit. 🤡 
https://twitter.com/FreckleBytes/status/1744934392588616082
I’ve added better types to our `Spec` type, was able to remove some of our own types, properly type the security schemes in most places.
But I’ve also had to add some additional @ts-ignores, mostly in tests and in some places where I just didn’t know better. Still lots to do …

chore: improve types

---

README.md

Let’s add an information about the next townhall to the root README. :)

chore: add the next Townhall to the README

---

README.md

feat: add rust documentation for aide with scalar 🦀 

---

.changeset/clever-toes-care.md
packages/api-client-proxy/src/createApiClientProxy.ts
packages/swagger-editor/src/helpers/fetchSpecFromUrl.ts

I didn't know this was using the API Client proxy when I changed it to return blobs 🤦

fix: expect a blob when fetching spec via proxy

---

packages/use-codemirror/src/hooks/useCodeMirror.ts

Add reactive provider for useCodemirror hook. Resets the extensions when the provider changes.

feat: Add optional extensions and reactive provider to useCodemirror

---

.changeset/clean-cherries-accept.md
packages/api-client-proxy/src/createApiClientProxy.test.ts
packages/api-client-proxy/src/createApiClientProxy.ts
packages/api-client-proxy/src/index.ts
packages/api-client-proxy/src/types.ts
packages/api-client/src/components/ApiClient/RequestHistoryItem.vue
packages/api-client/src/components/ApiClient/Response/Response.vue
packages/api-client/src/components/ApiClient/Response/ResponseBody.vue
packages/api-client/src/components/ApiClient/Response/ResponseMetaInformation.vue
packages/api-client/src/helpers/sendRequest.test.ts
packages/api-client/src/helpers/sendRequest.ts
packages/api-client/src/types.ts
packages/swagger-editor/src/helpers/fetchSpecFromUrl.ts

Rollsback #883 #950 #955
After chatting with @marclave it seems like we have too many exisiting sites using an old version of the proxy to do it the way I did in #883, we'll need to try again in a more backwards compatible way 😢

fix: rollback api client proxy and request changes

---

.changeset/fast-boats-promise.md
.changeset/small-horses-sort.md
packages/api-client/package.json
packages/api-client/src/components/ApiClient/Request/RequestQuery.vue
packages/api-client/src/components/ApiClient/Request/RequestVariables.vue
packages/api-client/src/components/Grid/Grid.vue
packages/api-reference/src/helpers/getApiClientRequest.ts
packages/api-reference/src/helpers/getParametersFromOperation.ts
packages/api-reference/src/helpers/getRequestFromOperation.ts
pnpm-lock.yaml

fixes https://github.com/scalar/scalar/discussions/731
before 😮‍💨 
after 😎

feat: add show more button to request variables and path params

---

packages/api-reference/src/components/Content/Operation/OperationAccordion.vue
packages/components/env.d.ts
packages/components/package.json
packages/components/src/components/ScalarModal/ScalarModal.vue
packages/components/src/components/ScalarTextField/ScalarTextField.vue
packages/components/tailwind.config.ts
pnpm-lock.yaml

chore: switch tailwind to use px values

---

.changeset/pink-owls-cry.md
packages/api-reference/src/components/Card/CardHeader.vue
packages/api-reference/src/components/Content/Authentication/Authentication.vue
packages/api-reference/src/components/Content/BaseUrl/BaseUrl.vue
packages/api-reference/src/components/Content/BaseUrl/ServerItem.vue
packages/api-reference/src/components/Content/ClientLibraries/ClientLibraries.vue
packages/api-reference/src/components/Content/Content.vue

Fixes #946
https://github.com/scalar/scalar/assets/6374090/960c5a12-e354-4f1f-ab16-3cf1f3b81bc4
https://github.com/scalar/scalar/assets/6374090/75e1069a-f24d-4517-a42a-8f8d58d7ae14

fix: resize classic intro cards for difference screen sizes

---

.changeset/plenty-beds-marry.md
packages/api-client/src/components/ApiClient/Response/ResponseBody.vue
packages/api-reference/src/components/Content/Operation/PathResponses/PathResponses.vue

**Problem**
if your response is of type `application/problem+json` we return No Body
https://discord.com/channels/1135330207960678410/1135330208627564597/1210630137326862378
https://datatracker.ietf.org/doc/html/rfc9457

fix: quick fix for supporting application/problem+json

---

.changeset/quiet-tables-sleep.md
packages/fastify-api-reference/src/utils/getJavaScriptFile.ts

#1044 didn’t fix it, let’s ff this. :) I found a way to test it this time.

fix: __dirname undefined

---

packages/fastify-api-reference/src/fastifyApiReference.ts
packages/themes/src/base.css

If your system differs from the  .dark-mode and .light-mode colours the scrollbar colours get messed up.
This fixes that.
+ fix fastify theme issue

fix: add back color schemes

---

.changeset/sweet-pillows-impress.md
packages/themes/src/presets/alternate.css
packages/themes/src/presets/bluePlanet.css
packages/themes/src/presets/deepSpace.css
packages/themes/src/presets/default.css
packages/themes/src/presets/kepler.css
packages/themes/src/presets/mars.css
packages/themes/src/presets/purple.css
packages/themes/src/presets/saturn.css

Fixed sidebar not having `--default` prefix 
Removed unused header css

fix: fixsidebar theme precedence and remove unused OSS variables

---

.changeset/cuddly-apricots-destroy.md
packages/api-reference/src/components/Content/Authentication/CardFormButton.vue
packages/api-reference/src/components/Content/Authentication/SecuritySchemeScopes.vue
packages/api-reference/src/components/Content/Schema/Schema.vue
packages/api-reference/src/components/MarkdownRenderer/MarkdownRenderer.vue
packages/api-reference/src/components/Sidebar/SidebarElement.vue

fix: visual regressions

---

.changeset/twenty-rules-eat.md
packages/api-reference/src/components/MobileHeader.vue

fix: mobile header button fix

---

.changeset/proud-ways-give.md
packages/api-reference/src/components/Content/Authentication/CardFormButton.vue
packages/api-reference/src/components/Content/ClientLibraries/ClientSelector.vue
packages/api-reference/src/components/Content/Content.vue
packages/api-reference/src/components/MarkdownRenderer/MarkdownRenderer.vue
packages/api-reference/src/components/Sidebar/SidebarElement.vue
packages/themes/src/base.css

fix: style of references from revert

---

.changeset/blue-fans-burn.md
packages/api-reference/src/components/Content/Introduction/Description.vue
packages/api-reference/src/components/MarkdownRenderer/MarkdownRenderer.vue

fix: only remove margin from 1st paragraph

---

.changeset/curvy-crews-glow.md
packages/api-client/src/components/ApiClient/Response/ResponseBody.vue
packages/api-reference/src/components/Content/Operation/PathResponses/PathResponses.vue

**Problem**
if your response is of type application/vnd.api+json we return No Body
https://www.iana.org/assignments/media-types/application/vnd.api+json

fix: quick fix for supporting application/vnd.api+json

---

.changeset/heavy-wolves-study.md
packages/api-reference/src/index.ts

Need to export getting started component for improved external integrations

feat: export getting started

---

.changeset/selfish-squids-beg.md
packages/api-reference/src/components/Sidebar/SidebarElement.vue

Sidebar item hover colour variable wasn't being applied

fix: add back sidebar item hover color

---

.changeset/tame-taxis-return.md
examples/web/src/fixtures/petstorev3.json
packages/api-reference/src/components/Content/Authentication/SecurityScheme.vue
packages/api-reference/src/helpers/getRequestFromAuthentication.test.ts
packages/api-reference/src/helpers/getRequestFromAuthentication.ts
packages/api-reference/src/stores/globalStore.ts
packages/api-reference/src/types.ts

Adds as basic implementation of oauth2 implicit flow

feat: allow oauth2 implicit flow, fix #604

---

README.md
documentation/adonisjs.md

This PR adds a detailed integration guide for AdonisJS and adds AdonisJS to the root README.

docs: new AdonisJS guide

---

.changeset/six-apples-cough.md
packages/api-client-react/src/ApiClientReactBase.tsx

Quick fix for react, but we still need the reactivity fix on the client

fix: allow api client react to be editable

---

.github/workflows/release.yml
packages/proxy-server/wrangler.toml

feat: add release-proxy-server job

---

.changeset/neat-queens-smile.md
packages/components/src/components/ScalarCodeBlock/ScalarCodeBlock.spec.ts
packages/components/src/components/ScalarCodeBlock/ScalarCodeBlock.vue

Previously broke the schema show with the SSR PR. This fixes that issue and also adds a test to prevent it in the future

fix: schema show on example responses

---

.changeset/ten-icons-happen.md
packages/api-reference/src/hooks/useSidebar.ts

now models can be added to tag groups!
example spec:
```
{
"openapi": "3.0.2",
"x-tagGroups": [
{
"name": "Customers",
"tags": ["PET", "STORE", "MODELS"]
}
],
"info": {
"title": "Swagger Petstore - OpenAPI 3.0",
"description": "This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about\nSwagger at [http://swagger.io](http://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!\nYou can now help us improve the API whether it's by making changes to the definition itself or to the code.\nThat way, with time, we can improve the API in general, and expose some of the new features in OAS3.\n\nSome useful links:\n- [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)\n- [The source API …
```

fix: add models to tag groups

---

.changeset/dry-sheep-smile.md
packages/api-client-react/src/style.css
packages/themes/src/base.css

Put border indents in proper file

fix: put border indents in proper file

---

.changeset/mean-readers-suffer.md
packages/api-reference/src/components/Content/Introduction/DownloadSpec.vue
packages/api-reference/src/components/MarkdownRenderer/MarkdownRenderer.vue
packages/nextjs-api-reference/src/theme.ts
packages/themes/src/base.css
packages/themes/src/presets/alternate.css
packages/themes/src/presets/bluePlanet.css
packages/themes/src/presets/deepSpace.css
packages/themes/src/presets/kepler.css
packages/themes/src/presets/mars.css

finally fix the text decoration targeting + removed some unused CSS in themes

fix: text decoration targetting

---

.changeset/mean-eels-peel.md
packages/api-reference/src/components/MarkdownRenderer/MarkdownRenderer.vue
packages/api-reference/src/components/Sidebar/SidebarElement.vue

First time using sidebar indent border hover variable and I misnamed it 😅
+ remove the important's that are no longer needed

fix: theme variable name + remove some importants

---

examples/hono-api-reference/package.json
examples/hono-api-reference/src/index.ts
examples/nextjs-api-reference/package.json
package.json
pnpm-lock.yaml

Just some minor changes, fixed types and added the scalar package which was missing.

fix: typescript in hono example

---

.changeset/eight-donkeys-switch.md
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue

read only was right aligned, this left aligns it!

fix: left align read only

---

.changeset/beige-spies-join.md

**Problem**
Currently, …
This happens because …
**Solution**
With this PR …

docs(changeset): manual fastify release

---

.changeset/chilled-forks-sip.md
packages/components/src/components/ScalarCodeBlock/ScalarCodeBlock.vue

Fix tabbing on docusaurus code block

fix: docusaurus code block

---

.changeset/good-falcons-hope.md
packages/api-reference/README.md
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/Content/Content.vue
packages/api-reference/src/components/SearchModal.vue
packages/api-reference/src/hooks/useSidebar.ts
packages/api-reference/src/types.ts

you can now hide models which results in not showing it in the Content, Sidebar & search

feat: add config to hide models

---

.changeset/loud-dogs-film.md
packages/api-reference/README.md
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/Content/Introduction/DownloadSpec.vue
packages/api-reference/src/helpers/provideSymbols.ts
packages/api-reference/src/types.ts

now you can hide the download button :)

feat: add config to hide download button

---

.changeset/brave-gorillas-brake.md
packages/oas-utils/package.json

Axios was missing as a peer dependency

feat: add axios peer dependency

---

.changeset/fifty-poets-relate.md
packages/api-reference/src/components/Sidebar/SidebarElement.vue

fixes new precedence issue and removes unused / code

fix: sidebar heading type remove hover color

---

.changeset/tiny-cooks-smell.md
packages/api-reference/src/components/SearchModal.vue

fixes https://github.com/scalar/scalar/issues/1440

fix: give explicit URL to href in search modal

---

.changeset/blue-dolls-tan.md
.changeset/thin-garlics-study.md
packages/api-reference/src/components/CustomToaster.vue
packages/nuxt/package.json
packages/nuxt/src/module.ts
packages/nuxt/src/runtime/components/nuxt-theme.css

This fixes the commonJs issues that the nuxt integration was having. Also updated the theme and made the toaster client only.

fix: nuxt integration

---

.changeset/olive-items-wait.md
packages/nuxt/src/runtime/components/nuxt-theme.css

fix: update nuxt theme variables

---

.changeset/nice-swans-report.md
packages/nuxt/src/module.ts
packages/nuxt/src/types.ts

**Problem**
Currently, there is not scalar tab in Nuxt DevTools
**Solution**
this PR adds support for Nuxt DevTools

feat(nuxt): add scalar tab to nuxt devtools

---

.changeset/stale-mice-pump.md
packages/api-reference/src/components/GettingStarted.vue
packages/themes/src/presets/kepler.css

**Problem**
active start item border misalignment, hover wrong radiuses and background lacking accessibility.
**Solution**
this pr is a proposal approach on the active start item style + re-use call to action hover background color for start item.

style: getting started tables

---

.github/workflows/validate-openapi-file.yml
specifications/scalar-galaxy-3.1.json
specifications/scalar-galaxy-3.1.yaml

Oops, our new example specification didn’t pass our validation. 🤡 
Let’s ff with the fixes and add a check to CI.

fix: example specification doesn’t pass validation

---

.changeset/smart-kids-judge.md
packages/components/src/components/ScalarIcon/icons/icons.ts

this pr adds the missing icon types following #1525.

fix: scalar icon type

---

README.md
packages/api-reference/README.md
packages/api-reference/src/types.ts

I’ve found a few minor typos, let‘s fix them swiftly. :)

fix: typos

---

.changeset/nine-mayflies-explode.md
packages/api-reference/src/components/MarkdownRenderer/MarkdownRenderer.vue

https://github.com/scalar/scalar/assets/6374090/051ad70d-6dcd-4550-8271-602b9a52d0f5

feat: add chevron for markdown summary

---

.changeset/tasty-comics-matter.md
packages/api-reference/src/components/Content/Operation/RequestBody.vue
packages/api-reference/src/components/Content/Operation/TryRequestButton.vue
packages/api-reference/src/components/Content/Schema/Schema.vue
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue
specifications/scalar-galaxy-3.1.json

**Problem**
as describe in #1498, description are duplicated when there is additional properties + request body description are not displayed.
**Solution**
this pr fixes the duplicate description + introduces the request body description:

fix: additional properties duplicate description

---

README.md

I thought it would be fun to offer our help with custom themes.
We do this anyway, why not promote it? :)
Also, I love to show the Windows 98 example to people. This PR adds a link to it in the styling section.

docs: offer to make a custom theme

---

cloudbuild.yaml
examples/nestjs-api-reference-fastify/.dockerignore
examples/nestjs-api-reference-fastify/Dockerfile

containerize nestjs fastify example app for deployment

chore: containerize nestjs fastify example app

---

.changeset/hip-spies-walk.md
packages/api-reference/src/components/Sidebar/SidebarHttpBadge.vue
packages/nuxt/README.md
packages/nuxt/playground/nuxt.config.ts
packages/nuxt/src/module.ts
packages/themes/src/components/DefaultFonts.vue

Fixed a couple minor bugs and allow multiple configs for nuxt integration.
closes #1500

feat(#1500): allow multiple specs for nuxt integration

---

.changeset/quick-boats-thank.md
packages/components/src/tailwind/index.ts

fix: remove ts extension from tailwind export

---

examples/nestjs-api-reference-fastify/Dockerfile
examples/nestjs-api-reference-fastify/src/main.ts

Get PORT from env in server code and Dockerfile

fix: nestjs fastify example

---

cloudbuild.yaml
examples/api-client-proxy/package.json
examples/cdn-api-reference/package.json
examples/echo-server/package.json
examples/express-api-reference/package.json
examples/fastify-api-reference/package.json
examples/hono-api-reference/.dockerignore
examples/hono-api-reference/Dockerfile
examples/hono-api-reference/package.json
examples/hono-api-reference/src/index.ts
examples/hono-api-reference/tsconfig.json
package.json
packages/api-client-proxy/package.json
packages/cli/package.json
packages/echo-server/package.json
packages/mock-server/package.json
pnpm-lock.yaml

Containerize and deploy Hono example app using Docker and Cloudbuild. Bumps vite-node package.

feat: containerize and deploy hono example app

---

examples/express-api-reference/Dockerfile

Comment and streamline Dockerfile
Set env variable for PORT

fix: express api reference example

---

.changeset/soft-scissors-sip.md
packages/cli/package.json
packages/cli/src/commands/init/InitCommand.ts
pnpm-lock.yaml

this pr introduces cli style updates + directory navigation capability when filling the OpenAPI file path in the cli during project init.

feat: cli style updates + directory navigation 

---

.changeset/new-jeans-mate.md
packages/draggable/package.json
packages/draggable/vite.config.ts
pnpm-lock.yaml

fix: export draggable types

---

.changeset/sharp-mangos-yell.md
packages/cli/package.json
packages/cli/rollup.config.js
packages/cli/tests/invoke-cli.ts
packages/mock-server/package.json
packages/mock-server/rollup.config.js
packages/mock-server/src/createMockServer.ts
packages/mock-server/tsconfig.build.json
packages/mock-server/tsconfig.json
pnpm-lock.yaml

Oops, the mock server build process was messed up and the types weren't properly exported.
This PR updates the build process and should fix the type export. 👍

fix: wrong types export for mock server 

---

.changeset/tiny-masks-hide.md
packages/api-reference/src/hooks/useClipboard.ts
packages/use-toasts/src/components/ScalarToasts.vue

feat: clean up toast styles and colors

---

README.md

All headings start with “With…”. I don’t think that’s needed. 😅

docs: remove “With …”

---

examples/web/.env.development
examples/web/src/pages/StartPage.vue

Set the urls for deployed example apps on the example page.

chore: set example urls

---

.changeset/shiny-apricots-rhyme.md

docs(changeset): chore: bump packages

---

.changeset/tender-cherries-tickle.md
.changeset/wet-apples-film.md
packages/draggable/src/Draggable.vue

Went down a rabbit hole of trying to get anchor links to drag properly. Turns out they got their own drag business going on. Just going to switch to divs with click listeners for now

fix: drag and drop

---

packages/play-button/README.md

feat: add docs

---

.changeset/brave-lions-applaud.md
packages/api-client/src/components/ApiClient/AddressBar.vue
packages/api-client/src/components/ApiClient/RequestMethodSelect.vue

this pr updates the api client address bar style as seen below:

feat: api client address bar style

---

examples/proxy-server/main.go

before we werent actually setting the path! fixed now :)

fix: missing path for request proxy

---

examples/proxy-server/main.go

we didnt handle CORS :) now we do ✨

fix: add cors support to proxy

---

.changeset/gold-lions-drive.md
packages/api-client/src/components/ApiClient/AddressBar.vue
packages/api-client/src/components/ApiClient/ApiClient.vue
packages/api-client/src/components/ApiClient/Request/Request.vue
packages/api-client/src/components/ApiClient/Request/RequestAuthentication/CardForm.vue
packages/api-client/src/components/ApiClient/Request/RequestAuthentication/CardFormButton.vue
packages/api-client/src/components/ApiClient/Request/RequestAuthentication/CardFormGroup.vue
packages/api-client/src/components/ApiClient/Request/RequestAuthentication/CardFormTextInput.vue
packages/api-client/src/components/ApiClient/Request/RequestAuthentication/RequestAuthentication.vue
packages/api-client/src/components/ApiClient/Request/RequestAuthentication/SecurityScheme.vue
packages/api-client/src/components/ApiClient/Request/RequestAuthentication/SecuritySchemeScopes.vue
packages/api-client/src/components/ApiClient/Request/RequestAuthentication/SecuritySchemeSelector.vue
packages/api-client/src/components/ApiClient/Request/RequestCookies.vue
packages/api-client/src/components/CollapsibleSection/CollapsibleSection.vue
packages/api-client/src/components/Grid/Grid.vue
packages/api-client/src/components/Grid/GridHeader.vue
packages/api-client/src/components/Grid/GridRow.vue
packages/api-client/src/components/Grid/GridRowEditable.vue
packages/api-client/src/components/SimpleTable/SimpleCell.vue
packages/api-client/src/components/SimpleTable/SimpleHeader.vue
packages/api-client/src/components/SimpleTable/SimpleTable.vue
packages/api-reference/src/components/ApiClientModal.vue
packages/use-codemirror/src/components/CodeMirror/CodeMirror.vue

feat: update api client UI

---

.changeset/clean-seahorses-listen.md
packages/api-client/src/components/Grid/GridRowEditable.vue

fix: required bg color

---

.changeset/fluffy-drinks-ring.md
packages/api-reference/src/components/ApiClientModal.vue

fix the blurry popup some users are facing

fix: blurry api client popup

---

.changeset/eight-roses-protect.md
packages/api-reference/src/components/ApiClientModal.vue

remove transform to fix windows users blur

fix: client popup blur

---

.changeset/many-ways-smell.md
packages/api-client/src/components/ApiClient/AddressBar.vue
packages/api-client/src/components/ApiClient/ApiClient.vue
packages/api-client/src/components/ApiClient/Request/Request.vue
packages/api-client/src/components/ApiClient/Request/RequestAuthentication/CardFormTextInput.vue
packages/api-client/src/components/ApiClient/Request/RequestAuthentication/RequestAuthentication.vue
packages/api-client/src/components/ApiClient/Request/RequestAuthentication/SecuritySchemeSelector.vue
packages/api-client/src/components/ApiClient/Request/RequestCookies.vue
packages/api-client/src/components/ApiClient/Request/RequestHeaders.vue
packages/api-client/src/components/ApiClient/Request/RequestQuery.vue
packages/api-client/src/components/ApiClient/Request/RequestVariables.vue
packages/api-client/src/components/CollapsibleSection/CollapsibleSection.vue
packages/api-client/src/components/Grid/Grid.vue
packages/api-client/src/components/Grid/GridHeader.vue
packages/api-client/src/components/Grid/GridRow.vue
packages/api-client/src/components/Grid/GridRowEditable.vue
packages/api-client/src/components/SimpleTable/SimpleCell.vue
packages/api-client/src/components/SimpleTable/SimpleHeader.vue
packages/api-client/src/components/SimpleTable/SimpleRow.vue
packages/api-client/src/components/SimpleTable/SimpleTable.vue
packages/use-codemirror/src/components/CodeMirror/CodeMirror.vue

Before:
After:
Note: there's still a few things I'm not happy with about this but need it in for now 🙈

feat: client ui updates

---

.changeset/short-planes-flow.md
packages/api-client-react/src/style.css
packages/api-client/src/components/ApiClient/Request/RequestAuthentication/SecuritySchemeSelector.vue
packages/api-client/src/components/CollapsibleSection/CollapsibleSection.vue
packages/api-reference/src/components/Content/Authentication/Authentication.vue
packages/api-reference/src/components/Content/BaseUrl/BaseUrl.vue
packages/api-reference/src/components/Content/ClientLibraries/ClientLibraries.vue
packages/api-reference/src/components/Content/ClientLibraries/ClientSelector.vue
packages/api-reference/src/components/Content/Content.vue
packages/nextjs-api-reference/src/theme.ts
packages/themes/src/presets/alternate.css
packages/themes/src/presets/bluePlanet.css
packages/themes/src/presets/deepSpace.css
packages/themes/src/presets/kepler.css
packages/themes/src/presets/mars.css
packages/themes/src/presets/moon.css
packages/themes/src/presets/saturn.css

feat: intro card redesign

---

.changeset/orange-plants-jump.md
packages/api-client/src/components/ApiClient/AddressBar.vue
packages/api-client/src/components/ApiClient/ApiClient.vue
packages/api-client/src/components/ApiClient/Request/Request.vue
packages/api-client/src/components/ApiClient/Request/RequestAuthentication/RequestAuthentication.vue
packages/api-client/src/components/ApiClient/Request/RequestAuthentication/SecuritySchemeSelector.vue
packages/api-client/src/components/ApiClient/Response/Response.vue
packages/api-client/src/components/CollapsibleSection/CollapsibleSection.vue
packages/api-client/src/components/Grid/Grid.vue
packages/api-client/src/components/Grid/GridRow.vue
packages/api-client/src/components/Grid/GridRowEditable.vue
packages/api-client/src/components/SimpleTable/SimpleCell.vue
packages/api-client/src/components/SimpleTable/SimpleTable.vue

A lot of minor touch ups to req / response
before:
after:

fix: client request response UI

---

.changeset/eighty-ligers-grab.md
packages/api-reference/src/components/Sidebar/SidebarElement.vue
packages/api-reference/src/hooks/useSidebar.ts

**Problem**
currently case in sidebar heading cannot be overload using style [as highlighted by](https://github.com/scalar/scalar/discussions/1271) @Lumca
**Solution**
this pr is a proposal to favor css style to uppercase them in order to allow deeper customization.

feat: api reference sidebar heading link case

---

.changeset/many-points-deliver.md
packages/nuxt/src/module.ts

This was missed when we went back to highlight
closes #1783

fix: rehype-highlight transpilation was missed

---

packages/scalar_fastapi/README.md

**Problem**
Currently, …
This happens because …
**Solution**
With this PR …

chore: provide working example for scalar_fastapi

---

.changeset/healthy-doors-occur.md
packages/cli/package.json
packages/cli/src/commands/init/InitCommand.ts
packages/cli/src/commands/init/init.test.ts
pnpm-lock.yaml

this pr is a proposal to use the beautiful @natemoo-re / clack prompts package over the current prompts one, within the cli init command + adds next step command logs

feat: scalar cli prompts

---

playwright/tests/cdn.spec.ts

Sidebar text changed from uppercase to sentence case.

chore: fix cdn ui test

---

.changeset/clean-hotels-fold.md
examples/react/package.json
examples/react/src/App.tsx
examples/react/src/vite-env.d.ts
packages/api-reference-react/src/ApiReferenceReact.tsx
packages/api-reference/src/esm.ts
packages/galaxy/package.json
packages/galaxy/src/index.ts
packages/galaxy/tsconfig.json
packages/galaxy/vite.config.ts
pnpm-lock.yaml

Uses the new integration API to create a reactive React integration. Component now updates when props change.

feat: Move react integration to reactive interface

---

.changeset/fast-hotels-cheer.md
packages/api-client/src/components/ApiClient/Request/Request.vue

this pr enables body on delete request, and fixes #1876

fix: api client body on delete request

---

examples/proxy-server/main.go

this fixes PUTs failing on pre requests

fix: set allowed headers before options finish

---

examples/proxy-server/main.go

fix: add missing PATCH request to cors allowed origins

---

.changeset/big-parents-drum.md
packages/components/src/index.ts

Removes the component app install, technically this is a breaking change but I don't think anyone was using this feature.
cc @amritk

refactor: remove component app install

---

.changeset/two-pens-refuse.md
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue

fix: style of x enum

---

.changeset/perfect-worms-battle.md
packages/themes/src/components/ResetStyles.vue
packages/themes/src/components/ScrollbarStyles.vue

Needed to put the reset in a layer as well to avoid having it override our tailwind styles

fix: also use cascade layers for CSS reset to avoid overriding tailwind

---

.changeset/late-coins-talk.md
package.json
packages/components/package.json

this pr is a proposal to update script regarding storybook in order to be able to access components on the fly from this page:

fix: storybook script update

---

.changeset/gentle-pumas-melt.md
packages/api-reference/src/hooks/useNavState.ts

missed a console log within the #1914 pr

fix: remove console log in use nav state

---

packages/components/src/index.ts

fix: actually export listbox component

---

.changeset/odd-pugs-rescue.md
packages/api-reference/package.json
packages/api-reference/src/components/MarkdownRenderer/MarkdownRenderer.vue
pnpm-lock.yaml

**Problem**
right now clicking through description items in the sidebar doesn't navigate us to the right item.
**Solution**
this pr is a proposal to add ids to description headings to enable navigation.

fix: markdown navigation

---

.changeset/odd-pugs-rescue.md
packages/api-reference/package.json
packages/api-reference/src/components/MarkdownRenderer/MarkdownRenderer.vue
pnpm-lock.yaml

Reverts scalar/scalar#1920
It adds duplicate IDs, and we have a better solution already.

fix: markdown navigation (rollback)

---

.changeset/unlucky-cycles-sip.md

docs(changeset): chore: export listbox component

---

.changeset/tiny-eagles-explain.md
packages/themes/vite.config.ts

fix: copy fonts to dist directory

---

packages/cli/package.json
packages/components/env.d.ts
packages/components/package.json
packages/components/src/components/ScalarListbox/ScalarListbox.stories.ts
packages/components/tailwind.config.ts
packages/galaxy/package.json
packages/themes/env.d.ts
packages/themes/package.json
packages/themes/src/tailwind.ts
packages/themes/tsconfig.json
packages/themes/vite.config.ts
pnpm-lock.yaml

Took me a minute but I figured out how to do it

feat: move tailwind preset from `@scalar/components` to `@scalar/themes`

---

.changeset/clean-geese-pretend.md
packages/nuxt/README.md

Updated the docs to include this temp fix for `pnpm` + `nuxt`

fix: add troubleshooting docs to nuxt package

---

packages/components/src/components/ScalarListbox/ScalarListbox.vue
packages/themes/src/tailwind.ts

before:
after:
https://github.com/scalar/scalar/assets/6201407/84cd2a75-129a-4e85-a06b-9d21cc42b288

fix: change listbox styles

---

packages/client-app/src/components/Sidebar/Sidebar.vue
packages/client-app/src/views/Request/RequestSidebarItem.vue

Fix scrolling in sidebar + button position
before:
after:

fix: client scrolling in sidebar + dont remove request type on hover

---

packages/client-app/src/components/Sidebar/SidebarListElement.vue
packages/client-app/src/components/Sidebar/SidebarListElementActions.vue
packages/client-app/src/store/workspace.ts
packages/client-app/src/views/Environment/Environment.vue
packages/oas-utils/src/entities/workspace/environment/environment.ts

this pr adds default environment variable to client-app package + fixtures.

feat: improve environment configurations

---

packages/client-app/src/components/DataTable/DataTable.vue
packages/client-app/src/components/DataTable/DataTableText.vue
packages/client-app/src/components/ViewLayout/ViewLayoutCollapse.vue
packages/client-app/src/views/Request/ResponseSection/ResponseBody.vue
packages/client-app/src/views/Request/ResponseSection/ResponseCookies.vue
packages/client-app/src/views/Request/ResponseSection/ResponseHeaders.vue
packages/components/src/components/ScalarCodeBlock/ScalarCodeBlock.vue

remove text inputs for headers response
reduce font size in body
change some border values etc
after:

fix: client response UI

---

packages/client-app/src/libs/index.ts
packages/client-app/src/libs/sendRequest.ts
packages/client-app/src/views/Request/Request.vue

before we couldnt add headers or cookies to requests, we also break up the body appropriately now

fix: missing headers and cookies on send request

---

examples/web/src/pages/StartPage.vue
package.json
packages/client-app/src/components/ActionModal/ActionModalRequest.vue
packages/client-app/src/components/ActionModal/ActionModalVariant.vue
packages/client-app/src/components/AddressBar/AddressBar.vue
packages/client-app/src/components/ViewLayout/ViewLayoutSection.vue
packages/client-app/src/libs/pathParams.ts
packages/client-app/src/libs/sendRequest.ts
packages/client-app/src/router.ts
packages/client-app/src/store/workspace.ts
packages/client-app/src/views/Request/Request.vue
packages/client-app/src/views/Request/RequestSection/RequestBody.vue
packages/client-app/src/views/Request/RequestSection/RequestParams.vue
packages/client-app/src/views/Request/RequestSection/RequestPathParams.vue
packages/client-app/src/views/Request/RequestSection/RequestTable.vue
packages/client-app/src/views/Request/RequestSidebarItem.vue
packages/client-app/src/views/Request/RequestSidebarItemMenu.vue
packages/client-app/vite.config.ts
packages/oas-utils/src/entities/workspace/shared/utility.ts
packages/oas-utils/src/entities/workspace/spec/requests.ts
packages/oas-utils/src/helpers/index.ts
packages/oas-utils/src/helpers/iterateTitle.ts
packages/oas-utils/src/transforms/import-spec.ts

- renamed instances to examples
- adding a new example works (though clicking on it does nothing... for now)
- simplified the schema file (requests.ts) based on zod best practices

feat: rename instances -> examples and make them work 

---

packages/client-app/src/components/DataTable/DataTableInput.vue
packages/client-app/src/components/Form/Form.vue
packages/client-app/src/constants.ts
packages/client-app/src/router.ts
packages/client-app/src/store/workspace.ts
packages/client-app/src/views/Cookies/CookieForm.vue
packages/client-app/src/views/Servers/ServerForm.vue
packages/client-app/src/views/Servers/Servers.vue
packages/oas-utils/package.json
packages/oas-utils/src/entities/workspace/server/index.ts
packages/oas-utils/src/entities/workspace/server/server.ts
packages/oas-utils/src/entities/workspace/workspace.ts

this pr introduces a first server view version in the client-app package as seen below:

feat: improve serverurl interaction in omnibar server page

---

packages/oas-utils/src/entities/workspace/spec/requests.ts
packages/object-utils/vite.config.ts

fix: "fix: build breaking"

---

packages/client-app/src/components/DataTable/DataTableCell.vue
packages/client-app/src/libs/sendRequest.ts
packages/client-app/src/views/Request/RequestSection/RequestBody.vue
packages/client-app/src/views/Request/RequestSection/RequestTable.vue
packages/oas-utils/src/entities/workspace/spec/requests.ts

continuation of https://github.com/scalar/scalar/pull/1966
needs some polish from @cameronrohani :)

feat: add file uploads to request body

---

packages/client-app/src/components/ActionModal/ActionModalRequest.vue

fix: set proper http method on request creation

---

package.json

Unfortunately its not that great, but better than what we had before! Just use this for development on the web example. Maybe we'll add watch next week!

chore: add dev web command

---

README.md

**Problem**
Currently, the `README.md` file points to the wrong contributing file.
This happens because PR #1885 renamed the file from `CONTRIBUTING` to `CONTRIBUTING.md`.
**Solution**
With this PR, it solves the contributing file reference in the `README.md` file.

fix: update contributing file

---

packages/client-app/src/components/AddressBar/AddressBar.vue

this pr favors scalar dropdown component usage for client app address bar server list in order to display call to action:

feat: address bar server interaction

---

packages/client-app/src/components/ContextBar.vue
packages/client-app/src/components/DataTable/DataTable.vue
packages/client-app/src/components/DataTable/DataTableCell.vue
packages/client-app/src/views/Request/Request.vue
packages/client-app/src/views/Request/RequestSection/RequestAuth.vue
packages/client-app/src/views/Request/RequestSection/RequestBody.vue
packages/client-app/src/views/Request/RequestSection/RequestPathParams.vue
packages/client-app/src/views/Request/RequestSidebarItem.vue
packages/client-app/src/views/Request/ResponseSection/ResponseBody.vue
packages/client-app/src/views/Request/ResponseSection/ResponseCookies.vue
packages/client-app/src/views/Request/ResponseSection/ResponseHeaders.vue

this pr updates globally height usage in client app package in order to bring it closer to the tailwind grid.

feat: client app height and border fixtures

---

.changeset/witty-cougars-shave.md
packages/client-app/src/views/Request/RequestSidebarItemMenu.vue
packages/components/src/components/ScalarDropdown/ScalarDropdown.vue
packages/components/src/components/ScalarFloating/ScalarFloating.vue
packages/components/src/components/ScalarFloating/types.ts
packages/components/src/components/ScalarListbox/ScalarListbox.vue
packages/components/src/components/ScalarPopover/ScalarPopover.vue

this pr adds teleport capability to the scalar floating component in order to enhance side menu position in client app package:

feat: request sidebar dropdown position

---

.changeset/sharp-falcons-glow.md

fix: release process due to removed package

---

Makefile

With the new dev setup I don’t use the Makefile anymore. This PR removes it. ✨ Less files in root = good. :)

chore: remove Makefile

---

packages/client-app/src/components/SideNav/WorkspaceProfileIcon.vue
packages/client-app/src/components/Sidebar/SidebarButton.vue
packages/client-app/src/components/ViewLayout/ViewLayout.vue
packages/client-app/src/components/ViewLayout/ViewLayoutSection.vue
packages/client-app/src/views/Request/ResponseSection/ResponseSection.vue

this pr fixes a list of client app package ui issues:
- duplicated border
- wrong focus state
- missing overflow
- shrinking profile icon

fix: client app fixtures

---

packages/client-app/src/components/ActionModal/ActionModalFolder.vue
packages/client-app/src/components/ActionModal/ActionModalRequest.vue
packages/client-app/src/components/ActionModal/ActionModalVariant.vue

this pr fixes the client app action modal style for the api client modal:

fix: api client modal action modal fix

---

packages/client-app/src/views/Request/Request.vue

cherry pick of https://github.com/scalar/scalar/pull/2038
:)

feat: api client modal sidebar toggle

---

packages/client-app/src/components/ViewLayout/ViewLayout.vue
packages/client-app/src/components/ViewLayout/ViewLayoutContent.vue
packages/client-app/src/views/Collection/Collection.vue
packages/client-app/src/views/Cookies/Cookies.vue
packages/client-app/src/views/Environment/Environment.vue
packages/client-app/src/views/Request/Request.vue
packages/client-app/src/views/Servers/Servers.vue

this pr fixes client app views layout after moving address bar to the request view.

fix: client app view layout

---

packages/client-app/src/components/AddressBar/AddressBar.vue
packages/client-app/src/components/Sidebar/Sidebar.vue
packages/client-app/src/views/Request/Request.vue

R e s p o n s i v e
https://github.com/scalar/scalar/assets/6201407/6e8d4a0a-382e-4d0e-a57a-dc85f3889f2b
Responsive

fix: make sidebar responsive

---

packages/client-app/src/components/AddressBar/AddressBar.vue

fix: give address bar read only attributes

---

packages/client-app/package.json
packages/client-app/src/components/HttpMethod/HttpMethod.vue
packages/client-app/src/components/Search/SearchButton.vue
packages/client-app/src/components/Search/SearchModal.vue
packages/client-app/src/components/Search/index.ts
packages/client-app/src/views/Request/Request.vue
packages/components/src/components/ScalarModal/ScalarModal.vue

i think we can make another wrapper component for search, so essentially merging the two components with Fuse or adding a "useFuse" hook. but for now this is good enough!

feat: add search to api client

---

packages/client-app/src/components/DataTable/DataTableCheckbox.vue

fix: checkbox hover style

---

packages/client-app/src/components/AddressBar/AddressBar.vue
packages/client-app/src/store/workspace.ts

this pr displays past request history vs active request ones.

feat: client app requests history

---

packages/api-client-modal/src/api-client-modal.ts
packages/api-client-modal/src/types.ts
packages/api-reference/src/components/ApiClientModal.vue
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/client-app/src/components/ActionModal/ActionModalImport.vue
packages/client-app/src/store/workspace.ts
packages/oas-utils/package.json
packages/oas-utils/src/entities/workspace/collection/collection.ts
packages/oas-utils/src/entities/workspace/cookie/cookie.ts
packages/oas-utils/src/entities/workspace/environment/environment.ts
packages/oas-utils/src/entities/workspace/folder/folder.ts
packages/oas-utils/src/entities/workspace/security-schemes/index.ts
packages/oas-utils/src/entities/workspace/security-schemes/security-schemes.ts
packages/oas-utils/src/entities/workspace/server/server.ts
packages/oas-utils/src/entities/workspace/shared/utility.ts
packages/oas-utils/src/entities/workspace/spec/request-examples.ts
packages/oas-utils/src/entities/workspace/spec/requests.ts
packages/oas-utils/src/helpers/deepMerge.ts
packages/oas-utils/src/helpers/index.ts
packages/oas-utils/src/transforms/import-spec.ts

We should pretty much just remove zod at some point since we aren't really parsing (everythings optional)

feat(client-app): add defaults for all resources and deep merge

---

packages/oas-utils/src/entities/workspace/workspace.ts

this pr update the workspace default name.

feat: update workspace name

---

packages/api-client-modal/playground/main.ts
packages/api-client-modal/src/api-client-modal.ts
packages/client-app/src/store/workspace.ts

we can eventually make this a workspace config cause we will want to tweak it from the client app too :)

feat: add proxy to fetch spec

---

packages/client-app/src/views/Request/RequestSection/RequestSection.vue

we shouldnt show body unless its a put post or patch

feat: hide body unless post put patch

---

packages/client-app/src/views/Request/RequestSection/RequestBody.vue

we just were not listening to updates on codeinput

fix: add missing body to request send

---

packages/client-app/src/components/AddressBar/AddressBar.vue
packages/client-app/src/components/AddressBar/AddressBarHistory.vue

we need to do a lot of work for request history, but we can fast follow with this

chore: hide request history

---

packages/client-app/src/libs/sendRequest.ts
packages/client-app/src/views/Request/ResponseSection/ResponseBody.vue

fix: null response codes error out client app

---

packages/client-app/src/views/Request/RequestSection/RequestSection.vue

chore: only show body and path params tabs when available

---

.changeset/empty-terms-visit.md
.changeset/sharp-files-drive.md
examples/web/index.html

docs(changeset): feat: release all the packages

---

.changeset/fresh-dragons-rhyme.md
packages/api-client-modal/package.json

docs(changeset): chore: make api client modal public

---

.changeset/proud-jars-shop.md
packages/use-tooltip/package.json
pnpm-lock.yaml

fix: move tippy to a dependency

---

packages/client-app/src/views/Request/RequestSection/RequestAuth.vue
packages/client-app/src/views/Request/RequestSection/RequestBody.vue

this pr favors scalar listbox component over select in request view:

feat(client-app): request select

---

packages/client-app/src/views/Request/Request.vue

this pr enables request sidebar toggle on ctrl/cmd key + b.

feat(client-app): hotkey request sidebar toggle

---

packages/client-app/src/store/workspace.ts
packages/client-app/src/views/Request/RequestSection/RequestBody.vue

feat(client-app): add example payload to request body

---

packages/api-reference/src/helpers/parse.ts

Oops, I found some of my debug output in the `main` branch. 😳

chore: remove debug output

---

README.md
documentation/docusaurus.md

This PR adds a new integration guide, just for Docusaurus. :)

docs: detailed Docusaurus integration guide

---

packages/client-app/src/components/DataTable/DataTable.vue
packages/client-app/src/components/DataTable/DataTableCell.vue
packages/client-app/src/components/DataTable/DataTableHeader.vue
packages/client-app/src/components/DataTable/DataTableRow.vue
packages/client-app/src/components/DataTable/DataTableText.vue
packages/client-app/src/views/Request/RequestSection/RequestTable.vue
packages/client-app/src/views/Request/ResponseSection/ResponseHeaders.vue

Took @hwkr wonderful PR and fixed conflicts + new issues that arose to make it work with description hovers
https://github.com/scalar/scalar/pull/1993

feat: allow data grid text content to scroll

---

.github/workflows/deploy-preview-examples.yml
packages/components/src/components/ScalarIcon/ScalarIcon.vue
packages/components/src/components/ScalarIcon/icons/index.ts

this pr updates scalar icon component to introduce a loading placeholder.

feat(components): scalar icon loading placeholder

---

packages/client-app/src/views/Environment/Environment.vue

this pr enables is a first addition in order to be able to edit non default environment name in the client app:

feat(client-app): environment name editable

---

scripts/pack-packages.sh

This checks for package.json when packing, also you can add any packages to the disallow list

fix: pack packages script for testing

---

README.md
documentation/adonisjs.md
documentation/react.md

Hey, I’ve just tested the React integration and used the opportunity to write a guide on the matter. :)

docs: detailed integration guide for React

---

.changeset/soft-poems-enjoy.md
packages/docusaurus/src/ScalarDocusaurusCommonJS.tsx

fix: remove use effect from docusaurus

---

.changeset/yellow-years-walk.md
packages/api-client/src/components/ApiClient/Request/RequestAuthentication/SecuritySchemeScopes.vue

following #2135 merge, reset style wrapper could be now removed.

fix(api-client): reset style sunset

---

.changeset/wicked-waves-travel.md
packages/api-reference/src/components/ShowMoreButton.vue
packages/docusaurus/src/theme.css

**Problem**
docusaurus has a precedence error with the show more icon, we can fix it properly later and we also forgot to remove the layers

fix: remove layers in docusaurus and fix precedence issue

---

.changeset/nice-hotels-unite.md
packages/client-app/src/components/ScalarHotkey.vue
packages/client-app/src/components/TopNav/TopNavItem.vue
packages/use-tooltip/package.json
packages/use-tooltip/src/useTooltip.ts
pnpm-lock.yaml

this pr update use tooltip package usage and dependencies, and fixes the following:

feat(use-tooltip): update

---

packages/client-app/src/components/HttpMethod/HttpMethod.vue

this pr style http methods component when not editable in order to avoid clickable expectation.

fix(client-app): http methods editable style

---

.changeset/curvy-spoons-serve.md
packages/client-app/src/components/ScalarHotkey.vue
packages/client-app/src/components/TopNav/TopNavItem.vue
packages/components/package.json
packages/components/src/components/ScalarTooltip/ScalarTooltip.spec.ts
packages/components/src/components/ScalarTooltip/ScalarTooltip.stories.ts
packages/components/src/components/ScalarTooltip/ScalarTooltip.vue
packages/components/src/components/ScalarTooltip/index.ts
packages/components/src/index.ts
pnpm-lock.yaml

this pr adds ScalarTooltip component, in order to be used in the client app package. n.b this could replace the usage of `useTooltip` package which can be remove after merge.

feat(components): scalar tooltip

---

README.md

update readme to include custom header example

fix: add custom header to readme

---

README.md

fix: update readme to be more compact

---

.changeset/brave-pets-dance.md
.changeset/early-kiwis-sort.md
.changeset/wet-trains-collect.md

Added some changesets for #2183.

chore: add some missing changesets

---

packages/client-app/src/App.vue
packages/oas-utils/src/entities/workspace/security/security-schemes.ts

- fixed the spec!
- rolled back to galaxy!
will need to come up with a better default function as this won't work

feat: fix spotify spec and change back to galaxy

---

.changeset/shaggy-llamas-unite.md
packages/client-app/src/libs/sendRequest.test.ts
packages/client-app/src/libs/sendRequest.ts

**Problem**
No query params are sent to the proxy
This happens because we dont add them to the url
**Solution**
With this PR we add them to the URL

fix: query params not added to request url

---

.changeset/popular-oranges-cross.md
packages/client-app/src/components/DataTable/DataTable.vue
packages/client-app/src/components/DataTable/DataTableCell.vue
packages/client-app/src/components/DataTable/DataTableInput.vue
packages/client-app/src/views/Request/RequestSection/RequestAuth.vue
packages/client-app/src/views/Request/RequestSection/RequestAuthDataTableInput.vue
packages/client-app/src/views/Request/components/OAuth2.vue
packages/client-app/src/views/Request/components/ScopesDropdown.vue

this pr sets form markup in client app table input along label in order to comply with form / password form good practices.

fix(client-app): data table input

---

.eslintrc.cjs
examples/web/src/components/DevApiClientOptions.vue
examples/web/src/components/DevReferencesOptions.vue
examples/web/src/components/MonacoEditor.vue
packages/api-client/src/helpers/getRequestFromAuthentication.ts
packages/api-reference-react/src/ApiReferenceReact.tsx
packages/api-reference/src/features.ts
packages/api-reference/src/helpers/deepMerge.ts
packages/api-reference/src/types.ts
packages/client-app/src/components/AddressBar/AddressBarHistory.vue
packages/client-app/src/components/TopNav/TopNavItem.vue
packages/client-app/src/store/topNav.ts
packages/components/src/components/ScalarFloating/types.ts
packages/oas-utils/src/entities/workspace/cookie/cookie.ts
packages/oas-utils/src/entities/workspace/security/security-schemes.ts
packages/oas-utils/src/entities/workspace/spec/requests.ts
packages/oas-utils/src/helpers/object.ts
packages/oas-utils/src/helpers/prettyPrintJson.ts
packages/oas-utils/src/spec-getters/getExampleFromSchema.ts
packages/oas-utils/src/types.ts
packages/object-utils/src/nested/nested.ts

This PR fixes a few more linter errors and warnings and `pnpm lint` finally passes again. :)
This PR also applies the comment formatting from #2236.

chore: less linter warnings

---

packages/api-reference/src/components/SearchButton.vue
packages/api-reference/src/components/api-client-bus.ts

@antlio using that symbol helper we can type the bus

fix: type modalstate

---

.changeset/breezy-llamas-compare.md
packages/client-app/src/components/DataTable/DataTable.vue
packages/client-app/src/views/Request/RequestSection/RequestBody.vue
packages/client-app/src/views/Request/RequestSection/RequestTable.vue
packages/components/src/components/ScalarIcon/icons/UploadSimple.svg
packages/components/src/components/ScalarIcon/icons/icons.ts

simplify file upload a bit... we should go all out with fixing this up and making a great UX here over the next few weeks but just a start :)

fix: client app binary file and multipart ui

---

.changeset/green-drinks-jump.md
packages/api-reference/src/components/Content/BaseUrl/ServerVariableSelect.vue
packages/api-reference/src/components/Content/BaseUrl/ServerVariableTextbox.vue
packages/api-reference/src/components/Content/BaseUrl/ServerVariables.vue

Checkboxes!
https://github.com/scalar/scalar/assets/6374090/a14d9738-ee4a-437a-82d0-bf22ec6fac84
https://github.com/scalar/scalar/assets/6374090/110b85da-2837-497e-b8c5-aee21e10404d

fix: extract server variable inputs into components

---

packages/client-app/src/views/Request/components/OAuth2.vue
packages/client-app/src/views/Request/libs/oauth2.ts
packages/oas-utils/src/entities/workspace/security/security-schemes.ts

Added the code for it, but its completely untested as I don't have an api that still supports it. Just wrote it from [this](https://developer.okta.com/blog/2018/06/29/what-is-the-oauth2-password-grant)

feat: add oauth password flow

---

packages/client-app/src/components/AddressBar/AddressBar.vue
packages/client-app/src/components/AddressBar/AddressBarServer.vue

this pr extracts address bar server into a component and fixes ui in readonly.

feat(client-app): address bar server component

---

.changeset/khaki-foxes-smile.md
.changeset/perfect-clouds-tell.md
packages/client-app/src/store/workspace.ts
packages/client-app/src/views/Request/Request.vue
packages/oas-utils/src/entities/workspace/spec/requests.ts

this pr introduces a timestamp in request in order to sort request history item most recent first.

feat(client-app): address bar request history

---

.changeset/curvy-elephants-hide.md
packages/client-app/src/components/TopNav/TopNavItem.vue

this pr adds missing click emit in the client app top nav item component.

fix(client-app): top nav item

---

.changeset/healthy-wasps-kick.md
packages/client-app/src/views/Request/RequestSection/RequestAuth.vue
packages/client-app/src/views/Request/RequestSection/RequestTable.vue

this pr updates the basic auth request password placeholder.

fix(client-app): request basic auth placeholder

---

packages/client-app/src/libs/sendRequest.ts

We weren't sending, but now we are

feat: added auth to sendRequest

---

packages/client-app/src/components/AddressBar/AddressBarServer.vue
packages/themes/src/scrollbars.css

Not sure why this was added, maybe @cameronrohani or @hwkr have some insight

style: remove random firefox padding

---

.changeset/tough-papayas-begin.md
packages/client-app/src/components/AddressBar/AddressBar.vue

this pr updates the client app address bar component in order to enable path update in the request.

feat(client-app): address bar request

---

.changeset/real-files-own.md
packages/client-app/src/Modal/api-client-modal.ts
packages/client-app/src/libs/sendRequest.test.ts
packages/client-app/src/libs/sendRequest.ts
packages/client-app/src/views/Request/Request.vue
packages/oas-utils/src/entities/workspace/workspace.ts

fix: remove hardcoded proxy url for new client

---

.changeset/mighty-adults-unite.md
packages/client-app/src/components/AddressBar/AddressBarHistory.vue

before i wasnt using the right router, now i am :)

fix: request history routing for client app

---

.changeset/popular-parents-bow.md
packages/components/src/components/ScalarCodeBlock/ScalarCodeBlock.vue
packages/components/src/components/ScalarMarkdown/ScalarMarkdown.vue

this would break org, so now it is good!

fix: move css imports to style tags

---

.changeset/fast-bugs-wash.md
packages/nuxt/src/runtime/components/nuxt-theme.css

was deleted in https://github.com/scalar/scalar/commit/b981770b7e77436d6c120c8b22232dc2d84a099c#diff-4cb3c24249a356642c39e9f40d5f92555af69c24ca62073be2bd11409e60f5e4

fix: add back missing nuxt theme

---

documentation/openapi.md

This PR adds `x-codeSamples` to our documentation folder. :)

docs: add `x-codeSamples`

---

packages/api-client/src/components/DataTable/DataTableInput.vue
packages/api-client/src/store/workspace.ts
packages/api-client/src/views/Request/RequestSection/RequestTable.vue
packages/oas-utils/src/entities/workspace/spec/request-examples.ts

this pr adds required hint for input according to param required state which gets hidden on input focus:

feat(api-client): required param hint

---

packages/api-client/src/components/Search/SearchButton.vue
packages/api-client/src/views/Request/Request.vue

this pr moves the search modal component to the request vue in api client package, in order to make it displayable on hotkey even if the sidebar if hidden.

feat(api-client): search modal

---

.changeset/honest-jokes-notice.md
packages/api-client/src/views/Request/Request.vue

fix: requests being sent multiple times

---

.changeset/lovely-bikes-sin.md
packages/api-client/src/Modal/ApiClientModal.vue
packages/api-client/src/Modal/api-client-modal.ts
packages/api-reference/src/components/ApiClientModal.vue

**Problem**
99 problems and they're all headless ui
- infinite modals
- cant target the classes
- slow
- pain
This happens because headless ui w client app
**Solution**
no more headless ui

fix: move to pure css solution for client modal no more headless ui

---

.changeset/plenty-ducks-poke.md
.changeset/stupid-jokes-own.md
packages/api-client/src/components/DataTable/DataTableInput.vue
packages/api-client/src/views/Request/RequestSection/RequestPathParams.vue

this pr fixes the display of the required infos on required item + prevent the update of required path param key that can currently be updated and removed.

fix(api-client): required path params

---

packages/api-client/src/Modal/api-client-modal.ts
packages/api-client/src/store/workspace.ts

it was bugging me, this makes more sense

fix: remove some toRaw

---

.changeset/long-waves-join.md
.changeset/moody-items-invite.md
packages/api-reference/src/components/ApiClientModal.vue
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/Content/Lazy/Loading.vue
packages/api-reference/src/components/Util/Style.vue
packages/nuxt/package.json
packages/nuxt/src/module.ts
pnpm-lock.yaml

This should fix all of the current nuxt issues
closes #1453
closes #1889
closes #2141

fix(nuxt): module runtime error, css missing, unknown file extension

---

.changeset/unlucky-shrimps-grin.md
packages/api-client/src/views/Request/RequestSidebarItem.vue

One more try, hopefully got em all now 😄 
closes #1564

fix(#2351): global css import bug

---

.changeset/shaggy-needles-camp.md
packages/api-reference/src/components/ApiReferenceLayout.vue

fix: create payload for non-nuxt SSG

---

.changeset/loud-shrimps-own.md
packages/api-client/src/views/Cookies/Cookies.vue

this pr redirects to the page of the cookie on creation.

fix(api-client): cookies navigation

---

.changeset/quick-geckos-relax.md
packages/api-reference/src/features/BaseUrl/ServerUrlSelect.vue

fix: vertical align server url

---

packages/api-client/src/App.vue

we were not loading the fonts in the scalar app :despair:

fix: missing fonts in scalar app

---

.changeset/happy-starfishes-perform.md
packages/api-client/src/components/TopNav/TopNav.vue

this pr should fix the error displayed on tab navigation usage:

fix(api-client): top nav path error

---

.changeset/config.json

revert https://github.com/scalar/scalar/pull/2439

chore: revert ignore changesets for deprecated packages

---

.changeset/silly-news-jog.md
.changeset/soft-onions-care.md
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/components/DataTable/DataTableCell.vue
packages/api-client/src/views/Request/RequestSection/RequestTable.vue
packages/use-codemirror/src/hooks/useCodeMirror.ts

this pr is a first stone in order to set up variable injection, by adding the code input component in request table relying on code mirror.
let's make sure the different recent added use case are well supported here too (min max, required)

feat(api-client): request input

---

.changeset/calm-pandas-hunt.md
packages/api-reference/src/components/Card/CardContent.vue
packages/api-reference/src/components/Content/Operation/PathResponses/ExampleResponse.vue
packages/api-reference/src/components/Content/Operation/PathResponses/PathResponses.vue
packages/components/src/components/ScalarCodeBlock/ScalarCodeBlock.vue

this pr fixes the copy element position in scalar code block component while making it sticky for better reachability as seen below:
**before**
**after**

fix(components): copy button in `<ScalarCodeBlock />`

---

packages/api-client/src/App.vue

fix(api-client): add keepalive to request for snappier loads

---

.changeset/cyan-snakes-stare.md
packages/api-client/src/components/TopNav/TopNav.vue
packages/api-client/src/components/TopNav/TopNavItem.vue
packages/api-client/src/views/Request/RequestSection/RequestSection.vue
packages/api-client/src/views/Request/RequestSidebarItem.vue
packages/api-client/src/views/Request/ResponseSection/ResponseSection.vue
packages/components/src/components/ScalarButton/variants.ts
packages/components/src/components/ScalarIcon/icons/ExternalLink.svg

before:
after:
+ external link icon size

fix(api-client): sidebar offsets and icon issues

---

.changeset/few-crabs-love.md
packages/api-reference/src/components/Content/Operation/PathResponses/ExampleResponse.vue

this pr attempts to fix #2356 by updating all of items displays logic.

fix(api-reference): duplicate example responses, fix #2356

---

.changeset/ninety-months-punch.md
packages/api-client/src/components/DataTable/DataTableCell.vue

fix(client-app): scopes checkbox

---

.changeset/quick-socks-bathe.md
documentation/configuration.md
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/hooks/useSidebar.ts
packages/api-reference/src/types.ts

**Problem**
Currently if you wanted all your tags opened by default it couldn't happen, now it can 💅

feat: add defaultOpenAllTags configuration option

---

.changeset/strong-carpets-suffer.md
package.json
packages/api-client/src/Modal/api-client-modal.ts
packages/api-client/src/components/AddressBar/AddressBarServer.vue
packages/api-client/src/components/SideNav/SideNavLink.vue
packages/api-client/src/router.ts
packages/api-client/src/store/workspace.ts
packages/api-client/src/views/Request/RequestSidebarItem.vue
turbo.json

This only does the routing portion, but it seems to be working. Just need to see if I caught every case. Just poke around to different pages and see if anything breaks.

feat(doc-2095): handle multiple workspace part 1 - routing

---

README.md
documentation/integrations/html.md

This PR adds a dedicated file about the HTML API, our most popular integration. :)

docs(api-reference): write about the HTML API

---

.changeset/great-nails-live.md
packages/api-client/src/components/AddressBar/AddressBarHistory.vue
packages/components/src/components/ScalarIcon/icons/History.svg

https://github.com/user-attachments/assets/f109af61-fae7-41ee-b754-20cdd3b2dd7b

fix(components): polish history icon

---

.changeset/honest-news-yawn.md
packages/api-client/src/store/workspace.ts
packages/api-client/src/views/Request/RequestSection/RequestTable.vue

this pr https://github.com/scalar/scalar/pull/2469 unfortunately introduced a regression for the api client standalone app, now we just set enabled on import :)

fix: table checkbox for required params on import

---

packages/api-client/src/components/ContextBar.vue
packages/api-client/src/views/Request/Request.vue

dark mode backgrounds weren't layering properly, this fixes that
before:
after:

fix(api-client): dark mode background colors

---

.changeset/fresh-brooms-relax.md
packages/api-client/src/components/AddressBar/AddressBar.vue
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/components/CodeInput/codeDropdownWidget.ts
packages/api-client/src/components/CodeInput/codeVariableWidget.ts
packages/api-client/src/store/workspace.ts
packages/api-client/src/views/Environment/EnvironmentVariableDropdown.vue
packages/api-client/src/views/Request/Request.vue
packages/oas-utils/src/entities/workspace/spec/request-examples.ts

now we have servers as env vars, you can select and update the entire address bar!

feat: revamp address bar

---

.changeset/six-beers-smash.md
packages/api-client/src/components/AddressBar/AddressBar.vue
packages/api-client/src/components/CodeInput/CodeInput.vue

only apply flex to addressbar codemirror

fix(api-client): address bar code mirror 

---

examples/api-client/index.html

let's add the amazing fathom analytics to client.scalar.com

chore: add fathom to client.scalar.com

---

examples/api-client/index.html

Cool, with #2531 we tested the deployment and with this PR we’re actually adding the fathom id. :)

chore: update fathom id

---

.changeset/lovely-timers-invent.md
packages/api-client-app/src/renderer/src/App.vue
packages/api-client-app/src/renderer/src/components/ApiClient.vue
packages/api-client/src/components/SideNav/SideNav.vue
packages/api-client/src/components/Sidebar/SidebarButton.vue
packages/api-client/src/components/TopNav/TopNav.vue
packages/api-client/src/components/TopNav/TopNavItem.vue
packages/api-client/src/components/ViewLayout/ViewLayoutCollapse.vue
packages/api-client/src/views/Request/Request.vue
packages/api-client/src/views/Request/RequestSection/RequestSection.vue
packages/api-client/src/views/Request/RequestSection/RequestTableTooltip.vue
packages/api-client/src/views/Request/RequestSidebarItem.vue
packages/api-client/src/views/Request/ResponseSection/ResponseSection.vue
packages/api-client/src/views/Request/components/OAuth2.vue
packages/components/src/components/ScalarButton/variants.ts

(this screenshot doesn't show all the stroke changes but you get the idea)

fix(api-client): app spacing + stroke thicknesses

---

packages/api-client-app/electron-builder.yml
packages/api-client-app/src/main/index.ts

chore(api-client): change Scalar API Client to Scalar

---

.changeset/pink-timers-ring.md
packages/api-reference/src/components/Content/Operation/OperationAccordion.vue
packages/docusaurus/src/theme.css

fix(docusaurus): theme dark mode variables + button color + classic theme icon uniformity

---

packages/api-client/src/store/workspace.ts
packages/api-client/src/views/Cookies/Cookies.vue

we now have a default cookie added to a workspace : )

feat(api-client): add cookie empty state

---

packages/api-client-app/src/main/index.ts
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/components/CodeInput/codeVariableWidget.ts
packages/api-client/src/components/HttpMethod/HttpMethod.vue
packages/api-client/src/views/Environment/EnvironmentVariableDropdown.vue

@cameronrohani need to touch this up

feat(api-client): add colors to env vars and pills

---

.changeset/olive-candles-fetch.md
packages/api-client-app/src/renderer/index.html
packages/api-client/src/components/SideNav/WorkspaceProfileIcon.vue

fix(api-client): scalar app sidenav spacing

---

.changeset/wet-rules-work.md
packages/api-client/src/views/Request/Request.vue

fix(api-client): electrical wiring for gitbook

---

.changeset/grumpy-eggs-enjoy.md
packages/api-client/src/layouts/App/createApiClientApp.ts
packages/api-client/src/layouts/Modal/api-client-modal.ts

We forgot to update some links. :)

chore(api-client): update broken links in error messages

---

.changeset/tidy-tables-push.md
packages/api-client/src/views/Request/RequestSection/RequestAuth.vue

fix: add null check to scheme model

---

.changeset/calm-socks-argue.md
packages/api-client/src/components/Search/SearchModal.vue

**Problem**
Currently we search all requests
**Solution**
With this PR we search for the active workspace

fix: scope search to active workspace

---

.changeset/odd-suits-sing.md
packages/api-client/src/components/HttpMethod/HttpMethod.vue

fix(api-cleint): api client http method bg color remove

---

.changeset/tricky-humans-explain.md
examples/nextjs-api-reference/app/client/page.tsx
packages/api-client-react/package.json
packages/api-client-react/src/ApiClientModalProvider.tsx
packages/api-client-react/vite.config.ts
pnpm-lock.yaml

This fixes the previous issue by async loading the js code as well on the client side

fix: api-client-react async loading

---

.changeset/violet-pillows-fold.md
packages/api-client-react/package.json

chore: make api client react public

---

.changeset/fresh-spies-hear.md
packages/api-client/src/components/SubpageHeader.vue
packages/api-client/src/views/Cookies/Cookies.vue
packages/api-client/src/views/Environment/Environment.vue
packages/api-client/src/views/Servers/Servers.vue

subpages now don't shift the whole app up
https://github.com/user-attachments/assets/15ba49d8-335f-42b2-b34b-75b92673dd4b

fix(api-client): add header to client subpages

---

.changeset/healthy-donkeys-develop.md
packages/api-client-react/package.json
packages/api-client-react/src/ApiClientModalProvider.tsx
packages/api-client-react/vite.config.ts
pnpm-lock.yaml

Need 'use-client' at the top of the file for next.js

feat(api-client-react): keep use-client directive after build

---

.changeset/dull-masks-grab.md
packages/components/src/components/ScalarCombobox/ScalarCombobox.spec.ts
packages/components/src/components/ScalarCombobox/ScalarCombobox.stories.ts
packages/components/src/components/ScalarCombobox/ScalarCombobox.vue
packages/components/src/components/ScalarCombobox/ScalarComboboxOption.vue
packages/components/src/components/ScalarCombobox/ScalarComboboxOptions.vue
packages/components/src/components/ScalarCombobox/index.ts
packages/components/src/components/ScalarCombobox/types.ts
packages/components/src/components/ScalarPopover/ScalarPopover.vue
packages/themes/src/tailwind.ts

It's a combobox! We might want to add some more features in the future but I think this is pretty good for now.
https://github.com/user-attachments/assets/11617f4d-8ab4-4bab-b853-5d68eb51f426

feat(components): create combo box component

---

.changeset/popular-comics-perform.md
packages/api-client-app/src/main/index.ts
packages/api-client-app/src/renderer/index.html
packages/api-client/src/components/AddressBar/AddressBar.vue
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/components/DarkModeToggle/DarkModeIconToggle.vue
packages/api-client/src/components/SideNav/SideNav.vue
packages/api-client/src/components/SideNav/SideNavLink.vue
packages/api-client/src/components/SideNav/WorkspaceProfileIcon.vue
packages/api-client/src/components/SubpageHeader.vue
packages/api-client/src/constants.ts
packages/api-client/src/layouts/App/ApiClientApp.vue
packages/api-client/src/router.ts
packages/api-client/src/views/Request/Request.vue
packages/api-client/src/views/Request/RequestSection/RequestBody.vue
packages/api-client/src/views/Request/RequestSection/RequestTable.vue

fix(api-client): some api client app clean up (font sizes, spacing, etc)

---

.changeset/tricky-eyes-lick.md
packages/components/.storybook/preview.css
packages/components/src/components/ScalarDropdown/ScalarDropdownItem.vue
packages/components/src/components/ScalarListbox/ScalarListbox.vue
packages/components/src/components/ScalarModal/ScalarModal.vue
packages/components/src/components/ScalarSearchResults/ScalarSearchResultItem.vue
packages/components/src/components/ScalarTextField/ScalarTextField.vue

Seems like at some point this got bumped to 12px in a bunch of places. @cameronrohani can you make sure the dropdowns looks the way you want them in the client / app / references?

fix(components): set component font size to 13px

---

.changeset/poor-buses-give.md
packages/api-client/src/libs/create-client.ts

just a little type loosening for the people

fix(api-client-react): types

---

packages/api-client/src/views/Request/Request.vue

we dont need this right now : )

chore: remove hotkey for search modal in api client app

---

examples/api-client/src/main.ts
package.json
packages/api-client/playground/app/main.ts
packages/api-client/playground/modal/main.ts

we can now test with `pnpm dev:client`
@hanspagel would it be possible to just move this into the api-client package?

fix(api-client): client.scalar.com and add command for testing

---

.changeset/rotten-hornets-cheer.md
packages/api-client/src/views/Request/RequestSection/RequestSection.vue

We will now also show it in !readOnly mode

feat: only hide auth on read only mode

---

.changeset/giant-balloons-add.md
packages/api-client/src/views/Request/RequestSection/RequestAuth.vue
packages/components/src/components/ScalarCombobox/ScalarCombobox.vue
packages/components/src/components/ScalarCombobox/ScalarComboboxOptions.vue
packages/components/src/components/ScalarPopover/ScalarPopover.vue
packages/components/src/index.ts

Some small updates to the combobox styles based on how it would be used for request auth.

feat(components): update combobox styles

---

.changeset/eleven-wasps-chew.md
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/components/Form/Form.vue
packages/api-client/src/components/Search/SearchButton.vue
packages/api-client/src/components/Sidebar/SidebarList.vue
packages/api-client/src/components/Sidebar/SidebarListElement.vue
packages/api-client/src/layouts/App/ApiClientApp.vue
packages/api-client/src/views/Request/Request.vue

quick fix for when tw-bg-base isn't defined on cm-pill and some overall scalar app polish

fix(api-client): tw-bg-base gitbook bug and some app polish

---

.changeset/new-weeks-buy.md
packages/components/src/components/ScalarCombobox/ScalarCombobox.stories.ts
packages/components/src/components/ScalarCombobox/ScalarCombobox.vue
packages/components/src/components/ScalarCombobox/ScalarComboboxMultiselect.vue
packages/components/src/components/ScalarCombobox/ScalarComboboxOption.vue
packages/components/src/components/ScalarCombobox/ScalarComboboxOptions.vue
packages/components/src/components/ScalarCombobox/types.ts

✨ Groups ✨ 
https://github.com/user-attachments/assets/d19e351d-d693-4f5e-80ea-b3a5d8fa91fb

feat(components): add combo box groups

---

.changeset/wet-cows-invent.md
packages/api-client/src/components/CommandPalette/CommandPaletteRequest.vue

now create request:
- allows you to choose the collection to add to
- defaults to active collection
- defaults to active folder
- optional folder if no folders exist
so much better ✨ 
https://github.com/user-attachments/assets/3b6c5978-e24f-459d-9548-e49e74482dcd

feat: improve create request command

---

.changeset/eleven-doors-check.md
packages/api-client/src/components/CommandPalette/CommandPaletteCollection.vue
packages/api-client/src/components/CommandPalette/CommandPaletteExample.vue
packages/api-client/src/components/CommandPalette/CommandPaletteFolder.vue
packages/api-client/src/components/CommandPalette/CommandPaletteImport.vue
packages/api-client/src/components/CommandPalette/CommandPaletteRequest.vue
packages/api-client/src/components/CommandPalette/CommandPaletteWorkspace.vue
packages/api-client/src/components/CommandPalette/TheCommandPalette.vue
packages/api-client/src/components/CommandPalette/handleKeyDown.ts
packages/api-client/src/components/Search/SearchButton.vue
packages/api-client/src/components/Sidebar/SidebarButton.vue
packages/api-client/src/views/Request/Request.vue

properly capture keyboard events for the command palette and deal with address bar!

feat: make the command palette amazing

---

.changeset/cyan-peas-jam.md
packages/api-client/src/constants.ts

not ready yet : )so lets hide it

fix: hide servers page

---

.changeset/yellow-countries-pretend.md
packages/api-client/src/views/Request/RequestSidebarItemMenu.vue
packages/components/src/components/ScalarTextField/ScalarTextField.vue

now we have a delete modal and a rename modal 🕺 
also hides duplicate for now
https://github.com/user-attachments/assets/37329e38-af28-478d-b7bb-de40365e8bca

feat(api-client): rename requests and use delete modal

---

.changeset/tall-poets-give.md
packages/api-client-app/src/main/index.ts
packages/api-client-app/src/renderer/index.html
packages/api-client/src/components/SideNav/SideHelp.vue
packages/api-client/src/views/Request/ResponseSection/ResponseEmpty.vue

fix: add alpha copy and some app cleanup

---

.changeset/large-birds-rhyme.md
packages/api-client/src/components/CommandPalette/TheCommandPalette.vue

this enter was always happening :despair:
temp fix till we remove all whenevers

fix: add request on enter triggering in command palette

---

.changeset/curly-files-hope.md
packages/api-client/src/views/Environment/EnvironmentVariableDropdown.vue

this pr is an update proposal in order to fix the redirection to the environment page, when add variable is selected from the environment variable dropdown.

fix(client-app): dropdown add variable redirection 

---

.changeset/weak-mugs-thank.md
packages/api-client/src/components/DataTable/DataTableInput.vue
packages/api-client/src/components/DataTable/DataTableInputSelect.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth.vue
packages/api-client/src/views/Request/RequestSidebarItem.vue
packages/api-client/src/views/Request/RequestSidebarItemMenu.vue

fixes word break in sidebar
fixes ellipsis display: none -> display: flex causing word to wrap in sidebar
fixes sidebar icon stroke width
adds more contrast to multi auth

fix: word break in sidebar items and ellipsis positioning

---

.changeset/wicked-ads-dance.md
packages/api-client/src/views/Cookies/Cookies.vue

this pr adds a cookie removal method proposal for the client app, in order to allow cookies to be removed + fallback on the last existing one.

feat(client-app): cookie removal

---

.changeset/lovely-ways-report.md
.changeset/six-buttons-give.md
packages/api-client/src/components/Sidebar/Actions/DeleteSidebarListElement.vue
packages/api-client/src/components/Sidebar/Actions/SidebarListElementForm.vue
packages/api-client/src/components/Sidebar/SidebarListElement.vue
packages/api-client/src/components/Sidebar/SidebarListElementActions.vue
packages/api-client/src/components/SubpageHeader.vue
packages/api-client/src/views/Request/RequestSidebarItemMenu.vue
packages/components/src/components/ScalarModal/ScalarModal.vue

fix: modal size and layout

---

packages/oas-utils/src/helpers/httpStatusCodes.ts

**Problem**
I'm a teapot was missing 😭 
**Solution**
With this PR we will have the best status code ever

fix(oas-utils): I'm a teapot 🫖

---

scalar.config.json

Adds a scalar config to deploy docs

feat: deploy docs with Scalar

---

.changeset/blue-snails-add.md
packages/api-client-app/package.json
packages/api-client-app/src/renderer/index.html
packages/api-client-app/src/renderer/src/main.ts
pnpm-lock.yaml

This PR integrates fathom, disables the logging of page views and adds just a launch event.

feat(api-client-app): integrate fathom

---

documentation/guides/getting-started.md
scalar.config.json

feat: getting started scalar guides

---

.changeset/serious-trains-grin.md
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/views/Request/RequestSection/RequestTable.vue
packages/api-client/src/views/Request/RequestSection/RequestTableTooltip.vue

this pr fixes #2551 as seen below:

fix: info button go out of bound if the value is too long on test

---

.changeset/wild-dogs-grab.md
packages/api-client/src/components/AddressBar/AddressBar.vue
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/components/ContextBar.vue
packages/api-client/src/components/DarkModeToggle/DarkModeIconToggle.vue
packages/api-client/src/components/HttpMethod/HttpMethod.vue
packages/api-client/src/components/SideNav/SideHelp.vue
packages/api-client/src/components/SideNav/SideNavLink.vue
packages/api-client/src/components/Sidebar/Sidebar.vue
packages/api-client/src/components/Sidebar/SidebarButton.vue
packages/api-client/src/components/Sidebar/SidebarToggle.vue
packages/api-client/src/components/SubpageHeader.vue
packages/api-client/src/components/TopNav/TopNav.vue
packages/api-client/src/components/TopNav/TopNavItem.vue
packages/api-client/src/components/ViewLayout/ViewLayout.vue
packages/api-client/src/components/ViewLayout/ViewLayoutContent.vue
packages/api-client/src/components/ViewLayout/ViewLayoutSection.vue
packages/api-client/src/layouts/App/ApiClientApp.vue
packages/api-client/src/layouts/Modal/ApiClientModal.vue
packages/api-client/src/views/Request/Request.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth.vue
packages/api-client/src/views/Request/RequestSidebarItem.vue
packages/api-client/src/views/Request/components/WorkspaceDropdown.vue
packages/themes/src/variables.css

fix(api-client): app style updates 

---

.changeset/red-grapes-train.md
packages/api-client/src/components/AddressBar/AddressBar.vue
packages/api-client/src/components/AddressBar/AddressBarHistory.vue
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/components/ContextBar.vue
packages/api-client/src/components/HttpMethod/HttpMethod.vue
packages/api-client/src/components/SubpageHeader.vue
packages/api-reference/src/components/Content/Operation/EndpointPath.vue

Just need to improve styles of bg-grey on top of address bar which I will do later today :)

fix: improve styles of address bar post UI polish

---

packages/api-reference/src/components/Content/ClientLibraries/ClientSelector.vue
packages/api-reference/src/features/BaseUrl/ServerUrlSelect.vue

we need to hide the scrollbar on base-url

fix: base url random scroll bar

---

.changeset/rotten-needles-wash.md
packages/use-toasts/src/components/ScalarToasts.vue

https://github.com/user-attachments/assets/709f46f2-35eb-4f4a-9029-571b76228289
https://github.com/user-attachments/assets/739b6f29-8673-4017-9799-e006e3dfd133

fix(use-toasts): set parent class for scalar toasts

---

.changeset/bright-clocks-happen.md
packages/api-client/src/views/Request/Request.vue
packages/api-client/src/views/Request/components/WorkspaceDropdown.vue

Automatically shows / hides the sidebar when you resize the window from big to small. Also fixes a border alignment issue.
https://github.com/user-attachments/assets/c5950b9b-b3c8-436a-b666-16eec1f1caf3

fix(api-client): improve api client responsiveness

---

.changeset/famous-rocks-compare.md
packages/api-reference/src/components/Content/Operation/Parameters.vue
packages/api-reference/src/components/Content/Operation/RequestBody.vue
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue

https://github.com/user-attachments/assets/9054052e-97be-40a1-8f5e-ef2b7256a503

style(api-references): cleanup operation font sizes and alignment

---

.changeset/many-countries-walk.md
packages/api-client/src/components/Sidebar/Sidebar.vue
packages/api-client/src/views/Request/Request.vue

this pr is a proposals to support sidebar dragging while adding some transition sugar:
[Uploading scalar-sidebar.mp4…](https://github.com/scalar/scalar/assets/14966155/feae7a15-e9b9-4836-80de-870afa235d07)

feat(api-client): request sidebar dragging

---

.changeset/nice-bikes-type.md
packages/api-client-app/src/renderer/src/main.ts
packages/api-client/src/index.ts
packages/api-client/src/router.ts

This took me way to long to debug but fixes #2791 and also the issue with sidebar items not highlighting when active.
@hanspagel I tested the app and everything seemed to be working fine still but if you want to confirm that wouldn't hurt 🙏

fix(api-client): move web hash router to a factory function

---

.changeset/lazy-trains-own.md
packages/api-client/src/components/Sidebar/Sidebar.vue
packages/api-client/src/views/Request/components/WorkspaceDropdown.vue
packages/api-reference/src/components/Card/Card.vue
packages/api-reference/src/components/Card/CardContent.vue
packages/api-reference/src/components/Content/Authentication/Authentication.vue
packages/api-reference/src/components/Content/ClientLibraries/ClientLibraries.vue
packages/api-reference/src/components/Content/ClientLibraries/ClientSelector.vue
packages/api-reference/src/components/Content/Content.vue
packages/api-reference/src/components/Content/Introduction/Description.vue
packages/api-reference/src/components/Content/Operation/PathResponses/PathResponses.vue
packages/api-reference/src/features/BaseUrl/ServerForm.vue
packages/api-reference/src/features/BaseUrl/ServerUrl.vue
packages/api-reference/src/legacy/components/CardForm.vue
packages/api-reference/src/legacy/components/CardFormTextInput.vue
packages/api-reference/src/legacy/components/SecuritySchemeScopes.vue
packages/api-reference/src/legacy/components/SecuritySchemeSelector.vue
packages/code-highlight/src/css/markdown.css
packages/docusaurus/src/theme.css

fix: markdown margins and cleanup stuff in intro card

---

.changeset/thick-lemons-check.md
packages/components/src/components/ScalarIcon/icons/index.ts
packages/nuxt/playground/nuxt.config.ts
packages/nuxt/src/module.ts

This fixes the CJS errors in the nuxt module. This does not fix our other issues, that will come soon!
Alright the other issue had to do with icons. so I just went back to regular loading for now! @hwkr @antlio open to improving icon loading but we need to make sure it works in nuxt!

fix(nuxt): cjs errors

---

.changeset/strong-lobsters-exercise.md
packages/api-client-app/src/renderer/index.html

fix: scalar app fathom analytics

---

.changeset/twenty-frogs-leave.md
packages/galaxy/src/specifications/3.1.yaml

should be `'$ref'` instead of `ref` : )

fix: improper usage of ref in token response

---

.changeset/gentle-masks-exist.md
packages/api-reference/src/components/Content/Operation/ContentTypeSelect.vue
packages/api-reference/src/components/Content/Operation/EndpointDetails.vue
packages/api-reference/src/components/Content/Operation/ParameterItem.vue
packages/api-reference/src/components/Content/Operation/Parameters.vue
packages/api-reference/src/hooks/useResponses.ts
packages/oas-utils/src/types.ts

feat: add response schema

---

.changeset/young-ladybugs-beg.md
packages/api-client/src/components/ScalarHotkey.vue
packages/api-client/src/components/TopNav/TopNav.vue
packages/api-client/src/layouts/App/ApiClientApp.vue
packages/api-client/src/libs/event-busses/hot-keys-bus.ts
packages/oas-utils/src/entities/workspace/consts/hot-keys.ts

this pr adds the tab navigation hotkeys + fix style on hotkey tooltips:
https://github.com/user-attachments/assets/1d0322a7-a8d7-4848-beed-c1ba4c8dd3fc

feat(api-client): tab navigation hotkeys

---

.changeset/polite-windows-burn.md
package.json
packages/components/src/components/ScalarModal/ScalarModal.stories.ts
packages/components/src/components/ScalarModal/ScalarModal.vue
packages/components/tailwind.config.ts

Fixing up the modal for use in the Dashboard ✨

fix(components): fix modal layout

---

.changeset/tame-flowers-serve.md
packages/api-client/src/components/ScalarHotkey.vue
packages/api-client/src/components/TopNav/TopNav.vue
packages/api-client/src/components/TopNav/TopNavItem.vue
packages/components/src/components/ScalarContextMenu/ScalarContextMenu.vue
packages/components/src/components/ScalarIcon/icons/AddTab.svg
packages/components/src/components/ScalarIcon/icons/CloseTab.svg
packages/components/src/components/ScalarIcon/icons/CloseTabs.svg
packages/components/src/components/ScalarIcon/icons/icons.ts

this pr adds context menu on top nav as seen below:
https://github.com/user-attachments/assets/ad4c62fb-a2b8-4255-a7e9-124af56915f4

feat(api-client): top nav context menu

---

packages/oas-utils/src/spec-extentions/x-scalar-folder.yaml

Cleans up the scalar folder extension definition

feat: Update x-scalar-folder definition

---

package.json

Added new `pnpm dev:nuxt` command to make it easier for the community to contribute

feat(nuxt): added new dev-nuxt command

---

.changeset/purple-tables-boil.md
packages/api-client/src/components/TopNav/TopNav.vue
packages/api-client/src/layouts/App/ApiClientApp.vue
packages/api-client/src/views/Request/Request.vue
packages/api-client/src/views/Request/RequestSidebarItem.vue

this pr adds topnav opening within the app on meta + click request link as seen below:
https://github.com/user-attachments/assets/169a371d-59b7-4bb3-b68c-e4c11d45a0a0

feat(api-client): meta click request to topnav

---

.changeset/thirty-mails-tell.md
packages/api-client/src/libs/event-busses/hot-keys-bus.ts
packages/api-client/src/views/Request/RequestSidebarItem.vue

this pr use export and use getModifiers function to be able to rely on the meta key no matter the OS.

fix(api-client): request sidebar item new tab event

---

.changeset/warm-keys-drive.md
packages/themes/src/utilities/hasObtrusiveScrollbars.ts

fix(themes): remove obtrusive scrollbar test after testing

---

.changeset/rude-actors-sell.md
.changeset/tiny-rocks-ring.md
packages/api-client/src/components/TopNav/TopNav.vue
packages/components/src/components/ScalarDropdown/ScalarDropdownItem.vue

this pr adds context menu also on the unique topnav:

feat(api-client): main topnav context menu

---

.changeset/eight-beds-peel.md
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/components/CodeInput/codeVariableWidget.ts
packages/api-client/src/views/Environment/EnvironmentVariableDropdown.vue
packages/api-client/src/views/Request/RequestSection/RequestTable.vue

this pr fixes the line addition when removing variable in the api client + some style (pill centering) as seen below:
https://github.com/user-attachments/assets/f610b57a-0267-44dc-a34d-60405149d0ac

fix(api-client): variable removal breaking line

---

.changeset/two-goats-jam.md
packages/api-client-app/src/main/index.ts

This PR adds a menu entry to the app to manually check for updates.
If a new version is found, it’ll show the same popup as if the update is auto-detected.

feat(api-client-app): check for updates

---

packages/snippetz/README.md

Oops, the README got lost. Here it is again. :)

docs(snippetz): README

---

packages/api-client/src/components/HttpMethod/HttpMethod.vue
packages/api-client/src/store/store.ts
packages/api-client/src/views/Request/RequestSection/RequestSection.vue
packages/api-client/src/views/Request/RequestSidebar.vue
packages/oas-utils/package.json
packages/oas-utils/src/entities/cookie/cookie.ts
packages/oas-utils/src/entities/environment/environment.ts
packages/oas-utils/src/entities/spec/collection.ts
packages/oas-utils/src/entities/spec/request-examples.ts
packages/oas-utils/src/entities/spec/requests.ts
packages/oas-utils/src/entities/spec/security.ts
packages/oas-utils/src/entities/spec/spec-objects.ts
packages/oas-utils/src/entities/workspace/workspace.ts
packages/oas-utils/src/transforms/import-spec.test.ts
pnpm-lock.yaml

- Request example default
- default uids
- cyclic dependency

fix(api-client): a few things

---

packages/api-client/src/store/workspace.ts
packages/api-client/src/views/Request/RequestSection/RequestSection.vue
packages/api-client/src/views/Request/RequestSidebar.vue
packages/api-client/src/views/Request/RequestSidebarItem.vue
packages/oas-utils/src/entities/spec/collection.ts
packages/oas-utils/src/entities/spec/request-examples.ts
packages/oas-utils/src/entities/spec/requests.ts
packages/oas-utils/src/entities/spec/spec-objects.ts
packages/oas-utils/src/transforms/import-spec.ts

Gets the sidebar going, lets go!

fix: sidebar

---

.changeset/funny-turkeys-arrive.md
packages/api-client/package.json
packages/api-client/src/libs/normalizeHeaders.test.ts
packages/api-client/src/libs/normalizeHeaders.ts
packages/api-client/src/libs/sendRequest.test.ts
packages/api-client/src/libs/sendRequest.ts
packages/api-client/src/views/Request/Request.vue
packages/api-client/src/views/Request/ResponseSection/ResponseBody.vue
packages/api-client/src/views/Request/ResponseSection/ResponseSection.vue
packages/api-reference/package.json
packages/api-reference/src/helpers/getHarRequest.ts
packages/api-reference/src/legacy/helpers/normalizeHeaders.test.ts
packages/api-reference/src/legacy/helpers/normalizeHeaders.ts
packages/oas-utils/package.json
packages/oas-utils/src/entities/workspace/spec/requests.ts
packages/void-server/src/utils/getBody.ts
pnpm-lock.yaml

closes #2895 
Went for the easiest way to remove axios, serialized headers and what not. Seems to be working, needs heavy testing! Also added bit of type safety and removed what I hope was unneeded code 🦑, and I _think_ cookies should work now? need to test

feat(api-client): remove axios

---

documentation/guides/markdown-sync.md
scalar.config.json

This PR adds a basic Markdown sync guide. Just the foundation, we’ll add to it soon. :)

docs: Markdown sync guide

---

oss-pledge.json

feat: add scalar oss pledge

---

packages/api-client/src/components/AddressBar/AddressBar.vue
packages/api-client/src/components/AddressBar/AddressBarServer.vue
packages/api-client/src/components/AddressBar/AddressBarServerItem.vue
packages/api-client/src/components/CommandPalette/CommandPaletteRequest.vue
packages/api-client/src/components/CommandPalette/CommandPaletteServer.vue
packages/api-client/src/components/CommandPalette/TheCommandPalette.vue
packages/api-client/src/components/HttpMethod/helpers.ts
packages/api-client/src/components/HttpMethod/index.ts
packages/api-client/src/components/Sidebar/Actions/DeleteSidebarListElement.vue
packages/api-client/src/components/Sidebar/Actions/SidebarListElementForm.vue
packages/api-client/src/store/collections.ts
packages/api-client/src/store/request-example.ts
packages/api-client/src/store/requests.ts
packages/api-client/src/store/servers.ts
packages/api-client/src/store/store.ts
packages/api-client/src/store/workspace.ts
packages/api-client/src/views/Request/RequestSidebarItem.vue
packages/oas-utils/src/entities/spec/collection.ts
packages/oas-utils/src/entities/spec/requests.ts
packages/oas-utils/src/entities/spec/server.ts

Server selection working for both request server and servers, adding servers only working for collection rn
also did some work in the request command pallette, its _almost_ there

feat: add server selection

---

packages/api-client/src/components/CommandPalette/CommandPaletteCollection.vue
packages/api-client/src/components/CommandPalette/CommandPaletteExample.vue
packages/api-client/src/components/CommandPalette/CommandPaletteRequest.vue
packages/api-client/src/components/CommandPalette/CommandPaletteTag.vue
packages/api-client/src/components/CommandPalette/TheCommandPalette.vue
packages/api-client/src/store/collections.ts
packages/api-client/src/store/store.ts
packages/api-client/src/store/tags.ts
packages/api-client/src/views/Request/RequestSidebarItem.vue
packages/oas-utils/src/entities/spec/spec-objects.ts
packages/object-utils/src/mutator-record/handlers.ts

- collection
- tags
Just found that we are using the raw mutators in the extended data factories. We will need to switch to use the side effect ones to have proper chaining. Will do this after all command pallettes are fixed

fix: a few command pallets

---

packages/api-client/src/store/store.ts

Fixed the routing but realized we are missing examples

fix: request example routing

---

packages/api-client/src/views/Request/RequestSection/RequestBody.vue
packages/api-client/src/views/Request/RequestSection/RequestSection.vue

Fixed request headers and body, it no longer errors. 
*I did yank out the content type stuff because IMO if the user wants it, they can add it explicitly.*
We can add it back in later if needed! Still not 100% happy with this component but we'll get there!

fix: request headers and body

---

packages/components/README.md

fix: themes documentation

---

documentation/guides/docs/getting-started.md
documentation/guides/introduction.md

Haha, the links changed. So let’s fix the links again. 😅

fix: broken links

---

packages/api-client/src/components/AddressBar/AddressBarHistory.vue
packages/api-client/src/libs/errors.ts
packages/api-client/src/libs/index.ts
packages/api-client/src/libs/normalize-headers.test.ts
packages/api-client/src/libs/normalize-headers.ts
packages/api-client/src/libs/send-request.test.ts
packages/api-client/src/libs/send-request.ts
packages/api-client/src/libs/string-template.test.ts
packages/api-client/src/libs/string-template.ts
packages/api-client/src/views/Request/Request.vue
packages/api-client/src/views/Request/RequestSection/RequestBody.vue
packages/api-client/src/views/Request/RequestSection/RequestSection.vue
packages/api-client/src/views/Request/ResponseSection/ResponseSection.vue
packages/api-reference/src/legacy/helpers/normalizeRequestMethod.ts
packages/oas-utils/src/entities/spec/parameters.ts
packages/oas-utils/src/entities/spec/request-examples.ts
packages/oas-utils/src/entities/spec/requests.ts
packages/oas-utils/src/helpers/httpMethods.ts
packages/oas-utils/src/helpers/redirectToProxy.ts

WIP
**Tasks**
Then review, approve and merge :)

chore(api-client): remove axios again

---

packages/api-client/src/errors.ts
packages/api-client/src/libs/errors.ts
packages/api-client/src/libs/send-request.ts
packages/api-client/src/views/Request/Request.vue

Also centralized error messages and added a prettyError function to convert javascript error messages to human readable ones 👍🏾

feat: added error handling for empty + invalid urls

---

packages/api-client/src/views/Request/RequestSection/RequestAuth/OAuth2.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuth.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestExampleAuth.vue
packages/api-client/src/views/Request/libs/oauth2.ts
packages/oas-utils/src/entities/spec/security.ts
packages/oas-utils/src/helpers/schema-model.ts
packages/oas-utils/src/transforms/import-spec.ts

Untested but better than before

fix: oauth2

---

.changeset/angry-cats-itch.md
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/oas-utils/package.json
packages/use-codemirror/package.json
packages/use-codemirror/src/hooks/useCodeMirror.ts
pnpm-lock.yaml

this pr adds fold capability to api client code input as seen below:

feat(api-client): code input foldable

---

packages/api-client/src/components/ContextBar.vue
packages/api-client/src/components/ViewLayout/ViewLayoutCollapse.vue
packages/api-client/src/components/ViewLayout/ViewLayoutSection.vue
packages/api-client/src/views/Request/RequestSection/RequestSection.vue
packages/api-client/src/views/Request/ResponseSection/ResponseSection.vue

this pr cherry picks context bar position and style updated from #3095 as seen below:

feat(api-client): context bar

---

.changeset/tasty-adults-press.md
packages/api-client/src/components/CommandPalette/CommandPaletteRequest.vue
packages/api-client/src/components/CommandPalette/TheCommandPalette.vue
packages/api-client/src/libs/event-busses/command-palette-bus.ts
packages/api-client/src/views/Request/RequestSidebarItem.vue
packages/api-client/src/views/Request/RequestSidebarItemMenu.vue

this pr adds a create request button in empty request sidebar collection/folder to display the request creation command modal: 
https://github.com/user-attachments/assets/3b3e7e0f-5424-4bdc-844e-22a4ca33961f

feat(api-client): add sidebar request creation button

---

packages/api-client/src/libs/event-busses/hot-keys-bus.ts
packages/api-client/src/views/Request/ResponseSection/ResponseEmpty.vue
packages/oas-utils/src/entities/hotkeys/hotkeys.ts

this pr sets the new request action from the api client empty response as seen below:
https://github.com/user-attachments/assets/730c0dea-d3c1-460b-b60a-f8f5051d2b94

feat(api-client): empty response new request

---

.changeset/cold-crabs-walk.md
packages/api-client/src/libs/send-request.test.ts
packages/api-client/src/libs/send-request.ts

fix: path only urls

---

packages/api-client/src/components/AddressBar/AddressBarServer.vue
packages/api-client/src/layouts/Modal/create-api-client-modal.ts
packages/api-client/src/libs/create-client.ts
packages/api-client/src/store/import-spec.ts
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuth.vue
packages/api-reference/src/components/ApiClientModal.vue
packages/oas-utils/src/transforms/import-spec.ts

Workspaces were not being created properly so I'm not even sure how the modal was opening. This pr fixes that as well as:
- auth error on client modal open
- update the currently selected server from references
- allow server selection on the client

fix: server selection, client auth, and workspace creation

---

.changeset/nasty-worms-know.md
packages/api-client/src/libs/create-client.ts
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestExampleAuth.vue
packages/api-reference/src/components/ApiClientModal.vue
packages/api-reference/src/components/api-client-bus.ts
packages/api-reference/src/legacy/components/SecurityScheme.vue
packages/oas-utils/src/entities/spec/security.ts
packages/oas-utils/src/transforms/import-spec.ts

This performs 1 way sync from references to the client. Did not do oauth2 yet

fix: sync auth from references to client

---

.changeset/smooth-turtles-taste.md
packages/api-client/src/store/cookies.ts
packages/api-client/src/store/environment.ts
packages/api-client/src/views/Environment/Environment.vue

fix: environment and cookie mutators

---

.changeset/ten-balloons-glow.md
packages/api-client/src/components/CommandPalette/CommandActionInput.vue
packages/api-client/src/components/CommandPalette/CommandPaletteServer.vue
packages/api-client/src/components/CommandPalette/CommandPaletteWorkspace.vue
packages/api-client/src/components/CommandPalette/TheCommandPalette.vue

this pr fixes:
- consistency issue among command palette actions (server)
- update styles
- fix input focus
- fix nanoid function typo

fix(api-client): command palette fixtures

---

.changeset/selfish-coins-ring.md
packages/api-client/src/components/AddressBar/AddressBar.vue
packages/api-client/src/components/Sidebar/Actions/DeleteSidebarListElement.vue
packages/api-client/src/components/Sidebar/Actions/SidebarListElementForm.vue
packages/api-client/src/components/Sidebar/Sidebar.vue
packages/api-client/src/components/TopNav/TopNav.vue
packages/api-client/src/components/TopNav/TopNavItem.vue
packages/api-client/src/views/Request/Request.vue
packages/api-client/src/views/Request/RequestSidebar.vue
packages/api-client/src/views/Request/RequestSidebarItem.vue
packages/api-client/src/views/Request/components/WorkspaceDropdown.vue

this pr fixes:
- sidebar width issue with long request name
- address bar font size consistency
- sidebar search background fade
- delete modal request name length

fix(api-client): sidebar fixtures

---

README.md

fix: update readme to include client + update reference images and h1

---

.changeset/three-pugs-worry.md
packages/api-client-app/src/renderer/src/main.ts

this pr is a first attempt to get real time analytics within the api client app.

feat(api-client-app): sets load analytics spa to auto

---

documentation/integrations/fastify.md

**Problem**
offical -> official

chore: update fastify.md

---

.changeset/stale-points-hear.md

docs(changeset): fix(api-client): add back content header

---

.changeset/famous-jokes-drop.md
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuth.vue

This corrects the security requirement auth lookup!

fix(api-client): request security requirement auth

---

.changeset/giant-dodos-buy.md
packages/oas-utils/src/entities/spec/request-examples.ts

fixes https://github.com/scalar/scalar/issues/3182 and https://github.com/scalar/scalar/issues/3165

fix: null example bug

---

README.md

fix: update readme design

---

.changeset/olive-drinks-join.md
README.md
packages/api-client/src/layouts/Modal/ApiClientModal.vue
packages/components/src/components/ScalarModal/ScalarModal.vue
packages/themes/src/tailwind.ts

fix: modal background in dark mode

---

examples/cdn-api-reference/package.json
examples/esm-api-reference/package.json
examples/proxy-server/package.json
packages/build-tooling/src/entry.ts
scripts/bootstrap-package/bootstrap-package.ts
scripts/bootstrap-package/package.json

The bootstrap script failed for me, so I took the opportunity and updated it a little bit:
* Fixed errors
* Improved the output
* Updated the wording

fix: bootstrap script doesn’t run

---

.changeset/calm-cameras-happen.md
packages/api-client/src/components/CommandPalette/CommandPaletteExample.vue
packages/api-client/src/views/Request/RequestSidebarItem.vue
packages/api-client/src/views/Request/RequestSidebarItemMenu.vue

this pr fixes:
- closes delete sidebar modal on action
- adds delete example warning message
- sets example parent request

fix(api-client): example sidebar modal

---

.changeset/quick-lions-bake.md
packages/api-client-app/src/renderer/index.html

**Problem**
Fathom isnt working properly
**Solution**
With this PR it might fix it

fix: fathom script

---

packages/scalar.aspnetcore/playground/Scalar.AspNetCore.Playground/Program.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Enums/TagSorter.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarOptionsExtensions.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Mapper/ScalarOptionsMapper.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Options/ScalarOptions.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Options/ScalarServer.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/ScalarConfiguration.cs
packages/scalar.aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarEndpointTests.cs
packages/scalar.aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarOptionsExtensionsTests.cs

This PR adds two new configuration properties (`Servers` and `TagSorter`) to the .NET package. 
Closes #3226

feat(Scalar.AspNetCore): add servers and tagSorter 

---

.changeset/dry-onions-decide.md
.changeset/fresh-zoos-flash.md
packages/themes/package.json
packages/themes/src/index.ts
packages/themes/tsconfig.json
packages/types/package.json
packages/types/src/legacy/reference-config.ts
pnpm-lock.yaml

feat: remove `@scalar/themes` from the dependencies of `@scalar/types`

---

.changeset/three-poems-matter.md
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuth.vue

Not 100% sure why but teleporting a div onto the body causes a page scroll.
https://github.com/user-attachments/assets/a05c58dd-d931-48da-bd7d-3e478d58002a

fix(api-client): don't teleport auth combobox to body

---

.changeset/silver-tips-sing.md
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuth.vue

fixes https://github.com/scalar/scalar/issues/3292

fix: remove stray hello world html

---

packages/api-client/src/views/Components/Schemas/Schemas.vue

Doesn’t look like we’re using this.
SCHEMA!!

chore(api-client): remove unused component

---

.changeset/clean-bananas-fold.md
packages/components/src/components/ScalarModal/ScalarModal.vue

this pr updates scalar modal animation to make it more consistent with the command palette in the client.
**before**
https://github.com/user-attachments/assets/c187c343-0cfa-481a-aefd-3d17ecb82da8
**after**
https://github.com/user-attachments/assets/3688cf77-20f4-4933-980d-de83333db8c3

style(components): updates modal animation

---

.changeset/mean-penguins-call.md
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.spec.ts
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue

fix(api-reference): render falsely default values

---

.changeset/friendly-peaches-obey.md
packages/themes/src/presets/bluePlanet.css
packages/themes/src/presets/deepSpace.css
packages/themes/src/presets/kepler.css
packages/themes/src/presets/mars.css
packages/themes/src/presets/saturn.css
packages/themes/src/variables.css

big friday energy inspired by @JohnPhamous amazing [tweet](https://x.com/JohnPhamous/status/1770861726604419369). gave a first shot at our custom theme selection but feel free to play with it, as seen below:
<details>
<summary>alternate</summary>
</details>
<details>
<summary>default</summary>
</details>
<details>
<summary>moon</summary>
</details>
<details>
<summary>purple</summary>
</details>
<details>
<summary>solarized</summary>
</details>
<details>
<summary>blue planet</summary>
</details>
<details>
<summary>deep space</summary>
</details>
<details>
<summary>saturn</summary>
</details>
<details>
<summary>kepler 11e</summary>
</details>
<details>
<summary>mars</summary>
</details>

style(themes): new selection colors

---

packages/scalar.aspnetcore/README.md

This PR updates the README to add badges, slightly update the description, make it look more like our other READMEs, add a mention of @xC0dex, add a development section and add a community and license section.

docs(Scalar.AspNetCore): update the README

---

.changeset/khaki-sloths-push.md
.github/workflows/ci.yml
packages/scalar.aspnetcore/package.json

This PR adds a basic workflow for building, testing and publishing the `Scalar.AspNetCore` package.

build(Scalar.AspNetCore): add ASP.NET Core build and test workflow

---

packages/scalar.aspnetcore/package.json

I've just used `pnpm format:packages`.

chore(Scalar.AspNetCore): auto format package.json

---

.changeset/great-windows-collect.md
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Enums/OperationSorter.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarOptionsExtensions.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Mapper/ScalarOptionsMapper.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Options/ScalarOptions.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/ScalarConfiguration.cs
packages/scalar.aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarOptionsExtensionsTests.cs
packages/scalar.aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarOptionsMapperTests.cs

I noticed that there was a new configuration `operationsSorter` added recently. I added this config to the `Scalar.AspNetCore` package!

feat(Scalar.AspNetCore): add OperationSorter configuration

---

packages/snippetz/README.md

Add the deployed snippetz playground to the readme.

docs(snippetz): Add playground link to README

---

.changeset/slow-beers-draw.md
packages/api-client/package.json
packages/build-tooling/package.json
packages/build-tooling/src/entry.ts
packages/cli/package.json
packages/code-highlight/package.json
packages/config/package.json
packages/hono-api-reference/package.json
packages/mock-server/package.json
packages/nextjs-openapi/package.json
packages/oas-utils/package.json
packages/object-utils/package.json
packages/openapi-types/package.json
packages/snippetz/package.json
packages/ts-to-openapi/package.json
packages/types/package.json
packages/void-server/package.json

Adds fallback exports for require syntax
closes #2994

chore: add `default` to package.json exports fields

---

.changeset/lazy-cooks-applaud.md
.github/workflows/ci.yml

Stackblitz seems to be eating up the github actions for 6 hours! Lets comment for now

fix(ci): temporarily comment out stackblitz

---

.changeset/angry-crabs-design.md
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/Content/Authentication/Authentication.vue
packages/api-reference/src/components/Content/ClientLibraries/ClientSelector.vue
packages/api-reference/src/components/Content/Content.vue
packages/api-reference/src/features/BaseUrl/ServerForm.vue
packages/api-reference/src/features/BaseUrl/ServerUrl.vue
packages/api-reference/src/features/BaseUrl/ServerUrlSelect.vue
packages/api-reference/src/features/BaseUrl/ServerVariablesForm.vue
packages/api-reference/src/features/BaseUrl/ServerVariablesSelect.vue
packages/api-reference/src/features/BaseUrl/ServerVariablesTextbox.vue
packages/api-reference/src/features/DownloadLink/DownloadLink.vue
packages/api-reference/src/legacy/components/CardFormTextInput.vue
packages/api-reference/src/legacy/components/SecuritySchemeSelector.vue
packages/api-reference/src/standalone.ts
packages/components/src/components/ScalarIcon/ScalarIcon.vue
packages/components/src/components/ScalarListbox/ScalarListbox.vue
packages/themes/src/reset.css
packages/themes/src/tailwind.ts

this pr fixes #3422 in order to enhance accessibility support and fix lack of as described in the issue.

fix(api-reference): accessibility issues

---

packages/api-client/src/views/Request/components/WorkspaceDropdown.vue

remove import to: on all workspace dropdowns

fix: remove 'import to:' copy

---

.changeset/clever-beers-admire.md
packages/api-client/src/components/DataTable/DataTableCell.vue
packages/api-client/src/components/ImportCurl/ImportCurlModal.vue
packages/api-client/src/libs/importers/curl.test.ts
packages/api-client/src/libs/importers/curl.ts
packages/api-client/src/libs/parse-curl.test.ts
packages/api-client/src/libs/parse-curl.ts

this pr fixes query parameters importation form curl following latest changed introduced in #3267.
**after**
https://github.com/user-attachments/assets/b14a0428-dfcd-461d-b575-3a4efa2eaeb4

fix(api-client): import curl query parameters

---

packages/api-client-app/README.md
packages/api-client-react/README.md
packages/api-client/README.md
packages/api-reference-react/README.md
packages/api-reference/README.md
packages/build-tooling/README.md
packages/cli/README.md
packages/components/README.md
packages/docusaurus/README.md
packages/echo-server/README.md
packages/express-api-reference/README.md
packages/fastify-api-reference/README.md
packages/galaxy/README.md
packages/hono-api-reference/README.md
packages/icons/README.md
packages/mock-server/README.md
packages/openapi-parser/README.md
packages/openapi-types/README.md
packages/scalar.aspnetcore/README.md
packages/void-server/README.md

What the title says! I saw so many mistakes and inconsistencies that we’ve added over time, I’ve just had to go through all/most READMEs.
This PR makes sure all READMEs for popular packages have the correct badges, a short description, a section mentioning Discord and a section about the license. I’ve also fixed typos, added a few more cross-links and tried to make things more clear where I felt we've been vague.

docs: update all the READMEs

---

.changeset/giant-otters-work.md
packages/api-client/src/views/Settings/Settings.vue
packages/api-client/src/views/Settings/SettingsGeneral.vue
packages/api-client/src/views/Settings/SettingsGeneralMode.vue

sorry but @marclave your setting page had to go

fix: style settings page

---

.changeset/bright-waves-pull.md
.changeset/tricky-years-sniff.md
packages/api-client/src/views/Request/RequestSidebar.vue
packages/api-client/src/views/Request/RequestSidebarItemMenu.vue
packages/components/src/components/ScalarIcon/icons/Unwatch.svg
packages/components/src/components/ScalarIcon/icons/icons.ts

this pr is a proposal to add the watch mode toggle in the sidebar context menu as seen below:
https://github.com/user-attachments/assets/d1a3f937-3886-4bc2-9c6a-f0b6a81f3f51

feat(api-client): toggle watch mode

---

SECURITY.md

This PR adds a security policy for our repository. :)

docs: write security policy

---

.changeset/three-singers-bathe.md
packages/api-client/src/components/CommandPalette/TheCommandPalette.vue
packages/api-reference/src/components/Content/ClientLibraries/ClientSelector.vue

not sure why we have custom scroll on this element, there might be a reason for it but none that I can find

fix: command palette ui

---

.changeset/nasty-elephants-fry.md
packages/api-reference/src/features/Search/SearchButton.vue
packages/api-reference/src/features/Search/SearchModal.vue
packages/components/src/components/ScalarSearchInput/ScalarSearchInput.vue
packages/components/src/components/ScalarSearchResults/ScalarSearchResultItem.vue
packages/components/src/components/ScalarSearchResults/ScalarSearchResultList.vue
packages/themes/src/reset.css
packages/themes/src/tailwind.ts

Adds screen reader support for the search modal including accessible names and aria descriptions.

fix(api-reference): search modal a11y improvements

---

README.md

fix: update readme images

---

.changeset/thick-oranges-drive.md
packages/api-client/src/views/Settings/SettingsGeneral.vue
packages/api-client/src/views/Settings/SettingsGeneralMode.vue

Updates: Added to the descriptions, explained the proxy more, linked to the new proxy, not the old one, highlighted the defaults, updated the labels …
Wdyt?
**Before**
**After**

chore(api-client): update wording on settings page

---

.changeset/ninety-trainers-judge.md
packages/api-client/src/components/DataTable/DataTableInput.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuth.vue
packages/api-client/src/views/Request/RequestSection/RequestTable.vue

before:
https://github.com/user-attachments/assets/6582f5d0-b50a-48dd-8622-46432983473e
after: 
https://github.com/user-attachments/assets/20fbe1f6-b87f-4ff4-a03a-ba02be89a195
@antlio or @cameronrohani we need to match the styles w client.scalar.com, not sure what i did :)

fix: add environment variables in auth request fields

---

.changeset/modern-phones-jump.md
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/views/Environment/EnvironmentVariableDropdown.vue

this pr adds keyboard navigation within environment variable dropdown as seen below:
https://github.com/user-attachments/assets/3e958fed-4fa9-48e3-a568-924bc092e498

feat(api-client): env var dropdown keyboard navigation

---

.changeset/dry-kangaroos-explain.md
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue

move required string rightmost + add back the 🍊 colour :)

style(api-reference): required string orange color

---

examples/express-api-reference/package.json
packages/api-client-proxy/package.json
packages/echo-server/package.json
packages/express-api-reference/package.json
packages/nestjs-api-reference/package.json
pnpm-lock.yaml

chore: update express

---

.changeset/shaggy-mugs-pay.md
packages/api-client/src/components/SideNav/SideNav.vue
packages/api-client/src/components/ViewLayout/ViewLayout.vue
packages/api-client/src/layouts/App/ApiClientApp.vue
packages/api-client/src/layouts/App/MainLayout.vue
packages/api-client/src/layouts/Web/ApiClientWeb.vue

https://github.com/user-attachments/assets/3feaa482-9776-412d-9788-9b5eeae10e5c

fix(api-client): bottom navigation on mobile

---

.changeset/grumpy-dodos-yawn.md
packages/api-reference/src/helpers/getExampleCode.test.ts
packages/api-reference/src/helpers/getExampleCode.ts

fix(api-reference): httpSnippet error when `hiddenClient` is true

---

.changeset/breezy-ligers-love.md
packages/api-client/src/views/Request/ResponseSection/ResponseMetaInformation.vue
packages/api-client/src/views/Request/ResponseSection/ResponseSection.vue

From a convo with anthony a few weeks ago - :) 
https://github.com/user-attachments/assets/9baf187a-e547-496f-b21e-eca8d00eb8ce

chore: response flip animation

---

.changeset/purple-emus-do.md
packages/components/src/components/ScalarSearchInput/ScalarSearchInput.vue
packages/themes/src/tailwind.ts

I have no clue why this bg variable changes border bottom color on live but not the local build version but need to get rid of it

style(api-client): fix border color variable

---

.changeset/rude-spoons-poke.md
packages/api-reference/src/components/Content/Schema/SchemaPropertyDetail.vue
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue

fix font size / styling  of `read only` and `property detail values`

style(api-reference): fix some minor font sizes

---

.changeset/beige-adults-poke.md
packages/api-reference/src/legacy/components/SecuritySchemeSelector.vue

fixing individual auth font size and color

fix(api-reference): unstyled auth label, fix #3572

---

.changeset/seven-monkeys-wink.md
packages/oas-utils/src/entities/spec/request-example.test.ts
packages/oas-utils/src/entities/spec/request-examples.ts

closes #3609 
before:
https://github.com/user-attachments/assets/92632483-bec9-421f-b82c-5e8c779784c8
after:
https://github.com/user-attachments/assets/53ad32dc-6ac8-4ce7-8155-a57f4adc395d

fix(oas-utils): improve parameter instance creation by handling enum values for number types

---

.changeset/rude-icons-hope.md
packages/api-client-app/src/renderer/index.html
packages/api-client/src/components/SideNav/SideNav.vue

download button
https://github.com/user-attachments/assets/14fbdec4-3426-4e98-8b17-9d2e2d527c46

feat(api-client): add download button to scalar web

---

packages/fetch/README.md

This PR adds the import statement to the README and this will also show up in `npm`

docs(fetch): add import statement

---

.changeset/sweet-lemons-whisper.md
packages/api-reference/src/components/Anchor/Anchor.vue
packages/api-reference/src/components/Card/CardTab.vue
packages/api-reference/src/components/Content/Operation/ParameterItem.vue
packages/api-reference/src/components/Content/Operation/TestRequestButton.vue
packages/api-reference/src/components/Content/Tag/Endpoints.vue
packages/api-reference/src/components/Content/Tag/Tag.vue
packages/api-reference/src/features/ExampleRequest/ExamplePicker.vue
packages/api-reference/src/features/ExampleRequest/ExampleRequest.vue
packages/api-reference/src/features/ExampleRequest/TextSelect.vue
packages/api-reference/src/features/ExampleResponses/ExampleResponse.vue
packages/api-reference/src/features/ExampleResponses/ExampleResponses.vue
packages/components/src/components/ScalarCodeBlock/ScalarCodeBlock.vue
packages/themes/src/reset.css

https://github.com/user-attachments/assets/d4bde006-5abf-480c-8d5c-cdfa321a4493

feat(api-reference): tag and operation accessibility

---

.changeset/selfish-nails-unite.md
packages/api-client/src/assets/variables.css
packages/api-client/src/components/ImportCollection/ImportCollectionModal.vue

this pr fixes the animation glitch on import collection animation as seen below:
https://github.com/user-attachments/assets/a29a9524-c277-4a93-9afc-d2e05a4d566f
https://github.com/user-attachments/assets/965bec07-5810-430e-95fc-fce5a8241f64

fix(api-client): collection modal animation

---

.changeset/sweet-walls-cross.md
packages/api-client/src/components/CodeInput/codeVariableWidget.ts
packages/api-client/src/store/environment.ts
packages/api-client/src/views/Environment/Environment.vue
packages/api-client/src/views/Environment/EnvironmentVariableDropdown.vue

this pr is a follow up on [@amritk comment](https://github.com/scalar/scalar/pull/3664#issuecomment-2444910163) and introduces the following:
- synchronization of keys between environment
- style updates on pill plugin
- fixes redirection (environment removal, page reload)
https://github.com/user-attachments/assets/65d93c91-d154-4f54-8f97-8c0c19b4048d

feat(api-client): environment variables management

---

CODEOWNERS

Adds a few more codeowners based on observations/learnings :)

chore: moarr codeowners

---

.changeset/dirty-shrimps-sparkle.md
packages/api-client/src/views/Request/RequestSection/RequestAuth/OAuth2.vue
packages/api-client/src/views/Request/libs/oauth2.ts
packages/oas-utils/src/entities/spec/security.ts

fix(api-client): default redirectURI and prefix relative redirectURIs with activeServer

---

.changeset/dirty-shrimps-sparkle.md
packages/api-client/src/views/Request/libs/oauth2.test.ts
packages/api-client/src/views/Request/libs/oauth2.ts

Added tests for what we have first, then I will add the new stuff
closes #3702

feat(api-client): add tests for oauth2

---

packages/scalar_django_ninja/README.md

**Problem**
Currently, the instructions don't give you all the details you need to install the Django Ninja API reference.
**Solution**
With this PR, you get both the details on installing and accessing the API reference.

chore: docs Django Ninja README.md

---

blog/hello-world.md
blog/scalar.config.json

chore: blog

---

.changeset/fair-flies-buy.md
packages/api-client/src/views/Request/RequestSection/RequestAuth/OAuthScopesInput.vue
packages/oas-utils/src/transforms/import-spec.ts

closes #3735
we can handle this temporarily here

fix(api-client): handle scopes array temporarily

---

.changeset/gold-phones-reply.md
packages/api-client/src/views/Request/libs/live-sync.test.ts
packages/oas-utils/src/transforms/import-spec.test.ts
packages/oas-utils/src/transforms/import-spec.ts

feat(api-client): add support for the x-defaultClientId extension

---

.changeset/silly-planets-cough.md
packages/api-client/src/components/ImportCollection/ImportNowButton.vue

import modal didnt work if we needed cors : )

fix: add missing proxy on import modal

---

.changeset/old-feet-impress.md
packages/api-client/src/views/Request/ResponseSection/ResponseBodyPreview.vue

currently we loop response media, but lets let the user control it :)

fix: remove loop from media response

---

.changeset/fair-ties-invent.md
packages/api-client/src/components/ContextBar.vue
packages/api-client/src/components/SideNav/DownloadAppButton.vue
packages/api-client/src/components/SideNav/SideNav.vue
packages/api-client/src/components/SideNav/SideNavLink.vue
packages/api-client/src/views/Request/RequestSection/RequestSection.vue
packages/api-client/src/views/Request/RequestSection/RequestTable.vue

before:
after:
link to scalar:

style(api-client): fix some visual bugs and add link to scalar on web

---

.changeset/chilly-monkeys-tap.md
examples/proxy-server/README.md
examples/proxy-server/main.go
examples/proxy-server/main_test.go
examples/proxy-server/package.json
packages/import/package.json
packages/import/src/resolve.test.ts
packages/import/src/resolve.ts
packages/oas-utils/src/helpers/makeUrlAbsolute.test.ts
packages/oas-utils/src/helpers/makeUrlAbsolute.ts
pnpm-lock.yaml

fix: rollback "feat(proxy-server): follow redirects (#3818)"

---

.changeset/moody-pigs-design.md
packages/oas-utils/src/transforms/import-spec.ts

@hanspagel another example of something we can do in the parser

fix(api-client): remove examples before request parsing

---

.changeset/twenty-carrots-hug.md
packages/api-client/src/layouts/Modal/ApiClientModal.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuth.vue

This seems to cause issues when using the react integrations. Maybe hold off for a few versions
Closes #3859

fix: remove useTemplateRef

---

.changeset/two-flies-help.md
packages/components/src/components/ScalarDropdown/ScalarDropdown.vue
packages/components/src/components/ScalarIcon/icons/House.svg
packages/components/src/components/ScalarListbox/ScalarListbox.vue
packages/components/src/components/ScalarMenu/ScalarMenu.spec.ts
packages/components/src/components/ScalarMenu/ScalarMenu.stories.ts
packages/components/src/components/ScalarMenu/ScalarMenu.vue
packages/components/src/components/ScalarMenu/ScalarMenuLink.vue
packages/components/src/components/ScalarMenu/ScalarMenuProduct.vue
packages/components/src/components/ScalarMenu/ScalarMenuProducts.vue
packages/components/src/components/ScalarMenu/ScalarMenuProfile.vue
packages/components/src/components/ScalarMenu/ScalarMenuResources.vue
packages/components/src/components/ScalarMenu/ScalarMenuSection.vue
packages/components/src/components/ScalarMenu/index.ts
packages/components/src/components/ScalarPopover/ScalarPopover.vue
packages/components/src/index.ts

feat(components): create ScalarMenu component

---

.changeset/purple-hairs-tap.md
packages/api-client/src/components/ViewLayout/ViewLayoutSection.vue

fixes scroll on mobile for client

fix(api-client): mobile overflow scroll on client

---

.changeset/stale-suns-thank.md
packages/api-client/src/libs/create-request-operation.test.ts
packages/api-client/src/libs/send-request.test.ts
packages/oas-utils/src/entities/spec/collection.ts
packages/oas-utils/src/entities/spec/parameters.test.ts
packages/oas-utils/src/entities/spec/request-examples.ts
packages/oas-utils/src/entities/spec/requests.ts
packages/oas-utils/src/entities/spec/spec-objects.ts
packages/oas-utils/src/entities/spec/x-scalar-environments.test.ts
packages/oas-utils/src/entities/spec/x-scalar-environments.ts
packages/oas-utils/src/entities/spec/x-scalar-secrets.test.ts
packages/oas-utils/src/entities/spec/x-scalar-secrets.ts
packages/oas-utils/src/spec-extentions/x-scalar-environments.yaml
packages/oas-utils/src/spec-extentions/x-scalar-folder.yaml
packages/oas-utils/src/transforms/export-spec.test.ts
packages/oas-utils/src/transforms/export-spec.ts
packages/oas-utils/src/transforms/import-spec.ts
packages/oas-utils/src/transforms/index.ts
packages/oas-utils/tsconfig.json
packages/oas-utils/tsconfig.test.json

Adds a custom extension to serialize environment variables and secrets into the spec.

feat(oas-utils): add environment and secret extensions

---

README.md

update 1/4 to readme - make all images bigger

style(readme): update client image

---

README.md

part 2/4 - make api ref image BIG

style(readme): update api ref image

---

README.md

add copy to readme, fix mobile image for refs, remove feature section and put it directly in api ref intro section

style(readme): add copy to readme

---

.changeset/sharp-oranges-talk.md
packages/components/src/components/ScalarCheckbox/ScalarCheckbox.stories.ts
packages/components/src/components/ScalarCheckbox/ScalarCheckbox.vue
packages/components/src/components/ScalarHeaderButton/ScalarHeaderButton.spec.ts
packages/components/src/components/ScalarHeaderButton/ScalarHeaderButton.stories.ts
packages/components/src/components/ScalarHeaderButton/ScalarHeaderButton.vue
packages/components/src/components/ScalarHeaderButton/index.ts

Adds checkbox and shared nav button

feat(components): new checkbox and header button

---

packages/openapi-parser/tests/diff.test.ts
playwright/tests/jsdelivr.spec.ts

Test specifications have been moved. Updates the location to pull test specifications from

chore(openapi-parser): update test specification location

---

.changeset/gorgeous-seahorses-raise.md
packages/api-client/src/components/ImportCollection/ImportCollectionModal.vue
packages/api-client/src/components/ImportCollection/IntegrationLogo.vue
packages/api-client/src/layouts/App/ApiClientApp.vue
packages/api-client/src/layouts/App/MainLayout.vue
packages/api-client/src/layouts/Web/ApiClientWeb.vue
packages/api-client/src/views/Settings/SettingsGeneral.vue
packages/api-client/src/views/Settings/components/SettingsAppearance.vue
packages/api-client/src/views/Settings/components/SettingsSection.vue
packages/api-reference/src/components/Content/Content.vue
packages/themes/src/index.ts
packages/themes/src/presets/elysiajs.css
packages/themes/src/presets/fastify.css
packages/types/src/legacy/reference-config.ts

when people come in from localhost, from one of our amazing integrations lets _really show it off_
icon + custom theme we made 😼
needs @cameronrohani to polish

feat(api-client): add framework themes

---

.changeset/spicy-cooks-grin.md
packages/api-client/src/components/AddressBar/AddressBar.vue
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue
packages/api-reference/src/features/BaseUrl/ServerUrlSelect.vue
packages/api-reference/src/legacy/components/SecuritySchemeSelector.vue
packages/code-highlight/src/css/code.css
packages/components/src/components/ScalarCodeBlock/ScalarCodeBlock.vue
packages/themes/src/presets/deepSpace.css

fixes for scalar galaxy (theme)
fixes for some padding with bulma
fixes for people using global styling on `<pre>` || `<code>`

fix(api-reference): some theme issues and conflicts with bulma

---

documentation/configuration.md

**Problem**
The configuration doc uses the incorrect proxy property so this will not work.
**Solution**
We will provide the correct proxy property

chore: Update configuration.md to correct proxy prop

---

.changeset/weak-teachers-compare.md
packages/api-reference/src/helpers/parse.ts
packages/oas-utils/src/transforms/import-spec.test.ts
packages/oas-utils/src/transforms/import-spec.ts

Short term fix to catch invalid parsing

fix(oas-utils): catch errors for invalid OpenAPI documents

---

.changeset/chatty-tigers-remember.md
packages/api-client/src/views/Request/RequestSection/RequestBody.vue
packages/api-client/src/views/Request/RequestSection/RequestParams.vue
packages/api-client/src/views/Request/RequestSection/RequestTable.vue

this pr fixes the row addition within api client request table that was prevented when using `@scalar/api-reference`.

fix(api-client): request table row addition

---

README.md

new animation for top 10 contributors for nov

readme: top 10 contributors november

---

.changeset/soft-jars-talk.md
packages/themes/src/index.ts

lets export each theme individually for easier access 🆒

chore: export each theme individually for easier access

---

README.md

PR 4000 LET'S GOOO
ᵢ ⱼᵤₛₜ 𝓌ₐₙₜₑ𝒹 ₜₒ ᵦₑ ₙᵤₘᵦₑᵣ ₄₀₀₀

docs: fix type in readme

---

.changeset/fair-berries-love.md
packages/themes/package.json
packages/themes/vite.config.ts

feat(themes): add commonjs export for themes

---

.changeset/two-terms-beg.md
packages/components/src/components/ScalarIcon/icons/Hide.svg
packages/components/src/components/ScalarIcon/icons/Show.svg

nit pr to update show / hide icons in order to fix bumpy interaction:
**⊢ before / after**
https://github.com/user-attachments/assets/c046ceac-e213-48bf-91cc-cdefda316c89
https://github.com/user-attachments/assets/1805037c-c662-4f9d-b4b5-47b85d2b701b

feat(icons): show hide password icons

---

.changeset/fair-moose-fetch.md
packages/components/src/components/ScalarErrorBoundary/ScalarErrorBoundary.spec.ts
packages/components/src/components/ScalarErrorBoundary/ScalarErrorBoundary.stories.ts
packages/components/src/components/ScalarErrorBoundary/ScalarErrorBoundary.vue

I made these changes to @hanspagel's original pr but never pushed them apparently 🤦 
https://github.com/user-attachments/assets/94a953e5-d03a-442d-8ecb-91fab03e9641

feat(components): style ScalarErrorBoundary and add tests and stories

---

.changeset/swift-ears-change.md
packages/components/src/hooks/useBindCx.spec.ts
packages/components/src/hooks/useBindCx.ts

Also adds tests to ensure that both prop and attribute reactivity are preserved.

feat(components): clean up reactivity for useBindCx

---

.changeset/silly-mayflies-shake.md
packages/api-client/package.json
packages/api-client/src/components/DataTable/DataTableCheckbox.vue
packages/api-client/src/components/HttpMethod/HttpMethod.vue
packages/components/package.json
packages/components/src/cva.test.ts
packages/components/src/cva.ts
packages/components/src/index.ts
pnpm-lock.yaml

I thought it wasn't working correctly, the tests say otherwise. My problem lies elsewhere

feat(components): upgrade cva + tw merge plus add tests

---

.changeset/violet-pumas-develop.md
packages/api-client/src/views/Request/RequestSection/RequestAuth/OAuth2.vue
packages/api-client/src/views/Request/libs/oauth2.test.ts
packages/api-client/src/views/Request/libs/oauth2.ts

feat(api-client): add proxy to oauth authorize server calls

---

README.md

This PR adds the Ruby on Rails integration developed by @dmytroshevchuk to the README. 🙌

docs: add Ruby on Rails integration

---

.changeset/great-rice-relax.md
packages/api-client/src/views/Request/RequestSubpageHeader.vue
packages/api-client/src/views/Request/ResponseSection/ResponseEmpty.vue

to test you can use
```css
.scalar .gitbook-show {
display: block !important;
}
.scalar .gitbook-hidden {
display: none !important;
}
```

feat(api-client): show API client button in GitBook

---

packages/scalar-app/package.json
pnpm-lock.yaml

This updates @todesktop/cli.
> Your version of @todesktop/cli is out of date.

chore: update @todesktop/cli

---

packages/scalar-app/todesktop.json

this pr update the todesktop config by specifying a pnpm version.

chore(scalar-app): specifies pnpm package manager version in todesktop

---

.changeset/shy-lamps-return.md

this pr adds missing changeset for #4116

chore(scalar-app): todesktop missing changeset

---

.changeset/clever-baboons-refuse.md
packages/api-client/src/views/Request/RequestSection/RequestAuth/OAuthScopesInput.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestExampleAuth.vue

needs @cameronrohani styles
closes https://github.com/scalar/scalar/issues/3698

feat(api-client): apply specific OAuth 2.0 security schemes

---

.changeset/popular-kiwis-cheat.md
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Enums/ScalarLayout.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarOptionsExtensions.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Mapper/ScalarOptionsMapper.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Options/ScalarOptions.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/ScalarConfiguration.cs
packages/scalar.aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarOptionsExtensionsTests.cs
packages/scalar.aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarOptionsMapperTests.cs

This PR adds the possibility to configure the Scalar layout in the `Scalar.AspNetCore` package.
Closes #4126

feat(Scalar.AspNetCore): add layout option

---

.github/workflows/ci.yml

The release must be done in the UI now. :)

ci: disable toDesktop release

---

README.md

This PR adds Ts.ED to the root README. :)
https://tsed.dev/tutorials/scalar.html

docs: add Ts.ED

---

packages/api-client/src/libs/send-request/send-request.ts

Fix regression caused by #3981.
**Problem**
Same issue as #3419.
**Solution**
Same solution as #3305.

fix(api-client): uppercase request method

---

.changeset/empty-lizards-shout.md
packages/api-client/src/views/Request/RequestSection/RequestAuth/OAuthScopesInput.vue

fix(api-reference): scope UI in ref max height

---

.changeset/quick-moons-hunt.md
packages/api-reference/src/features/Operation/hooks/useRequestExample.ts

fix: operation server null check

---

documentation/integrations/dotnet.md

This PR _hopefully_ improves the docs of how the authentication in .NET and the `Scalar.AspNetCore` package works.

docs(Scalar.AspNetCore): clarify authentication

---

.changeset/stupid-rice-float.md
packages/api-reference/src/components/ApiReferenceLayout.vue

fix(api-reference): missing open in api client button

---

.github/actions/build/action.yml
.github/workflows/ci.yml
package.json
pnpm-lock.yaml

This reverts commit 292736953627a0d7dae38d1c8b58b3625bf4e1e3.

fix: revert ci: read from cache for subsequent builds (#4196)

---

.changeset/two-kangaroos-live.md
packages/api-client/src/views/Request/RequestSection/RequestSection.vue

this pr is part of #4214 in order to ensure the request body being displayed.

fix(api-client): adds request body input safety check

---

.changeset/many-panthers-listen.md
packages/nextjs-api-reference/package.json
pnpm-lock.yaml

chore: bump nextjs peerDependencies

---

.changeset/chilled-lions-sniff.md
packages/api-client/src/components/ImportCurl/ImportCurlModal.vue
packages/api-client/src/views/Request/Request.vue

this pr adds a collection selector to the import curl modal and fix the server being created in drafts collection requests:
<div>
</div>

feat(api-client): import curl collection

---

.github/pull_request_template.md

This PR adds a checklist to the PR template, so it’s easy to go through and check whether the PR can be considered complete.
Should help with reviewing PRs and getting them in even quicker. ⚡

chore: add a checklist to the PR template

---

packages/api-reference-react/README.md
packages/nextjs-api-reference/README.md

quick fix to the react docs 
**Checklist**

chore: update the react docs

---

packages/components/README.md

Adds a checklist for adding new components (for me to copy and paste into my PRs). This is mostly a reminder for me right now but will be useful for others contributing as well.

docs(components): add checklist for new components

---

.changeset/giant-lemons-deny.md
packages/use-codemirror/package.json
packages/use-codemirror/playground/App.vue
packages/use-codemirror/playground/components/CodeMirror.vue
packages/use-codemirror/src/themes/createCodeMirrorTheme.test.ts
packages/use-codemirror/src/themes/createCodeMirrorTheme.ts
packages/use-codemirror/src/themes/index.ts
pnpm-lock.yaml

**Problem**
We have some CJS/ESM problems with `@uiw/codemirror-themes` for a while.
Fixes #4222
**Solution**
We’re using just a single file from the package, so let’s drop it into our code base. :)
I’ve also fixed the styling of the playground.
**Checklist**

chore(use-codemirror): remove `@uiw/codemirror-themes`

---

.changeset/fuzzy-dolphins-breathe.md
.github/workflows/ci.yml
.github/workflows/deploy-components.yml
packages/components/.gitignore
packages/components/package.json
turbo.json

Opened a new PR thinking that would fix stuff. It did not but I figured out what the problem was and now it's working!

feat(components): host storybook on netlify

---

documentation/guides/docs/github-sync.md

@marclave has requested a rename 🙏 The repo itself has already been updated.

docs: rename repo to scalar/starter

---

documentation/configuration.md
packages/types/src/legacy/reference-config.ts

**Problem**
Forgot to update the docs
@hanspagel did you say you auto generated this somewhere?
**Checklist**

feat(api-reference): updated docs for new hash functions

---

packages/api-client/src/libs/send-request/set-request-cookies.test.ts
packages/api-client/src/libs/send-request/set-request-cookies.ts

Omg, I broke a test with a quick refactor before merging and didn’t notice.
This should fix it.

fix(api-client): broken test

---

.changeset/great-rabbits-drum.md
.changeset/warm-dolphins-change.md
CONTRIBUTING.md
packages/components/.storybook/main.ts
packages/components/.storybook/preview.css
packages/components/README.md
packages/components/src/docs/Introduction.mdx
packages/themes/README.md

Trying to get some of the info that's just in my head into the docs before onboarding new folks. Also makes the storybook a little fancier by including the readme.
**Checklist**

docs: improve components and themes docs

---

.changeset/tender-tips-begin.md
SECURITY.md
documentation/themes.md
packages/api-client/src/components/SideNav/SideHelp.vue
packages/components/src/components/ScalarMenu/ScalarMenuResources.vue
packages/scalar-app/todesktop.json

Updates the Scalar support email in a bunch of places, we might want to do it in more places too? These seemed like the most reasonable though.
@marclave's email is all over 😅 
**Checklist**

chore: update Scalar support email

---

.changeset/curvy-humans-care.md
packages/components/src/components/ScalarFloating/ScalarFloating.vue

**Problem**
floating component is firing log error as it doesn't find id.
**Solution**
this pr sets the target ref on floating component mounted to ensure element availability.
**Checklist**

fix(components): floating target ref

---

.changeset/cyan-zebras-rescue.md
packages/api-client/src/components/CodeInput/CodeInput.vue

**Problem**
This fixes the style issues on the address bar
**Solution**
We fix them a bit
**Checklist**

fix(api-reference): addressbar style in modal mode

---

.github/workflows/ci.yml

Not sure if this will work but YOLO lets test it in prod

feat(ci): added bust cache to github action

---

documentation/integrations/django-ninja.md

**Problem**
Currently, I documented how to use Django Ninja in the integration's [README](https://github.com/scalar/scalar/pull/3778), but it would be also useful to have it here.
**Solution**
With this PR, adding documentation on how to fully set up the Django Ninja integration. 
**Checklist**

docs: Django Ninja integration

---

documentation/integrations/django.md

**Problem**
Currently, there's no details on how to integrate Django and Scalar's API Reference
**Solution**
With this PR, documenting @m1guer's Scalar Django integration
**Checklist**

docs: django integration

---

.changeset/yellow-eggs-serve.md
packages/api-client/src/components/AddressBar/AddressBar.vue
packages/api-client/src/components/Server/ServerDropdown.test.ts
packages/api-client/src/components/Server/ServerDropdown.vue
packages/api-client/src/components/Server/ServerDropdownItem.vue
packages/api-client/src/components/ViewLayout/ViewLayoutCollapse.vue
packages/api-client/src/hooks/useLayout.ts
packages/api-client/src/views/Request/RequestSection/RequestAuth/OAuth2.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuth.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuthDataTable.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestExampleAuth.vue
packages/api-client/src/views/Request/RequestSection/RequestSection.vue
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/Content/Content.vue
packages/api-reference/src/features/BaseUrl/BaseUrl.vue

**Problem**
The add server button shows up on the references client modal
**Solution**
It no longer shows up there, also added tests 🧪 
**Checklist**

feat(api-client): added some tests for the new server dropdown

---

packages/use-codemirror/package.json
packages/use-codemirror/src/index.ts
pnpm-lock.yaml

**Problem**
Its always breaking!
**Solution**
We just remove it and we can add it on the org side directly
**Checklist**

chore: remove yjs

---

.changeset/shiny-cherries-thank.md

this PR adds the missing changeset tor #4659

fix(use-codemirror): missing changeset

---

.changeset/mean-experts-count.md
.changeset/slimy-pillows-sin.md
packages/components/src/components/ScalarCombobox/ScalarCombobox.stories.ts
packages/components/src/components/ScalarCombobox/ScalarCombobox.vue
packages/components/src/components/ScalarCombobox/ScalarComboboxMultiselect.vue
packages/components/src/components/ScalarCombobox/ScalarComboboxOptions.vue
packages/components/src/components/ScalarCombobox/ScalarComboboxPopover.vue
packages/components/src/components/ScalarCombobox/types.ts

https://github.com/user-attachments/assets/62362df9-45a4-459e-8602-bce71ec53210
Fixes DOC-2956
**Checklist**

fix(components): improve combobox resizing

---

.changeset/orange-games-look.md
documentation/openapi.md
packages/api-reference/src/components/Content/Schema/SchemaProperty.test.ts
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue
packages/api-reference/src/components/Content/Schema/helpers/optimizeValueForDisplay.ts

**Problem**
Currently, we’re optimizing discriminators (anyOf, allOf …) for display, but don’t use that, e.g. to render enums.
**Solution**
With this PR, we’re using the optimized value for everything, and look - the enums appear again.
I’ve seen we didn't add `x-enumDescriptions` to the docs, so I've added these, too.
**Before**
**After**
**Example**
```json
{
"openapi": "3.1.1",
"info": {
},
"schemas": {
"Example": {
"required": [
"works",
"does-not-work",
"does-not-work-either"
],
"works": {
"$ref": "#/components/schemas/Something"
},
"does-not-work": {
"anyOf": [
{
"$ref": "#/components/schemas/Something"
}
]
},
"does-not-work-either": {
"anyOf": [
{
"$ref": "#/components/schemas/Something"
}, …
```

fix(api-reference): enums in discriminators aren’t shown 

---

.changeset/eight-jars-dance.md
packages/components/package.json
packages/components/src/components/ScalarFileUpload/ScalarFileUpload.stories.ts
packages/components/src/components/ScalarFileUpload/ScalarFileUpload.test.ts
packages/components/src/components/ScalarFileUpload/ScalarFileUpload.vue
packages/components/src/components/ScalarFileUpload/ScalarFileUploadDropTarget.vue
packages/components/src/components/ScalarFileUpload/ScalarFileUploadError.vue
packages/components/src/components/ScalarFileUpload/ScalarFileUploadFileList.vue
packages/components/src/components/ScalarFileUpload/ScalarFileUploadInput.vue
packages/components/src/components/ScalarFileUpload/ScalarFileUploadInputCompact.vue
packages/components/src/components/ScalarFileUpload/ScalarFileUploadLoading.vue
packages/components/src/components/ScalarFileUpload/index.ts
packages/components/src/components/ScalarFileUpload/types.ts
pnpm-lock.yaml

Creates a file upload / dropzone component with two variants and several composition options. Will confirm the design with Cam soon™ 
https://github.com/user-attachments/assets/4d2df036-c7bd-40df-8c4c-b9d1ec39ff53
**Checklist**

feat(components): create file uploader component

---

examples/nextjs-api-reference/package.json
integrations/nextjs/package.json
packages/nextjs-openapi/package.json
pnpm-lock.yaml

**Problem**
Dependabot keeps bugging us to update Next (probably security update), but the PRs don’t pass CI (for reasons).
**Solution**
I’ve updated manually and hope CI is passing here.
**Checklist**

chore: update Next to 15.1.2

---

.changeset/plenty-shirts-behave.md
packages/api-client/src/views/Request/RequestRoot.vue

**Problem**
Currently, our request history doesnt work, any updates to the request update each history item
**Solution**
With this PR we clone each result before appending to the history, so we can properly handle the history
**Checklist**

fix: request history

---

.github/workflows/ci.yml
lefthook.yml
package.json
packages/components/src/components/ScalarSidebar/ScalarSidebarButton.vue
packages/components/src/components/ScalarSidebar/ScalarSidebarGroup.vue
packages/components/src/components/ScalarSidebar/ScalarSidebarIndent.vue
packages/oas-utils/src/entities/spec/request-example.test.ts
packages/oas-utils/src/entities/spec/request-examples.ts
packages/oas-utils/src/spec-getters/getRequestBodyFromOperation.ts
pnpm-lock.yaml

**Problem**
We skipped the `format:check` script while we still had the old formatting.
**Solution**
This PR adds it to CI again.

ci: run `format:check` again

---

CODEOWNERS

Just a CODEOWNERS update
Had to remove Tom
Added myself to the API client, I review a lot of those PRs and code more in that package recently

chore: CODEOWNERS update

---

.changeset/six-fireants-listen.md
packages/api-reference/src/components/Card/Card.vue
packages/api-reference/src/components/Content/Tag/Endpoints.vue

Before / after:
https://github.com/user-attachments/assets/ae531ffb-4dc4-497e-b504-ce4834442200
**Checklist**

fix(api-reference): improve high zoom level readability

---

.changeset/three-ducks-battle.md
packages/api-client/src/components/ViewLayout/ViewLayoutCollapse.vue

**Problem**
**Solution**
**Checklist**

fix(api-reference): auth border

---

package.json
pnpm-lock.yaml

**Problem**
I thought upgrading turbo would fix this next.js issue, it did not but I found a workaround
https://github.com/vercel/turborepo/issues/3340
Also turbo sometimes randomly hangs so maybe that'll get fixed
**Solution**
With this PR we upgrade the turbo package
**Checklist**

chore: upgrade turbo

---

.changeset/friendly-islands-divide.md
integrations/hono/playground/index.ts
integrations/hono/tsconfig.json

**Problem**
Currently, hono is broke
**Solution**
With this PR we fix hono playground build.
**Checklist**

fix(hono): docker build in ci

---

.changeset/fresh-penguins-shave.md
integrations/express/Dockerfile
integrations/fastify/Dockerfile

**Problem**
Currently, …
**Solution**
With this PR …
**Checklist**

fix(express): added types to fastify and express dockerfiles

---

.changeset/tender-snails-applaud.md
integrations/express/Dockerfile
integrations/fastify/Dockerfile
integrations/hono/Dockerfile
packages/galaxy/Dockerfile

**Problem**
Currently, I have been adding the packages one by one (to save space?)
**Solution**
With this PR we just copy all packages to save dev time.
**Checklist**

feat(tooling): include all packages in dockerfiles

---

.github/workflows/ci.yml

Slow, hangs every now and then and not actually used, let’s remove it.

ci: remove stackblitz

---

eslint.config.mjs
packages/components/src/components/ScalarColorModeToggle/ScalarColorModeToggleButton.vue
packages/components/src/components/ScalarColorModeToggle/ScalarColorModeToggleIcon.vue
packages/components/src/components/ScalarFloating/ScalarFloating.vue

Adds exceptions for a bunch of rules that conflict with prettier (at @amritk's rec).
**Checklist**

chore: add exceptions for eslint rules that conflict with prettier

---

.changeset/metal-rocks-agree.md
.github/workflows/deploy-examples.yml

**Problem**
Currently, deploy examples is even more busted
**Solution**
With this PR maybe we fix it
**Checklist**

fix(ci): fix deploy examples build

---

.changeset/itchy-dancers-attack.md
.changeset/plenty-fireants-heal.md
packages/types/src/api-reference/api-reference-configuration.test-d.ts
packages/types/src/api-reference/api-reference-configuration.ts
packages/void-server/package.json
packages/void-server/src/createVoidServer.test.ts
packages/void-server/src/createVoidServer.ts
packages/void-server/src/index.ts
packages/void-server/src/utils/getRequestData.ts
packages/void-server/src/utils/index.ts
packages/void-server/tsconfig.build.json
packages/void-server/tsconfig.json
packages/void-server/vite.config.ts
pnpm-lock.yaml

Let’s use the stricter TS config for @scalar/void-server. :)

refactor(void-server): strict TS config

---

.cursor/rules/tests.mdc
.cursor/rules/typescript.mdc
.cursor/rules/vue-components.mdc
CODEOWNERS

**Problem**
Currently, we’re using Cursor, but only have individual Cursor rules (@marclave) or non at all (me). This makes Cursor write in various styles or maybe even delete code that we want, or introduce new patterns/styles.
**Solution**
With this PR we’re adding Cursor rules that we all share. This could help to streamline the output for us, and even for external contributors.
It’s also a perfect place for humans to look up coding style related things, or even learn from what we consider best practices.
They are probably not perfect, but it’s a start. @amritk feel free to add to it! I quickly jotted down a few points and asked ChatGPT to improve it for the purpose of using it as a Cursor rule.
**Summary**
- Keep components small, focused, and composable.
- Move logic out of templates …

chore: Cursor rules

---

projects/client-scalar-com/index.html

This PR adds just a few more meta tags to https://client.scalar.com. 
Not necessary, but nice to have. :)

feat(client.scalar.com): add more meta tags

---

.changeset/thick-pears-reply.md
packages/components/src/components/ScalarCombobox/ScalarComboboxOptions.vue

Before / after: 
https://github.com/user-attachments/assets/d4935478-2f73-4c9c-8377-f9852d45106c

fix(components): handle no active option for combobox

---

.changeset/chilled-spoons-work.md
packages/components/src/components/ScalarForm/index.ts

fix(components): add missing forms exports

---

.changeset/olive-ducks-jog.md
packages/components/src/components/ScalarForm/ScalarFormField.vue

Sorry another small one.
**Checklist**

fix(components): don't show form field label if none is provided

---

.changeset/brown-elephants-burn.md
.changeset/great-cameras-end.md
.changeset/rude-cows-jump.md
packages/galaxy/src/documents/3.1.yaml
packages/mock-server/tests/galaxy.test.ts

I got side tracked, and did a bigger update to Scalar Galaxy.
* added more data to the planet schema
* split the user schema in user and credentials again (cosmetic change)
* fixed the invalid examples for the image upload
* added a callback (see #5174, not rendered yet)
* add an externalDocs link (not rendered yet)
* added some missing responses
new minor version

feat(galaxy): more of everything

---

documentation/migrate/stoplight.md

**Problem**
Currently, it's unclear how to migrate from Stoplight
**Solution**
With this PR, we add a Stoplight migration guide. Added a new folder for migrations as we expect to have more :)
**Checklist**

docs: Stoplight migration guide

---

documentation/configuration.md

**Problem**
Currently, …
**Solution**
With this PR …
**Checklist**

docs: correct typos in configuration.md

---

packages/core/README.md

**Problem**
Currently, …
**Solution**
With this PR …
**Checklist**

docs: correct import in `@scalar/core` README.md

---

.changeset/wild-kids-sniff.md
packages/api-reference/src/components/ShowMoreButton.vue
packages/api-reference/src/components/Sidebar/SidebarElement.vue
packages/types/src/api-reference/api-reference-configuration.ts

**Solution**
With this PR we add a couple callbacks to the sidebar
**Checklist**

feat(api-reference): add a few callbacks to the sidebar

---

.changeset/mean-poets-rhyme.md
packages/api-client/src/components/DataTable/DataTable.vue
packages/api-client/src/components/DataTable/DataTableCell.vue
packages/api-client/src/components/ScalarAsciiArt.vue
packages/api-client/src/components/ScalarHotkey.test.ts
packages/api-client/src/components/ScalarHotkey.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuthDataTable.vue
packages/api-client/src/views/Request/RequestSection/RequestBody.vue
packages/api-client/src/views/Request/RequestSection/RequestCodeExample.vue
packages/api-client/src/views/Request/RequestSection/RequestParams.vue
packages/api-client/src/views/Request/RequestSection/RequestSection.vue
packages/api-client/src/views/Request/RequestSection/RequestTable.vue
packages/api-client/src/views/Request/ResponseSection/RequestHeaders.vue
packages/api-client/src/views/Request/ResponseSection/ResponseHeaders.vue

https://github.com/user-attachments/assets/11af1bb0-cc58-4368-913a-423f095e620f
**Checklist**

fix(api-client): improve request table header a11y

---

.changeset/nine-turtles-relate.md
examples/web/src/components/DevReferencesOptions.vue
integrations/nuxt/src/runtime/components/ScalarApiReference.vue
integrations/nuxt/src/types.ts
packages/nextjs-openapi/src/openapi.ts

chore: replaced deprecated ReferenceConfiguration with ApiReferenceConfiguration

---

.changeset/shy-deers-crash.md
packages/themes/src/variables.css

fix(themes): make `--scalar-font-size-1` smaller

---

.changeset/fifty-buttons-yell.md
.changeset/strong-garlics-lay.md
packages/api-client/src/views/Collection/CollectionAuthentication.vue
packages/api-client/src/views/Collection/CollectionSettings.vue
packages/api-client/src/views/Collection/components/MarkdownInput.vue

**Problem**
currently within collection page:
- empty description is not displaying empty state + style issue
- disabled authentication is not showing option
- collection without required authentication is not allowing to set any auth
**Solution**
this pr updates the collection overview and settings to fix issues listed aboved:
`description`
| <img width="750" alt="image" src="https://github.com/user-attachments/assets/65c9c68a-694c-42a9-b5c8-0d34c3f43a02" /> | <img width="750" alt="image" src="https://github.com/user-attachments/assets/4351d2db-b0d2-4bc2-8978-124bd525e5f2" /> |
| empty description displays blank | empty description displays empty state | 
`authentication style`
| <img width="750" alt="image" …

fix(api-client): collection authentication options

---

.changeset/hot-vans-guess.md
.changeset/itchy-maps-jog.md
documentation/configuration.md
documentation/themes.md
packages/api-client/src/views/Settings/SettingsGeneral.vue
packages/themes/src/index.ts
packages/themes/src/presets/laserwave.css
packages/types/src/api-reference/api-reference-configuration.ts
packages/types/src/legacy/reference-config.ts

Pew pew. [Demo](https://11261b7a-f059-4539-b086-c36a316767a7--scalar-deploy-preview.netlify.app/test-api-reference/modern/laserwave)
**Checklist**

feat(themes): add laserwave theme

---

CONTRIBUTING.md
package.json

Also added it to the docs ✨ 
**Checklist**

fix: align refs dev command with other dev commands

---

documentation/guides/docs/getting-started.md
documentation/integrations/docusaurus.md
documentation/integrations/fastify.md
documentation/integrations/go.md

**Problem**
These four files contain small issues
**Solution**
With this PR I have updated those files
**Checklist**

docs: fix a few typos

---

.changeset/long-books-hope.md
packages/api-client/src/views/Request/ResponseSection/index.ts

Just going to keep exporting
**Checklist**

chore(api-client): export response body component

---

README.md

docs(contributor): update readme contributors animation

---

integrations/aspnetcore/.editorconfig
integrations/aspnetcore/playground/Scalar.AspNetCore.Playground/Books/BookEndpoints.cs
integrations/aspnetcore/src/Scalar.AspNetCore.Microsoft/Scalar.AspNetCore.Microsoft.csproj
integrations/aspnetcore/src/Scalar.AspNetCore/Converters/PkceJsonConverter.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Converters/StabilityJsonConverter.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Enums/ScalarTheme.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Mapper/ScalarOptionsMapper.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Scalar.AspNetCore.csproj
integrations/aspnetcore/tests/Directory.Build.props
integrations/aspnetcore/tests/Scalar.AspNetCore.Microsoft.Tests/Scalar.AspNetCore.Microsoft.Tests.csproj
integrations/aspnetcore/tests/Scalar.AspNetCore.Tests/Scalar.AspNetCore.Tests.csproj
integrations/aspnetcore/tests/apis/Scalar.AspNetCore.Tests.Api/Scalar.AspNetCore.Tests.Api.csproj

With this PR, I simplified the `.editorconfig` and ran a format & cleanup profile to apply the latest ruleset.

chore(Scalar.AspNetCore): code formatting

---

integrations/django-ninja/scalar_django_ninja/scalar_django_ninja.py
integrations/fastapi/scalar_fastapi/scalar_fastapi.py
integrations/nextjs/src/custom-theme.ts
integrations/sveltekit/src/custom-theme.ts

Some theme vars escaped previous migrations. This should finalize them.

feat(themes): migrate remaining theme vars that were not caught

---

.changeset/fluffy-cows-explain.md
packages/api-client/src/views/Request/consts/mediaTypes.ts

feat(api-client): add support `application/dns-json` media type

---

package.json

Some scripts were left over, but are broken now. Let’s remove them.

chore: remove unused scripts

---

.changeset/tame-candles-joke.md
packages/api-client/src/views/Request/RequestSection/RequestTable.vue

Just adds some labels to the code inputs.
**Checklist**

fix(api-client): add aria label to request table code inputs

---

.changeset/empty-plants-own.md

I chose the wrong package in the changeset. This PR updated the package reference in the changeset.

docs(Scalar.AspNetCore): update changeset

---

.changeset/curvy-bikes-knock.md
.changeset/serious-kiwis-grab.md
packages/api-reference/src/components/Content/Lazy/Loading.vue
packages/api-reference/src/components/Sidebar/Sidebar.vue
packages/api-reference/src/features/Operation/layouts/ClassicLayout.vue
packages/api-reference/src/features/Operation/layouts/ModernLayout.vue
packages/api-reference/src/helpers/scroll-to-id.test.ts
packages/api-reference/src/helpers/scroll-to-id.ts
packages/code-highlight/src/css/markdown.css
packages/components/src/components/ScalarMarkdown/ScalarMarkdown.test.ts
packages/components/src/components/ScalarMarkdown/ScalarMarkdown.vue

**Problem**
currently using heading within tag markdown description is not adding id which prevent from sharing a link pointing to specific element. also sharing description section url is not redirecting to the heading.
**Solution**
this pr is a proposal to generate id to markdown heading id along fixing the scroll to id logic to get to the specific element on url share. fixes #5768
**Test file**
<details>
<summary>OpenAPI Specification</summary>
```yaml
openapi: 3.1.1
info:
title: Scalar Galaxy
description: |
The Scalar Galaxy is an example OpenAPI specification to test OpenAPI tools and libraries. It’s a fictional universe with fictional planets and fictional data. Get all the data for [all planets](#tag/planets/GET/planets).
* https://github.com/scalar/scalar
* …
```

feat(api-reference): markdown heading id

---

.changeset/wise-seahorses-work.md
packages/api-reference/tailwind.config.ts

Just working on lowering our average PR size 🫡 
**Checklist**

chore(api-reference): delete rogue Tailwind v3 config

---

.changeset/chatty-houses-hug.md
packages/api-client/src/libs/string-template.test.ts
packages/api-client/src/libs/string-template.ts

**Problem**
currently when a path parameter doesn't have a value its template is not getting displayed in the example.
**Solution**
this pr updates the string template file to have template substitution in empty value case. fixes #5764 
| <img width="1116" alt="image" src="https://github.com/user-attachments/assets/b2f88a2a-d7f2-46ae-a1a2-cfcc94df058f" /> | <img width="1116" alt="image" src="https://github.com/user-attachments/assets/96854dd0-eead-478d-a5c6-3a795a6108a7" /> |
| variable missing from path | variable displayed in path | 
**Tests**
<details>
<summary>Open API spec document</summary>
```yaml
openapi: 3.1.1
info:
title: Scalar Galaxy
description: |
The Scalar Galaxy is an example OpenAPI specification to test OpenAPI tools and libraries. …
```

fix(api-client): path parameters template for empty value

---

.changeset/light-pets-share.md

docs(changeset): Flatten layouts and add workspace store

---

.changeset/young-bags-crash.md
packages/api-reference/src/components/ApiReferenceLayout.vue

Removes header from classic layout

fix(api-reference): remove header for classic mobile

---

.changeset/happy-radios-relax.md
integrations/aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarEndpointRouteBuilderExtensions.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarOptionsExtensions.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Options/ScalarOptions.cs

This PR updates some XML comments to be more understandable and consistent.
**Checklist**

docs(Scalar.AspNetCore): improve xml comments

---

.changeset/little-walls-promise.md
integrations/fastify/package.json
integrations/nextjs/package.json
integrations/sveltekit/package.json
pnpm-lock.yaml

chore: remove unused dependencies

---

.changeset/long-toys-remain.md
biome.json
packages/api-reference/src/components/ApiReference.vue
packages/api-reference/src/hooks/useMultipleDocuments.ts
packages/api-reference/src/v2/ApiReferenceWorkspace.vue
packages/build-tooling/src/helpers.ts
packages/workspace-store/src/client.test.ts
packages/workspace-store/src/client.ts
packages/workspace-store/src/schemas/server-workspace.ts

Shifts state between components.

feat(api-reference): Re-organize workspace initialization

---

integrations/aspnetcore/playground/Scalar.AspNetCore.Benchmarks/Scalar.AspNetCore.Benchmarks.csproj
integrations/aspnetcore/tests/Directory.Packages.props

Monthly .NET update 🚀 
**Checklist**

chore(Scalar.AspNetCore): update dependencies

---

documentation/guides/api/getting-started.md
documentation/guides/registry/cli.md
documentation/guides/registry/dashboard.md
documentation/guides/registry/getting-started.md
documentation/guides/registry/github-workflows.md
documentation/guides/sdks/getting-started.md
scalar.config.json

**Problem**
Currently we have no registry docs!
**Solution**
With this PR we got a foundation of dashboard + cli docs for our registry!
**Checklist**

feat: add registry docs :)

---

.changeset/big-bottles-poke.md
packages/api-client/src/libs/send-request/create-request-operation.test.ts
packages/api-client/src/libs/send-request/create-request-operation.ts

fix(api-client): safely create a new response when there is no content

---

scalar.config.json

feat: add scalar api reference to docs 👀

---

.changeset/olive-waves-share.md
packages/workspace-store/src/server.test.ts
packages/workspace-store/src/server.ts

With this PR we correctly reference the chunks
**Checklist**

fix(workspace-store): relative paths for ssg mode

---

scalar.config.json

fix: up scalar config for more readable sidebar

---

.changeset/thick-snakes-marry.md
.github/workflows/ci.yml
integrations/docker/.gitignore
integrations/docker/Dockerfile

This PR updates the docker CI:
- use blacksmith actions
- improve the vulnerability scan
- remove unknown input fields
**Checklist**

feat(docker-ci): switch to blacksmith action

---

.changeset/warm-emus-jump.md
documentation/integrations/aspire.md
integrations/aspire/playground/Scalar.Aspire.AppHost/Scalar.Aspire.AppHost.csproj
integrations/aspire/src/Scalar.Aspire/Options/ScalarOptions.cs
integrations/aspire/src/Scalar.Aspire/ScalarHook.cs
integrations/aspire/tests/Scalar.Aspire.Tests/Extensions/ScalarOptionsExtensionsTests.cs
integrations/aspire/tests/Scalar.Aspire.Tests/ScalarOptionsMapperTests.cs
integrations/aspire/tests/Scalar.Aspire.Tests/ScalarTestOptions.cs

This PR updates the following for the `Scalar.Aspire` integration:
- makes the `ScalarOptions` abstract
- updates dependencies
- improves the docs
**Checklist**

chore(Scalar.Aspire): minor improvements

---

documentation/integrations/nestjs.md

**Problem**
Currently, …
**Solution**
With this PR …
**Checklist**

docs: add example for fastify adapter in nestjs

---

documentation/guides/docs/components/buttons.md
documentation/guides/docs/components/callouts.md
documentation/guides/docs/components/code-blocks.md
documentation/guides/docs/components/embeds.md
documentation/guides/docs/components/images.md
documentation/guides/docs/components/markdown-support.md
documentation/guides/docs/components/math.md
documentation/guides/docs/components/steps.md
documentation/guides/docs/components/tabs.md
scalar.config.json

**Problem**
Currently we have no documentation on our components!
**Solution**
With this PR we now have some : )
**Checklist**

feat: foundation documentation on our components

---

.changeset/mighty-news-sing.md
.changeset/purple-frogs-buy.md
.changeset/small-pots-battle.md
packages/galaxy/src/documents/3.1.yaml

Adds a few more features to the Scalar Galaxy example. :)

feat(galaxy): exclusiveMinimum, exclusiveMaximum, additionalProperties, x-enum-varnames, x-enum-descriptions

---

CODEOWNERS

Renovate + @xC0dex = ❤️
**Checklist**

chore(CODEOWNERS): add code owner for renovate

---

packages/oas-utils/src/transforms/import-spec.ts

chore: remove unused console.log

---

documentation/guides/access.md

**Problem**
fix a typo
**Checklist**

fix: typo in docs

---

documentation/guides/docs/components/images.md
documentation/guides/docs/components/tabs.md

**Changes**
this pr updates some documentation component content to match current usage, to be updated accordingly given in progress work on rendering.
**Checklist**

fix(documentation): updates guides components

---

.changeset/perfect-falcons-fail.md
integrations/sveltekit/src/scalar-api-reference.ts

**Problem**
Currently, …
**Solution**
With this PR …
**Checklist**

feat(sveltekit): set default _integration to svelte

---

.changeset/chilly-dogs-carry.md
packages/api-reference/src/blocks/hooks/useBlockProps.test.ts
packages/api-reference/src/blocks/hooks/useBlockProps.ts
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/Content/Content.vue
packages/api-reference/src/features/Operation/Operation.vue
packages/api-reference/src/features/Operation/components/callbacks/Callback.vue
packages/api-reference/src/features/Operation/components/callbacks/Callbacks.vue
packages/api-reference/src/features/Operation/layouts/ClassicLayout.vue
packages/api-reference/src/features/Operation/layouts/ModernLayout.vue
packages/api-reference/src/features/example-request/ExamplePicker.vue
packages/api-reference/src/features/example-request/ExampleRequest.vue
packages/api-reference/src/features/example-request/TextSelect.vue
packages/api-reference/src/features/example-request/index.ts
packages/api-reference/src/features/example-responses/ExampleResponses.test.ts
packages/api-reference/src/features/example-responses/ExampleResponses.vue
packages/api-reference/src/features/test-request-button/TestRequestButton.test.ts
packages/api-reference/src/features/test-request-button/TestRequestButton.vue
packages/api-reference/src/index.ts
packages/api-reference/src/v2/ApiReferenceWorkspace.vue
packages/api-reference/src/v2/blocks/scalar-request-example-block/components/RequestExample.vue

**Problem**
revert of https://github.com/scalar/scalar/pull/6218
Currently, workspace store is broke
**Solution**
With this PR we rollback the integration of it
**Checklist**

fix(api-reference): rollback store

---

.changeset/tough-needles-film.md
packages/api-reference/src/components/Content/ClientLibraries/ClientLibraries.vue
packages/api-reference/src/components/Content/ClientLibraries/ClientSelector.vue
packages/api-reference/src/features/example-responses/ExampleResponseTab.vue
packages/api-reference/src/features/example-responses/ExampleResponses.vue

Reverts scalar/scalar#6302
Needs some tweaks

revert(api-reference): updates client libraries card

---

.changeset/tidy-parents-search.md
packages/api-reference/src/components/Content/ClientLibraries/ClientSelector.vue

This is @antlio's PR #6302 but without the style changes which were breaking at small screen sizes.
**Checklist**

feat(api-reference): add combobox to client libraries card

---

.changeset/tiny-horses-fail.md
packages/api-reference/src/features/Operation/Operation.test.ts
packages/api-reference/src/features/Operation/Operation.vue
packages/api-reference/src/features/Operation/layouts/ClassicLayout.vue
packages/api-reference/src/features/Operation/layouts/ModernLayout.vue
packages/api-reference/src/helpers/test-utils.ts
packages/workspace-store/src/schemas/v3.1/type-guard.ts

**Problem**
Currently, we do not show path parameters.
**Solution**
With this PR we combine path parameters with parameters.
Tests inc...
**Checklist**

fix(api-reference): path parameters missing from operation

---

.changeset/olive-dolls-rush.md
packages/api-reference/src/features/example-responses/ExampleResponses.vue

This one was at least an easy fix
**Checklist**

fix(api-reference): center show schema checkmark

---

.github/renovate.json
biome.json

This PR adds a comprehensive Renovate configuration that fits our needs!
**What changed**
- Separate PRs for each package/integration
- Grouping patch and minor dependencies (per package/integration)
- Grouping major dependencies (per package/integration)
- Disable some dependencies that we will update manually anyway
**Preview**
Checkout https://github.com/xC0dex/scalar/issues/1
**Checklist**

chore(renovate): enhance configuration

---

packages/api-reference/index.html

[Don't think this was meant to be committed?
](https://github.com/scalar/scalar/pull/6282#discussion_r2231627295)
**Checklist**

revert(api-reference): remove hiddenClients: true from references dev env

---

.github/renovate.json

This PR assigns the king to all security-related pull requests.
**Checklist**

ci(renovate): add hans as assignee for vulnerability alerts

---

.changeset/tall-frogs-talk.md
integrations/nuxt/src/module.ts

**Problem**
clsoes #6367
Currently, the commonjs issue came back.
**Solution**
With this PR I uncommented the fix
**Checklist**

fix(nuxt): CommonJS issues

---

packages/react-renderer/package.json
packages/scripts/package.json
packages/themes/package.json
packages/use-tooltip/package.json
pnpm-lock.yaml

Just tidies up the build scripts.

chore(repo): unify all package build scripts to build tooling

---

.changeset/hungry-tables-rescue.md
packages/build-tooling/package.json
packages/build-tooling/scripts/build-esbuild.js
packages/build-tooling/scripts/build-rollup.js
packages/build-tooling/scripts/build-vite.js
packages/build-tooling/scripts/build-vite.ts
packages/build-tooling/scripts/format-check.js
packages/build-tooling/scripts/format.js
packages/build-tooling/scripts/lint-check.js
packages/build-tooling/scripts/lint-fix.js
packages/build-tooling/scripts/types-build-vue.js
packages/build-tooling/scripts/types-build.js
packages/build-tooling/scripts/types-check-vue.js
packages/build-tooling/scripts/types-check.js
packages/build-tooling/scripts/utils/utils.js

Prevents downstream vite configs from impacting the shell script execution.

feat(build-tooling): Migrate bin scripts to .js. They should be dep free

---

integrations/aspire/.config/dotnet-tools.json
integrations/aspire/playground/Scalar.Aspire.AppHost/.aspire/settings.json
integrations/aspire/playground/Scalar.Aspire.AppHost/Program.cs
integrations/aspire/playground/Scalar.Aspire.AppHost/Scalar.Aspire.AppHost.csproj
integrations/aspire/playground/Scalar.Aspire.UserService/Dockerfile
integrations/aspire/playground/Scalar.Aspire.UserService/index.js
integrations/aspire/playground/Scalar.Aspire.UserService/package.json
pnpm-lock.yaml

This PR improves the .NET Aspire playground by removing Fastify dependencies enabling support for publishing the playground.
**Checklist**
Waits for https://github.com/scalar/scalar/pull/6547

chore(Scalar.Aspire): enhance playground with aspire publish

---

packages/nextjs-openapi/README.md

**Problem**
Currently, …
**Solution**
With this PR …
**Checklist**

docs(nextjs-openapi): fix example

---

integrations/aspnetcore/src/Directory.Build.props
integrations/aspnetcore/src/Scalar.AspNetCore.Microsoft/README.md
integrations/aspnetcore/src/Scalar.AspNetCore.Microsoft/Scalar.AspNetCore.Microsoft.csproj
integrations/aspnetcore/src/Scalar.AspNetCore.Swashbuckle/README.md
integrations/aspnetcore/src/Scalar.AspNetCore.Swashbuckle/Scalar.AspNetCore.Swashbuckle.csproj
integrations/aspnetcore/src/Scalar.AspNetCore/Scalar.AspNetCore.csproj

This PR improves the documentation for our .NET extension packages by adding dedicated READMEs for each package.
**Checklist**

docs(Scalar.AspNetCore): custom readme for extensions

---

.changeset/nice-beers-beg.md
packages/api-client/src/views/Request/RequestSection/RequestAuth/OAuthScopesInput.vue
packages/api-reference/src/components/Content/Models/Models.test.ts
packages/api-reference/src/components/Section/CompactSection.vue

**Problem**
Currently, the models are opening by default.
**Solution**
With this PR we fix the typo causing this.
**Checklist**

fix(api-reference): models opening by default

---

documentation/guides/introduction.md
documentation/guides/pricing.md
scalar.config.json

Pricing page for docs :) 
let's review this @marclave

feat(documentation): add pricing page

---

documentation/guides/introduction.md
documentation/guides/pricing.md

feat(documentation): add links to hover stickers

---

.changeset/neat-lizards-agree.md
packages/api-reference/src/components/Content/Content.vue

fix(api-reference): remove extra padding on intro card

---

packages/analytics-client/src/events.ts

**Problem**
Currently the event payload for the page-view event is out of date.
**Solution**
With this PR the payload will be up to date
**Checklist**

chore(analytics): Update page-view event data

---

integrations/nextjs/package.json
pnpm-lock.yaml
pnpm-workspace.yaml

security update
see  #6702 and #6703 for further details

chore(next): update to Next.js 15.4.7

---

.github/workflows/ci.yml

Makes snapshots run on workflow dispatch

chore: move snapshots to run on workflow dispatch

---

integrations/aspnetcore/playground/Scalar.AspNetCore.Playground/Extensions/ServiceCollectionExtensions.cs

Just one thing I noticed. 
**Checklist**

chore(Scalar.AspNetCore): add security requirement for playground spec
