scalar/scalar

.changeset/nervous-parents-burn.md
packages/docusaurus/src/theme.css

Scopes the Docusaurus theme styles so they don't spill out of the references.
Fixes #2447

fix(docusaurus): scope docusaurus theme styles

---

.changeset/clean-papayas-call.md
packages/api-client/src/views/Request/RequestSection/RequestTable.vue

this pr fixes #2467 and checked here by default only required item.

fix(api-client): input checked by default if required

---

.changeset/small-lamps-sip.md
packages/api-reference/src/components/Content/Tag/Tag.vue

**Problem**
Currently in the docs we lose reactivity for the show more button
This happens because onMounted post parsedSpec
**Solution**
With this PR we make it a computed property just incase : )

fix: make default tag check computed for reactivity bugs

---

.changeset/lucky-candles-give.md
packages/api-client/src/components/CodeInput/CodeInput.vue

fix(client-app): codemirror bg color

---

.changeset/twelve-keys-push.md
packages/components/src/components/ScalarModal/ScalarModal.vue

can make it better later but marc-gpt css has been implemented
before:
after:

fix: add max height to search modal

---

.changeset/late-keys-push.md
packages/api-client/src/views/Request/RequestSection/RequestBody.vue

**Problem**
Currently, when I test a request and the content type of the body is JSON, changing the content type of the body to others, such as multipart/form-data, does not update the activeBody. This results in the body remaining as JSON when the request is sent.
**Solution**
With this PR, I have added a function to update the activeBody when the content type changes.
This is my second contribution. If there's anything else, you can let me know. 😅

fix(api-client): update active body when content type changes

---

.changeset/quiet-gorillas-float.md
packages/api-client/src/libs/sendRequest.ts

**Problem**
Currently we always send the body on http requests
This happens because we dont do any null checks
**Solution**
With this PR we null check and only add it the body is not null

fix: only add body data if body data is not null

---

.github/workflows/ci.yml

I noticed that the Turborepo cache is (still) not leveraged properly. We’re doing the build and then pick up the cache in other jobs, just to still see a high cache miss rate. Note how the type check and others are still taking forever:
So I’ve checked the logs and noticed this one in the Post Cache step:
> Cache hit occurred on the primary key turbo-Linux-node-20, not saving cache.
So … it found the cache and decided to not update the cache. This is not what we want. :)
With this PR the cache should be updated after the full build.
For a full-rebuild it looks like this now (notice how the type check and others are way faster):
Because build time is down to 0-1s in those jobs:

ci: update turborepo cache after build

---

.changeset/config.json
packages/api-client-app/package.json

This release workflow failed:
> npm error 403 403 Forbidden - PUT https://registry.npmjs.org/scalar-api-client - You may not perform that action with these credentials.
Looks like it tried to publish the scalar-api-client. Let’s set it to private and ignore it for changesets.

chore: do not release scalar-api-client

---

.changeset/wise-ants-rescue.md
packages/themes/src/reset.css

This is _probably_ what this should be otherwise we sometimes get unexpected behaviour where the font size reverts to the browser default of 16px on certain elements.
I checked and I don't think this should break anything.

fix(themes): switch from font-size unset to inherit

---

examples/fastify-api-reference/src/index.ts

**Problem**
Currently, when I try using the example from the `fastify-api-reference` and send a request, I don't get anything because it doesn't return a response and the API request remains pending.
**Solution**
With this PR, I ensure the API responds correctly.

fix: add reply response in fastify-api-reference example.

---

.changeset/silver-seahorses-shave.md
documentation/configuration.md
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/Sidebar/Sidebar.vue
packages/api-reference/src/hooks/useSidebar.test.ts
packages/api-reference/src/hooks/useSidebar.ts
packages/api-reference/src/types.ts

This PR adds an option to sort the tags, this makes switching from Swagger UI to Scalar even easier:
**Notes**
* Custom functions can’t be passed when `JSON.stringify` is used to pass the configuration.
* Models & Webhooks aren’t in that list.
* Tag groups aren’t sorted aswell, but I think you can just define them in the order that you like.
**Relevant links**
* #1436 
* https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/#:~:text=values%20for%20Parameters.-,tagsSorter,-Unavailable

feat(api-reference): add `tagsSorter` to the configuration, fix #1436

---

.changeset/four-emus-pull.md
packages/api-reference/src/helpers/getModels.ts
packages/api-reference/src/hooks/useSidebar.test.ts

We hide operations and webhooks with `x-internal: true`, but we don't hide schemas. With this PR schemas/models with `x-internal: true` are hidden, too.
See #2468

feat(api-reference): hide schemas with `x-internal: true`, fix #2468

---

.changeset/lemon-pillows-bathe.md
packages/api-client/src/components/CommandPalette/CommandPalette.vue

fix: adjust command palette icon thickness

---

.changeset/six-laws-attack.md
.changeset/soft-rules-float.md
packages/mock-server/src/createMockServer.ts
packages/mock-server/src/utils/anyOpenAuthPasswordGrantAuthentication.ts
packages/mock-server/src/utils/getOpenAuthTokenUrl.ts
packages/mock-server/src/utils/isOpenAuthPasswordGrantRequired.ts
packages/mock-server/tests/basicAuthentication.test.ts
packages/mock-server/tests/oAuthPasswordGrant.test.ts

With this PR, the `@scalar/mock-server` adds an OpenAuth2 token endpoint and requires the OpenAuth2 password grant authentication if it’s required in the given OpenAPI document.
* Currently, the token endpoint doesn’t care what data you send, as long as it's a POST request.
* And the authentication checks for the `Authentication: Bearer ***` header and doesn’t care about the given token.
I kept it simple for this PR, but this can be further improved by adding support for other OpenAuth workflows, or by being a little bit more strict in the token endpoint (at least requiring the necessary parameters).

feat(mock-server): check OpenAuth2 password grant authentication is required

---

.changeset/tidy-peas-call.md
packages/api-reference/src/components/ApiReference.vue

Sets the background color on the `<body>` tag in a layer so it's set for iOS. It turns out this also colors the address bar in addition to the top chrome which is nice.
Since it's in a layer it _should_ be easy to override if anyone doesn't want it set for their use.
Fixes #2496

fix(api-reference): set background color on body, fix #2496

---

.changeset/pink-dots-march.md
packages/api-reference-react/package.json
packages/docusaurus/package.json
packages/nextjs-api-reference/package.json
pnpm-lock.yaml

As correctly stated in https://github.com/scalar/scalar/issues/2482#issuecomment-2231993359, React and Nextjs should be peer dependencies.
Means, they have to be installed, but we don’t care about the exact version as long as it’s in the React 18.* or Next 14.* range.
See #2482 for more context on why it’s probably fixing the issue.

chore: make react a peer dependency, fix #2482

---

.changeset/calm-kids-fail.md
packages/api-reference-react/vite.config.ts
packages/nextjs-api-reference/vite.config.ts

With #2518 we moved `react` and `next` to the peer dependencies. The build configuration excludes all dependencies from the bundle, but not the peer dependencies. This would have led to version conflicts because we were about to ship a specific React version to users.
With this PR, we’re also excluding peer dependencies for the relevant packages. This way, users won’t run into React/Next.js version conflicts.

chore: exclude peer dependencies to avoid React version conflicts

---

README.md

Oops, we merged the release and ci workflows, but I forgot to remove the release badge. 🙈

docs: remove dead badge

---

.changeset/cuddly-meals-enjoy.md
packages/api-client/package.json
packages/api-client/src/components/CommandPalette/TheCommandPalette.vue
packages/api-client/src/components/CommandPalette/index.ts
packages/api-client/src/layouts/App/ApiClientApp.vue
packages/api-client/src/libs/eventBusses/command-palette.ts
packages/api-client/src/views/Request/Request.vue
packages/api-client/src/views/Request/components/WorkspaceDropdown.vue

Need some QA but I believe this should do it. Now we can trigger the command palette from anywhere. Should be trivial to add the hotkey opening as well!
- also leaned more towards type inference instead of setting types
- switched the event bus event to be an object so we can pass metadata in the future (pre-select request etc)

feat: moved command palette to the client app base

---

.changeset/modern-goats-jump.md
packages/api-client/playground/app/main.ts
packages/api-client/src/components/CodeInput/codeVariableWidget.ts
packages/api-client/src/components/CommandPalette/CommandPaletteExample.vue
packages/api-client/src/components/CommandPalette/TheCommandPalette.vue
packages/api-client/src/components/SideNav/SideNav.vue
packages/api-client/src/libs/eventBusses/command-palette.ts
packages/api-client/src/router.ts
packages/api-client/src/store/workspace.ts
packages/api-client/src/views/Request/RequestSidebarItem.vue
packages/api-client/src/views/Request/RequestSidebarItemMenu.vue

Made requests functional. We still have the double enter problem but I will leave that for another PR.
- fixed the phantom galaxy workspace
- built out the request example command palette
- added add and delete for examples and requests
- added routing for examples
- switched back to routerLink instead of @click handler on sidebar

feat(doc-2064): make examples functional in api client

---

.changeset/weak-swans-serve.md
packages/build-tooling/src/vite-options.ts

The public dir is not functioning as expected because rollup is re-deleting the dist directory. Need to disable the dist deletion for vite builds.

chore(build-tooling): public/ folder is emptied for all Vite builds

---

.changeset/strong-eels-greet.md
packages/use-codemirror/src/hooks/useCodeMirror.ts

Codemirror has stopped recognizing newlines with enter key.

fix(use-codemirror): enter doesn’t create a new line

---

.github/workflows/ci.yml

Add permissions for publishing to npm. Documentation [here](https://docs.npmjs.com/generating-provenance-statements#example-github-actions-workflow)

fix: release workflow permissions

---

.changeset/giant-chefs-argue.md
packages/api-client/src/layouts/Modal/api-client-modal.ts

Currently, we log an error when no OpenAPI document is passed to the API client modal.
This PR just creates an empty workspace instead. :)
See #2555

feat(api-client): create a default workspace if no OpenAPI document is passed to the modal

---

.changeset/tall-bobcats-develop.md
packages/api-client/src/components/AddressBar/AddressBarHistory.vue
packages/api-client/src/views/Request/Request.vue

we properly use a mutator to store in localstorage
we properly navigate to historical requests

fix(api-client): can’t navigate to request history entry

---

.changeset/gentle-frogs-doubt.md
packages/components/src/components/ScalarModal/ScalarModal.vue

**before**
was stuck to the bottom
**after :)**

fix(api-client): search modal isn’t centered

---

packages/api-client/src/views/Request/RequestSidebarItemMenu.vue

**Problem**
Currently, when you click `...` twice  it reloads the page
This happens because of a click.stop headless recursive event
**Solution**
With this PR we just dont click.stop

fix(api-client): remove click.stop page refresh action item

---

.changeset/small-pots-relate.md
packages/docusaurus/package.json
packages/docusaurus/postcss.config.mjs
pnpm-lock.yaml

Should fix the Docusaurus build issues. I'm not sure if this is how we like postcss set up though, hoping @amritk or @hanspagel can confirm this is good (vs setting up Vite or something).

fix(docusaurus): build docusaurus theme css with postcss

---

packages/hono-api-reference/README.md

This PR updates the README.md in `hono-api-reference` to correct the import.

docs: update import to @scalar/hono-api-reference 

---

.changeset/shiny-trees-hunt.md
packages/oas-utils/src/transforms/import-spec.ts

Currently we use a default of localhost, but this breaks for our opensource integrations that rely on the servers origin to fallback to for the server, now we default to the origin the server is hosted on! we might want to eventually do something different for the Scalar App where we actually _dont_ have a server populated if theres no server, and have an empty varible in an error state so the user can update it : )
but that can be a future thing

fix: latest changes broke testing base url

---

.changeset/rotten-camels-taste.md
packages/api-client/src/components/CodeInput/CodeInput.vue

this is actually a spooky bug, cause we were always triggering an onChange on first load for all inputs.
now we only trigger if its actually different!

fix: activate query params by default only if required

---

.changeset/witty-hats-compete.md
packages/api-client/src/views/Request/RequestSection/RequestBody.vue

**Problem**
Currently we don't save the raw encoding value and if you change we dont properly set the content-type
This happens because we dont handle it
**Solution**
With this PR we save both the raw encoding value and set the Content-Type header depending on the content type
https://github.com/user-attachments/assets/771c273a-e29c-496d-9a79-ba9e9bf2a000

fix(api-client): all request bodies are sent as form data, fix #2511

---

.changeset/sixty-items-add.md
packages/api-reference/src/components/Content/Operation/OperationAccordion.vue

Just switched to using the thickness prop
Looks the same:
https://github.com/user-attachments/assets/246a58f0-d9b9-4c32-89fc-7163ae070cdc

chore(api-references): use thickness instead of css overrides

---

.changeset/ninety-birds-return.md
packages/api-client/src/views/Request/ResponseSection/ResponseBody.vue
packages/use-codemirror/src/hooks/useCodeMirror.ts

**Problem**
Currently HighlightJS freezes for large responses > 700KB. https://github.com/scalar/scalar/issues/2503
Codemirror does a great job w large files + virtualization, so lets remove Highlight.js for the API Client Responses
In this PR I also remove "preview" mode, since it needs to be re-thought out :)

fix: remove ScalarCodeBlock that freezes browser in response preview

---

.changeset/three-spoons-grin.md
packages/api-client/src/components/HttpMethod/HttpMethod.vue

collision in gitbook that should be fixed now: 
before:
after:

fix: whitespace http method

---

.changeset/seven-schools-jump.md
packages/api-client/src/components/CodeInput/CodeInput.vue

was driving me 🫨 
before:
https://github.com/user-attachments/assets/45cc2c00-2438-405a-9a37-e087e4f2eec5
after:
https://github.com/user-attachments/assets/272e8612-1577-4a3d-bde2-aef690cb3e25

fix: remove trailing whitespace codemirror env pill

---

.changeset/heavy-flowers-tan.md
packages/void-server/package.json
packages/void-server/src/utils/getBody.ts
pnpm-lock.yaml

The recent `@scalar/void-server` can’t be deployed to Cloudflare. We recently introduced `undici` as a dependency, but this requires a lot of Node APIs (`string_decoder`, `node:assert`), and this makes trouble on CF. :)
This PR tries to get rid of undici. Hopefully, this helps.

chore(void-server): remove unidici from void server

---

.changeset/smooth-chairs-kneel.md
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/galaxy/src/specifications/3.1.yaml

Make sure the section is expanded so we can scroll to it on hash change. Also adds some internal links to the Scalar Galaxy description.
Fixes #2603
https://github.com/user-attachments/assets/2309ab56-b83c-48db-8f02-e510782c557f
https://github.com/user-attachments/assets/574b62a1-82d4-4a24-890e-938c65a9ad74

fix(api-reference): allow scrolling to collapsed sections via hash

---

.changeset/early-clouds-share.md
packages/api-client/src/layouts/Modal/ApiClientModal.vue

with the addition of the "scalar-app" class to headless ui we needed to remove layout code that was being written on 'scalar-app'

fix: remove layout code from scalar-app

---

.changeset/stale-ravens-dress.md
packages/api-client-app/src/main/index.ts
packages/api-client-app/src/renderer/index.html

The toDesktop static analysis pointed out a security issue, this PR tries to fix it.
More context: https://www.todesktop.com/static-analysis/permission-request-handler-global-check
> You may have seen permission requests while using Chrome: they pop up whenever the website attempts to use a feature that the user has to manually approve (like notifications).
> …
> By default, Electron will automatically approve all permission requests unless the developer has manually configured a custom handler. 
Source: https://www.electronjs.org/docs/latest/tutorial/security#5-handle-session-permission-requests-from-remote-content
Note: I use the opportunity to also simplify the CSP header (shouldn't change what it does). We need to add `connect-src: *` to allow requests to all hosts.

chore(api-client-app): block all permission requests

---

.changeset/grumpy-dogs-reply.md
packages/api-reference/src/hooks/useReactiveSpec.ts

I’m debugging the performance and thought it would be cool to have a few key metrics in the console. We already had something for the dereferencing, this PR adds some metrics about the OpenAPI document fetching.
Open the browser console to see it.
```bash
fetch: 1552 ms (https://sandbox.scalar.com/files/korOI/openapi.yaml)
size: 621 kB
dereference: 181 ms
```

feat(api-reference): performance logging

---

.changeset/hot-timers-cough.md
packages/void-server/src/utils/getBody.ts

I have still trouble with the import from `node:buffer`, so let’s try to remove it entirely.
I think, comparing `myObject instanceof myClass` is basically comparing if it has the same attributes, so we can also just do this manually.
This should make it easier to deploy `@scalar/void-server`.

chore(void-server): remove `node:buffer` import

---

.changeset/neat-beds-guess.md
packages/api-client/src/libs/create-client.ts

closes #2634
We had defaulted the proxy to the scalar one with no way to disable. This allows users to disable it

fix(#2634): remove default proxy

---

.changeset/real-ways-dance.md
packages/api-client/src/hooks/useDarkModeState.ts
packages/api-reference/src/hooks/useDarkModeState.ts

I saw an exception in jsdom, which doesn’t have the matchMedia API:
```bash
TypeError: window?.matchMedia is not a function
❯ getDarkModeState src/hooks/useDarkModeState.ts:23:15
21|     if (
22|       typeof window !== 'undefined' &&
23|       window?.matchMedia('(prefers-color-scheme: dark)')?.matches
|               ^
24|     ) {
25|       return true
```
This PR fixes it!

fix: matchMedia is not a function

---

.changeset/rotten-apes-explain.md
packages/api-client/src/layouts/App/create-api-client-app.ts
packages/api-client/src/layouts/Modal/api-client-modal.ts
packages/api-client/src/libs/create-client.ts
packages/api-reference/src/esm.ts

I was wondering why the configuration is required and thought about making it optional. With this PR you can just omit the configuration:
```diff
-await createApiClientModal(document.getElementById('app'), {})
+await createApiClientModal(document.getElementById('app'))
```

feat(api-client): make the configuration for `createApiClientApp` and `createApiClientModal` optional

---

.changeset/grumpy-spoons-attend.md
packages/api-client-app/package.json
packages/api-client-app/src/main/index.ts
pnpm-lock.yaml

With this PR the window size and position of the app is restored on load.
In case the window is placed outside the display (even if it’s just parts of it), for example when switching from a big to a small screen, it’s moved inside the viewport again.

feat(api-client-app): store window size and position

---

.changeset/rare-files-sparkle.md
packages/api-client-app/src/renderer/src/main.ts

We used to load the galaxy example on every app start. This was fine as long as we didn’t have persistence, but now it’s added again and again.
This PR fixes it, because it’s not added at all. :)
See #2627

fix: app adds galaxy example on every start, fix #2627

---

.github/workflows/ci.yml

With this PR a list of all published packages should be echo’d in CI, right after publishing.
I’m just testing if and how that works to eventually hook into the process to automate the release of our app.
Unfortunately, I couldn’t come up with another way to test it, then actually adding it to the workflow and waiting for the next release. Even if it has errors, it shouldn’t break the release workflow, because it comes *after* everything is published.

ci: output all published packages

---

.changeset/gentle-plants-cough.md
packages/components/src/components/ScalarIcon/icons/index.ts

This add a placeholder `<svg>` while the async component is loading to prevent layout shift.
I think by the nature of async components it needs to load them in anytime the view is mounted / unmounted, it doesn't send additional requests for the icons once they've been loaded in. Apparently the small amount of time it takes them to load from cache is enough to cause a flicker but this PR minimizes that flicker.
https://github.com/user-attachments/assets/52761105-03b7-498c-88e7-a37e84e41931

fix(components): provide a placeholder for icons while loading

---

.changeset/proud-tips-listen.md
packages/components/src/components/ScalarCombobox/ScalarCombobox.stories.ts
packages/components/src/components/ScalarCombobox/ScalarCombobox.vue
packages/components/src/components/ScalarCombobox/ScalarComboboxMultiselect.vue
packages/components/src/components/ScalarCombobox/ScalarComboboxOptions.vue
packages/components/src/components/ScalarCombobox/ScalarComboboxPopover.vue
packages/components/src/components/ScalarCombobox/index.ts
packages/components/src/index.ts

Multiselect combobox as requested by @amritk. I split it into two components to make it easier to have correct types for the `v-model` props (I think we need to do this for `ScalarListbox` too at some point).
I also made the combobox open when you press the up or down arrows while the target / button is focused (this is what the HeadlessUI combobox does). 
https://github.com/user-attachments/assets/aad92afd-89de-41de-be33-141cb15a728d

feat(components): add multiselect combobox

---

.changeset/cold-birds-doubt.md
.changeset/eleven-teachers-appear.md
.changeset/weak-books-give.md
packages/mock-server/package.json
packages/mock-server/src/createMockServer.test.ts
packages/mock-server/src/createMockServer.ts
packages/mock-server/src/utils/findPreferredResponseKey.test.ts
packages/mock-server/src/utils/findPreferredResponseKey.ts
pnpm-lock.yaml

This PR adds three great features to `@scalar/mock-server`:
**Headers**
Adds headers (defined in the OpenAPI document) to the mocked response.
**Redirects**
You can now define a redirect (`Location` header and status code 30*)
**Content types**
No matter what content type is given, it tries to pick the appropriate content type (based on the `Accept` header, falls back to JSON or what’s available). Even works with XML.

feat(mock-server): headers, redirects and all content types

---

.changeset/dirty-dodos-matter.md
.changeset/thick-boxes-marry.md
packages/mock-server/src/createMockServer.ts
packages/void-server/package.json
packages/void-server/tsconfig.build.json
packages/void-server/tsconfig.json

I tried to start the playground for the mock-server, but it failed. The root cause was the import from `./utils`. I couldn’t really figure out why, but I know that we’ve had circular references there a while ago. Though I didn’t saw a wrong import, I didn’t care enough to really find out what’s wrong (at least not today).
While debugging, I found a few tiny things that I’d like to improve.
Read the commit messages for more context. :)

chore(mock-server): clean up

---

packages/api-client-app/RELEASE.md

This PR adds a description of the manual release process for our app.
Yes, we’ll automate this eventually, but for now this is how it works. :)

docs(api-client-app): release process

---

packages/object-utils/src/mutator-record/mutations.test.ts

There is this one test that is failing every now and then, and it really bugs me to manually rerun the jobs. 😅
This PR makes sure the test is executed up to 3 times. Still better then disabling it I’d say, and it’s probably just a race condition or something anyway.

chore: retry flaky test

---

.github/workflows/ci.yml

Another attempt to just output all packages and check whether `scalar-api-client` was published (it’s never really published to npm, but I think it’s in the output and it would help to have access to that information).
Slowly working my way towards automating the app release process. 🤡

ci: output published packages

---

.github/workflows/ci.yml

In #2621 I’ve added a step to create PR comments, but that fails in `main` — because there’s no PR then. :)
This PR just skips the step in `main`.

ci: do not create PR comment in main

---

.github/actions/build/action.yml
.github/workflows/ci.yml

This PR introduces a composite action for the steps that are required to do a (full) build of the repository. A build (even if cached) is required for most jobs, so we’ve repeated the code over and over. But no more! This PR puts it into a single place.
Makes the CI workflow file smaller and a litte easier to grasp. :)
Read more: https://docs.github.com/en/actions/using-workflows/avoiding-duplication

ci: reusable composite actions

---

.changeset/strange-ears-clean.md
packages/api-client/src/components/CommandPalette/CommandPaletteFolder.vue

we now show only the collections to a workspace and default to the active collection

fix: add default active collection to folder create command

---

.changeset/wet-dolphins-poke.md
packages/api-client/src/libs/sendRequest.test.ts
packages/api-client/src/libs/sendRequest.ts

**Problem**
Currently, when I try to upload a file with form-data, the key is sent as the file name instead of the correct key.
**Solution**
With this PR, I ensure that the correct key is used instead of the file name when sending the request. Additionally, if both a file and a value are present, the file will be used for the request.

fix(api-client): upload file in form-data with key

---

.changeset/thin-garlics-jam.md
packages/oas-utils/src/transforms/import-spec.ts

we only used the parsedSpec for checking "servers" but we really dont need that at all, we should let our amazing openapi-parser handle all things loading of spec and we then use the result
this fixes a bug where if a yaml file has newlines, or wrapped in string characters that it fails to load 😨

fix: superfluous yaml or json parse before spec parsing

---

.changeset/empty-eagles-join.md
packages/api-client/src/components/SubpageHeader.vue

this pr fixes the back to requests redirection link to be effective when navigating from another workspace than default:

fix(client-app): back to requests redirection link

---

.changeset/serious-masks-press.md
packages/api-client/src/components/CommandPalette/TheCommandPalette.vue

this pr adds a first empty state to the client app command palette component:
https://github.com/user-attachments/assets/a5c9b67b-21f9-453d-a53a-4e5afc3fb4b1

feat(client-app): command palette empty state

---

.changeset/smooth-nails-sing.md
packages/oas-utils/src/transforms/import-spec.ts

I've done quite a lot of specs previously were the path of the request is just used as the default identifier, which makes the most sense to me if there is no summary. No need to add the type as a prefix/suffix since we already display it.
This is just a simple fallback so that the summary is set to something sensible rather than being empty or having the same default label for all requests.

feat: use pathstring when req summary isn't available

---

packages/scalar.aspnetcore/Scalar.AspNetCore.cs
packages/scalar.aspnetcore/Scalar.AspNetCore.csproj
packages/scalar.aspnetcore/ScalarOptions.cs

Addressing user feedback from https://github.com/scalar/scalar/pull/1737#issuecomment-2171906715.
Instead of exposing the `DataUrl` as a single string property, I've expsoed customization for it as a function that takes the document name as an argument.
Someone can configure the options like so:
```csharp
app.MapScalarApiReference(options =>
{
options.DataUrlFunc = (documentName) => $"/swagger/{documentName}.json";
});
```

feat: support customizing DataUrl via ScalarOptions

---

.changeset/seven-jars-thank.md
packages/use-codemirror/src/hooks/useCodeMirror.ts

this pr updates scalar/use-codemirror package in order to enable linting only on given content to avoid following behavior:

fix(use-codemirror): lint

---

.changeset/fifty-walls-cheer.md
packages/api-client-app/src/renderer/index.html

Turns out our electron app is a little more locked down than a browser so we have to whitelist displaying `blob:` sources (which is what we use to display response previews).

fix(api-client-app): allow blob: as source in Content-Security-Policy

---

documentation/configuration.md
documentation/integrations/nextjs.md

This PR changes the example theme configuration to a string and fix some typo.

docs: change example theme config to string and fix some typo.

---

.changeset/rare-pumas-help.md
packages/api-client/src/views/Request/RequestSection/RequestAuth.vue

this pr updates api client authentication counter logic + enhances select style as seen below:
**before**
**after**

fix(api-client): authentication UI

---

.changeset/purple-pugs-give.md
packages/api-client/src/views/Request/consts/mediaTypes.ts

**Problem**
Currently, `application/problem+json` responses are displayed as binary files.
This happens because it is not added to the list of supported media types.
**Solution**
With this PR I added it to the list of supported media types.

feat(api-client): added application/problem+json media type

---

.changeset/soft-clouds-cry.md
packages/void-server/src/utils/getBody.ts

I’ve seen this error in the release PR for Node 18:
```bash
FAIL  |@scalar/void-server| src/createVoidServer.test.ts > createVoidServer > returns multipart form data with multiple files
SyntaxError: Unexpected token I in JSON at position 0
```
Turns out, the code is still assuming we have the `File` class, which was only introduced in Node 20.
This PR should fix it, basically polyfilling it.

fix(void-server): file undefined

---

.github/workflows/ci.yml

This is a new attempt to detect when the app got a new version number, which we could eventually use to automate the release of it.
The old attempt relied on the output of the changeset action, but that was empty. :(
With this PR we’re checking whether the commit message starts with `RELEASING:` (generated by the changeset workflow),  and if the `package.json` of the app was touched.
This should only happen at the same time when the version is increased. :)

ci: check whether scalar-api-client has a new version number

---

.changeset/eleven-schools-learn.md
packages/api-client/src/views/Request/RequestSection/RequestAuth.vue

this pr updates the selected authentication style using pill and allows unselection action, following #2732 as seen below:
**before**
**after**

style(api-client): selected authentication

---

.changeset/twenty-jobs-cough.md
packages/api-client-app/src/main/index.ts
packages/api-client-app/src/renderer/src/main.ts
packages/api-client/src/libs/normalizeHeaders.test.ts
packages/api-client/src/libs/normalizeHeaders.ts
packages/api-client/src/libs/sendRequest.ts
packages/api-client/src/views/Request/ResponseSection/ResponseHeaders.vue

Currently, we’re using proxy.scalar.com to avoid CORS issues. This has some caveats:
* Local domains can’t be processed
* The traffic goes through a remote server that users might not want to trust (though it’s open source)
* It’s adds some overhead to the request
There are two obvious solutions to this, that I decided against:
**❌ Bundle our proxy with the Electron app and run it locally**
It could be error prone to compile, bundle and ship an additional executable, that then needs to occupy a port on the user’s machine.
There are a lot of limitations around cookies and other domains, so we’d never really be able to set cookies properly.
**❌ Execute requests in Node**
We could add a way to intercept requests and - instead of executing them in the frontend - execute them in a Node …

feat(api-client-app): don’t use the proxy, intercept requests instead

---

.changeset/beige-pumas-heal.md
packages/api-client/src/components/AddressBar/AddressBarHistory.vue
packages/themes/src/tailwind.ts

Fixes some of the layout issues with the address bar history and reverses the order so the most recent entry is at the top. 
There seems to be another bug where clicking a history item doesn't always mutate the address bar properly and that's still outstanding.

fix(api-client): rebuild address bar history with grid

---

.changeset/popular-rockets-wonder.md
packages/api-client/src/components/CommandPalette/TheCommandPalette.vue
packages/api-client/src/components/SubpageHeader.vue
packages/components/src/components/ScalarIcon/icons/ChevronLeft.svg

this pr updates the scalar icon chevron left element in order to fix position issue:
**before**
**after**

style(components): icon chevron left

---

.changeset/tender-gorillas-sparkle.md
packages/api-client/src/layouts/Modal/create-api-client-modal.ts
packages/api-client/src/libs/create-client.ts
packages/api-client/src/store/workspace.ts
packages/api-reference/index.html
packages/api-reference/src/components/ApiClientModal.vue
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/oas-utils/src/transforms/import-spec.ts

we allow for overrides of the servers in the references but we need to initialize the api client as well : )
this fixes https://github.com/scalar/scalar/issues/2761
```
servers: [
{
url: 'https://api.scalar.com',
description: 'Scalar API',
},
],
```
this now works

fix: add overload to servers as prop for create client app

---

.changeset/perfect-panthers-look.md
packages/api-client/src/components/Sidebar/SidebarListElementActions.vue

this pr adds missing event listener to be able to close the delete sidebar list element modal.

fix(api-client): delete sidebar list element

---

.changeset/ninety-beds-bathe.md
packages/docusaurus/src/index.ts

**Problem**
Currently, there is no way to disable the nav links generated by the docusaurus plugin.
**Solution**
With this PR users can now choose to enable/disable the nav link for any spec file they add to their docs.
Default will stay as `true` but users can now simply set `showNavLinks` to false to remove the nav link

feat(docusaurus): add showNavLink config option

---

.changeset/twenty-candles-jump.md
packages/api-reference/src/components/Content/Webhooks/Webhooks.vue

this pr fixes #2774 by adding anchor id reference in the section container.

fix(api-reference): webhooks section anchor, fix #2774

---

.changeset/sweet-clocks-speak.md
packages/api-client/src/views/Request/RequestSection/RequestAuth.vue

this pr updates the api client authentication combobox in order to only display select auth and filter out unselected ones, to avoid infinite list:

fix(api-client): authentication select

---

.changeset/weak-laws-yawn.md
packages/api-client/src/views/Request/RequestSection/RequestPathParams.vue

this pr is a proposal to set path variables according to url updates, adding a `{value}` will populate the path variables table, and removing it from the url will remove it from the table, unless is has a value or is required.
https://github.com/user-attachments/assets/986f3a2d-6f16-41a9-aba2-75728c58781f

feat(api-client): set path variables from url

---

.changeset/witty-rings-peel.md
packages/api-client/src/components/AddressBar/AddressBar.vue
packages/api-client/src/errors.ts
packages/api-client/src/libs/eventBusses/executeRequestBus.ts
packages/api-client/src/libs/eventBusses/index.ts
packages/api-client/src/libs/eventBusses/requestStatusBus.ts
packages/api-client/src/libs/sendRequest.ts
packages/api-client/src/views/Request/Request.vue

Redid the address bar loading logic so it actually reflects whether or not the request has loaded yet, the logic itself is a little complicated but I think it makes for a nice UX.
Basically while we're waiting on a request the loading bar progresses asymptotically towards 85% (i.e. it will never actually get to 85%). Then when the request gets back we fill the rest of the bar linearly in 400ms which is the timing we were using before to fill the entire bar. 400ms feels about long enough that you can tell whats happening while still feeling snappy.
The tl;dr; is fast requests feel the same as they did before but with slow requests you can actually tell that the request hasn't loaded yet.
Other changes:
- Made the loading bar a little bit darker
- Added toasts for all Axios errors (some of …

feat(api-client): improve client request loading and feedback

---

.changeset/forty-ravens-teach.md
packages/fastify-api-reference/src/fastifyApiReference.test.ts
packages/fastify-api-reference/src/fastifyApiReference.ts

This PR updates the default `routePrefix` in the `fastify-api-reference` configuration from an empty string to `/reference`. For helps avoid potential conflicts with root route in the application.

chore(fastify-api-reference): change default routePrefix

---

.changeset/cool-kiwis-run.md
packages/docusaurus/README.md

**Problem**
New `showNavLink` option for the docusaurus plugin did not have any documentation besides the type file that it existed.
**Solution**
Now it is documented

docs: documented new showNavLink option in docusaurus plugin

---

CODEOWNERS

Currently, @marclave has to review all the PRs. But that might not scale too well. :)
This PR suggests to extend the list of code owners and just falls back for to @marclave for everything else.
Feedback highly appreciated! Feel free to comment if you feel (not) responsible for a specific part.

chore: extend the list of codeowners

---

.changeset/weak-fishes-burn.md
documentation/openapi.md
packages/api-reference/src/components/Content/Schema/Schema.vue
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue
packages/oas-utils/src/spec-getters/getExampleFromSchema.test.ts
packages/oas-utils/src/spec-getters/getExampleFromSchema.ts
packages/oas-utils/src/spec-getters/getRequestBodyFromOperation.test.ts

This PR refactors how we deal with `additionalProperties`. After reading the bug reports from the community and re-reading the specification, I got a completely different understand of how they were meant to work. :)
Fixes #2457, #1858, #2606.
**Example**
```json
{
"info": {
},
"paths": {
"/Auth/Login": {
"get": {
"tags": [
"Auth"
],
"content": {
"schema": {
"$ref": "#/components/schemas/as-obj"
}
}
},
},
"responses": {
"400": {
"description": "Error",
"content": {
"schema": {
"$ref": "#/components/schemas/as-false"
}
}
}
},
"401": {
"description": "Error",
"content": {
"schema": {
"$ref": "#/components/schemas/as-obj"
}
}
}
}
}
}
}
}, …
```

fix(api-reference): additional properties, fix #2457, fix #1858, fix #2606

---

.changeset/friendly-teachers-walk.md
packages/api-client/src/components/Sidebar/SidebarListElementActions.vue
packages/api-client/src/views/Cookies/Cookies.vue
packages/api-client/src/views/Environment/Environment.vue

this pr fixes a log errors due to a missing prop that also displays wrong warning message on environment page:
**before**
**after**

fix(api-client): sidebar list prop

---

.changeset/serious-paws-doubt.md
packages/api-client/src/components/HttpMethod/HttpMethod.vue
packages/api-client/src/views/Request/RequestSidebarItem.vue

this pr aims to fix few glitches on api client sidenav ui within gitbook as seen below:
**before**
**after**

fix(api-client): sidenav ui

---

.changeset/thin-ladybugs-eat.md
packages/api-client-app/src/main/index.ts
packages/api-client-app/src/preload/index.ts
packages/api-client-app/src/renderer/src/main.ts

This PR adds a way to open a file dialog, read files from disk and drag and drop files and URLs into the app to import new OpenAPI documents.
**Drag’n’drop**
https://github.com/user-attachments/assets/e18b72c2-0179-4730-8d7e-dd5e2efa3564
**Open…**

feat(api-client-app): drag and drop files and urls

---

.changeset/slow-terms-hunt.md
packages/api-client/src/components/Search/SearchModal.vue

this pr as an attempts to fix the data not being retrieved when using the search modal in the client within an api reference and might fixes #2703. when opening the search the first time, data are displayed, but once it gets closed/re-opened, no results is displayed:
**before**
**after**

fix(api-client): search modal data population

---

.changeset/flat-books-leave.md
packages/themes/src/variables.css

fix(themes): sets a default for scalar brightness filters

---

.changeset/twelve-pugs-doubt.md
packages/api-client/src/components/Sidebar/SidebarListElement.vue
packages/api-client/src/views/Cookies/CookieForm.vue
packages/api-client/src/views/Cookies/Cookies.vue

this pr updates the cookie sidebar list element in order to:
- group cookie per domain
- subgroup cookie per path
- set cookie name placeholder name using index
**before**
**after**

feat(api-client): group cookies

---

.changeset/cold-trains-guess.md
packages/api-client/src/components/SideNav/SideNav.vue

This PR makes the side nav (but not the buttons inside) a draggable region, so it’s easier to move the app window around:
https://github.com/user-attachments/assets/f14b822d-2343-4090-9169-ed71e9ab9d05

feat(api-client): make the side nav a draggable region

---

.changeset/three-eggs-shout.md
packages/components/src/components/ScalarIcon/icons/User.svg

Outlines the user icon to better match our other icons. As far as I can tell the Dashboard is the only place using this icon at the moment.
Similar to the Play icon we can add the fill back if we want to use it as a filled icon somewhere.
<br />

style(components): outline user icon

---

.changeset/five-buckets-suffer.md
packages/api-client/src/components/TopNav/TopNav.vue

this pr fixes topnav misalignment as seen below:
**before**
**after**

fix(api-client): topnav alignment

---

.changeset/three-snakes-know.md
packages/api-client/src/libs/event-busses/hot-keys-bus.ts
packages/oas-utils/src/entities/workspace/workspace.ts

after merging #2797 hotkey doesn't require the key combinations anymore (meta + letter for instance) and event are fired when pressing only the letter. this pr is an attempt to bring back the combination requirement when specified in the bus accordingly.

fix(api-client): hotkeys modifier

---

CODEOWNERS

There are a few PRs where I’m added as the codeowner, but I don’t know exactly why.
One example with changes to the client:
https://github.com/scalar/scalar/pull/2690
Let’s just remove this one line from the codeowners file. It was meant to match all dotfiles in the root directory, but I think it also matches the changeset folder.

chore: remove rule for all dot files

---

.prettierignore

I just noticed we’re formatting the `out/` directory of the app, which has generated files only. Let’s ignore this. 😊

chore: add app output to prettierignore

---

.changeset/gorgeous-spies-hope.md
packages/api-client-app/src/renderer/src/main.ts

With this PR, we’re checking whether the Electron context is available before tracking an event in Fathom. This PR also removes the `auto: false` flag to enable the anonymous tracking of page views, and it’s configured to work with the hash router now.

fix(api-client-app): check whether the renderer is executed in the Electron context

---

.changeset/fast-comics-sparkle.md
.changeset/metal-rats-sin.md
.changeset/witty-chefs-grin.md
packages/api-client/src/store/workspace.ts
packages/api-client/src/views/Request/RequestSidebarItem.vue
packages/api-client/src/views/Request/RequestSidebarItemMenu.vue
packages/api-client/src/views/Request/components/WorkspaceDropdown.vue
packages/components/package.json
packages/components/src/components/ScalarContextMenu/ScalarContextMenu.spec.ts
packages/components/src/components/ScalarContextMenu/ScalarContextMenu.stories.ts
packages/components/src/components/ScalarContextMenu/ScalarContextMenu.vue
packages/components/src/components/ScalarContextMenu/index.ts
packages/components/src/components/ScalarDropdown/ScalarDropdown.vue
packages/components/src/components/ScalarDropdown/ScalarDropdownItem.vue
packages/components/src/index.ts
packages/object-utils/package.json
pnpm-lock.yaml

this pr adds a new scalar context menu component and uses it:
- for the request sidebar item actions (rename, delete...)
- for the workspace actions (rename, delete)
this fixes #2702  as workspace can be removed unless it is the only existing one, in that case the button is disabled and a tooltip is displayed.
https://github.com/user-attachments/assets/8138d920-6452-4ef2-801a-d26de57c8380

feat(api-client): request sidebar context menu

---

.changeset/perfect-scissors-smash.md
packages/api-client/src/components/AddressBar/AddressBar.vue
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/components/TopNav/TopNav.vue
packages/api-client/src/libs/event-busses/hot-keys-bus.ts
packages/oas-utils/src/entities/workspace/consts/hot-keys.ts
packages/oas-utils/src/entities/workspace/workspace.ts

this pr is a follow up on #2814 and aims to:
- enable multiple hotkey modifier  usage (e.g. meta + alt + key)
- add topnav hotkeys
- add addressbar focus hotkey

feat(api-client): hotkeys modifiers

---

packages/api-client/playground/modal/main.ts
packages/oas-utils/src/entities/workspace/spec/createRequest.test.ts

This PR has a ~~failing~~ test for #2736. It used to throw a max call stack exceeded error. Run it like this:
```
pnpm test createRequest
```
The actual issue was fixed in #2805 and #2807.

test(api-client): createRequest with circular reference

---

.changeset/shaggy-llamas-wonder.md
packages/api-client/src/components/Sidebar/Sidebar.vue

this pr brings back the sidebar title removed by mistake in #2459:
**before**
**after**

fix(api-client): sidebar title

---

packages/scalar_fastapi/README.md
packages/scalar_fastapi/scalar_fastapi/scalar_fastapi.py

**Problem**
Currently, it's only possible to configure a few options when using FastAPI Scalar plugin.
This happens because the configuration is missing
**Solution**
With this PR I add the following configurations:
- `hide_donwload_button`
- `hide_models`
- `hidden_clients`
- `servers`
- `default_open_all_tags`
- `layout`
- `show_sidebar`
- `dark_mode`
- `search_hot_key`
I chose these configs first, because I need them in my current project. More configs could be added easily.

feat(scalar_fastapi): extend configuration for FastAPI

---

.changeset/fluffy-poems-try.md
documentation/configuration.md
packages/api-reference/src/components/ApiReference.vue
packages/api-reference/src/components/Layouts/ClassicLayout.vue
packages/api-reference/src/components/Layouts/ModernLayout.vue
packages/api-reference/src/hooks/useDarkModeState.test.ts
packages/api-reference/src/hooks/useDarkModeState.ts
packages/api-reference/src/types.ts

**Problem**
Currently users arent able to disable the dark mode button or force a state, this often leads to us defaulting to the browser or system settings which can be infinitely jarring
**Solution**
I updated the docs, added some more configuration for the user :) we are so back
Whether dark mode is on or off initially (light mode)
```js
{
darkMode: true
}
```
forceDarkModeState makes it always this state no matter what
```js
{
forceDarkModeState: 'dark'
}
```
Whether to show the dark mode toggle
```js
{
hideDarkModeToggle: true
}
```
some people might have external night and day mode buttons, so these arent all inclusive :)

fix(api-reference): initial dark mode state bug and add configuration for darkmode

---

.changeset/funny-lies-suffer.md
packages/fastify-api-reference/package.json
packages/fastify-api-reference/src/fastifyApiReference.test.ts
packages/fastify-api-reference/src/fastifyApiReference.ts
pnpm-lock.yaml

This PR adds a `hooks` option to the API reference route, allowing you to include hooks such as basic authentication to protect your API reference route or add other custom functionality as needed.
example with basic authentication:
https://github.com/user-attachments/assets/aaaebe7e-a814-4e31-9dd7-7bd0ea6d0d2f

feat(fastify-api-reference): add hooks option for API reference route

---

.changeset/healthy-teachers-burn.md
packages/api-reference/vite.config.ts
packages/nuxt/src/module.ts

Optimizing the whole module was incorrect as it causes other issues with unicorn. This _should_ only optimize references which should be ok

fix(nuxt): add specific optimize dependency for vite

---

.changeset/tiny-students-provide.md
packages/oas-utils/src/entities/workspace/spec/requests.ts
packages/oas-utils/src/transforms/import-spec.ts

this pr fixes the `default` tag issue that is now added to every request instead of just request without tag, which was duplicating them in the api client and creating an unneeded `default` collection:

fix(oas-utils): request default tag

---

.changeset/selfish-foxes-exercise.md
packages/api-reference/src/components/Content/Tag/Tag.vue
packages/api-reference/src/components/Content/Webhooks/Webhooks.vue
packages/api-reference/src/components/Section/SectionContainer.vue
packages/api-reference/src/components/ShowMoreButton.vue

For consideration - make tag background have more contrast when unopened?

fix: make tag background have more contrast when unopened

---

packages/scalar.aspnetcore/README.md

Updating .NET readme usage snippet
- Updating `app.MapOpenAPi()` to match how .NET 9 default templates use it (behind IsDevelopment guard).
- Updating usage text to indicate the default URL of the usage snippet would be

fix: README.md

---

.changeset/twenty-beers-attack.md
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/Content/Tag/Endpoints.vue
packages/api-reference/src/components/Content/Tag/Tag.vue
packages/api-reference/src/components/Content/Tag/mutationObserver.ts
packages/api-reference/src/hooks/useSidebar.ts

Currently we use a 100ms timeout to detect when a section should be open. If a section has a lot of elements or the client is just slow, it will miss this window and try to scroll to an element which does not exist. 
Here we leverage our already existing and firing lazyBus to detect when the element has loaded to ensure we scroll at the correct time.
Also used the same method for endpoint links in the tag headers

fix(api-reference): markdown links

---

.changeset/mean-balloons-guess.md
packages/api-client/src/components/Sidebar/Sidebar.vue
packages/api-client/src/store/workspace.ts

this pr introduces the enableResizer prop for the sidebar component in order to only enable dragging / resizing on request view, and not on others like cookies, environments.

fix(api-client): sidebar dragging

---

cloudbuild.yaml
packages/void-server/Dockerfile
packages/void-server/playground/index.ts
packages/void-server/rollup.config.ts
tooling/base-docker-builder/Dockerfile

With this PR, the `void-server` playground example is deployed to cloud run.

feat: deploy void-server to cloud run

---

.changeset/flat-cups-agree.md
packages/api-client/src/views/Request/RequestSidebarItem.vue

this pr brings back native context menu on draft folder, as highlighted in [#2788 by hans](https://github.com/scalar/scalar/pull/2788#pullrequestreview-2227517665) and will be follow up by other addition:

fix(api-client): request sidebar draft context menu

---

.changeset/wild-ties-grab.md
packages/api-client/src/components/CommandPalette/TheCommandPalette.vue
packages/api-client/src/libs/event-busses/hot-keys-bus.ts
packages/api-client/src/views/Request/Request.vue

this pr fixes the navigation issue cause by the focused search input in the command palette modal:
https://github.com/user-attachments/assets/8369c324-e4fe-420f-8b1c-eb23b639a74e

fix(api-client): command palette navigation

---

.changeset/nervous-houses-enjoy.md
packages/api-reference/src/components/Content/Operation/PathResponses/ExampleResponse.vue
packages/api-reference/src/features/ExampleRequest/ExampleRequest.vue
packages/components/src/components/ScalarCodeBlock/ScalarCodeBlock.vue
packages/themes/src/scrollbars.css

Looks like when we switched from codemirror to highlight JS we lost a bunch of our custom scroll classes that were targeting the code block. This PR should put things back to the way they were.
https://github.com/user-attachments/assets/779aff99-72df-4910-8f3b-80e25f9ecc92

fix(components): rebuild code block x-y scroll box

---

.changeset/stale-files-love.md
packages/components/src/components/ScalarLoading/ScalarLoading.stories.ts
packages/components/src/components/ScalarLoading/ScalarLoading.vue

Changes `useLoadingState` to not automatically clear when calling `useLoadingState.validate()` or `useLoadingState.invalidate()`. I checked and the only usages this should affect are the Dashboard.
Motivation: it seems like in forms where we redirect somewhere on success (like in the Dashboard) it's distracting to have the checkmark clear itself before redirecting.
https://github.com/user-attachments/assets/3e0334ed-41f2-4069-888a-56aa94137263
https://github.com/user-attachments/assets/d980e5ea-1f26-4606-a4be-1173b7dbd15a

fix(components): don't clear loading state automatically

---

.changeset/sixty-sloths-tease.md
packages/api-client-app/src/main/index.ts

this pr updates the app native shortcut to be able to use `meta + w` to close tab as expected:

fix(api-client): close tab hotkey event prevent

---

.changeset/fresh-frogs-help.md
packages/themes/src/presets/bluePlanet.css
packages/themes/src/presets/mars.css

I think when we moved the scroll to the `<body>` we allowed the flare for these themes to spill outside and create horizontal scroll.

fix(themes): restrict flare overflow for themes

---

.changeset/thin-monkeys-melt.md
packages/oas-utils/src/entities/workspace/spec/request-examples.ts

**Problem**
Currently, `File` is not a global type in node 18 and is causing release issues 
**Solution**
With this PR, temporary fix to use `any` type to avoid release issues

fix: temporary fix set type to any

---

.changeset/popular-crews-peel.md
packages/components/src/components/ScalarButton/ScalarButton.vue
packages/components/src/components/ScalarLoading/ScalarLoading.stories.ts
packages/components/src/components/ScalarLoading/ScalarLoading.vue
packages/components/src/components/ScalarSearchInput/ScalarSearchInput.vue

Switches the `<ScalarLoading>` component to use the same sizes as our `<ScalarIcon>` component

fix(components): refactor loading to match icon sizes

---

.changeset/tough-sheep-chew.md
packages/api-client/src/components/CodeInput/CodeInput.vue

fix(api-client): force code mirror to scroll on overflow

---

.changeset/purple-peas-add.md
packages/api-client/src/views/Request/RequestSection/RequestTableTooltip.vue

this pr fixes the ui glitch caused by the displayed div when no properties are shown:
**before**
**after**

fix(api-client): request table tooltip

---

.changeset/purple-ties-call.md
packages/api-client/src/views/Request/RequestSection/RequestParams.vue

this pr updates the delete all rows method in order to avoid to clear all the rows when pushing the `clear` action, and instead filter out param that are enabled or required.
we could also prevent the deletion of param coming from a specification whether being enabled or not.

fix(api-client): request params deletion

---

.changeset/afraid-glasses-work.md
packages/api-client/src/views/Request/RequestSidebarItem.vue
packages/api-client/src/views/Request/components/WorkspaceDropdown.vue
packages/components/src/components/ScalarTextField/ScalarTextField.stories.ts
packages/components/src/components/ScalarTextField/ScalarTextField.vue

Seems like our text field got a little broken at some point. This fixes the error text and makes it so helper text works on its own again.
I also made the error text medium to align with the icon and set the default label background to `scalar-background-1` instead of `scalar-background-2` which I think makes more sense as the default, @cameronrohani let me know if this is a bad idea.

fix(components): display ScalarTextField errors properly

---

packages/galaxy/Dockerfile
packages/galaxy/playground/index.ts
packages/galaxy/rollup.config.ts

**Problem**
This PR adds the playground example to the rollup build entrypoints and fixes the playground path to load the spec.

fix: galaxy playground example loads spec in dev and prod

---

.changeset/fuzzy-bears-dress.md
packages/api-client/src/store/workspace.ts

We need to correctly initialize multiple values for complex auth, this fixes #2871

fix(api-client): ensure complex auth is correctly initialized

---

packages/galaxy/Dockerfile
packages/galaxy/package.json
packages/galaxy/playground/index.ts
packages/mock-server/package.json
packages/mock-server/playground/index.ts
pnpm-lock.yaml

This PR corrects the path so the mock server loads the galaxy json spec from the galaxy dist folder. 
This PR also adds `hono-api-reference` base route to the galaxy playground.

fix(mock-server): path to galaxy spec

---

.changeset/wise-goats-develop.md
packages/api-client/src/components/AddressBar/AddressBar.vue
packages/api-client/src/libs/event-busses/cancel-request-bus.ts
packages/api-client/src/libs/event-busses/index.ts
packages/api-client/src/libs/sendRequest.ts
packages/api-client/src/views/Request/Request.vue
packages/api-client/src/views/Request/ResponseSection/ResponseLoadingOverlay.vue
packages/api-client/src/views/Request/ResponseSection/ResponseMetaInformation.vue
packages/api-client/src/views/Request/ResponseSection/ResponseSection.vue

Adds a loading state for slow requests (appears when the request takes more than 1 second) and a cancel button.
Also fixed a bug where you can click the request button multiple times.
https://github.com/user-attachments/assets/efa3b2f5-2100-4b66-a721-e84ddbd5c866

feat(api-client): add loading state and cancellation for slow requests

---

.changeset/ninety-elephants-march.md
packages/api-client/src/components/CommandPalette/CommandPaletteImport.vue
packages/api-client/src/store/workspace.ts

this pr adds a missing v-model on the command palette import collection in order to be able to import document collection using url + add toast state:
https://github.com/user-attachments/assets/3213c6a3-b320-4ff7-8794-538f4fc6aa9f

fix(api-client): command palette import

---

documentation/integrations/fastify.md

This PR adds documentation for the usage of the additional hooks option in the `fastify-api-reference`, related to #2834.

docs: add documentation for additional hooks in Fastify

---

.changeset/long-carrots-own.md
packages/nuxt/README.md
packages/nuxt/playground/nuxt.config.ts
packages/nuxt/src/module.ts
packages/nuxt/src/runtime/components/ScalarApiReference.vue
packages/nuxt/src/types.ts

In this PR, I made these changes:
1. Update Nuxt default config, as in Docs mentioned default route `/scalar` [commit](https://github.com/scalar/scalar/commit/71ff33b05572e78138be88fa54fb9cb845a72dc8)
2. Added `theme` config because I want to use the default theme, not only `nuxt` once; I think this will be better if the user could select from predefined ones or an exclusive `nuxt` theme, which is the default; also updated README.md file
https://github.com/user-attachments/assets/01c4f182-25d7-44a6-9ba8-1a010813833e

feat(nuxt): add dynamic styles import, update README

---

.changeset/selfish-paws-jog.md
.changeset/wet-deers-remain.md
packages/api-client/src/components/CommandPalette/CommandPaletteCollection.vue
packages/api-client/src/components/CommandPalette/CommandPaletteExample.vue
packages/api-client/src/components/CommandPalette/CommandPaletteFolder.vue
packages/api-client/src/components/CommandPalette/CommandPaletteRequest.vue
packages/api-client/src/components/CommandPalette/TheCommandPalette.vue
packages/components/src/components/ScalarButton/variants.ts

this pr prevents command palette data submission if input value is empty, set error state toast accordingly and comments out the server link which will be reactivated once the server view is set:

feat(api-client): command palette input required

---

.changeset/slow-yaks-chew.md
packages/components/src/components/ScalarModal/ScalarModal.stories.ts
packages/components/src/components/ScalarModal/ScalarModal.vue
packages/components/tailwind.config.ts

Add an `xl` Scalar modal and tweaks the sizing of the `lg` modal to allow it to be a bit taller before scrolling. I checked and we don't use the `lg` modal anywhere so this shouldn't break anything.
https://github.com/user-attachments/assets/859dd924-89f2-435b-a101-ad23d459b3ec

feat: add xl scalar modal

---

.changeset/dull-suits-hang.md
packages/api-reference/src/components/Content/Models/CollapsedModel.vue
packages/api-reference/src/components/Content/Models/Models.vue
packages/api-reference/src/components/Content/Schema/Schema.vue
packages/api-reference/src/components/Content/Schema/SchemaHeading.vue

Collapses and cleans up the models area, based off of #2833.
* Opens a model if you click on it in the sidebar
* Opens a model if you navigate to it via url
* Open a model if you navigate to it via search
* Highlights the model in the sidebar if it's visible and open
I also make the chevron a tiny bit smaller because it was running into the model heading.
https://github.com/user-attachments/assets/7244eff3-5d93-4202-8729-17f7aebd177d

feat(api-reference): collapse models by default

---

.changeset/search-modal-deprecated-endpoint.md
packages/api-reference/src/features/Search/SearchModal.vue

style(api-reference): search modal deprecated endpoint

---

.changeset/green-turtles-allow.md
packages/components/src/components/ScalarCodeBlock/ScalarCodeBlock.vue

Switches to a single scroll container (both x and y) for `ScalarCodeBlock`.
https://github.com/user-attachments/assets/adae3c6f-d603-44ff-bfce-37282802cf6e
https://github.com/user-attachments/assets/201d4b72-dec9-49b4-8050-2c6ef453dfc8

fix(components): use single scroll container for codeblock

---

.changeset/selfish-ladybugs-pretend.md
packages/oas-utils/src/spec-getters/getExampleFromSchema.test.ts
packages/oas-utils/src/spec-getters/getExampleFromSchema.ts

I’ve had a nasty typo: Instead of passing options to `getExampleFromSchema` I just merged the options with the result. 🙈 
This PR fixes it and adds a basic test for schemas containing `anyOf`.
See #2218

fix(api-reference): incorrect example for schemas with anyOf, fix #2218

---

.github/workflows/ci.yml

With this PR we (temporarily) bump the version numbers to have the upcoming version numbers in the packages released on stackblitz.
See #2847

ci: bump version numbers before publishing the pre-release, fix #2847

---

.changeset/curly-moose-confess.md
packages/oas-utils/src/spec-getters/getExampleFromSchema.test.ts
packages/oas-utils/src/spec-getters/getRequestBodyFromOperation.test.ts
packages/oas-utils/src/spec-getters/getRequestBodyFromOperation.ts

Long overdue! This PR adds support for request bodies with the `application/x-www-form-urlencode` and `multipart/form-data` content types. :)
See #2902 for more context.

feat(api-reference): multipart and url encoded request data, fix #2902, fix #1451

---

packages/openapi-types/README.md

I removed the release workflow from `scalar/openapi-parser`, but the `@scalar/openapi-types` package (which already lives here) points to the release workflow badge. Let’s remove this to make CI in main green again.

chore: remove parser release badge

---

.changeset/nasty-bats-mate.md
packages/api-client/src/views/Environment/Environment.vue

this pr removes variable wording from function and call to action to reflect better actions as spotted by @hanspagel :
**before**
**after**

fix(api-client): environment wording

---

packages/api-reference/package.json
packages/api-reference/src/features/ExampleRequest/ExampleRequest.vue
pnpm-lock.yaml

We made the @scalar/snippetz core and all plugins and everything just a single package, this was released as @scalar/snippetz@0.2.0.
See https://github.com/scalar/snippetz/pull/45
This PR updates to it. :)

chore: update `@scalar/snippetz`

---

README.md
packages/openapi-parser/README.md

I’ve found some (now) outdated links to the openapi-parser repository, let’s fix this.

chore: update links

---

packages/galaxy/Dockerfile

Add the new workspace dependency, `openapi-parser` to the Dockefile

fix: update galaxy dockerfile dependencies

---

packages/cli/package.json
packages/cli/src/commands/format/format.test.ts
packages/cli/src/commands/init/init.test.ts
packages/cli/src/commands/validate/validate.test.ts

The `scalar init` test deleted the `scalar.config.json` in root.
This PR makes all CLI tests use files inside the CLI directory.
This is also great, because you can run `pnpm test` in the package folder again. :)

fix(cli): init test deletes `scalar.config.json`

---

.changeset/dull-owls-brake.md
packages/api-client/src/views/Request/RequestSidebarItem.vue

this pr brings back events in the ellipsis menu that have been omitted, in order to be able to display action modal again from the ellipsis menu actions (spotted by @hanspagel):

fix(api-client): request sidebar menu actions

---

.eslintrc.cjs

this pr adds max lines rules to the eslint config in order to prevent components from containing any significant amount of business logic. this aims to encourage the creation of helper files, so as to maintain an atomic approach to the functions written and tested in them.
```
1:1  warning  Block has too many lines (79). Maximum allowed is 50  vue/max-lines-per-block
✖ 1 problem (0 errors, 1 warning)
│  package_format (skip) no matching staged files
┃  prettier ❯ 
```

chore: eslint script max lines

---

.changeset/dirty-months-jump.md
packages/api-client-app/open/index.html
packages/api-client-app/open/src/components/App.vue
packages/api-client-app/open/src/main.ts
packages/api-client-app/open/vite.config.ts
packages/api-client-app/package.json
packages/api-client-app/src/main/index.ts
packages/api-client-app/src/renderer/src/main.ts
packages/api-client-app/todesktop.json
packages/cli/package.json
pnpm-lock.yaml

With this PR the app is registered as the default handler for `scalar://` protocol links, this allows to import an OpenAPI document through links.
Let’s say we’d love to import our Scalar Galaxy example:
`https://cdn.jsdelivr.net/npm/@scalar/galaxy/dist/latest.json`
We can encode the URI and prefix it with our protocol:
`scalar://${encodeURIComponent("https://cdn.jsdelivr.net/npm/@scalar/galaxy/dist/latest.json")}`
Which gives us this:
scalar://https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2F%40scalar%2Fgalaxy%2Fdist%2Flatest.json
To test how this opens in the app, do the following:
1. `$ cd packages/api-client-app`
2. `$ pnpm dev`
3. `$ open scalar://https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2F%40scalar%2Fgalaxy%2Fdist%2Flatest.json`
There’s also a simple HTML file that we’d eventually need to host …

feat(api-client-app): `scalar://` links

---

.changeset/slimy-actors-invent.md
packages/openapi-parser/src/types/index.ts
packages/openapi-parser/src/utils/upgrade.test-d.ts
packages/openapi-parser/src/utils/upgrade.test.ts
packages/openapi-parser/src/utils/upgrade.ts

Currently, the `upgrade` function returns the `OpenAPI.Document` type.
We can narrow this down, because we know the version number, though.
With this PR the `upgrade` function (used on it’s own) returns the `OpenAPIV3_1.Document` type.

fix(openapi-parser): `upgrade` doesn’t return OpenAPI 3.1 type

---

.changeset/wicked-dancers-share.md
examples/api-client/package.json
examples/cdn-api-reference/package.json
examples/docusaurus/package.json
examples/express-api-reference/package.json
examples/fastify-api-reference/package.json
examples/nestjs-api-reference-express/package.json
examples/nestjs-api-reference-fastify/package.json
examples/nextjs-api-reference/package.json
examples/react/package.json
examples/ssg/package.json
examples/web/package.json
packages/api-client-app/package.json
packages/nextjs-openapi/package.json
packages/snippetz/package.json
scripts/format-package.ts

Publishing fails because `@scalar/snippetz` doesn’t have the repository URL in the package.json.
With this PR the repository URL is automatically added with `pnpm format:packages` and the changes are already applied to all files.

chore: automatically add repository URL to every package.json

---

packages/scalar.aspnetcore/SacalarClients.cs
packages/scalar.aspnetcore/ScalaConfiguration.cs
packages/scalar.aspnetcore/Scalar.AspNetCore.cs
packages/scalar.aspnetcore/Scalar.AspNetCore.csproj
packages/scalar.aspnetcore/ScalarOptions.cs
packages/scalar.aspnetcore/ScalarTargets.cs
packages/scalar.aspnetcore/ScalarThemes.cs

Some missing configurations have been added to the AspNetCore SDK, and documentation has been updated.
**Added options:** 
- HideModels
- ForceDarkModeState
- HideDarkModeToggle
- DefaultOpenAllTags
- DefaultHttpClient
- HiddenClients - Left as a bool for easier configuration.
**New Features:** 
- **EnabledClients** and **EnabledTargets**: Allow filtering ONLY the ones you want to show. These options override the HiddenClients array with the opposite options.
- **Authentication**: Improved class relationships.
- **Theme**, **Clients** and **Targets** are available as enum options.
- Add documentation options

feat: Add new configuration options and docs

---

CONTRIBUTING
packages/api-client/src/libs/sendRequest.test.ts
packages/oas-utils/src/helpers/fetchSpecFromUrl.test.ts

With this PR the contributing guide is updated to list the required servers (`@scalar/void-server` + `@scalar/proxy-server`) for a complete test run.
And with this PR, in the two test files that require them, we check whether they are running and throw a helpful error if they aren’t running already.

chore: require some servers to be running for some test files

---

.changeset/clean-melons-wait.md
packages/openapi-parser/README.md
packages/openapi-parser/src/utils/upgrade.test.ts
packages/openapi-parser/src/utils/upgradeFromTwoToThree.test.ts
packages/openapi-parser/src/utils/upgradeFromTwoToThree.ts

I’d consider it experimental and it lacks features (e.g. support security schemes), but it’s a start:
```ts
import { upgrade } from '@scalar/openapi-parser'
const { specification } = upgrade({
swagger: 2.0,
info: {
title: 'Hello World',
version: '1.0.0',
},
basePath: '/v1',
schemes: ['http'],
host: 'api.example.com',    
paths: {},
})
// Output:
//
// {
//   openapi: '3.1.0',
//   info: {
//     title: 'Hello World',
//     version: '1.0.0',
//   },
//   servers: [
//     {
//       url: 'http://api.example.com/v1',
//     },
//   ],
//   paths: {},
// }  
```

feat(openapi-parser): upgrade from Swagger 2.0

---

.changeset/silly-lions-heal.md
packages/api-reference/src/components/Content/Operation/Operation.vue

I don’t think it was intentional to have the path variable italic, so this PR makes it `font-style: normal` again:
**Before**
**After**

style: don't make the path variable italic

---

.changeset/chilly-cycles-breathe.md
documentation/configuration.md
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/Content/Operation/TestRequestButton.vue
packages/api-reference/src/helpers/provideSymbols.ts
packages/types/src/legacy/reference-config.ts

Every now and them [someone asks to disable the “Test Request” button](https://github.com/scalar/scalar/discussions/3005), which launches the embedded API client. Currently, people just hide it with CSS or even use alternatives, just because they can’t disable it. 
This PR introduces the `hideTestRequestButton` option to allow users to hide the button.
I’ve kept the footer of the card, because otherwise we’d need the logic to disable the button in the parent component, and these are 3 different components. Keeping the footer was way easier, so I went with this solution.
**Preview**
```js
{
hideTestRequestButton: true
}
```

feat(api-reference): allow to hide the “Test Request” button

---

.changeset/weak-ties-rescue.md
packages/api-reference/src/components/Content/Operation/PathResponses/PathResponses.vue
packages/api-reference/src/components/Content/Schema/Schema.vue
packages/components/src/components/ScalarCodeBlock/ScalarCodeBlock.vue
packages/use-toasts/src/components/ScalarToasts.vue

This replaces some CSS values with mixed support with alternative values.
While they behave [slightly different according to MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content#flex-start), I couldn’t spot any difference in our use case.
See #3003

fix: autoprefixer warnings, fix #3003

---

cloudbuild.yaml
packages/api-client-app/Dockerfile
packages/api-client-app/package.json

We need an intermediate page before we open the Electron app from a link.
This PR deploys a simple vue app page to cloud run using cloud build

chore(api-client-app): deploy open electron app page

---

oss-pledge.json

**Problem**
Currently, the URL for the Scalar logo for the Open Source Pledge profile is bad.
**Solution**
With this PR, the URL magically becomes good. 😄

fix: logo url in oss-pledge.json

---

.changeset/green-adults-crash.md
packages/api-reference/src/components/Content/Models/Models.vue
packages/api-reference/src/components/Content/Webhooks/Webhooks.vue
packages/api-reference/src/components/Section/CompactSection.vue

this pr moves id to section markup level for model and webhook components in order to fix anchor offset issue as seen below:
**before**
https://github.com/user-attachments/assets/7a82f0a7-2ba1-40cd-86c1-84408164c80a
**after**
https://github.com/user-attachments/assets/46bd3508-1e62-479f-993a-0d470575cdb3

fix(api-reference): anchor offset

---

.changeset/breezy-shoes-deliver.md
packages/api-reference/src/components/Content/Operation/OperationAccordion.vue

this pr hides the test icon in classic layout api reference when `hideTestRequestButton` is enabled introduced in #3016:
**before**
**after**

fix(api-reference): operation accordion test icon

---

.changeset/tame-melons-thank.md
documentation/configuration.md
packages/api-reference/src/components/ApiReference.vue
packages/types/src/legacy/reference-config.ts

this pr adds favicon configuration for api reference as highlighted in #2637:
**Preview**
```js
{
favicon: 'path/to/favicon.svg'
}
```

feat(api-reference): adds favicon configuration

---

.changeset/fluffy-eagles-do.md
packages/api-client/src/libs/sendRequest.ts
packages/oas-utils/src/entities/workspace/spec/request-examples.ts

The `File` type is not available in Node 18, so let’s use this object as a workaround.

fix: `File` is not defined (Node 18) DOC-2222

---

.github/workflows/ci.yml

The `File` type [slips through again and again](https://github.com/scalar/scalar/actions/runs/10673537971/job/29601485700?pr=3022), and it causes the tests in the release PR to fail, because this is the only place we build and test against Node 18 (where we don’t have the `File` type).
Let’s just build and test every PR against Node 18 and 20 again.

ci: build and test on Node 18 and 20

---

.github/workflows/ci.yml

Oops, I forgot to add `'build'` as an requirement for the Netlify deploy step.
Not a problem, but it can’t leverage the build cache if it starts before the cache is filled.

ci: the Netlify deployment should wait for the initial build

---

.changeset/little-pets-approve.md
.eslintrc.cjs
examples/docusaurus/docusaurus.config.ts
packages/api-reference/src/standalone.ts
packages/docusaurus/src/ScalarDocusaurusCommonJS.tsx

While not solving every issue this PR does improve the memory performance and DOM performance of the Scalar Docusaurus integration. Things it does do:
- Unmounts and removes the app when switching away from Scalar Docs in Docusaurus
- Checks to see if the Scalar CDN script has been loaded already rather than fetch a new copy every time
- Deletes the old configuration when refreshing the config (which hopefully will allow the browser to free up that memory)
Because our Docusaurus integration uses the CDN version of the app we will need to make sure we publish the new `standalone.js` before releasing the Docusaurus update (or at the same time?). I think we should be safe to publish the changes to `standalone.js` on their own, the only functionality change should be that the …

fix(docusaurus): improve docusaurus memory issues

---

.changeset/ten-pets-return.md
documentation/configuration.md
packages/api-reference/src/components/DarkModeToggle/DarkModeIconToggle.vue
packages/api-reference/src/components/Layouts/ClassicLayout.vue
packages/api-reference/src/components/Layouts/ModernLayout.vue
packages/types/src/legacy/reference-config.ts

This PR is a proposal to introduce the `hideSearch` option to allow users to hide the search from api reference sidebar as requested in #2869.
**Preview**
```js
{
hideSearch: true
}
```

feat(api-reference): allow to hide search

---

scalar.config.json

I think we need to swap the logos.
Currently, it looks like this:

fix: logo light/dark mode

---

scalar.config.json

Let’s use a custom page title and description for <https://guides.scalar.com>

chore: add siteMeta

---

README.md

We’ve had two files for the Laravel integration, which I fixed, but I didn’t update the link in the root README it seems.

docs: fix broken link to laravel integration

---

packages/api-client/src/views/Request/RequestSection/RequestAuth/DeleteRequestAuthModal.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuth.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuthModal.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestExampleAuth.vue
packages/api-client/src/views/Request/consts/new-auth-options.ts
packages/components/src/components/ScalarCombobox/ScalarComboboxMultiselect.vue
packages/components/src/components/ScalarCombobox/ScalarComboboxOption.vue
packages/components/src/components/ScalarCombobox/ScalarComboboxOptions.vue
packages/components/src/components/ScalarModal/ScalarModal.vue

this pr adds security scheme button creation to auth combobox along auth modal in order to add security scheme to a collection:
https://github.com/user-attachments/assets/d43f9c1a-7e7c-4e23-b3dd-58d42e9a0d8a
some more refactor and polish to be added as i started by duplicating const type and flows but we might want to re-use `new-auth-options` ones.

feat(api-client): security schemes modal

---

.changeset/dry-kings-drum.md
packages/api-reference/src/features/BaseUrl/ServerForm.vue

Before:
https://github.com/user-attachments/assets/ff104f94-03ac-4c03-8929-77e53990d7b5
After:
https://github.com/user-attachments/assets/75c8fddf-67ef-4529-8586-0986cd87f13f

fix(api-reference): server description color style

---

.github/workflows/ci.yml

I don’t see a good reason why the CI workflows should only run on PRs against main.
Let us run them in all PRs!
Skipping the queue here to use it in some of the PRs we’re doing against our super huge PR.

ci: run workflows on all PRs

---

.changeset/kind-grapes-lick.md
packages/themes/src/presets/default.css

This fixes some issues with transparent theme colors sometimes causing inconsistent layering when placed over each other. 
For example icons that use a fill and an outline (main / this PR): 
This PR updates all of the base colors in the default theme (colors 1 through 3 and the border color) to be opaque. I can also update the rest of the themes and colors to all be opaque if that's something we want as well.
In order to match the existing look of the app I adjusted the border color slightly to be slightly darker in light mode and slightly lightly in dark mode. I think the change is pretty subtle?
These screenshots can be used to compare the before after if you don't feel like checking out the PR: [ComparisonScreenshots.zip](https://github.com/user-attachments/files/16912988/ComparisonScre …

feat(themes): make base dark mode colors opaque

---

.changeset/lemon-dryers-kick.md
packages/api-client/src/components/Sidebar/Sidebar.vue
packages/draggable/src/Draggable.vue

These should be scoped so they don't leak out of the client. I tested it and everything still seems to be working fine but another test wouldn't hurt 🙏

fix(api-client): scope api client draggable styles

---

.changeset/thick-monkeys-shout.md
packages/oas-utils/src/spec-getters/getExampleFromSchema.test.ts
packages/oas-utils/src/spec-getters/getExampleFromSchema.ts

**Problem**
Examples are not generated for schemas with `anyOf` when `type` is not defined on the object
Currently, I used some auto gen tools to generate json schemas, and it creates unions with `anyOf` instead of `oneOf`
Examples are generated fine for `oneOf` schemas, but the `anyOf` case is completely ignored
**Solution**
With this PR, I create an implementation for the `anyOf` that is similar to the `oneOf`'s implementation

feat: getExampleFromSchema can generate examples for anyOf schemas, fix #2417

---

README.md

While we’re working on a new format, let’s remove the Townhall event from the root README. :)

docs: remove townhall event

---

.changeset/smooth-ties-dress.md
packages/oas-utils/src/spec-getters/getExampleFromSchema.test.ts
packages/oas-utils/src/spec-getters/getExampleFromSchema.ts

Currently, we just don’t render schemas more than 5 levels deep.
This PR renders deeply nested schemas, no matter how deeply they are nested.
But circular references are detected and only the first five levels are rendered in that case.
See #2337 for more context.

feat: render deeply nested schemas, fix #2337

---

.changeset/dirty-crabs-give.md
packages/api-reference/src/features/ExampleRequest/ExampleRequest.vue
packages/api-reference/src/helpers/getExampleCode.test.ts
packages/api-reference/src/helpers/getExampleCode.ts

We broke the example code generation for most clients in #2995.
This PR fixes multiple issues causing the example code generation for most clients, and even deletes a dead code block.
We just didn’t pass the client id in some cases and we added an `js` alias to the `@scalar/snippetz` call, but not to the `httpsnippet-lite` call where it’s actually needed.

fix: request example code works for some clients only, fix #3094

---

.eslintrc.cjs

I’d love to have less lines in Vue components, but the rule doesn’t work well in practice. It just adds squiggly lines to the whole file and instead of nudging me to refactor the component it just makes me close it faster. Also, red squiggly lines are really hard to spot then.
So let’s make our components have less lines, but let’s also remove this rule for now!

chore: remove max-lines-per-block rule

---

packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/views/Request/ResponseSection/ResponseBody.vue
packages/api-client/src/views/Request/ResponseSection/ResponseBodyRaw.vue
packages/components/src/components/ScalarCodeBlock/ScalarCodeBlock.vue

this pr adds copy capability to response code in api client as seen below:

feat(api-client): response codeblock copy

---

packages/api-reference/vite.standalone.config.ts

**Problem**
While playing around with #2918, I found that the placeholders in [the license header](https://github.com/scalar/scalar/blob/main/packages/api-reference/license-banner-template.txt) were not correctly replaced.
**Solution**
This PR fixes the regular expressions to match the placeholder's format.

fix(api-reference): placeholders in the license header not replaced

---

examples/docusaurus/sidebars.ts
packages/api-reference-editor/playground/main.ts
packages/api-reference/src/components/Content/Authentication/Authentication.stories.ts
packages/api-reference/src/helpers/getExampleCode.test.ts
packages/api-reference/src/hooks/useReactiveSpec.test.ts
packages/api-reference/src/legacy/helpers/getRequestFromAuthentication.test.ts
packages/api-reference/src/legacy/helpers/normalizeHeaders.ts
packages/echo-server/src/createEchoServer.test.ts
packages/fastify-api-reference/src/fastifyApiReference.test.ts
packages/mock-server/tests/galaxy.test.ts
packages/nestjs-api-reference/src/nestJSApiReference.ts
packages/openapi-parser/src/utils/betterAjvErrors/helpers.ts
packages/openapi-parser/tests/openapi3-examples/3.0/fail/internalPathItemRef.test.ts
packages/ts-to-openapi/src/js-doc.ts

This PR fixes just some linter warnings:
* ESLint fixes some things automatically
* replaced @ts-ignore with @ts-expect-error
* deleted some dead imports/variables

chore: fix some linter warnings

---

packages/api-client/src/components/HttpMethod/HttpMethod.vue
packages/components/src/components/ScalarListbox/ScalarListbox.vue
packages/oas-utils/src/helpers/httpMethods.ts

this pr updates http methods style and ordering in the address bar:
**before**
**after**

feat(api-client): address bar http methods

---

examples/api-client/package.json
examples/docusaurus/package.json
examples/express-api-reference/package.json
examples/fastify-api-reference/package.json
examples/nestjs-api-reference-express/package.json
examples/nestjs-api-reference-fastify/package.json
examples/nextjs-api-reference/.eslintrc.cjs
examples/nextjs-api-reference/package.json
examples/ssg/package.json
examples/web/package.json
package.json
packages/api-client-app/package.json
packages/cli/package.json
packages/express-api-reference/package.json
packages/hono-api-reference/package.json
packages/mock-server/package.json
packages/nestjs-api-reference/package.json
packages/snippetz/package.json
packages/void-server/package.json
pnpm-lock.yaml
scripts/format-package.ts

The `format:packages` script showed a whole bunch of warnings and errors for missing npm scripts (mostly lint:check, lint:fix, types:check) and some packages not being ESM.
This PR fixes all of them.

chore: add missing npm scripts

---

.changeset/blue-moons-dream.md
packages/api-client/src/views/Request/RequestSection/RequestSection.vue

this pr favors span markup over input in the api client request header on read only mode to avoid style issue:
**before**
**after**

fix(api-client): request header

---

packages/api-client/src/components/DataTable/DataTable.vue
packages/api-client/src/components/Form/Form.vue
packages/api-client/src/components/Sidebar/Sidebar.vue
packages/api-client/src/components/Sidebar/SidebarButton.vue
packages/api-client/src/components/SubpageHeader.vue
packages/api-client/src/components/ViewLayout/ViewLayout.vue
packages/api-client/src/components/ViewLayout/ViewLayoutContent.vue
packages/api-client/src/components/ViewLayout/ViewLayoutSection.vue
packages/api-client/src/views/Cookies/CookieForm.vue
packages/api-client/src/views/Cookies/CookieRaw.vue
packages/api-client/src/views/Environment/Environment.vue

this pr updates layout responsiveness to reach a good enough on mobile, to be enhanced later on:
**before**
**after**

style(api-client): layout responsiveness

---

.changeset/twelve-penguins-end.md
packages/api-client/src/layouts/App/create-api-client-app.ts
packages/api-client/src/router.ts

I tried this a few different ways but this seemed to be the simplest and most robust. Persists the most recent active workspace `uid` so that we can go to it when we load `/`.
Client Web:
https://github.com/user-attachments/assets/5fef215e-f953-4e25-8f1f-f9f773c597eb
Client App:
https://github.com/user-attachments/assets/92d22c16-57b9-495f-ae91-73ce581ce7a3

feat(api-client): track active workspace in local storage

---

.changeset/forty-yaks-remember.md
packages/api-client/src/components/Sidebar/Actions/DeleteSidebarListElement.vue
packages/api-client/src/components/Sidebar/Actions/RenameSidebarListElement.vue
packages/api-client/src/components/Sidebar/Actions/SidebarListElementForm.vue
packages/api-client/src/views/Request/RequestSidebarItem.vue

this pr adds consistency between delete/rename action modal style while updating the button position in order to fix ux risk of clicking to the wrong action due to call to action proximity.
tba: workspace modal actions
<details>
<summary>before</summary>
</details>
<details open>
<summary>after</summary>
</details>

feat(api-client): request sidebar item modal style

---

.changeset/rich-pets-share.md
packages/api-client/src/components/AddressBar/AddressBar.vue
packages/api-client/src/components/Sidebar/Sidebar.vue
packages/api-client/src/components/TopNav/TopNav.vue
packages/api-client/src/views/Request/Request.vue

Based on chats with @cameronrohani this disables the resizing behaviour for the sidebar on small screen and makes the sidebar fill the viewport. We could also move the sidebar into a popover if that sort of overlay behavior if preferred.
https://github.com/user-attachments/assets/6c3de414-c617-4437-aa85-b1590a8fafca

feat(api-client): disable sidebar resizing on small screens

---

.changeset/five-ways-argue.md
packages/void-server/src/createVoidServer.test.ts
packages/void-server/src/utils/getRequestData.ts

I was reviewing #3055 and noticed `@scalar/void-server` only returns the first value for query parameter arrays.
This PR adds support for arrays:
**Request**
```bash
GET /?foo=foo&foo=bar&example=value
```
**Response**
```js
{
query: {
foo: ['foo', 'bar'],
example: 'value',
},
}
```

feat(void-server): query parameter arrays

---

.changeset/wild-timers-design.md
packages/api-client/src/components/ContextBar.vue
packages/api-client/src/views/Request/RequestSection/RequestSection.vue
packages/api-client/src/views/Request/ResponseSection/ResponseSection.vue
packages/components/src/components/ScalarSearchInput/ScalarSearchInput.vue

this pr sets context bar back to its previous position to maintain readability:
**before**
**after**

feat(api-client): style context bar revert

---

.changeset/breezy-moons-grab.md
packages/api-client/src/libs/send-request.test.ts

**Problem**
Fix https://github.com/scalar/scalar/issues/3054
Before the fix proposal
**Solution**
After the fix proposal
**Comments**
this is the first step in handling arrays. in the future, one might think of supporting other ways of defining arrays, e.g. https://swagger.io/docs/specification/serialization/

fix(api-client): arrays as query params

---

.changeset/rotten-melons-dress.md
packages/api-client/src/libs/create-client.ts

we werent respecting the proxy config, lets fix it! :) 
the scalar api client still has the proxy by default

fix: respect the proxy url config

---

.changeset/silent-rats-bathe.md
packages/api-client/src/views/Request/Request.vue

this pr fixes a typo in the hide event modal in order to re-enable modal closing on button click from a reference.

fix(api-client): hide modal event

---

.github/dependabot.yml

This PR adds the NuGet package manager to the dependabot configuration. The `Scalar.AspNetCore` project itself has only one dependency, but the demo and test projects have some more. I think weekly updates are fine as the dependencies are not crucial.

chore: Add Nuget to dependabot configuration

---

packages/scalar.aspnetcore/src/Scalar.AspNetCore/Options/ScalarOptions.cs

**Problem**
The `ForceThemeMode` property was set to `ThemeMode.Light` by default, which caused properties like `DarkMode` to have no effect.
**Solution**
The default value is now `null` as intended.
Closes #3156

fix(Scalar.AspNetCore): ForceThemeMode is null by default

---

.changeset/early-geese-impress.md
packages/api-client/src/views/Request/RequestSection/RequestPathParams.vue
packages/oas-utils/src/helpers/regexHelpers.ts

this pr fixes the current path variable regex that display also the request path table for environment variables by setting up a path regex helper.

fix(api-client): path regex helper

---

packages/api-client/package.json
packages/api-client/src/libs/send-request.ts
packages/api-client/src/views/Request/RequestSection/RequestBody.test.ts
packages/api-client/src/views/Request/RequestSection/RequestBody.vue
packages/api-client/src/views/Request/RequestSection/RequestSection.vue
packages/oas-utils/src/entities/spec/request-examples.ts
pnpm-lock.yaml

Closes #3157, #3142
- fixed not being able to select different body content types
- added tests for body content types
- added back in the magic content header
- made content header set correctly when switching examples

fix(api-client):  add back content header

---

.changeset/famous-trainers-shake.md
packages/api-client/src/components/AddressBar/AddressBarServer.vue
packages/api-reference/src/legacy/helpers/getUrlFromServerState.ts

**Problem**
Currently we have `//` if a server has a trailing slash
**Solution**
(we remove it from rendering :) )

fix: remove trailing slash in examples and in client for server

---

.changeset/brown-peaches-bathe.md
packages/api-client/package.json
packages/api-client/src/views/Request/RequestSection/RequestBody.vue
packages/api-client/src/views/Request/RequestSidebar.vue
packages/api-client/src/views/Request/RequestSidebarItem.vue
packages/api-client/src/views/Request/RequestSidebarItemMenu.vue
packages/api-client/src/views/Request/types/index.ts
packages/api-client/src/views/Request/types/sidebar-item.ts
packages/components/src/components/ScalarDropdown/ScalarDropdown.vue
packages/components/src/components/ScalarFloating/ScalarFloating.vue
packages/components/src/components/ScalarFloating/types.ts

This improves the load time of the api-client by about 25x when looking at big specs. This was caused by the context menu + menu + modals in every instance of the sidebar items. We should aim to keep looping items as lean as we can!
Before:
sidebar load time: 2629.917236328125 ms
After:
sidebar load time: 110.170166015625 ms
@antlio I had to remove the context menu because I couldn't figure out how to pull it out of the ReqeuestSidebarItem and into the parent. Maybe you can help with that.
TODO:

feat(api-client): performance upgrades for sidebar

---

.changeset/nasty-penguins-argue.md
packages/express-api-reference/package.json
packages/express-api-reference/src/expressApiReference.ts
packages/nestjs-api-reference/package.json
packages/nestjs-api-reference/src/nestJSApiReference.ts
pnpm-lock.yaml

closes #3159
closes #3187
In `@scalar/nestjs-api-reference` and `@scalar/express-api-reference`, `@scalar/api-reference` and `express` should be listed under `devDependencies` to avoid including them in built package. Check above issues for details.

chore(nestjs-api-reference, express-api-reference): move `@scalar/api-reference` and `express` from `dependencies` to `devDependencies`

---

.changeset/empty-coins-love.md
packages/nextjs-api-reference/src/ApiReference.ts

chore(nextjs-api-reference): fix import of ReferenceConfiguration

---

packages/object-utils/src/mutator-record/mutations.test.ts

**Problem**
Currently, the [mutations test is flaky 
](https://github.com/scalar/scalar/actions/runs/10987367520/job/30502196429?pr=3192)
**Solution**
With this PR, the vitest syntax is updated to retry the test. Vitest docs https://vitest.dev/api/#test-api-reference

fix: retry flaky mutation test

---

.changeset/unlucky-mice-film.md
packages/api-client/src/components/AddressBar/AddressBar.vue
packages/api-client/src/components/AddressBar/AddressBarHistory.vue
packages/api-client/src/libs/errors.ts

this pr fixes address bar empty url typo + adds style enhancements and loading overflow:
**before**
**after**

fix(api-client): address typo style

---

.changeset/slimy-birds-check.md
packages/api-client/src/views/Request/RequestSidebarItem.vue

this pr enables back the sidebar item being disabled from a reference client, unless it was meant to be.

fix(api-client): sidebar folder toggle

---

.changeset/six-apricots-play.md
examples/web/src/pages/ApiReferenceTestPage.vue
package.json
packages/nextjs-openapi/package.json
packages/ts-to-openapi/package.json
pnpm-lock.yaml

With every minor version, typescript gets smarter...
plus emoji imports
```typescript
import { "🍌" as banana } from "./foo"
/**
* om nom nom
*/
function eat(food: string) {
console.log("Eating", food);
};
eat(banana);
```

chore: upgrade to TypeScript 5.6

---

.changeset/hungry-rules-stare.md
packages/api-client/src/components/AddressBar/AddressBar.vue
packages/api-client/src/components/HttpMethod/HttpMethod.vue

this pr fixes the visibility of the address bar http methods dropdown introduced in #3194.

fix(api-client): address bar http methods

---

.changeset/poor-moose-lick.md
packages/api-client/src/views/Request/RequestSection/RequestBody.vue

This PR ensures we add the extra empty row to forms in the client on route change. Previously we were doing it when the content type changed, but if it didn't change and it was a different route there would be no row added.

fix(api-client): adding default extra row on route change

---

.changeset/heavy-mayflies-lay.md
packages/api-client/src/libs/local-storage.ts
packages/api-client/src/views/Request/RequestSidebar.vue
packages/oas-utils/src/migrations/local-storage.ts
packages/object-utils/src/mutator-record/handlers.ts

closes #3208 
This PR: 
- fixes the bug that Hans encountered
- adds safe parsing after the migration is done to prevent any further breaking of the app in the case of a bad migration

feat(api-client): adds safe parsing after migration

---

.changeset/stupid-bananas-begin.md
packages/api-reference/src/features/Search/SearchModal.vue

**Problem**
when using search function inside of the references there is a race condition that causes the search to sometimes not jump to the correct endpoint the first time it is searched, highlighed in this [issue](https://github.com/scalar/scalar/issues/2741)
**Solution**
This PR changes the function `onSearchResultClick` inside of `SearchModal.vue` Now it uses a `MutationObserver` to wait until the target section is loaded in the DOM before navigating to it. This ensures that the docs scroll to the correct section right away when a user clicks a search result.

fix(api-reference): search results scroll to wrong position

---

.changeset/tender-moose-fix.md
packages/api-client/src/components/CodeInput/CodeInput.vue

this pr fixes #3227 by adding input content max height:

fix(api-client): address bar input long content

---

.changeset/fresh-rivers-brush.md
packages/openapi-parser/src/utils/upgradeFromTwoToThree.test.ts
packages/openapi-parser/src/utils/upgradeFromTwoToThree.ts

OpenAPI 3.x doesn’t have `formData` parameters anymore, so let’s add them to the request body on `upgrade()` instead. :)
See #3205 for more context.
We don't show the form data parameters in the API client, though: #3222

feat(openapi-parser): upgrade Swagger 2.0 formData parameters, see #3205

---

packages/api-client/src/libs/environment-parser.ts
packages/api-client/src/views/Environment/Environment.vue

this pr fixes the environment variable not being displayed in the dropdown + sets back the language to code input.

fix(api-client): environment dropdown

---

.changeset/chatty-trainers-cover.md
.changeset/slimy-carrots-shop.md
packages/fastify-api-reference/package.json
packages/fastify-api-reference/src/fastifyApiReference.test.ts
packages/fastify-api-reference/src/fastifyApiReference.ts
packages/fastify-api-reference/src/index.ts
packages/fastify-api-reference/src/proxy.test.ts
packages/fastify-api-reference/src/types.ts
pnpm-lock.yaml

When Fastify is proxied with a route prefix, we can't rely on the configured route prefix that our integration has. The URL that we requested the JS from was invalid in those cases.
With this PR we’re making the JS asset path relative, which requires to access the reference with a trailing slash.
I registered a new route (depending on the configuration) e.g. `/reference`, which redirects to `/reference/`. This makes the browser request the JS with the `/reference/` prefix instead of just `/`.
This PR also includes the following unrelated changes (sorry):
* The `publicPath` prefix wasn’t really implemented, so I marked it as deprecated and deleted the relevant code. I’m not sure why this was in there. 👀 
* `/reference/@scalar/fastify-api-reference/js/browser.js` -> …

fix(fastify-api-reference): JS can’t be fetched in proxied environments

---

.changeset/many-hotels-camp.md
packages/api-client-app/src/renderer/index.html
packages/api-client-app/src/renderer/src/main.ts

Currently, we block any images loaded from fathom. This PR adds to the content security policy to allow images to be fetched from fathom.
It also scopes the tracking to just Electron, and not client.scalar.com.

fix(api-client-app): images from fathom are blocked

---

.changeset/slow-spoons-pump.md
packages/api-reference/src/components/ApiReferenceLayout.vue

Previously chrome might have been ignoring this bad css rule, but fixed!

fix: css missing comma

---

.changeset/mean-icons-rescue.md
packages/api-client-app/src/renderer/src/main.ts

Turns out we’ve used an invalid URL for the pageviews, which worked locally, but not in the build - for some reason.

fix(api-client-app): invalid pageview url

---

packages/api-client/src/views/Request/components/WorkspaceDropdown.vue

Doing the important work over here. 😁
* If I create something, it’s obviously new.
* We use title case for other add/create actions.
**Before**
**After**

chore(api-client): create workspace wording

---

.changeset/gentle-dolls-agree.md
packages/fastify-api-reference/src/fastifyApiReference.ts

This should solve @mcollina's issue with hosting Scalar via Fastify at a nested / proxied URL. Instead setting the spec URL to be absolute based on the route prefix (e.g. `/reference/openapi.json`) we assume it's relative to the current page (e.g. `./openapi.json`) which it should be since we host the file there ourselves when we register the plugin.
@hanspagel let me know if you see any issues with resolving it like this.
The test repo I was using was https://github.com/mcollina/scalar-fastify-proxy. Fyi @mcollina as far as I can tell setting `publicPath: './'` wasn't actually doing anything since it's no longer used by the integration.

feat(fastify-api-reference): use relative URL for fetching spec

---

packages/scalar.aspnetcore/src/Scalar.AspNetCore/Enums/ScalarTheme.cs

This PR fixes two typos in the theme names.
Closes #3269

fix(Scalar.AspNetCore): typo in theme names

---

.changeset/clean-buckets-perform.md
.changeset/late-shirts-shave.md
.changeset/nasty-cups-live.md
.changeset/pretty-trains-do.md
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue
packages/galaxy/src/specifications/3.1.yaml

Shows all the schema example values in the "Models" section again when the `examples` keyword is used (e.g. an array of examples). It sounds like OAS 3.1 has introduced the ability to add multiple examples to a schema as part of its alignment with JSON schema which only [allows an array of examples](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-00#section-9.5). 
I also added some additional example data to Scalar Galaxy with multiple examples.

fix(api-reference): show examples in models section

---

packages/api-client/src/components/Sidebar/Sidebar.vue

> [@vue/compiler-sfc] `defineProps` is a compiler macro and no longer needs to be imported.

chore(api-client): remove defineProps import

---

.changeset/moody-owls-dance.md
packages/api-client/src/components/CommandPalette/CommandPaletteCollection.vue
packages/api-client/src/components/IconSelector.vue
packages/api-client/src/views/Request/RequestSidebar.vue

this pr increases icon library icon usage stroke to maintain icon / text consistency as suggested by @cameronrohani  in sidebar, command palette:
**before**
**after**

style(api-client): icon library stroke

---

.changeset/light-brooms-roll.md
packages/api-client/src/layouts/Modal/create-api-client-modal.ts
packages/api-client/src/libs/create-client.ts
packages/api-client/src/store/import-spec.ts
packages/api-reference/src/components/ApiClientModal.vue
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/oas-utils/src/transforms/import-spec.ts

Since security schemes are selected per request, it isn't so easy to change the currently selected scheme from the references. HOWEVER we can set the scheme on initialization!
closes #3264

feat(api-client): sets initial security scheme in the client 

---

.changeset/old-olives-itch.md
examples/api-client/index.html
packages/api-client-app/src/renderer/index.html

Turns out blob urls in object (or iframe) tags are executed in the same origin context as the host page which means they're vulnerable to XSS injection. 
I updated our `Content-Security-Policy` for the app and set a `Content-Security-Policy` for examples/api-client (which seems to be used for client.scalar.com) to not allow scripts from blobs. This prevents scripts from running in html previews and in svgs when they're opened in a new tab via right click → "Open Image in New Tab"
Fixes #3286 
https://github.com/user-attachments/assets/08340b65-70d8-4f69-b6ce-d5fd8aa40128
https://github.com/user-attachments/assets/0590325e-6a5e-4976-8dc4-1dd15c0a4a30

fix(api-client): add Content-Security-Policy to client.scalar.com

---

packages/api-client/src/views/Request/ResponseSection/ResponseBody.vue
packages/api-client/src/views/Request/ResponseSection/ResponseBodyRaw.vue

I saw some code to format the raw response body in the API client. But it’s passed to `ScalarCodeBlock` anyway, and this component is already formatting the content (pretty printing JSON).

chore(api-client): remove unused code

---

.changeset/smooth-windows-remain.md
packages/oas-utils/src/transforms/import-spec.ts

**Problem**
Currently when you import `"swagger": "2.0",` and using `securityDefinitions`, it breaks our client 😨 
**Solution**
With this PR we check for that field on import 😎 
https://petstore.swagger.io/v2/swagger.json
test that spec on https://client.scalar.com vs our preview 😎 
**edit** Amrit brought up that we need to handle this in the upgrade actually 🤯

fix(api-client): add missing securityDefinitions check on import

---

packages/components/src/components/ScalarMarkdown/test.md

This URL is breaking the Markdown Link check in CI.
We miss you Aaron 🥹

fix(components): inactive url in markdown example

---

examples/api-client/index.html

now we have a favicon for https://client.scalar.com

fix(client.scalar.com): add missing favicon to client.scalar.com

---

.github/workflows/ci.yml

For security reasons secrets aren’t available in PRs coming from forks.
Let’s skip steps that require secrets, so they don’t fail for external contributions.

ci: don’t run jobs with secrets in forks

---

.changeset/fresh-experts-crash.md
.changeset/kind-llamas-drum.md
packages/api-client/src/views/Request/RequestSidebar.vue
packages/components/src/components/ScalarIcon/icons/Scribble.svg
packages/components/src/components/ScalarIcon/icons/icons.ts

this pr adds draft collection a scribble icon as suggested by @cameronrohani

feat(api-client): squiggly icon for drafts

---

.changeset/tasty-timers-add.md
packages/api-client/src/views/Request/RequestSidebar.vue

this pr updates the empty sidebar item content introduced in #3279 to be re-introduced once their import is supported.

fix(api-client): sidebar empty state

---

.changeset/good-rabbits-invite.md
packages/api-client/src/views/Request/ResponseSection/ResponseEmpty.vue
packages/api-client/src/vite-env.d.ts
packages/api-client/vite.config.ts

fix(api-client): add correct version number in ascii preview

---

.changeset/empty-snails-vanish.md
packages/api-client/src/components/AddressBar/AddressBarServer.vue

**Problem**
Currently, you couldn't see the add servers if there was only 1 server in the address bar
**Solution**
With this PR we bypass this logic and show all options when in the api client

fix(api-client): allow to add servers in read only mode

---

.changeset/khaki-cheetahs-doubt.md
packages/openapi-parser/src/utils/resolveReferences.test.ts
packages/openapi-parser/src/utils/resolveReferences.ts

**Problem**
Currently, openapi-parser does not support self references in `$ref` properties  e.g. openapi.json cannot reference an object with `./openapi.json#/parameters/Parameter` (I think it gets stuck in a loop of circular references). Whilst this is a bit of a weird way of doing a reference, I don't believe it's against the spec (https://json-schema.org/draft/2020-12/json-schema-core#ref) and I've come across a few instances of this in the [Azure API spec](https://github.com/Azure/azure-rest-api-specs/blob/ad60d7f8eba124edc6999677c55aba2184e303b0/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2016-10-10/apimanagement.json#L49).
**Solution**
This PR adds a simple check during reference resolution to see if the reference prefix matches the current filename. …

feat(openapi-parser): self reference the document

---

packages/config/package.json

The CLI is broken, because we didn’t publish the `@scalar/config` package, let’s fix this. :)
I published manually to fix the CLI, this PR sets it to public for future releases.

chore: make `@scalar/config` package public

---

README.md

adding a fun lil animation to the github readme 🤷 ...
you ever wonder what your top 10 GitHub contributors for september would look like projected on a pillar in a room in html/css in a foreignobject in a svg in a img in a readme.md file on your GitHub?

docs: add image to GitHub contributor section

---

.changeset/two-tigers-enjoy.md
packages/api-client/src/libs/send-request.ts

fixes https://github.com/scalar/scalar/issues/3303
as per https://www.rfc-editor.org/rfc/rfc7231#section-4.1
before:
```
curl 'https://sandbox.scalar.com/test' \
-X 'patch' \
-H 'accept: */*' \
-H 'accept-language: en-US,en;q=0.9' \
-H 'content-length: 0' \
-H 'content-type: application/json' \
-H 'origin: https://sandbox.scalar.com' \
-H 'priority: u=1, i' \
-H 'referer: https://sandbox.scalar.com/p/GcxDQ' \
-H 'sec-ch-ua: "Google Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"' \
-H 'sec-ch-ua-mobile: ?0' \
-H 'sec-ch-ua-platform: "macOS"' \
-H 'sec-fetch-dest: empty' \
-H 'sec-fetch-mode: cors' \
-H 'sec-fetch-site: same-origin' \
-H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36'
```
after
``` …
```

fix(api-client): uppercase method on request send, fix #3303

---

.github/workflows/update-contributors.yml

**Problem**
This workflow runs at 3pm also on forks, which can be annoying as the job will fail.
**Solution**
This PR prevents the workflow from running on forks.

ci: skip update-contributors workflow on forks

---

.changeset/eleven-tigers-mix.md
packages/api-client/src/libs/create-client.ts
packages/api-reference/src/components/ApiClientModal.vue
packages/api-reference/src/features/BaseUrl/BaseUrl.vue
packages/api-reference/src/features/BaseUrl/ServerForm.vue
packages/api-reference/src/features/BaseUrl/ServerUrlSelect.vue

Synchronizes the selected server in the references with the selected server in the api client.
I'm not sure if this is the preferred callback pattern but I did my best to keep it simple and clean up the server selector a little bit. I wasn't sure how to set up variables to test that part @hanspagel?
https://github.com/user-attachments/assets/f2e6cbbc-e4a0-4eca-bfb7-a9e329528ad6

fix(api-references): selected server doesn’t update the API client, fix #2830

---

.changeset/empty-donkeys-tan.md
.changeset/lemon-shoes-judge.md
packages/api-reference/src/legacy/components/SecurityScheme.vue
packages/galaxy/src/specifications/3.1.yaml

The reference currently doesn't support the OAuth Authorization Code flow due to an issue in the `SecurityScheme.vue` component. The password flow scopes have a non-null assertion, which prevents the Authorization Code flow from being rendered properly. This issue was reported in #1960.
This PR modifies the `SecurityScheme.vue` component to correctly support the Authorization Code flow. Additionally, it adds an Authorization Code flow example to the galaxy spec for testing and demonstration purposes.
- Updated `SecurityScheme.vue` to handle Authorization Code flow rendering
- Added Authorization Code flow example to the galaxy spec
- Removed unnecessary non-null assertion for password flow scopes
- Fixes #1960: OAuth Authorization Code bug
- Verified that the Authorization Code flow now …

fix(api-reference): OAuth authorization code flow rendering

---

.changeset/olive-roses-cough.md
packages/api-client/src/components/CommandPalette/CommandActionForm.vue
packages/api-client/src/components/CommandPalette/CommandActionInput.vue
packages/api-client/src/components/CommandPalette/CommandPaletteCollection.vue
packages/api-client/src/components/CommandPalette/CommandPaletteExample.vue
packages/api-client/src/components/CommandPalette/CommandPaletteImport.vue
packages/api-client/src/components/CommandPalette/CommandPaletteRequest.vue
packages/api-client/src/components/CommandPalette/CommandPaletteServer.vue
packages/api-client/src/components/CommandPalette/CommandPaletteTag.vue
packages/api-client/src/components/CommandPalette/CommandPaletteWorkspace.vue
packages/api-client/src/components/CommandPalette/TheCommandPalette.vue
packages/themes/src/variables.css

this pr adds the following enhancements:
- focus on first result when conducting command search
- return on global menu on delete key from a command
- enhances styles and fix border opacity
https://github.com/user-attachments/assets/3435ca91-ddd7-4fc8-83b9-061d4bb9e1c2

feat(api-client): command palette navigation

---

.changeset/chilly-cycles-refuse.md
packages/types/package.json
packages/types/src/index.ts

I tried updating this package, [elysia-swagger](https://github.com/elysiajs/elysia-swagger), to use @scalar/types, but there was an error about a missing declaration file. This PR will fix that.

chore(types): add point to declaration file

---

CODEOWNERS

This is a suggestion to add @xC0dex as a code owner, so he’ll be auto-assigned for .NET PRs as a reviewer together with @marclave.

chore(Scalar.AspNetCore): add @xC0dex as an additional code owner

---

.changeset/moody-kiwis-learn.md
examples/api-client/vite.config.ts.js
packages/api-client/src/libs/create-fetch-body.test.ts
packages/api-client/src/libs/create-fetch-headers.test.ts
packages/api-client/src/libs/create-fetch-query-params.test.ts
packages/api-client/src/libs/create-request-operation.test.ts
packages/api-client/src/libs/decode-buffer.test.ts
packages/api-client/src/libs/send-request.ts

This PR adds a few more tests around `createRequestOperation` and the used helpers.
Just one code change: We’re trimming whitespace from the header name now.
Note: I’ve also added one to test for the uppercase request method added in #3305, but I didn’t enable it, because it requires more code changes. Will ff with a separate PR.

chore(api-client): add more tests

---

packages/scalar.aspnetcore/README.md
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarEndpointRouteBuilderExtensions.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Mapper/ScalarOptionsMapper.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/ScalarConfiguration.cs
packages/scalar.aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarEndpointTests.cs
packages/scalar.aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarOptionsExtensionsTests.cs
packages/scalar.aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarOptionsMapperTests.cs

This PR increases the code coverage of the `Scalar.AspNetCore` to 💯%.
I also updated one link in the Readme to target the correct docs.

test(Scalar.AspNetCore): Increase Code Coverage

---

.changeset/sharp-walls-bathe.md
packages/api-reference/src/features/ExampleResponses/ExampleResponse.vue
packages/oas-utils/src/spec-getters/getExampleFromSchema.test.ts
packages/oas-utils/src/spec-getters/getExampleFromSchema.ts

I’m playing around with a huge OpenAPI document with huge schemas. Find the screenshot of a perf profile for opening a tag. The big blue box is `getExampleFromSchema` taking more than 1s:
This PR tries to improve the performance and the results are amazing: The new implementation is 1.000× faster than what we had before.

chore(oas-utils): `getExampleFromSchema` performance improvements

---

packages/code-highlight/src/code/highlight.ts

There’s an error in the console when the auth credentials are shorter than 3 characters. It’s saying that we won’t mask the credentials in that case.
I can’t think of any scenario where 2 characters are confidential anyway and no one will notice when it’s in the browser console, I think we can remove it.

chore: remove credentials min length error

---

.changeset/slow-bees-fix.md
packages/api-client/src/store/store.ts

This seems to be causing issues in the guides because it sometimes clears the contents of the spec, you can test it by setting `content: ''` in the example.

fix(api-client): don't error if there aren't any collections

---

.changeset/nine-beers-sip.md
packages/api-client/src/views/Request/RequestSection/RequestSection.vue
packages/api-client/src/views/Request/ResponseSection/ResponseSection.vue

this pr updates the request and response section order and naming as seen below:
- `all` displayed first
- `variables` for path variables section instead of request
**before**
**after**

feat(api-client): request and response section

---

.changeset/silent-ladybugs-matter.md
packages/api-client/src/components/AddressBar/AddressBarServer.vue

We showed the server dropdown even if empty to allow adding servers in #3297, but this leaves an empty gap:
This reverts that change and you can just add servers from the command palette

fix(api-client): remove servers dropdown if empty

---

.changeset/proud-meals-return.md
packages/api-client/src/components/Sidebar/Sidebar.vue
packages/api-client/src/views/Request/RequestSidebar.vue

this pr fixes the sidebar call to action position that is not visually accessible from cookies, anvironment views:
**before**
**after**

fix(api-client): sidebar cta position

---

.github/workflows/ci.yml

During the last release, I noticed [a warning](https://github.com/scalar/scalar/actions/runs/11149128322/job/30987323086#step:9:8) in the `aspnetcore-publish` job. I've updated the `working-directory` to target the .NET project instead of the .NET solution to get rid of the warning.

ci: switch working directory for aspnetcore-publish job

---

.changeset/plenty-dancers-breathe.md
packages/api-client/src/libs/send-request.ts

fixes #3124 
This PR addresses an issue with Basic Authentication header formatting when the password is empty. According to [RFC 7617](https://datatracker.ietf.org/doc/html/rfc7617), the Basic Auth header must include the colon `(:)` separator between the username and password, even if the password is empty.
- Ensured that the username:password format is maintained by appending a colon after the username, even when the password is empty.
This change ensures compliance with the Basic Auth standard and prevents potential authorization issues when no password is supplied.

fix(api-client): Basic Auth header format for empty passwords

---

.changeset/clean-zoos-battle.md
documentation/configuration.md
packages/api-reference/.gitignore
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/Sidebar/Sidebar.vue
packages/api-reference/src/hooks/useSidebar.test.ts
packages/api-reference/src/hooks/useSidebar.ts
packages/types/src/legacy/reference-config.ts

feat(api-reference): add `operationsSorter` to the configuration

---

.changeset/odd-spoons-learn.md
packages/hono-api-reference/README.md
packages/hono-api-reference/src/honoApiReference.test.ts
packages/nestjs-api-reference/README.md
packages/nextjs-api-reference/README.md
packages/nextjs-api-reference/src/ApiReference.ts

This PR updates the configuration to allow the user to specify the `@scalar/api-reference` CDN version in the `next-js` integration. It also adds documentation for pinning the version in other integrations.
Maybe we add the cdn url as an option in the universal configuration object?
It was proposed to add an option in vite config to pin the versions but I'm not seeing any specific advantages over specifying the version in the script tag

feat(nextjs-api-reference): pin cdn version

---

.github/dependabot.yml

I love dependabot, but let’s limit it to nuget security updates for now. :)

chore: nuget security updates only

---

.changeset/smart-sloths-pump.md
packages/api-client/src/components/ContextBar.vue
packages/api-client/src/components/EnvironmentSelector/EnvironmentSelector.vue
packages/api-client/src/components/SideNav/SideNav.vue
packages/api-client/src/components/TopNav/TopNav.vue
packages/api-client/src/components/ViewLayout/ViewLayoutCollapse.vue
packages/api-client/src/views/Request/RequestSection/RequestSection.vue
packages/api-client/src/views/Request/RequestSubpageHeader.vue
packages/api-client/src/views/Request/components/WorkspaceDropdown.vue

overall style OCD pr:
<table>
<thead>
<td align="center">
Top Right Buttons
</td>
</thead>
<tbody>
<td>
<table>
<thead>
<td>Before</td>
<td>After</td>
</thead>
<tbody>
<td>
</td>
<td>
</td>
</tbody>
</table>
</td>
</tbody>
</table>
<table>
<thead>
<td align="center">
Sidenav Toggle
</td>
</thead>
<tbody>
<td>
<table>
<thead>
<td>Before</td>
<td>After</td>
</thead>
<tbody>
<td>
</td>
<td>
</td>
</tbody>
</table>
</td>
</tbody>
</table>
<table>
<thead>
<td align="center">
Section + Subsections
</td>
</thead>
<tbody>
<td>
<table>
<thead>
<td>Before</td>
<td>After</td>
</thead>
<tbody>
<td>
</td>
<td>
</td>
</tbody>
</table>
</td>
</tbody>
</table>

style(api-client): updates overall alignments

---

.changeset/stupid-buckets-dress.md
packages/api-client/package.json
packages/api-client/src/layouts/App/ApiClientApp.vue
packages/api-client/src/layouts/App/hotkeys.ts
packages/api-client/src/layouts/Web/ApiClientWeb.vue
packages/api-client/src/layouts/Web/create-api-client-web.test.ts
packages/api-client/src/layouts/Web/create-api-client-web.ts
packages/api-client/src/layouts/Web/index.ts
packages/api-client/src/libs/event-busses/hot-keys-bus.ts
projects/client-scalar-com/src/main.ts

After chatting with @marclave we decided to remove the tabs on `client.scalar.com` and only have them in the electron app similar to what linear does.
It made the most sense to me to split these into two packages one for the app and one for the web version.
https://github.com/user-attachments/assets/0d838c66-c5b1-4816-bf84-c7842537b7c2
https://github.com/user-attachments/assets/218c2dec-4dae-4e55-815e-7ae9163f17df

feat(api-client): remove tabs on client.scalar.com

---

cloudbuild.yaml
packages/snippetz/Dockerfile
packages/snippetz/package.json
packages/snippetz/playground/index.html
packages/snippetz/playground/package.json
packages/snippetz/playground/src/App.vue
packages/snippetz/playground/src/components/CodeExample.vue
packages/snippetz/playground/src/main.ts
packages/snippetz/playground/src/style.css
packages/snippetz/playground/tsconfig.build.json
packages/snippetz/playground/vite.config.ts
pnpm-lock.yaml
pnpm-workspace.yaml

Currently, we don't have a playground example for the @scalar/snippetz package in the monorepo.
This PR migrates the old snippetz demo, containerizes, and deploys it.

feat(snippetz): migrate and deploy snippetz playground

---

.changeset/unlucky-fireants-sneeze.md
packages/api-client/src/components/AddressBar/AddressBar.vue

this pr updates placeholder display according to active server presence:
**before**
**after**

fix(api-client): address bar placeholder

---

.changeset/clever-baboons-confess.md
packages/api-client/src/components/CommandPalette/TheCommandPalette.vue

this pr removes the command palette commands label as suggested by @marclave + increases search icon size to maintain icon alignment consistency, as seen below:
**before**
**after**

fix(api-client): command palette label

---

.changeset/friendly-rocks-wait.md
packages/api-reference/src/components/Content/ClientLibraries/ClientLibraries.vue
packages/api-reference/src/components/Content/Operation/Operation.vue
packages/api-reference/src/components/Content/Operation/OperationAccordion.vue
packages/api-reference/src/features/ExampleRequest/ExampleRequest.vue

Cleans up the UI when there aren't any clients / example so we still show a path and the test request button.
Fixes #3380

fix(api-reference): show path and test request when hiddenClients is true

---

.changeset/shaggy-steaks-enjoy.md
packages/api-client/src/layouts/App/ApiClientApp.vue
packages/api-client/src/layouts/Web/ApiClientWeb.vue
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/themes/src/index.ts
packages/themes/src/presets/default.css
packages/themes/src/variables.css

Looks like we were injecting a copy of `variables.css` from `@scalar/themes` into the `scalar-theme` layer, we already import `variables.css` into the `scalar-base` layer as part of `@scalar/themes/style.css`.
It's important it's only in the `scalar-base` layer otherwise there's a risk of the default variables overriding theme variables (which is the issue in #3388). This updates the precedence to be:
1. Any user styles that they add to the page outside of a css layer
2. The theme injected into the `scalar-theme` css layer via [`getThemeStyles()`](https://github.com/scalar/scalar/blob/6279c5977c5067f21c61d4d91d7963f4a4b9a384/packages/themes/src/index.ts#L114) (includes any selection color overrides)
3. The variables & default (base) theme injected into the `scalar-base` css layer by …

fix(themes): remove variables from theme layer and move selection to default theme

---

.changeset/late-chairs-scream.md
packages/api-client/src/libs/extractAttachmentFilename.test.ts
packages/api-client/src/libs/extractAttachmentFilename.ts
packages/api-client/src/views/Request/ResponseSection/ResponseBody.vue
packages/api-client/src/views/Request/ResponseSection/ResponseBodyDownload.vue

This update adds the capability to download a file response with the correct filename extracted from the response headers. The feature ensures that when a file is downloaded via the API client, the filename is properly set according to the content disposition, providing a more user-friendly experience.
before
https://github.com/user-attachments/assets/368e48c7-cc04-403e-809b-19e3fa890c23
after
https://github.com/user-attachments/assets/938de78d-e0b8-498b-a94f-a16485653b00

feat(api-client): handle file download with filename in response

---

packages/object-utils/src/nested/nested.test.ts
packages/object-utils/src/nested/nested.ts

There was a critical logic error in determining the end state for nested setting. This corrects the logic.

fix(object-utils): setNested doesn’t work with arrays

---

.changeset/fresh-frogs-thank.md
packages/api-client/src/components/AddressBar/AddressBar.vue
packages/api-client/src/components/AddressBar/AddressBarHistory.vue
packages/api-client/src/components/AddressBar/AddressBarServer.vue
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/components/CommandPalette/TheCommandPalette.vue
packages/api-client/src/components/ContextBar.vue
packages/api-client/src/components/Sidebar/Sidebar.vue
packages/api-client/src/components/ViewLayout/ViewLayout.vue
packages/api-client/src/components/ViewLayout/ViewLayoutSection.vue
packages/api-client/src/layouts/App/ApiClientApp.vue
packages/api-client/src/layouts/Modal/ApiClientModal.vue
packages/api-client/src/views/Cookies/Cookies.vue
packages/api-client/src/views/Environment/EnvironmentVariableDropdown.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuth.vue
packages/api-client/src/views/Request/RequestSection/RequestTableTooltip.vue
packages/api-client/src/views/Request/RequestSidebar.vue
packages/api-client/src/views/Request/RequestSidebarItem.vue
packages/api-client/src/views/Request/ResponseSection/ResponseLoadingOverlay.vue

I faced a z-index issue in another branch, so I tried to debug it and found a lot of z-index layers throughout the API client. Some in Tailwind, some in CSS, some even conflicting with eachother.
I tried removing all and it didn’t look too bad, so @hwkr added a Tailwind config and reintroduced a z-index where actually needed.
We should test this thoroughly, though. I might have missed places where we need to add it again. Can you all help me with that? 👀 Just leave a screenshot here and we’ll fix it.

fix(api-client): too many z-index layers

---

.changeset/hip-avocados-count.md
packages/api-reference/src/components/ApiReferenceLayout.vue

This one has been a little annoying and I could have sworn I fixed it before. Basically on initial load lazy loading works fine, BUT on subsequent loads there was a strange content jump happening. Turns out this was the browser remembering the scrollPosition, which we don't want as we manually handle it with lazy loading.
enter `history.scrollRestoration = 'manual'`
Before:
https://github.com/user-attachments/assets/b9d9c8d0-4d21-4f0d-b5f2-2d5edc9c7548
After:
https://github.com/user-attachments/assets/cacad2cd-801c-4a52-8888-0d3c11d12e30

fix(api-reference): lazy loading content jump

---

CODEOWNERS

I think right now we're always adding all the default codeowners on every PR that includes a changeset (which most of them do) which I don't think is what we want?

chore: remove changeset codeowners

---

.changeset/weak-terms-reply.md
packages/object-utils/package.json
packages/object-utils/src/mutator-record/debounce.test.ts
packages/object-utils/src/mutator-record/debounce.ts
packages/object-utils/src/mutator-record/handlers.ts
pnpm-lock.yaml

Currently, the `object-utils` package depends on `@vueuse/core` for its `useDebounceFn` 
This PR removes the dependency, `@vueuse/core`, from `@scalar/object-utils` by creating a new dependency-less debounce function for use with mutations.

feat(object-utils): new debounce function without dependencies

---

.changeset/gentle-years-teach.md
packages/openapi-parser/src/utils/traverse.ts
packages/openapi-parser/src/utils/upgradeFromThreeToThreeOne.test.ts
packages/openapi-parser/src/utils/upgradeFromThreeToThreeOne.ts

Currently, when upgrading an OpenAPI document to 3.1, we’re transforming all `example` attributes to an `examples` object. For schemas, it’s more common to use arrays.
With this PR we’re transforming them to arrays, and not to objects anymore (for schemas only).
Note: Probably easier to review the commits, than just the changed files.
See #3373

chore(openapi-parser): make `examples` in schemas an array on upgrade, fix #3373

---

.changeset/kind-monkeys-clap.md
packages/api-client/src/components/EnvironmentSelector/EnvironmentSelector.vue
packages/api-client/src/components/Sidebar/Sidebar.vue
packages/api-client/src/components/Sidebar/SidebarButton.vue
packages/api-client/src/components/TopNav/TopNav.vue
packages/api-client/src/components/ViewLayout/ViewLayout.vue
packages/api-client/src/components/ViewLayout/ViewLayoutContent.vue
packages/api-client/src/components/ViewLayout/ViewLayoutSection.vue
packages/api-client/src/views/Request/RequestSidebar.vue
packages/api-client/src/views/Request/RequestSubpageHeader.vue

this pr updates style in api client in order to fixes and enhances responsiveness glitches such as
- view header button width
- alignments
- double borders
- border radiuses
as seen below:
**before**
**after**

style(api-client): enhances responsiveness

---

CODEOWNERS

Looks like you can’t have users without full write permission in the `CODEOWNERS` file, sorry @xC0dex. :(
I need to find another way to automatically assign you as a reviewer.

chore: remove user without write permission from CODEOWNERS

---

.changeset/great-singers-lay.md
packages/api-reference/src/components/ApiReferenceLayout.vue

In some cases, the download was triggered twice. We register an event listener for the download, but we don’t unregister ist when the component is unmounted. This PR fixes it.

fix(api-reference): duplicate download event listener

---

.changeset/grumpy-feet-beam.md
packages/openapi-parser/src/utils/upgradeFromTwoToThree.test.ts
packages/openapi-parser/src/utils/upgradeFromTwoToThree.ts

With this PR Swagger 2.0 securityDefinitions are upgraded to the OpenAPI 3.0 structure, too.
Example: https://petstore.swagger.io/v2/swagger.json (breaks the API client without the PR)

feat(openapi-parser): upgrade Swagger 2.0 securityDefinitions

---

.github/workflows/ci.yml

The API client doesn’t deploy on push to main anymore.
I’ve recently added a check to CI, whether it’s running in a fork or not. This is using the `github.event.pull_request`, but the `pull_request` event is not available in `main`, so the check fails.
This PR tries to fix it.
It‘ll still run for the main branch in forks, but we can deal with that in a separate PR.

ci: deploy API client on push to main

---

.changeset/happy-wolves-glow.md
packages/api-reference/src/components/Content/Content.vue
packages/api-reference/src/components/Content/Tag/TagList.vue
packages/api-reference/src/components/Content/Tag/index.ts

Renders the tags based on the tag group configuration if one is set. I looked at adding the tag group titles but it seemed like maybe too much. We can add them though if we want.
Test file [tagGroups.yaml.zip](https://github.com/user-attachments/files/17302686/tagGroups.yaml.zip)

fix(api-reference): render tags in tag group order if set

---

.changeset/new-chairs-allow.md
packages/api-client/src/components/CommandPalette/CommandPaletteServer.vue
packages/api-client/src/components/CommandPalette/TheCommandPalette.vue

this pr updates the command palette server collection dropdown displays and logic, in order to display a create collection button if no collection exists + updates the submit button state:
**before**
**after**

fix(api-client): command palette server collection

---

.changeset/neat-beers-dress.md
packages/api-client/src/components/ViewLayout/ViewLayoutCollapse.vue
packages/api-client/src/views/Request/ResponseSection/ResponseBodyVirtual.vue
packages/api-client/src/views/Request/ResponseSection/ResponseSection.vue
packages/components/src/components/ScalarVirtualText/ScalarVirtualText.spec.ts
packages/components/src/components/ScalarVirtualText/ScalarVirtualText.stories.ts
packages/components/src/components/ScalarVirtualText/ScalarVirtualText.vue
packages/components/src/components/ScalarVirtualText/index.ts
packages/components/src/index.ts
packages/oas-utils/src/helpers/parse.ts

We need a way to handle giant responses. Responses so big we can't even show them in plain text. So I added this virtual scroller.
Whats left (for a follow up PR):
- we need to play with the threshold to get it right
- also the scrollbar/height calculations don't quite work
test with `https://raw.githubusercontent.com/json-iterator/test-data/refs/heads/master/large-file.json`
Before:
browser crash
After:

feat(api-client): added virtual text component and implement it for big responses

---

.changeset/wise-doors-hide.md
examples/fastify-api-reference/src/index.ts
packages/fastify-api-reference/src/fastifyApiReference.test.ts
packages/fastify-api-reference/src/fastifyApiReference.ts

Currently, our Fastify integration throws an error if `ignoreTrailingSlash` is set to `true`.
If this is set, Fastify registers both versions of a route (with and without a trailing slash), which we do too. So it correctly throws an error, because the route is already registered.
This PR should fix it. :)
Fixes #3408

fix(fastify-api-reference): does not work with `ignoreTrailingSlash: true`

---

.changeset/slow-comics-melt.md
packages/fastify-api-reference/src/fastifyApiReference.ts

This PR adds `*` wildcard CORS headers to the OpenAPI documents our Fastify package is exposing.
Makes it easier to access them without a proxy. :)
Extracted from #3423.

feat(fastify-api-reference): CORS headers for the OpenAPI documents

---

.changeset/tall-kangaroos-jump.md
packages/openapi-types/package.json
pnpm-lock.yaml

I’ve had problems to build the `@scalar/openapi-types` locally, switching to the build tooling scripts for types:build and types:check helped.
Ah, and I’ve had to fix the pnpm lock file for whatever reason.

chore(openapi-types): use build tooling scripts for types

---

.changeset/pink-cats-push.md
packages/api-client/package.json
packages/api-client/src/libs/create-request-operation.test.ts
packages/api-client/src/libs/decode-buffer.test.ts
packages/api-client/src/libs/send-request.test.ts
packages/api-client/src/libs/send-request.ts
packages/api-client/src/views/Request/ResponseSection/ResponseSection.vue
packages/oas-utils/src/entities/spec/requests.ts

Fixes #3467
Switched the unit of measurement to bytes and dropped the threshold to 20k. Lets see how this does.
Also removed some Json parsing since it was redundant. Will fix up the tests

fix(api-client): lower syntax highlighting threshold on responseBody

---

.changeset/shy-bobcats-try.md
packages/api-client/src/components/SideNav/SideHelp.vue
packages/api-client/src/components/SideNav/SideNav.vue

this pr adds gap to sidenav components and updates the hover color on sidehelp:
**before**
**after**

style(api-client): gap between sidebar entries

---

.changeset/yellow-singers-count.md
packages/oas-utils/src/entities/spec/spec-objects.ts

fix #3463 
Turns out we already had a default, was just missing optional()

fix(api-client): add collection.info.version optional

---

.changeset/thirty-paws-sleep.md
packages/themes/src/reset.css

this pr removes the focus visible style added in the theme reset stylesheet in #3435 in order to fix ui focus issue, while we found another better approach to it.
**before**
in reference
in api client
**after**
in reference
in api client

fix(themes): reset

---

packages/api-client-app/package.json
pnpm-lock.yaml

This needs to be up to date to stay compatible with the ToDesktop Cloud.
> Run pnpm --filter scalar-api-client todesktop:release:ci
>
> scalar-api-client@0.1.61 todesktop:release:ci /home/runner/work/scalar/scalar/packages/api-client-app
> todesktop release --latest --force
> 
> Your version of @todesktop/cli is out of date.
> Run npm install --save-dev @todesktop/cli to update to v1.9.6.

chore: update `@todesktop/cli`

---

.changeset/big-candles-hammer.md
packages/api-client/src/views/Request/RequestSubpageHeader.vue

this pr fixes a duplicated utility class introduced after a rebase:
**before**
**after

fix(api-client): removes duplicated utility class in request header

---

.changeset/calm-coats-hammer.md
packages/api-client/src/layouts/App/ApiClientApp.vue
packages/api-client/src/views/Cookies/Cookies.vue
packages/api-client/src/views/Request/RequestSidebar.vue
packages/api-client/src/views/Request/RequestSidebarItem.vue

add back sidebar indent lines + make stroke width of chevrons + icons feel more 1:1
after:
before:

fix: sidebar indent lines and stroke thickness

---

.github/dependabot.yml

This PR enables Dependabot PRs for the `@todesktop/*` dependencies (which we need to keep up to date to stay compatible with the ToDesktop Cloud) and `electron`.

chore(api-client-app): enable Dependabot updates for `@todesktop/*` and `electron`

---

packages/api-client-app/package.json
pnpm-lock.yaml

This PR updates Electron from 31 to 33.
Makes sense to keep Electron (and the bundled Chromium browser) up to date, I’d say.

chore: update to Electron 33

---

.changeset/rude-berries-hunt.md
package.json
packages/api-client/package.json
packages/api-client/playground/web/index.html
packages/api-client/playground/web/main.ts
turbo.json

this pr adds and updates:
- `pnpm dev:web-app` that open the api client web version
- `pnpm dev:app` that open the api client app version
to do so a web app playground has been added in order to use the api client web component that has been introduced in #3351 to reflect the web usage locally.
**why**
currently when using `pnpm dev:app`, the api client launch the app version that does not reflect the web usage.

feat(api-client): add web app playground

---

.changeset/breezy-numbers-jam.md
packages/api-client/src/components/CommandPalette/TheCommandPalette.vue
packages/api-client/src/components/ImportCollection/ImportCollectionModal.vue
packages/api-client/src/components/ImportCollection/ImportNowButton.vue
packages/api-client/src/components/ImportCollection/WorkspaceSelector.vue
packages/api-client/src/layouts/App/create-api-client-app.test.ts
packages/api-client/src/layouts/Modal/create-api-client-modal.test.ts
packages/api-client/src/layouts/Web/create-api-client-web.test.ts
packages/components/src/components/ScalarModal/ScalarModal.vue

Due to some how we have some of our accessibility stuff set up opening the command palette from inside another modal (e.g. the import modal) is difficult™. This creates a small dialog for creating a new workspace from inside the new import modal + some other modal related cleanup.
https://github.com/user-attachments/assets/0d6261a2-c5cc-47ba-80ef-21ddc46bf91f
Also on the todo is an overhaul of all the modals to bring them into alignment soon™

feat(api-client): create custom workspace selector

---

.github/dependabot.yml

Dependabot was complaining because the npm configs had overlapping directories. Let’s see if this PR helps.

fix: broken dependabot config, overlapping directories

---

.changeset/loud-deers-double.md
packages/api-client/package.json
packages/api-reference/package.json
packages/api-reference/playground/examples/src/App.vue
packages/hono-api-reference/package.json
pnpm-lock.yaml

This PR removes some unused dependencies I’ve found in `@scalar/api-reference` and `@scalar/api-client`.

chore: remove unused dependencies

---

README.md
documentation/integrations/laravel-scribe.md

As composer (PHP package manager) doesn’t support monorepos, our Laravel package (secretly launched) has to live in its own repository. This PR makes sure it’s mentioned in the appropriate places.

docs: add  `Scalar for Laravel` to the READMEs

---

.changeset/itchy-bobcats-look.md
packages/api-reference-react/src/ApiReferenceReact.tsx
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/helpers/provideSymbols.ts
packages/api-reference/src/standalone.ts
packages/docusaurus/src/index.ts
packages/express-api-reference/src/expressApiReference.ts
packages/fastify-api-reference/src/fastifyApiReference.ts
packages/hono-api-reference/src/honoApiReference.ts
packages/nestjs-api-reference/src/nestJSApiReference.ts
packages/nextjs-api-reference/src/ApiReference.ts
packages/nuxt/src/runtime/components/ScalarApiReference.vue
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarEndpointRouteBuilderExtensions.cs
packages/scalar_fastapi/scalar_fastapi/scalar_fastapi.py
packages/types/src/legacy/reference-config.ts

This PR adds an `_integration` identifier to the API reference configuration. All our official integration pass a string (for example `'nextjs'`) to `@scalar/api-reference` now.
This gives us the opportunity to make framework-specific optimisations or add some helpful debug information in the future.

feat(api-reference): add integration identifiers

---

.changeset/brown-birds-join.md
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/components/ContextBar.vue
packages/api-client/src/components/EnvironmentSelector/EnvironmentSelector.vue
packages/api-client/src/components/SideNav/SideHelp.vue
packages/api-client/src/components/SideNav/SideNavLink.vue
packages/api-client/src/components/Sidebar/Sidebar.vue
packages/api-client/src/components/Sidebar/SidebarList.vue
packages/api-client/src/components/Sidebar/SidebarToggle.vue
packages/api-client/src/components/TopNav/TopNav.vue
packages/api-client/src/layouts/App/ApiClientApp.vue
packages/api-client/src/views/Request/Request.vue
packages/api-client/src/views/Request/RequestSection/RequestSection.vue
packages/api-client/src/views/Request/RequestSidebar.vue
packages/api-client/src/views/Request/RequestSubpageHeader.vue
packages/api-client/src/views/Request/ResponseSection/ResponseSection.vue
packages/api-client/src/views/Request/components/WorkspaceDropdown.vue

fix sidebar between 780 - 800px 🙃 
- fix codemirror placeholder colors
- reduce details in request / response
- better aligned 'all / active filter' with global enviornment
- move workspace selector to top bar
- aligned modal x (close) button with filter 
- made modal x and sidebar toggle have more contrast
- improved background colours for tabs across all themes

fix: ui tweaks and fixes

---

.changeset/short-cats-camp.md
packages/themes/src/reset.css

I'm not sure why but having the vendor prefixes here was breaking the placeholder selector. This seems to fix it in chrome and has [good compatibility](https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder#browser_compatibility).

fix(themes): remove vendor prefixes for input placeholder

---

.changeset/dirty-eels-know.md
packages/api-client-react/playground/App.tsx
packages/api-client-react/playground/main.tsx
packages/api-client-react/src/ApiClientModalProvider.tsx
packages/api-client-react/src/client-store.ts

Added caching strategy so if you try to load mulitple clients with the same spec.url, it will open the cached one! Had to get a bit hacky to make it work but it works!
To test:
- `cd packages/api-client-react`
- `pnpm dev`
the bottome two buttons should open different routes, the top button should re-open the last route

feat(api-client-react): add caching strategy to allow for multiple clients

---

.changeset/ninety-yaks-tie.md
packages/api-client/src/store/workspace.ts

this pr fixes the default workspace request by setting the request uid to its request example in order to have the request history display.
**before**
**after**

fix(api-client): workspace default request

---

packages/api-client/src/components/CommandPalette/CommandPaletteImport.vue
packages/api-client/src/components/CommandPalette/TheCommandPalette.vue

Currently, we say “Import Collection”, but we’re actually importing OpenAPI documents. That’s why I propose a new label.

chore(api-client): update import collection wording

---

.changeset/fuzzy-cameras-impress.md
packages/api-client/src/store/store.ts

this pr updates the value of the api client's default proxy setting and adds :
- in development, proxy is disabled by default
- in production, proxy is enabled by default

fix(api-client): proxy setting

---

.github/actions/build/action.yml
.github/workflows/ci.yml
.github/workflows/deploy-examples.yml
.github/workflows/lint-icons.yml
.github/workflows/lint-markdown-files.yml
.github/workflows/lint-pr.yml
.github/workflows/test-cdn-jsdelivr.yml
.github/workflows/test-cdn-local.yml
.github/workflows/test-nuxt-integration.yml
.github/workflows/update-contributors.yml
.github/workflows/validate-openapi-file.yml

Our GitHub Action workflows use actions from other repositories, and so far, we’ve referenced them by version tags. However, tags can be changed, which means someone could add unwanted code to an existing tag and compromise any repository using it.
To reduce this risk, it’s a good practice to pin actions to a specific commit hash. This ensures that the exact version of the action is used, lowering the chances of security issues or unexpected changes.

ci: pin all actions to a commit hash

---

.changeset/cuddly-actors-change.md
packages/api-client-app/src/main/index.ts
packages/api-client-app/src/main/resolve.ts

The import of @scalar/import doesn’t work. I've had to copy the file in the package as a quick fix.
Next week: proper fix

fix(api-client-app): can not start Electron app

---

.changeset/short-experts-breathe.md
packages/api-client-app/src/main/index.ts

This PR exists and restarts the app when an update is found after manually clicking “Check for updates”.
Requires #3542 to run the Electron app locally. Simulate an update with `pnpm dev:update`, ignore the first popup, select Check for updates in the menu.
Next week: proper UX

fix(api-client-app): check for updates doesn’t do anything

---

.changeset/eight-bottles-rescue.md
packages/api-client/src/libs/send-request.ts
packages/api-client/src/libs/string-template.ts

before:
server variable requests would fail
now they use defaults :)

fix: support server variables in request sending

---

.changeset/sixty-suns-pay.md
packages/api-client/src/components/AddressBar/AddressBarServerItem.vue
packages/api-client/src/components/DataTable/DataTableInputSelect.vue
packages/api-client/src/components/EnvironmentSelector/EnvironmentSelector.vue
packages/api-client/src/components/ImportCollection/WorkspaceSelector.vue
packages/api-client/src/views/Request/components/WorkspaceDropdown.vue
packages/components/src/components/ScalarCombobox/ScalarComboboxOption.vue
packages/components/src/components/ScalarListbox/ScalarListbox.vue

this pr fixes the background inconsistencies when using themes in order to favor accent background:
**before**
**after**

style(api-client): active element background

---

.changeset/lazy-buttons-remember.md
packages/openapi-types/src/openapi-types.ts

**Problem**
Currently, the `openapi` field of the OpenAPIV3 Document mistakenly duplicates `3.0.2` and does not include `3.0.3`
```ts
openapi?: '3.0.0' | '3.0.1' | '3.0.2' | '3.0.2';
```
**Solution**
This pr adds `3.0.3` to the allowed values of `openapi` in the OpenAPIV3 Document.

fix(openapi-types): include '3.0.3' in allowed OpenAPIV3 versions

---

.changeset/new-apricots-exist.md
packages/api-client/src/components/ViewLayout/ViewLayout.vue
packages/api-client/src/components/ViewLayout/ViewLayoutContent.vue
packages/api-client/src/views/Request/RequestSubpageHeader.vue
packages/api-client/src/views/Request/ResponseSection/ResponseSection.vue

**Problem**
Large responses are causing heavy input lag in Chromium browsers only, most recently with #3467. This is due to a performance bug in Chromium with the general sibling CSS selector that Tailwind uses for the `divide` classes. When this class is applied to an element with many, many descendants (as is the case with large parsed JSON responses) it causes the browser to halt as it re-renders the style. Firefox and Safari do not have this issue.
**Solution**
With this PR I've manually applied the same style to the two impacted components without using this selector, attempting to keep it as close as possible to the intended look. Also, through running some tests, I've found that Chrome can now render up to 200kb JSON responses, and have increased the threshold accordingly. For …

perf(api-client): improve large response performance in Chromium

---

.changeset/few-shrimps-buy.md
packages/api-client/src/components/CodeInput/codeVariableWidget.ts
packages/api-client/src/views/Request/RequestSection/RequestBody.vue

this pr styles tooltip position/brightness and decreases back the request body content size:
**before**
**after**

style(api-client): tooltip fixtures

---

.changeset/big-cooks-look.md
packages/import/README.md
packages/import/src/resolve.test.ts
packages/import/src/resolve.ts

Oops, sandbox links that contain uppercase letters aren’t resolved by `@scalar/import`. This PR fixes it.
And let’s allow `null` as a value, too. Let’s just try to be as flexible as possible with what we take as an input.

fix(import): sandbox links with uppercase letters can’t be resolved

---

.changeset/green-eyes-act.md
packages/api-client/src/components/DataTable/DataTableCell.vue
packages/api-client/src/views/Request/RequestSection/RequestTableTooltip.vue

this pr fixes #3543 and the dropdown overflow issue within api client data table cell - mistakenly added to fix tooltip gradient visibility, now fixed using full height:
**before**
**after

fix(api-client): data cell dropdown overflow issue

---

.changeset/eleven-frogs-smile.md
packages/api-client/src/components/AddressBar/AddressBar.vue

this pr increases z index on loading background in address bar component, in order to fix color inconsistencies when submitting request without focus as seen below:
**before**
**after**

style(api-client): address bar loading background

---

.changeset/thin-toys-draw.md
packages/api-client/src/components/CodeInput/CodeInput.vue

this pr removes the stopped propagation on key enter within code input, which is preventing the meta+enter action from submitting the request from the address bar focus.

fix(api-client): address bar hotkey submission

---

.github/actions/build/action.yml
.github/workflows/ci.yml
.github/workflows/deploy-examples.yml
.github/workflows/test-cdn-jsdelivr.yml
.github/workflows/test-cdn-local.yml
.github/workflows/test-nuxt-integration.yml
.github/workflows/validate-openapi-file.yml
packages/icons/README.md
packages/mock-server/README.md

Currently, the build action that we use everywhere restores *and* writes to the cache. This produces conflicts.
With this PR we’re making sure, we’re only restoring from the cache. There’s only one place where we write to the Turborepo cache, and this is in the build job of the ci workflow. So after the build was done the first time.
**Results**
1st run: 9m 17s
2nd run: 3m 45s

ci: in the reusable build action, only restore from the cache

---

.changeset/moody-points-juggle.md
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarOptionsExtensions.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Mapper/ScalarOptionsMapper.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Options/ScalarOptions.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/ScalarConfiguration.cs
packages/scalar.aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarOptionsExtensionsTests.cs
packages/scalar.aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarOptionsMapperTests.cs

This PR adds the `_integration` property to the configuration. The .NET integration provides a new `DotNetFlag` property, which is set to `true` by default.

feat(scalar.aspnetcore): add integration configuration property

---

.changeset/early-cobras-fail.md
packages/openapi-parser/src/schemas/v3.1/schema.json

According to the OpenAPI 3.1 spec ([link](https://swagger.io/specification/#:~:text=to%20RFC3986.-,Relative%20References%20in%20URLs,-Unless%20specified%20otherwise)),
> Unless specified otherwise, all properties that are URLs MAY be relative references as defined by [RFC3986](https://tools.ietf.org/html/rfc3986#section-4.2). Unless specified otherwise, relative references are resolved using the URLs defined in the [Server Object](https://swagger.io/specification/#server-object) as a Base URL. Note that these themselves MAY be relative to the referring document.
It seems the v3.0 spec already uses `uri-reference`. This PR updates v3.1 to use the same

fix(openapi-parser): update `uri` types to be `uri-reference` in schema v3.1

---

.changeset/tidy-pandas-tease.md
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/DarkModeToggle/DarkModeToggle.vue
packages/api-reference/src/components/Sidebar/Sidebar.vue
packages/api-reference/src/components/Sidebar/SidebarElement.vue
packages/api-reference/src/features/BaseUrl/ServerUrlSelect.vue

Various improvements to the references sidebar.
https://github.com/user-attachments/assets/06bcf541-fe9b-4825-8060-7f23113395d9
Keep in mind that this is voiceover in Chrome and all screen readers work a little bit differently.
https://github.com/user-attachments/assets/ff082dbf-f242-4591-b497-d510478979f1
https://github.com/user-attachments/assets/d18da811-919e-4259-9ba2-7f3641ea2fcc

fix(api-reference): sidebar a11y improvements

---

.changeset/two-tables-invent.md
packages/api-client/src/layouts/Modal/create-api-client-modal.ts
packages/api-client/src/libs/create-client.ts
packages/api-client/src/libs/send-request.ts
packages/api-client/src/store/import-spec.ts
packages/api-client/src/views/Request/Request.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuth.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestExampleAuth.vue
packages/api-client/src/views/Request/RequestSection/RequestSection.vue
packages/api-reference/index.html
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/features/ApiClientModal/ApiClientModal.vue
packages/api-reference/src/features/ApiClientModal/useApiClient.ts
packages/api-reference/src/legacy/components/SecuritySchemeSelector.vue
packages/oas-utils/src/transforms/import-spec.ts

Closes #3377
1. Pre-fills client auth according to the authentication config object.
2. Syncs up the collection selected auth with the references one.
3. Update the selectedSecuritySchemeUids to come from the collection on the modal, and the request otherwise
This should hold us over until we get a collection page

fix(api-client): prefill auth

---

.changeset/heavy-hotels-grin.md
.changeset/serious-plums-begin.md
packages/api-client-app/src/renderer/index.html
packages/api-client/src/components/SideNav/SideNav.vue
packages/api-client/src/components/TopNav/TopNav.vue
packages/api-client/src/layouts/App/MainLayout.vue
packages/api-client/src/layouts/Web/ApiClientWeb.vue

this pr moves the app top border to the topnav component in order to fix the glitch from the preview modal in #3236, and also sets [overscroll behavior](https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior) and fix icon size consistencies between web / desktop:
**before**
import modal
sidenav icon
**after**
import modal
sidenav icon

style(api-client): top navigation

---

.github/dependabot.yml
.github/workflows/update-contributors.yml

I think it’s fine to have the dependabot updates and the contributors update on a weekly basis.

chore: weekly interval for automatically created PRs

---

documentation/configuration.md

**Problem**
Currently, there's a lil ambiguity on the `hiddenClients` config.
**Solution**
With this PR I hopefully cleared a little bit up.
(I couldn't make sense of `By default hides Unirest` on line 240 since that doesn't _seem_ to map to `fetch`, but feel free to add it back.)

chore: Add details on configuration.md

---

.changeset/healthy-brooms-film.md
packages/api-client/src/components/DataTable/DataTableInput.vue

this pr fixes #3630 by setting an input for masked password state:
before:

fix(api-client): favors input on data table password type when masked

---

.changeset/rude-books-smile.md
packages/api-client/src/components/DataTable/DataTableInput.vue

**Problem**
This PR solves the issue #3636, authentication entries do not overflow when they have many characters.
**Solution**

fix(api-client): overflow is added

---

.changeset/lovely-peas-jog.md
packages/oas-utils/src/entities/spec/request-examples.ts

**Problem**
Currently we set the parameters to `header` and not `headers`
**Solution**
we map it to headers so we can render it in the client
we can add a proper migration later, but for now this doesnt impact any data just ingress
before:
after:
🥳

fix: add mapping of header to headers

---

.changeset/fast-swans-teach.md
packages/api-client/src/components/ViewLayout/ViewLayoutSection.vue
packages/api-client/src/views/Request/RequestSection/RequestSection.vue
packages/api-client/src/views/Request/ResponseSection/ResponseSection.vue

this pr fixes request section hover glitch and alignment as seen below:
**request section hover glitch before / after**
https://github.com/user-attachments/assets/076fd585-c791-42b5-ace2-e20ea3d187fc
https://github.com/user-attachments/assets/0fd4ef93-9b65-45ac-97fb-323af41dbd5b
**request section search <> input misalignment before / after**

style(api-client): request section ui

---

documentation/integrations/dotnet.md
packages/scalar.aspnetcore/README.md

This PR addresses the missing .NET integration documentation in the `documentation/integrations` folder. I've added some useful examples and descriptions.
Closes #3617 
For easier reading: https://github.com/xC0dex/scalar/blob/docs/documentation/integrations/dotnet.md
**Note**: The `Lint Markdown files` flow is failing due to a dead reference. Once this is merged, the link is no longer dead 😆.

docs(Scalar.AspNetCore): add .NET integration documentation

---

packages/api-reference/src/helpers/waitFor.ts
packages/api-reference/src/standalone.spec.ts
packages/galaxy/package.json
playwright/package.json
pnpm-lock.yaml

**Problem**
Currently, the standalone test is flaky in CI on Node 18
**Solution**
This PR:
- adds retries 
- explicitly adds the jsdom file directive for the runtime environment
- combines the tests because they build off each other to guarantee execution order

test(api-reference): make the standalone test stable

---

packages/components/src/components/ScalarCodeBlock/ScalarCodeBlock.vue

Fixes #3003
Replace `align-items: start` with `align-items: flex-start` in `packages/components/src/components/ScalarCodeBlock/ScalarCodeBlock.vue`.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/scalar/scalar/issues/3003?shareId=f0241905-a338-42c9-9d6e-76e5eda10a51).

fix(components): autoprefixer warning by using flex-start instead of start

---

.changeset/modern-drinks-peel.md
packages/api-client/src/store/security-schemes.ts
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuth.vue
packages/api-reference/index.html
packages/oas-utils/src/entities/spec/security.ts

This is a quick to the problem, long term solutions have been added to the canvas such as:
- proper error handling
- removing these oauthexamples
closes #3624

fix(oas-utils): added safe parsing to oauth example generation

---

.changeset/silver-papayas-retire.md
packages/oas-utils/src/spec-getters/getExampleFromSchema.test.ts
packages/oas-utils/src/spec-getters/getExampleFromSchema.ts

We recently improved how examples are generated for the anyOf, oneOf, allOf … rules, but there were still issues with them when they are in an array.
More context in: #3510
**Before**
```json
{
"cats": [
{
"$type": "",
"name": ""
},
{
"breed": "Unknown"
}
],
"dogs": [
{
"$type": "…",
"name": "…"
},
{
"breed": "Unknown"
}
]
}
```
**After**
```json
{
"cats": [
{
"$type": "",
"name": "",
"breed": "Unknown"
}
],
"dogs": [
{
"$type": "…",
"name": "…",
"breed": "Unknown"
}
]
}
```

fix(api-reference): arrays with `allOf` items render invalid examples

---

.changeset/nice-lies-agree.md
packages/api-client/src/store/environment.ts
packages/api-client/src/views/Environment/Environment.vue

this pr sets back the default environment variable value according to latest workspace refactoring:

fix(api-client): environment default value

---

.changeset/bright-comics-own.md
packages/api-client/src/components/AddressBar/AddressBarServer.vue
packages/api-reference/src/features/BaseUrl/ServerUrlSelect.vue
packages/components/src/components/ScalarDropdown/ScalarDropdown.vue
packages/components/src/components/ScalarFloating/ScalarFloating.vue
packages/components/src/components/ScalarListbox/ScalarListbox.vue

Updates `ScalarListbox` and `ScalarDropdown` to not overflow their bounding boxes (e.g. their scroll boxes) and to scroll instead. I also updated the server selection dropdown in the API Client to use more horizontal space and show more of the server url.
https://github.com/user-attachments/assets/9bd0fb83-1c66-4490-a2eb-2062e87ab3e1
https://github.com/user-attachments/assets/54e6c347-03f9-4c6d-921e-a86ab39241f4

fix(components): resize and scroll scalar listbox and dropdown

---

.changeset/warm-apes-build.md
packages/api-client/src/libs/create-client.ts
packages/api-client/src/store/store.ts
packages/api-reference-react/package.json
packages/api-reference-react/playground/App.tsx
packages/api-reference-react/playground/index.html
packages/api-reference-react/playground/main.tsx
packages/api-reference-react/tsconfig.json
packages/api-reference/package.json
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/embeds/OpenApiDocument/OpenApiDocument.vue
packages/api-reference/src/features/ApiClientModal/ApiClientModal.vue
packages/api-reference/src/legacy/components/SecuritySchemeSelector.vue
packages/oas-utils/src/transforms/import-spec.ts
packages/object-utils/src/mutator-record/handlers.ts
pnpm-lock.yaml
turbo.json

Alright in this pr we fixed the react and regular api-reference reactivity by destroying the store and re-creating it on update.
Also added a api-reference-react playground for testing reactive auth changes
Also added a reset command to the mutators.
I booted using diffing into another ticket https://github.com/scalar/scalar/issues/3676
To test: 
`pnpx turbo run playground --filter @scalar/api-reference-react` It will update every 10 seconds

fix(api-reference-react): reactive auth

---

.changeset/young-cows-retire.md
packages/api-reference/src/components/Content/Schema/Schema.vue
packages/api-reference/src/components/Section/CompactSection.vue

this pr fixes the over margin on open schema properties + anchor clickable area:
**section before / after**
https://github.com/user-attachments/assets/3c2a8674-014d-447f-939c-356e292723d5
https://github.com/user-attachments/assets/b189e10d-44b1-46eb-85a7-c786c5a984ee
**anchor before / after**
https://github.com/user-attachments/assets/2d681850-a64a-4252-804c-3236e04b436d
https://github.com/user-attachments/assets/f4fdac41-4b1f-4a54-afc4-f1901d634d0e

fix(api-reference): compact section

---

.changeset/cold-planes-compete.md
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue

this pr adds a disclosure button over 4 enum values as proposed in #3320 in order to avoid too long list displayed at all time:

feat(api-reference): disclosure button for enum values

---

.changeset/fresh-chairs-learn.md
packages/oas-utils/src/entities/spec/parameters.test.ts
packages/oas-utils/src/entities/spec/parameters.ts
packages/oas-utils/src/entities/spec/request-examples.ts

this pr fixes #3456 by adding to parameter schema example and examples along setting theme aside schema examples as request example value.
this should now enable to retrieve value on the following usage:
```yaml
name: limit
in: query
description: The number of items to return
example: 123
```

fix(oas-utils): parameter example value

---

.changeset/big-carpets-agree.md
README.md
documentation/integrations/html.md
documentation/integrations/nextjs.md
packages/api-reference/README.md
packages/express-api-reference/README.md
packages/fastify-api-reference/README.md
packages/hono-api-reference/README.md
packages/nestjs-api-reference/README.md
packages/types/src/legacy/reference-config.ts

`url` has better performance for larger documents, can be cached by the browser, and it’s easier to import documents to let’s say <https://client.scalar.com>.
I’ve gone through all the READMEs and made sure we’re promoting `url` instead of `content` (embedded OpenAPI documents).
~~This also marks `content` as `@deprecated`. Let me know how you feel about this, but I think we should really go all-in on the URL.~~ Just adds a `@remark`.

docs(api-reference): promote `url` instead of `content`

---

.github/workflows/ci.yml
packages/fetch/package.json
packages/galaxy/scripts/publish.ts

No more removed new line at the end of the `galaxy/package.json`!
Also updates the fetch `package.json`.
Also runs the `ci` → `format` action _after_ the build so that our build tooling can't create prettier errors (and pass build) like was happening with the galaxy package json.
It would be nice to confirm that the `build` command doesn't leave any uncommited files, but I looked it up and it seemed complicated with GH actions (if someone wants to add that though that would be cool).

chore(galaxy): align galaxy package.json with prettier

---

packages/api-client/src/views/Environment/EnvironmentVariableDropdown.vue

`defineExpose` is available globally with the latest Vue version:
> [@vue/compiler-sfc] `defineExpose` is a compiler macro and no longer needs to be imported.

chore(api-client): remove `defineExpose` import

---

packages/api-client/src/components/OpenApiClientButton.vue

Makes it so the button is only shown if the spec uses a URL.
We can't use `link` to check if the spec has a URL here because we construct it in a computed property and it's therefore always defined.

fix(api-client): api client button is always visible

---

.changeset/shiny-tips-hang.md
examples/nextjs-api-reference/app/another-reference/page.tsx
examples/nextjs-api-reference/package.json
packages/api-reference/src/components/Content/Lazy/Loading.vue
pnpm-lock.yaml

closes #3447
not sure why this only happened on next.js 🤷🏾 Added ApiReferenceReact page to the next.js example as well
before:
https://github.com/user-attachments/assets/045c37a6-1bd7-4c89-b09c-ca2fe7c078c7
after:
https://github.com/user-attachments/assets/a9d744f9-049e-4665-99fa-5a53a9461eb9

fix(api-reference): strange jump on lazy loading

---

.changeset/tame-starfishes-bow.md
packages/api-reference/src/features/ExampleRequest/ExampleRequest.vue
packages/api-reference/src/features/ExampleRequest/TextSelect.vue
packages/api-reference/src/stores/useHttpClientStore.test.ts
packages/api-reference/src/stores/useHttpClientStore.ts

This fixes a few things:
* Removes available target sections if they don't have any available clients and an array of hidden client is passed in
* Still shows custom examples if `hiddenClients` is `true`
* Cleans up some of the types in `ExampleRequest.vue`
Fixes #3688
Fixes #3689

refactor(api-reference): properly show hidden http clients and custom examples

---

.changeset/silly-planes-yawn.md
packages/oas-utils/src/transforms/import-spec.ts

fixes #1939
This just pre-selects the first auth in modal mode if there's no preferredSecurityScheme passed in to match the reference auth.

fix(api-reference): pre-select first auth in the modal when no auth selected

---

.changeset/fresh-cats-clean.md
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/components/Sidebar/SidebarList.vue
packages/api-client/src/views/Environment/Environment.vue

this pr adds the following elements to the environment view:
- removes copy capability from sidebar item
- adds copy capability to code input
- updates style (sidebar / code input)
- adds lint to code input
**lint before / after**
**style before / after**

fix(api-client): environment content copy capability

---

.changeset/chatty-lobsters-rule.md
packages/api-client/src/components/Sidebar/Actions/SidebarListElementForm.vue

this pr fixes the style of the danger button on sidebar list form component:

fix(api-client): sidebar form danger button

---

.changeset/itchy-cougars-relate.md
packages/galaxy/playground/index.ts

Loads the Scalar Galaxy Spec by URL rather than via `content` so you can open it in the API client.
I'm assuming the playground is what we deploy to `galaxy.scalar.com`, let me know if it's something else...

feat(galaxy): load the spec from a URL rather than as content

---

.changeset/sour-lamps-warn.md
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarOptionsExtensions.cs

This PR adds 2 little annotations to URL parameters to tell the IDE that a URI is expected here. IDE's like Rider or Visual Studio understand this attribute and will provide better syntax highlighting.

feat(Scalar.AspNetCore): add StringSyntax attribute to urls

---

.changeset/blue-eyes-walk.md
packages/api-client/src/components/Sidebar/SidebarButton.vue
packages/api-client/src/layouts/App/ApiClientApp.vue
packages/api-client/src/layouts/Modal/ApiClientModal.vue
packages/api-client/src/layouts/Web/ApiClientWeb.vue
packages/api-client/src/views/Cookies/Cookies.vue
packages/api-client/src/views/Environment/Environment.vue
packages/api-client/src/views/Request/ResponseSection/ResponseEmpty.vue

this pr favors provide / inject approach to condition scalar hotkey display in the web layout vs previous `isApp` prop set.
**on desktop**
**on web**

fix(api-client): web layout hotkey display

---

.changeset/violet-bulldogs-nail.md
packages/import/src/resolve.test.ts
packages/import/src/resolve.ts

Currently, `resolve()` returns `undefined` for URLs that respond with JSON/YAML (OpenAPI documents).
This PR fixes it and returns the URL if responded with an OpenAPI document.

fix(import): resolve JSON/YAML URLs

---

.github/workflows/ci.yml
examples/proxy-server/go.mod
examples/proxy-server/main.go
examples/proxy-server/main_test.go
examples/proxy-server/package.json

When the proxy receives a response containing a `Location` header with a relative URL (e.g. `Location: /foobar`), it redirects to the proxy itself.
With this PR this is fixed and the relative URL is prefixed with the original URL, that we’d like to fetch.
This PR also adds some tests (finally) to the proxy server.

fix(proxy-server): redirects with relative URLs in the `Location` header, fix #3668

---

.changeset/lazy-moose-talk.md
packages/oas-utils/src/helpers/makeUrlAbsolute.test.ts
packages/oas-utils/src/helpers/makeUrlAbsolute.ts

When the OpenAPI document URL is relative and we try to make it an absolute URL this is happening currently:
❌ `https://example.com/swagger` + `swagger.json` = `https://example.com/swagger/swagger.json`
But we actually want this:
✅ `https://example.com/swagger` + `swagger.json` = `https://example.com/swagger.json`
Without touching this case (trailing slash):
✅ `https://example.com/swagger/` + `swagger.json` = `https://example.com/swagger/swagger.json`

fix(oas-utils): relative URLs are wrong

---

documentation/integrations/rust.md

**Problem**
Currently, I struggled a bit with the current rust integration of scalar since it was to much oriented towards axum and I couldn't make it work with actix.
**Solution**
With this PR I propose another integration of scalar in rust that focuses on integrating scalar in any rust web framework. Don't get me wrong, tamasfe's crate is really good, but its DX is too much scoped towards axum.
Here is the crate I propose : [scalar-doc.rs](https://crates.io/crates/scalar-doc)

feat: added another option for rust integration

---

.changeset/odd-pans-grow.md
packages/oas-utils/src/entities/spec/spec-objects.ts

I think this is the last of it, I would add safe parsing to collection but if there's no collection, we can't show anything anyway

fix: remove URL validation from collection info

---

.changeset/fifty-comics-speak.md
packages/api-client/src/assets/variables.css
packages/api-client/src/components/Sidebar/Sidebar.vue
packages/api-client/src/components/ViewLayout/ViewLayoutSection.vue

this pr fixes the height issue on request section for non readonly spotted by @hanspagel : 

fix(api-client): request height section

---

.changeset/silly-beers-unite.md
packages/api-reference/src/features/ExampleResponses/ExampleResponses.vue

I think this attribute is just a leftover. Let’s try to remove it. :)
Fixes #3725

chore(api-reference): remove unnecessary SVG attribute

---

.changeset/fluffy-comics-deny.md
packages/api-client/src/components/DataTable/DataTableInputSelect.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/OAuth2.vue
packages/api-client/src/views/Request/RequestSection/RequestAuthDataTableInput.vue
packages/api-client/src/views/Request/libs/oauth2.test.ts
packages/api-client/src/views/Request/libs/oauth2.ts
packages/oas-utils/src/entities/spec/security.ts
packages/oas-utils/src/migrations/v-2.1.0/migration.ts

closes #604
closes #3705
Added a super basic front-end
and tested it using spotify (they support pkce)

feat(api-client): improve oauth2 error handling + add PKCE capabilities with tests

---

.changeset/little-dragons-care.md
.changeset/silver-mice-sleep.md
packages/galaxy/src/specifications/3.1.yaml
packages/mock-server/src/utils/handleAuthentication.ts
packages/mock-server/src/utils/logAuthenticationInstructions.ts
packages/mock-server/src/utils/setupAuthenticationRoutes.ts
packages/mock-server/tests/authentication/openIdConnect.test.ts

This PR adds everything that’s necessary to use OpenID Connect authentication with the Mock Server. :)

feat(mock-server): OpenID Connect (OIDC) endpoint

---

packages/api-client-app/package.json
pnpm-lock.yaml

This updates `@todesktop/cli`.
> Your version of @todesktop/cli is out of date.
> Run npm install --save-dev @todesktop/cli to update to v1.10.2.

chore(api-client-app): update `@todesktop/cli`

---

.github/workflows/ci.yml

This lists all files in  `./packages/api-client-app/out` before uploading it to toDesktop, just for the purpose of debugging the CI issues.
**Example Output**
```bash
main		preload		renderer
./packages/api-client-app/out/main:
chunks		index.js
./packages/api-client-app/out/main/chunks:
icon-BVRhZO9N.png
./packages/api-client-app/out/preload:
index.js
./packages/api-client-app/out/renderer:
assets		index.html
./packages/api-client-app/out/renderer/assets:
Cookies.vue-69pojGTh.js			Request.vue-Cpyzkg0L.js			Sidebar.vue-BnaErmk_.js			index-TLzcm0Kv.css
DataTableInput.vue-B5L2p30M.js		ScalarTextField.vue-BvLXS853.js		SidebarListElement.vue-CvSXMOHS.js	useSidebar-zyxptzzT.js
Environment.vue-CmxcreFu.js		Servers.vue-BHx4ZcC9.js			ViewLayoutContent.vue-WmK4pNwu.js
Form.vue-mi-V3wxO.js …
```

ci: list appFiles before doing the todesktop build

---

.github/workflows/ci.yml
packages/api-client-app/package.json

This PR refactors the npm scripts for the Electron app, to make it a little simpler (or a little bit more like the other packages).
@coderabbitai summary

refactor(api-client-app): simpler npm scripts

---

.changeset/tricky-rings-eat.md
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/components/DataTable/DataTableInputSelect.vue
packages/api-client/src/views/Request/RequestSection/RequestTable.vue

this pr fixes #3734 as we were relying on setting the selected value on model value, hence the wrong value was added. This pr also adds the support of the default if present.

fix(api-client): select input default

---

.changeset/ten-cobras-run.md
packages/openapi-parser/src/utils/upgradeFromThreeToThreeOne.test.ts
packages/openapi-parser/src/utils/upgradeFromThreeToThreeOne.ts

When upgrading an (old) example structure to the (new) example objects, for some reason I didn’t put the example in the `value` attribute. I just reread the specification and fixed this.
@amritk Does this break the API client schema? Would you mind to look into this? 
**Before**
```js
{
examples: {
default: 'foobar'
}
}
```
**After**
```js
{
examples: {
default: {
value: 'foobar'
}
}
}
```
OpenAPI 3.1 Example Object: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#example-object
Fixes #3760.

fix(openapi-parser): when migrating plain `example` to example objects there’s no `value` attribute

---

.changeset/thick-readers-jog.md
packages/galaxy/src/specifications/3.1.yaml
packages/galaxy/tests/yaml.test.ts
packages/openapi-parser/src/utils/openapi/openapi.test.ts
packages/openapi-parser/src/utils/openapi/utils/workThroughQueue.test.ts
packages/openapi-parser/src/utils/upgrade.test.ts
packages/openapi-parser/src/utils/upgradeFromThreeToThreeOne.test.ts
packages/openapi-parser/src/utils/upgradeFromThreeToThreeOne.ts
packages/openapi-parser/src/utils/upgradeFromTwoToThree.test.ts
packages/openapi-parser/src/utils/upgradeFromTwoToThree.ts
packages/openapi-types/src/openapi-types.test-d.ts
packages/openapi-types/src/openapi-types.ts

Adds [OpenAPI 3.0.4](https://github.com/OAI/OpenAPI-Specification/releases/tag/3.0.4) and [OpenAPI 3.1.1](https://github.com/OAI/OpenAPI-Specification/releases/tag/3.1.1) to:
* `@scalar/openapi-types`
* `@scalar/openapi-parser`
* `@scalar/galaxy`
There’s no new features, just additional explanations in the specification it seems.
Fixes #3652.

feat(openapi-types): add OpenAPI 3.0.4 and OpenAPI 3.1.1

---

.changeset/real-planets-rule.md
.github/workflows/ci.yml
packages/api-reference/docker/src/Dockerfile

The release of the docker image failed because the security scanning failed. This PR fixes it.
* We’re now scanning specifically the Dockerfile.
* The suggestion to run caddy as a non-root user came up, so I’ve added this, too.
* All the Docker steps are only executed when something in the folder changed (to avoid blocking main with the security check at random times).

fix(api-reference): docker image can’t be scanned

---

.changeset/dry-foxes-do.md
packages/import/src/resolve.test.ts
packages/import/src/resolve.ts

This should help to resolve a few more URLs from our friends at GitBook. :)

feat(import): find OpenAPI document URLs in escaped JS objects

---

packages/mock-server/README.md
packages/mock-server/src/createMockServer.test.ts

With this PR:
* The README is updated.
* There’s an example for the recently added authentication mocking.
* It’s mentioned that OpenAPI documents are served automatically.
* A HTTP redirect test is added.

docs(mock-server): update the README

---

.changeset/nine-peaches-search.md
packages/api-client/src/layouts/Modal/create-api-client-modal.ts
packages/api-client/src/libs/create-client.ts
packages/api-client/src/store/import-spec.ts
packages/oas-utils/src/entities/spec/security.ts
packages/oas-utils/src/transforms/import-spec.test.ts
packages/oas-utils/src/transforms/import-spec.ts

closes #3295
closes #3476
references #3475
Overload servers wasn't doing much before, I renamed it to servers so it matches the references + shares types + simplifies the config. Now we just pass the reference config straight into the client. (only proxy remains with a different name)
I based this off my other PR because I wanted those config changes.  So merge #3606 first, then rebase, then this one

fix(api-client): not respecting server overload

---

.changeset/dirty-laws-whisper.md
packages/oas-utils/src/spec-getters/getExampleFromSchema.ts

**Problem**
We use `format: object-id` to specify that the value should be a MongoDB Object ID. Currently, an example value isn't automatically generated for these fields.
**Solution**
With this PR, any field with `format: object-id` will now have a default example value, just like how it works for `format: uuid`.

feat(oas-utils): add object-id value example

---

.changeset/metal-ants-travel.md
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuth.vue

closes #3613
Based on feedback from [prev PR](https://github.com/scalar/scalar/pull/3826), added all options like this instead. Copy is up for debate as usual
Preview:

feat(api-client): display which auth is required on a request

---

.github/workflows/ci.yml

We disabled the Stackblitz pre-release publish job a while ago, but I think it’s time to add it again.
The pre-release allows us to test packages like they’d be published on npm, before actually publishing to npm.

ci: enable stackblitz pre-release again

---

.changeset/khaki-cougars-wash.md
packages/api-client/src/components/ContextBar.vue

this pr adds back missing hover in the context bar styles in order to fix hover interaction:
https://github.com/user-attachments/assets/529cd28a-75a0-44d2-aa80-556d6d085c02
https://github.com/user-attachments/assets/ed1d7b54-4dc3-449c-b762-6af1b7073cde

fix(api-client): context bar hover interaction

---

.changeset/wise-moons-pull.md
packages/api-client/src/views/Request/ResponseSection/ResponseEmpty.vue

style(api-client): make roadmap cta slightly more prominent

---

.changeset/green-nails-sparkle.md
.changeset/lemon-tomatoes-wash.md
examples/proxy-server/README.md
examples/proxy-server/main.go
examples/proxy-server/main_test.go
examples/proxy-server/package.json
packages/import/package.json
packages/import/src/resolve.test.ts
packages/import/src/resolve.ts
packages/oas-utils/src/helpers/makeUrlAbsolute.test.ts
packages/oas-utils/src/helpers/makeUrlAbsolute.ts
pnpm-lock.yaml

Currently, when the proxy gets a `Location` header (redirect), it just proxies it:
`https://proxy.scalar.com/?scalar_url=https://example.com/foo` responds with `Location: /bar`
And the browser will follow the redirect, requesting an URL that doesn’t exist:
`https://proxy.scalar.com/bar`
With this PR, the proxy just follows the redirect:
`https://proxy.scalar.com/?scalar_url=https://example.com/foo` responds with the _content_ of `https://example.com/bar`
But in `@scalar/import` we try to transform relative URLs to absolute URLs, so we need to know the resulting URL. To achieve this, the proxy now adds a [`X-Forwarded-Host` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host) and `@scalar/import` uses this to prefix relative URLs (if it’s available).
This PR …

feat(proxy-server): follow redirects

---

.changeset/lemon-hornets-tickle.md
packages/api-client/src/views/Request/ResponseSection/ResponseSection.vue

**Problem**
Currently, we virtualize everything and dont check the content type
**Solution**
With this PR we virtualize only text based contents, so we can add a better more exhaustive check later but for now should handle most :)

fix: only virtualize text based contents

---

.changeset/calm-files-float.md
.changeset/clean-paws-leave.md
packages/api-client/src/components/ViewLayout/ViewLayoutCollapse.vue
packages/api-client/src/views/Request/ResponseSection/ResponseBody.vue
packages/api-client/src/views/Request/ResponseSection/ResponseBodyVirtual.vue
packages/api-client/src/views/Request/ResponseSection/ResponseHeaders.vue
packages/api-client/src/views/Request/ResponseSection/ResponseSection.vue
packages/components/src/components/ScalarCodeBlock/ScalarCodeBlock.vue

this pr is a first raw approach regarding the response section items in order to have them fill up the given space vs overflowing no matter their height, along code block + response body virtual component fixtures:
**response body block before / after**
⊢ PR updates the overflow and style of the response section to maintain the visualization of section titles for any child's height:
<details>
<summary>before / after screenshots</summary>
https://github.com/user-attachments/assets/27550126-e492-4c90-baa1-a74a6ae0bd0a
https://github.com/user-attachments/assets/0196dd57-f840-417a-af8a-7bf742fb1ac0
</details>
**response cookie block before / after**
<details>
<summary>before / after screenshots</summary>
</details>
**code block before / after**
⊢ PR adds a minimum height to maintain good …

style(api-client): response section childs space

---

.changeset/green-nails-argue.md
packages/void-server/src/createVoidServer.test.ts
packages/void-server/src/utils/createXmlResponse.ts

Currently, `@scalar/void-server` replies with XML, but doesn’t add the XML content-type header.
This PR adds it.

fix(void-server): does not respond with XML header

---

.changeset/large-zebras-sell.md
packages/mock-server/src/routes/respondWithOpenApiDocument.ts
packages/mock-server/tests/openapi.test.ts

Currently, `@scalar/mock-server` doesn’t add YAML http headers when serving the OpenAPI documents as YAML.
This PR adds them.

fix(mock-server): OpenAPI YAML endpoints don’t have a YAML content-type header

---

.changeset/sharp-clouds-sneeze.md
packages/api-client/src/components/ImportCollection/DropEventListener.vue
packages/api-client/src/components/ImportCollection/ImportCollectionListener.vue
packages/api-client/src/components/ImportCollection/ImportCollectionModal.vue
packages/api-client/src/components/ImportCollection/PasteEventListener.vue
packages/api-client/src/components/ImportCollection/UrlQueryParameterChecker.vue
packages/api-client/src/components/ImportCollection/hooks/useUrlPrefetcher.ts

Currently, the import collection modal is shown when any URL is pasted or dropped into the UI.
With this PR we’re checking whether the pasted/dropped URL is pointing to an OpenAPI document first, and only then show the modal.
It still shows the import modal when an URL is provided through a query parameter (when following a link from the references).

fix(api-client): import modal shows up for any URL

---

.changeset/healthy-experts-sneeze.md
packages/api-reference/src/components/Content/Content.vue
packages/api-reference/src/features/BaseUrl/ServerForm.vue
packages/api-reference/src/features/BaseUrl/ServerVariablesForm.vue
packages/api-reference/src/features/BaseUrl/ServerVariablesSelect.vue
packages/api-reference/src/features/BaseUrl/ServerVariablesTextbox.vue

this pr updates the introduction card server description ui as seen below:
- fixes border consistency
- updates description ui
<div>
</div>

style(api-reference): introduction card server description

---

.changeset/clever-phones-stare.md
.changeset/three-llamas-watch.md
packages/api-client/src/store/import-spec.ts
packages/api-reference/src/features/Search/useSearchIndex.ts
packages/oas-utils/src/transforms/import-spec.test.ts
packages/oas-utils/src/transforms/import-spec.ts
pnpm-lock.yaml

This PR improve a few code comments and adds a bunch of tests for `importSpecToWorkspace`.
It’s also adding a console.log for the time it takes to create the workspace, and removes the console.log for the time it takes to create the search index. The search index was never really blocking anything, and it was rather quick, even for big files. The workspace becomes more relevant for the time to interaction, so I’d like to keep an eye on it for real-world examples. 
The diff is hard to follow, but no actual code is touched (except the mentioned logging).

test(oas-utils): more tests for `importSpecToWorkspace`

---

.changeset/rich-llamas-live.md
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/themes/src/presets/alternate.css
packages/themes/src/presets/bluePlanet.css
packages/themes/src/presets/deepSpace.css
packages/themes/src/presets/default.css
packages/themes/src/presets/kepler.css
packages/themes/src/presets/mars.css
packages/themes/src/presets/moon.css
packages/themes/src/presets/purple.css
packages/themes/src/presets/saturn.css
packages/themes/src/presets/solarized.css
packages/themes/src/reset.css
packages/themes/src/variables.css
packages/use-codemirror/src/hooks/useCodeMirror.ts
packages/use-codemirror/src/themes/index.ts

this pr sets back selection style disabled in #3618 along adding user select property on web layout for a better app feeling + adds missing variables to use codemirror.
> [!NOTE]
> we should wait for [#2558](https://github.com/GitbookIO/gitbook/pull/2558) to be merged prior to merge this one

fix(api-client): selection style

---

.changeset/nasty-rabbits-greet.md
packages/api-client/src/store/requests.ts
packages/api-client/src/store/workspace.ts
packages/api-client/src/views/Request/RequestSidebar.vue
packages/api-client/src/views/Request/RequestSidebarItem.vue
packages/api-client/src/views/Request/RequestSidebarItemMenu.vue

this pr adds the clear drafts capability from request sidebar draft collection, as seen below:
https://github.com/user-attachments/assets/d9b48bc6-2cfb-477b-95c6-c9ca17f2f9eb
we might want to set a more central empty state in the view afterward.

feat(api-client): clear drafts

---

.changeset/breezy-baboons-admire.md
.changeset/poor-days-rhyme.md
packages/api-client/src/components/CodeInput/codeVariableWidget.ts
packages/api-client/src/views/Request/RequestSection/RequestPathParams.vue
packages/api-reference/src/features/ApiClientModal/ApiClientModal.vue
packages/api-reference/src/features/BaseUrl/ServerVariablesSelect.vue
packages/api-reference/src/features/ExampleRequest/ExampleRequest.vue
packages/api-reference/src/helpers/getApiClientRequest.ts
packages/api-reference/src/helpers/getExampleCode.ts
packages/api-reference/src/legacy/components/SecurityScheme.vue
packages/api-reference/src/legacy/helpers/getUrlFromServerState.test.ts
packages/api-reference/src/legacy/helpers/getUrlFromServerState.ts
packages/api-reference/src/legacy/stores/useServerStore.ts
packages/oas-utils/src/helpers/findVariables.ts
packages/oas-utils/src/helpers/regexHelpers.test.ts
packages/oas-utils/src/helpers/regexHelpers.ts
packages/oas-utils/src/spec-getters/getRequestFromOperation.ts

this pr fixes #3697 by setting default server variable and enhancing empty variable value as seen below:
**⊢ base url before / after**
**⊢ request example before / after**

fix(api-reference): base url variables DOC-2476

---

.changeset/lemon-pens-protect.md
packages/components/src/index.ts

Not the final solution but simplifies the index file and makes it easier to export new components.
I don't think this should change the consumed API anywhere but someone who knows about packages can weigh in?

feat(components): simplify index exports

---

.github/workflows/ci.yml
packages/scalar.aspnetcore/global.json
packages/scalar.aspnetcore/playground/Scalar.AspNetCore.Playground/Scalar.AspNetCore.Playground.csproj
packages/scalar.aspnetcore/tests/Scalar.AspNetCore.Tests/Scalar.AspNetCore.Tests.csproj
packages/scalar.aspnetcore/tests/apis/Scalar.AspNetCore.Tests.Api/Scalar.AspNetCore.Tests.Api.csproj

.NET 9 was released yesterday 🚀 and this PR updates all dependencies in the `Scalar.AspNetCore` package to use the latest stable versions.

chore(Scalar.AspNetCore): bump dependencies to a stable version

---

.changeset/swift-games-drop.md
packages/use-hooks/src/useColorMode/useColorMode.test.ts
packages/use-hooks/src/useColorMode/useColorMode.ts

Initial mode now defaults to `system` instead of `dark` 🤦 
Added some extra tests too.

fix(use-hooks): set default color mode to system instead of dark

---

documentation/integrations/dotnet.md
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarOptionsExtensions.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Options/Authentication/HttpBasicOptions.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Options/Authentication/HttpBearerOptions.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Options/Authentication/HttpOptions.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Options/Authentication/ScalarAuthenticationOptions.cs
packages/scalar.aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarOptionsExtensionsTests.cs

Add missing options model definition for prefilling http basic/bearer tokens.
**Problem**
Currently, there's no `Http` property in `ScalarAuthenticationOptions`, which makes users unable to set a prefilled token for http basic/bearer authentication according to https://github.com/scalar/scalar/issues/1356#issuecomment-2048333833.
**Solution**
This PR adds `Http.Bearer.*` `Http.Basic.*` properties to `ScalarAuthenticationOptions`, several `WithHttp*Authentication` extension methods, alongside with unit tests.

feat(Scalar.AspNetCore): add missing options model definition for prefilling http basic/bearer tokens

---

.changeset/eighty-buses-reply.md
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.spec.ts
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue

this pr fixes small glitches on long content usage in api reference:
**⊢ schema property before / after**
**⊢ property enum before / after**

fix(api-reference): property detail long content

---

.changeset/stupid-games-burn.md
packages/api-reference/src/components/ApiReference.vue
packages/use-hooks/src/useColorMode/types.ts
packages/use-hooks/src/useColorMode/useColorMode.test.ts
packages/use-hooks/src/useColorMode/useColorMode.ts

Small fix to add a computed dark / light mode so that the toggle can show the correct value initially.

feat(use-hooks): add computed dark light mode

---

.changeset/blue-rats-wait.md
packages/api-client/src/views/Request/RequestSection/RequestTableTooltip.vue

This PR enhanced template logic to conditionally display `minimum`, `maximum`, and `default` properties even if their values are falsy (0, false) but defined.
before:
after:

fix(api-client): falsy value display in RequestTableTooltip

---

.changeset/cold-crabs-unite.md
packages/icons/README.md
packages/icons/package.json
packages/icons/scripts/update-list-of-icons.ts

This PR adds a list of all available icons to the README.
Great for a quick preview of what’s in the package.

feat(icons): add list of icons to the README

---

.changeset/six-seals-accept.md
.changeset/weak-cameras-smash.md
packages/api-client/src/views/Request/ResponseSection/ResponseBodyRaw.vue
packages/use-codemirror/src/hooks/useCodeMirror.ts
packages/use-codemirror/src/themes/index.ts

Replaces `ScalarCodeBlock` with the `useCodeMirror` hook.
**Problem**
Currently we dont get:
- search
- folding
- any sort of advanced interactions with the text for the future of making variables from responses
**Solution**
Lets use our codemirror package since we handle large responses with virtualization
before:
after:
*edit*
i fixed the orange

feat(api-client): code folding to the response preview

---

.changeset/fluffy-pigs-explain.md
packages/api-client/src/components/Sidebar/Sidebar.vue
packages/api-client/src/views/Request/Request.vue
packages/api-reference/src/components/Layouts/ModernLayout.vue
packages/use-hooks/package.json
packages/use-hooks/src/useBreakpoints/README.md
packages/use-hooks/src/useBreakpoints/index.ts
packages/use-hooks/src/useBreakpoints/useBreakpoints.test.ts
packages/use-hooks/src/useBreakpoints/useBreakpoints.ts
pnpm-lock.yaml

Adds a `useBreakpoint` hook so we can use our Tailwind breakpoints in a consistent way that matches how we use the in CSS. 
Fixes DOC-1338 😱 🧟 
Also fixed a bug with the API Client sidebar while I was in there (it used to be possible to do this if you opened the sidebar with a viewport between 780px and 800px)

feat(use-hooks): add useBreakpoint hook

---

.github/workflows/lint-markdown-files.yml

With this PR dead markdown links are a warning, not a blocker for the workflow. Sometimes external links are just dead and we can’t do anything about it, but it’s still great to be notified about it. We found a bunch of wrong links that way already.

ci: continue when markdown links are dead

---

.changeset/late-bikes-provide.md
packages/components/src/components/ScalarMenu/ScalarMenu.vue
packages/components/src/components/ScalarMenu/ScalarMenuLink.vue
packages/components/src/components/ScalarMenu/ScalarMenuProduct.vue
packages/components/src/components/ScalarMenu/ScalarMenuProducts.vue
packages/components/src/components/ScalarMenu/ScalarMenuSection.vue

Ended up going with 1 column here to make it closer to our sidebar

refactor(components): scalar menu apply same styles as sidebar

---

.changeset/eleven-lies-argue.md
package.json
packages/components/.prettierrc
packages/icons/package.json
packages/postman-to-openapi/package.json
packages/themes/package.json
packages/themes/vite.config.ts
pnpm-lock.yaml

Currently we're only exposing the tailwind preset as typescript which was okay but now `useBreakpoints` consumes it as JS which is breaking our publish `vite-ssg` build.
```
dist/
├── fonts.css.js
├── index.d.ts
├── index.d.ts.map
├── index.js
├── pixelPreset.d.ts
├── pixelPreset.d.ts.map
├── presets/
├── style.css
├── tailwind.d.ts
├── tailwind.d.ts.map
└── utilities/
```
```
dist/
├── fonts.css.js
├── index.d.ts
├── index.d.ts.map
├── index.js
├── pixelPreset.d.ts
├── pixelPreset.d.ts.map
├── pixelPreset.js
├── presets/
├── style.css
├── tailwind.d.ts
├── tailwind.d.ts.map
├── tailwind.js
└── utilities/
```

feat(themes): expose tailwind preset as js not just ts

---

.changeset/smart-feet-roll.md
packages/components/src/components/ScalarTooltip/ScalarTooltip.vue

this pr fixes the variable value tooltip visibility when used within the address bar as seen below:
**⊢ before / after**
<div>
</div>

fix(api-client): view layout z index

---

.changeset/tame-ads-type.md
packages/api-reference/src/components/Section/Section.vue
packages/api-reference/src/components/Section/SectionContainer.vue
packages/api-reference/src/legacy/components/CardFormGroup.vue

fix(api-reference): section borders missing

---

.changeset/funny-pets-play.md
.changeset/nine-dryers-brush.md
packages/api-client/src/views/Request/ResponseSection/ResponseBodyRaw.vue
packages/api-client/src/views/Request/ResponseSection/ResponseHeaders.vue

this pr fixes #3955 and #3962 along:
- response body content display pretty printed
- response body content scrollability back
- copy button style to only display it on content hover
- response headers style
**⊢ header before after**
<div>
</div>
**⊢ response before after**
<div>
</div>

fix(api-client): response preview pretty print

---

.changeset/big-rats-own.md
packages/api-client/src/components/ViewLayout/ViewLayoutCollapse.vue
packages/api-client/src/components/ViewLayout/ViewLayoutSection.vue
packages/api-client/src/views/Request/RequestSection/RequestSection.vue

this pr fixes few responsive glitches as listed below:
- request section input alignment
- environment editor height
- view layout caret alignment
**⊢ request section before after**
<div>
</div>
<br>
**⊢ environment editor before after**
<div>
</div>

style(api-client): mobile layout fixtures

---

.changeset/stupid-dryers-warn.md
packages/components/src/components/ScalarMenu/ScalarMenuProduct.vue

This menu has flex-col on larger, screens
this pr fixes that

fix(components): scalar menu flex not on just small screen

---

.changeset/thin-drinks-sparkle.md
packages/api-reference/src/components/Content/Operation/RequestBody.vue
packages/api-reference/src/features/BaseUrl/ServerVariablesForm.vue
packages/code-highlight/src/css/markdown.css

this pr fixes font / icon size glitch in api reference as seen below:
**⊢ base url before / after**
<div>
</div>
**⊢ markdown code before / after**
<div>
</div>
**⊢ request body select before / after**
<div>
</div>

style(api-reference): font size fixtures

---

.changeset/brown-tips-sort.md
packages/api-client/src/views/Request/ResponseSection/ResponseSection.vue
packages/api-reference/src/features/Search/SearchButton.vue

sometimes people apply classes globally to `.grid`, this stretches the content so that the layout doesn't break when people do that

fix(api-client): css conflict with grid

---

.changeset/twelve-berries-tap.md
packages/mock-server/package.json
packages/mock-server/src/createMockServer.ts
packages/mock-server/src/routes/mockAnyResponse.ts
packages/mock-server/src/utils/createOpenApiDefinition.ts
packages/mock-server/src/utils/getOpenAuthTokenUrls.test.ts
packages/mock-server/src/utils/getOperations.ts
packages/mock-server/src/utils/index.ts
packages/mock-server/src/utils/setupAuthenticationRoutes.ts
packages/mock-server/tests/authentication/apiKey.test.ts
packages/mock-server/tests/authentication/basicAuthentication.test.ts
packages/mock-server/tests/authentication/bearerAuthentication.test.ts
packages/mock-server/tests/authentication/oAuth.test.ts
packages/mock-server/tests/authentication/openIdConnect.test.ts
packages/mock-server/tsconfig.build.json
packages/mock-server/tsconfig.json
packages/mock-server/vite.config.ts
pnpm-lock.yaml

This PR introduces the path aliases we already have in other packages to the `@scalar/mock-server`.
Easier to move files around without modifying the imports.
Stole the configuration from `@scalar/oas-utils`.
Also removes the barrel file from `./utils`.

refactor(mock-server): use path aliases

---

.changeset/sour-hotels-exist.md
.changeset/twelve-elephants-smell.md
packages/api-reference/src/features/ExampleRequest/ExampleRequest.vue
packages/api-reference/src/legacy/helpers/getUrlFromServerState.ts
packages/types/src/legacy/reference-config.ts

this pr is a proposal to fix #3964 in order to favor the path server in the request example if it exists:
**⊢ before / after**
should be ff with setting the right server in the client modal on test request.

feat(api-reference): displays path server in request example

---

README.md

This PR adds Nim/HappyX as a framework to the README, and it introduces a new list with frameworks where the API reference is the default already.

docs: add HappyX, new list with frameworks where we are the default

---

.changeset/green-nails-sparkle.md
.changeset/lemon-tomatoes-wash.md
examples/proxy-server/README.md
examples/proxy-server/main.go
examples/proxy-server/main_test.go
examples/proxy-server/package.json
examples/proxy-server/public/index.html
packages/api-client/src/libs/send-request/create-request-operation.test.ts
packages/import/package.json
packages/import/src/resolve.test.ts
packages/import/src/resolve.ts
packages/oas-utils/src/helpers/makeUrlAbsolute.test.ts
packages/oas-utils/src/helpers/makeUrlAbsolute.ts
pnpm-lock.yaml

A previous version of this PR has been merged and rolled back. This PR has more changes than the initial PR:
* Even more tests
* Refactor of the proxy, hopefully easier to follow the code
* It doesn't merge CORS headers anymore, but overwrites them (the idea of the proxy is to be easy with cross-origin requests)
* Manually tested with a bunch of URLs, too (directly, in the reference and in the API client)
Here’s the original description:
Currently, when the proxy gets a `Location` header (redirect), it just proxies it:
`https://proxy.scalar.com/?scalar_url=https://example.com/foo` responds with `Location: /bar`
And the browser will follow the redirect, requesting an URL that doesn’t exist:
`https://proxy.scalar.com/bar`
With this PR, the proxy just follows the redirect: …

feat(proxy-server): follow redirects DOC-2535

---

.changeset/rich-vans-fold.md
packages/api-client/src/views/Request/RequestSection/RequestBody.vue

this pr adds a selector to the api client request body in order to be able to switch examples from an OAD:
course of action:

feat(api-client): request body example selector

---

examples/proxy-server/Dockerfile

With #3848 we added an API reference to the proxy server, but I forgot to add the static assets in the Dockerfile and the server now shows `Error reading index.html` on `/`.
This PR adds the assets to fix the issue.

fix(proxy-server): doesn’t deploy public assets

---

.changeset/new-suns-run.md
packages/api-reference/src/components/ApiReference.vue
packages/api-reference/src/components/ApiReferenceLayout.vue

In some integrations as well as our docs, we use `ApiReferenceLayout` directly. In these cases setting hidden clients was not working. This PR moves that config mapping into the layout so it works everywhere!

fix(api-reference): move client config to ApiReferenceLayout

---

.changeset/curvy-terms-live.md
packages/api-client/src/views/Request/ResponseSection/ResponseMetaInformation.vue
packages/oas-utils/src/helpers/httpStatusCodes.ts

this nit pr adds color to http status code in order to display response status color in the client to enhance scanning experience of the information:
**⊢ before / after**
<div>
</div>
_originally requested by PabloGmz [in discord](https://discord.com/channels/1135330207960678410/1304202363720040490/1304208523277635604)_

feat(api-client): adds response status color

---

.changeset/chilled-wasps-camp.md
packages/api-reference/src/helpers/getExampleCode.test.ts
packages/api-reference/src/helpers/getExampleCode.ts
packages/snippetz/README.md
packages/snippetz/src/core/types.ts
packages/snippetz/src/plugins/js/fetch/fetch.test.ts
packages/snippetz/src/plugins/js/fetch/fetch.ts
packages/snippetz/src/plugins/js/ofetch/ofetch.test.ts
packages/snippetz/src/plugins/js/ofetch/ofetch.ts
packages/snippetz/src/plugins/node/fetch/fetch.test.ts
packages/snippetz/src/plugins/node/fetch/fetch.ts
packages/snippetz/src/plugins/node/ofetch/ofetch.test.ts
packages/snippetz/src/plugins/node/ofetch/ofetch.ts
packages/snippetz/src/plugins/node/undici/undici.test.ts
packages/snippetz/src/plugins/node/undici/undici.ts
packages/snippetz/src/plugins/shell/curl/curl.test.ts
packages/snippetz/src/plugins/shell/curl/curl.ts
packages/snippetz/src/snippetz.ts

We recently added a way to dynamically extend the list of available clients in TypeScript. Turns out the types were wrong in the build: The output only had one plugin import, instead of all. So as a result only this one client was in the types, all the others were missing:
I don’t know exactly why that is. But I don’t want to bother, so I went back to a simpler approach of just a list of available clients.
I’ve also changed the plugin API to make it simpler. This is what changed:
* No function invocation needed (I don't know what I was thinking)
* The function name includes the target to avoid conflicts
* No types for the parameters needed, just one type for the whole object including the generator
```diff
-export function curl(
-  request?: Partial<Request>,
-  configuration?: …
```

fix(snippetz): types are wrong

---

.changeset/great-timers-provide.md
packages/use-codemirror/src/hooks/useCodeMirror.ts

this pr fixes the error fired when changing request along using a variable in code mirror input:
```json
Error: Calls to EditorView.update are not allowed while an update is in progress
```

fix(use-codemirror): dispatch value frame

---

.changeset/hot-colts-tap.md
packages/oas-utils/src/helpers/findVariables.ts

this pr updates import made in `findVariables` to fix circular dependencies caught by @marclave.

fix(oas-utils): updates find variables import

---

.changeset/old-pumpkins-chew.md
packages/api-client/src/components/HttpMethod/HttpMethod.vue

this pr updates http method variants according to the fix in #4036:
<div>
</div>

style(api-client): http method variants

---

.changeset/neat-mayflies-learn.md
.changeset/tall-pots-rush.md
packages/api-reference/src/components/Anchor/Anchor.vue
packages/api-reference/src/components/Content/ClientLibraries/ClientLibraries.vue
packages/api-reference/src/components/Content/Content.vue
packages/api-reference/src/components/Content/Introduction/Introduction.vue
packages/api-reference/src/components/Content/Tag/Endpoints.vue
packages/api-reference/src/components/Content/Tag/TagAccordion.vue
packages/api-reference/src/components/Section/SectionColumn.vue
packages/api-reference/src/components/Section/SectionContainerAccordion.vue
packages/api-reference/src/components/Section/SectionHeader.vue
packages/api-reference/src/features/Operation/layouts/ClassicLayout.vue
packages/api-reference/src/features/Operation/layouts/ModernLayout.vue

this pr fixes #3956 by:
- enhancing section header display with long content
- fixing classic layout responsiveness
**⊢ header before / after**
<div>
</div>
**⊢ classic alignment + border before / after**
<div>
</div>
**⊢ classic mobile before / after**
<div>
</div>

fix(api-reference): section header long content + classic layout responsive

---

.changeset/quick-turkeys-sniff.md
examples/fastify-api-reference/src/index.ts
packages/fastify-api-reference/package.json

**Problem**
While I'm working on my Fastify project, I noticed that `FastifyApiReferenceOptions` can not be resolved.
```ts
import type { FastifyApiReferenceOptions } from '@scalar/fastify-api-reference'
```
Above import statement shows a bellow error.
```
Module '"@scalar/fastify-api-reference"' has no exported member 'FastifyApiReferenceOptions'. Did you mean to use 'import FastifyApiReferenceOptions from "@scalar/fastify-api-reference"' instead?ts(2614)
```
**Solution**
I'm not 100% sure, but some `moduleResolution` mode does not read `types` field in `package.json` when export map exists, and export map needs `types` condition to properly resolve TypeScript types.
https://www.typescriptlang.org/docs/handbook/modules/reference.html#the-moduleresolution-compiler-option
According to the …

fix(fastify-api-reference): export map needs explicit types condition

---

.changeset/perfect-turtles-do.md
documentation/configuration.md
packages/api-client/src/libs/create-client.ts
packages/api-client/src/store/store.ts
packages/api-client/src/views/Request/RequestSubpageHeader.vue
packages/api-reference/src/components/Layouts/ModernLayout.vue
packages/types/src/legacy/reference-config.ts

this pr adds the `hideClient?` option to the configuration in order to be able to hide the api client button from the reference as seen below:
**⊢ sidebar hideClient: false (default) / hideClient: true**
<div>
</div>
<br>
**⊢ modal hideClient: false (default) / hideClient: true**
<div>
</div>

feat(configuration): adds hideClientButton option

---

.changeset/giant-teachers-smile.md
packages/api-client/src/views/Request/ResponseSection/ResponseBodyPreview.vue

this pr fixes #4060 updates the image style in response preview to avoid them from shrinking:
<div>
</div>

fix(api-client): image response preview

---

documentation/configuration.md

This PR adds a list of all the available HTTP clients to the `hiddenClients` documentation.
Easier to copy and paste and just remove the ones you don’t want to hide.

docs: add a list of available HTTP clients

---

packages/postman-to-openapi/src/convert.test.ts

We updated the test files for the `@scalar/postman-to-openapi` package, but we didn’t update the tests yet. Now main and all rebased branches are failing CI.
Let’s skip the tests until we updated them. ✌️

ci: skip postman-to-openapi tests until the tests were updated

---

.github/workflows/ci.yml
.github/workflows/deploy-examples.yml
.github/workflows/lint-icons.yml
.github/workflows/lint-markdown-files.yml
.github/workflows/lint-pr.yml
.github/workflows/test-cdn-jsdelivr.yml
.github/workflows/test-cdn-local.yml
.github/workflows/test-electron-app.yml
.github/workflows/test-nuxt-integration.yml
.github/workflows/update-contributors.yml
.github/workflows/validate-openapi-file.yml

I just noticed we’re using `ubuntu-latest` (which will soon be bumped to `ubuntu-24.04`) and `ubuntu-20.04` in our workflows.
Let’s use `ubuntu-22.04` everywhere.
I tried `ubuntu-24.04`, but the Electron tests didn’t pass and I’m not ready to fix this.
I’d prefer the pinned version, so we can decide when to upgrade it.

ci: upgrade to ubuntu-22.04

---

.changeset/shaggy-paws-argue.md
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarOptionsExtensions.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Mapper/ScalarOptionsMapper.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Options/ScalarOptions.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/ScalarConfiguration.cs
packages/scalar.aspnetcore/tests/Scalar.AspNetCore.Tests/Scalar.AspNetCore.Tests.csproj
packages/scalar.aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarOptionsExtensionsTests.cs
packages/scalar.aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarOptionsMapperTests.cs

This PR adds support for the recently introduced (https://github.com/scalar/scalar/pull/4047) `hideClientButton` option to the `Scalar.AspNetCore` integration.

feat(Scalar.AspNetCore): add HideClientButton configuration

---

.changeset/five-sheep-fetch.md
packages/api-client/src/views/Request/RequestSidebar.vue

this pr fixes the add item hotkey style issue on desktop, however we might also maintain it and fix it for darkmode:
<div>
</div>

style(api-client): removes add item hotkey style

---

.changeset/young-sloths-beg.md
packages/api-client/src/components/ImportCollection/ImportCollectionModal.vue
packages/api-client/src/components/ImportCollection/hooks/useUrlPrefetcher.ts
packages/api-client/src/components/OpenApiClientButton.vue

This PR makes it possible to import embedded API definitions to the API client:
* always shows _the button_, even for embedded content
* fixes the import for embedded content
* falls back to passing the API reference URL for the import (if we don’t have an OpenAPI document URL)

feat(api-reference): import from embedded OpenAPI documents

---

.changeset/gentle-adults-grab.md
packages/api-client/src/views/Request/RequestSidebarItem.vue

We’re using `${method} - ${path}` as a fallback for the title of the request in the sidebar. But already show the request method, so using just the `request.path` should be good.
**Before**
**After**

feat(api-client): use just the request path as a fallback for the sidebar

---

.changeset/slimy-bananas-prove.md
packages/oas-utils/src/helpers/isLocalUrl.test.ts
packages/oas-utils/src/helpers/isLocalUrl.ts
packages/oas-utils/src/helpers/redirectToProxy.test.ts

When we added support for requests to URLs without the http/https protocol prefix, we’ve added a check that was looking for dots in URLs to detect domains.
Turns out, relative file paths with a dot in them look like valid URLs (without a protocol). That led to an exception when e.g. `openapi.yaml` was passed as an OpenAPI document URL.
This PR tries to create a new `URL` object in the `isLocalUrl` check, which will fail for a bunch of cases and then return false - which eventually makes our packages to skip the proxy. Which is what we want for relative URLs (but also for invalid URLs).
**Example**
```html
<script
id="api-reference"
data-url="openapi.yaml"></script>
```
**Exception**

fix(oas-utils): throws an error for relative file paths

---

.github/workflows/ci.yml

We just had a galaxy brain idea: We don’t need to wait for the build to run the tests. 👀 
Let’s run them in parallel. This should shave off 60s CI time, but even better:
We’ll get the feedback for failed tests way earlier.
I think we need to build at least two packages, the CLI and the fastify package, because they test the build. Let’s see.

ci: don’t wait for the build to run the tests

---

examples/proxy-server/Dockerfile
examples/proxy-server/package.json

I’ve tried this already, but let’s try again: The proxy server got an API reference, but it’s not served in production:
```
Error reading index.html
```
This PR should finally add the static assets to the image.

fix(proxy-server): error reading from static assets

---

.changeset/real-cheetahs-end.md
.changeset/silver-boats-mate.md
packages/api-client/src/views/Request/RequestSection/RequestBody.vue
packages/oas-utils/src/entities/spec/request-examples.ts

this pr is a proposal to get the key/value form parameter displayed in the request body of the api client:

fix(api-client): sets form parameter key request body

---

.changeset/funny-hornets-arrive.md
packages/api-reference/src/features/Search/SearchButton.vue

this pr fixes #2740 and updates `meta + k` command in api reference in order to trigger the command even while holding the meta key and re-pushing `k`.

fix(api-reference): meta + k holding search modal

---

.changeset/smart-rice-move.md
packages/postman-to-openapi/src/convert.test.ts
packages/postman-to-openapi/src/convert.ts
packages/postman-to-openapi/src/helpers/authHelpers.ts
packages/postman-to-openapi/src/helpers/itemHelpers.ts
packages/postman-to-openapi/src/helpers/requestBodyHelpers.ts
packages/postman-to-openapi/src/helpers/responseHelpers.ts
packages/postman-to-openapi/src/helpers/serverHelpers.ts
packages/postman-to-openapi/src/types.ts

**Problem**
Currently, the parser misinterprets Postman Examples/response bodies as folders, causing incorrect parsing. This affects everything in the parser, resulting in the converted OpenAPI spec missing request bodies, response bodies, servers, etc.
**Solution**
With this PR, we refactor the parser to properly handle servers within Postman folders, move the status codes parsing from `itemHelpers.ts` to a more appropriate place in `responseHelpers.ts`, make small improvements to tag handling, along with other small improvements to formatting and more robust tests by removing redundant tests and adding new tests for response bodies, request bodies, and nested servers.

fix(postman-to-openapi): Postman examples are misinterpreted as folders

---

.changeset/honest-cooks-push.md
packages/api-client/tailwind.config.ts

this pr fixes the address bar background color that was not showing up anymore by safelisting tailwing background utilities:

fix(api-client): address bar background

---

.changeset/tender-mirrors-do.md
.changeset/wet-brooms-drop.md
packages/api-client/src/components/CommandPalette/CommandPaletteRequest.vue
packages/api-client/src/components/HttpMethod/helpers.ts
packages/api-client/src/components/HttpMethod/index.ts
packages/api-client/src/views/Request/libs/live-sync.ts
packages/oas-utils/src/helpers/httpMethods.ts
packages/oas-utils/src/transforms/import-spec.test.ts
packages/oas-utils/src/transforms/import-spec.ts

this pr fixes #4088 in order to sort method based on path VS prior method iteration as it was altering the operation order:
⊢ before / after for [galaxy](https://galaxy.scalar.com/)
<div>
</div>

fix(oas-utils): order of imported operations

---

.changeset/calm-ties-relate.md
packages/scalar-app/src/main/index.ts

this pr fixes #4099 adds a dialog box on check for updates action to display information that the app is up to date along its version.

feat(scalar-app): adds dialog box on check for updates

---

.changeset/polite-zoos-fly.md
packages/api-client/src/components/Sidebar/Actions/SidebarListElementForm.vue

this pr fixes variant danger style in use that display filled background by removing unused utilities:
<div>
</div>

fix(api-client): variant danger style

---

.changeset/shaggy-toys-fetch.md
packages/api-client/src/views/Request/RequestSidebar.vue

this pr fixes the watch mode toggle from sidebar that was not mutating the collection + adds a toast for the state:

fix(api-client): watch mode toggle from sidebar

---

.changeset/fluffy-spies-glow.md
packages/api-client/src/views/Request/RequestSidebarItem.vue

this pr is a proposal to filter out the first request example in order to avoid duplicating the main request data, this way we only access main request example from the request, and show up manually created examples:
<div>
</div>

fix(api-client): sidebar request examples

---

examples/fastify-api-reference/src/index.ts

Make the base route the reference. This is easier and makes more sense than having the base route return a 404 and needing to navigate to `/reference`

fix(fastify-api-reference): make the base route the reference

---

.changeset/thin-tools-cheer.md
packages/api-client/src/views/Request/RequestSidebarItem.vue

this pr fixes the sidebar request button being displayed in modal:
<div>
</div>

fix(api-client): sidebar request button

---

.changeset/cuddly-berries-remain.md
.changeset/itchy-lemons-wait.md
packages/api-client/src/views/Request/components/WorkspaceDropdown.vue
packages/components/src/components/ScalarTooltip/ScalarTooltip.vue

this pr updates the tooltip component in order to fix the tooltip visibility within client modal as seen below:
<div>
</div>
and also fix index issue in api client:
<div>
</div>

fix(api-client): tooltips have wrong z-index

---

.changeset/breezy-buses-leave.md
packages/api-reference/src/components/Section/CompactSection.vue

This PR fixes a circular dependency in the `<CompactSection />` component.
> Export "default" of module "src/components/Section/CompactSection.vue" was reexported through module "src/components/Section/index.ts" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.

fix(api-reference): circular dependency

---

.changeset/breezy-flowers-warn.md
packages/api-client/src/views/Request/RequestSection/RequestBody.vue

this pr adds back the request body border updated in #3981 + fixes broken selected example as seen in #3809
<div>
</div>

fix(api-client): request body examples

---

.changeset/brave-birds-tap.md
packages/api-client/src/views/Request/RequestSidebarItem.vue

this pr updates the style of the request sidebar item in api client in order to fix the button readability on long title:
disclaimer: moved the hover class higher to make sure the mask is on at the same time as the button getting displayed.
<div>
</dov>

style(api-client): request sidebar actions on hover

---

.changeset/chilled-ducks-wave.md
packages/api-client/src/views/Request/ResponseSection/ResponseEmpty.vue

this pr re-orders the empty response actions as seen below, nit/ocd but feels better:
<div>
</div>

style(api-client): empty response action order

---

.changeset/slow-waves-own.md
packages/api-client/src/views/Request/RequestSidebar.vue

this pr updates the watch mode toast watcher to prevent them from being displayed in editor/sandbox context:

fix(api-client): watch mode toast

---

README.md
packages/scalar-app/README.md

This PR adds a Scalar App version badge to the root README and the Scalar App README:
Actually, @antlio built this. I’ve added this to the READMEs only.
**Button**
[![Scalar App](https://img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fapi.todesktop.com%2Fv1%2FgetReleaseBuildIds%3FappId%3D240718bnjmcfyp4&query=%24.releases%5B%3A1%5D.version&label=Scalar%20App&labelColor=%231a1a1a&color=%23e7e7e7)](https://scalar.com/download)
**Preview**

docs: add scalar app version badge

---

.changeset/silent-papayas-call.md
packages/oas-utils/src/entities/spec/request-examples.ts

this pr fixes #4142 by update parse enum in request example entity to include array:
<div>
</div>

feat(oas-utils): request example parse enum array

---

.github/dependabot.yml

Some dependencies just require manual updates, I was not able to merge one of the dependabot PRs for them without fixing some type mismatches.

chore: make dependabot ignore some dependencies

---

.changeset/khaki-hairs-help.md
packages/api-reference/src/components/Content/Schema/SchemaProperty.test.ts
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue

this pr increases the number of enum item visible in the api reference:
_initially requested [in discord by @Arthur](https://discord.com/channels/1135330207960678410/1135330208627564597/1311623771710296074)_

feat(api-reference): enum value visible item number increase

---

.changeset/spicy-islands-enjoy.md
packages/api-reference/src/hooks/useNavState.ts

**Problem**
The id attribute value of the `<section>` element is being encoded using encodeURIComponent(), for example:
When a document link with a hash is opened in a new tab, the browser attempts to find the element corresponding to the hash and scroll to it. This behavior is similar to the following code:
However, because the element cannot be found due to the encoding, the browser does not scroll to the intended section.
**Solution**
Remove `encodeURIComponent()` from [packages/api-reference/src/hooks/useNavState.ts](https://github.com/scalar/scalar/compare/main...lc-soft:scalar:lcsoft/fix-nav-id?expand=1#diff-ccdd228d6187612f62c06d9aaafbc4c0c9fa973ca37de2d80744df2b7dccdb43)
The id attribute value of the `<section>` element will then be set as follows:
With this change, the browser …

fix(api-reference): correct anchor id encoding to ensure correct page scrolling

---

.changeset/lovely-bikes-lick.md
.changeset/strong-shoes-retire.md
packages/api-client/src/components/AddressBar/AddressBarServerItem.vue
packages/api-client/src/libs/create-client.ts
packages/api-client/src/libs/send-request/send-request.ts
packages/api-client/src/views/Request/RequestSection/RequestPathParams.vue
packages/api-client/src/views/Request/RequestSection/RequestSection.vue
packages/api-reference/src/features/ApiClientModal/ApiClientModal.vue

this pr fixes #4158 by :
- bringing back the variables table on server using path variable
- fixes send request to include variable values
- style address bar server dropdown
- sets values from reference to client modal
⊢ variables before / after
<div>
</div>
⊢ address bar dropdown before / after
<div>
</div>

fix(api-client): server variables

---

.github/workflows/ci.yml
.github/workflows/deploy-examples.yml
.github/workflows/lint-icons.yml
.github/workflows/lint-markdown-files.yml
.github/workflows/lint-pr.yml
.github/workflows/test-cdn-jsdelivr.yml
.github/workflows/test-cdn-local.yml
.github/workflows/test-electron-app.yml
.github/workflows/test-nuxt-integration.yml
.github/workflows/update-contributors.yml
.github/workflows/validate-openapi-file.yml

**Problem**
Currently, some CI jobs are running for an extended period of time.
**Solution**
With this PR, CI jobs run for a maximum of 15 minutes before they timeout. This is a stop-gap solution while we improve our workflows. In the meantime, this will stop our workflows running for too long.

chore: ci jobs timeout after 15 minutes

---

.changeset/shaggy-mayflies-sell.md
packages/api-reference/src/components/Anchor/Anchor.vue
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/Content/Introduction/Description.vue
packages/api-reference/src/components/Section/CompactSection.vue
packages/api-reference/src/components/Section/Section.vue
packages/api-reference/src/components/Sidebar/SidebarElement.vue
packages/api-reference/src/hooks/useNavState.ts

We have no ability to use hashes in a consuming app due to API Reference force overwriting them.
This allows an integration to a set a hash prefix that will be ignored by the references.

feat(api-reference): Adds optional hash prefixing

---

.github/actions/build/action.yml

Runners for GitHub Actions have two cores. This PR limits the heavy build job to just use a maximum of two processes to avoid hitting limits.

ci: limit build process to two processes

---

.changeset/tiny-turkeys-thank.md
packages/api-reference/src/components/ApiReferenceLayout.vue

Hotfix for hardocoded test prefix

fix(api-reference): Incorrect prefix

---

.github/workflows/test-cdn-jsdelivr.yml
.github/workflows/test-cdn-local.yml
.github/workflows/test-electron-app.yml
.github/workflows/test-nuxt-integration.yml
.github/workflows/validate-openapi-file.yml

With this PR, workflows use the composite build action for building packages.

chore: use composite build action instead of pnpm script

---

.changeset/rotten-lobsters-lick.md
packages/api-reference/src/components/DarkModeToggle/DarkModeToggle.vue
packages/api-reference/src/components/Layouts/ClassicLayout.vue
packages/api-reference/src/components/Layouts/ModernLayout.vue

this pr fixes the sidebar footer being totally hidden on modern layout `hideDarkModeToggle` configuration:
<div>
</div>

fix(api-reference): hide darkmode toggle only

---

.changeset/new-falcons-enjoy.md
packages/api-client/src/components/AddressBar/AddressBar.vue
packages/api-client/src/components/AddressBar/AddressBarServer.vue

this pr fixes the address bar servers component being display even on active collection without servers as we were fallbacking on activeServer anyway :pedro-laugh-cry: . I also propose in that PR to get the dropdown displayed for unique server in order to get access easily to the `Add Server` button.
⊢ draft request before / after
<div>
</div>
⊢ request with unique server before / after
<div>
</div>

fix(api-client): address bar servers dropdown display

---

.changeset/neat-onions-destroy.md
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestExampleAuth.vue

this pr hides flow row for unique scheme flow:
<div>
</div>

fix(api-client): request example auth flow

---

.github/actions/build/action.yml
.github/workflows/ci.yml
package.json
pnpm-lock.yaml

Not related to the current issues, but just found out you can control whether turborepo writes the cache. This feature was introduced in turbo@2.2.4, that’s why updated Turborepo, too.
With this PR subsequent builds read from the local cache (that was restored by GitHub Actions), without writing to it.
https://turbo.build/repo/docs/reference/run#--cache-options
EDIT: While this feels cleaner, I can’t see any performance benefits. The whole action takes ~50s and turborepo say the build takes ~700ms with and without this PR.

ci: read from cache for subsequent builds

---

.changeset/brave-grapes-march.md
.changeset/silent-dingos-hide.md
.changeset/tough-buttons-begin.md
packages/api-reference/src/helpers/parse.ts
packages/api-reference/src/standalone.ts
packages/nuxt/package.json
packages/nuxt/src/runtime/components/ScalarApiReference.vue
packages/oas-utils/src/transforms/import-spec.ts
packages/openapi-parser/package.json
packages/openapi-parser/src/types/index.ts
packages/openapi-parser/src/utils/details.ts
packages/openapi-parser/src/utils/normalize.test.ts
packages/openapi-parser/src/utils/normalize.ts
packages/openapi-parser/src/utils/upgrade.test.ts
packages/openapi-parser/src/utils/upgrade.ts
packages/openapi-parser/src/utils/upgradeFromThreeToThreeOne.ts
packages/openapi-parser/src/utils/upgradeFromTwoToThree.test.ts
packages/openapi-parser/src/utils/upgradeFromTwoToThree.ts
packages/openapi-parser/src/utils/validate.test.ts
packages/types/src/legacy/reference-config.ts
packages/types/src/utils/utility-types.ts
pnpm-lock.yaml

When passing `null` (or an empty string) as the content, errors are thrown.
This PR fixes it in multiple places to improve the handling for various use cases.
**@scalar/openapi-parser**
* `normalize()` returns `{}` for empty OpenAPI documents
* added tests for the `normalize()` utility, can’t believe we didn’t had any
* `upgrade()` (and the specific upgrade helpers) deal with empty content
* `details()` utility handles empty content
* replaced some uses of `AnyObject` with `UnknownObject` and fixed TS issues
**@scalar/oas-utils**
* skip the parser for empty content, add a console.warning
**@scalar/types**
* explicitly allow `null` in the `SpecConfiguration`
**@scalar/api-reference**
* Slightly improve the types in the horrible `parse` helper
**@scalar/nuxt**
* import `ReferenceConfig` …

fix: content `null` throws an error

---

.changeset/three-toys-breathe.md
packages/api-client/src/views/Request/RequestSection/RequestPathParams.vue

This line seems to be deleting path params, @antlio what was it for?
Before:
After:

fix: path params disapearing

---

.changeset/strong-flowers-melt.md
packages/components/src/components/ScalarMenu/ScalarMenuButton.vue
packages/components/src/components/ScalarMenu/ScalarMenuProduct.vue

Just cleans up a couple little issues with the ScalarMenu.
Before:
After:
Before and after:

chore(components): ScalarMenu component cleanup

---

.changeset/cyan-geese-dream.md
packages/api-reference/src/components/ApiReferenceLayout.vue

I’ve just found out we’re still using the deprecated ~~proxy~~ attribute in `@scalar/api-reference`, let’s default to the new `proxyUrl` attribute.

fix(api-reference): workspace store uses deprecated proxy attribute

---

.changeset/shaggy-moons-accept.md
.changeset/twelve-ducks-matter.md
examples/ssg/src/App.vue
packages/api-client/src/store/store.ts
packages/api-reference/src/components/ApiReference.vue
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/features/Search/SearchButton.vue
packages/api-reference/src/index.ts
packages/use-hooks/src/useBreakpoints/useBreakpoints.test.ts
packages/use-hooks/src/useClipboard/useClipboard.test.ts
packages/use-hooks/src/useColorMode/useColorMode.test.ts
packages/use-hooks/src/useColorMode/useColorMode.ts

The SSG build is broken, let’s fix it!
```bash
cd examples/ssg
pnpm build
```
**Source**
https://github.com/scalar/scalar/blob/main/packages/api-reference/src/components/ApiReferenceLayout.vue#L321-L329
**Error**
```
Error: Could not parse CSS stylesheet
at exports.createStylesheet 
…
@layer scalar-theme {
/* basic theme */
.light-mode {
--scalar-background-1: #fff;
--scalar-background-2: #f6f6f6;
--scalar-background-3: #e7e7e7;
--scalar-background-accent: #8ab4f81f;
--scalar-color-1: #2a2f45;
--scalar-color-2: #757575;
--scalar-color-3: #8e8e8e;
--scalar-color-accent: #0099ff;
--scalar-border-color: #dfdfdf;
}
```

fix(api-reference): SSG build is broken

---

.changeset/afraid-beds-sneeze.md
packages/api-reference/src/components/Sidebar/Sidebar.vue
packages/api-reference/src/components/Sidebar/SidebarElement.vue
packages/api-reference/src/features/DownloadLink/DownloadLink.vue
packages/code-highlight/src/css/markdown.css
packages/themes/src/variables.css

add font weights sidebar items (active, inactive) in a css variable
add link hover colours in a variable
add link weights in a variable
add link text decoration colours in a variable

feat(api-reference): extend font weights for links and sidebar items

---

.github/workflows/ci.yml

Let’s decrease the timeout from 15 to 10 minutes. A full build should only take 5-6 minutes.

ci: decrease timeout to 10 minutes

---

.github/actions/build/action.yml

Another attempt to fix CI by increasing the Node memory limit. 👀 
EDIT: This looks good, there’s a high chance this actually fixes it.

ci: increase memory limit for build step

---

.changeset/slow-spies-roll.md
packages/openapi-parser/src/utils/upgradeFromThreeToThreeOne.test.ts
packages/openapi-parser/src/utils/upgradeFromThreeToThreeOne.ts

**Problem**
Currently, if the schema contains `format: binary`, it will be converted to undefined, resulting in the following error and the API client window will be blank.
The content of the schema YAML file is as follows:
**Solution**
With this PR, I referred to the code in the upgradeFromThreeToThreeOne.ts file and changed the upgrade result of `format: binary`.

fix(openapi-parser): correct schema upgrade for "format: binary"

---

.changeset/fresh-geckos-peel.md
packages/api-client/src/libs/create-client.ts
packages/api-reference/src/features/ApiClientModal/ApiClientModal.vue

This reverts [commit 51bfd5f](https://github.com/scalar/scalar/pull/4160/commits/51bfd5f7d5258881ae3a852df6b70be3a784b0fb) which is preventing the path parameters to be displayed in the api reference client modal.
Will get back to it with a better approach based in that case on retrieving the server variables.

revert(api-reference): sets server variables values in client

---

CODEOWNERS

Let’s add @geoffgscott to the CODEOWNERS file for /.github (CI). :)

chore: add geoff to CI codeowners

---

.changeset/khaki-singers-refuse.md
.changeset/tricky-weeks-admire.md
packages/api-client/src/components/SideNav/SideNav.vue
packages/api-client/src/components/Sidebar/SidebarListElement.vue
packages/api-client/src/views/Environment/Environment.vue
packages/api-client/src/views/Request/RequestSection/RequestBody.vue
packages/api-client/src/views/Request/RequestSubpageHeader.vue
packages/components/src/components/ScalarSearchInput/ScalarSearchInput.vue

this pr fixes few alignment and padding inconsistencies as seen below:
⊢ workspace dropdown alignment before / after
⊢ environment dropdown alignment before / after
⊢ body border before / after

style(api-client): enhances padding and alignment consistency

---

.github/workflows/test-cdn-jsdelivr.yml
.github/workflows/test-cdn-local.yml
.github/workflows/test-electron-app.yml
.github/workflows/test-nuxt-integration.yml

We’ve added a check whether the playwright dependencies (browsers) were restored from cache, but that check failed for Playwright version updates (for whatever reason) - and with it all tests.
https://github.com/scalar/scalar/actions/runs/12375837584/job/34541570648?pr=4255
It turns out, we don’t need to cache Playwright binaries.
> Caching browser binaries is not recommended, since the amount of time it takes to restore the cache is comparable to the time it takes to download the binaries.
Source: https://playwright.dev/docs/ci#caching-browsers

ci: do not cache playwright binaries

---

.changeset/weak-schools-train.md
packages/nextjs-api-reference/package.json
packages/nextjs-api-reference/vite.config.ts
pnpm-lock.yaml

We have a commit hook that keeps changing them, so I just removed it. It is safe to assume that next.js users have next.js and react installed 🙂

chore: bump next.js peerDependencies again

---

.changeset/brave-hornets-look.md
packages/api-client-react/README.md
packages/api-reference-react/README.md
packages/nextjs-api-reference/README.md

Should have made the react 19 upgrade a minor bump due to it not being backwards compatible with older react versions. This PR gives it a minor bump + updates the readmes

docs(changeset): react 19 upgrade minor bump

---

.github/workflows/ci.yml

I think the recent issues we faced with publishing were related to having the `changesets/action` running in parallel doing two different things. 🤔
Anyway, publishing shouldn’t be executed in parallel and existing jobs shouldn’t be canceled, so let’s add this to the CI workflow.
EDIT: #4261 should make CI green

ci: no concurrent publish

---

.changeset/famous-worms-wash.md
packages/api-client/src/views/Request/RequestSection/RequestParams.vue

this pr updates the request params clear action in the api client in order to allow clearance on enabled items, however required items will remain + it adds a tooltip information as seen below:

fix(api-client): request params clear action

---

.changeset/popular-peas-listen.md
packages/api-reference/src/features/ApiClientModal/ApiClientModal.vue

This is just a quick fix to reduce typing lag. The actual fix should be to switch to the live sync diff as stated in [this ticket](https://github.com/scalar/scalar/issues/4290) but this does the job for now 🙂 
to test:
```bash
pnpx turbo dev --filter @scalar/api-reference-editor
```

fix(api-reference): debounce client config updates to increase perf

---

.changeset/poor-toys-sip.md
packages/api-reference/src/hooks/useNavState.ts

**Problem**
Currently, manually refreshing the page or using a URL with a hash to open a new tab does not cause the corresponding section to scroll into the view. I have fixed similar issue in PR #4173.
I found that this issue is caused by this commit:
https://github.com/scalar/scalar/commit/56c1981d9a1e0b38837fa6881f6f76a17cc7b616#diff-ccdd228d6187612f62c06d9aaafbc4c0c9fa973ca37de2d80744df2b7dccdb43L68-R77
**Solution**
With this PR, the section id and `hash.value` are both raw values that have not been encoded with `encodeURIComponent()`, allowing the browser to correctly find the section and scroll it into view.

fix(api-reference): correct `hash.value` encoding to ensure scrolling

---

.changeset/sharp-ears-clean.md
packages/api-client/src/components/AddressBar/AddressBar.vue
packages/api-client/src/components/Sidebar/Sidebar.vue
packages/api-client/src/components/Sidebar/SidebarToggle.vue
packages/api-client/src/libs/create-client.ts
packages/api-client/src/store/store.ts
packages/api-client/src/views/Request/Request.vue
packages/api-client/src/views/Request/RequestSidebar.vue
packages/api-client/src/views/Request/RequestSubpageHeader.test.ts
packages/api-client/src/views/Request/RequestSubpageHeader.vue

**Problem**
The `showSidebar` config option doesn't do anything in the client
**Solution**
We now do not render the sidebar if that config option is false. Giving us a nice performance boost on big specs. I also renamed the old `showSidebar` var to `isSidebarShowing` to more accurately reflect what it does.
**Checklist**

fix(api-client): showSidebar config option for the client

---

.github/workflows/ci.yml

Let’s not skip CI for release PRs, I’m not really convinced this is the right solution.
But let’s make the important jobs a requirement for the publish jobs.
---
~~Release PRs are created automatically by GitHub Actions. But GitHub Actions doesn’t trigger workflows for actions performed by bots (to avoid infinite loops), that’s why they don’t run when the release PR is (automatically) updated (by the bot).~~
~~This looks like CI is hanging, so let’s just skip CI for the release PR.~~
~~**But, Hans, isn’t that dangerous?**~~
~~I don’t think so! Code has passed CI three times before being published:~~
~~1. In the PR branch (the UI warns if it’s not rebased on main)
2. When it’s in main (and the release PR is created eventually)
3. Once it’s in main again (after the release PR is merged, the …

ci: make important jobs a requirement for the publish process

---

.changeset/mean-starfishes-kick.md
packages/api-reference/src/components/ApiReferenceLayout.vue

:)
we need to add an immediate here for the case where we directly pass in a parsed spec, vs the usual way we do things (it loads after it starts empty

fix: initial workspace load

---

.changeset/dull-otters-lay.md
.changeset/lovely-carrots-guess.md
packages/api-client/src/views/Request/Request.vue
packages/oas-utils/package.json
packages/oas-utils/src/migrations/data-version.ts
packages/oas-utils/src/migrations/migrator.ts
packages/oas-utils/src/migrations/v-2.4.0/index.ts
packages/oas-utils/src/migrations/v-2.4.0/migration.ts
packages/oas-utils/src/migrations/v-2.4.0/types.generated.ts

this PR is the final touch in fixing #4240 and includes:
- send request updates
- drafts requests migration
⊢ send request updates
+ sets active server only for non drafts requests in order to avoid issue on draft usages
⊢ drafts requests migration
+ removes server from drafts request 
+ moves previously used server to the path

fix(api-client): removes server in drafts requests

---

.changeset/thick-flowers-play.md
packages/api-reference/src/components/ApiReferenceLayout.vue

**Problem**
With `immediate: true` we sometimes send an empty spec to the watcher which then tries to create a store from it. 
**Solution**
We ensure a spec exists before trying to do so.
**Checklist**
before:
after:

fix(api-reference): ensure store exists before trying to create store

---

.changeset/odd-maps-stare.md
packages/api-client/src/views/Request/RequestSection/RequestParams.vue

**Problem**
Params aren't saving or sending (store is not being updated)
**Solution**
We rollback and use a different strategy for the stricter tsconfig update
closes #4325
**Checklist**

fix(api-client): params not saving or sending

---

.changeset/breezy-mice-tap.md
packages/oas-utils/src/migrations/v-2.4.0/migration.ts

this pr updates the 2.4.0 migration to only return the non drafts collections without changes.

chore: updates migration

---

.changeset/tiny-colts-tickle.md
packages/api-client/src/components/EnvironmentSelector/EnvironmentSelector.vue
packages/oas-utils/src/migrations/v-2.4.0/migration.ts

Rolls back the migration bug from earlier. Also removes `as`

fix(api-client): revert migration change

---

.changeset/eleven-taxis-act.md
packages/api-client/src/views/Request/RequestSection/RequestParams.vue

**Problem**
Currently we get a nasty runtime error w radix tooltip! not sure why, but gunna comment it out and resolve in the new year
https://github.com/scalar/scalar/issues/4334
**Solution**
i commented it out
**Checklist**

fix: runtime error with radix tooltip

---

.github/workflows/ci.yml
packages/scalar-app/package.json

The toDesktop build takes too long, and CI is failing when it’s waiting for the build.
But there’s no benefit that we get from waiting for it, so let’s just trigger the build and continue.
Should make the release commits green again.
https://github.com/scalar/scalar/actions/runs/12435977129/job/34723231861

ci: async todesktop build

---

README.md

I’ve just discovered a new Scalar Django integration by @m1guer! Let’s add it to the root README. :)

docs: add Django integration to the root README

---

.changeset/angry-boxes-argue.md
packages/api-client/src/views/Request/RequestSidebar.vue

**Problem**
request sidebar search cannot be toggle back when opened and not being populated.
**Solution**
this pr updates the code and removes blur action that was keeping the visibility to true in order to be able to be able to toggle the search visibility back.
|  <video src="https://github.com/user-attachments/assets/930eed9a-4a77-4870-b506-09bdc6cc2f40" /> |  <video src="https://github.com/user-attachments/assets/bff92df1-ad46-4885-94f1-6fa2593e6717" /> |
| search visibility is always true | search visibility toggle back |
**Checklist**

fix(api-client): request sidebar search toggle

---

.changeset/calm-beds-explode.md
packages/use-toasts/package.json
packages/use-toasts/src/components/ScalarToasts.test.ts
pnpm-lock.yaml

Let’s clean up @scalar/use-toasts a little bit.
With this PR it’s finally:
* using `@scalar/build-tooling`
* having tests 🥳

chore(use-toasts): update build process

---

.changeset/tall-islands-lay.md
packages/api-client/src/components/Sidebar/SidebarList.vue
packages/api-client/src/views/Cookies/Cookies.vue
packages/api-client/src/views/Environment/Environment.vue

**Problem**
recent changes in #4247 broken the consistency through the different pages.
**Solution**
this pr updates sidebar item ui to keep consistency within pages through border re-alignment, spacing updates + icon size consistency.
| <img width="275" alt="image" src="https://github.com/user-attachments/assets/bccf8308-462e-4df8-909d-cbed23d9bf0e" /> | <img width="275" alt="image" src="https://github.com/user-attachments/assets/2d5eca02-296d-4c58-ac60-0203f14363f7" /> |
| left border not aligned + inconsistent icon size & border top | left border re-aligned + icon size increased & border top removed  |
**Checklist**

style(api-client): sidebar views ui consitency

---

.changeset/ten-dodos-sip.md
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue

this pr fixes #1971 by adding example to the schema heading:
<div>
</div>

feat(api-reference): adds example property in schema heading

---

.changeset/clever-rocks-allow.md
packages/api-client/src/components/ContextBar.vue
packages/api-client/src/components/EnvironmentSelector/EnvironmentSelector.vue
packages/api-client/src/components/ViewLayout/ViewLayoutCollapse.vue
packages/api-client/src/components/ViewLayout/ViewLayoutSection.vue
packages/api-client/src/views/Request/RequestSection/RequestSection.vue
packages/api-client/src/views/Request/RequestSidebar.vue
packages/api-client/src/views/Request/RequestSubpageHeader.vue
packages/api-client/src/views/Request/ResponseSection/ResponseHeaders.vue

this pr is updating utilities + removing some left over from #4247 as discussed w/ @cameronrohani and according to @hwkr post merge review.
i fixed some alignment in the last commit:
<div>
</div>

fix(api-client): layout fixtures

---

.changeset/swift-beds-hear.md
packages/api-client/src/views/Request/RequestSidebar.vue

**Problem**
watch mode state notification get displayed in the desktop app when removing a collection.
**Solution**
this pr prevents displaying watch mode state notification on collection deletion + for drafts collection and add missing type in request sidebar component file.
**Checklist**

fix(api-client): request sidebar watch toast

---

.changeset/real-dolls-walk.md
packages/oas-utils/src/spec-getters/getExampleFromSchema.test.ts
packages/oas-utils/src/spec-getters/getExampleFromSchema.ts

**Problem**
Currently, we don't add anything to the generated examples when the schema has `patternProperties` (just a regex pattern instead of a property name).
**Solution**
With this PR we use the regex pattern as the property name, see the attached test for an example.
Fixes #3911.
**Checklist**

feat(oas-utils): examples for schemas with `patternProperties`

---

documentation/integrations/go.md

This fixed some small typos in go integrations related docs.

docs: fixed small typos in go.md

---

.changeset/dry-cars-listen.md
packages/nuxt/src/module.ts
packages/nuxt/src/runtime/components/ScalarApiReference.vue

**Problem**
Fixes #4204
The experimental OpenAPI feature in Nitro currently breaks this module. This is becasue the OpenAPI endpoint has moved from `/_nitro/openapi.json` to `/_openapi.json`
**Solution**
This PR updates the endpoint in the code. However, since the feature is experimental, it may change again. The documentation is here: https://nitro.build/config#openapi
I've also updated the `nitro:config` hook to set the `production` key to `prerender`. By default, the OpenAPI specification is only available during development. Setting this option will ensure the json file is prerendered and available in production. I've conditionally set the option as to not overwrite the user's configuration if they choose `runtime`.
**Checklist**
See the [contributing …

fix(nuxt): new OpenAPI endpoint

---

.changeset/heavy-pugs-remain.md
packages/api-reference/src/features/Operation/components/OperationParameters.vue
packages/api-reference/src/hooks/useOperation.ts

**Problem**
Currently, cookie parameters don’t show up in the list of parameters. 
See #4397 for more context
**Solution**
With this PR we’re adding the cookie parameters, so they don’t feel excluded anymore.
**Example**
```yaml
openapi: 3.1.0
info:
title: Hello World
version: 1.0.0
components:
parameters:
CSRFCookie:
name: csrf
in: cookie
description: Anti-CSRF cookie
required: true
schema:
type: string
paths:
/example:
post:
parameters:
- $ref: '#/components/parameters/CSRFCookie'
```
**Checklist**
I’ll add this fix and a test to #4281, where I modified the relevant components already.
EDIT: Done.

fix(api-reference): cookie parameters don’t show up

---

.changeset/empty-pants-love.md
packages/api-client/src/views/Request/ResponseSection/ResponseBodyVirtual.vue
packages/api-client/src/views/Request/ResponseSection/ResponseSection.vue
packages/components/src/components/ScalarVirtualText/ScalarVirtualText.vue

**Problem**
Currently, when receiving a response body above the virtualization threshold, the UI breaks, leaving the user unable to view the actual response body.
**Solution**
With this PR, I've updated the CSS from the component to fix this issue.
**Linked Issue**
closes #4365 
**Changes**
1. Added `overflow-x-auto` on the `ResponseBodyVirtual` component to fix the actual issue
2. Removed `mx-1` on the subcomponents to remove gap around containers
**Checklist**
---
Feel free to let me know if I can improve anything.

fix(api-client): UI breaking when response body too big

---

.changeset/loud-terms-pay.md
packages/scalar-app/src/renderer/src/main.ts

**Problem**
when using the desktop app, drop event creates empty collection as seen in #4349 - as relying on `text/uri-list` that is available in the app context.
to reproduce: 
- using the desktop app
- drag a request from a collection to another
| <img width="280" alt="image" src="https://github.com/user-attachments/assets/6ca0d2a6-385a-492d-b12d-26312a202bac" /> | <img width="280" alt="image" src="https://github.com/user-attachments/assets/702d34f4-6653-453e-9392-e3b389492c53" /> |
| an empty collection is created on drop event | no empty collection is created on drop event |
**Solution**
prevents self importation on drop event by avoiding import action for url origin.
**Checklist**

fix(scalar-app): drag self importation

---

.changeset/odd-timers-end.md
packages/api-client/src/views/Request/RequestSection/RequestParams.vue

**Problem**
currently empty api client usage through reference is throwing the following error:
**Solution**
this pr fixes #4334 as a follow of #4341 and makes sure to only have the clear action available in parameter presence.
tested using api client react playground as highlighted by @marclave.
**Checklist**

fix(api-client): request params tooltip runtime error

---

cloudbuild.json
tooling/cloudbuild/cloudbuildEnv.json

Some examples have moved from the `examples` folder to `packages`. This is updates the cloudbuild env to use the correct paths. Eventually all examples will be moved to packages. This migration is in progress 😄

ci: update paths of the fastify and express examples

---

.changeset/tough-pillows-kick.md
packages/api-reference/src/components/Content/Schema/SchemaProperty.test.ts
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue

**Problem**
Currently when using only one enum value, the value doesn't get displayed in the api reference schema property.
**Solution**
this pr fixes #2006 by showing enum of 1 value in the reference.
| <img width="439" alt="image" src="https://github.com/user-attachments/assets/6eb20e7b-23f6-4722-ac33-59b343d38682" /> | <img width="439" alt="image" src="https://github.com/user-attachments/assets/7aaf8536-f40e-453d-acdc-1f76de078db6" /> |
| enum list value is not being displayed | enum list value is displaying the one value |
**Checklist**

fix(api-reference): displays array enum of one

---

.changeset/shaggy-peas-begin.md
packages/api-reference/src/components/Content/Tag/Tag.vue

**Problem**
Currently if a tag has only one endpoint in a multiple tag reference - it cannot be collapsible (e.g. show more button).
**Solution**
this pr fixes #4409 by enabling collapsibility to non default tag that have one endpoint, this way if a reference has no tag usage the non collapsibility remain.
|  <img width="1185" alt="image" src="https://github.com/user-attachments/assets/55d260db-2e76-43d5-8c95-6310a3d63fcc" /> | <img width="1185" alt="image" src="https://github.com/user-attachments/assets/0ffbab36-d8c9-4090-ae26-2bec51f81101" /> |
| operations are displayed and are not collapsible | operations remain collapsed by default | 
**Checklist**

feat(api-reference): one endpoint tag collapsibility

---

.changeset/proud-frogs-shake.md
packages/api-client/src/views/Request/RequestSection/RequestParams.vue

**Problem**
following #4387  runtime error were displayed in the client and saucing #4418.
**Solution**
this pr extracts the tooltip display in a function and update the condition to check values and fixes #4418. 
**Checklist**

feat(api-client): show tooltip in request params

---

.changeset/new-spiders-hammer.md
packages/api-client/src/libs/send-request/create-request-operation.test.ts
packages/api-client/src/libs/send-request/send-request.ts

**Problem**
Currently empty parameters are not sent through request rather enabled or not.
**Solution**
this pr fixes #4406 in order to allows enabled empty parameters to be sent while keep omitting the non enabled ones.
nb. we should make sure that this still provide a solution for #3291
**Checklist**

fix(api-client): allows enabled empty parameters in request

---

.changeset/blue-bags-dance.md
packages/api-client/src/views/Request/RequestSection/RequestBody.vue

**Problem**
Currently, when settings data (key and value) in the multipart form body and uploading a file after. The file will overwrite the existing data you might have already set.
**Solution**
With this PR, I made sure the body will select key or value first if it exists already, otherwise it will default back to the filename for both fields.
**Issues**
solves #4357 
**Checklist**
---
Feel free to let me know if this change is what we would want. Or if I can change/improve anything.

fix(api-client): filename overwrites key/value in multipart form body

---

.changeset/sour-cougars-sing.md
packages/openapi-parser/src/utils/dereference.test.ts
packages/openapi-parser/src/utils/resolveReferences.ts

**Problem**
fix #4347 
**Solution**
Call the hook after dereferencing the schema, and add docs about the behaviours.
Also added `errors` array to parameter instead of return value of `dereference`, so it reduces a little memory usage
**Checklist**

fix(openapi-parser): call `onDereference` after dereference process

---

.changeset/pink-vans-repair.md
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue

**Problem**
a duplication has been introduced in #4162 for schema property example, being now shown twice.
**Solution**
this pr removes the duplication and update the style for array value.
| <img width="491" alt="image" src="https://github.com/user-attachments/assets/f6bb288d-82f0-4f8f-b651-02e50d2fb704" /> | <img width="491" alt="image" src="https://github.com/user-attachments/assets/eec90e11-2733-43d5-855b-033d03ea0a72" /> |
**Checklist**

fix(api-reference): schema example duplication

---

.changeset/perfect-crews-greet.md
packages/components/src/components/ScalarMenu/ScalarMenu.stories.ts
packages/components/src/components/ScalarMenu/ScalarMenuTeamPicker.vue

I remembered @marclave wanted a create new team button, also realized I should switch the radio menu to use the accessible Radix Vue radio group.
**Checklist**

feat(components): add create team button to team picker

---

.changeset/tame-news-grow.md
packages/api-client/src/components/AddressBar/AddressBar.vue
packages/api-client/src/libs/hot-keys.ts
packages/oas-utils/src/entities/hotkeys/hotkeys.ts

**Problem**
ctrl + enter doesnt work on linux anymore
**Solution**
ideally we would remove whenever + magic keys as they have caused issues in the past, but this is a quick fix that works
Update: did the proper fix and removed magic keys + whenever
**Checklist**

fix(api-client): linux enter hotkey

---

.changeset/mighty-penguins-invite.md
packages/api-client/src/libs/send-request/create-request-operation.test.ts
packages/api-client/src/libs/send-request/send-request.ts

**Problem**
Query params are duplicated when they are in the path string
**Solution**
We remove any query params from the path string
**Checklist**
closes #4428

fix(api-client): duplicate query params

---

.changeset/violet-bugs-hammer.md
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue
packages/api-reference/src/components/Content/Schema/helpers/formatExample.test.ts
packages/api-reference/src/components/Content/Schema/helpers/formatExample.ts
packages/api-reference/src/features/Operation/components/OperationResponses.vue
packages/api-reference/src/features/Operation/components/ParameterList.vue
packages/api-reference/src/features/Operation/components/ParameterListItem.vue

**Problem**
As a response to #1971 we’ve added the examples to all sections in the operation in #4162.
Turns out, it doesn’t really make sense to have the examples in the response list. It’s redundant with the box on the right side of the operation, and the formatting helper wasn’t really meant to deal with that kind of data.
Fixes #4438
**Solution**
With this PR the response list on the left doesn't show the example responses anymore and  the formatting helper is moved to a separate helper, got some tests and some better handling for other data types.
**Before**
**After**
**Checklist**

feat(api-reference): remove examples from responses

---

.changeset/silent-panthers-rescue.md
packages/openapi-parser/src/utils/traverse.test.ts
packages/openapi-parser/src/utils/traverse.ts
packages/openapi-parser/src/utils/upgradeFromThreeToThreeOne.test.ts

**Problem**
Currently, in some cases arrays are converted to objects during in the `upgrade` helper.
**Solution**
With this PR arrays will be arrays after the upgrade.
Fixes #4075 #3782.
**Example**
https://sandbox.scalar.com/e/fi5lT
**Before**
**After**
**Checklist**

fix(openapi-parser): example arrays are transformed to objects

---

.changeset/blue-parents-hunt.md
.changeset/twenty-cows-sleep.md
packages/api-client/src/components/ImportCollection/WorkspaceSelector.vue
packages/api-client/src/views/Environment/EnvironmentModal.vue
packages/components/src/components/ScalarModal/ScalarModal.vue

**Problem**
when opening the workspace creation modal form the import collection, the modal is not style nor displayed correctly.
**Solution**
this pr updates the style of the workspace creation modal as seen below:
| <img width="590" alt="image" src="https://github.com/user-attachments/assets/89ace468-1815-4053-a3a6-8193263c396a" /> | <img width="590" alt="image" src="https://github.com/user-attachments/assets/51184595-cc4f-4637-8782-76a39b591b8c" /> |
| modal border, radius are off + index  | modal has now consistent ui and proper context displayed | 
**Checklist**

fix(scalar-client): import collection workspace modal

---

.changeset/three-games-shave.md
packages/api-client/src/components/ImportCollection/ImportCollectionModal.vue

**Problem**
currently importing a reference to the client creates schema type issue (e.g. with hono).
**Solution**
this pr fallback to the default theme id if the integration theme is not supported / typed.
**Checklist**

fix(api-client): sets integration theme id fallback

---

.changeset/pink-mugs-repair.md
packages/openapi-types/src/openapi-types.test-d.ts
packages/openapi-types/src/openapi-types.ts

I’m splitting https://github.com/scalar/scalar/pull/4281 in a few smaller PRs.
**Problem**
Currently, we have a few places where keep a type for the HTTP methods.
**Solution**
With this PR we’re adding them to the `@scalar/openapi-types` package, so we’ll have a central place for it.
**Checklist**

feat(openapi-types): add HTTP methods

---

package.json
pnpm-lock.yaml

**Problem**
Currently, the preview release to stackblitz fails.
> npm warn exec The following package was not found and will be installed: pkg-pr-new@0.0.39
> Error: The operation was canceled.
https://github.com/scalar/scalar/actions/runs/12755774655/job/35552785137?pr=4448
**Solution**
This PR adds it as a dev dependency to the workspace, this should help.
**Checklist**

fix: missing dependency for the stackblitz preview release

---

.changeset/five-lizards-change.md
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue
packages/api-reference/src/components/Content/Schema/helpers/optimizeValueForDisplay.test.ts
packages/api-reference/src/components/Content/Schema/helpers/optimizeValueForDisplay.ts

**Problem**
Currently, the rendering for discriminators containing `null` is super verbose. Let’s be smarter and flatten them when possible.
Thanks @frankie567 for the idea!
**Before**
**After**
**Example**
```json
{
"openapi": "3.1.1",
"info": {
"title": "API Reference",
},
"schemas": {
"User": {
"modified_at": { "anyOf": [{ "type": "string", "format": "date-time" }, { "type": "null" }] },
"created_at": { "oneOf": [{ "type": "string", "format": "date-time" }, { "type": "number" }, { "type": "null" }] },
"not_created_at": { "not": [{ "type": "string", "format": "date-time" }, { "type": "number" }, { "type": "null" }] }
},
"required": ["modified_at"]
}
}
}
}
```
**Checklist**

feat(api-reference): flatten discriminators containing `'null'`

---

.changeset/long-beans-punch.md
.changeset/loud-boats-poke.md
packages/api-client/src/components/CommandPalette/CommandPaletteServer.vue
packages/api-client/src/components/DataTable/DataTable.vue
packages/api-client/src/components/DataTable/DataTableCell.vue
packages/api-client/src/components/Form/Form.vue
packages/api-client/src/components/SideNav/SideNavLink.vue
packages/api-client/src/components/Sidebar/Sidebar.vue
packages/api-client/src/components/Sidebar/SidebarList.vue
packages/api-client/src/components/Sidebar/SidebarListElement.vue
packages/api-client/src/components/ViewLayout/ViewLayoutCollapse.vue
packages/api-client/src/components/ViewLayout/ViewLayoutSection.vue
packages/api-client/src/constants.ts
packages/api-client/src/routes.ts
packages/api-client/src/views/Cookies/CookieForm.vue
packages/api-client/src/views/Cookies/Cookies.vue
packages/api-client/src/views/Environment/Environment.vue
packages/api-client/src/views/Environment/EnvironmentVariableDropdown.vue
packages/api-client/src/views/Request/RequestSidebar.vue
packages/api-client/src/views/Request/RequestSidebarItem.vue
packages/api-client/src/views/Request/ResponseSection/ResponseEmpty.vue
packages/api-client/src/views/Servers/ServerForm.vue
packages/api-client/src/views/Servers/Servers.vue
packages/api-client/tailwind.config.ts

**Problem**
it is not currently possible to add, update or delete server per collection.
**Solution**
this pr brings back initial work done by @hanspagel in a global server page. server variables including enum will follow along request server management that is currently under design tinkering.
| after |
| -------|
| <img width="889" alt="image" src="https://github.com/user-attachments/assets/a0099cd7-3abe-4f8a-805d-a0e2d08b63bd" /> |
| server page brought back along add, update, delete capability |
**Checklist**

feat(api-client): adds servers page back

---

.changeset/brave-carrots-jam.md
packages/api-client/src/libs/create-client.ts
packages/api-client/src/store/store.ts
packages/api-client/src/views/Request/RequestSubpageHeader.vue
packages/api-reference/src/components/ApiReferenceLayout.vue

**Problem**
currently the client button in the reference client button is relaying on collection integration only and not on the reference configuration, as used in the sidebar button. in some case the client button query is not the same in the reference and in the client.
**Solution**
this pr sets the usage of the reference configuration integration in the client button in modal to ensure value usage parity between reference and client.
**Checklist**

fix(api-client): favors configuration integration in modal client button

---

.changeset/seven-eels-compete.md
packages/api-reference/src/components/Content/Introduction/Introduction.test.ts
packages/api-reference/src/components/Content/Introduction/Introduction.vue
packages/api-reference/src/features/DownloadLink/DownloadLink.vue

**Problem**
Currently, a lot of people just having something like `1` or `2` as the version in their API definition, but I think the rendering might be a bit confusing. The number is just shown without any context.
**Solution**
With this PR it’s rendered as `v1`, which might be enough to make it look like a version number.
Wdyt?
**Checklist**

feat(api-reference): version prefix

---

.changeset/smooth-cooks-chew.md
packages/api-client/src/routes.test.ts
packages/api-client/src/routes.ts

**Problem**
the settings route is accessible anymore as it has somehow been removed in #4450
**Solution**
this par adds back the missing settings route.
**Checklist**

fix(api-client): settings route

---

.changeset/clever-badgers-rhyme.md
.changeset/lemon-mice-know.md
packages/api-reference/src/blocks/constants.ts
packages/api-reference/src/blocks/helpers/getLocation.test.ts
packages/api-reference/src/blocks/helpers/getLocation.ts
packages/api-reference/src/blocks/hooks/useBlockProps.ts
packages/api-reference/src/components/Content/Tag/TagList.vue
packages/api-reference/src/components/HttpMethod/HttpMethod.vue
packages/api-reference/src/features/Operation/Operation.test.ts
packages/api-reference/src/features/Operation/Operation.vue
packages/api-reference/src/features/Operation/layouts/ClassicLayout.vue
packages/api-reference/src/features/Operation/layouts/ModernLayout.vue
packages/types/src/legacy/reference-config.ts

I’m splitting https://github.com/scalar/scalar/pull/4281 in a few smaller PRs.
This PR renders the operation description from the store. It’ll be a bit weird in the transition phase and we’re actually way more ahead in the blocks PR, but let's just slowly migrate to a better future.
This PR:
* retrieves the request entity from the store inside the `<Operation />` component (just for the transition, won't be needed in the future)
* adds some light-weight helpers to make that easy
* takes the operation description from the store instead of our legacy `parsedSpec`
You might wonder why it’s only rendering the description from the store and not the other information:
It’s just that I think no one will be upset if that one thing doesn’t work. If we don’t see any issues with the description in …

feat(api-reference): render the operation description from the store

---

.changeset/stupid-gifts-call.md
packages/api-client/src/libs/send-request/send-request.ts

**Problem**
Currently, *all* cookies are deleted, even if they weren’t created by the API client. This breaks authentication in apps embedded our API reference.
**Solution**
With this PR we just don't delete cookies anymore. Not a real solution, but the quickest fix I could think of.
Fixes #3989
**Checklist**

fix(api-client): deletes all cookies

---

documentation/openapi.md

Updates our docs to match:
* [Redocly](https://redocly.com/docs-legacy/api-reference-docs/specification-extensions/x-tag-groups)
* [Our config](https://github.com/scalar/scalar/blob/main/packages/types/src/legacy/reference-config.ts#L544)
* [Our implementation](https://github.com/scalar/scalar/blob/main/packages/api-reference/src/hooks/useSidebar.ts#L268)
**Checklist**

docs(openapi): update x-tagGroup -> x-tagGroups

---

.changeset/late-hounds-share.md
packages/mock-server/src/createMockServer.test.ts
packages/mock-server/src/routes/mockAnyResponse.ts

**Problem**
Currently, the mock server returns write-only attributes in the responses.
**Solution**
With this PR we’re generating the response with `mode: 'read'` to omit write-only attributes.
**Checklist**

fix(mock-server): returns write-only attributes

---

.changeset/nervous-candles-hide.md
packages/api-reference/docker/package.json

This PR should trigger the initial release for the @scalar/api-reference Docker image.
Last time we attempted it, the repository didn’t exist on Docker Hub, but it does now.
Using the changeset, it should be tagged as 0.1.0.
Fixes #4356

chore(docker): trigger the initial release

---

.github/workflows/ci.yml
projects/client-scalar-com/wrangler.toml

**Problem**
Currently, we deploy everything that lands in main to `client.scalar.com` instantly. So we might break production more often.
**Solution**
With this PR we only deploy to production when a new version of `@scalar/api-client` is released, but deploy every commit in `main` to https://client.staging.scalar.com.
You can’t configure Cloudflare Pages to show different content on different domains. So I’ve created another project for staging.
**Checklist**

ci: deploy client to staging by default

---

.changeset/grumpy-beans-sell.md
packages/galaxy/src/specifications/3.1.yaml

**Problem**
Currently, the Galaxy examples shows read-only attributes (id) in the request, and write-only attributes (password) in the response.
**Solution**
With this PR we’re adding `readOnly: true` and `writeOnly: true` to attributes where applicable. This also made it possible to merge the `NewUser` and the `User` schemas.
Actually, I don’t know why I forgot about this when writing the initial document. 🤔 
**Checklist**

feat(galaxy): add `readOnly`/`writeOnly` attributes

---

.changeset/five-cups-destroy.md
packages/scalar.aspnetcore/playground/Scalar.AspNetCore.Playground/Books/Book.cs
packages/scalar.aspnetcore/playground/Scalar.AspNetCore.Playground/Books/BookEndpoints.cs
packages/scalar.aspnetcore/playground/Scalar.AspNetCore.Playground/Program.cs
packages/scalar.aspnetcore/playground/Scalar.AspNetCore.Playground/Properties/launchSettings.json
packages/scalar.aspnetcore/playground/Scalar.AspNetCore.Playground/Scalar.AspNetCore.Playground.csproj
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarEndpointRouteBuilderExtensions.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarOptionsExtensions.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Options/ScalarOptions.cs
packages/scalar.aspnetcore/tests/Scalar.AspNetCore.Tests/Scalar.AspNetCore.Tests.csproj
packages/scalar.aspnetcore/tests/apis/Scalar.AspNetCore.Tests.Api/Program.cs
packages/scalar.aspnetcore/tests/apis/Scalar.AspNetCore.Tests.Api/Scalar.AspNetCore.Tests.Api.csproj

Closes #4490 
**Problem**
With the last major release, we used a regex pattern for handling static assets. However, regex requires additional route policies, which may not exist in AOT (Ahead-Of-Time) compilation scenarios, causing the API to stop working.
**Solution**
In this PR, I have simplified the solution by moving away from using regex pattern. Since we only have two static assets, I have created two dedicated endpoints instead of one with a regex pattern.
**Others**
- Updated some dependencies
- Updated the playground to an AOT API
- Passing a `CancellationToken` to the `DocumentNamesProvider`. This is 💯% internal and not part of the public API.
**Checklist**

fix(Scalar.AspNetCore): support aot case

---

.changeset/unlucky-fireants-hope.md
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuthDataTable.vue

fixes #4449
**Problem**
Hitting enter in the auth input in references refreshes the page
**Solution**
We prevent on submit
**Checklist**

fix(api-reference): pressing enter in the password input causes the page refresh

---

documentation/guides/docs/github-sync.md
documentation/guides/introduction.md

Updates the GitHub sync markdown docs to reflect the dashboard updates and new publish flow.
I've also created a [template repository](https://github.com/scalar/docs-template) that folks can copy to build their docs site with and linked it in the updated documentation.

docs: update GitHub sync documentation to reflect new dashboard

---

packages/api-client/src/components/ContextBar.vue

**Problem**
SonarQube [found an issue](https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&issueStatuses=OPEN%2CCONFIRMED&id=xC0dex_scalar&open=AZR-cmd64ZKv-nhPxGj0) in this CSS file. As a .NET developer, I felt brave enough to fix it. 😎
**Solution**
~I bumped the number to 8 because that seems like what was intended.~ I removed the duplicated code.
**Checklist**
**Off-Topic**
BTW, I’m planning to open a discussion about SonarQube soon – I think it’s a valuable tool and worth diving deeper into.

fix(api-client):  duplicated css selector

---

.changeset/odd-parrots-lick.md
.changeset/pink-ways-protect.md
packages/api-client/src/views/Request/RequestSection/RequestBody.vue

**Problem**
when selecting binary as a request body content type, raw value are being removed + style inconsistencies.
**Solution**
this pr prevents raw value from being removed on binary type selection in order to be able to come back to it, and updates ui.
| <img width="632" alt="image" src="https://github.com/user-attachments/assets/61e30eb7-324a-4694-a1f5-b1e943c406db" /> | <img width="632" alt="image" src="https://github.com/user-attachments/assets/8766d60b-e4f6-42e0-aa4b-e5dce53e6273" /> |
| missing top border + wrong alignment of the label | border added and alignment straight | 
**Checklist**

fix(api-client): request body

---

.changeset/itchy-tigers-float.md
packages/code-highlight/src/code/highlight.test.ts
packages/code-highlight/src/code/highlight.ts

**Problem**
currently when using `token(` in credentials value, the code example is not rendered.
**Solution**
this pr fixes #4498 by removing regex instance to highlight credentials.
| <img width="546" alt="image" src="https://github.com/user-attachments/assets/6760878c-45ac-4f90-b3c4-11ec6b47835f" /> | <img width="546" alt="image" src="https://github.com/user-attachments/assets/2bbfd973-86d7-4bd3-a94f-8b7d5179804b" /> |
| code example is not rendered | code example get rendered |  
**Checklist**

fix(code-highlight): removes regex for highlight credentials

---

.changeset/shaggy-trees-sort.md
packages/api-client/src/views/Request/libs/oauth2.test.ts
packages/api-client/src/views/Request/libs/oauth2.ts

Make state variable a length of 8 to support OAuth providers (Kinde) who need more entropy in the state parameter
**Problem**
Currently, I cannot use Scalar to authenticate with Kinde due to the state parameter not being at least 8 characters
**Solution**
With this PR I am changing the length of the state parameter from 5 to 8.
**Checklist**

fix(api-client): change OAuth State parameter to a length of 8

---

.changeset/great-dots-approve.md
.changeset/mean-fishes-grin.md
packages/api-reference/src/components/ApiReferenceLayout.test.ts
packages/components/src/components/ScalarFloating/ScalarFloating.vue

**Problem**
Currently, we don't have proper SSG/SSR tests and don’t even notice when we break SSG/SSR builds.
**Solution**
This PR adds two basic tests which render a super simple OpenAPI document and a big real-world OpenAPI document (GitHub’s REST API).
See #4458
**Checklist**

test(api-reference): add SSR/SSG tests

---

.github/workflows/ci.yml
.github/workflows/deploy-components.yml

**Problem**
Currently, the components library is failing to build in CI. It is missing dependencies related to build-tooling. 
**Solution**
With this PR, 
`/workflows/deploy-components`
- Use [ellipsis](https://pnpm.io/filtering#--filter-package_name-1) to ensure that all direct and indirect dependencies are installed. 
* add a step to build the components library and related dependencies (build-tooling)
* Run all commands from root using `--filter` to ensure pathing is consistent. 
`/workflows/ci` 
* build storybook before deploying the preview
**Checklist**

fix(ci): components dependencies

---

.changeset/tame-pumpkins-approve.md
packages/components/src/components/ScalarMenu/ScalarMenuTeamPicker.vue
packages/components/src/components/ScalarMenu/ScalarMenuTeamProfile.vue

This PR correctly sets the role for team picker items (before it was being overridden by the `DropdownMenu.RadioGroup`) and hides the team profile icon from screen readers.
**Checklist**

fix(components): improve ScalarMenu team picker a11y

---

.changeset/strong-shirts-juggle.md
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarEndpointRouteBuilderExtensions.cs
packages/scalar.aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarEndpointTests.cs
packages/scalar.aspnetcore/tests/apis/Scalar.AspNetCore.Tests.Api/ApiKeyAuthenticationSchemeHandler.cs
packages/scalar.aspnetcore/tests/apis/Scalar.AspNetCore.Tests.Api/Program.cs

Closes #4529 
**Problem**
The recently introduced static assets endpoints may require authentication when a fallback authentication is configured. This results in `401 Unauthorized` responses when the browser attempts to load static assets.
**Solution**
I applied the `AllowAnonymous()` method to the static assets endpoints to ensure they bypass authentication. Additionally, I updated the test to cover this scenario.
**Checklist**

fix(Scalar.AspNetCore): allow anonymous for assets endpoint

---

.prettierignore

Looks like we’ve added a build folder which is not called dist, but didn’t add it to the .prettierignore yet.
That’ll change with this PR.

chore: add storybook build folder to .prettierignore

---

packages/scalar.aspnetcore/tests/Scalar.AspNetCore.Tests/Scalar.AspNetCore.Tests.csproj
packages/scalar.aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarEndpointTests.cs

This PR bumps the `xunit` dependency to version 3. I followed their [migration guide](https://xunit.net/docs/getting-started/v3/migration).

chore(Scalar.AspNetCore): migrate tests to xunit v3

---

.changeset/nine-walls-search.md
examples/proxy-server/README.md
examples/proxy-server/main.go
examples/proxy-server/main_test.go
packages/api-client/package.json
packages/api-client/playground/app/main.ts
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/components/CommandPalette/CommandActionInput.vue
packages/api-client/src/components/CommandPalette/TheCommandPalette.vue
packages/api-client/src/components/DataTable/DataTableInput.vue
packages/api-client/src/components/Form/Form.vue
packages/api-client/src/components/Sidebar/SidebarListElement.vue
packages/api-client/src/libs/send-request/create-request-operation.test.ts
packages/api-client/src/libs/send-request/send-request.ts
packages/api-client/src/libs/send-request/set-request-cookies.test.ts
packages/api-client/src/libs/send-request/set-request-cookies.ts
packages/api-client/src/store/active-entities.ts
packages/api-client/src/store/cookies.ts
packages/api-client/src/views/Cookies/CookieForm.vue
packages/api-client/src/views/Cookies/CookieModal.vue
packages/api-client/src/views/Cookies/Cookies.vue
packages/api-client/src/views/Request/RequestSection/RequestParams.vue
packages/api-client/src/views/Request/RequestSection/RequestSection.vue
packages/api-client/src/views/Request/RequestSection/RequestTable.vue
packages/api-client/vite.config.ts
packages/oas-utils/src/entities/cookie/cookie.ts
pnpm-lock.yaml

**Problem**
Currently, cookies don’t work at all. 🫨
**Solution**
With this PR cookies work. :) This is what changed:
* The cookie name for global cookies is stored.
* The cookie attributes that only the server can set are removed (expires, httpsonly, secure …).
* The global cookies are available in the request. 💥 
* The sidebar on the global cookie page is just a list now (the collapsing/expanding was broken).
* Global cookies are rendered as read-only in the list of request cookies (if they’ll be added to the request).
* The proxy can forward a custom `X-Scalar-Cookie` as a `Cookie` header (to circumvent browser policies).
* Cookie authentication works.
* When I click on the global cookie in the request view, I’m redirected to the cookie form.
* The commands “Add Cookie” and “Add …

feat(api-client): cookies 🍪

---

packages/scalar.aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarEndpointTests.cs

**Problem**
Currently, the Scalar.AspNetCore tests fail in main. I forgot to rebase before merging the recent PR.
**Solution**
With this PR it should pass again, because we added the recently introduced parameter to the also recently introduced tests.
**Checklist**

fix(Scalar.AspNetCore): add missing parameter to tests

---

tooling/base-docker-builder/Dockerfile

**Problem**
Currently, the base builder is failing because integrations are not being built. 
**Solution**
With this PR, integrations are built in the base builder so they are available in later build and deploy steps. This may significantly increase the base builder time and further selectivity could help reduce unneccessary build time.
**Checklist**

fix(tooling): build integrations in base builder
