.changeset/spotty-meals-report.md
packages/api-reference/src/components/Content/Introduction/Introduction.test.ts
packages/api-reference/src/components/Content/Introduction/Introduction.vue

Brings back the `.introduction-section` class which is used in a bunch of themes. Also adds a test so we (hopefully) don't accidentally delete the class again.

fix(api-reference):  add `.introduction-section` class to Introduction

---

.changeset/brave-boxes-jog.md
packages/api-client/src/components/Form/Form.vue
packages/api-client/src/views/Request/RequestSection/RequestBody.vue
packages/api-client/src/views/Request/RequestSection/RequestTable.vue

**Problem**
While using index as a key is often a bit no no, using the name caused a new one to be created every time you typed a letter.
**Solution**
We bring back the index key and remove the unshift, we will need to be careful of array modification
**Checklist**

fix(api-client): add back index to template loop

---

.changeset/clean-planets-fly.md
packages/api-client/src/components/DataTable/DataTableInputSelect.vue
packages/api-client/src/libs/send-request/create-fetch-query-params.test.ts
packages/api-client/src/libs/send-request/send-request.ts

**Problem**
currently we cannot send query parameter array value.
**Solution**
this pr is a first stepping stone to fix #4232  in order to support the query parameters array value for array typed using the following format `123,456
`. this will be then enhanced by more UI formatting + selector.
| <img width="850" alt="image" src="https://github.com/user-attachments/assets/1a8ab44c-984e-43c5-835e-a404d598f18c" /> | <img width="850" alt="image" src="https://github.com/user-attachments/assets/babd7075-c44a-435f-aa8d-1328ca7a99b4" /> |
| comma separated value is sent as it is | comma separated value is handle as an array | 
**Checklist**

feat(api-client): query parameters array support

---

.changeset/fluffy-insects-protect.md
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Enums/ScalarClient.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Enums/ScalarTarget.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarEndpointRouteBuilderExtensions.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/Mapper/ScalarOptionsMapper.cs
packages/scalar.aspnetcore/src/Scalar.AspNetCore/ScalarConfiguration.cs
packages/scalar.aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarOptionsMapperTests.cs

Closes #4549
It looks like we added support for some more targets and clients, I added them to `ScalarTarget` and `ScalarClient` enums. I also updated the JSON serializer options to return `true` if `HiddenClients` is true.
**Checklist**

fix(Scalar.AspNetCore): HiddenClients configuration behavior

---

.changeset/smart-rice-breathe.md
.changeset/three-nails-remember.md
documentation/configuration.md
packages/api-client/src/libs/send-request/create-request-operation.test.ts
packages/api-client/src/views/Request/Request.vue
packages/api-client/src/views/Request/hooks/useOpenApiWatcher.ts
packages/api-client/src/views/Request/libs/watch-mode.test.ts
packages/api-client/src/views/Request/libs/watch-mode.ts
packages/api-reference/src/features/ApiClientModal/ApiClientModal.vue
packages/oas-utils/src/entities/spec/collection.ts
packages/oas-utils/src/entities/spec/server.test.ts
packages/oas-utils/src/entities/spec/server.ts
packages/oas-utils/src/transforms/import-spec.test.ts
packages/oas-utils/src/transforms/import-spec.ts
packages/oas-utils/vite.config.ts
packages/types/src/legacy/reference-config.ts

WIP
Need to fix tests
**Problem**
The server logic in the reference covered some edge cases that we didn't cover in the client.
**Solution**
This PR:
* moves the server logic to a separate function
* add tests
* covers some more edge cases
* adds baseServerURL to the documentation
* improves the Zod schema for the servers
* closer to the specification
* removes `'default'` as the default value for variables
* if `enum` is defined: enforces `default` is a possible value
* if a single server is invalid, it's omitted, but the others servers are still there
* the data is validated against the schema first *and then* modified, this makes it more robust
* updated the comments
**Checklist**

feat(api-client): better server handling

---

.changeset/chilly-rivers-march.md
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/views/Request/RequestSection/RequestTable.vue
packages/oas-utils/src/entities/spec/request-example.test.ts
packages/oas-utils/src/entities/spec/request-examples.ts

**Problem**
setting examples in parameters is not currently retrieved in the client and displays only the first example value.
**Solution**
this pr fixes #4188 by displaying parameters examples in the client as a dropdown.
| <img width="729" alt="image" src="https://github.com/user-attachments/assets/d1cabc74-1023-42e8-bf60-48aee2779e61" /> | <img width="729" alt="image" src="https://github.com/user-attachments/assets/5f032269-b6cc-4ba9-a6d3-ee183cf82ff1" /> |
**Checklist**

feat(api-client): parameter examples support

---

.changeset/metal-phones-burn.md
packages/components/src/components/ScalarListbox/ScalarListbox.vue
packages/components/src/components/ScalarListbox/ScalarListboxItem.vue

**Problem**
current margin usage in listbox is causing gap inconsistency on single list item.
**Solution**
this pr removes margin and uses gap instead.
| <img width="331" alt="image" src="https://github.com/user-attachments/assets/92c3ec44-9857-4828-8720-4ae0d2fb0ffb" /> | <img width="331" alt="image" src="https://github.com/user-attachments/assets/231c1a0c-7964-49d5-b003-509e499f2434" /> |
| higher top and down spaces | consistent surrounding space | 
**Checklist**

fix(components): listbox margin

---

packages/components/.storybook/main.ts

Turns out the order of this array affects the order in which Storybook selects the first page. This updates it so the docs will be the first page loaded.
**Checklist**

docs(components): make introduction the first page of storybook

---

.changeset/silent-dots-knock.md
.changeset/sweet-walls-brush.md
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/components/DataTable/DataTableInputSelect.vue
packages/api-client/src/views/Request/RequestSection/RequestTableTooltip.vue
packages/components/src/components/ScalarButton/variants.ts

**Problem**
currently user cannot select multiple value in the request example dropdown selector for array.
**Solution**
this pr adds multiselect support to request example array as seen below:
https://github.com/user-attachments/assets/482ea9ef-8012-44d8-a8a1-8757aa69cd6d
**Checklist**

feat(api-client): request example array multiselect

---

.changeset/fuzzy-bottles-smell.md
examples/nextjs-api-reference/app/header/layout.tsx
examples/nextjs-api-reference/app/header/style.css
packages/api-reference/src/components/Content/Lazy/Loading.vue
packages/api-reference/src/components/Content/Tag/TagList.vue

**Problem**
On bigger specs when we load the first operation of a tag, sometimes there is a jump and it scrolls to the wrong element.
**Solution**
We do NOT lazy load any tags until the open one, this should eliminate the jump!
**Checklist**

fix(api-reference): inconsistent scroll position on page load when navigating to

---

.changeset/empty-sheep-relate.md
packages/api-client/src/components/Server/types.ts

Types are broken in main, let’s fix this swiftly.

fix(api-client): type mismatch for the server variable

---

.changeset/witty-bats-double.md
packages/api-client/src/components/AddressBar/AddressBar.vue
packages/api-client/src/components/AddressBar/AddressBarServer.vue
packages/api-client/src/components/CodeInput/CodeInput.vue

**Problem**
recent updates from #4532 broke the address bar ui in the reference + doesn't allow scroll on long server content.
**Solution**
this pr fixes the ui on reference + enables scroll on long server content.
| <img width="781" alt="image" src="https://github.com/user-attachments/assets/c2d103af-047d-4348-a0cd-a372f1b5e891" /> | <img width="781" alt="image" src="https://github.com/user-attachments/assets/e3425185-359b-4573-bf36-604309f47026" /> |
**Checklist**

fix(api-client): address bar UI

---

packages/api-reference/src/components/ApiReferenceLayout.test.ts

**Problem**
Currently, we only test a basic example and the GitHub REST API definition in an SSR environment. This is already good, but maybe not broad enough.
**Solution**
With this PR we’re testing a bunch of real-world examples.
**Preview**
**Checklist**

test(api-reference): testing SSR for a bunch of real-world examples

---

.changeset/green-laws-tease.md
.changeset/young-cooks-draw.md
packages/api-client/src/components/Sidebar/SidebarListElement.vue
packages/api-client/src/views/Cookies/Cookies.vue
packages/api-client/src/views/Environment/Environment.vue
packages/api-client/src/views/Servers/Servers.vue
packages/themes/src/reset.css

**Problem**
currently api client sidebar are using wrong markup + outline focus is off.
**Solution**
this pr is a proposal to reset outline by offsetting it by default + update markups.
| <img width="440" alt="image" src="https://github.com/user-attachments/assets/aaf422c8-a9d5-4880-9110-293d21a1a8e0" /> | <img width="440" alt="image" src="https://github.com/user-attachments/assets/36e3347f-399a-4a0a-b780-d683b6edda65" /> |
| top outline focus is cropped | top outline is now fully visible | 
**Checklist**

fix(api-client): sidebar outline + markup

---

.changeset/chatty-garlics-deny.md
packages/api-client/src/components/AddressBar/AddressBar.vue
packages/api-client/src/components/AddressBar/AddressBarServer.vue
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/components/CodeInput/codeVariableWidget.ts
packages/api-client/src/components/EnvironmentSelector/EnvironmentSelector.vue
packages/api-client/src/components/Sidebar/Sidebar.vue
packages/api-client/src/libs/create-client.ts
packages/api-client/src/store/store.ts
packages/api-client/src/views/Request/Request.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuth.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuthDataTable.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestExampleAuth.vue
packages/api-client/src/views/Request/RequestSection/RequestSection.vue
packages/api-client/src/views/Request/RequestSidebar.vue
packages/api-client/src/views/Request/RequestSidebarItem.vue
packages/api-client/src/views/Request/RequestSubpageHeader.test.ts
packages/api-client/src/views/Request/RequestSubpageHeader.vue
packages/api-client/src/views/Request/ResponseSection/ResponseEmpty.vue
packages/api-client/src/views/Request/handle-drag.ts
packages/api-reference/src/components/ApiReferenceLayout.vue

**Problem**
we currently have two way to distinguish reference and client usages.
**Solution**
this pr favors the usage of the layout hook over the previously used isReadOnly. To be thoroughly tested to make sure no previously set behavior are now possible in client/reference and vice versa.
**Checklist**

feat(api-client): favors layout hook over isReadOnly

---

.changeset/grumpy-rice-run.md
packages/scalar-app/src/main/index.ts

**Problem**
currently clicking on `Check for Updates...` button in update presence restart and install automatically without notice.
**Solution**
this pr is a proposal to update the updater modal content and actions by introducing the following actions:
`update available`
- restart and install | later
`no update available`
- ok | reload all tabs | submit a ticket
| update available | no update available |
| <img width="824" alt="image" src="https://github.com/user-attachments/assets/b1f1bfa3-d7aa-4ddb-9dc0-9b00765b077d" /> | <img width="824" alt="image" src="https://github.com/user-attachments/assets/da0c4880-1032-489a-8a28-38d5643b21b6" />
**Checklist**

feat(scalar-app): desktop updater modal

---

.changeset/orange-dogs-lick.md
packages/api-client/src/libs/create-client.ts
packages/api-client/src/libs/importers/curl.ts
packages/oas-utils/src/entities/spec/request-examples.ts

**Problem**
currently `application/json` is set by default on request example creation which can cause error in some use case as seen in #4542 
**Solution**
this pr removes the default content type.
**Checklist**

fix(api-client): request body default

---

.changeset/pretty-flies-beam.md
packages/api-client/src/libs/create-client.ts
packages/api-reference/src/features/Operation/layouts/ClassicLayout.vue
packages/api-reference/src/features/Operation/layouts/ModernLayout.vue
packages/api-reference/src/features/TestRequestButton/TestRequestButton.test.ts
packages/api-reference/src/features/TestRequestButton/TestRequestButton.vue
packages/play-button/src/index.ts

Currently, we pass the (legacy) `TransformedOperation` to the `TestRequestButton`, pass the method and the path to the API client, and then resolve the request entity from the store.
With this PR, we’re just passing the RequestEntity to the button, and then only pass the request UID to the client.
Way easier, and also another component where we can get rid of the (legacy) `TransformedOperation`.

refactor(api-reference): use the store in `TestRequestButton`

---

.changeset/real-seahorses-film.md
packages/api-client/src/components/ViewLayout/ViewLayoutCollapse.vue
packages/api-client/src/layouts/Modal/create-api-client-modal.ts
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuth.vue

**Solution**
- fixed the top border on ref auth
- removed ability to collapse ref auth
- started client in ref with sidebar closed
**Checklist**

fix(api-reference): a few minor layout tweaks

---

.changeset/big-tomatoes-invite.md
packages/api-client/src/store/import-spec.ts
packages/oas-utils/src/transforms/import-spec.ts

**Problem**
Currently, when importing a spec file, the collection is created, but no requests are shown
**Solution**
With this PR, I'm fixing the way requests are added to the children of the collection. In the example spec, `tags` was an empty list, so `if (r.tags)` evaluated to `true`, added an extra step to check list length.
solves #4596 (see this issue for example spec file)
**Checklist**
---
Which references should be added as children? Is it fine that only requests are added to the children property? Should others also be added (like examples)?
I'm also not sure if this is the correct place to add the requests to the children, or if this …

fix(api-client): No request imported while collection successfully created

---

.changeset/sweet-donuts-reply.md
integrations/aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarEndpointRouteBuilderExtensions.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Options/ScalarOptions.cs
integrations/aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarEndpointTests.cs

**Problem**
With version 2.0.0 we removed the option to set the document name in the HTML title due to the support of the multiple OpenAPI documents. However, if only one document was added to the configuration (which is currently the case because we postponed the multi docs support) we could technically show the document name again.
**Solution**
This PR brings back the support for showing the OpenAPI document name in the title. 
```c#
app.MapScalarApiReference(options =>
{
options.Title = "Scalar API Reference | {documentName}";
});
```
results in `Scalar API Reference | v1`.
**Checklist**

feat(Scalar.AspNetCore): add placeholder support for the title

---

.changeset/quiet-pianos-move.md
packages/api-client/src/views/Settings/SettingsGeneral.vue
packages/api-client/src/views/Settings/components/SettingsAppearance.vue

**Problem**
some api client settings ui code seems duplicated giving funky borders.
**Solution**
this pr removes duplication and sets variant and color properly.
| <img width="839" alt="image" src="https://github.com/user-attachments/assets/8fdf88b7-8b74-4ccb-9f19-5836d3df0afe" /> | <img width="839" alt="image" src="https://github.com/user-attachments/assets/8e66f1c8-432c-4108-86fa-679ff5bc94ca" /> |
| inactive checkbox border is off  | active checkbox use primary bg and border are fixed | 
**Checklist**

fix(api-client): settings UI

---

.changeset/soft-phones-cheat.md
.changeset/strange-squids-argue.md
packages/api-client/src/components/DataTable/DataTableInputSelect.vue
packages/api-client/src/components/EnvironmentSelector/EnvironmentSelector.vue
packages/api-client/src/components/ImportCollection/WorkspaceSelector.vue
packages/components/src/components/ScalarListbox/ScalarListboxCheckbox.vue

**Problem**
currently inactive checkbox are not displaying any border which can create visual misalignment with content.
**Solution**
this pr sets border on inactive checkbox within the api client and fixes checkmark icon inconsistencies.
| <img width="839" alt="image" src="https://github.com/user-attachments/assets/3b76b4d8-d627-4ff8-bf4e-3f71bab8bc2c" /> | <img width="839" alt="image" src="https://github.com/user-attachments/assets/b8f91f26-9e9d-440d-b14c-ad56a0cb052e" /> |
**Checklist**

fix(api-client): checkbox ui

---

.changeset/smart-bears-breathe.md
packages/themes/src/variables.css

**Problem**
recent changes to box shadow in darkmode mistakenly set it as inset which breaks the ui.
**Solution**
this pr removes the inset from the box shadow variable.
| <img width="839" alt="image" src="https://github.com/user-attachments/assets/9b488aac-2bf3-4cc7-840e-8c761ae2842c" /> | <img width="839" alt="image" src="https://github.com/user-attachments/assets/8665b25a-ba9d-4a0c-9cb6-0063655922f2" /> |
| missing top border | whole border back | 
**Checklist**

fix(themes): box shadow variable

---

.changeset/fair-beds-film.md
packages/api-client/src/layouts/Modal/ApiClientModal.vue

Turns out this needs to be a scoped style instead of a tailwind class because all the tailwind classes are scoped to `.scalar-client`.
**Checklist**

fix(api-client): set modal z-index via scoped style

---

.changeset/thick-poets-design.md
packages/api-client/src/libs/send-request/create-fetch-auth.test.ts
packages/api-client/src/libs/send-request/send-request.ts
packages/api-client/src/store/active-entities.ts
packages/api-client/src/store/security-schemes.ts
packages/api-client/src/views/Request/RequestSection/RequestAuth/DeleteRequestAuthModal.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/OAuth2.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuth.test.ts
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuth.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuthDataTable.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuthTab.vue
packages/api-client/src/views/Request/RequestSection/RequestSection.vue
packages/api-client/src/views/Request/libs/auth.test.ts
packages/api-client/src/views/Request/libs/auth.ts
packages/api-reference/src/components/Content/Content.vue
packages/api-reference/src/features/Operation/hooks/useRequestExample.ts
packages/oas-utils/src/entities/shared/index.ts
packages/oas-utils/src/entities/shared/utility.ts
packages/oas-utils/src/entities/spec/collection.ts
packages/oas-utils/src/entities/spec/requests.ts
packages/oas-utils/src/transforms/import-spec.test.ts
packages/oas-utils/src/transforms/import-spec.ts

Complex security, this was done a few times but kept breaking whenever we refactored or changed something. Have now added tests to ensure this does not happen again!
fixes #3359
currently needs
Originally I did it the easy way with much less changes, but it was not quite correct. So I switched from comma separated to using a proper array! Also switched to prop drilling so we can add integration tests :). Now the integration tests are still a little basic as we have a lot of reliance on `useActiveEntities` but I will keep drilling 
**Problem**
Complex auth was broken
**Solution**
We add back in complex auth
**To test**
load up the client and import this spec to test
`https://gist.githubusercontent.com/amritk/f64887015e998bf81ff349d3ace64cd5/raw/4499a362e1f274ef7f2f61e7f572c34dfa67e4db/test. …

fix(api-reference): complex security requirements

---

.changeset/happy-seahorses-warn.md
packages/oas-utils/src/transforms/import-spec.test.ts
packages/oas-utils/src/transforms/import-spec.ts

**Problem**
It was incorrectly selecting security scheme uids when there was no security requirements on the collection
**Solution**
We add a test and only select security requirements from the collection
**To Test**
You can use this spec
https://socksproxyapi.darrenmc.dev/docs/openapi.json
**Checklist**

fix(api-reference): setting initial security when there are no requirements

---

.changeset/fresh-shoes-push.md
.changeset/lazy-beans-sparkle.md
packages/api-client/src/views/Request/RequestSection/RequestBody.vue
packages/oas-utils/package.json
packages/oas-utils/src/entities/spec/request-examples.ts
packages/oas-utils/src/migrations/README.md
packages/oas-utils/src/migrations/data-version.ts
packages/oas-utils/src/migrations/migrator.ts
packages/oas-utils/src/migrations/v-2.4.0/types.generated.ts
packages/oas-utils/src/migrations/v-2.5.0/index.ts
packages/oas-utils/src/migrations/v-2.5.0/migration.test.ts
packages/oas-utils/src/migrations/v-2.5.0/migration.ts
packages/oas-utils/src/migrations/v-2.5.0/types.generated.ts

**Problem**
currently we do not pre-fill the header with default ones as highlighted in #4534 
**Solution**
this pr adds `Accept` header by default and fixes #4534. we might want to adds other ones:
- Accep-Encoding
- User-Agent (in desktop app usage)
- Connection
| <img width="632" alt="image" src="https://github.com/user-attachments/assets/6557a819-5a70-45dd-aa6d-026ee1b59ba7" /> | <img width="632" alt="image" src="https://github.com/user-attachments/assets/69998143-2ce3-4e21-99fe-6cf23e3e6502" /> |
| content type header only | accept header prefilled | 
**Checklist**

feat(api-client): accept header

---

.changeset/nervous-rules-grin.md
packages/api-reference/src/components/Content/Content.vue

**Problem**
We show an optional auth when there's no auth defined in the schema
**Solution**
We hide the auth section
before: 
after:
**Checklist**

fix(api-reference): hide auth section in references when there's no securitySchemes

---

integrations/aspnetcore/src/Scalar.AspNetCore/Mapper/ScalarOptionsMapper.cs
integrations/aspnetcore/src/Scalar.AspNetCore/ScalarConfiguration.cs
integrations/aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarOptionsMapperTests.cs

**Problem**
I noticed that the `Proxy` property is marked as deprecated.
**Solution**
I renamed it to `ProxyUrl`.
**Checklist**

fix(Scalar.AspNetCore): rename Proxy property to ProxyUrl

---

integrations/aspnetcore/playground/Scalar.AspNetCore.Playground/Dockerfile
integrations/aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarEndpointRouteBuilderExtensions.cs

**Problem**
The Dockerfile was not working as expected. It publishes the app as AOT, but this takes time and is not working in docker.
**Solution**
I disabled AOT publishing for Docker. We don't need this anyway, it's just enabled for the analyzers. 
I also updated one comment in the code.
**Checklist**

fix(Scalar.AspNetCore): update playground Dockerfile

---

examples/proxy-server/cloudbuild.yaml

**Problem**
Request latency in Europe and Asia for proxy requests is fairly substantial (often reaching highs of 500-750ms+), compared to users in US regions.
**Solution**
After introducing multi-region deployments for the proxy, we can add an extra regional NEG which the external load balancer will point to. This should significantly decrease proxy latency in our most popular regions.
(Note that we are using beta cli here as this is a shortcut for having to define multiple separate deployment steps for each region, because Google).
**Checklist**

chore(tooling): setup proxy multi-region deployment

---

.changeset/lazy-boxes-bake.md
packages/api-client/src/views/Request/RequestSection/RequestSection.vue

**Solution**
this PR is following up with #4667 in order to only display auth in security schemes presence in reference client modal also.
| <img width="725" alt="image" src="https://github.com/user-attachments/assets/bed03f48-1dd0-4697-b54d-1e48bdfd5530" /> | <img width="725" alt="image" src="https://github.com/user-attachments/assets/c1d7891b-ae84-4295-b0b7-466eb8c9cb9e" /> |
| auth section displayed without security presence | hidden auth section in no security presence | 
**Checklist**

fix(api-client): request auth modal

---

.changeset/fuzzy-teachers-push.md
packages/api-reference/src/components/Content/Schema/helpers/formatExample.test.ts
packages/api-reference/src/components/Content/Schema/helpers/formatExample.ts

**Problem**
currently number parameter example are being displayed as string in the reference and fixed #4678.
**Solution**
this PR updates the type formatting to maintain de type displayed.
| <img width="580" alt="image" src="https://github.com/user-attachments/assets/24c13422-2334-467b-9f06-d730c2e92ff6" /> | <img width="580" alt="image" src="https://github.com/user-attachments/assets/15412885-000f-4a8f-a09d-6947183148a0" /> |
| example value as string | example value as number | 
**Checklist**

fix(api-reference): example format

---

.changeset/tasty-onions-yell.md
packages/api-reference/src/components/Content/Introduction/Description.test.ts
packages/api-reference/src/components/Content/Introduction/Description.vue

**Problem**
The hash prefix was missing and not working on ORG
**Solution**
We ensure the hash prefix is added to the heading IDs
**Checklist**

fix(api-reference): add hash prefix to heading IDs

---

.github/workflows/test-cdn-jsdelivr.yml

**Problem**
Currently, the automated PRs created to update the CDN api reference test snapshots are not notifying the correct people. 
**Solution**
With this PR, review is requested from relevant members of the team.
**Checklist**

chore: add reviewers to snapshot update pr

---

.changeset/gold-buses-cheer.md
.changeset/tall-brooms-change.md
packages/snippetz/playground/src/App.vue
packages/snippetz/playground/src/components/CodeExample.vue
packages/snippetz/playground/src/style.css
packages/snippetz/src/snippetz.ts

**Problem**
playground snippetz usage is throwing an error. 
```console
Cannot read properties of undefined (reading 'findPlugin')
```
**Solution**
this pr returns object in the snippetz function + updates playground style.
| <img width="888" alt="image" src="https://github.com/user-attachments/assets/a0a45ce5-db95-48d7-87aa-d81b9b962c84" /> | <img width="888" alt="image" src="https://github.com/user-attachments/assets/23668e10-d018-497a-a0f9-69a7ecb36180" /> |
| example and input in one code block | display example and output distinctly | 
**Checklist**

fix(snippetz): `findPlugin` undefined

---

.changeset/tidy-zebras-poke.md
packages/api-reference/src/components/Content/Schema/Schema.vue
packages/api-reference/src/components/Content/Schema/SchemaProperty.test.ts
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.test.ts
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue
packages/openapi-types/src/openapi-types.ts

**Problem**
Currently, Scalar's `api-reference` does not show a model's properties defined in [`patternProperties`](https://json-schema.org/understanding-json-schema/reference/object#patternProperties) at all (just like many other tools like Swagger's UI to my knowledge), making it hard to see that they exist *should they exist*.
**Solution**
With this PR I implemented rudimentary rendering for these properties.
**Checklist**
**Preview**
A model with an exemplary schema as follows:
```json5
{
"foo": { "type": "integer" },
"bar": { "type": "string" }
},
"additionalProperties": { "type": "string" },
"patternProperties": {
"^foo-\\d+": {
"bar": { "type": "boolean" }
}
},
"^bar-\\w+": { …
```

feat(api-reference): implement rendering of `patternProperties`

---

examples/proxy-server/cloudbuild.yaml

**Problem**
Client proxy is now deployed cross-regionally, with a great improvement in response metrics (this is the pattern we will follow going forward for other services).
Now we just need some slight extra control over instance sizes and numbers.
**Solution**
Just adding two extra flags to increase the number of concurrent requests each proxy instance can handle, and the minimum number of instances - we will be updating both as needed based on metrics.
**Checklist**

chore(tooling): fine grained proxy deployment

---

.changeset/mean-experts-count.md
packages/components/src/components/ScalarMenu/ScalarMenu.vue

Because this doesn't use `ScalarFloating` we need to set a `z-index`
**Checklist**

fix(components): set z-index on ScalarMenu by default

---

.changeset/sweet-sloths-boil.md
packages/api-client/src/components/Sidebar/SidebarListElement.vue
packages/api-client/src/views/Request/RequestSidebarItem.vue
packages/api-reference/src/components/Sidebar/SidebarElement.vue
packages/components/src/components/ScalarSidebar/ScalarSidebar.stories.ts
packages/components/src/components/ScalarSidebar/ScalarSidebarButton.vue
packages/components/src/components/ScalarSidebar/ScalarSidebarGroup.test.ts
packages/components/src/components/ScalarSidebar/ScalarSidebarGroup.vue
packages/components/src/components/ScalarSidebar/ScalarSidebarGroupToggle.vue
packages/components/src/components/ScalarSidebar/ScalarSidebarItem.vue
packages/components/src/components/ScalarSidebar/ScalarSidebarItems.vue
packages/components/src/components/ScalarSidebar/index.ts
packages/components/src/components/ScalarSidebar/types.ts
packages/components/src/components/ScalarSidebar/useSidebarGroups.test.ts
packages/components/src/components/ScalarSidebar/useSidebarGroups.ts

This creates a sidebar item component for use everywhere and align the sidebar group toggles in the API Client and references. There's more work to do on fully aligning how the sidebars work and look but I wanted to sync with Cam first because it will noticeably change how the references sidebar looks.
Also adds a (little) animation for the chevron but we can remove that if we prefer.
(Also check out the storybook preview)
https://github.com/user-attachments/assets/f2cdab79-6218-4201-8680-83e972a6061f
**Checklist**

feat(components): create sidebar item components

---

.changeset/lucky-papayas-look.md
packages/api-client/src/views/Request/RequestSection/RequestBody.vue

**Problem**
currently when using a custom content type it is not retrieved at the client modal level and also override the example once back to the reference.
**Solution**
this pr sets the request content-type if present and fixes #4562.
| <img width="765" alt="image" src="https://github.com/user-attachments/assets/8f5b2947-9956-4939-b287-2926f8f7f3d6" /> | <img width="765" alt="image" src="https://github.com/user-attachments/assets/2c2db24b-771a-44c6-8602-1e31a17b9e5b" /> |
| content-type is using json | content-type is using custom | 
**Checklist**

fix(api-client): content-type request 

---

.changeset/weak-boxes-film.md
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/views/Request/RequestSection/RequestParams.vue
packages/api-client/src/views/Request/RequestSection/RequestTable.vue

**Solution**
this pr fixes global cookies ui as caught by @hanspagel and highlight their readonly state.
| <img width="632" alt="image" src="https://github.com/user-attachments/assets/f600b413-0a5e-40d3-a1ff-54ab222a743f" /> | <img width="632" alt="image" src="https://github.com/user-attachments/assets/29860f48-0401-48eb-ad8e-79141957a7db" /> |
| inconsistent padding | consistent padding + readonly style | 
**Checklist**

fix(api-client): read-only cookies visualisation

---

.changeset/poor-peaches-exist.md
packages/oas-utils/src/entities/spec/index.ts
packages/oas-utils/src/entities/spec/operation.ts
packages/oas-utils/src/entities/spec/requests.ts

**Problem**
request was constantly bumping into the global request class causing typescript errors, also auto import didn't work. 
**Solution**
We alias request with operation which brings it more in line with our codebase + openapi spec.
**Checklist**

feat(oas-utils): alias request with operation

---

package.json
pnpm-lock.yaml

Extracted from #4537: Removed concurrently.
I don't think we use ts-node either. Might be wrong, though. But if CI passes, it’s good.
Doesn’t need a changeset, doesn’t alter code, nor the dependencies of a published package.

chore: remove concurrently and ts-node

---

tooling/base-docker-builder/Dockerfile

**Problem**
Currently, the base-builder Docker file is failing to build. 
**Solution**
With this PR, the tsconfig.node.json is copied into the Dockerfile because it is needed by @scalar/types and others. 
**Checklist**

chore(tooling): copy node tsconfig base file in base builder dockerfile

---

.changeset/wild-poets-check.md
packages/api-client/src/components/SideNav/SideNavLink.vue

**Problem**
currently in light mode the topbar active pages are not highlighted as they should.
**Solution**
this pr updates the sidenav topbar style to get active page highlighted.
| <img width="378" alt="image" src="https://github.com/user-attachments/assets/4211ba38-50cf-4447-8b07-cfef3d174b89" /> | <img width="378" alt="image" src="https://github.com/user-attachments/assets/706adbf9-4a63-4629-ba2f-c3add07fe477" /> |
| active page not highlighted | active page highlighted | 
**Checklist**

fix(api-client): topbar active page

---

.changeset/rare-news-begin.md
packages/api-client/src/store/collections.test.ts
packages/api-client/src/store/collections.ts

**Problem**
currently on collection deletion, servers are not removed from the workspace.
**Solution**
this pr removes servers used in a collection on collection removal.
**Checklist**

fix(api-client): collection deletion servers

---

.changeset/odd-ducks-smoke.md
packages/api-client/src/components/Search/useSearch.test.ts
packages/api-client/src/components/Search/useSearch.ts

**Problem**
currently the search is not returning any results.
**Solution**
this pr updates the filtering in order to return requests.
| <img width="285" alt="image" src="https://github.com/user-attachments/assets/9333563c-74a6-40a7-ba9b-bd580c316238" /> | <img width="285" alt="image" src="https://github.com/user-attachments/assets/22c3bbbd-4cdf-4f82-8ffd-c5d98c2888cc" /> |
| no results | results back in | 
**Checklist**

fix(api-client): sidebar search request

---

.changeset/afraid-bags-dance.md
packages/api-client/src/views/Request/libs/oauth2.test.ts
packages/api-client/src/views/Request/libs/oauth2.ts

**Problem**
Currently we send the scopes in the initial login as well as the authorization calls for auth code
**Solution**
Turns out it was breaking some security by sending the scopes a second time, this removes that bit.
Closes #4287
**Checklist**

fix(api-client): remove scopes from authCode auth call

---

.changeset/few-maps-serve.md
packages/oas-utils/src/transforms/import-spec.test.ts
packages/oas-utils/src/transforms/import-spec.ts

**Problem**
We aren't storing security requirements on an operation
**Solution**
We fix that and add a test
Fixes #4017
**Checklist**

fix(api-client): parse security requirements per operation correctly

---

.changeset/mighty-eyes-talk.md
packages/api-client/src/libs/send-request/build-request-security.ts
packages/api-client/src/libs/send-request/create-fetch-auth.test.ts
packages/api-client/src/libs/send-request/create-request-operation.ts

**Problem**
Currently if we have both an auth header and a regular header with the same key 'Authorization' we stack them up into an array.
**Solution**
With this PR the headers overrides the auth and there is no more array.
fixes #4131
**Checklist**

fix(api-client): give headers priority over auth

---

.changeset/funny-meals-smash.md
documentation/configuration.md
packages/oas-utils/src/transforms/import-spec.test.ts
packages/oas-utils/src/transforms/import-spec.ts
packages/types/src/legacy/reference-config.ts

**Problem**
We can only pre-select a single auth type
**Solution**
With this PR we can pre-select both multiple auth, and complex auth as an added bonus
closes #3890
**Checklist**

feat(api-reference): allow pre-selecting multiple and complex auth

---

.changeset/hungry-hornets-fix.md
packages/api-client/src/views/Settings/components/SettingsAppearance.vue

**Problem**
currently the appearance setting button are missing hover state background.
**Solution**
this pr adds the missing hover state background on appearance button hover.
| <img width="727" alt="image" src="https://github.com/user-attachments/assets/fa614267-39ca-4299-bffa-86f9faf2c86f" /> | <img width="727" alt="image" src="https://github.com/user-attachments/assets/4ef5efcb-9b1f-4077-af5a-b191ed2ff100" /> |
| missing background on hover | background on hover | 
**Checklist**

fix(api-client): appearance settings button hover

---

packages/oas-utils/src/transforms/import-spec.ts

Found this console.log, which produces a lot of noise.
Let’s remove this.
Doesn’t need a changeset, will be just part of the next release.

chore(oas-utils): remove console.log

---

.changeset/hot-dolls-cover.md
packages/api-client/src/views/Environment/Environment.vue
packages/api-client/src/views/Servers/Servers.vue

**Problem**
With #4716 I broke the routing on the servers and environment pages. We’ve used `:collectionId` before, but I refactored the code to use `PathId.Collection` (which is `collection` not `collectionId`), so we’ve had to update more places then I did in the initial PR.
**Solution**
With this PR you can click on environments and servers and see the content change again.
**Checklist**

fix(api-client): routing broken on environment and servers page

---

.changeset/tidy-jobs-hunt.md
packages/galaxy/src/documents/3.1.yaml

**Problem**
I’m working on the code examples and the example responses and wanted to test multiple mime types. But you know what? The Scalar Galaxy example has JSON only!
**Solution**
With this PR we’re adding XML to the Scalar Galaxy example.
I’ve also asked the [OpenAPI doctor](https://pb33f.io/doctor/) to give feedback and addressed most points (e.g. missing descriptions).
**Checklist**

feat(galaxy): XML support

---

.changeset/clever-books-carry.md
.changeset/healthy-steaks-compare.md
.changeset/thirty-wolves-try.md
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/oas-utils/src/entities/spec/request-example.test.ts
packages/oas-utils/src/entities/spec/request-examples.ts
packages/openapi-parser/src/utils/upgradeFromThreeToThreeOne.test.ts
packages/openapi-parser/src/utils/upgradeFromThreeToThreeOne.ts

**Problem**
Currently, you receive a warning when importing an OpenAPI document containing `type: ['string', 'null']` or a Swagger 2.0, OpenAPI 3.0 document containing `nullable: true` (which will be transformed to the array syntax during upgrade), that’s the case for the [GitHub RestAPI OpenAPI document](https://raw.githubusercontent.com/github/rest-api-description/refs/heads/main/descriptions/api.github.com/api.github.com.yaml) for example.
Fixes #3812
**Solution**
With this PR, we’re extending the schema to allow an array as the type, normalize it to use a single string and `nullable: true` instead, but still deal with other arrays if someone goes wild.
**Example**
```diff
{
"openapi": "3.0.0",
"info": {
},
"paths": {
"/": {
"get": { …
```

fix(api-reference): warnings for `type: ['string', 'null']`

---

.github/actions/build/action.yml

**Problem**
Currently, CI is failing claiming we use an old version of actions/cache.
**Solution**
With this PR all uses of actions/cache are pinned to the same hash.
If CI passes here, we can merge.
**Checklist**

ci: reset github actions cache commit hash

---

tooling/base-docker-builder/Dockerfile

We forgot to copy the new tsconfig.

fix: `tsconfig.strict.json` missing in Docker

---

.changeset/tough-mice-cover.md
documentation/configuration.md
packages/api-reference/playground/esm/index.html
packages/api-reference/playground/esm/vite.config.ts
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/Content/Introduction/Introduction.vue
packages/api-reference/src/components/Content/Lazy/Loading.vue
packages/api-reference/src/hooks/useConfig.ts
packages/types/src/legacy/reference-config.ts

**Solution**
We add an onLoaded callback to the reference config. ~This gets triggered as soon as lazy loading occurs and the loading component is up.~ moved it to the intro so its a bit faster than lazy load but should still be pretty accurate.
For our friends at upload thing.
To test cd into `packages/api-reference` and run `pnpm playground:esm`
**Checklist**

feat(api-reference): add onLoaded event

---

.changeset/real-pots-shave.md
packages/api-reference/src/features/ExampleResponses/ExampleResponses.test.ts
packages/api-reference/src/features/ExampleResponses/ExampleResponses.vue
packages/api-reference/src/features/Operation/layouts/ClassicLayout.vue
packages/api-reference/src/features/Operation/layouts/ModernLayout.vue

Splitting #4281 in smaller PRs:
**Problem**
Currently, we still use the deprecated transformed operation to render the example responses.
**Solution**
With this PR, we’re using the store to render example responses and add tests! Isn’t that cool?
For the example responses in the card on the right side only.
**Checklist**

refactor(api-reference): render example responses from store

---

.changeset/breezy-tips-hide.md
packages/api-reference/src/features/ExampleRequest/ExampleRequest.vue

**Problem**
currently on `hideTestRequestButton` the example request still displays a footer which in some cases act as an extra padding [as seen on vercel](https://vercel.com/docs/rest-api/endpoints#tag/access-groups/create-an-access-group-project).
**Solution**
this pr updates the footer display logic to ensure that it gets used only in multiple example or test request button presence.
| <img width="538" alt="image" src="https://github.com/user-attachments/assets/3c8a2376-2698-4551-aaa3-67c1af4d7daf" /> | <img width="538" alt="image" src="https://github.com/user-attachments/assets/ef74fb90-e0ae-4b25-bf1b-64650f0c7371" /> |
| footer remains even without multiple examples | footer is not displayed | 
**Checklist**
See …

fix(api-reference): example request footer

---

.changeset/violet-chefs-poke.md
documentation/integrations/dotnet.md
integrations/aspnetcore/playground/Scalar.AspNetCore.Playground/Program.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarEndpointRouteBuilderExtensions.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Options/ScalarOptions.cs
integrations/aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarEndpointTests.cs
integrations/aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarOptionsTests.cs
integrations/aspnetcore/tests/apis/Scalar.AspNetCore.Tests.Api/Program.cs

**Problem**
Currently, OpenApiRoutePattern only allows relative paths
**Solution**
With this PR OpenApiRoutePattern also allows full URLs to external openapi documents
**Checklist**

feat(aspnetcore): allow full url for `OpenApiRoutePattern`

---

.changeset/lazy-clouds-look.md
packages/api-client/src/components/DataTable/DataTableInputSelect.vue

**Problem**
Currently, when you try to provide a custom value for a parameter that has examples, the value disappears as soon as you hit enter.
https://github.com/user-attachments/assets/49c49699-b289-4d68-902a-e5fa2426cf5c
I think I tracked it down to events being emitted too much and overwriting your custom value...
**Solution**
With this PR, I removed those (unneeded?) event emits and got 'working' behavior. Meaning, the custom value is not dissapearing. The value itself however is still not being added to the list of available entries. Unsure if that's desired behavior?
https://github.com/user-attachments/assets/4c699d8d-503d-4960-a285-750763d6bbae
**Checklist**
See the [contributing guide](https://github.com/scalar/scalar/blob/main/CONTRIBUTING.md) …

fix(api-client): custom parameter disappearing

---

.changeset/dirty-mails-stare.md
.changeset/silly-parents-itch.md
packages/api-client/src/components/Sidebar/Sidebar.vue
packages/api-client/src/views/Request/RequestSection/helpers/getting-started.test.ts
packages/api-client/src/views/Request/RequestSection/helpers/getting-started.ts
packages/api-client/src/views/Request/RequestSidebar.vue
packages/api-client/src/views/Request/RequestSidebarItem.vue

**Problem**
currently the getting started state is not optimally responsive + get displayed when a request exists out of a drafts collection.
**Solution**
this pr updates responsiveness + only extracts a function to only display the state when a single request from the draft collection is added.
| <img width="506" alt="image" src="https://github.com/user-attachments/assets/6bf40129-9d5e-4a8d-a39c-1cd200f57d4d" /> | <img width="506" alt="image" src="https://github.com/user-attachments/assets/e9f14f5b-b2dd-42dd-aec9-df203c8961bc" /> |
| state is overflowing the requests | requests height according to state presence + scroll |
**Checklist**

fix(api-client): getting started sidebar state

---

.changeset/witty-garlics-thank.md
packages/api-client/src/components/CodeInput/CodeInput.vue

**Problem**
currently address bar in modal is not using the right font style.
**Solution**
this pr updates code input style according to layout.
| <img width="538" alt="image" src="https://github.com/user-attachments/assets/a8c344f9-ace6-40b5-b4d9-5ee18cdef886" /> | <img width="538" alt="image" src="https://github.com/user-attachments/assets/dcce4111-b659-482e-a810-6352de706a6d" /> |
| font family and size is off | consistent font family and size | 
**Checklist**

fix(api-client): modal address bar

---

.changeset/ninety-moose-switch.md
integrations/express/package.json
integrations/express/src/apiReference.test.ts
integrations/express/src/apiReference.ts
integrations/express/src/lib/static-rendering.ts
integrations/express/src/types.ts
integrations/express/tsconfig.json
integrations/express/vite.config.ts

**Problem**
Currently, we’re rendering embedded content twice in the Express integration. First as part of the configuration object and then as the content of the script tag.
This makes the server response roughly twice as big as needed.
**Solution**
With this PR we’re rendering it only once! I’ve used the opportunity to extract a few of the functions into a lib.
As a next step, I’d like to move the lib to a global place and use the same lib in all JS-based integrations. 👀  
**Checklist**

feat(express-api-reference): render the content only once

---

.changeset/tender-ducks-hang.md
packages/import/src/get-configuration-attribute.test.ts
packages/import/src/get-content-of-script-tag.test.ts
packages/import/src/resolve.test.ts
packages/import/src/resolve.ts

**Problem**
Currently, the import breaks with HTML attributes that contain HTML tags (e.g. in the description of the OpenAPI document).
**Solution**
With this PR we’re doing a better job parsing HTML attributes and `<script>` tag contents.
And if something fails, we also try to sanitize the JSON to make it parse. That’s pretty specific for a case I’ve found, we might be able to remove this eventually again, but for now it helps.
**Checklist**

fix(import): can’t parse HTML attributes with HTML tags inside

---

.changeset/angry-rocks-rescue.md
packages/api-client/src/libs/send-request/create-request-operation.test.ts
packages/api-client/src/libs/send-request/create-request-operation.ts

**Problem**
If you have a lowercase only auth header it will get deleted
**Solution**
Instead of adding and deleting we just lowercase them.
fixes #4763
**Checklist**

fix(api-client): ensure we preserve lowercase authentication headers

---

packages/openapi-parser/src/utils/load/load.test.ts

**Problem**
Currently, we have some unnecessary comments in the openapi parser testing.
**Solution**
With this PR we can remove @hanspagel 's filesystem from the test comments 😄 
**Checklist**

chore(openapi-parser): remove comments

---

integrations/aspnetcore/playground/Scalar.AspNetCore.Playground/Scalar.AspNetCore.Playground.csproj
integrations/aspnetcore/src/Scalar.AspNetCore/Mapper/ScalarOptionsMapper.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Scalar.AspNetCore.csproj
integrations/aspnetcore/tests/Scalar.AspNetCore.Tests/Scalar.AspNetCore.Tests.csproj
integrations/aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarOptionsMapperTests.cs
integrations/aspnetcore/tests/apis/Scalar.AspNetCore.Tests.Api/Scalar.AspNetCore.Tests.Api.csproj

This PR updates some dependencies to the latest version. The `NetEscapades.EnumGenerators` package has a breaking change which I fixed. I also improved the tests to test the behavior of the `NetEscapades.EnumGenerators` generator.
**Checklist**

chore(Scalar.AspNetCore): update packages and test improvements

---

.changeset/sixty-berries-sin.md
packages/api-client/src/components/DataTable/DataTableInputSelect.vue

**Problem**
currently enum with long value breaks the layout.
**Solution**
this pr sets overflow on enum value.
| <img width="348" alt="image" src="https://github.com/user-attachments/assets/73f687e1-b6a2-43a6-bf4b-d6bca1fcb641" /> | <img width="348" alt="image" src="https://github.com/user-attachments/assets/5a8edd22-a62c-4e01-a4cf-babac51c780d" /> |
**Checklist**

fix(api-client): enum long value

---

packages/build-tooling/scripts/lint-check.sh
packages/build-tooling/scripts/lint-fix.sh

**Problem**
The new lint script uses ESLint to lint Vue files, but it tries it even in packages that don’t have Vue files.
**Solution**
Let’s just check whether we have Vue files before running ESLint.
**Checklist**

feat(build-tooling): only lint when vue files are there

---

.changeset/hungry-schools-doubt.md
packages/api-reference/src/features/Operation/components/ParameterListItem.vue

**Problem**
Currently, we’re rendering Markdown in the response description on the right side, but not on the left side. That’s inconsistent.
**Solution**
With this PR we’re rendering Markdown on the left side, too.
Fixes #4747
**Before**
**After**
**Checklist**

feat(api-reference): render Markdown in the response list

---

.changeset/cyan-camels-exist.md
packages/fastify-api-reference/README.md
packages/fastify-api-reference/src/fastifyApiReference.test.ts
packages/fastify-api-reference/src/fastifyApiReference.ts
packages/fastify-api-reference/src/types.ts

**Problem**
Currently, we just use the default logger settings. If you want to override the setting for the logLevel for our routes, there’s no way to do this.
**Solution**
With this PR we’re passing an (optional) `logLevel` to all registered routes.
Fixes #4783
**Checklist**

feat(fastify-api-reference): pass `logLevel` to registered routes

---

.changeset/big-cherries-worry.md
integrations/express/package.json

**Problem**
Currently, the package.json of the Express integration points to the old CJS build that we don’t have anymore
**Solution**
This PR removes it. ✨ 
Fixes #4800
**Checklist**

fix(express-api-reference): package.json points to CJS build

---

.changeset/eleven-pillows-leave.md
packages/api-client/src/views/Request/ResponseSection/ResponseBodyVirtual.vue

**Problem**
Currently, on small screens virtualization was not working since the container did not have a fixed height so it was taking up all the space. That was causing all the response body to be rendered which was making the tab unresponsive
See  #4757 
**Solution**
With this PR we set a max height on the container in order to make virtualization work on smaller screens.
**Checklist**

fix(api-client): virtualization issues causing tab to be unresponsive

---

.changeset/shiny-ligers-yawn.md
.changeset/smooth-roses-lick.md
packages/api-client/src/components/AddressBar/AddressBar.vue
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/libs/hot-keys.test.ts
packages/api-client/src/libs/hot-keys.ts

**Problem**
You cannot execute the request from the address bar
**Solution**
With this PR we allow:
- allowing any hotkey with a modifier to trigger from within any inputs (ctrl+enter will work)
- allow hitting enter to submit in the address bar specifically
This one is for @DemonHa, I kept hitting this as well 😭 
**Checklist**

fix(api-client): hitting hotkeys while in inputs

---

.changeset/mean-brooms-decide.md
.changeset/mighty-eggs-do.md
.changeset/wise-actors-tease.md
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/components/DataTable/DataTableCell.vue
packages/api-client/src/components/DataTable/DataTableInputSelect.vue
packages/api-client/src/views/Request/RequestSection/RequestTable.vue
packages/api-client/src/views/Request/RequestSection/RequestTableTooltip.vue
packages/api-client/src/views/Request/libs/request.test.ts
packages/api-client/src/views/Request/libs/request.ts
packages/components/src/components/ScalarIcon/icons/Alert.svg
packages/components/src/components/ScalarIcon/icons/index.ts
packages/themes/src/presets/default.css
packages/themes/src/tailwind.ts

**Problem**
currently when using a different type or expected value in a request parameter, no visual cue is given.
**Solution**
this pr is adding in order to incentive the user regarding the expected type or value:
- lib function that return warning message according to the expected type/value
- visual alert on the given row receiving a non valid type/value
- keeps allowing request to be sent
| <img width="617" alt="image" src="https://github.com/user-attachments/assets/05ba09d2-48f2-480b-9864-794e914c9818" /> | <img width="617" alt="image" src="https://github.com/user-attachments/assets/d8177ade-3fc7-40c1-8e6d-622e4c555fad" /> |
| no visual cue is used | row is highlighted along displaying a warning message | 
**Checklist**
I’ve gone through the …

feat(api-client): schema based validation

---

.changeset/plenty-cups-own.md
packages/api-client/src/layouts/Web/ApiClientWeb.vue
packages/api-client/src/store/active-entities.ts
packages/api-client/src/views/Request/Request.vue
packages/api-client/src/views/Settings/SettingsGeneral.vue

**Problem**
There was a completely blank view when your active collection has no requests.
**Solution**
Added a few failsafes, moved the if statement so the sidebar will show even if theres no active request, added some empty states.
**Checklist**

fix(api-client): client empty state

---

eslint.config.mjs
packages/api-client/src/components/CommandPalette/CommandPaletteExample.vue

**Problem**
Eslint fixes it, then prettier breaks it.
**Solution**
We unfortunately need to comment the eslint rule, its much nicer but there's no way to configure it into prettier.
Lets remove prettier?
**Checklist**

chore: disable `vue/singleline-html-element-content-newline` ESLint rule

---

.changeset/giant-parents-live.md
packages/components/src/components/ScalarSidebar/ScalarSidebar.stories.ts
packages/components/src/components/ScalarSidebar/ScalarSidebarButton.vue
packages/components/src/components/ScalarSidebar/ScalarSidebarGroup.vue
packages/components/src/components/ScalarSidebar/ScalarSidebarIndent.vue
packages/components/src/components/ScalarSidebar/ScalarSidebarItem.vue
packages/components/src/components/ScalarSidebar/ScalarSidebarItems.vue
packages/components/src/components/ScalarSidebar/types.ts
packages/components/tailwind.config.ts
packages/themes/src/presets/alternate.css
packages/themes/src/presets/default.css
packages/themes/src/variables.css

This PR adds theme-able nesting lines with a customizable offset / spacing.
https://github.com/user-attachments/assets/3e33c03b-6f26-4ed1-b1ca-cfdc504f154e
**Checklist**

feat(components): add sidebar nesting indicator lines

---

.changeset/many-balloons-smash.md
.changeset/mean-brooms-decide.md
.changeset/mighty-eggs-do.md
.changeset/wise-actors-tease.md
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/components/DataTable/DataTableCell.vue
packages/api-client/src/components/DataTable/DataTableInputSelect.vue
packages/api-client/src/views/Request/RequestSection/RequestTable.vue
packages/api-client/src/views/Request/RequestSection/RequestTableTooltip.vue
packages/api-client/src/views/Request/libs/request.test.ts
packages/api-client/src/views/Request/libs/request.ts

**Problem**
currently request can be sent out with empty required field and no visual cue is given.
**Solution**
this pr adds visual cue when a required field value is empty and prevents the request to be sent.
| <img width="1466" alt="image" src="https://github.com/user-attachments/assets/cbb114d8-a64d-4d93-9345-224a2a6f2104" /> | <img width="1466" alt="image" src="https://github.com/user-attachments/assets/2722f218-ceff-4377-bfcc-79b2df27cb3b" /> |
| no required field visual cue nor error | required field visual cue + toast | 
**Checklist**

feat(api-client): request required field validation

---

.changeset/twelve-moose-leave.md
packages/use-codemirror/src/hooks/useCodeMirror.ts

**Problem**
currently we cannot from the api client input undo or redo value insertion.
**Solution**
this pr adds history support to codemirror in order to enable undo/redo action.
**Checklist**

feat(use-codemirror):  undo/redo

---

.changeset/wicked-berries-fold.md
packages/api-client/src/components/CommandPalette/CommandPaletteImport.vue

**Problem**
Currently, you import a collection and you have to click it
**Solution**
With this PR it navigates to our new collection page :)
**Checklist**

fix(api-client): when importing a collection we navigate to the collection page

---

.changeset/tough-owls-compete.md
packages/api-reference/playground/examples/src/App.vue
packages/api-reference/src/features/ExampleResponses/ExampleResponses.test.ts
packages/api-reference/src/features/ExampleResponses/ExampleResponses.vue
packages/types/src/legacy/reference-config.ts

**Problem**
Currently, we don't handle `*/*` mimeTypes
**Solution**
With this PR we render it :) 
before:
after:
**Checklist**

fix(api-reference): show */* mimetype in example response

---

.changeset/tall-bikes-crash.md
packages/api-reference/src/helpers/parse.ts
packages/api-reference/src/hooks/useReactiveSpec.test.ts
packages/api-reference/src/hooks/useReactiveSpec.ts

**Problem**
Currently, the API reference doesn’t clear it’s state properly when the OpenAPI document changes. You can see this in the sidebar, that it keeps models and webhooks, even if you replace the document with an empty OpenAPI document.
This is especially a problem when used with an input or when switching between multiple API definitions.
**Solution**
With this PR we’re clearing the state properly. :)
**Checklist**

fix(api-reference): doesn’t clear state properly

---

.changeset/silly-jeans-grab.md
packages/api-client/src/components/CommandPalette/TheCommandPalette.vue

**Problem**
currently users cannot navigate to pages through the command palette.
```console
Uncaught Error: No match for
{"name":"/workspace/default/environment","params":{"workspace":"default"}}
```
**Solution**
this pr updates the command palette routing.
**Checklist**

fix(api-client): command palette routing

---

.changeset/sweet-cars-own.md
packages/api-reference/src/features/Search/SearchButton.vue
packages/api-reference/src/features/Search/SearchModal.vue
packages/api-reference/src/features/Search/useSearchIndex.ts
packages/components/src/components/ScalarColorModeToggle/ScalarColorModeToggleIcon.vue
packages/components/src/components/ScalarModal/ScalarModal.stories.ts
packages/components/src/components/ScalarSearchInput/ScalarSearchInput.vue
packages/components/src/components/ScalarSearchResults/ScalarSearchResultItem.vue

Improves the search dialog to better support NVDA vs Voiceover. Sorry if the video is a little much, should be much more verbose now though ✨ 
https://github.com/user-attachments/assets/950d1bee-3712-42e6-9887-f30220cc8e2e
**Checklist**

fix(api-reference): improve search button and modal a11y

---

biome.json

We’ve got some problems with Biome and the ASP.NET Core integration, this should fix it.

chore: ignore some aspnetcore folders

---

.changeset/tidy-clouds-fetch.md
packages/api-client/src/components/CodeInput/CodeInput.vue

**Problem**
currently api reference modal address bar is wrapping on long path.
**Solution**
this pr sets no wrap to disabled address bar path.
| <img width="548" alt="image" src="https://github.com/user-attachments/assets/37269bad-f4a0-456e-8e0a-0e4070913c05" /> | <img width="573" alt="image" src="https://github.com/user-attachments/assets/964d6ed2-4a26-4a4b-bc82-14b56cac4d85" /> |
**Checklist**

fix(api-client): address bar path whitespace

---

.changeset/rich-carpets-build.md
packages/api-client/src/components/DataTable/DataTableInput.vue
packages/api-client/src/components/ViewLayout/ViewLayoutCollapse.vue
packages/api-client/src/components/ViewLayout/ViewLayoutSection.vue
packages/api-client/src/views/Cookies/CookieForm.vue
packages/api-client/src/views/Cookies/Cookies.vue
packages/api-client/src/views/Environment/Environment.vue
packages/api-client/src/views/Request/RequestSection/RequestCodeExample.vue
packages/api-client/src/views/Request/RequestSection/RequestSection.vue
packages/api-client/src/views/Request/ResponseSection/ResponseEmpty.vue

**Problem**
currently some outline are hidden by overflow within the api client.
**Solution**
this pr fixes a focus type issue + refactor overall border style management.
| <img width="754" alt="image" src="https://github.com/user-attachments/assets/3b75c967-eacd-4c83-8199-d1419d0945e1" /> | <img width="754" alt="image" src="https://github.com/user-attachments/assets/013907a4-7f26-4193-b450-d64b42807f1c" /> |
| outline overflow | outline fully visible | 
**Checklist**

fix(api-client): overall border style

---

.changeset/spotty-queens-pretend.md
examples/web/src/pages/EmbeddedApiReferencePage.vue
packages/api-reference/src/components/Anchor/Anchor.vue
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/Content/Introduction/Introduction.vue
packages/api-reference/src/components/Content/Lazy/Loading.vue
packages/api-reference/src/components/Content/Models/Models.vue
packages/api-reference/src/components/Content/Models/ModelsAccordion.vue
packages/api-reference/src/components/Content/Tag/Endpoints.vue
packages/api-reference/src/components/Content/Tag/Tag.vue
packages/api-reference/src/components/Content/Tag/TagAccordion.vue
packages/api-reference/src/components/Section/SectionContainer.vue
packages/api-reference/src/components/Section/SectionHeader.vue
packages/api-reference/src/components/Section/SectionHeaderTag.vue
packages/api-reference/src/components/Section/index.ts
packages/api-reference/src/components/Sidebar/Sidebar.vue
packages/api-reference/src/features/Operation/Webhooks.vue
packages/api-reference/src/features/Operation/layouts/ClassicLayout.vue
packages/api-reference/src/features/Operation/layouts/ModernLayout.vue
packages/api-reference/src/standalone/lib/html-api.ts

More a11y! This PR cleans up our headings so users get a proper tree with the heading names and labels our regions correctly so you can navigate the page sections. Models and webhooks still need a bit more work but this is still an improvement.
I also added hidden headings so the full heading tree structure is available to screen readers even if the "Show More" buttons are collapsed. 
Here's a before and after video with NVDA, it also works well with voiceover but I can't take a screen recording of that because running the screen recorder confuses voiceover.
https://github.com/user-attachments/assets/06300a38-3c11-4cb0-b265-a2e23584bd30
**Checklist**

fix(api-reference): fix headings and add / organize regions 

---

.changeset/stupid-birds-rescue.md
packages/snippetz/src/utils/convertWithHttpSnippetLite.test.ts
packages/snippetz/src/utils/convertWithHttpSnippetLite.ts

**Problem**
Currently, if a mimeType of `application/json` is provided & theres no jsonObj, we dont handle the scenario when a `text` is provided
Fixes #4870
**Solution**
With this PR we handle it
**Checklist**

fix(snippetz): doesn’t parse text for JSON requests

---

.github/actions/build/action.yml
tooling/base-docker-builder/Dockerfile

OMG, the build is failing way too often and I think we hit the memory limit again. GHA runners for public repositories have 16 GB, so let’s increase the limit to 8 GB.
If CI passes on the first run, we should merge this PR.
I have the impression that we/turborepo has a memory leak, but I couldn’t find a way to properly debug this (without spending too much time).
EDIT: It failed, but because of a flaky test.

ci: increase memory limit

---

.changeset/cool-brooms-add.md
integrations/express/Dockerfile
integrations/fastify/Dockerfile

**Problem**
We recently added the html builder to api-reference.
pnpm will only replace the `workspace:*` dependencies on publish, here we are using the monorepo packages so it could not find the api-reference in the docker containers
**Solution**
We could either replace all `workspace:*` dependencies before pnpm i OR just copy over the dependencies into the docker container. Since there was only one dependency in this case I just copied it and it worked. Open to the other method as well. 
**Checklist**

fix(integrations): express and fastify examples not running

---

.changeset/two-buses-tell.md
packages/themes/src/tailwind.ts

Let's us override `font-code` by setting `font-sans`.
**Checklist**

feat(themes): add font-sans for default scalar font

---

.changeset/olive-parrots-attend.md
documentation/markdown.md
packages/code-highlight/package.json
packages/code-highlight/src/css/markdown.css
packages/code-highlight/src/markdown/markdown.ts
packages/code-highlight/src/rehype-alert/index.ts
packages/code-highlight/src/rehype-alert/rehype-alert.test.ts
packages/code-highlight/src/rehype-alert/rehype-alert.ts
packages/galaxy/src/documents/3.1.yaml

**Problem**
there are no support of markdown alert as of today.
**Solution**
this pr is a proposal to support markdown alert using the following:
```md
> [!note]
> This is a note callout.
```
| <img width="569" alt="image" src="https://github.com/user-attachments/assets/21ae3b89-469f-43d7-9539-c5e141bc5e91" /> | <img width="569" alt="image" src="https://github.com/user-attachments/assets/a7573823-3f4d-40ba-8fbe-1cffbd39109f" /> |
**Checklist**

feat(code-highlight): markdown alert callout support

---

.changeset/shaggy-waves-sin.md
packages/api-client/src/libs/create-client.ts

**Problem**
Currently, we have a flaky test that sometimes (actually way too often, but not always) says `localStorage is not defined` in CI.
**Solution**
With this PR `createClient` doesn’t rely on localStorage to be available. Hopefully, this fixes the flaky test.
**Checklist**

feat(api-client): rely less on local storage

---

.changeset/khaki-plums-doubt.md
packages/galaxy/Dockerfile

**Problem**
Currently, …
**Solution**
With this PR …
**Checklist**

fix(galaxy): ensure we move the api reference package into the galaxy dockerfile

---

.changeset/flat-deers-hang.md
packages/api-client/tailwind.config.ts
packages/components/src/components/ScalarMenu/ScalarMenuTeamPicker.vue
packages/components/tailwind.config.ts

fix(components): set the submenu z-index above the menu

---

.changeset/hip-walls-accept.md
packages/api-reference/src/components/ApiReferenceLayout.vue

**Problem**
Currently the reference editor within docs is overflowing the topbar menu.
**Solution**
this pr resets z-index from the reference editor element.
| <img width="618" alt="image" src="https://github.com/user-attachments/assets/f9daca6e-3507-4331-89e2-133a19a8d3e3" /> | <img width="618" alt="image" src="https://github.com/user-attachments/assets/aeb8f9b4-8dcc-44b8-ad07-cbc0a4ff2c6d" /> |
**Checklist**

fix(api-reference): removes reference editor z index

---

.changeset/hungry-pets-wait.md
packages/api-client-react/README.md
packages/api-client-react/package.json
packages/api-client-react/playground/App.tsx
packages/api-client-react/playground/index.html
packages/api-client-react/src/ApiClientModalProvider.tsx
packages/api-client-react/tsconfig.build.json
packages/api-client-react/tsconfig.json
packages/api-client-react/vite.config.ts
packages/api-reference-react/README.md
packages/api-reference-react/package.json
packages/api-reference-react/src/ApiReferenceReact.tsx
packages/api-reference-react/src/index.ts
packages/api-reference-react/src/style.css
packages/api-reference-react/tsconfig.build.json
packages/api-reference-react/tsconfig.json
packages/api-reference-react/vite.config.ts
pnpm-lock.yaml

**Problem**
We have issues running the packages on react 18
**Solution**
With this PR we should be able to run on both react 18 as well as 19.
**Checklist**

fix(api-reference-react): ensure react packages work on both react versions

---

.changeset/red-gorillas-mix.md
packages/api-reference/playground/esm/index.html
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/hooks/useNavState.ts
packages/api-reference/src/types.ts
packages/types/src/legacy/reference-config.ts

**Solution**
With this PR we add a front-end redirect.
To test:
```zsh
cd packages/api-reference
pnpm playground:esm
```
then hit [http://localhost:5173/#tag/planets/GET/planets/{planetId}](http://localhost:5173/#tag/planets/GET/planets/%7BplanetId%7D) and you should land on the path version
**Checklist**

feat(api-reference): add redirect

---

integrations/fastapi/README.md
integrations/fastapi/scalar_fastapi/scalar_fastapi.py
integrations/fastapi/setup.py

**Problem**
Currently, it is not possible to set the `authentication` configuration options for Scalar from the `scalar-fastapi` integration as it is not a supported argument.
**Solution**
With this PR it is possible to add the authentication options in the FastAPI integration, it defaults to an empty dictionary if no argument is passed.
**Checklist**

feat(scalar_fastapi): Add authentication configuration for FastAPI

---

.changeset/six-pandas-fold.md
packages/api-reference/src/features/Operation/components/ContentTypeSelect.vue
packages/api-reference/src/features/Operation/components/ParameterListItem.vue
packages/api-reference/src/features/Operation/components/RequestBody.vue

**Problem**
currently the content type select style used in api reference response is broken
**Solution**
this pr updates content type select component style and uses it in request body also.
| <img width="597" alt="image" src="https://github.com/user-attachments/assets/86e6f333-73ed-4744-9836-89f6d4415c99" /> | <img width="597" alt="image" src="https://github.com/user-attachments/assets/ce4ad61f-c5c0-46e5-8e92-694f2c404e02" /> |
**Checklist**

fix(api-reference): content type select

---

.changeset/stale-ways-reply.md
packages/galaxy/playground/package.json

**Problem**
Currently, our CI tries to deploy the @scalar-examples/galaxy but it does not exist.
**Solution**
With this PR we set it to private so it does not try to publish
**Checklist**

fix(galaxy): make galaxy playground private

---

.changeset/chilled-keys-flow.md
packages/api-reference/playground/esm/index.html
packages/oas-utils/src/transforms/import-spec.ts
packages/types/src/legacy/reference-config.ts

This is a super temp hack to get multiple bearer auth tokens in, we will add proper multi auth right after the config PR.
```ts
authentication: {
http: {
bearer: {
token: 'Default Bearer',
multiple: {
bearerAuth: 'Bearer token 1',
bearerAuth2: 'Bearer token 2',
},
},
},
},
```
**Checklist**

feat(api-reference): add multiple bearer auth

---

.changeset/tricky-boats-draw.md
integrations/aspnetcore/src/Scalar.AspNetCore/Mapper/ScalarOptionsMapper.cs
integrations/aspnetcore/src/Scalar.AspNetCore/ScalarConfiguration.cs
integrations/aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarOptionsMapperTests.cs

Closes #4941 
**Problem**
We had a typo in the `ScalarConfiguration` and the tags sorter configuration was serialized to `tagSorter`.
**Solution**
I renamed the property to `TagsSorter` so it's correctly serialized to `tagsSorter`.
**Checklist**

fix(Scalar.AspNetCore): rename TagSorter property to TagsSorter

---

documentation/configuration.md
packages/api-client/src/components/Server/ServerSelector.vue
packages/api-reference/src/features/BaseUrl/BaseUrl.vue
packages/types/src/legacy/reference-config.ts

**Problem**
Currently when a server changes we cant tell the outside world its changed
**Solution**
With this PR we allow a callback for when the active server changes
**Checklist**

feat: add server change callback

---

.changeset/pink-eggs-return.md
packages/api-client/src/components/TopNav/TopNav.vue
packages/api-client/src/components/TopNav/TopNavItem.vue

**Problem**
currently the icon displayed on the top nav when in a collection is not matching with the collection icon.
**Solution**
this pr updates the top nav logic in order to reflect the collection icon:
| <img width="788" alt="image" src="https://github.com/user-attachments/assets/afa9ba60-1f52-4fea-8e61-858fc48139d0" /> | <img width="788" alt="image" src="https://github.com/user-attachments/assets/b0a0f923-4459-4e43-9578-94cbadd7e033" /> |
**Checklist**

fix(api-client): top nav icon collection not retrieved

---

.changeset/purple-dingos-laugh.md
packages/api-client/src/components/OpenApiClientButton.vue
packages/api-client/src/layouts/Modal/ApiClientModal.vue
packages/api-client/src/views/Request/RequestSubpageHeader.vue
packages/components/src/components/ScalarModal/ScalarModal.vue
packages/themes/src/tailwind.ts
packages/use-hooks/src/useBreakpoints/useBreakpoints.test.ts
packages/use-hooks/src/useBreakpoints/useBreakpoints.ts

A bit more zoom cleanup and adding a tailwind breakpoint for it for consistency.
https://github.com/user-attachments/assets/72974326-b328-4bda-9307-efd0786fcbaa
**Checklist**

fix(themes): improve how we handle zoomed in screens

---

.changeset/wicked-hornets-change.md
examples/nextjs-api-reference/app/another-client/page.tsx
examples/nextjs-api-reference/app/client/components/Button.tsx
examples/nextjs-api-reference/app/client/components/ClientWrapper.tsx
examples/nextjs-api-reference/app/client/page.tsx
packages/api-client-react/src/ApiClientModalProvider.tsx
packages/api-client/src/libs/create-client.ts
packages/api-client/src/libs/get-request-uid-by-path-method.test.ts
packages/api-client/src/libs/get-request-uid-by-path-method.ts
pnpm-workspace.yaml

**Problem**
Currently, every time you open the modal it goes to the same request
**Solution**
With this PR we boot out the function into its own util so we can test it, also fixed it.
**Checklist**

fix(api-client): find correct request for route change

---

.github/dependabot.yml

Weekly dependabot updates feel like they are daily, let’s see if monthly updates feel like they are weekly.

chore: monthly dependabot updates

---

.changeset/twelve-points-raise.md
packages/api-client/src/views/Request/RequestSection/RequestBody.test.ts
packages/api-client/src/views/Request/RequestSection/RequestBody.vue

**Problem**
Currently, we remove content-type header if its added in the spec
**Solution**
With this PR we only set the content-type header if the body is selected
**Checklist**

fix(api-client): remove header update if initial body is set to raw

---

package.json
packages/scalar-app/todesktop.json
pnpm-workspace.yaml
tooling/base-docker-builder/Dockerfile

**Problem**
Currently, our pnpm version is a bit stale.
**Solution**
With this PR we upgrade pnpm to get the new goodies (linking etc)
Also security (yay) I allowed these packages + core-js to run postbuild scripts, we can add the others if needed.
**Checklist**

chore: upgrade pnpm

---

tooling/base-docker-builder/Dockerfile

**Problem**
Currently, my fork of a package will not download as there's no git on the slim docker image.
**Solution**
With this PR we add git, which also adds quite a bit of disk space but 🤷🏾 
**Checklist**

fix: base docker image was missing git

---

.changeset/flat-chefs-mate.md
packages/oas-utils/src/entities/spec/parameters.test.ts
packages/oas-utils/src/entities/spec/parameters.ts
packages/oas-utils/src/entities/spec/request-examples.ts

**Problem**
currently parameter examples of type array or not well supported as seen in [sf compute api documentation](https://docs.sfcompute.com/api-reference#tag/orders/POST/v0/orders)
**Solution**
this pr updates the parameter entity to support examples of type array.
| <img width="1193" alt="image" src="https://github.com/user-attachments/assets/2df61eb8-6e8f-4dfb-8c62-87749f3674af" /> | <img width="1193" alt="image" src="https://github.com/user-attachments/assets/a8c9831e-68b8-42c2-8b12-4a1b9a5debcc" /> |
| endpoint is not rendering properly | endpoint is not rendered | 
**Checklist**

fix(oas-utils): parameter examples array support

---

.changeset/good-seas-swim.md
.github/workflows/ci.yml

**Problem**
Currently our CI has broken, build tooling seems to be missing although it is there locally.
**Solution**
With this PR we just kill the turbo cache in case that is the issue, as we didn't change anything.
**Checklist**

fix(build-tooling): ci build

---

.changeset/mean-flowers-shave.md
packages/galaxy/Dockerfile

**Problem**
Currently, the types package was missing from galaxy
**Solution**
With this PR we add the types package
**Checklist**

fix(galaxy): types missing from galaxy docker file

---

.changeset/grumpy-flowers-know.md
packages/api-client/src/components/AddressBar/AddressBarHistory.vue
packages/api-client/src/components/Sidebar/SidebarToggle.vue
packages/api-client/src/layouts/Modal/create-api-client-modal.ts
packages/api-client/src/views/Request/Request.vue
packages/api-client/src/views/Request/RequestRoot.test.ts
packages/api-client/src/views/Request/RequestRoot.vue
packages/api-client/src/views/Request/RequestSidebar.vue
packages/api-client/src/views/Request/RequestSubpageHeader.test.ts
packages/api-client/src/views/Request/RequestSubpageHeader.vue
packages/api-reference/src/features/ApiClientModal/useApiClient.ts

Improves the client sidebar toggle, search and address bar. I moved the toggle to an overlay in a single location so it doesn't break focus when opening the sidebar. As a bonus we get the toggle animation back ✨ @cameronrohani if you want to double check I didn't break the sidebar.
https://github.com/user-attachments/assets/12d266a5-79b3-44bc-a4da-4912dcbc205b
**Checklist**

fix(api-client): improve api client sidebar and address bar a11y

---

.changeset/long-dancers-wash.md
packages/api-client/src/libs/extractAttachmentFilename.test.ts
packages/api-client/src/libs/extractAttachmentFilename.ts

See related issue #4925 
**Checklist**

fix(api-client): handle UTF-8 encoded file names for content-disposition header

---

.changeset/proud-spies-fetch.md
packages/api-client/src/views/Request/RequestSection/RequestBody.vue
packages/api-client/src/views/Request/RequestSection/RequestTable.vue

**Problem**
currently the multi form upload style is broken.
**Solution**
this pr updates the multi form styles + its logic in order to remove the file only if the key have been updated, otherwise the all row.
| <img width="612" alt="image" src="https://github.com/user-attachments/assets/4a27a21b-7dd0-460b-91c1-0288ecc54e1d" /> | <img width="612" alt="image" src="https://github.com/user-attachments/assets/73649c0d-0d23-470d-8de9-453aa5256ce6" /> |
| overflowing row creating a gap | row height is preserved | 
**Checklist**

fix(api-client): multi form upload

---

.changeset/cold-years-cross.md
.changeset/spotty-walls-crash.md
packages/api-client/src/libs/importers/curl.ts
packages/api-client/src/views/Request/RequestSection/RequestBody.vue
packages/oas-utils/src/entities/spec/request-examples.ts
packages/oas-utils/src/helpers/normalizeMimeType.test.ts
packages/oas-utils/src/helpers/normalizeMimeType.ts
packages/oas-utils/src/helpers/normalizeMimeTypeObject.test.ts
packages/oas-utils/src/spec-getters/getRequestBodyFromOperation.test.ts
packages/oas-utils/src/spec-getters/getRequestBodyFromOperation.ts
packages/types/src/legacy/reference-config.ts

**Problem**
Currently we convert everything to a `json` type and not respecting the proper mime type definition 
**Solution**
With this PR it respects the mime type definition if available ans fixes #4525 
**Checklist**

fix(api-client): mime type transformation issue

---

.changeset/fuzzy-papayas-shop.md
packages/api-client/src/components/CodeInput/CodeInput.vue

Adds visual and screen reader instructions for exiting the code mirror input. I tried to add a screen reader label to the code mirror input but wasn't able to get it working so this just uses an alert for now.
**Checklist**

fix(api-client): add keyboard instructions for code inputs

---

.changeset/slow-pants-itch.md
packages/types/src/api-reference/api-reference-configuration.test.ts
packages/types/src/api-reference/api-reference-configuration.ts

**Problem**
Currently, we missed allowing true for `hiddenClients`
**Solution**
With this PR we allow `true`
**Checklist**

fix(api-reference): hidden clients zod schema update

---

.changeset/flat-camels-do.md
packages/components/src/components/ScalarModal/ScalarModal.vue

**Problem**
Currently the modal is centered when opening the client from an api reference.
**Solution**
this pr removes the x axis margin from the scalar modal component.
| <img width="1470" alt="image" src="https://github.com/user-attachments/assets/b230e37d-2a73-4531-a5e6-abeb705ff088" /> | <img width="1470" alt="image" src="https://github.com/user-attachments/assets/e6b0e841-ca39-407a-8493-ca2ffbafaca6" /> |
**Checklist**

fix(components): scalar modal position

---

.changeset/sixty-maps-battle.md
packages/api-reference/src/standalone.ts
packages/api-reference/vite.config.ts
packages/api-reference/vite.standalone.config.ts

**Problem**
Currently, its kind of hard to know what version of references users are on when debugging.
**Solution**
With this PR we log the version so we can grab it from the console.
**Checklist**

feat(api-reference): add version logged to the console

---

.changeset/seven-monkeys-cover.md
integrations/nuxt/package.json
packages/api-client/src/views/Request/RequestSection/RequestBody.test.ts
packages/api-client/src/views/Request/RequestSection/RequestBody.vue

**Problem**
Currently, the body selected would be none due to an early return of mime type
**Solution**
With this PR we remove that early return and things seem to just work?
**Checklist**

fix(api-client): incorrect body being selected

---

.changeset/red-windows-juggle.md
.changeset/six-impalas-return.md
integrations/fastify/vite.config.ts
packages/oas-utils/src/transforms/import-spec.ts

**Problem**
Currently, the standalone file seems to be missing
**Solution**
With this PR we find it using resolve so its relative to the current file. ALSO as a bonus we remove undefined selected security schemes.
**Checklist**

fix(fastify-api-reference): ensure we copy over the standalone file into the correct directory

---

.gitattributes
.prettierrc

**Problem**
Windows users (✋) had issues with prettier and biome during a commit. The formatters replaced every EOL to `crlf`.
**Solution**
I added a `.gitattributes` file to the root of the project and updated the prettier config. Other big projects also have the `* text=auto` setting in the configuration. It looks like this works on my (windows) machine. It would be awesome if someone with a mac could verify that `pnpm format` works as expected.
With this PR …
**Checklist**

chore: update eol to LF

---

.changeset/shiny-pans-notice.md
packages/api-client/src/views/Components/CodeSnippet/helpers/get-snippet.ts
packages/api-client/src/views/Request/RequestSection/RequestCodeExample.test.ts
packages/api-client/src/views/Request/RequestSection/RequestCodeExample.vue

**Problem**
currently the authentication is missing from the code snippet
**Solution**
this pr sets the operation security scheme uid in the request code example.
| <img width="628" alt="image" src="https://github.com/user-attachments/assets/c8834344-06a2-4e07-ae9e-1ff07dde1b81" /> | <img width="628" alt="image" src="https://github.com/user-attachments/assets/1c8f6ac1-db70-4a0c-9429-be7f3bd7ac1c" /> |
**Checklist**

fix(api-client): missing authentication in code snippet

---

.changeset/odd-trees-listen.md
integrations/fastify/package.json

**Problem**
Currently, we were missing the build:playground script.
**Solution**
With this PR we add it back
**Checklist**

fix(fastify): missing script to build playground

---

.changeset/nine-suits-greet.md
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/Content/Introduction/Introduction.vue
packages/api-reference/src/features/BaseUrl/BaseUrl.vue
packages/api-reference/src/features/ExampleRequest/ExampleRequest.vue
packages/api-reference/src/features/Search/useSearchIndex.test.ts
packages/api-reference/src/features/TestRequestButton/TestRequestButton.test.ts
packages/api-reference/src/features/TestRequestButton/TestRequestButton.vue
packages/api-reference/src/hooks/useConfig.test.ts
packages/api-reference/src/hooks/useConfig.ts
packages/api-reference/src/hooks/useNavState.test.ts
packages/api-reference/src/hooks/useNavState.ts
packages/api-reference/src/hooks/useSidebar.test.ts
packages/core/package.json

**Problem**
Currently, I live in a linear, synchronous world.
**Solution**
With this PR it becomes reactive.
**Checklist**

fix(api-reference): make useConfig reactive

---

.changeset/fuzzy-spies-type.md
.changeset/loud-chairs-teach.md
documentation/markdown.md
packages/code-highlight/src/css/markdown.css
packages/code-highlight/src/markdown/markdown.ts
packages/code-highlight/src/rehype-alert/rehype-alert.test.ts
packages/code-highlight/src/rehype-alert/rehype-alert.ts

**Problem**
currently markdown alert are not being properly styled within api reference.
**Solution**
this pr fixes the markdown alert rendering + adds icon and update style.
| <img width="620" alt="image" src="https://github.com/user-attachments/assets/f08a57d2-1118-4006-87ab-529adfb4df28" /> | <img width="620" alt="image" src="https://github.com/user-attachments/assets/eb626747-40e1-4ba6-b633-2216e785d274" /> |
<details>
<summary>All the supported alert</summary>
| code | preview |
| [!note] | <img width="527" alt="image" src="https://github.com/user-attachments/assets/06104289-86e0-4696-9782-c18c5e29c7e9" /> |
| [!tip] | <img width="527" alt="image" src="https://github.com/user-attachments/assets/4e803e96-7c7d-4e26-add6-8afc41780294 …

fix(code-highlight): markdown alert

---

documentation/configuration.md

https://github.com/scalar/scalar/tree/main/examples/proxy-server to
https://github.com/scalar/scalar/tree/main/projects/proxy-scalar-com
**Problem**
Currently, …
**Solution**
With this PR …
**Checklist**

fix: dead link in docs

---

.changeset/eight-bags-breathe.md
packages/components/src/components/ScalarModal/ScalarModal.vue

**Problem**
recent updates to scalar modal broke its position in org usage due to a utility class precedence issue.
**Solution**
this pr removes scoped style to maintain modal position.
| <img width="1470" alt="image" src="https://github.com/user-attachments/assets/dae738f1-ee66-43da-b3a5-e3507bb14f9a" /> | <img width="1470" alt="image" src="https://github.com/user-attachments/assets/4c0d84d2-78b1-453b-b34d-d52ebf642992" /> |
**Checklist**

fix(components): modal position

---

.changeset/thin-seahorses-tickle.md
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuth.test.ts
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuth.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuthTab.vue

**Problem**
currently when using complex auth within the client the indicator is not displaying the right value.
**Solution**
this pr updates the auth indicator function to support complex auth and fixes #4933.
| <img width="605" alt="image" src="https://github.com/user-attachments/assets/4a06e06c-5bc1-4cf4-8da7-01eea6cd6eb8" /> | <img width="605" alt="image" src="https://github.com/user-attachments/assets/24a291be-8b15-4d9b-92d7-30b7eebe4ded" /> |
| auth is only required for one requirement | auth required for both requirements | 
**Checklist**

fix(api-client): complex auth indicator is not retrieved

---

.changeset/dull-avocados-cheer.md
packages/openapi-parser/README.md
packages/openapi-parser/src/utils/upgradeFromTwoToThree.ts

Time to remove the warning for the Swagger 2.0 upgrade, it’s running fine in production for months.

chore(openapi-parser): remove warning for Swagger 2.0 upgrade

---

.changeset/young-ladybugs-taste.md
integrations/nextjs/package.json
integrations/nextjs/src/ApiReference.ts
integrations/nextjs/src/custom-theme.ts
integrations/nextjs/src/types.ts
packages/core/package.json
pnpm-lock.yaml

With this PR we’re using the central HTML rendering library from `@scalar/core` in the Next.js integration.
This will make it so easy to add the multi document feature.

feat(nextjs): use HTML rendering lib from `@scalar/core`

---

.changeset/lemon-humans-sort.md
packages/oas-utils/src/entities/spec/security.test.ts
packages/oas-utils/src/entities/spec/security.ts

**Problem**
Currently, having null a scope breaks everything
**Solution**
With this PR we add a catch for null values
**Checklist**

fix(oas-utils): allow null as an oauth2 scope

---

.changeset/selfish-eggs-behave.md
.github/workflows/deploy-examples.yml

**Problem**
Currently, our example deploy breaks
**Solution**
With this PR we move the cache restore up to before the install
**Checklist**

fix(ci): move turbo cache restore up in deploy-examples

---

.changeset/rich-suns-learn.md
packages/api-reference/src/features/Operation/components/ContentTypeSelect.test.ts
packages/api-reference/src/features/Operation/components/ContentTypeSelect.vue
packages/api-reference/src/features/Operation/components/ParameterListItem.vue
packages/api-reference/src/features/Operation/components/RequestBody.vue
packages/components/src/components/ScalarListbox/ScalarListbox.vue

**Problem**
currently the content type selector is using browser native dropdown.
**Solution**
this pr is a proposal to use the scalar dropdown component.
| <img width="370" alt="image" src="https://github.com/user-attachments/assets/4a1d45c9-e5a5-4ca1-8fcc-a5845602b449" /> | <img width="370" alt="image" src="https://github.com/user-attachments/assets/c9f42d2b-78c2-4b00-a2e1-35a1cf4a12a8" /> |
**Checklist**

feat(api-reference): content type select

---

packages/api-client/src/components/AddressBar/AddressBar.vue

Let’s remove the console.log, doesn’t need a changelog, will be just part of the next release.

chore(api-client): remove focusAddressBar console.log

---

.changeset/good-horses-approve.md
.github/workflows/deploy-examples.yml

**Problem**
Currently, deploy examples always breaks on the first try. That makes it seem cache related
**Solution**
With this PR we remove restoring turbo cache to see if that helps
**Checklist**

fix(ci): remove turbo cache from deploy examples

---

.changeset/unlucky-shirts-switch.md
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/components/DataTable/DataTableInput.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/OAuth2.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuthTab.vue
packages/api-client/src/views/Request/RequestSection/RequestTableTooltip.vue

**Problem**
currently security scheme descriptions are not displayed within the api client.
**Solution**
this pr  adds security scheme description through already existing tooltip component usage. fixes #4934
| <img width="601" alt="image" src="https://github.com/user-attachments/assets/46d7b4e7-2cf8-4344-8bd1-85a33e51938d" /> | <img width="643" alt="image" src="https://github.com/user-attachments/assets/e649ab89-a2cf-476f-8806-721dd80135ca" /> |
| no description available | description is available through tooltip hover |
**Checklist**

feat(api-client): security scheme auth description

---

package.json
pnpm-lock.yaml

**Problem**
currently the `prettier-plugin-tailwindcss` dependency is available to the workspace level, where `taildwindcss` is not, which is creating some formatting issue and then breaks the format CI.
**Solution**
this pr adds `tailwindcss` dev dependency at the workspace level.
**Checklist**

chore(worksapce): adds tailwindcss to workspace

---

packages/core/package.json
packages/snippetz/Dockerfile
packages/void-server/Dockerfile

**Problem**
Currently we need some build files in docker
**Solution**
With this PR we copy over all packages
**Checklist**

fix: copy over whole packages files in docker

---

.gitattributes

This PR forces `lf` line endings (also on windows). Hopefully this will just work on any OS.

chore: update .gitattributes to enforce LF line endings

---

.changeset/rare-stingrays-lick.md
packages/import/src/resolve.test.ts
packages/import/src/resolve.ts

**Problem**
Currently, we aren't importing URLs from the config attribute
**Solution**
With this PR we grab them
**Checklist**

fix(import): importing of unescaped configuration urls

---

.changeset/funny-ligers-jog.md
.gitattributes

**Problem**
Currently, we added a new line to git attributes which seems to be editing our snapshots
**Solution**
With this PR we ignore png files (may need to add other file types down the road)
Also added a changeset to bump references from a previous fix
**Checklist**

fix: treat png files as binary

---

.changeset/happy-bees-search.md
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue
packages/api-reference/src/features/Operation/components/ParameterListItem.vue

**Problem**
Currently, we don’t show whether a parameter is deprecated.
See #5077
**Solution**
We’ve had the styles already, with this PR we’re passing down the `deprecated` attribute to show whether a parameter is deprecated.
**Preview**
**Checklist**

feat(api-reference): show deprecated parameters

---

.changeset/gorgeous-ghosts-confess.md
packages/api-client/src/components/DataTable/DataTableHeader.vue
packages/api-client/src/components/DataTable/DataTableRow.vue
packages/api-client/src/views/Request/RequestRoot.vue
packages/api-client/src/views/Request/RequestSection/RequestTable.vue
packages/api-client/src/views/Request/RequestSection/RequestTableTooltip.vue
packages/api-reference/src/components/Content/ClientLibraries/ClientLibraries.vue
packages/api-reference/src/components/Content/ClientLibraries/ClientSelector.vue
packages/api-reference/src/components/Content/Tag/OperationsListItem.vue
packages/api-reference/src/features/Operation/layouts/ModernLayout.vue
packages/api-reference/src/helpers/scrollToId.ts
packages/api-reference/src/hooks/useSidebar.ts

Changes:
1. Client libraries tabs switch elements correctly
2. Client libraries tabs are labelled by the heading
3. Added screen reader table headers to the request tables
4. Add a label to the request table help tooltip
5. Focus the sidebar toggle on modal load
6. Focus the selected operation from the endpoints list when clicked
**Checklist**

fix(api-reference): focus and screenreader improvements for client libraries, endpoints list and API client

---

.changeset/dirty-readers-watch.md
packages/api-reference/src/components/Section/CompactSection.vue

**Problem**
currently on certain screen size the collapsible section trigger or loosing their position and are not aligned anymore.
**Solution**
this pr updates the collapsible section trigger style to ensure same position behavior on all screen.
| <img width="839" alt="image" src="https://github.com/user-attachments/assets/fda605f5-5ef1-44c3-ba08-7edc1afe4d5d" /> | <img width="839" alt="image" src="https://github.com/user-attachments/assets/19eb89de-52bd-49e8-a28a-c10bb2424e80" /> |
| collapsible trigger arrow are off positioned | collapsible arrow position remain |
**Checklist**

fix(api-reference): collapsible section trigger responsiveness

---

.changeset/fuzzy-files-hide.md
packages/api-client/src/components/Server/ServerDropdown.test.ts
packages/api-client/src/components/Server/ServerDropdown.vue
packages/api-client/src/components/Server/ServerDropdownItem.vue
packages/api-client/src/store/active-entities.ts

**Problem**
currently a server cannot be deselected from the client address bar when set.
**Solution**
this pr introduces deselection capability while keeping the possibility to select back server.
| after |
| -------|
| <img width="643" alt="image" src="https://github.com/user-attachments/assets/50a9d417-0b95-49b4-90d6-98e60d80f25e" /> |
**Checklist**

feat(api-client): address bar server deselection

---

.changeset/shiny-ads-allow.md
integrations/docusaurus/src/theme.css
packages/code-highlight/src/css/markdown.css
packages/themes/src/reset.css

We have an issue with a caret showing up in Safari on `<summary>` elements. It seems like we had a more specific fix in our markdown code but this moves it to the `reset.css`.
**Checklist**

fix(themes): hide summary caret in reset

---

.changeset/mighty-stingrays-clap.md
packages/themes/src/presets/default.css

all code colors and accent colours on default theme are now p-3. I feel like I can see for the first time again
after:
before:

feat(api-reference): add p-3 color support to default scalar theme

---

.changeset/curly-plants-bow.md
packages/api-client/src/libs/create-client.ts
packages/api-client/src/views/Request/RequestRoot.test.ts
packages/api-client/src/views/Request/RequestSidebar.vue
packages/api-reference/index.html
packages/api-reference/src/blocks/hooks/useBlockProps.test.ts
packages/api-reference/src/blocks/hooks/useBlockProps.ts
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/Content/Content.vue
packages/api-reference/src/components/Content/Lazy/Loading.vue
packages/api-reference/src/components/Content/Tag/OperationsList.vue
packages/api-reference/src/components/Content/Tag/OperationsListItem.vue
packages/api-reference/src/components/Content/Tag/Tag.vue
packages/api-reference/src/components/Content/Tag/TagList.vue
packages/api-reference/src/components/Content/Tag/TagSection.vue
packages/api-reference/src/features/BaseUrl/BaseUrl.vue
packages/api-reference/src/features/Operation/Operation.vue
packages/api-reference/src/hooks/useMultipleDocuments.ts
packages/oas-utils/src/transforms/import-spec.ts

**Problem**
closes #5102
Currently, we have collection hard coded to [0] in a few places so we werent getting things like operation lists
**Solution**
With this PR we add proper multi collection(doc) support by using the slug from the selector as the uid.
To test just keep switching specs with the console open and see if there's any errors
**Checklist**

fix(api-reference): doesn’t switch the collection

---

.changeset/smooth-ways-yell.md
packages/api-client/src/views/Request/RequestSection/RequestAuth/OAuth2.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/OAuthScopesInput.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuthTab.vue

**Problem**
following the auth description introduction, information can be dense for multiple authentication. 
**Solution**
this pr is a proposal to merge description to generated label + some style fixes.
| <img width="537" alt="image" src="https://github.com/user-attachments/assets/7584beaa-c68d-4d84-9543-93978d2537ae" /> | <img width="537" alt="image" src="https://github.com/user-attachments/assets/6fe2ccde-b03b-4cfe-b5c5-125a7d7ee216" /> |
**Checklist**

fix(api-client): multiple authentication description

---

.changeset/tasty-bats-grow.md
packages/api-reference/src/components/Content/Introduction/Introduction.vue
packages/api-reference/src/components/ShowMoreButton.vue

**Problem**
currently introduction badges are lacking gap when multiple and show more button is not optically centered.
**Solution**
this pr adds gap to introduction badges:
| <img width="309" alt="image" src="https://github.com/user-attachments/assets/16ad1f82-e607-47ca-b6ef-445ec234e3a1" /> | <img width="309" alt="image" src="https://github.com/user-attachments/assets/c2a0f5b6-f0f1-4c50-b4b7-57076f6c73e0" /> |
optically correct show more content position and update style:
| <img width="309" alt="image" src="https://github.com/user-attachments/assets/0bb623eb-f595-42f1-832c-e557ea34122c" /> | <img width="309" alt="image" src="https://github.com/user-attachments/assets/5249e66d-150e-4c86-8289-734064121490" /> | …

fix(api-reference): style fixtures

---

.changeset/real-elephants-begin.md
packages/api-reference/src/features/Search/SearchButton.vue

From Thompson Reuters:
> I noticed in this release there is a border shadow around the sidebar-search input field that shows up differently in different browsers. The screenshot is on our site, but i see the same behavior on [sandbox.scalar.com](http://sandbox.scalar.com/). This line is controlled by the css attribute box-shadow.
> 
> This shows safari, chrome, and firefox from left to right.
> 
> ![image](https://github.com/user-attachments/assets/4237fdea-82e2-492d-89d9-f8f05667dc21)
I wasn't able to produce on my Mac (but it might be because of my display) this should fix it? @cameronrohani let me know if there's a reason we shouldn't do this.
**Checklist**

fix(api-references): change search button outline from shadow to border

---

.changeset/dry-seals-kick.md
.changeset/friendly-emus-remember.md
packages/api-client/src/components/CodeInput/CodeInput.test.ts
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/vitest.setup.ts
packages/api-reference/src/features/Operation/components/RequestBody.vue

**Problem**
Currently, boolean values can be null regardless of the spec
**Solution**
With this PR we only allow null when nullable is true. 
Also bonus fix added back in a lost request body description
**Checklist**

fix(api-reference): booleans incorrectly allowing null

---

.changeset/loud-donkeys-prove.md
packages/api-client/src/layouts/Modal/ApiClientModal.vue
packages/api-client/src/views/Request/RequestRoot.vue

Turns out this wasn't working in the references only in the playground. Now it works in the references.
https://github.com/user-attachments/assets/d1dcc864-482e-4b4c-982a-b851d0662014
**Checklist**

fix(api-client): focus the client modal sidebar button when modal opens

---

.changeset/famous-rules-kick.md
packages/api-client/src/libs/create-client.test.ts
packages/api-client/src/libs/create-client.ts
packages/api-client/src/store/store.ts

**Problem**
Currently, we have no testing on create-client.
**Solution**
With this PR we add  basic testing to create-client. This is just part one of a series to improve live store updates by using sync tech. Currently we just destroy the store everytime but that will soon change
**Checklist**

chore(api-client): add tests for create client

---

.changeset/itchy-lions-laugh.md
.changeset/many-cobras-promise.md
.github/workflows/ci.yml
packages/api-reference-react/src/index.ts

**Problem**
Currently, we only export the props for the component
**Solution**
With this PR we export a few of the key config types for ease of use.
Also fixed the ci cuz its broke
**Checklist**

feat(api-reference-react): re-export config types from the react integration + fix ci

---

.changeset/flat-spiders-sell.md
documentation/integrations/dotnet.md
integrations/aspnetcore/README.md
integrations/aspnetcore/package.json
integrations/aspnetcore/playground/Scalar.AspNetCore.Playground/Extensions/ServiceCollectionExtensions.cs
integrations/aspnetcore/playground/Scalar.AspNetCore.Playground/Program.cs
integrations/aspnetcore/playground/Scalar.AspNetCore.Playground/Scalar.AspNetCore.Playground.csproj
integrations/aspnetcore/src/Scalar.AspNetCore/Contract/ScalarConfiguration.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Contract/ScalarSource.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarEndpointRouteBuilderExtensions.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarOptionsExtensions.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Mapper/ScalarOptionsMapper.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Options/ScalarDocument.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Options/ScalarOptions.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Scalar.AspNetCore.csproj
integrations/aspnetcore/src/Scalar.AspNetCore/StaticAssets/scalar.aspnetcore.js
integrations/aspnetcore/src/Scalar.AspNetCore/StaticAssets/scalar.aspnetcore.test.js
integrations/aspnetcore/tests/Scalar.AspNetCore.Tests/Scalar.AspNetCore.Tests.csproj
integrations/aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarEndpointTests.cs
integrations/aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarOptionsExtensionsTests.cs
integrations/aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarOptionsMapperTests.cs

This PR adds Multiple OpenAPI documents support to the `Scalar.AspNetCore` integration. This PR is based on the following wonderful PRs:
- https://github.com/scalar/scalar/pull/5013
- https://github.com/scalar/scalar/pull/4999
- https://github.com/scalar/scalar/pull/4872
**Multiple OpenAPI documents**
Basically, this PR adds 2 new methods `AddDocument` and `AddDocuments` for adding OpenAPI documents to the Scalar API Reference configuration (One configuration, multiple sources):
```c#
string[] versions = ["v1", "v2"];
// Adds a document with a title
app.MapScalarApiReference(options => options.AddDocument("v1", "My awesome version 1"));
// Adds multiple documents
app.MapScalarApiReference(options => options.AddDocuments("v1", "v2"));
app.MapScalarApiReference(options => …
```

feat(Scalar.AspNetCore): Support Multiple OpenAPI documents

---

.changeset/short-dolphins-scream.md
packages/api-reference/package.json
packages/api-reference/src/components/Content/Content.vue
packages/api-reference/src/components/Content/Models/Models.vue
packages/api-reference/src/components/Content/Schema/Schema.vue
packages/api-reference/src/components/Content/Schema/SchemaDiscriminator.vue
packages/api-reference/src/components/Content/Schema/SchemaHeading.vue
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue
packages/api-reference/src/components/Content/Tag/TagList.vue
packages/api-reference/src/components/Section/CompactSection.vue
packages/api-reference/src/components/Section/SectionHeaderTag.vue
packages/api-reference/src/features/Operation/Operation.vue
packages/api-reference/src/features/Operation/components/OperationParameters.vue
packages/api-reference/src/features/Operation/components/OperationResponses.vue
packages/api-reference/src/features/Operation/components/ParameterList.vue
packages/api-reference/src/features/Operation/components/ParameterListItem.vue
packages/api-reference/src/features/Operation/components/RequestBody.vue
packages/api-reference/src/features/Operation/layouts/ClassicLayout.vue
packages/api-reference/src/features/Operation/layouts/ModernLayout.vue
pnpm-lock.yaml

**Problem**
currently discriminator description are duplicated, properties accordion gets duplicated.
**Solution**
this pr updates the way discriminator are displayed within api reference:
- allof are not merged
- anyof + one of are displaying a schema model dropdown
| <img width="595" alt="image" src="https://github.com/user-attachments/assets/22b4f2fc-48cd-43fa-8166-916a65f7bf61" /> | ![image](https://github.com/user-attachments/assets/e4125d27-0128-4870-a38e-c7aad9e90ec8) |
<details>
<summary>OpenAPI specification testing document</summary>
```yaml
openapi: 3.0.3
info:
title: Petstore API
version: 1.0.0
tags:
- name: pets
description: Operations related to pets
paths:
/pets/allof:
get:
summary: Get pets with allOf usage
tags:
- pets
responses: …
```

feat(api-reference): schema discriminator display

---

.github/dependabot.yml

Nobody cares about updates for tsup. Let’s just replace it with rollup soon-ish.

chore(dependabot): ignore tsup

---

.changeset/flat-spiders-sell.md

I noticed that I used a dead link into the changelog 👀. I updated the link to point to the correct file.

docs: Update link in changelog

---

.changeset/bright-tomatoes-walk.md
integrations/nestjs/playground/nestjs-api-reference-express/src/app.controller.ts

Same fix but for nest + express
**Checklist**

fix(nest.js): incorrect type import in nest.js express playground 

---

packages/api-reference/src/index.ts

**Problem**
Currently, we’re doing this in the root index of `@scalar/api-reference`:
```ts
export * from '@/stores'
export * from '@/helpers'
export * from '@/types'
export * from '@/hooks'
```
This exposes all stores, helpers, types and hooks from the package. But we want to be able to move them around, rename them, drop them or change their API. Also, tree-shaking doesn’t work well in all environments.
**Solution**
Let’s trim down the list of exports to the stuff that we’re actually importing somewhere. Ideally, we’d move most of the remaining exports to other entrypoints, but that’s for a separate PR.
**Checklist**

chore(api-reference): remove wildcard exports

---

.changeset/soft-pets-look.md
.changeset/thirty-peas-tap.md
packages/api-client-react/src/ApiClientModalProvider.tsx
packages/api-client/src/libs/create-client.test.ts
packages/api-client/src/libs/create-client.ts
packages/api-reference/src/components/Content/Introduction/Introduction.vue
packages/api-reference/src/components/Content/Tag/Tag.vue
packages/api-reference/src/features/Operation/layouts/ModernLayout.vue
packages/core/package.json
packages/types/src/api-reference/api-reference-configuration.ts

**Problem**
Currently, if you change the servers in the reference config, it will not get updated as it is not active.
**Solution**
With this PR we don't make it reactive, but instead do a quick fix of just re-creating the store whenever anything changes. This is much slower, but should be ok for now. If we run into performance issues we can bump up priority of using sync for the config.
Also exposed the `isLoading` prop to control loading of references
**Checklist**

feat(api-reference): expose isLoading in config & "fix" config reactivity

---

.changeset/nice-pugs-eat.md
examples/web/src/pages/EmbeddedApiReferencePage.vue
packages/api-reference/playground/vue/src/App.vue
packages/api-reference/playground/vue/src/components/DebugBar.vue
packages/api-reference/src/hooks/useConfig.test.ts
packages/api-reference/src/standalone/lib/html-api.ts
packages/core/README.md
packages/types/src/api-reference/api-reference-configuration.test.ts

**Problem**
Currently, there were still a few places that had the `spec` prefix.
**Solution**
With this PR, the `spec` prefix is only in some tests that we keep to ensure the backwards compatibility.
**Checklist**

chore(api-reference): remove spec prefix

---

integrations/aspnetcore/README.md
integrations/aspnetcore/docs/README.md
integrations/aspnetcore/docs/authentication.md
integrations/aspnetcore/docs/multiple-openapi-documents.md
integrations/aspnetcore/docs/multiple-scalar-api-references.md
integrations/aspnetcore/docs/scalar-vs-generators.md
integrations/aspnetcore/docs/subpath-deployment.md

We had many questions regarding about .NET, OpenAPI and Scalar. I hope that these docs help to understand everything a bit better. My plan is to gradually enhance and improve these documentation/examples.
Currently, the docs are located here `/integrations/aspnetcore/docs`. Do you know a better place for multiple related doc files?
This documentation contains:
- Scalar.AspNetCore
- Authentication
- Multiple OpenAPI Documents
- Multiple Scalar API References
- SubPath Deployment
Later, I'd like to
- enhance Authentication → Even more examples.
- add Metadata → Describing endpoints (summaries, comments etc.).
- improve the existing integration documentation by adding docs for **all** configuration options.
**Checklist**

docs(Scalar.AspNetCore): more detailed examples and explanations

---

.changeset/swift-mirrors-battle.md
packages/openapi-parser/src/utils/upgradeFromTwoToThree.test.ts
packages/openapi-parser/src/utils/upgradeFromTwoToThree.ts

**Problem**
Currently, we just ditch the `basePath` of a Swagger 2.0 document when there’s no `host`. That’s so wrong.
**Solution**
We’re keeping the lovely `basePath` with this PR here, isn’t it wonderful?
Fixes #5126 
**Checklist**

fix(openapi-parser): Swagger 2.0 `basePath` is ignored when there’s no `host`

---

.changeset/slow-cups-pull.md
packages/snippetz/src/plugins/shell/curl/curl.test.ts
packages/snippetz/src/plugins/shell/curl/curl.ts

**Problem**
See #5177
**Solution**
With this PR we’re pretty printing JSON bodies, even for multipart/form-data, because why not?
Fixes #5177
**Checklist**

fix(snippetz): shell/curl with multipart/form-data JSON body doesn’t pretty print

---

README.md

Just found micronaut-openapi, which has support for Scalar.
Let’s add it to the README.
What is Micronaut? A modern JVM-based framework.

docs: add micronoaut-openapi

---

.changeset/proud-boats-swim.md
packages/api-client/src/views/Request/libs/oauth2.ts

AWS Cognito will return 400 when authorization header is provided.
**Problem**
When using scalar with AWS Cognito for public oauth2 client, we got 400 when exchanging the code.
**Solution**
With this PR, it won't send the Authorization header when it is a public client.
**Checklist**

fix(api-client): don’t send authorization header for public client

---

.changeset/green-panthers-change.md
integrations/express/src/apiReference.ts

fixes https://github.com/scalar/scalar/issues/5199.
Commit 89d8b7504759c5bb3eae687c49b3363e8890828b as part of [1], incorrectly changed the return value type for express middleware function returned by apiReference(). Removing braces from the arrow function implementation turned its body type from "block" to "expression". In an expression body, only a single expression is specified, which becomes the implicit return value.
This commit reverts that change to restore the original return type which was consistent with express's guidelines.
Although the above change did not impact runtime execution of the middleware (express does not care about the return value type at all), it did trigger a build error on Typescript projects using @types/express 5.x for type validation.
[1] …

fix(express): @types/express@5 TypeScript error

---

.changeset/cool-points-love.md
packages/api-reference/src/features/ExampleRequest/ExampleRequest.vue
packages/api-reference/src/helpers/freeze-element.test.ts
packages/api-reference/src/helpers/freeze-element.ts

**Problem**
Currently, when you change clients, all of snippets change size and the content shifts
closes #5196
**Solution**
With this PR we "Freeze" the current element such that it doesn't move when you switch clients.
We can use this tech to improve lazy loading as well!
TO test:
- change clients and the content should not move!
**Checklist**

feat(api-reference): "Freeze" elements on page when switching clients

---

.changeset/three-doors-breathe.md
packages/api-reference/src/components/Sidebar/Sidebar.vue

**Problem**
Currently, we had some hacky old timeout code which broke tests randomly but frequently enough to be annoying.
closes #5088
**Solution**
With this PR we get rid of it and hopefully it wont break any more tests
**Checklist**

fix(api-reference): remove bad timeout code and replace with mutation observer

---

.changeset/tall-parents-care.md
documentation/configuration.md
packages/api-reference/src/hooks/useMultipleDocuments.ts
packages/types/src/api-reference/api-reference-configuration.ts

**Solution**
With this PR we add a callback which gets triggered when you select a version
**Checklist**

feat(api-reference): add callback `onDocumentSelect`

---

.cursor/rules/openapi-glossary.mdc

This PR adds a cursor rule for the OpenAPI glossary, so AI won’t ever confuse the documents and the specification and all the other stuff. :))

chore: add OpenAPI glossary cursor rule

---

.changeset/olive-pens-dance.md
packages/api-client/src/layouts/Modal/create-api-client-modal.ts
packages/api-client/src/layouts/Modal/index.ts

**Problem**
Currently the create api client modal function usage is not retrieving the layout value, resulting in desktop action accessible from the modal.
**Solution**
this pr adds the missing layout value in the create api client function.
| <img width="1386" alt="image" src="https://github.com/user-attachments/assets/1021a157-57ef-4cd9-9f8c-bc57e14cecae" /> | <img width="1386" alt="image" src="https://github.com/user-attachments/assets/e6568f75-8926-4871-a0df-d53a434e61d6" /> |
| desktop action are available in the modal (add item, shortcut, etc) | desktop actions are not available in the modal | 
**Checklist**

fix(api-client): layout modal

---

.changeset/tricky-pots-cry.md
projects/scalar-app/todesktop.json

**Problem**
We moved a few dependencies to the pnpm workspace catalog, and while we use pnpm@10 in the toDesktop cloud, we don’t push the whole monorepository there, but only the scalar-app/ folder. This breaks the build.
**Solution**
With this PR we’re ignoring the pnpm catalog dependencies in the toDesktop build cloud.
**Checklist**

fix(scalar-app): toDesktop can’t install pnpm catalog dependencies

---

.changeset/brown-owls-brush.md
integrations/nestjs/src/nestJSApiReference.ts

**Problem**
When using the NestJS integration, we expect too many attributes. We forgot to make the type Partial.
**Solution**
With this PR we add `Partial<>` and now you can freely pass any configuration while still having a nice auto-complete.
Fixes #5228
**Checklist**

fix(nestjs): configuration requires too many attributes

---

.changeset/purple-pears-eat.md
packages/api-reference/src/components/GettingStarted.vue
packages/core/vite.config.ts

**Problem**
Currently, the links on getting started point to the old locations
**Solution**
With this PR we update the links for all of the integrations.
**Checklist**

fix(api-reference): integration links on the getting started component

---

.changeset/khaki-wolves-study.md
.changeset/neat-maps-relate.md
packages/api-reference/src/components/Sidebar/SidebarElement.vue
packages/api-reference/src/hooks/useReactiveSpec.test.ts
packages/api-reference/src/hooks/useReactiveSpec.ts
packages/types/src/api-reference/api-reference-configuration.test.ts
packages/types/src/api-reference/api-reference-configuration.ts

**Problem**
Currently, we can only use sync functions as `onDocumentSelect`
**Solution**
- allow using async functions aka returning promises
- useReactiveSpec not clearing spec between document changes, switched to a ref from reactive for this
- ensure interaction observer is always disabled before opening up sections
**Checklist**

fix(api-reference): allow promise returns in onDocumentSelect

---

.changeset/neat-shrimps-arrive.md
packages/api-client/src/components/ViewLayout/ViewLayoutSection.test.ts
packages/api-client/src/components/ViewLayout/ViewLayoutSection.vue
packages/api-client/src/views/Request/RequestSection/RequestSection.test.ts
packages/api-client/src/views/Request/RequestSection/RequestSection.vue
packages/api-client/src/views/Request/RequestSection/RequestTable.vue
packages/api-client/src/views/Request/ResponseSection/ResponseSection.test.ts
packages/api-client/src/views/Request/ResponseSection/ResponseSection.vue

I need to target the api client via CSS classes :) 
this adds classes to everything I'll need to target

style(api-client): add class names for targetting client

---

.changeset/new-phones-search.md
packages/api-reference/src/features/ExampleResponses/ExampleResponses.vue

**Problem**
Currently, the response body in the references was only showing a select number of content types.
**Solution**
With this PR we will show any content type! In the future we can also extend this to use the one selected in the body dropdown.
**Checklist**

fix(api-reference): response body not showing

---

.changeset/hungry-crews-poke.md
packages/api-client/src/layouts/Modal/create-api-client-modal.ts
packages/api-client/src/libs/create-client.ts
packages/api-client/src/views/Collection/CollectionAuthentication.vue
packages/api-client/src/views/Collection/CollectionNavigation.vue
packages/api-client/src/views/Collection/CollectionSettings.vue
packages/api-client/src/views/Request/Request.vue
packages/api-client/src/views/Request/RequestRoot.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuth.vue
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/oas-utils/src/entities/spec/collection.ts
packages/oas-utils/src/migrations/v-2.5.0/migration.ts
packages/oas-utils/src/transforms/import-spec.test.ts
packages/oas-utils/src/transforms/import-spec.ts

**Problem**
Currently, in the client we can only set auth at the request level
**Solution**
With this PR we are able to set auth at the collection level. Also added a `useCollectionSecurity` flag to the collection so we can flick it on and off.
**Checklist**

feat(api-client): add auth to the collection page

---

.changeset/quick-scissors-press.md
packages/api-reference/src/components/Content/Models/Models.vue
packages/api-reference/src/components/Content/Schema/Schema.vue
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue
packages/api-reference/src/components/Content/Schema/SchemaPropertyExamples.vue
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue
packages/galaxy/src/documents/3.1.yaml

we currently don't have a copy to clipboard button for examples + it gets overwhelming when you have too many examples, so this aims to fix that :) 
I also updated an example in scalar galaxy that have multiple examples
before:
after:

feat(api-reference): copy example/examples  to clipboard

---

.changeset/heavy-tables-smoke.md
packages/api-reference/src/features/Search/useSearchIndex.ts

**Problem**
Currently, we had a watcher on a value to generate search results. .value is not responsive.
**Solution**
With this PR we move the watcher to the ref instead so its reactive.
**Checklist**

fix(api-reference): empty search results on references

---

.changeset/serious-ways-tickle.md
documentation/configuration.md
packages/api-reference/src/hooks/useMultipleDocuments.test.ts
packages/api-reference/src/hooks/useMultipleDocuments.ts
packages/types/src/api-reference/api-reference-configuration.ts

**Problem**
We support multiple configurations and a single configuration with multiple sources, but can you image: we don’t support multiple configurations *with* multiple sources. Let’s tackle this.
**Solution**
This PR adds support for multiple configurations with multiple sources. 💥 
**Checklist**

feat(api-reference): multiple configurations with multiple sources

---

.changeset/honest-rockets-rush.md
packages/openapi-parser/src/utils/upgradeFromThreeToThreeOne.test.ts
packages/openapi-parser/src/utils/upgradeFromThreeToThreeOne.ts

**Problem**
Currently, the `byte` format is ignored when upgrading from OpenAPI version `3.0.x` to `3.1.x`.
**Solution**
With this PR, the `byte` format is upgraded properly. This PR closes #5272
**Checklist**

fix(openapi-parser): migrate byte format

---

.changeset/new-baboons-cry.md
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/hooks/useNavState.test.ts
packages/api-reference/src/hooks/useNavState.ts

**Problem**
Currently, if you refresh the page while using pathRouting it does not route to the correct spot.
**Solution**
It turns out config was undefined as it is provided in `ApiReferenceLayout` so if we use `useNavState` in that component we don't get config. So we pass in config here as we are computing it above.
**Checklist**

fix(api-reference): ensure pathRouting works on initial load

---

.changeset/brown-glasses-marry.md
packages/api-reference/src/components/ApiReferenceLayout.vue

**Problem**
Currently, the open in api client button is missing because we were still looking at the old spec.url
**Solution**
With this PR we also check for config.url for the `documentUrl` which brings the button back!
**Checklist**

fix(api-reference): Open in API Client button is missing

---

.changeset/yellow-ladybugs-rhyme.md
packages/api-reference/src/components/Content/Schema/Schema.vue
packages/api-reference/src/features/Operation/components/RequestBody.vue
packages/oas-utils/src/spec-getters/get-example-from-schema.test.ts
packages/oas-utils/src/spec-getters/get-example-from-schema.ts

**Problem**
Currently, we have a hard limit on depth for circular bodies, however nothing stops it from expanding horizontally.
**Solution**
With this PR we add a cap on properties after 3 levels deep to 10 (can be adjusted as we go) in the client request body.
Added a show additional properties button as well when it has 12 properties
**Checklist**

fix(api-reference): prevent the store from crashing when we have exponential body properties

---

integrations/hono/README.md
integrations/hono/playground/index.ts

**Problem**
Currently, we’re using `/openapi.yaml` as the default URL in the Hono README. But the Zod OpenAPI documentation uses `/doc` as the default URL to expose the OpenAPI document.
**Solution**
With this PR we’re changing the examples in the README, so users have one thing less to think about.
**Checklist**

docs(hono): use /doc as the default

---

.changeset/rude-suits-roll.md
packages/api-client/src/views/Request/consts/mediaTypes.ts

**Problem**
Currently, any response of `Content-Type: application/vnd.api+json` will be parsed as a Binary file, when it should be treated as a plain text json response.
See https://sandbox.scalar.com/e/bKl1f to reproduce.
**Solution**
With this PR, we map the json api content type to the right format.
**Checklist**

feat(api-client): add support for json api mime type

---

.changeset/short-hats-grow.md
.changeset/thirty-boats-stare.md
packages/api-reference/src/components/ApiReference.vue
packages/api-reference/src/features/ExampleRequest/ExampleRequest.vue

**Problem**
Currently, the sidebar scroll listener is disabled by default. Also when we have a custom client selected, we cannot switch to the globally selected client (shell + curl by default).
**Solution**
With this PR we enable the scroll listener by default.
We also toss in a quick fix for the custom client selector.
**Checklist**

fix(api-reference): client selector and sidebar scroll listener

---

.changeset/red-pans-battle.md
packages/api-client/src/components/AddressBar/AddressBarHistory.vue
packages/api-client/src/views/Request/RequestRoot.vue

**Problem**
In #4864 we started to clone the request result, but we lost the `Blob` for binary responses. And then we couldn’t and didn't show a Download button anymore.
**Solution**
With this PR we’re improving the cloning of the request result, so we keep the `Blob`.
Fixes #5208 
Note: Restoring from the request history doesn’t work at all (and never did). We need to fix that in a separate PR.
**Checklist**

fix(api-client): doesn't show a download button anymore

---

.changeset/metal-lemons-tease.md
packages/api-client/src/libs/create-client.ts

**Problem**
Currently, auth is unselectable if we use `updateConfiguration` from the htmlApi
**Solution**
With this PR this is another bandaid, we may need that new store sooner rather than later.
A fully reactive store makes me 🤤 
**Checklist**

fix(api-reference): this should fix the unselectable auth bug

---

.changeset/tidy-flowers-pump.md
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue

fixing some very minor type stuff that's been driving me crazy
1. when there's no heading on a property there's double padding 
before:
after:
2. the delineator I used in enum's can't really be used with the fonts we have so had to just do it with CSS
before
after:
Last thing is we didn't have margin a proper between description + child attribute button so added one

fix(api-reference): fix some minor type issues with properties

---

.changeset/flat-ladybugs-explain.md
.changeset/slow-icons-share.md
integrations/hono/README.md
integrations/hono/playground/index.ts
integrations/hono/src/index.ts
integrations/hono/src/scalar.test.ts
integrations/hono/src/scalar.ts
integrations/hono/vite.config.ts

**Problem**
Currently, we’re exporting `apiReference` as the middleware for Hono.
But people refer to our solution as Scalar and when they [come from Swagger UI](https://hono.dev/examples/swagger-ui) it might be more familiar to replace swaggerUI with Scalar in your code.
**Solution**
With this PR we deprecate the ~~`apiReference`~~ export and add a `Scalar` export.
```ts
import { Hono } from 'hono'
import { Scalar } from '@scalar/hono-api-reference'
const app = new Hono()
// Use the middleware to serve the Scalar API Reference at /scalar
app.get('/scalar', Scalar({ url: '/doc' }))
export default app
```
**Checklist**

feat(hono): rename export from `apiReference` to `Scalar`

---

.changeset/nervous-penguins-bake.md
.changeset/olive-mangos-serve.md
.changeset/proud-flowers-smile.md
packages/api-client/src/components/ImportCollection/hooks/useUrlPrefetcher.ts
packages/api-client/src/libs/send-request/create-request-operation.test.ts
packages/api-client/src/libs/send-request/create-request-operation.ts
packages/api-client/src/store/import-spec.ts
packages/api-client/src/views/Request/hooks/useOpenApiWatcher.ts
packages/api-reference-editor/src/components/ApiReferenceEditor.vue
packages/api-reference/src/hooks/useReactiveSpec.ts
packages/oas-utils/src/helpers/fetch-document.test.ts
packages/oas-utils/src/helpers/fetch-document.ts
packages/oas-utils/src/helpers/fetch-spec-from-url.test.ts
packages/oas-utils/src/helpers/fetch-spec-from-url.ts
packages/oas-utils/src/helpers/fetch-with-proxy-fallback.ts
packages/oas-utils/src/helpers/index.ts
packages/oas-utils/src/helpers/redirect-to-proxy.test.ts
packages/oas-utils/src/helpers/redirect-to-proxy.ts

**Problem**
Our API reference can’t fetch OpenAPI documents from other (local) domains, if CORS isn’t set up properly (because we can’t use the remote proxy then).
**Solution**
Initially, I thought we’re just missing something in the fetching logic, turns out: Not really.  BUT two changes:
* The @scalar/api-reference fetching logic is closer to what we do for API requests.
* If the proxyUrl is relative, we’ll use it even for local domains (fixes #5258)
I used the opportunity to streamline the fetching a bit, though:
* Renamed `fetchSpecFromUrl` to `fetchDocument` (we’re talking about documents, not about the standard/specification)
* Updated comments
* Removed the isValidUrl/isRelativeUrl/whatever logic from `useReactiveSpec` and just used `fetchDocument` (to make it work the same in all …

fix(api-reference): proxy is skipped for localhost, even if the proxy is local

---

packages/api-reference/package.json
packages/api-reference/playground/components/index.html
packages/api-reference/playground/components/src/App.vue
packages/api-reference/playground/components/src/main.ts
packages/api-reference/playground/components/vite.config.ts
packages/api-reference/src/components/Content/Schema/Schema.preview.ts
packages/api-reference/src/components/Content/Schema/Schema.vue
packages/api-reference/src/components/Content/Schema/SchemaDiscriminator.vue

**Problem**
Every time we fix something for the schema rendering, we break something else. The tests we have aren’t very visual, it’s hard to miss bugs, and the Scalar Galaxy example only covers a few schema use cases.
**Solution**
This PR reinvents storybook (just a Vue component that looks for a `*.preview.ts` files and renders what it exports). This makes it easier to add examples and quickly check whether they are rendered nicely.
* Fixes #5251
* It’s showing the schema name for discriminators, when there’s one defined.
You’re wondering why we don’t use Storybook? I never got HMR working in `@scalar/api-reference`. Even after I copied the exact same setup from `@scalar/components`.
**Preview**
**Checklist**

feat(api-reference): better schema rendering

---

.changeset/chilled-beans-hug.md
packages/api-reference/src/components/ApiReference.vue
packages/api-reference/src/components/Sidebar/Sidebar.vue

Turns out this was a mistake, @cameronrohani can we confirm that the sidebar still scrolls on this PR?
**Checklist**

fix(api-reference): strange jump on initial load

---

.changeset/four-weeks-flash.md
.changeset/nice-dots-itch.md
.changeset/seven-laws-rhyme.md
packages/postman-to-openapi/src/convert.test.ts
packages/postman-to-openapi/src/convert.ts
packages/postman-to-openapi/src/helpers/itemHelpers.ts
packages/postman-to-openapi/src/helpers/postResponseScripts.ts
packages/postman-to-openapi/src/helpers/responseHelpers.ts
packages/postman-to-openapi/test/scalar-void.json
packages/postman-to-openapi/test/scalar-void.test.ts

**Problem**
Currently, we just omit Postman scripts. But what if … we import them?
Preparation for #4968.
**Solution**
With this PR we’re importing those post-response scripts!
And I’ve noticed a few things that I wanted to change in the same PR:
* `/` paths are omitted
* `/raw` paths are handled differently
* responses are just made up
* the 'default' tag is just created as a fallback (not necessary to make something up, let’s keep the data clean)
* all the tests were skipped, let’s actually run them :eyes:
**Checklist**

feat(postman-to-openapi): import post-response scripts

---

.changeset/tall-falcons-train.md
.changeset/thick-parrots-heal.md
.changeset/witty-singers-jog.md
packages/api-client/src/components/Server/ServerDropdownItem.vue
packages/api-reference/src/features/Operation/Operation.vue
packages/oas-utils/src/transforms/import-spec.test.ts
packages/oas-utils/src/transforms/import-spec.ts

**Problem**
Currently when an OpenApi document has an operation server:
- server gets displayed at the collection selector level
- server is accessible amongst any other endpoints
- operation in questions is not displaying the server by default
**Solution**
this pr is a proposal to distinguish operation from collection servers at the import level while setting an operation server when available to get displayed.
⊢ api reference server selector
| <img width="1145" alt="image" src="https://github.com/user-attachments/assets/4d23c12f-ef76-4f1c-ad04-a1f680b2c967" /> | <img width="1145" alt="image" src="https://github.com/user-attachments/assets/e993a7e3-3da5-4d48-a7ca-e396e06eae35" /> |
| any api document server displayed | only collection servers …

fix(api-reference): support server url definition per individual endpoint

---

.changeset/olive-rocks-film.md
packages/api-reference/src/features/ApiClientModal/ApiClientModal.vue

**Problem**
Currently, we may have some jumpiness on config update.
**Solution**
With this PR we disable the intersection observer in case it was causing the jumpiness.
**Checklist**

fix(api-reference): disable intersection on update

---

.changeset/slow-points-exercise.md
packages/code-highlight/src/languages/basic.ts
packages/code-highlight/src/languages/standard.ts

**Problem**
Currently, we don’t have any syntax highlighting for the (new) Dart code examples.
**Solution**
This PR adds it to the set of standard languages, that we use in @scalar/api-reference and @scalar/api-client.
Fixes #4913
**Preview**
**Checklist**

fix(api-reference): syntax highlighting doesn’t work for Dart

---

.changeset/early-guests-turn.md
packages/api-client/src/components/SideNav/SideNav.vue

**Problem**
currently the sidenav doesn't get an active state when on any pages.
**Solution**
this pr updates the sidenav active state logic. late night hotfix which might be done better.
| <img width="505" alt="image" src="https://github.com/user-attachments/assets/3a4793ac-2745-49d4-b443-ea76ea70fb47" /> | <img width="505" alt="image" src="https://github.com/user-attachments/assets/23e18985-7383-43cd-922c-f42fdfb091f2" /> |
| request sidenav state is not active | request sidenav state is active | 
**Checklist**

fix(api-client): sidenav active state

---

.changeset/weak-spies-invite.md
packages/api-reference/src/components/Content/Lazy/Loading.vue

**Problem**
Currently, we show the lazy loading fake container on every config change, we don't need to do that.
**Solution**
With this PR we only show the lazy loading on initial load.
**Checklist**

fix(api-reference-react): only lazyload once

---

.changeset/shiny-impalas-share.md
packages/api-reference/src/components/Card/Card.vue
packages/code-highlight/src/code/highlight.test.ts
packages/code-highlight/src/code/highlight.ts
packages/code-highlight/src/css/code.css
packages/components/src/components/ScalarCodeBlock/ScalarCodeBlock.stories.ts

Updates `ScalarCodeBlock` to inherit it's font size from it's parent allowing it to use different font sizes. Had to tweak how we do credentials a little bit to get it working.
https://github.com/user-attachments/assets/7f1b943f-ac51-4a0c-aa3a-4ebc7147104d
https://github.com/user-attachments/assets/267f80cf-1c75-432c-8182-b04709423582
**Checklist**

feat(code-highlight): allow ScalarCodeblock to support different font sizes

---

.changeset/wise-dodos-chew.md
packages/api-reference/index.html
packages/api-reference/src/components/Content/ClientLibraries/ClientSelector.vue
packages/api-reference/src/components/Content/Schema/Schema.vue
packages/api-reference/src/components/Content/Schema/SchemaDiscriminator.vue
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue
packages/api-reference/src/features/Operation/components/ParameterListItem.vue
packages/api-reference/src/features/Operation/components/RequestBody.vue
packages/api-reference/src/features/Search/SearchButton.vue
packages/api-reference/src/features/Search/SearchModal.vue
packages/api-reference/src/features/Search/useSearchIndex.ts
packages/components/src/components/ScalarModal/ScalarModal.vue
packages/components/src/components/ScalarSearchResults/ScalarSearchResultItem.vue

Adds a number of a11y fixes to the references search and a few smaller fixes to the rest of the references.
- Updates the search dialog to have a label and stopped the entire dialog content being used as the description for all dialogs.
- Updates the search dialog to use a combobox / aria-activedescendent pattern (reads the number of results).
- Return to the search button if the search is opened via click
- Search results need to either wrap to another line at high zoom levels
- Fixed the tab count being incorrect for the client libraries tabs, also looked into the tab order but decided to keep the order as-is since the more button is sort of a pseudo tab.
- Add unique screen reader names for the 'Show/Hide Child Attributes' buttons.
- Swapped an `<li>` for a `<div>` in the response …

fix(api-reference): references search a11y round 2 (3?)

---

.changeset/cuddly-swans-rest.md
packages/oas-utils/src/entities/spec/spec-objects.ts
packages/oas-utils/src/helpers/omit-undefined-values.test.ts
packages/oas-utils/src/helpers/omit-undefined-values.ts

**Problem**
We have this helper we use for Zod schemas, that removes undefined values from the data. But it transforms arrays to object, that’s bad.
**Solution**
With this PR it’s all good again, because now we handle Arrays and we even have tests for it.
Got this from #5341, but need this in sooner.
**Checklist**

fix(oas-utils): `omitUndefinedValues` (for Zod schemas) doesn’t handle Arrays

---

.changeset/forty-flowers-impress.md
packages/api-client/src/layouts/App/ApiClientApp.vue
packages/api-client/src/layouts/Modal/ApiClientModal.vue
packages/api-client/src/layouts/Web/ApiClientWeb.vue
packages/api-client/src/tailwind/variables.css

This was causing issues if `--scalar-background-1` was set to transparent (which it shouldn't be but we probably don't want to do this anyway).
It seems like this was [added along with the client import flow](https://github.com/scalar/scalar/commit/bd8e253c4126216fabd1a8d504f61026e2373690#diff-fda38c80e7cf76a6c78e3caf45248ede32f55bad34d29fb4517aa46260d40b47) at some point but I did some testing and the import flow works fine without it so I'm guessing it's just stale code. We probably don't want to do it this way anyway because we use the `.dark-mode` class for the contrast cards in the references meaning `html:has(.dark-mode)` applies even in light mode, we just didn't notice because it was hidden behind a background of `--scalar-color-1`  <sup>so<sup>cursed</sup></sup>.
**Checklist** …

fix(api-client): don't set html background from client

---

.changeset/olive-numbers-roll.md
packages/api-client/src/components/ImportCollection/ImportCollectionListener.vue
packages/api-client/src/components/ImportCollection/ImportNowButton.vue
packages/api-client/src/components/ImportCollection/utils/import-collection.ts
packages/api-client/src/components/ImportCollection/utils/workspace-store-is-empty.ts

**Problem**
We always show the import modal. That’s fine, but let’s make it even simpler.
**Solution**
With this PR we’re skipping the import modal, if the store is empty (just has one workspace, just has the “drafts” collection).
Makes importing even faster.
**Checklist**

feat(api-client): skip the import modal when the store is empty

---

.changeset/polite-moles-protect.md
packages/api-reference/playground/components/src/App.vue
packages/api-reference/src/components/Content/Schema/Schema.preview.ts
packages/api-reference/src/components/Content/Schema/SchemaDiscriminator.vue
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue
packages/api-reference/src/components/Content/Schema/helpers/merge-all-of-schemas.test.ts
packages/api-reference/src/components/Content/Schema/helpers/merge-all-of-schemas.ts

**Problem**
We introduced this new function to merge `allOf` schemas into one, but that didn't cover all cases.
**Solution**
With this PR we’re moving the function to a separate file, add tests and cover more uses cases (e.g. deeply nested `allOf` schemas).
Fixes #5325
**Preview**
**Checklist**

fix(api-reference): doesn’t merge deeply nested allOf schemas

---

.changeset/orange-pets-collect.md
packages/api-reference/src/components/Content/Introduction/Introduction.vue
packages/api-reference/src/hooks/useSidebar.ts

**Problem**
I think we had this already, but there’s no more "Introduction” heading in the sidebar anymore. An entry that lets you jump to the top of the page.
**Solution**
With this PR we’re adding an Introduction heading (if we have a description) to the sidebar.
**Preview**
**Checklist**

feat(api-reference): add Introduction heading to the sidebar

---

.changeset/forty-ducks-admire.md
packages/api-reference/src/components/Content/Schema/Schema.vue
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue
packages/api-reference/src/features/Operation/components/ParameterListItem.vue

**Problem**
We collapse responses in the list, super annoying.
**Solution**
With this PR we’re expanding them by default. No need to click the additional toggle to see them anymore.
**Before**
**After**
**Checklist**

feat(api-reference): directly show responses in the list

---

.changeset/angry-goats-rush.md
.changeset/cuddly-cups-pull.md
packages/api-client/src/components/ScalarAsciiArt.vue
packages/api-client/src/views/Request/RequestSidebar.vue

**Problem**
currently the getting started ascii art is rendered all the time while being hidden + gets crawled by search engines as seen below:
| currently |
| -------|
| <img width="598" alt="image" src="https://github.com/user-attachments/assets/e5ee91d9-d3dc-49bb-a409-094ec4fdf52e" /> |
| search meta description result is showing ascii |
**Solution**
this pr adds the following updates:
- displays ascii if getting started only
- adds inert html attribute to prevent content from being crawled ([see reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inert)).
**Checklist**

fix(api-client): sidebar empty getting started rendering

---

.changeset/two-dots-sneeze.md
packages/api-reference/src/components/Content/Models/Models.vue
packages/api-reference/src/components/Content/Models/ModelsAccordion.vue

**Problem**
Currently, in the Sidebar, the model schema displays the schema title first, but the main model view does not.
**Solution**
This PR updates the model view to display the schema title in the heading when available.
before:
after:
**Checklist**

feat(api-reference): show schema title in heading when available

---

.changeset/curly-tips-kick.md
packages/api-client/src/views/Request/Request.vue
packages/api-client/src/views/Request/RequestSection/RequestSection.vue
packages/api-client/src/views/Request/ResponseSection/ResponseEmpty.vue
packages/api-client/src/views/Request/ResponseSection/ResponseSection.vue

This hook is no good and deprecated, incorrect useage
**Checklist**

fix(api-client): remove instances of useActiveEntities

---

documentation/migrate/api-hub.md

**Problem**
Currently, it's unclear how to migrate from API Hub's suite of tools
**Solution**
With this PR, we add a migration guide for API Hub's Design, Portal, and Explore features
**Checklist**

docs: API Hub migration guide

---

packages/api-client/src/hooks/useResponseBody.test.ts
packages/api-client/src/hooks/useResponseBody.ts
packages/api-client/src/views/Request/ResponseSection/ResponseBody.vue
packages/api-client/src/views/Request/ResponseSection/ResponseBodyVirtual.vue

**Problem**
Currently useResponseBody is not reactive 🫨 
**Solution**
With this PR it is 
**Checklist**

fix(api-client): make useResponseBody reactive

---

packages/api-client/package.json
packages/build-tooling/src/entry.ts
packages/code-highlight/package.json
packages/components/src/scripts/typegen.ts
packages/draggable/package.json
packages/oas-utils/package.json
packages/object-utils/package.json
packages/openapi-types/package.json
packages/snippetz/package.json
packages/types/package.json
packages/use-codemirror/package.json
packages/use-hooks/package.json

**Problem**
Currently, the generated order of the export entries is different on Windows. This could be annoying as it would always generate a gitt diff.
**Solution**
With this PR the keys are sorted, so its always the same order.
**Checklist**

chore: ensure consistent order of package.json exports keys

---

.changeset/tough-pears-flash.md
packages/components/src/components/ScalarForm/ScalarForm.stories.ts
packages/components/src/components/ScalarForm/ScalarFormField.vue
packages/components/src/components/ScalarTextInput/ScalarTextInput.stories.ts
packages/components/src/components/ScalarTextInput/ScalarTextInput.test.ts
packages/components/src/components/ScalarTextInput/ScalarTextInput.vue

Adjusts the ScalarForm fields to allow changing the label component (in case you don't want to automatically tie to an input) and tweaks the layout / stories for the text input. Also adds a test.
**Checklist**

feat(components): scalar form text field improvements

---

.changeset/quiet-pans-study.md
packages/api-client/src/hooks/useClientConfig.ts
packages/api-client/src/libs/create-client.test.ts
packages/api-client/src/libs/create-client.ts
packages/api-client/src/views/Request/RequestRoot.vue
packages/api-reference/src/hooks/useConfig.ts
packages/types/src/api-reference/api-reference-configuration.ts

**Solution**
With this PR we add a new client config hook for reactive config, as well as a callback on request sent.
**Checklist**

feat(api-client): add new callback for request sent

---

.changeset/blue-starfishes-hope.md
packages/api-client/src/views/Request/RequestSection/RequestCodeExample.vue

**Problem**
Currently we hit some large codemirror perf bugs on api client cause we load BODY + SNIPPET
**Solution**
Lets not overwhelm the user and have code snippets hidden by default
**Checklist**

fix: make code snippet default closed

---

.changeset/metal-experts-explode.md
packages/api-reference/src/components/Layouts/ModernLayout.vue
playwright/tests/testApiReference.ts

It seems like at some point the defaults for the config got moved into the `ApiReferenceLayout` (which is a child of `ModernLayout`) meaning that that if `showSidebar` was undefined it didn't get defaulted to true in `ModernLayout`.
Also updated our tests so it will hopefully be harder to break it next time.
@hanspagel let me know if this seems like a good solution or if we should do something else 🫡 
**Checklist**

fix(api-reference): show sidebar if not set

---

.changeset/few-dogs-brake.md
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuthTab.vue

**Problem**
Currently, when using [apiKey security schema ](https://swagger.io/docs/specification/v3_0/authentication/api-keys/) value of the api key is displayed as plain text. API keys are considered secrets the same way passwords are, they should not be displayed as plain text.
**Solution**
With this PR I change displayed value in api key input to password type the same way it is already handled for password in basic HTTP authentication
**Checklist**

fix(api-client): mask api key value in authentication section

---

.changeset/many-pugs-study.md
packages/api-client/src/components/CommandPalette/TheCommandPalette.vue

**Problem**
currently when navigating using arrow key through the command palette, some item are not visible or skipped.
**Solution**
this pr updates the arrow key handler to take into consideration the command grouping + the sticky command menu / viewport to handle focused item display.
| <video src="https://github.com/user-attachments/assets/6612747c-7157-410f-9116-b881b2b06b32"/> | <video src="https://github.com/user-attachments/assets/9718a501-234f-4626-b1b2-fe8924ebfe8a"/> |
**Checklist**

fix(api-client): command palette arrow navigation

---

.changeset/bright-mirrors-build.md
.changeset/itchy-months-mate.md
packages/api-client/src/views/Request/RequestSection/RequestBody.test.ts
packages/api-client/src/views/Request/RequestSection/RequestBody.vue
packages/api-reference/src/features/ExampleRequest/ExampleRequest.vue

**Problem**
currently when using vendor specific content type (e.g. `application/vnd.api+json`), the type gets changed to `application/json` + the examples selector is not getting displayed as seen in #5399.
**Solution**
this pr updates the request body logic to avoid updating the content type and bring back the example selector + fix the body update on change.
| <img width="1113" alt="image" src="https://github.com/user-attachments/assets/bfcc3eaf-239a-4bc9-af32-98ed5a25395e" /> | <img width="1113" alt="image" src="https://github.com/user-attachments/assets/024fb332-125c-482f-af10-ff69e0a1def5" /> |
| unsupported vendor specific content type + no examples | vendor specific content type support + examples | 
**Checklist**
I’ve gone through the …

fix(api-client): vendor specific content type examples

---

.changeset/chilly-trainers-judge.md
packages/api-reference/src/components/DocumentSelector/DocumentSelector.vue

fix(api-reference): align document selector chevron

---

.changeset/cool-scissors-worry.md
.changeset/nasty-kangaroos-whisper.md
.changeset/tidy-deers-turn.md
packages/api-client/src/libs/send-request/create-fetch-auth.test.ts
packages/api-client/src/libs/send-request/create-request-operation.test.ts
packages/api-client/src/libs/send-request/create-request-operation.ts
packages/api-client/src/views/Request/ResponseSection/ResponseBodyStreaming.vue
packages/api-client/src/views/Request/ResponseSection/ResponseSection.vue
packages/oas-utils/src/entities/spec/requests.ts
packages/void-server/src/createVoidServer.ts
packages/void-server/src/utils/createStreamResponse.ts

**Problem**
Currently, we have no real support for streaming events.
closes #1928
**Solution**
With this PR we add:
Text streams:
Server sent events:
**Checklist**

feat(api-client): read response streams ⚡

---

.changeset/nice-rats-work.md
packages/components/src/components/ScalarSearchResults/ScalarSearchResultList.vue

Alerts when no results are found in `ScalarSearchResultsList`.
**Checklist**

fix(components): alert when no results found in search

---

.changeset/rich-mails-fetch.md
packages/api-reference/src/features/ApiClientModal/ApiClientModal.vue
packages/api-reference/src/hooks/useMultipleDocuments.ts

**Problem**
- we weren't clearing path on multi doc change when using pathRouting
- our config watcher was triggering when nothing changed, re-creating the store for no reason
**Solution**
With this PR 
- we clear the path if path routing
- added a hacky json.stringify check for diff checking
**Checklist**

fix(api-reference): some jumpiness on config "changes" and multi doc select

---

.changeset/eight-eyes-sort.md
packages/api-reference/src/components/Content/Schema/SchemaDiscriminator.vue

**Problem**
**Solution**
**Checklist**

fix(api-reference): overflow scrolling on anyOf discriminator

---

.changeset/tricky-jokes-lie.md
packages/components/src/components/ScalarSearchResults/ScalarSearchResultItem.vue

fix(components): break words when wrapping search results

---

.changeset/proud-forks-fly.md
packages/api-reference/src/features/ExampleResponses/ExampleResponse.vue
packages/mock-server/src/routes/mockAnyResponse.ts

**Problem**
Currently, we’re using `"…"` as the fallbacks for strings when we generate examples from schemas.
**Solution**
I thought I’d be smart when I built that, but a few people are confused by it, and actually, just using `"string"` seems easier to understand (it’s also what Swagger UI does).
Note: We can’t really do this for numbers, booleans and others, because we’d need to make them a string then.
**Checklist**

feat(api-reference): new string fallback for schema examples

---

.changeset/breezy-rabbits-melt.md
.changeset/kind-steaks-boil.md
packages/api-client/src/libs/send-request/create-request-operation.test.ts
packages/api-client/src/libs/send-request/create-request-operation.ts

**Problem**
closes #5437
closes #5440
Currently, my code for detecting a stream was wrong. Also we are listening for collections when pasting into codemirror.
**Solution**
With this PR
- we no longer check for paste on a `<br>` (go figure)
- the check for stream checks for the literal keyword stream, this will not cover all cases but it will prevent more false positives for now
**Checklist**

fix(api-reference): stream detection code incorrect

---

CODEOWNERS

This PR adds me as a code owner for the `Scalar.AspNetCore` integration. We attempted this in the past, but at the time, I didn't have write access.

chore(CODEOWNERS): add xC0dex as code owner for aspnetcore integration

---

.changeset/chilled-vans-join.md
.changeset/violet-kiwis-mix.md
packages/api-client/src/components/ImportCollection/ImportCollectionModal.vue
packages/api-client/src/layouts/Web/ApiClientWeb.vue

**Problem**
color mode utility classes being currently set to the body element - while background variables are scoped to them (dark | light) - do not make background variables available at the html element level (as wrapping the body one).
this is causing some background color mismatch during the closing the import collection modal transition.
**Solution**
this pr updates the import collection modal style to target the element and maintain the background.
| ![image](https://github.com/user-attachments/assets/b9b01683-81e5-4831-95ab-35821bcde8ad) | ![image](https://github.com/user-attachments/assets/0089643a-6780-48e4-849a-26e9aa8a3927) |
| background color is not set  | background color set according to theme | 
**Checklist**
I’ve gone through the …

fix(api-client): import modal transition

---

documentation/integrations/dotnet.md
integrations/aspnetcore/README.md

This PR adds documentation for legacy .NET versions that are not supported by our official `Scalar.AspNetCore` package. Specifically, I included a simple guide in the integration docs explaining how to use the HTML integration in existing .NET applications.
Additionally, I’ve added `FastEndpoints` to the list of supported OpenAPI document providers. While it uses `NSwag` under the hood, its setup differs slightly from the standard configuration.

docs(Scalar.AspNetCore): add docs for legacy .NET versions and FastEndpoints

---

.changeset/light-clouds-hide.md
packages/components/src/components/ScalarTooltip/ScalarTooltip.vue

**Problem**
currently the default text size used in the tooltip has broken and is now too big according to its context.
**Solution**
this pr adds a text size variant with a text size default.
| <img width="609" alt="image" src="https://github.com/user-attachments/assets/98625a00-b7f6-44a6-beae-5281a9b8d0cd" /> | <img width="609" alt="image" src="https://github.com/user-attachments/assets/46e1aa0c-3568-4b84-a33a-70e5da0235b8" /> |
| <img width="609" alt="image" src="https://github.com/user-attachments/assets/dfa0d21f-2882-4efe-be40-99317e3785fb" /> | <img width="609" alt="image" src="https://github.com/user-attachments/assets/3e778b41-628a-4777-a3be-271c1dd0caab" /> |
**Checklist**

fix(components): `<ScalarTooltip />` base font size

---

.changeset/brave-feet-know.md
packages/api-reference/src/components/Content/Schema/SchemaDiscriminator.vue

**Problem**
- resolved #5428
Currently:
The discriminator panel has zero padding, which doesn't look like an intentional style. 
**Solution**
In this PR, I have set the padding for level 0 to `8px`.
After:
**Checklist**

style(schema-discriminator): update padding in discriminator panel

---

packages/galaxy/playground/src/index.ts

**Problem**
Currently, https://galaxy.scalar.com/ shows the Hono custom theme. But this is our default example, that’s not really related to Hono.
**Solution**
Let’s just use the default theme.
**Checklist**

feat(galaxy): use `default` theme for playground

---

.changeset/smooth-suns-wink.md
packages/api-client/src/views/Request/libs/index.ts
packages/api-reference/package.json
packages/api-reference/src/features/ApiClientModal/ApiClientModal.vue
pnpm-lock.yaml

**Problem**
Currently, we just blindly re-create the store on any config change.
**Solution**
With this PR we only re-create the whole store when content or url changes (spec related). Otherwise we use the tools from live sync to update the store accordingly.
TODO: we can also use live sync on the spec too but just requires a bit of time which is scarce right now
**To test**
plop this into api-reference/index.html
```html
<script type="module">
const reference = Scalar.createApiReference('#app', {
url: 'https://cdn.jsdelivr.net/npm/@scalar/galaxy/dist/latest.json',
servers: [
{
url: 'https://excited-glider-18.clerk.accountsstage.dev/',
},
],
authentication: {
securitySchemes: {
bearerAuth: {
token:
'xxww',
},
},
},
})
setTimeout(() => {
reference.updateConfiguration({
url: …
```

feat(api-reference): use live sync mutator for config changes to store

---

.changeset/afraid-turtles-pull.md
.changeset/two-fireants-know.md
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/views/Request/RequestSection/RequestParams.vue
packages/api-client/src/views/Request/RequestSection/RequestPathParams.vue
packages/api-client/src/views/Request/RequestSection/RequestTable.vue
packages/api-client/src/views/Request/RequestSection/RequestTableTooltip.vue

**Problem**
currently it is not possible to quickly remove a key and value at the request table row level + long content get stripped out through scroll.
**Solution**
this pr introduces:
- row deletion capability fixes #3788
- line wrapping on long content
| <video src="https://github.com/user-attachments/assets/726381da-f9f3-44e9-9fc6-02eb0efc4252" /> | <video src="https://github.com/user-attachments/assets/f5ad15d5-e089-4287-88bd-7f2ebd448484"/>  |
| row non deletable and long content is hard to reach | row is deletable and wrapped if long content | 
**Checklist**

feat(api-client): request table row deletion and input wrapping

---

.changeset/neat-fireants-breathe.md
packages/oas-utils/src/spec-getters/get-example-from-schema.test.ts
packages/oas-utils/src/spec-getters/get-example-from-schema.ts

**Problem**
If a schema/property is flagged as deprecated, it’s still in the generated examples.
**Solution**
We can omit it from the generated examples. I’ve found this great addition here: https://github.com/GitbookIO/gitbook/pull/3085
**Checklist**

feat(api-reference): omit deprecated fields from generated examples

---

.changeset/slimy-maps-promise.md
integrations/express/package.json
integrations/express/playground/package.json
integrations/nestjs/package.json
pnpm-lock.yaml
pnpm-workspace.yaml

**Problem**
Currently, we’re still using Express 4. 🫨 
**Solution**
Let’s upgrade to the latest and greatest.
**Checklist**

chore(express): upgrade to Express 5

---

.changeset/cuddly-seahorses-heal.md
.changeset/two-eagles-kiss.md
packages/api-client/src/views/Request/libs/watch-mode.test.ts
packages/api-client/src/views/Request/libs/watch-mode.ts
packages/api-reference/src/hooks/useMultipleDocuments.ts
packages/oas-utils/src/transforms/import-spec.test.ts
packages/oas-utils/src/transforms/import-spec.ts
packages/types/src/api-reference/api-reference-configuration.ts
packages/types/src/entities/security-scheme.ts

**Problem**
Currently, authentication config was typed to any and didn't work for empty string values (falsy).
**Solution**
With this PR we add an explicit check for defined and null and fixed types.
**Checklist**

fix(api-reference): types + reactivity for auth config

---

documentation/configuration.md

**Problem**
Currently, the closing quotes for the section about plugins is not closed.
**Solution**
With this PR the closing quotes are closed

docs: end code block

---

.changeset/selfish-lemons-learn.md
integrations/aspnetcore/src/Scalar.AspNetCore/Options/Authentication/Flows/AuthorizationCodeFlow.cs

**Problem**
With the recent PR https://github.com/scalar/scalar/pull/5451 we migrated to the new authentication. I forgot to make the `Pkce` entry nullable. So the default value was set to `no`. This overwrites the extensions set in the OpenAPI document itself.
**Solution**
Now the `Pkce` property is nullable, as every auth related property should be!
**Checklist**

fix(Scalar.AspNetCore): make Pkce property nullable

---

.changeset/pink-garlics-brush.md
integrations/aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarOptionsExtensions.cs

**Problem**
Some obsolete messages refer to methods that no longer exist.
**Solution**
This PR updates the obsolete messages.
**Checklist**

fix(Scalar.AspNetCore): update obsolete messages

---

.changeset/large-bobcats-do.md
packages/api-client/src/components/DataTable/DataTableInput.vue
packages/api-client/src/views/Request/RequestSection/RequestTable.vue

**Problem**
currently when using pill in an input the padding is off.
**Solution**
this pr updates padding on input with pill element.
| <img width="642" alt="image" src="https://github.com/user-attachments/assets/7e4719f6-c0a4-4b6f-af91-efd52a807ab0" /> | <img width="642" alt="image" src="https://github.com/user-attachments/assets/a8b44c70-0046-438b-8df9-e8118cf6a318" /> |
**Checklist**

fix(api-client): request input pill

---

.changeset/sharp-coats-matter.md
packages/api-client/src/components/DataTable/DataTableInput.vue
packages/api-client/src/components/Form/Form.vue
packages/api-client/src/views/Collection/CollectionServerForm.vue
packages/api-client/src/views/Collection/CollectionServers.vue

**Problem**
currently server removal button is within a dropdown of one and long description content are not easily readable.
**Solution**
this pr extracts the deletion cta from the dropdown and update form to better handle long content.
| <img width="1100" alt="image" src="https://github.com/user-attachments/assets/b9e29902-cc53-4967-8be2-b58d262c337f" /> | <img width="1100" alt="image" src="https://github.com/user-attachments/assets/b6057855-936f-4aa0-8ee2-0685d05a9c79" /> |
**Checklist**

feat(api-client): updates collection server page style

---

packages/api-client/src/libs/send-request/create-request-operation.test.ts

**Problem**
Past me used https://void.scalar.com in the tests. https://void.scalar.com is down. Main is broken. No good.
**Solution**
Present me removed https://void.scalar.com from the tests.
**Checklist**

chore: don’t rely on void.scalar.com for tests

---

.changeset/chilly-donuts-mate.md
.changeset/hip-geckos-call.md
.changeset/sour-shirts-reflect.md
packages/api-client/src/components/CodeInput/CodeInput.test.ts
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/components/CodeInput/codeVariableWidget.ts
packages/api-client/src/components/EnvironmentSelector/EnvironmentSelector.vue
packages/api-client/src/components/SideNav/SideNav.vue
packages/api-client/src/components/Sidebar/SidebarListElement.vue
packages/api-client/src/libs/env-helpers.test.ts
packages/api-client/src/libs/env-helpers.ts
packages/api-client/src/libs/send-request/create-request-operation.ts
packages/api-client/src/libs/string-template.test.ts
packages/api-client/src/libs/string-template.ts
packages/api-client/src/store/active-entities.ts
packages/api-client/src/store/environment.ts
packages/api-client/src/views/Environment/Environment.vue
packages/api-client/src/views/Environment/EnvironmentColors.vue
packages/api-client/src/views/Environment/EnvironmentModal.vue
packages/api-client/src/views/Environment/EnvironmentVariableDropdown.vue
packages/api-client/src/views/Environment/handle-drag.ts
packages/api-client/src/views/Request/RequestSection/RequestParams.vue
packages/api-client/src/views/Request/RequestSection/RequestSection.test.ts
packages/api-client/src/views/Request/RequestSection/RequestSection.vue
packages/oas-utils/src/entities/environment/environment.ts

**Problem**
currently collection environment usage is not properly usable due to issues:
- environment selector position is overflowing once selected
- environment collection routes needs to be updated
- pill plugin lacks reactivity on environment change
- draft collection if shown in environment page
- environment selector is displaying uid instead of name
- environment collection name cannot be updated
- zod schema prevent short name usage for environment
**Solution**
this pr fixes #5384 #4349 + listed above issues +:
- updates default environment variable pill color for better accessibility
- adds icon on global variable pill
`environment selector`
| <img width="334" alt="image" src="https://github.com/user-attachments/assets/d10061de-eaba-4168-b01b- …

fix(api-client): environment collection

---

.changeset/rare-owls-look.md
.changeset/smooth-pumpkins-double.md
packages/api-reference/src/components/Content/Schema/Schema.vue
packages/api-reference/src/components/Content/Schema/SchemaDiscriminator.test.ts
packages/api-reference/src/components/Content/Schema/SchemaDiscriminator.vue
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue

**Problem**
currently when any of discriminator includes a title with value, it is not retrieved within the tab.
**Solution**
this pr adds:
- support of title value that fixes #5488 
- update schema discriminator logic that fixes #5447
- dropdown for long discriminator content usage follow up #5429
- style enhancement finalizing #795
`title`
| <img width="563" alt="image" src="https://github.com/user-attachments/assets/73aa0400-045e-453a-acbe-a1cda26ef13c" /> | <img width="563" alt="image" src="https://github.com/user-attachments/assets/738de780-b943-4bc4-984c-86dc8084da00" /> |
`deeper level`
| <img width="563" alt="image" src="https://github.com/user-attachments/assets/4a36f424-0b2b-46b5-b45f-b60eee2f58e8" /> | …

fix(api-reference): title and higher level discriminator support

---

.changeset/ten-pillows-learn.md
packages/api-client/src/views/Request/ResponseSection/ResponseLoadingOverlay.vue

**Problem**
currently when sending a request with section open the loading layer is not at the right place.
**Solution**
this pr increases z index to position loading layer over content.
| <img width="604" alt="image" src="https://github.com/user-attachments/assets/da5df832-18bc-482b-aed4-e4fca7a0f8eb" /> | <img width="604" alt="image" src="https://github.com/user-attachments/assets/ff5fdea2-5376-42d1-b917-73a86ab91e52" /> |
**Checklist**

fix(api-client): response loading layer order

---

.changeset/wet-snakes-sing.md
packages/api-client/src/components/ViewLayout/ViewLayoutSection.vue

**Problem**
currently attribute inheritance is creating class duplication along cx usage in view layout section component.
**Solution**
this pr disables attribute inheritance to fix class duplication.
| <img width="504" alt="image" src="https://github.com/user-attachments/assets/94418232-e9d5-4e00-b8f1-6638748d00ca" /> | <img width="504" alt="image" src="https://github.com/user-attachments/assets/ae17ee8c-ab43-4e81-9e2d-877150018524" /> |
**Checklist**

fix(api-client): view layout section duplicated classes

---

.changeset/tasty-bats-care.md
packages/api-client/src/components/DataTable/DataTableInput.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuthDataTableInput.vue

currently we use input type="password" to mask password credentials 
this causes browsers to trigger their password autofill's which is _generally_ intended for user passwords and not quite intended for our use cases of passwords in our data tables.
now when someone uses type="password" on password inputs it will apply change the type to text and apply the  class `scalar-password-input` which overrides the characters to be discs, giving it the effect of a password input. 
there's a better way to go about doing this that maybe @hwkr or @antlio can help me with in the future :) but we need to get this in for now 
before: 
after:

fix(api-client): mask password input but don't define it as a password

---

.changeset/fuzzy-poems-grin.md
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.test.ts
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue

**Problem**
currently only the type is displayed as property heading over schema name.
**Solution**
this pr displays schema name when available over type and fixes #5377.
| <img width="570" alt="image" src="https://github.com/user-attachments/assets/ad3c8ef6-7e43-4d0e-af18-9ed256a3aa96" /> | <img width="570" alt="image" src="https://github.com/user-attachments/assets/5d9d8684-666f-42c2-8b66-aff2b5e2ae39" /> |
**Checklist**

fix(api-reference): displays schema name in property heading

---

.changeset/dirty-seals-invite.md
packages/api-reference/src/components/Content/Content.vue

**Problem**
Currently, we cannot target the intro cards with css in case we want to hide them.
**Solution**
With this PR we add a unique class to each of the intro cards.
**Checklist**

feat(api-reference): add classes to intro cards

---

integrations/hono/README.md

**Problem**
Just added [hono-openapi](https://github.com/rhinobase/hono-openapi) as a option in the hono package for setting up OpenAPI

fix(docs): added hono-openapi in hono integration package

---

.prettierignore

During `pnpm format` I noticed that prettier also formats generated files inside `bin` and `obj` folder. We already have this rule for biome, let's add it to prettier.

chore(prettier): add aspnetcore build directories to prettierignore

---

.changeset/dirty-clocks-exist.md
.changeset/forty-months-hug.md
examples/nuxt/package.json
packages/api-client/package.json
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/components/CodeInput/index.ts
packages/api-client/src/components/ViewLayout/index.ts
packages/api-client/src/views/Request/RequestSection/RequestAuth/OAuth2.vue
packages/oas-utils/package.json
packages/oas-utils/src/helpers/security/get-schemes.test.ts
packages/oas-utils/src/helpers/security/get-schemes.ts
packages/oas-utils/src/helpers/security/has-token.test.ts
packages/oas-utils/src/helpers/security/has-token.ts
packages/oas-utils/src/helpers/security/index.ts
pnpm-lock.yaml
pnpm-workspace.yaml

**Solution**
With this PR
- export viewLayoutCollapse from api-client. I know we want to add it to components but I have another PR open for that
- export codeInput and allow additional languages
- bump zod version to match org
- add a few security scheme helpers to oas-utils
**Checklist**

feat(api-client): export viewLayoutCollapse and add some helpers

---

.changeset/poor-apricots-chew.md
packages/api-reference/src/components/Sidebar/SidebarHttpBadge.test.ts
packages/api-reference/src/components/Sidebar/SidebarHttpBadge.vue

Added HTTP method-specific CSS classes for custom styling
**Problem**
Currently, there's no possibility to customize http methods of endpoints in the sidebar. They all have to same css class.
**Solution**
With this PR I added a specific css class per http method so that they can be customized.
**Checklist**

feat(api-reference): CSS class for HTTP methods

---

.changeset/young-sloths-listen.md
packages/api-client/src/views/Request/ResponseSection/ResponseBody.vue
packages/api-client/src/views/Request/ResponseSection/ResponseSection.vue

**Solution**
With this PR we just expose the layout prop, pretty standard across our external components in client.
**Checklist**

chore(api-client): add layout prop to ResponseBody

---

.changeset/fresh-falcons-build.md
.changeset/long-needles-drop.md
.changeset/sour-ligers-confess.md
.changeset/stupid-needles-sort.md
packages/api-client/src/components/DataTable/DataTableInputSelect.vue
packages/api-reference/src/components/Content/Schema/SchemaPropertyExamples.vue
packages/api-reference/src/components/Content/Schema/helpers/formatExample.test.ts
packages/api-reference/src/components/Content/Schema/helpers/formatExample.ts
packages/api-reference/src/features/Operation/components/ParameterListItem.vue
packages/components/src/components/ScalarTooltip/ScalarTooltip.vue
packages/oas-utils/src/entities/spec/parameters.ts
packages/oas-utils/src/entities/spec/request-example.test.ts
packages/oas-utils/src/entities/spec/request-examples.ts

**Problem**
as highlighted in #5518, parameter object example / examples is not currently displayed within the reference and well supported in the client along content example support.
**Solution**
this pr fixes UI glitches and improves overall examples support.
`example support`
| <img width="604" alt="image" src="https://github.com/user-attachments/assets/a38d69f6-54fd-4df0-9e3b-ac01767552b9" /> | <img width="604" alt="image" src="https://github.com/user-attachments/assets/ffd8d3c2-75e0-4bcb-b271-1d5d2c0e74a7" /> |
tested with
<details>
<summary>OAI specification document</summary>
```yaml
openapi: 3.1.1
info:
title: Examples
version: 1.0.0
paths:
'/not-working':
get:
description: |
Demonstrates examples on the parameter object isn't shown as …
```

feat(api-reference): parameter examples improvements

---

.changeset/sour-laws-draw.md
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue

**Problem**
current usage of destructture along  `withDefaults` is unnecessary and won't apply and fire an error on build.
**Solution**
this pr updates the way default is set along destructure and remove one unused prop.
**Checklist**

fix(api-reference): schema property heading prop defaults

---

.changeset/pink-dolphins-rhyme.md
integrations/aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarEndpointRouteBuilderExtensions.cs
integrations/aspnetcore/src/Scalar.AspNetCore/StaticAssets/scalar.aspnetcore.js
integrations/aspnetcore/src/Scalar.AspNetCore/StaticAssets/scalar.aspnetcore.test.js
integrations/aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarEndpointTests.cs

**Problem**
Currently, the API Reference script is loaded as `type=module` even if we don't use any module feature here. This _may_ cause some issues in browsers. 
**Now**
This PR removes the `type=module` attribute, so the script is loaded like a default JS script.
**Checklist**

fix(Scalar.AspNetCore): improve module script loading

---

.changeset/sour-eels-whisper.md
.changeset/tame-spoons-hide.md
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/features/ApiClientModal/ApiClientModal.vue
packages/oas-utils/src/transforms/index.ts

**Problem**
Currently, we moved to diffing on config changes. However servers is an override so we want to remove the old ones and just add the new ones.
**Solution**
With this PR we remove then re-add servers on change. (we can diff this later but need to be smarter on addition)
**Checklist**

fix(api-reference): config servers change

---

.changeset/unlucky-owls-collect.md
packages/api-client/src/libs/send-request/create-request-operation.test.ts
packages/api-client/src/libs/send-request/create-request-operation.ts

**Problem**
Currently, we just checked for stream in the header to stream a response.
**Solution**
With this PR we only check for server sent events this way (with `text/event-stream`) as there's no way to reliably check for stream in the browser. ~We will add this to the [UI later.](https://github.com/scalar/scalar/issues/5574).~ [Apparently it is being added to the spec](https://github.com/OAI/OpenAPI-Specification/pull/4554)
closes #5519
closes  #2684
**Checklist**

fix(api-client): remove incorrect stream header check

---

.changeset/config.json
package.json
scripts/package.json
scripts/src/cli.ts

**Problem**
We just recently added a private package called `@scalar/scripts`, but there’s an actual [`@scalar/scripts` coming soon](https://github.com/scalar/scalar/pull/4968).
**Solution**
To avoid conflicts, this PR renames the package to `@scalar-internal/build-scripts`.
**Checklist**

chore: rename @scalar/scripts to @scalar-internal/build-scripts

---

.changeset/hot-forks-carry.md
packages/api-client/src/components/ViewLayout/ViewLayoutCollapse.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuthDataTable.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuthTab.vue
packages/api-reference/src/components/Content/ClientLibraries/ClientLibraries.vue
packages/api-reference/src/components/Content/ClientLibraries/ClientSelector.vue
packages/api-reference/src/components/Content/Content.vue
packages/api-reference/src/features/BaseUrl/BaseUrl.vue
packages/components/src/components/ScalarMarkdown/ScalarMarkdown.vue

**Problem**
currently the long authentication description are not easy to read through scroll usage.
**Solution**
this pr wraps the authentication description and displays it fully on hover.
| <img width="553" alt="image" src="https://github.com/user-attachments/assets/76963d7e-43d5-415f-bb62-d39e2e092bed" /> | <img width="537" alt="image" src="https://github.com/user-attachments/assets/50eed9be-636e-4d4b-ae77-43ea4954ae96" /> |
**Checklist**

fix(api-client): displays authentication description on hover

---

.changeset/blue-books-walk.md
documentation/integrations/dotnet.md
integrations/aspnetcore/docs/authentication.md
integrations/aspnetcore/playground/Scalar.AspNetCore.Playground/Program.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarOptionsExtensions.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Options/Authentication/ScalarAuthenticationOptions.cs
integrations/aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarOptionsExtensionsTests.cs
integrations/aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarOptionsMapperTests.cs

**Problem**
Currently, it's not possible to define multiple preferred security schemes in the .NET integration.
**Solution**
This PR adds support for it! It looks like I have totally overseen the `preferredSecurityScheme` option during the authentication refactoring.
```csharp
app.MapScalarApiReference(options => options
// before (obsolete)
.WithPreferredScheme("ApiKey")
// now
.AddPreferredSecuritySchemes("ApiKey")
// or add multiple
.AddPreferredSecuritySchemes("ApiKey", "OAuth")
// other config
.AddApiKeyAuthentication("ApiKey", apiKey =>
{
apiKey.Value = "your-api-key";
})
);
```
**Checklist**

feat(Scalar.AspNetCore): support multiple preferred security schemes

---

packages/mock-server/playground/index.ts

**Problem**
Currently, https://galaxy.scalar.com only shows the Scalar Galaxy reference. This is a great demo, but doesn’t show multi document support.
**Solution**
This PR adds a second document to show multi document support on https://galaxy.scalar.com. :)
**Checklist**

feat(mock-server): add another document to galaxy.scalar.com

---

.changeset/friendly-monkeys-double.md
packages/api-reference/src/components/Section/SectionHeader.vue
packages/themes/src/base/variables.css
packages/themes/src/presets/custom-theme-starter.css

**Solution**
this pr is updating the heading variable values in our theme package to match incoming dashboard updates. it shouldn't affect the style or make any changes to the current state of reference.
| <img width="1464" alt="image" src="https://github.com/user-attachments/assets/c2a66bb6-1bde-4cf0-af08-e30ebc502467" /> | <img width="1464" alt="image" src="https://github.com/user-attachments/assets/09569c60-0e1b-48ad-aa2b-92ab0557e034" /> |
**Checklist**

feat(themes): heading variables update

---

.changeset/chilled-apples-work.md
documentation/configuration.md
packages/api-client/src/libs/local-storage.ts
packages/api-client/src/views/Request/RequestSection/RequestAuth/OAuth2.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/OAuthScopesInput.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuth.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuthDataTable.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuthTab.vue
packages/api-client/src/views/Request/RequestSection/helpers/update-scheme.test.ts
packages/api-client/src/views/Request/RequestSection/helpers/update-scheme.ts
packages/api-reference/index.html
packages/api-reference/src/components/Content/Content.vue
packages/types/src/api-reference/api-reference-configuration.ts

**Problem**
Currently, we do not save auth in references. Users must enter it everytime if they refresh.
**Solution**
- added auth persistance for security schemes + selection
- updated docs with all missing properties including the new persist auth
closes #5320
closes #5598
closes #4704
**Checklist**

feat(api-reference): persist auth in local storage

---

.changeset/ten-stingrays-exercise.md
.changeset/wise-pans-run.md
packages/api-client/src/components/ViewLayout/ViewLayoutSection.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuthDataTable.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuthTab.vue
packages/api-client/src/views/Request/RequestSection/RequestSection.vue
packages/api-client/src/views/Request/RequestSidebar.vue

**Problem**
currently when searching and navigating through the request navigation search, no visual hint is provided while the navigation is working.
**Solution**
this pr updates the prop usage for the component + enhances the border on the request section (for one last time).
`sidebar search`
| <img width="612" alt="image" src="https://github.com/user-attachments/assets/6029c5aa-b1ae-49ed-8b62-6420ed8840a7" /> | <img width="612" alt="image" src="https://github.com/user-attachments/assets/00a50686-b63e-4229-ab74-3209b8b62b3b" /> |
| missing visual hint on selected item | selected item is highlighted | 
`request section`
| <img width="612" alt="image" src="https://github.com/user-attachments/assets/325156b9-c19b-4ddd …

fix(api-client): request sidebar search visual hint

---

integrations/nuxt/README.md

Caught a couple of typos while reading the readme

docs(nuxt): fix typos in README

---

.changeset/six-rice-rest.md
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.test.ts
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue

**Problem**
currently setting `null` of an empty value doesn't get displayed in api reference property heading.
**Solution**
this pr displays `null` or empty value set in property heading.
| <img width="559" alt="image" src="https://github.com/user-attachments/assets/737cb213-1976-40ff-8a8b-4cb24e14033c" /> | <img width="559" alt="image" src="https://github.com/user-attachments/assets/52ce1090-3d6f-4479-92fd-d6116e4513a9" /> |
| null value doesn't get rendered | null value get rendered | 
**Checklist**

fix(api-reference): property heading null and empty value

---

.changeset/funny-toys-peel.md
packages/api-client/src/libs/send-request/decode-buffer.ts
packages/api-client/src/views/Request/ResponseSection/ResponseBody.vue
packages/api-client/src/views/Request/ResponseSection/ResponseBodyDownload.vue
packages/api-client/src/views/Request/consts/mediaTypes.test.ts
packages/api-client/src/views/Request/consts/mediaTypes.ts

This PR introduces fallback support for MIME types that end in `+json`, which are not explicitly listed in the `mediaTypes` map. These types now correctly return a default JSON configuration via the `getMediaTypeConfig` function.
closes #5586

feat(api-client): add fallback handling for +json MIME types

---

.changeset/dull-glasses-fix.md
packages/api-client/src/components/CodeInput/CodeInput.vue
packages/api-client/src/components/DataTable/DataTable.vue
packages/api-client/src/components/EnvironmentSelector/EnvironmentSelector.vue
packages/api-client/src/views/Collection/CollectionAuthentication.vue
packages/api-client/src/views/Collection/CollectionEnvironment.vue
packages/api-client/src/views/Collection/CollectionNavigation.vue
packages/api-client/src/views/Collection/CollectionServers.vue
packages/api-client/src/views/Collection/components/EnvironmentForm.vue
packages/api-client/src/views/Environment/EnvironmentModal.vue

**Solution**
this pr adds the collection environment page in order to allow user to set their environment variables directly from at the collection level.
| after |
|------|
| <img width="1465" alt="image" src="https://github.com/user-attachments/assets/3f95cb92-939a-4950-97ba-25b0833aa313" /> |
**Test**
<table>
<tbody>
<tr>
<td>
#
</td>
<td>
description
</td>
<td>preview</td>
</tr>
<tr>
<td valign="top">1</td>
<td valign="top" width="40%">Import <a href="https://cdn.jsdelivr.net/npm/@scalar/galaxy/dist/latest.yaml">Scalar Galaxy Document</a></td>
<td ><img width="520" alt="image" src="https://github.com/user-attachments/assets/2395f7b3-4a54-4bf4-b725-c77aaf1b84be" /></td>
</tr>
<tr>
<td valign="top">2</td>
<td valign="top" width="40%">Select <code>Environment</code></td>
<td><img …

feat(api-client): collection environment page

---

.changeset/fast-feet-occur.md
packages/api-reference/src/components/Content/Schema/Schema.preview.ts
packages/api-reference/src/components/Content/Schema/Schema.vue
packages/api-reference/src/components/Content/Schema/SchemaDiscriminator.test.ts
packages/api-reference/src/components/Content/Schema/SchemaDiscriminator.vue
packages/api-reference/src/components/Content/Schema/SchemaProperty.test.ts
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue

Fixes some issues with the schema discriminators and updates the UX to always render a dropdown (based on @cameronrohani's suggestion).
Most of the issues seem to be coming from whether or not a `type` is set at the top level for a `oneOf` (or similar) discriminator. I did my best to do what I considered a reasonable job of rendering the content with or without a type set but it's very possible we'll want to tweak it in the future based on folks actual usage.
(Renders the discriminator block twice)
https://github.com/user-attachments/assets/21858e3f-44ee-4855-abfa-027881fe2d42
https://github.com/user-attachments/assets/b34b1332-be75-4fb2-ad4d-5b662b002474
**Checklist**

fix(api-reference): improve handling of schema discriminators

---

examples/sveltekit/package.json
packages/react-renderer/package.json
pnpm-lock.yaml

**Problem**
When running pnpm install, there’s an error in the console:
> SyntaxError: The requested module 'vite' does not provide an export named 'defaultClientConditions'
See https://github.com/sveltejs/vite-plugin-svelte/issues/1048
**Solution**
This PR downgrades the Vite Svelte plugin.
Fixes #5579
**Checklist**

fix(sveltekit): vite does not provide export defaultClientConditions

---

.changeset/empty-plants-own.md
.github/workflows/ci.yml
integrations/aspnetcore/package.json
integrations/aspnetcore/src/Scalar.AspNetCore/Extensions/HttpContextAcceptEncodingCheckExtensions.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarEndpointRouteBuilderExtensions.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Scalar.AspNetCore.csproj
integrations/aspnetcore/tests/Scalar.AspNetCore.Tests/Scalar.AspNetCore.Tests.csproj
integrations/aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarEndpointTests.cs

**Problem**
Currently, the size of `Scalar.AspNetCore.dll` is about 3000KB. The reason why the file is so large is that the embedded resources are relatively large.
**Solution**
Using gzip to compress the `StaticAssets/*` at build time. And decompress it before response it.
This change can compress the size of the`Scalar.AspNetCore.dll` from 3000KB to 1000KB.
Closes #5604
**Checklist**

refactor(Scalar.AspNetCore): compress embedded resource to reduce the Scalar.AspNetCore.dll size

---

.changeset/spotty-chefs-pay.md
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue

Wraps really long property titles so they don't overflow their box.
**Checklist**

fix(api-reference): handle really long property titles

---

.changeset/thin-flowers-fold.md
integrations/nuxt/src/runtime/components/ScalarApiReference.vue

**Problem**
Currently, the component uses `$fetch`, using this in the script setup causes it to fetch twice (server and client), using `useFetch` solve this problem by ensuring that if something is fetched on server, the data is forwarded to the client in the payload.
**Solution**
With this PR we benefit from SSR with `useFetch`
References:
https://nuxt.com/docs/api/composables/use-fetch
https://nuxt.com/docs/getting-started/data-fetching#the-need-for-usefetch-and-useasyncdata
**Checklist**

perf(nuxt): replace $fetch with useFetch in component script setup

---

.changeset/violet-pets-work.md
packages/api-reference/src/components/Content/Schema/helpers/merge-all-of-schemas.ts

**Problem**
currently when having an infinite all of ref usage, the maximum call stack size exceeded error is thrown.
**Solution**
this pr sets a max depth to the number of all of schema merge capacity to prevent the error and maintain the properties getting displayed and fixes #5628.
| <img width="1177" alt="image" src="https://github.com/user-attachments/assets/3cd09dbe-a067-45b2-a301-41cce37555e8" /> | <img width="1177" alt="image" src="https://github.com/user-attachments/assets/0a2dc60d-b002-4b7a-b400-b958388b2949" /> |
**Checklist**

fix(api-reference): all of schema max depth merging

---

.changeset/rotten-paws-buy.md
packages/api-reference/src/components/MobileHeader.vue

We had the truncation set up but the mobile header width wasn't being restricted properly
**Checklist**

fix(api-reference): restrict mobile header width

---

.changeset/fifty-ducks-carry.md
packages/api-reference/src/features/Operation/components/ParameterListItem.vue
packages/api-reference/src/features/Operation/hooks/useResponses.ts

**Problem**
If a Swagger 2.0 document has a schema attached to a response, it’s not rendered in the response list:
**Solution**
Note: OpenAPI 3.x document have a different structure, but until we have an upgraded document here, we can just pass the schema attribute. Easy patch.
With this PR, we’re showing the schema in the list:
**Checklist**

feat(api-reference): show responses schema in the list

---

.changeset/dull-tigers-count.md
integrations/nuxt/playground/layouts/default.vue
integrations/nuxt/playground/nuxt.config.ts
integrations/nuxt/playground/pages/index.vue
integrations/nuxt/src/module.ts
integrations/nuxt/src/runtime/pages/ScalarPage.vue

Fixes #5018
**Problem**
Currently, the Scalar page inherits the default Nuxt layout.
**Solution**
This PR turns off the layout, leaving all the styling to Scalar.
Reference: https://nuxt.com/docs/api/utils/define-page-meta#defining-layout
**Checklist**

fix(nuxt): don’t use default layout

---

.changeset/quick-wombats-fly.md
packages/components/src/components/ScalarSearchResults/ScalarSearchResultItem.vue
packages/components/src/components/ScalarSearchResults/ScalarSearchResultList.vue

Semantically it makes more sense for this to be an `<a>` tag and we're managing the aria semantics already with the `role="option"`.
Fixes #5589
**Checklist**

fix(components): set search result item to use an anchor tag

---

.changeset/real-buckets-destroy.md
packages/api-reference/src/components/Anchor/Anchor.vue
packages/api-reference/src/hooks/useNavState.test.ts
packages/api-reference/src/hooks/useNavState.ts

**Problem**
Currently, we combine the path and hash when we hit the copy button
**Solution**
With this PR we check for path routing then correctly copy the path or hash
closes #5638
**Checklist**

fix(api-reference): copy path without hash when pathRouting is enabled

---

.changeset/breezy-worms-wait.md
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue

**Problem**
currently the model name is not showing up when used within schema property child.
**Solution**
this pr adds missing schemas to schema property, fixes #5377.
| <img width="581" alt="image" src="https://github.com/user-attachments/assets/14af852f-9541-435d-a42f-3311c394720b" /> | <img width="581" alt="image" src="https://github.com/user-attachments/assets/fdb6361a-62aa-4b40-b217-113c7834ef71" /> |
| array is displayed instead of model name | model get displayed | 
**Checklist**

fix(api-reference): schema property child model name in type

---

.changeset/dirty-chefs-type.md
packages/api-client/src/libs/send-request/index.ts

**Problem**
Currently, we don't export decodeBuffer
**Solution**
With this PR we export decodeBuffer
**Checklist**

chore(api-client): export decodeBuffer

---

.changeset/olive-rivers-dream.md
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.test.ts
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue
packages/api-reference/src/features/Operation/components/ParameterListItem.vue

**Problem**
currently setting a const within an array is not getting displayed in the api reference.
**Solution**
this pr updates the property heading support of const to get it displayed and fixes #5648.
| <img width="589" alt="image" src="https://github.com/user-attachments/assets/03174e30-c48f-4a0b-be21-b5d8dd00b47d" /> | <img width="589" alt="image" src="https://github.com/user-attachments/assets/fb40ea99-daa3-4783-b28f-7e87eb4cded4" /> |
**Checklist**

fix(api-reference): display array item const

---

.changeset/lazy-roses-wave.md
integrations/nuxt/package.json
integrations/nuxt/src/runtime/components/ScalarApiReference.vue
pnpm-lock.yaml

**Problem**
Currently, the nuxt module does not save the user's color mode preference when using the toggle switch, it is tied to starting with the one defined in the config.
**Solution**
With this PR we'll add support for saving the user's color mode preference and handle their states.
I look forward to your feedback.
**Checklist**

feat(nuxt): SSR-friendly color mode preference implementation

---

integrations/aspnetcore/src/Scalar.AspNetCore/Scalar.AspNetCore.csproj
integrations/aspnetcore/tests/Scalar.AspNetCore.Microsoft.Tests/Scalar.AspNetCore.Microsoft.Tests.csproj
integrations/aspnetcore/tests/Scalar.AspNetCore.Swashbuckle.Tests/Scalar.AspNetCore.Swashbuckle.Tests.csproj
integrations/aspnetcore/tests/Scalar.AspNetCore.Tests/Scalar.AspNetCore.Tests.csproj

This PR bumps some dependencies to the latest and greatest version and also removes an unused `coverlet.collector` test dependency.

chore(Scalar.AspNetCore): bump dependencies

---

integrations/aspnetcore/.editorconfig
integrations/aspnetcore/Scalar.AspNetCore.slnx
integrations/aspnetcore/src/Directory.Build.props
integrations/aspnetcore/tests/Directory.Build.props
integrations/aspnetcore/tests/Directory.Packages.props
integrations/aspnetcore/tests/Scalar.AspNetCore.Microsoft.Tests/Scalar.AspNetCore.Microsoft.Tests.csproj
integrations/aspnetcore/tests/Scalar.AspNetCore.Swashbuckle.Tests/Scalar.AspNetCore.Swashbuckle.Tests.csproj
integrations/aspnetcore/tests/Scalar.AspNetCore.Tests/Scalar.AspNetCore.Tests.csproj

Another maintenance PR 🛠️
This PR enables the `ManagePackageVersionsCentrally` feature for the .NET test projects. This simplifies the package management.

chore(Scalar.AspNetCore): use centralized package management

---

.changeset/brave-eagles-invent.md
integrations/hono/README.md
integrations/hono/src/scalar.test.ts
integrations/hono/src/scalar.ts

This PR introduces a flexible middleware for `hono` that accepts dynamic configuration as either a synchronous or asynchronous function with hono context, which is useful in runtimes like [Cloudflare Workers](https://hono.dev/docs/getting-started/cloudflare-workers#bindings) where environment values can be accessed via `c.env`
**Checklist**

feat(hono): support for dynamic configuration

---

.changeset/forty-toes-build.md
packages/api-client/src/libs/send-request/create-fetch-query-params.test.ts
packages/api-client/src/libs/send-request/create-fetch-query-params.ts
packages/api-client/src/libs/send-request/create-request-operation.ts
packages/oas-utils/src/entities/spec/parameters.test.ts
packages/oas-utils/src/entities/spec/parameters.ts

**Problem**
Per #4232, the API client only has rudimentary support for array query params and can only correctly handle `style: 'form'` and `explode: true`. Unexploded array params are quite common, and though it would eventually be nice to see [all styles](https://spec.openapis.org/oas/v3.1.1.html#style-values) supported in paths, headers, queries, and cookies, this seems like a good start.
**Solution**
This patch updates `createFetchQueryParams` to take in an additional optional`Request` object, and uses that to locate the schema corresponding to each param to be serialized. If the schema has the `explode` property set to `false` (the default is `true`) then the parameters are serialized as CSV. Otherwise, the existing behavior of serializing the same key multiple times is used.
There …

fix(api-client): support unexploded array query parameters

---

.changeset/curvy-onions-thank.md
packages/api-reference-react/package.json

**Problem**
Currently, attempting to import newer versions of `api-reference-react` into commonJS projects fails with:
`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /node_modules/@scalar/api-reference-react/package.json`
Previously this was addressed in https://github.com/scalar/scalar/pull/3405 for other packages by adding a `default` export.
**Solution**
With this PR a default export is added in a similar fashion for `api-reference-react`.
**Checklist**

chore: add `default` to `api-reference-react` package.json export field

---

.changeset/smart-ghosts-study.md
packages/api-client/src/components/Server/ServerVariablesForm.vue
packages/api-reference/src/features/BaseUrl/BaseUrl.vue

**Problem**
currently on reference border are missing from the server variable form.
**Solution**
this pr sets the missing style for server variable form when using reference layout.
| <img width="598" alt="image" src="https://github.com/user-attachments/assets/e1785fc5-2237-4f5c-8e6d-1bd0198c3708" /> | <img width="598" alt="image" src="https://github.com/user-attachments/assets/3a989a8d-5053-4952-9f69-30ba3524bba8" /> |
| form border are missing | form border gets displayed | 
**Checklist**

fix(api-client): server variable form border

---

.changeset/eight-pianos-fly.md
documentation/configuration.md
documentation/integrations/dotnet.md
integrations/aspnetcore/docs/authentication.md
integrations/aspnetcore/src/Scalar.AspNetCore/Contract/ScalarConfiguration.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarOptionsExtensions.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Mapper/ScalarOptionsMapper.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Options/ScalarOptions.cs
integrations/aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarOptionsExtensionsTests.cs
integrations/aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarOptionsMapperTests.cs

**Problem**
Currently, the option `persistAuth` is not part of the `Scalar.AspNetCore` integration.
**Solution**
Now it is 😎!
**Checklist**

feat(Scalar.AspNetCore): add support for persistent authentication state

---

.changeset/olive-ravens-study.md
integrations/nextjs/package.json

**Problem**
Currently, our CI broke on next
**Solution**
With this PR we manually bump the package version, may need to do this for others as well
**Checklist**

chore(nextjs-api-reference): bump version

---

.changeset/dirty-ants-own.md
packages/openapi-parser/src/utils/upgradeFromTwoToThree.ts

Taken from #5529
**Problem**
If you pass something that isn’t an object to the Swagger upgrade utility, it’s failing (swagger of undefined).
**Solution**
This PR adds a check whether we deal with an object.
Same for the OpenAPI 3.0 -> 3.1 upgrade.
**Checklist**

fix(openapi-parser): Swagger upgrade fails for non-objects

---

.changeset/fuzzy-camels-buy.md
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuthDataTable.vue
packages/api-reference/src/components/Content/Content.vue

**Problem**
follow up of #5693 as there is some missing element and enhancement opportunities.
**Solution**
this pr updates the introduction card and auth component style.
`auth`
| <img width="1463" alt="image" src="https://github.com/user-attachments/assets/882221a7-0619-4982-bf52-adfd45fac17e" /> | <img width="1463" alt="image" src="https://github.com/user-attachments/assets/113a8ddd-2388-4332-b85b-1e87cf6c2019" /> |
| missing empty state border | empty state border displayed | 
`responsive`
| <img width="825" alt="image" src="https://github.com/user-attachments/assets/f6cb4322-81f7-4e2f-a302-34d9148a9d7a" /> | <img width="825" alt="image" src="https://github.com/user-attachments/assets/dcf09747-c72f-46e0-af3c-c890 …

fix(api-reference): introduction card auth style

---

.changeset/fuzzy-scissors-yawn.md
.changeset/three-cherries-hammer.md
packages/api-client/src/components/Server/ServerSelector.vue
packages/api-reference/src/components/Content/Introduction/Introduction.vue

**Solution**
this pr updates the introduction card style to bring back previous alignment of selector with content + fix overflowing issue with long server content.
| <img width="1464" alt="image" src="https://github.com/user-attachments/assets/7ce0155a-ddf2-4130-8ce4-55458ea2264a" /> | <img width="1464" alt="image" src="https://github.com/user-attachments/assets/94c8544a-4d93-4259-98dc-2bb0bf7d1be7" /> |
| server selector aligned with description | server selector aligned with title baseline |
**Checklist**

fix(api-reference): introduction component alignment

---

.changeset/old-boxes-heal.md
integrations/aspnetcore/src/Directory.Build.props

This PR removes the deprecated license URL property. This is some preparation for the prefix reservation.

chore(Scalar.AspNetCore): remove obsolete license URL property

---

.changeset/grumpy-meals-warn.md
.changeset/many-scissors-relax.md
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.test.ts
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue

**Problem**
currently schema name of type object are not retrieved in the reference property level.
**Solution**
this pr adds a schema name function to handle both array and object type schema name retrieval and fixes #5711 .
| <img width="825" alt="image" src="https://github.com/user-attachments/assets/8370df6d-7bb0-4743-81a7-ab80ba339bfa" /> | <img width="825" alt="image" src="https://github.com/user-attachments/assets/71f6fd62-c6a8-4216-9d6d-21ff1a397536" /> |
| only type object displayed | type object and model schema name displayed |
**Checklist**

fix(api-reference): sets schema name property heading

---

.changeset/lovely-onions-peel.md
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.test.ts
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue

**Solution**
following up with #5713 type were both handled the same way, this pr updates the logic to add array suffix accordingly.
| <img width="882" alt="image" src="https://github.com/user-attachments/assets/0727ae62-846b-42d8-99e4-f5afab371b71" /> | <img width="882" alt="image" src="https://github.com/user-attachments/assets/88badc91-350f-4afc-9f17-58858d143916" /> |
**Checklist**

fix(api-reference): schema property heading type

---

cloudbuild.yaml
packages/galaxy/Dockerfile
tooling/base-docker-builder/.dockerignore
tooling/base-docker-builder/Dockerfile

**Problem**
We previously got rid of cloud build steps for the mock server, but it's really not an ideal flow for galaxy since we want it to be as up-to-date as possible. 
**Solution**
Adds the cloud build config only for the mock server, and I'll setup everything else on GCP for this 👍 
Fixes #5691
**Checklist**

ci(galaxy): deploy galaxy.scalar.com

---

scalar.config.json

Looks like this file was renamed (by me).
Before: The preview didn’t work.
After: It works!!
`npx @scalar/cli project preview scalar.config.json`

docs: file not found

---

cloudbuild.json

**Problem**
Cloudbuild doesn't support std 8gb, just bumping it
**Solution**
Bump machine type
**Checklist**

chore: update cloudbuild machine type

---

.changeset/yellow-games-own.md
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.test.ts
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue

**Problem**
currently schema references name does not get displayed in the property heading.
**Solution**
this pr update schema property heading component logic and fixes #5552.
| <img width="575" alt="image" src="https://github.com/user-attachments/assets/a84c170c-89c3-438a-a39a-0b201a8f8cf6" /> | <img width="575" alt="image" src="https://github.com/user-attachments/assets/53830348-6f57-453b-975a-9f3497c91da5" /> |
**Checklist**

fix(api-reference): schema references name in property heading

---

.changeset/wise-pants-play.md
packages/api-reference/src/components/Content/Schema/SchemaComposition.test.ts
packages/api-reference/src/components/Content/Schema/SchemaComposition.vue
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue

**Problem**
following recent refactoring some style got lost and also some properties value fallback is not happening anymore.
**Solution**
this pr updates the schema composition style along displaying value in some cases.
| <img width="1086" alt="image" src="https://github.com/user-attachments/assets/4a6bd3e6-9865-4e34-a9e1-c690a818b633" /> | <img width="1086" alt="image" src="https://github.com/user-attachments/assets/c8cb416d-9cfb-4d3f-b556-9bc014aa8d2a" /> |
**Checklist**

fix(api-reference): schema composition style and value

---

packages/api-reference/README.md

Just updated the README a bit. :) Less, but better, basically copied what we had in other places already.

docs: update the @scalar/api-reference README

---

.changeset/eight-gorillas-learn.md
.changeset/neat-lions-check.md
packages/api-reference/src/components/Content/Schema/Schema.vue
packages/api-reference/src/components/Content/Schema/SchemaDiscriminator.vue
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue
packages/api-reference/src/components/Content/Schema/helpers/schema-discriminator.test.ts
packages/api-reference/src/components/Content/Schema/helpers/schema-discriminator.ts

**Problem**
currently in discriminator presence reference is not retrieving mapping nor resolving schemas in its ui.
**Solution**
this pr introduces schema discriminator in order to be able to select schema accordingly and fixes #795 .
| after |
|------|
| <img width="1464" alt="image" src="https://github.com/user-attachments/assets/b31d894d-f905-446f-9555-35b2f1d49f0c" /> |
**Test**
[Open API spec doc](https://sandbox.scalar.com/files/FRNqy/openapi.yaml)
**Checklist**

feat(api-reference): discriminator support

---

.changeset/angry-icons-applaud.md
packages/api-client/src/views/Components/CodeSnippet/helpers/convert-to-har-request.ts
packages/oas-utils/src/entities/spec/request-example.test.ts
packages/oas-utils/src/entities/spec/request-examples.ts

**Problem**
Currently, when building code examples for multipart requests, `Content-Type: multipart/form-data` header is added to the request. It is wrong behavior, because the correct header should contain **required** parameter `boundary` as per https://datatracker.ietf.org/doc/html/rfc2046#section-5.1.1. Often this value is desired by the HTTP client libraries because boundary should not be contained inside any of the parts.
I found out that if one explicitly passes header without boundary, both Python (requests) and curl do not overwrite the header and thus send malformed requests.
**Solution**
With this PR, header is removed.
**Checklist**

fix(oas-utils): do not add content-type for multipart requests

---

.changeset/early-bananas-punch.md
packages/api-reference/src/components/Content/Schema/Schema.vue

**Problem**
recent updates increased single property level but now hides first level object content in compact elements.
**Solution**
this pr removes the added level incrementation:
| <img width="1470" alt="image" src="https://github.com/user-attachments/assets/563bfc94-087f-4ff4-b4a8-238514e7d533" /> | <img width="1470" alt="image" src="https://github.com/user-attachments/assets/911a0a6e-78d2-4017-8f20-c5d2a3e449b7" /> |
**Checklist**

fix(api-reference): decreases single property schema level

---

.changeset/cool-ants-thank.md
packages/api-reference/vite.standalone.config.ts

fix(api-reference): add tailwind plugin to standalone vite config

---

.changeset/calm-pens-sneeze.md
packages/build-tooling/src/esbuild/build.ts

This PR updates the `entryPoints` configuration for the `esbuild` build process to ensure that test and spec files (`.test.ts`, `.spec.ts`, `.test.js`, `.spec.js`) are excluded from the final bundle.

fix(build-tooling): exclude test files from esbuild entry points

---

.changeset/cold-camels-smell.md
documentation/integrations/dotnet.md
integrations/aspnetcore/src/Scalar.AspNetCore.Microsoft/Extension/OpenApiOptionsExtensions.cs
integrations/aspnetcore/src/Scalar.AspNetCore.Microsoft/Transformers/CodeSampleOpenApiOperationTransformer.cs
integrations/aspnetcore/src/Scalar.AspNetCore.Swashbuckle/Extensions/SwaggerGenOptionsExtensions.cs
integrations/aspnetcore/src/Scalar.AspNetCore.Swashbuckle/Filters/CodeSampleDocumentFilter.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Attributes/CodeSampleAttribute.cs
integrations/aspnetcore/src/Scalar.AspNetCore/ExtensionKeys.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Extensions/EndpointConventionBuilderExtensions.cs
integrations/aspnetcore/tests/Scalar.AspNetCore.Microsoft.Tests/CodeSampleTransformerTests.cs
integrations/aspnetcore/tests/Scalar.AspNetCore.Swashbuckle.Tests/CodeSampleFilterTests.cs

This PR adds a new `[CodeSample]` attribute and one extension `CodeSample()` method to the `Scalar.AspNetCore` package to support custom code samples. The OpenAPI generator extensions are also updated to make use of the new attribute and extension method.
I also updated the related documentation to be easier to follow.
Usage:
```csharp
// Extension methods
app.MapPost("/orders", CreateOrder)
.CodeSample("fetch('/orders', { method: 'POST' })", ScalarTarget.JavaScript, "Create Order")
.CodeSample("curl -X POST /orders", ScalarTarget.Shell, "Create Order with cURL")
// Attribute
[CodeSample("fetch('/products').then(r => r.json())", ScalarTarget.JavaScript)]
public IActionResult GetProducts() { }
```
What do you think about the name `CodeSample`?
**Checklist**

feat(Scalar.AspNetCore): add support for code samples

---

.changeset/light-spoons-warn.md
packages/api-reference/src/components/Content/Schema/Schema.vue

**Problem**
up to today description is not displayed in compact (within tag) schema in order to prevent duplication in allof usage. this however is not the most optimal approach as it prevents any description from being displayed.
**Solution**
this pr extracts the schema description display handling and update the logic in order to only hide level 0 description as it corresponds to allof schema merging. fixes #5739 #5768 #5495 #5338
| <img width="1116" alt="image" src="https://github.com/user-attachments/assets/e38ad3af-141e-4d42-9ce5-520d62121aa6" /> | <img width="1116" alt="image" src="https://github.com/user-attachments/assets/2730e1c2-613c-494e-8b39-65696cc73acd" /> |
**Checklist**

fix(api-reference): description on properties

---

.changeset/bright-rocks-melt.md
packages/api-reference/src/components/Content/Models/Models.vue
packages/api-reference/src/components/Content/Schema/Schema.vue
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.test.ts
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue

**Problem**
current logic for schema property heading is subject to value mismatch in some case which cause wrong property name being displayed. 
**Solution**
this pr updates the schema property heading logic and introduce a `hideModelNames` prop to differentiate data displayed between parameter and model. fixes #5737 
| <img width="1116" alt="image" src="https://github.com/user-attachments/assets/b273cdb8-4ce7-4e92-9581-440ca4e0ec75" /> | <img width="1116" alt="image" src="https://github.com/user-attachments/assets/c904e26a-4bef-4ac9-9b6d-7b930582eb7e" /> |
| wrong schema name in parameter + schema name is displayed within model | right schema in parameter + type in model | 
**Checklist**

fix(api-reference): schema property name mismatch

---

.changeset/poor-trainers-shake.md
documentation/integrations/dotnet.md
integrations/aspnetcore/src/Scalar.AspNetCore/Options/Authentication/Flows/OAuthFlow.cs
integrations/aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarOptionsExtensionsTests.cs

**Problem**
Currently, it is not possible to use the `x-scalar-security-query` extension in the `Scalar.AspNetCore` integration.
**Solution**
Now it is 😎 
**Checklist**

feat(Scalar.AspNetCore): support AdditionalQueryParameters

---

.changeset/curly-brooms-accept.md
.changeset/metal-vans-jump.md
packages/api-reference/src/components/Content/Schema/SchemaComposition.test.ts
packages/api-reference/src/components/Content/Schema/SchemaComposition.vue

**Problem**
currently required property are not highlighted when in nested schema composition. 
**Solution**
this pr passes the missing required information to get the label to show up in property. fixes #5772 
`required label`
| <img width="1116" alt="image" src="https://github.com/user-attachments/assets/ecf20146-423c-4181-a09e-92a3648305c1" /> | <img width="1116" alt="image" src="https://github.com/user-attachments/assets/e287525f-943e-4d9c-ad9d-7c34c0ef5932" /> |
`const enum`
| <img width="1116" alt="image" src="https://github.com/user-attachments/assets/3d82b4a6-0fa3-4ee1-8149-e09f340ff255" /> | <img width="1116" alt="image" src="https://github.com/user-attachments/assets/8e3b9496-da64-414a-b9ac-c39a39960b6a" …

fix(api-reference): schema composition required property label

---

.changeset/serious-chairs-sell.md
packages/api-client/src/style.css
packages/api-reference/src/components/Content/Content.vue
packages/api-reference/src/features/Operation/components/ParameterListItem.vue
packages/api-reference/src/style.css
packages/components/src/style.css

Switches the components, references and the client to all use the .scalar-app scoping class so the styles can be deduped.
Unfortunately the deduping only seems to happen in production environments so we still have some duplication when running the dev servers.
**Checklist**

feat(themes): use .scalar-app as the base class for all tailwind styles

---

.changeset/brown-buttons-itch.md
packages/api-reference/src/features/Search/SearchButton.vue

**Solution**
this pr updates the search button style to match with guide search button usage by using box shadow vs border.
| <img width="280" alt="image" src="https://github.com/user-attachments/assets/f3a70d89-adb8-44a7-8622-efe73c75dbe7" /> | <img width="280" alt="image" src="https://github.com/user-attachments/assets/6c0c1d8e-ec67-49f4-aa63-32db58be3f3a" /> |
**Checklist**

fix(api-reference): search button style

---

.changeset/twenty-planets-complain.md
packages/api-reference/src/components/ApiReferenceLayout.vue

**Problem**
currently in reference header presence, on scroll the sidebar is going above.
**Solution**
this pr increases reference header z index to stay on top.
| <img width="329" alt="image" src="https://github.com/user-attachments/assets/62542090-3602-47ab-aba9-170220bd0c8d" /> | <img width="329" alt="image" src="https://github.com/user-attachments/assets/bf725a22-47ed-446f-a57f-d2456ee4471e" /> |
**Checklist**

fix(api-reference): reference header index

---

.github/workflows/ci.yml

**Problem**
Currently, we run the build step on npm publish on every PR merge but we don't publish. We also can't use blackrock for this job.
**Solution**
With this PR we extend the time to 15 min and only do it on release
**Checklist**

fix(CI): we should only npm publish on release

---

.github/workflows/ci.yml

**Problem**
Currently, we build toDesktop every time but don't release.
**Solution**
With this PR we just skip the whole job
**Checklist**

fix(CI): skip to desktop build on merge as well

---

.changeset/quick-apes-breathe.md
packages/api-reference/src/components/Layouts/ClassicLayout.vue
packages/api-reference/src/components/Section/SectionAccordion.vue
packages/api-reference/src/components/Section/SectionContainerAccordion.vue
packages/api-reference/src/features/Operation/layouts/ClassicLayout.vue

Should fix the issues with the icon sizing.
**Checklist**

fix(api-reference): size icons for Tailwind v4

---

.changeset/strange-singers-shout.md
.github/workflows/ci.yml

**Problem**
I removed NPM publish from running on PR merge, but apparently that was creating the release PR.
**Solution**
With this PR we restore that
**Checklist**

fix(ci): restore changeset

---

packages/api-client/src/libs/send-request/create-request-operation.test.ts
projects/proxy-scalar-com/main.go
projects/proxy-scalar-com/main_test.go

We need to ensure that the proxy does not allow any traffic to private ip ranges (including GCP loopback and metadata cidr) on both initial request and any redirects. 
The proxy has been isolated, but to prevent some easy mistakes in the future, I'm just adding these for now. 

feat(proxy): harden cidr ranges

---

projects/proxy-scalar-com/main.go

- Adds custom dialer to fully prevent dns rebind
- Checks ipv6->v4 mapping against cidr denylist
- Deny 0.0.0.0

feat(proxy): custom dial context

---

.changeset/nine-lions-worry.md
integrations/aspnetcore/Scalar.AspNetCore.slnx
integrations/aspnetcore/playground/Scalar.AspNetCore.Benchmarks/Program.cs
integrations/aspnetcore/playground/Scalar.AspNetCore.Benchmarks/Scalar.AspNetCore.Benchmarks.csproj
integrations/aspnetcore/playground/Scalar.AspNetCore.Benchmarks/ScalarOptionsMapperBenchmarks.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Mapper/ScalarOptionsMapper.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Scalar.AspNetCore.csproj

This PR adds a benchmark project to the `Scalar.AspNetCore` integration. The goal is to enable easier benchmarking, testing, and optimization of existing methods.
I also improved the mapper by reducing allocations and execution time. The code is also now more readable, IMO.
**Checklist**

feat(Scalar.AspNetCore): add benchmarks and improve ScalarOptions mapping

---

.changeset/empty-rivers-clean.md
packages/api-reference/src/features/Operation/components/ParameterHeaders.vue

**Problem**
currently header properties doesn't expand nor use consistent radius when open.
**Solution**
this pr updates header properties style to behave like parameter properties style.
| <img width="564" alt="image" src="https://github.com/user-attachments/assets/1d2d88e8-c203-4131-ac1b-7903f123ee8a" /> | <img width="564" alt="image" src="https://github.com/user-attachments/assets/081ff15a-f767-4cef-9767-b31cf430eed6" /> |
**Checklist**

fix(api-reference): header properties style

---

.changeset/spicy-olives-build.md
packages/api-reference/src/components/Content/Schema/SchemaComposition.test.ts
packages/api-reference/src/components/Content/Schema/SchemaComposition.vue
packages/api-reference/src/components/Content/Schema/helpers/schema-name.test.ts
packages/api-reference/src/components/Content/Schema/helpers/schema-name.ts

**Problem**
recent update in schema composition and discriminator support introduced lack of name and content retrieval.
**Solution**
this pr extracts a schema name helper to better handle use cases and update the schema composition accordingly. fixes #5806
**Tests**
https://sandbox.scalar.com/e/dtj9s
**Checklist**

fix(api-reference): schema composition name handling

---

.changeset/pink-pants-end.md
packages/api-client/src/views/Request/RequestSection/RequestSection.vue

**Problem**
currently auth section is displayed even in no security presence + scripts are present while not introduced yet.
**Solution**
this pr updates the request section filter auth display logic + comment out the scripts for the time being.
| <img width="700" alt="image" src="https://github.com/user-attachments/assets/c3579f02-a096-4c6c-87dc-6261026a7166" /> | <img width="700" alt="image" src="https://github.com/user-attachments/assets/a9354d13-9b62-4bbd-95ec-a391a60dcb8c" /> |
**Checklist**

fix(api-client): request section section filter auth

---

.changeset/stupid-trees-know.md
packages/api-reference/src/features/DownloadLink/DownloadLink.vue

**Problem**
Currently, the download button floats on top of our lazy loader
**Solution**
With this PR we set the z-index to 0 so that it stays underneath.
| ![image](https://github.com/user-attachments/assets/93d233ca-7cc7-4ed1-8a65-cd367ec3eea1) | ![image](https://github.com/user-attachments/assets/43aec6d9-ad77-4c07-84b7-244af934458e)|
**Checklist**

fix(api-reference): z-index of download button

---

.changeset/fresh-buckets-refuse.md
packages/openapi-parser/src/utils/upgrade-from-two-to-three.test.ts
packages/openapi-parser/src/utils/upgrade-from-two-to-three.ts

**Problem**
Currently, the `collectionFormat` keyword is just ignored.
**Solution**
With this PR the `collectionFormat` keyword is migrated to the two new keywords `style` and `explode`. If the old behavior described by `collectionFormat` cannot be described with the new keywords, it is simply removed and the default behavior for the respective parameter types is used.
**Checklist**

fix(openapi-parser): Migrate serialization style

---

.changeset/four-worms-explode.md
packages/api-client/src/views/Request/RequestSection/RequestSection.test.ts
packages/api-client/src/views/Request/RequestSection/RequestSection.vue

**Problem**
recent changes in #5829 cut too deep in the logic and auth is not getting displayed in operation security presence at all in the modal.
**Solution**
this pr updates the auth hidden logic to maintain the previous introduced fix to hide the auth section while keep it displayed accordingly. fixes #5860 #5858
| before | <img width="722" alt="image" src="https://github.com/user-attachments/assets/219a3ef0-f644-42b4-baf2-5b90c5542aca" /> |
| after | <img width="722" alt="image" src="https://github.com/user-attachments/assets/d5e07e70-f851-4ff5-94e1-fa857d2d762f" /> |
**Checklist**

fix(api-client): authentication section display

---

.changeset/poor-bulldogs-sleep.md
packages/openapi-parser/package.json
packages/openapi-parser/src/utils/bundle/bundle.test.ts
packages/openapi-parser/src/utils/bundle/plugins/fetch-urls.test.ts
packages/openapi-parser/src/utils/bundle/plugins/read-files.ts
pnpm-lock.yaml
pnpm-workspace.yaml

**Problem**
Currently, we're performing dynamic imports at the top level, which causes issues with Vite, particularly due to top-level await not being supported in all contexts.
**Solution**
This PR moves the dynamic imports inside the plugin definition, ensuring they're executed only when needed.
We also stabilize test behavior by using static ports, ensuring consistent values for the same files across test runs.
**Checklist**

fix(openapi-parser): use dynamic imports inside the plugin

---

.changeset/rotten-laws-shop.md
packages/helpers/tsconfig.json

**Problem**
The `@scalar/helpers` package currently emits import statements without file extensions in the output. This causes issues in environments like Webpack (when fullySpecified: true is enabled) or when using ESM in Node.js, where explicit file extensions are required.
**Solution**
This PR updates the build process to include .js file extensions in internal import paths, ensuring compatibility with ESM and bundlers that enforce fully specified imports.
**Checklist**

fix(helpers): ensure .js extension is emitted for imports

---

.changeset/poor-crabs-lay.md
packages/workspace-store/src/create-workspace-store.ts
packages/workspace-store/src/index.ts

**Problem**
Currently, on the `api-client` package we don't support top level awaits
**Solution**
With this PR we introduce a sync store so we can use it on the `api-client` package
**Checklist**

feat(workspace-store): create a sync client store

---

pnpm-workspace.yaml

**Problem**
currently on pnpm command run, he workspace has conflict between two @scalar-examples/nuxt-playground-prod packages.
**Solution**
this pr adds the exclusion of `!**/.output/**` to the pnpm workspace configuration in order to prevent having package.json files that can have duplicate names across different examples/integrations.
**Checklist**
- [] I’ve added a changeset (`pnpm changeset`).

chore(configuration): adds .output exclusion to workspace configuration

---

documentation/integrations/laravel-scribe.md

**Problem**
Currently, the doc specifically related to the laravel integration with Scribe had some typos, "curious" is curioius and  the sentence "The YAML file should describe you’re API." 
**Solution**
With this PR I fixed these typos.
**Checklist**
- [ x] I’ve added an explanation _why_ this change is needed.
- [x ] I’ve updated the documentation.

fix(integrations): some typos in the laravel doc

---

.changeset/many-books-fix.md
packages/workspace-store/src/client.test.ts
packages/workspace-store/src/client.ts

**Problem**
We were previously handling file reading logic directly within the client-side store. This approach is incompatible with Webpack builds, leading to bundling issues since fs and related Node APIs are not available in the browser environment.
**Solution**
This PR removes the readFile plugin from the client store to resolve the Webpack compatibility issues. Instead, we rely solely on the fetchUrls plugin for loading document content in environments where direct file system access isn't available.
**Checklist**

fix(workspace-store): remove readFiles plugin from the client store

---

integrations/fastapi/README.md
integrations/fastapi/scalar_fastapi/scalar_fastapi.py
integrations/fastapi/setup.py

**Problem**
Currently, [`hideClientButton`](https://github.com/scalar/scalar/blob/main/documentation/configuration.md#hideclientbutton-boolean) configuration is not available in FastAPI configuration.
**Solution**
With this PR, `hide_client_button` is added as configuration parameter to `get_scalar_api_reference`.
**Checklist**

feat(scalar_fastapi): add `hide_client_button` to configuration

---

.changeset/three-crabs-care.md
packages/openapi-parser/README.md
packages/openapi-parser/src/plugins-browser.ts
packages/openapi-parser/src/plugins.ts
packages/openapi-parser/src/utils/bundle/bundle.test.ts
packages/openapi-parser/src/utils/bundle/bundle.ts
packages/openapi-parser/src/utils/bundle/plugins/parse-json/index.test.ts
packages/openapi-parser/src/utils/bundle/plugins/parse-json/index.ts
packages/openapi-parser/src/utils/bundle/plugins/parse-yaml/index.test.ts
packages/openapi-parser/src/utils/bundle/plugins/parse-yaml/index.ts
packages/openapi-parser/src/utils/bundle/plugins/read-files/index.ts
packages/openapi-parser/src/utils/load/load.ts

**Problem**
Currently, the bundler does not support raw YAML or JSON strings as input, which limits flexibility when consuming APIs from dynamic or in-memory sources.
**Solution**
This PR adds support for parsing both YAML and JSON strings as valid input to the bundler, allowing them to be processed just like file-based documents.
**Checklist**

feat(openapi-parser): introduce parseJson and parseYaml plugins for bundler

---

.changeset/famous-pears-jog.md
packages/api-client/src/components/AddressBar/AddressBar.vue

**Problem**
recent changes in #5795 and #5833 changed the approach that was used to display the background loading state, as highlighted in #5904
**Solution**
this pr updates the address bar style to bring bar the background on load.
| before | <img width="700" alt="image" src="https://github.com/user-attachments/assets/66c27aeb-992d-47b5-b69b-c0114edc83b0" /> | 
| after | <img width="700" alt="image" src="https://github.com/user-attachments/assets/325c3477-403e-4b1e-9ffb-1444609a3856" /> |
we might be able to remove the `backgroundColor` from the helper after this cc @amritk?
**Checklist**

fix(api-client): address bar bg

---

.changeset/mean-dancers-sort.md
packages/api-reference/src/v2/ApiReferenceWorkspace.vue

**Problem**
currently the darkmode toggle is not reactive anymore to dark mode change.
**Solution**
this pr updates the fresh api reference workspace dark mode watcher to add back the toggle state on dark mode change.
| before | <img width="302" alt="image" src="https://github.com/user-attachments/assets/c8775264-293f-4760-989b-f75b1856bb88" /> | 
| after | <img width="302" alt="image" src="https://github.com/user-attachments/assets/a60cbf01-b57a-4602-9f9a-4dca6948dee4" /> |
**Checklist**

fix(api-reference): sidebar darkmode toggle state

---

.changeset/nine-rules-move.md
.changeset/rich-fishes-boil.md
packages/api-reference/src/components/Content/Schema/Schema.vue
packages/api-reference/src/components/Content/Schema/SchemaDiscriminator.vue
packages/api-reference/src/components/Content/Schema/SchemaProperty.test.ts
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue

**Problem**
currently when using discriminator including nested schema, it causes a maximum call stack and recursivity.
**Solution**
this pr prevents the recursion in discriminator context. fixes #5919
| before | <img width="579" alt="image" src="https://github.com/user-attachments/assets/80b4fa28-1a26-436e-893f-c373e860b9e8" /> |
| after | <img width="579" alt="image" src="https://github.com/user-attachments/assets/27b1acd3-5c7f-4627-a52a-ca132fe9f319" /> |
**Checklist**

fix(api-reference): schema property discriminator recursion

---

.changeset/giant-steaks-give.md
.changeset/pretty-weeks-rule.md
.changeset/red-mails-beam.md
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue
packages/api-reference/src/components/Content/Schema/helpers/schema-name.test.ts
packages/api-reference/src/components/Content/Schema/helpers/schema-name.ts

**Problem**
update made in #5783 removed some logic unnecessarily so and do not properly check for the right schema model + model name used instead of primitive type.
**Solution**
this pr refactors schema property heading component by using the previously added schema name helper + adds new functions to it. fixes #5895 #5903 #5907
`model name`
| before | <img width="570" alt="image" src="https://github.com/user-attachments/assets/128f8b33-0ed4-4a97-a809-1f73634a6164" /> | 
| after | <img width="570" alt="image" src="https://github.com/user-attachments/assets/5530e769-5de4-49ed-9e71-8076404817da" /> |
`primitives`
| before | <img width="570" alt="image" src="https://github.com/user-attachments/assets/9f29f913-2906-4 …

fix(api-reference): schema property heading model name

---

.changeset/five-birds-fetch.md
packages/openapi-parser/src/utils/bundle/bundle.test.ts
packages/openapi-parser/src/utils/bundle/bundle.ts
packages/openapi-parser/src/utils/bundle/plugins/fetch-urls/index.ts
packages/openapi-parser/src/utils/bundle/plugins/parse-json/index.ts
packages/openapi-parser/src/utils/bundle/plugins/parse-yaml/index.ts
packages/openapi-parser/src/utils/bundle/plugins/read-files/index.ts

**Problem**
The bundler previously assumed that only two plugins—`fetchUrls` and `readFiles`—would handle string inputs. This assumption limited extensibility and caused incorrect handling of other potential string-based inputs.
**Solution**
This PR removes the hardcoded assumption and makes the input handling more flexible. It now checks whether the input string is a URL or a file path before setting the base origin, allowing other plugins to process string inputs correctly without unintended side effects.
**Checklist**

feat(openapi-parser): correctly set the base origin for string inputs for the bundler

---

.changeset/funny-moose-tie.md
packages/api-reference/src/components/ApiReferenceLayout.vue

**Problem**
Currently, our scroll listener was on a dom element
**Solution**
With this PR we move it to the window. I tested pathRouting but it doesn't seem like we even use hashPrefix anymore. Opened up another ticket to look into that one.
**Checklist**

fix(api-reference): scroll to top to remove hash

---

.changeset/wild-experts-approve.md
packages/openapi-parser/src/utils/upgrade-from-three-to-three-one.test.ts
packages/openapi-parser/src/utils/upgrade-from-three-to-three-one.ts

**Problem**
Currently, we just leave x-webhooks as is
**Solution**
With this PR we upgrade x-webhooks to webhooks which were introduced in the 3.1.0 spec
**Checklist**

feat(openapi-parser): add x-webhooks to the upgrader

---

.changeset/little-houses-grab.md
packages/snippetz/package.json
packages/snippetz/src/clients.ts
packages/snippetz/src/plugins/python/httpx/async.test.ts
packages/snippetz/src/plugins/python/httpx/async.ts
packages/snippetz/src/plugins/python/httpx/index.ts
packages/snippetz/src/plugins/python/httpx/sync.test.ts
packages/snippetz/src/plugins/python/httpx/sync.ts
packages/snippetz/src/plugins/python/requestsLike.ts
packages/types/src/snippetz/snippetz.ts

**Problem**
Add python [httpx](https://github.com/encode/httpx/) as client.
**Solution**
Since httpx and requests have almost same usage patterns, I extracted the common code into `requestsLike.ts`. I also added conversion from `true/false/null` to `True/False/None` and related tests.
**Checklist**

feat(snippetz): add python/httpx plugin

---

.changeset/ten-news-applaud.md
packages/api-reference/src/components/Content/Schema/SchemaProperty.test.ts
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue

**Problem**
after recent changes, schema property object are not properly rendering properties when within array type.
**Solution**
this pr updates the type object to include array type to render properties. fixes #5939
| before | <img width="552" alt="image" src="https://github.com/user-attachments/assets/9210cac5-5265-4b63-9bae-92ca88d1d93c" /> |
| after | <img width="552" alt="image" src="https://github.com/user-attachments/assets/fa050724-d636-4e9f-a93b-081650d867b9" /> |
**Checklist**

fix(api-reference): schema property array type object 

---

.changeset/seven-rats-divide.md
packages/api-client/src/libs/create-client.ts
packages/api-reference/src/features/ApiClientModal/ApiClientModal.vue
packages/api-reference/src/features/DocumentSource/hooks/useDocumentSource.ts

**Problem**
Currently, we re-import the new document into the client store but to not remove the old one. Resulting in infinite collections.
**Solution**
With this PR we reset the store before importing
**Checklist**

fix(api-reference): re-create client store on document change

---

.changeset/sixty-humans-sparkle.md
packages/api-reference/src/components/Content/Schema/SchemaProperty.test.ts
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue

**Problem**
using `x-enumDescriptions` while being implemented, is not getting displayed in the api reference as expecting an array instead of an object.
**Solution**
this pr updates the current logic to get to display enum description accordingly. fixes #5934 #5938
| before | <img width="700" alt="image" src="https://github.com/user-attachments/assets/a60f141f-4075-49ff-8e4f-d8cfe5d51449" /> |
| after | <img width="700" alt="image" src="https://github.com/user-attachments/assets/858a10c2-4f1b-46ea-815c-85175beaaa82" /> | 
**Test**
<details>
<summary>OpenApi Document</summary>
```json
{
"schemas": {
"planet": {
"enum": [
"Ice giant",
"Dwarf",
"Gas",
"Iron"
],
"title": "Planet",
"description": "The …
```

fix(api-reference): x-enumDescriptions should be an object

---

.changeset/chilled-roses-tell.md
packages/api-client/src/views/Request/RequestSection/RequestBody.test.ts
packages/api-client/src/views/Request/RequestSection/RequestBody.vue

**Problem**
Currently, deleting rows in the request body form-data is not yet implemented.
before:
https://github.com/user-attachments/assets/93385b82-427a-4070-be04-27fd79d5ad1c
after:
https://github.com/user-attachments/assets/ccc18063-a335-430f-a435-71818a0b3248
**Checklist**

feat(api-client): implement deleteRow function for RequestBody form data

---

.changeset/ninety-ears-double.md
packages/api-reference/src/features/DocumentSource/hooks/useDocumentFetcher.ts

**Problem**
Currently, if we provide both content and url we re-fetch the document.
**Solution**
With this PR we do not fetch if we have content already. URL is needed to share the document so sometimes both are provided and the content is fetched on the server, no need for a double fetch.
**Checklist**

fix(api-reference): only fetch document if we dont have content

---

projects/proxy-scalar-com/.env.example
projects/proxy-scalar-com/main.go
projects/proxy-scalar-com/package.json

**Problem**
We previously blocked this set of CIDR addresses for production usage of the proxy; since the proxy can also be ran locally to hit private CIDR ranges, we should ensure that these are bypassed by default.
Improved devex for https://github.com/scalar/scalar/pull/5812
**Solution**
- Introduce an env check which will bypass CIDR logic for dev
- Update default dev commands + docker to use dev env
**Checklist**

feat(proxy): bypass cidr checks for dev

---

.changeset/large-stingrays-decide.md
packages/api-reference/src/components/Content/ClientLibraries/ClientLibraries.vue

**Problem**
currently the client libraries style appears inconsistant + doesn't offer copy capability (e.g. in SDK usage)
**Solution**
this pr updates the style accordingly and re-introduce the copy capability.
| before | <img width="700" alt="image" src="https://github.com/user-attachments/assets/7b53b090-1967-4d78-b747-99f8a118ea5f" /> |
| after | <img width="700" alt="image" src="https://github.com/user-attachments/assets/5066faad-5b79-4c38-83f6-152071d65788" /> | 
**Checklist**

fix(api-reference): client libraries style

---

.changeset/mighty-pants-eat.md
packages/api-reference/src/components/Content/Schema/helpers/optimizeValueForDisplay.test.ts
packages/api-reference/src/components/Content/Schema/helpers/optimizeValueForDisplay.ts

**Problem**
properties get lost during all of schema merge, leading to losing the schema title within schema composition dropdown.
**Solution**
this pr ensures that original schema properties are preserved. fixes #5912
| before | <img width="572" alt="image" src="https://github.com/user-attachments/assets/112458e2-bf8b-4c9f-bc39-a7f467878b37" /> |
| after | <img width="572" alt="image" src="https://github.com/user-attachments/assets/1d91b2b6-1a8e-444f-8bc5-b350e37b1853" /> |
**Test**
<details>
<summary>OpenAPI document</summary>
```yaml
{
"openapi": "3.0.4",
"info": {
},
"paths": {
"/api/Action": {
"post": {
"content": {
"schema": {
"$ref": …
```

fix(api-reference): oneof dropdown schema title display

---

scalar.config.json

**Problem**
Currently we are missing analytics on guides.scalar.com
**Solution**
With this PR we add fathom :)
**Checklist**

feat: add analytics to guides.scalar.com

---

playwright/tests/testApiReference.ts

**Problem**
addition of #5927 introduced the same wording that is currently tested against in description through playwright, resulting in a double results hence breaking the test. 
**Solution**
this pr updates the playwright api reference test to be more specific against the tested description to avoid double result.
**Checklist**

fix(api-reference): updates playwright api reference test

---

.changeset/curvy-cats-invite.md
packages/api-reference/src/index.ts

**Problem**
Need useSidebar separately in org for now to handle some item actions
**Solution**
Export current useSidebar; it was exported previously but from hooks instead, and we got rid of that
**Checklist**

feat(api-reference): export references useSidebar

---

.changeset/big-cougars-matter.md
packages/api-reference/src/libs/openapi.ts

**Problem**
Currently, we do not ignore models correctly.
**Solution**
With this PR we apply x-scalar-ignore although we will be removing this all and using the sidebar logic soon which already contains this!
**Checklist**

fix(api-reference): ensure x-scalar-ignore applies to models

---

.github/workflows/dependency-review.yml

**Problem**
I just found this official GitHub action that reviews dependencies for known security vulnerabilities.
**Solution**
This PR adds it as an additional workflow to further increase the security of our repository.
Note: Looks like it’s only reviewing touched files.
**Checklist**

ci: review dependencies for known security issues

---

.changeset/sour-mirrors-move.md
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue
packages/api-reference/src/components/Content/Schema/helpers/schema-name.ts

**Problem**
Currently, we don't use the content encoding from version 3.1 of the spec to show descriptions, it used to be called format in 3.0.
https://spec.openapis.org/oas/latest.html#migrating-binary-descriptions-from-oas-3-0
**Solution**
With this PR we fix this and show the content type.
@antlio so I removed the code which checks for additional properties. Not sure if it was meant to match all additional properties but either way I don't think that is safe. What was that part specifically fixing?
Then I added the content encoding to be displayed so it matches the old style.
**Checklist**

fix(api-reference): show content type description in schema property

---

.changeset/fresh-radios-enjoy.md
biome.json
packages/api-reference/src/features/Search/useSearchIndex.test.ts
packages/api-reference/src/features/Search/useSearchIndex.ts
packages/api-reference/src/helpers/parse.ts

**Problem**
closes #5983 
Currently, using x-tag-groups duplicates the operations in the list
**Solution**
With this PR we prevent that duplication. Also it seems search was broken when you don't have any tags, fixed that as well.
**Checklist**

fix(api-reference): remove duplicate operations in x-tag-groups

---

.changeset/lovely-ducks-explain.md
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.test.ts
packages/api-reference/src/components/Content/Schema/helpers/schema-name.test.ts
packages/api-reference/src/components/Content/Schema/helpers/schema-name.ts

**Problem**
closes #6001
Currently, we are matching the schema name based on a matching type.
**Solution**
That is unsafe as we can easily have multiple schemas with different names and the same types, specially for non-object or arrays. Previously it was matching strings which are quite common. Now it will only match if all array or object properties match which is a bit safer but not perfect.
Alright so after some digging I realize what @antlio meant. Once we de-reference we lose the name of the schema. I just made it a little safer by only property matching on objects or arrays, this should be slightly less error prone.
We should come back at this one in the new workspace store and keep some reference to the name @DemonHa as long as we have access to the ref string we should be good! …

fix(api-reference): reduce incorrect schema names

---

.changeset/curly-snakes-hang.md
packages/api-reference/src/components/DocumentSelector/DocumentSelector.vue
packages/api-reference/src/components/Sidebar/Sidebar.vue
packages/api-reference/src/components/Sidebar/SidebarElement.vue
packages/api-reference/src/components/Sidebar/SidebarGroup.vue
packages/api-reference/src/features/ExampleResponses/ExampleResponses.vue
packages/components/src/components/ScalarSidebar/ScalarSidebarSearchButton.vue
packages/components/src/components/ScalarSidebar/ScalarSidebarSearchInput.vue
scalar.config.json

New sidebar styles
14px font now, font weight regular, and semibold when active + endpoint will get semibold when active

feat(api-reference): align api reference sidebar style with figma

---

scalar.config.json

**Problem**
picked the right icon for docs & added defaultOpen
**Solution**
With this PR …
**Checklist**

fix(documentation): wrong sidebar icon and add `defaultOpen: false`

---

.changeset/slow-dogs-sniff.md
integrations/aspnetcore/src/Scalar.AspNetCore/Contract/ScalarConfiguration.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Enums/DocumentDownloadType.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarOptionsExtensions.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Mapper/ScalarOptionsMapper.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Options/ScalarOptions.cs
integrations/aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarOptionsMapperTests.cs

This PR adds support for the new `documentDownloadType` property (https://github.com/scalar/scalar/pull/6009)
**Checklist**

feat(Scalar.AspNetCore): add DocumentDownloadType configuration

---

.changeset/chilly-cycles-brake.md
.changeset/long-feet-exercise.md
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/ClassicHeader.vue
packages/api-reference/src/components/DocumentSelector/DocumentSelector.vue
packages/api-reference/src/features/Search/SearchButton.vue
packages/components/src/components/ScalarListbox/ScalarListbox.vue
packages/components/src/components/ScalarSidebar/ScalarSidebarSearchButton.vue

Prevents inconsistent external line heights from affecting the search button layout and set the width to full for the references search button export.
Normally it's preferred to use the parent to manage layout (e.g. flexbox, grid) but this maintains the current behaviour.
Also:
* Removes the spacing around the document selector on the classic layout
* Manages the width of the search on classic layout
* Makes sure classes are being passed the the search on the classic layout
**Checklist**

fix(api-reference): fix up search and document selector on classic layout

---

.changeset/plenty-countries-own.md
packages/components/src/components/ScalarSidebar/ScalarSidebar.stories.ts
packages/components/src/components/ScalarSidebar/ScalarSidebarButton.vue
packages/components/src/components/ScalarSidebar/ScalarSidebarGroup.vue
packages/components/src/components/ScalarSidebar/ScalarSidebarIndent.vue
packages/components/src/components/ScalarSidebar/ScalarSidebarItems.vue
packages/components/src/components/ScalarSidebar/ScalarSidebarPlayground.vue
packages/components/src/components/ScalarSidebar/ScalarSidebarSection.vue
packages/components/src/components/ScalarSidebar/ScalarSidebarSpacer.vue
packages/themes/src/base/variables.css
packages/themes/src/tailwind/theme.css
packages/use-hooks/src/useBindCx/cva.ts

Add sidebar sections and updates the sidebar to align with the figmas. To keep the work small going to try to get this merged this then do sub sidebars.
(Right side shows bounding boxes / spacing)
**Checklist**

feat(components): add sidebar sections

---

integrations/aspire/playground/Scalar.Aspire.UserService/package.json

This PR adds the prefix `@scalar-internal` to the playground service, so it's ignored by changeset.
**Checklist**

fix(Scalar.Aspire.Playground):  prefix name with `@scalar-internal`

---

.changeset/famous-carrots-remember.md
packages/api-reference/src/features/sidebar/helpers/create-sidebar.test.ts
packages/api-reference/src/features/traverse-schema/helpers/traverse-schemas.ts

**Problem**
We list the schemas in the sidebar, but we always use the key and ignore the title (if the schema has one):
https://json-schema.org/draft/2020-12/json-schema-core#section-4.3.5
**Solution**
With this PR we’re using the schema title (if it’s available) and fall back to the key of the schema.
Closes https://github.com/scalar/scalar/issues/6038
**Checklist**

feat(api-reference): use schema title for the sidebar (if available)

---

.changeset/yellow-bobcats-dance.md
packages/components/src/components/ScalarCodeBlock/ScalarCodeBlock.vue
packages/components/src/components/ScalarCombobox/ScalarCombobox.test.ts
packages/components/src/components/ScalarCombobox/ScalarComboboxOptions.vue
packages/components/src/components/ScalarCombobox/ScalarComboboxPopover.vue

**Problem**
Currently, when you have long list of combobox options, it does a janky scroll on open.
**Solution**
With this PR we toss a timeout on the autofucus and it seems to fix the issue. @hwkr this is all yours now.
**Checklist**

fix(components): janky scroll on combobox autofocus

---

documentation/configuration.md

Changed property from `httpVerb` to `method` (now lowercase)
**Checklist**

docs: update `operationsSorter` example

---

.changeset/dirty-bulldogs-eat.md
packages/api-reference/src/features/sidebar/helpers/create-sidebar.test.ts
packages/api-reference/src/features/traverse-schema/helpers/traverse-paths.ts

**Problem**
Currently, we’re using the operation summary for the sidebar entries, even if it’s just an empty string `''`.
Example: https://demo.scribe.knuckles.wtf
**Solution**
With this PR we’ll use the path then. :)
**Checklist**

fix(api-reference): uses empty summary for the sidebar

---

.changeset/fair-dots-yawn.md
packages/api-reference/src/components/ApiReferenceLayout.vue

**Problem**
If you open an URL with an operation id or something in the hash, we don’t scroll to it.
**Solution**
I’m trying the @amritk tactic and just deleted some code to make it work. 👀 
**Checklist**

fix(api-reference): does not scroll to anchor on load

---

.changeset/pretty-carrots-cheer.md
packages/api-reference/src/components/Content/Lazy/Loading.vue

**Problem**
The tags section is rendered on initial page load using the same section ID as the main page content.
This causes potential conflicts or confusion when targeting or navigating to specific sections of the page, as both the page and the tags section share the same ID.
**Solution**
With this PR we give a unique id for the tag section so when the page finish loading we scroll to the correct section of the page
**Checklist**

fix(api-references): duplicate section ID for tags on page load

---

README.md

no longer use base64's in svgs, will cut ~3mb from our readme images and make them way more c r i s p

docs: update readme client / refs images

---

.changeset/cool-humans-taste.md
packages/api-reference/src/components/Content/Lazy/Loading.vue

**Problem**
```bash
│ [@vue/compiler-sfc] withDefaults() is unnecessary when using destructure with defineProps().
│ Reactive destructure will be disabled when using withDefaults().
│ Prefer using destructure default values, e.g. const { foo = 1 } = defineProps(...).
│
│ /Users/hanspagel/Documents/Projects/scalar/packages/api-reference/src/components/Content/Lazy/Loading.vue
│ 42 |   * - need to find an event for codemirror loaded, currently using timeout for models
│ 43 |   */
│ 44 |  const { document, collection, server, layout, parsedSpec } = withDefaults(
│    |                                                               ^^^^^^^^^^^^
│ 45 |    defineProps<{
│ 46 |      document: OpenAPIV3_1.Document
```
**Solution**
Do what the warning says.
**Checklist**
I’ve gone through the …

fix(api-reference): `withDefaults` is used with destructured props

---

packages/api-reference/src/features/Search/useSearchIndex.test.ts

**Problem**
Oops, we merged two search PRs without rebasing them, resulting in failing tests in main.
**Solution**
This PR fixes the tests. :)
**Checklist**

fix(api-reference): search tests are failing

---

.changeset/smooth-books-exist.md
packages/api-client/src/components/ImportCollection/ImportCollectionModal.vue
packages/api-client/src/components/ImportCollection/OpenAppButton.vue
packages/api-client/src/components/ImportCollection/utils/get-openapi-version.test.ts
packages/api-client/src/components/ImportCollection/utils/get-openapi-version.ts
packages/api-client/src/components/ImportCollection/utils/import-collection.ts
packages/api-client/src/components/ImportCollection/utils/is-document.test.ts
packages/api-client/src/components/ImportCollection/utils/is-document.ts
packages/api-client/src/components/ImportCollection/utils/is-url.test.ts
packages/api-client/src/components/ImportCollection/utils/is-url.ts
packages/api-client/src/components/ImportCollection/utils/isDocument.ts
packages/api-client/src/components/ImportCollection/utils/isUrl.ts
packages/oas-utils/src/transforms/import-spec.test.ts
packages/oas-utils/src/transforms/import-spec.ts

**Problem**
When we import documents that don’t have a server, we just fallback to the URL of the API client (which will never be the actual API, because … it’s the API client).
Example: https://api.theirstack.com/
**Solution**
With this PR we’re using the `documentUrl` as a fallback, so if something was imported from https://example.com without a `servers` array, we just assume the API is on https://example.com (not on the URL of the API client).
I've also renamed the import helpers (kebab-case) and added tests.
**Checklist**

feat(api-client): use `documentUrl` as a fallback server

---

packages/snippetz/src/plugins/shell/curl/curl.test.ts
packages/snippetz/src/plugins/shell/curl/curl.ts

**Problem**
Currently, URL's with a `$` (dollar sign) special character are not being handled correctly by the curl shell package (i.e. not single quoting the URL) which results in the curl command not executing as expected when run in a terminal/shell (as it will interpret it as a variable). 
For further context on how this was discovered: I am implementing OpenAPI documentation (with Scalar) for a specification that uses `$` characters in their routes, e.g. [`/CodeSystem/$lookup`](https://www.hl7.org/fhir/R5/codesystem-operation-lookup.html). Example here https://sandbox.scalar.com/e/lCjAs
**Solution**
With this PR I have added the `$` to the special characters which are used to determine whether the URL needs to be single quoted (which resolves the issue when the curl command is run in …

fix(snippetz): shell/curl does not add quotes for URLs with special character `$`

---

.changeset/proud-bears-protect.md
.github/workflows/ci.yml

This PR adds `linux/arm64` as a platform for the docker builds.
Closes #6089
**Checklist**

feat(Scalar.Aspire): add support for multi-platform docker build

---

.changeset/cyan-hats-invent.md
packages/api-reference/src/features/traverse-schema/helpers/traverse-tags.test.ts
packages/api-reference/src/features/traverse-schema/helpers/traverse-tags.ts

**Problem**
https://discord.com/channels/1135330207960678410/1385687477301547130
Currently, httpVerb was removed from operationsSorter
**Solution**
With this PR we add backwards compatibility
**Checklist**

fix(api-reference): operationsSorter backwards compatibility

---

.changeset/tasty-pigs-tan.md
packages/api-reference/src/components/Content/Schema/Schema.vue
packages/api-reference/src/components/Content/Schema/SchemaComposition.vue

**Problem**
For a composition we show the description three times, that’s too much.
**Solution**
With this PR, we just show it once. :) Fixes #5999
**Preview**
**Example**
```json
{
"info": {
},
"paths": {
"/foo": {
"post": {
"summary": "foo",
"description": "Foo body",
"content": {
"schema": {
"foos": {
"oneOf": [
{
"title": "foo1",
"description": "foo1 description"
},
{
"type": "array",
"title": "foo2",
"description": "foo2 description",
"items": {
"type": "string"
}
}
]
}
}
}
}
}
}
}
}
}
}
```
**Checklist**

fix(api-reference): shows composition description three times

---

.changeset/pink-camels-sit.md
packages/api-reference/src/components/Content/Models/Models.vue
packages/api-reference/src/components/Content/Schema/helpers/get-schema-type.test.ts
packages/api-reference/src/components/Content/Schema/helpers/get-schema-type.ts

**Problem**
Currently, we render the schema title if it’s available.
**Solution**
With this PR we’re also using the `xml.name` as a fallback, as suggested in https://github.com/scalar/scalar/pull/5676#issuecomment-2892431645
Fixes #5682
We’ll still look into the `title` attribute first.
**Preview**
**Example**
```json
{
"info": {
"title": "xml.name",
"version": "1.0"
},
"schemas": {
"ExampleSchema": {
"type": "array",
"items": {
"id": {
"type": "integer"
}
},
"xml": {
"name": "XmlTag"
}
},
"xml": {
"name": "XmlName"
}
}
}
}
}
```
**Checklist**

feat(api-reference): use xml.name as a fallback for schema titles

---

.changeset/gorgeous-brooms-attend.md
.changeset/short-suits-walk.md
packages/api-client/src/components/CommandPalette/CommandActionInput.vue
packages/api-client/src/components/CommandPalette/TheCommandPalette.vue
packages/api-client/src/views/Cookies/Cookies.vue
packages/api-client/src/views/Environment/Environment.vue

**Problem**
currently the command palette input style if offish + action link are not redirecting to the right page
**Solution**
this pr:
- updates command palette action input style to increase consistency and alignment
- fixes and opens modal on command palette action link navigation
- adds missing id to textarea leading to console warning
| preview | state |
| before | <img width="626" alt="image" src="https://github.com/user-attachments/assets/e795e8b9-a8d8-45e4-a1a4-30c9dfb3fcae" /> |
| after | <img width="626" alt="image" src="https://github.com/user-attachments/assets/820900e0-847e-43bf-b299-055e9a901cb1" /> |
**Checklist**

fix(api-client): command palette action link path are not redirecting

---

.changeset/wicked-goats-dance.md
.github/workflows/ci.yml
integrations/fastapi/MANIFEST.in
integrations/fastapi/package.json
integrations/fastapi/pytest.ini
integrations/fastapi/run_tests.py
integrations/fastapi/scalar_fastapi/__init__.py
integrations/fastapi/setup.py
integrations/fastapi/tests/README.md
integrations/fastapi/tests/__init__.py
integrations/fastapi/tests/requirements.txt
integrations/fastapi/tests/test_imports.py
integrations/fastapi/tests/test_integration.py
integrations/fastapi/tests/test_scalar_fastapi.py
pnpm-lock.yaml

**Problem**
Currently, we’re manually publishing the FastAPI package (and by manually mean, we don’t publish it all).
*phone rings*
Hans: 👀 
*Hans picks up phone*
Hey, stoneage here, I want my workflow back!
**Solution**
With this PR we’ll catapult ourselves in the year 2025 and build, test and publish the FastAPI package in CI.
And yeah, we’ve finally got tests for the FastAPI integration. :)
✅ I’ve added the GitHub Action secret already.
**Checklist**

ci: build, test and publish FastAPI integration

---

.changeset/unlucky-ads-unite.md
packages/snippetz/package.json
pnpm-lock.yaml

**Problem**
Currently, we are installing `@scalar/types` as a dev dependency, which is going to cause problems when we install this package.
**Solution**
With this PR we move `@scalar/types` to dependencies
**Checklist**

chore(snippetz): move @scalar/types to dependencies

---

.changeset/pretty-timers-impress.md
packages/api-reference/src/features/sidebar/components/SidebarElement.test.ts
packages/api-reference/src/features/sidebar/components/SidebarElement.vue
packages/api-reference/src/features/traverse-schema/index.ts

**Problem**
With the recent sidebar refactor we introduced a regression: deprecated operations aren’t rendered with a strike-through style anymore.
**Solution**
Fixes #6129
**Checklist**

fix(api-reference): deprecated operations aren’t striked in the sidebar anymore

---

.changeset/cold-waves-run.md
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.test.ts
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue

**Problem**
In OpenAPI 3.0 `exclusiveMinum` and `exclusiveMaximum` were boolean values, but they became specific numbers in OpenAPI 3.1. The rendering still expected booleans.
**Solution**
With this PR we’re using them as numbers, not as booleans.
The upgrader already upgrades them to be numbers, not booleans.
Fixes #5624
Fixes #5966
**Preview**
**Example**
```json
{
"info": {
"title": "FooAPI",
},
"paths": {
"/foo": {
"get": {
"summary": "Get Foo",
"operationId": "",
"parameters": [],
"content": {
"schema": {
"foo": {
"type": [
"integer"
],
"exclusiveMinimum": 1,
"exclusiveMaximum": 10
}
}
}
}
}
}
}
}
}
}
```
**Checklist**

fix(api-reference): treat `exclusiveMinimum` and `exclusiveMaximum` as numbers

---

.changeset/violet-terms-draw.md
packages/api-client/src/views/Collection/components/MarkdownInput.vue

**Problem**
currently when updating api client collection description and switching more to preview breaks the focus within input preventing usage of modal for instance.
**Solution**
this pr delays mode switch to avoid input typing issue. fixes #6103
**Checklist**

fix(api-client): input focus post collection description update

---

.changeset/young-islands-pump.md
packages/workspace-store/src/client.ts
packages/workspace-store/src/schemas/v3.1/strict/components.ts
packages/workspace-store/src/schemas/v3.1/strict/path-item.ts

**Problem**
Currently, we were missing 2 http methods from the spec (head, options) and connect which we also support but isn't in the spec yet.
**Solution**
With this PR we simply add those 3 methods, however this put our generated type complexity over the top so we had to annotate a few things. 
A real fix would be to remove compose or something similar, @DemonHa is on that case. But unblocks blocks (lol)
**Checklist**

fix(workspace-store): add a couple missing http methods and add type annotations

---

packages/openapi-parser/src/utils/upgrade-from-three-to-three-one.test.ts
packages/openapi-parser/src/utils/upgrade-from-three-to-three-one.ts

**Problem**
we are currently checking for the string 'undefined' within the applyChangesToDocument function instead of the value, which can lead to not setting schema type properly.
**Solution**
this pr updates the function to check the value is defined instead.
**Checklist**

fix(openapi-parser): applyChangesToDocument undefined type check

---

README.md

seems like something changed with how github handles markdown img heights... This should fix it for our readme
after:
before:

fix(readme): github readme height bug

---

.changeset/shaggy-elephants-boil.md
packages/api-reference/src/features/Operation/components/ContentTypeSelect.vue
packages/api-reference/src/features/Operation/components/RequestBody.vue
packages/api-reference/src/features/Operation/layouts/ClassicLayout.vue

**Problem**
The classic layout does not show the request body anymore. We forgot to pass the relevant prop. 🤦 
See https://discord.com/channels/1135330207960678410/1391503347189682337
**Solution**
This PR renders the request body again. Turns out there were a bunch of style fixes needed to make it look good.
**Before**
Starts with responses …
**After**
Shows the request body…
**Checklist**

fix(api-reference): classic layout does not show request body

---

.changeset/pink-files-compare.md
.changeset/violet-sheep-rescue.md
.changeset/warm-falcons-remember.md
packages/api-client/src/components/Form/Form.vue
packages/api-client/src/components/Server/ServerVariablesSelect.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuth.vue
packages/components/src/components/ScalarToggle/ScalarToggle.vue

**Problem**
current api client collection setting pages contains few ui inconsistencies including forms, toggle, select position.
**Solution**
this pr updates the api client collection settings pages in order to fix them as seen below:
`auth`
| before | <img width="554" alt="image" src="https://github.com/user-attachments/assets/76cdc14e-3598-4da7-8ddd-6b2735e89a05" /> |
| after | <img width="554" alt="image" src="https://github.com/user-attachments/assets/21325f0f-8955-411c-ad3b-1d00878dbe9a" /> |
`form`
| before | <img width="554" alt="image" src="https://github.com/user-attachments/assets/94bb5d81-2e15-4db1-b7ca-054cc24efce4" /> |
| after | <img width="554" alt="image" …

fix(api-client): collection ui inconsistencies

---

.changeset/wicked-insects-push.md
integrations/aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarEndpointRouteBuilderExtensions.cs

**Problem**
Currently, we return only one endpoint instead of the whole endpoint group.
**Solution**
With this PR, we return the endpoint group instead of one endpoint.
Closes #6182
**Note**
I _think_ this shouldn't cause any issue. I checked a couple of scenarios.
**Checklist**

feat(Scalar.AspNetCore): return scalar endpoint group instead of endpoint

---

.changeset/cool-mice-approve.md
packages/workspace-store/README.md
packages/workspace-store/src/client.test.ts
packages/workspace-store/src/client.ts
packages/workspace-store/src/helpers/general.ts
packages/workspace-store/src/navigation/helpers/get-tag.test.ts
packages/workspace-store/src/navigation/helpers/traverse-description.ts
packages/workspace-store/src/navigation/helpers/traverse-document.test.ts
packages/workspace-store/src/navigation/helpers/traverse-document.ts
packages/workspace-store/src/navigation/helpers/traverse-paths.ts
packages/workspace-store/src/navigation/helpers/traverse-schemas.ts
packages/workspace-store/src/navigation/helpers/traverse-tags.test.ts
packages/workspace-store/src/navigation/helpers/traverse-tags.ts
packages/workspace-store/src/navigation/helpers/traverse-webhooks.test.ts
packages/workspace-store/src/navigation/helpers/traverse-webhooks.ts
packages/workspace-store/src/navigation/types.ts
packages/workspace-store/src/schemas/inmemory-workspace.ts
packages/workspace-store/src/schemas/navigation.ts
packages/workspace-store/src/schemas/v3.1/strict/openapi-document.ts
packages/workspace-store/src/server.ts

**Problem**
There is currently no way to persist the entire workspace state between sessions. This limits the ability to save work, share it, or restore it later.
**Solution**
This PR adds support for exporting the complete internal workspace state as a JSON-like string. This exported state can be saved externally and later reloaded to fully restore the workspace, enabling seamless state persistence and recovery across sessions.
**Checklist**

feat(workspace-store): add persistence layer to workspace store

---

.changeset/tough-bugs-report.md
packages/components/src/components/ScalarCombobox/ScalarCombobox.test.ts
packages/components/src/components/ScalarCombobox/ScalarComboboxOptions.vue

**Problem**
Currently, the page jumps when you open a large combobox. It can be seen in:
https://github.com/scalar/scalar/pull/6191
**Solution**
With this PR we revert back to the timeout which does not cause a scroll (nextTick does).
**Checklist**

fix(components): scalar combobox options scroll on open

---

.changeset/wicked-rats-watch.md
packages/components/src/components/ScalarSidebar/ScalarSidebar.stories.ts
packages/components/src/components/ScalarSidebar/ScalarSidebarButton.vue
packages/components/src/components/ScalarSidebar/ScalarSidebarGroup.test.ts
packages/components/src/components/ScalarSidebar/ScalarSidebarGroup.vue
packages/components/src/components/ScalarSidebar/ScalarSidebarGroupToggle.vue
packages/components/src/components/ScalarSidebar/ScalarSidebarIndent.vue
packages/components/src/components/ScalarSidebar/ScalarSidebarItems.vue
packages/components/src/components/ScalarSidebar/ScalarSidebarNestedItems.vue
packages/components/src/components/ScalarSidebar/ScalarSidebarPlayground.vue
packages/components/src/components/ScalarSidebar/ScalarSidebarSection.vue
packages/components/src/components/ScalarSidebar/ScalarSidebarSpacer.vue
packages/components/src/components/ScalarSidebar/findScrollContainer.test.ts
packages/components/src/components/ScalarSidebar/findScrollContainer.ts
packages/components/src/components/ScalarSidebar/useSidebarGroups.ts
packages/components/src/components/ScalarSidebar/useSidebarNestedItems.test.ts
packages/components/src/components/ScalarSidebar/useSidebarNestedItems.ts

Creates a nested items component which allows you to create nested sidebars as elements within sidebars.
[**Storybook Demo**](https://9b839acd-2c4f-4048-9703-6bf951a41e37--scalar-components.netlify.app/iframe.html?args=&id=components-scalarsidebar--with-nested-sidebars&viewMode=story)
Features:
- Groups remain semantically correct in the DOM, that is to say the nested items follow a sublist relationship (`ul > li > ul > li` etc.)
- Items are animated gracefully in and out
- Scroll / overflow is handled between item groups and during animations
- Keyboard focus is handled between item groups 
https://github.com/user-attachments/assets/04014363-c781-445d-a815-906faa42bd42
Scroll handling between nested item groups:
https://github.com/user-attachments/assets/4f839b18-ea9b-4787-88c6-d76cace780 …

feat(components): add nested sidebar component

---

.changeset/gorgeous-berries-pump.md
packages/oas-utils/src/transforms/import-spec.test.ts
packages/oas-utils/src/transforms/import-spec.ts

**Problem**
When a document without servers is imported from a relative URL, the relative URL is used as a server URL.
Which is not good.
**Solution**
With this PR we won’t use relative document URLs as server fallbacks anymore.
Fixes #6192
**Checklist**

fix(api-client): do not use relative URL as a server URL

---

.changeset/shaggy-apricots-hope.md
packages/workspace-store/src/helpers/proxy.test.ts
packages/workspace-store/src/helpers/proxy.ts

**Problem**
Currently, local $ref resolution does not work correctly when the $ref appears inside an array. This leads to incomplete or incorrect schema resolution in these cases.
**Solution**
This PR fixes the local $ref resolution logic to correctly handle $ref references nested within arrays, ensuring schemas are fully and accurately resolved regardless of their location.
**Checklist**

fix(workspace-store): support local ref resolution on arrays

---

.changeset/soft-melons-turn.md
packages/oas-utils/src/transforms/import-spec.ts

**Problem**
Currently, the port is not considered when building the server URL.
**Solution**
Now the port will be appended if present.
Closes #6210
**Checklist**

fix(oas-utils): include port in server URL

---

.changeset/gold-parents-tap.md
packages/api-reference/src/components/Content/Schema/SchemaEnumPropertyItem.vue
packages/api-reference/src/components/Content/Schema/SchemaEnumValues.test.ts
packages/api-reference/src/components/Content/Schema/SchemaEnumValues.vue
packages/api-reference/src/components/Content/Schema/SchemaProperty.test.ts
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue

**Problem**
Currently, enum descriptions are not displayed for expandable enum values in the API Reference.
**Solution**
`Before`:
`After`:
Closes #6199
**Checklist**

fix(api-reference): show description for expandable enum values

---

.changeset/small-moles-guess.md
packages/code-highlight/src/css/markdown.css

**Solution**
this pr updates the markdown details component style to match behavior with static docs for sibling usage + enhance long content support.
| before | <img width="594" alt="image" src="https://github.com/user-attachments/assets/e870d4e4-4e16-490c-91fb-b1cab54d565e" /> |
| after | <img width="594" alt="image" src="https://github.com/user-attachments/assets/7fa52d83-72f7-45cd-8fdb-1d678ee3f461" /> |
**Checklist**

feat(code-highlight): updates markdown details style

---

.changeset/spicy-monkeys-boil.md
packages/api-reference/src/features/example-request/ExampleRequest.vue

**Problem**
when updating discriminator the request example payload doesn't get updated accordingly as it used to.
**Solution**
this pr updates the request example discriminator change function to ensure get example from request vs operation.
**Testing**
<details>
<summary>OpenAPI Discriminator Object</summary>
```yaml
openapi: 3.0.3
info:
title: Polymorphic Object Example
version: 1.0.0
paths:
/vehicle:
post:
summary: Submit a vehicle
requestBody:
required: true
content:
application/json:
schema:
$ref: "#/components/schemas/Vehicle"
responses:
'200':
description: Vehicle submitted successfully
components:
schemas:
Vehicle:
type: object
required:
- type
- manufacturer
properties:
type:
type: string
description: Type of vehicle
manufacturer:
type: string
description: Name of the …
```

fix(api-reference): request example payload doesn't change on discriminator updates

---

.changeset/chilly-pants-buy.md
packages/api-reference/src/components/ApiReference.vue
packages/api-reference/src/components/HttpMethod/HttpMethod.vue
packages/api-reference/src/helpers/convert-security-scheme.test.ts
packages/api-reference/src/helpers/convert-security-scheme.ts
packages/api-reference/src/v2/ApiReferenceWorkspace.vue
packages/api-reference/src/v2/blocks/scalar-request-example-block/components/ExamplePicker.test.ts
packages/api-reference/src/v2/blocks/scalar-request-example-block/components/ExamplePicker.vue
packages/api-reference/src/v2/blocks/scalar-request-example-block/helpers/find-client.ts
packages/api-reference/src/v2/blocks/scalar-request-example-block/index.ts
packages/api-reference/src/v2/events/definitions.ts
packages/api-reference/src/v2/hooks/useStore.ts
packages/workspace-store/src/client.test.ts
packages/workspace-store/src/schemas/v3.1/strict/callback.ts
packages/workspace-store/src/schemas/workspace.ts
packages/workspace-store/src/server.test.ts

This is just to break up https://github.com/scalar/scalar/pull/6218 into two PR's. This one lays the groundwork and actually shouldn't change anything as its mostly touching files/components that aren't being used. So its safe to merge and it brings the cognitive load down on reviewing the other one!
**Checklist**

feat(api-reference):  lay groundwork for block implementation

---

.changeset/wise-roses-divide.md
packages/api-reference/index.html
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/components/Section/SectionAccordion.vue
packages/api-reference/src/components/Section/SectionContainerAccordion.vue
packages/api-reference/src/features/Operation/components/callbacks/Callback.vue
packages/api-reference/src/features/Operation/components/callbacks/Callbacks.vue
packages/api-reference/src/features/Operation/layouts/ClassicLayout.vue
packages/api-reference/src/features/Operation/layouts/ModernLayout.vue
packages/api-reference/src/features/example-request/ExampleRequest.vue
packages/api-reference/src/features/test-request-button/TestRequestButton.test.ts
packages/api-reference/src/features/test-request-button/TestRequestButton.vue
packages/themes/src/base/reset.css

A bunch of cleanup on the classic layout:
* Update border to use default border width (0.5px)
* Fix issue with italics in operation path
* Matched operation HTTP method border radius to external card
* Restricted the height of the examples and made them sticky
* Update icons to phosphor and clean up transitions
* Add callback support in classic layout
* Fixed some double border issues
@cameronrohani we can tweak things however you like :)
**Checklist**

fix(api-reference): classic layout improvements

---

.changeset/eighty-dots-cry.md
packages/snippetz/src/plugins/rust/reqwest/reqwest.test.ts
packages/snippetz/src/plugins/rust/reqwest/reqwest.ts

**Problem**
We’ve added support for rust/reqwest code examples just recently, but it has two issues:
* Even for JSON endpoints, it’s expecting a plain text body.
* The code looks super crammed.
**Solution**
This PR:
* removes the response body handling (other generators don’t have that either)
* adds some whitespace
* pretty prints JSON
* refactors the generator for clarity and readability
* updates the tests
Fixes #6232
**Before**
**After**
**Checklist**

feat(snippetz): improved rust/reqwest output

---

.changeset/tall-comics-fry.md
packages/api-reference/src/features/example-responses/ExampleResponses.vue

**Problem**
In some cases, an additional `value` key shows up in the example responses after switching the tabs.
**Solution**
This PR fixes it. :)
Fixes #5435
Fixes #5064
I struggled to write a test for it, the code is ready to be refactored for sure. I’ll look into this on another day.
**Checklist**

fix(api-reference): example responses show additional `value` key

---

.vscode/settings.json

Updates the vs code config so we get tailwind support in functions and Vue `<transition>` classes.
**Checklist**

chore: update vscode tailwind config

---

.changeset/kind-shrimps-guess.md
packages/components/src/helpers/add-scalar-classes.test.ts
packages/components/src/helpers/add-scalar-classes.ts

It seems like sometimes Headless UI removes the portal root when the modal goes away which causes it to loose the `scalar-app` class. This updates the helper to watch for the portal root as long as the page is open and always add the `scalar-app` class.
I also removed `scalar-client` since we don't use it anymore for scoping and adds a bunch of tests to make sure the helper works.
**Checklist**

fix(components): update add scalar classes to always watch for the headless root

---

.changeset/eight-hotels-care.md
.changeset/seven-onions-compete.md
integrations/fastapi/package.json
integrations/fastapi/playground/main.py
integrations/fastapi/scalar_fastapi/__init__.py
integrations/fastapi/scalar_fastapi/scalar_fastapi.py
integrations/fastapi/tests/test_imports.py
integrations/fastapi/tests/test_integration.py
integrations/fastapi/tests/test_scalar_fastapi.py

**Problem**
Currently, we don’t support themes in the FastAPI integration.
**Solution**
This PR adds support for themes, including a whole bunch of tests.
Fixes #4157
**Checklist**

feat(fastapi): new theme option

---

.changeset/empty-garlics-yell.md
.changeset/seven-onions-compete.md
packages/api-reference/examples/openapi.json
packages/workspace-store/src/client.test.ts
packages/workspace-store/src/client.ts

**Problem**
Currently, when the request fails OR the data is not a valid object, it’s the same console message.
**Solution**
With this PR, we’re making a difference here. :) Easier to debug errors.
**Checklist**

feat(workspace-store): error message tells the reason `loadDocument` fails

---

.changeset/pink-trees-clean.md
.changeset/seven-onions-compete.md
packages/galaxy/src/documents/3.1.yaml

Looks like the hashes changed at some point? This PR fixes the internal link the Scalar Galaxy example.

fix(galaxy): broken internal link

---

.changeset/serious-rings-dress.md
.changeset/slow-cougars-hope.md
packages/api-reference/src/features/Search/SearchModal.vue
packages/components/src/components/ScalarSearchInput/ScalarSearchInput.vue

**Problem**
currently hitting enter within api reference search modal in no result presence lead to an error getting displayed and breaking the experience.
**Solution**
this pr prevents navigation on enter in no result presence + updates style to enhance empty state element positioning.
| before | <img width="612" height="177" alt="image" src="https://github.com/user-attachments/assets/69d40ea2-23ba-4c91-880d-06d7187b6c16" /> |
| after | <img width="612" height="177" alt="image" src="https://github.com/user-attachments/assets/84dcc650-d3a0-4b4b-a198-c74bad3617d8" /> |
**Checklist**

fix(api-reference): search bug with undefined operation on enter key

---

.changeset/seven-onions-compete.md
packages/api-reference/index.html
packages/openapi-parser/src/utils/bundle/plugins/fetch-urls/index.ts
packages/workspace-store/src/client.test.ts
packages/workspace-store/src/client.ts

**Problem**
Currently, the workspace store doesn’t load relative URLs. I think it’s because `isRemoteUrl` returns `false` for relative URLs.
**Solution**
This PR adds a relative URL example (`pnpm dev:reference`) to show the error.
⚠️ It doesn’t fix the issue yet.
**Checklist**

fix(workspace-store): can’t load relative URLs

---

.changeset/spicy-humans-travel.md
.changeset/young-singers-unite.md
packages/api-reference/src/components/Content/Content.vue
packages/api-reference/src/components/Content/Introduction/Introduction.vue
packages/api-reference/src/features/base-url/BaseUrl.vue

**Problem**
currently when the server dropdown overflow the next section, a stacking issue appears preventing from selection the last servers + server variables label/input font size is not consistent with the other introduction forms.
**Solution**
this pr fixes the stacking issue + font size inconsistency. fixes #6259 
| before | <img width="644" height="363" alt="image" src="https://github.com/user-attachments/assets/62e24418-eef0-4b63-940e-ee3c9d57243d" /> |
| after | <img width="644" height="363" alt="image" src="https://github.com/user-attachments/assets/528b1b7d-beeb-4c85-b6f5-b7fd82cf456a" /> |
**Checklist**

fix(api-reference): server dropdown stacking issue

---

.changeset/soft-pots-shake.md
.changeset/wise-trainers-wonder.md
packages/api-client/src/components/SectionFilter.vue
packages/api-client/src/components/Server/ServerSelector.vue
packages/api-client/src/components/Server/ServerVariablesForm.vue
packages/api-client/src/components/ViewLayout/ViewLayoutCollapse.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuth.vue
packages/api-reference/src/features/base-url/BaseUrl.vue
packages/components/src/components/ScalarCombobox/ScalarComboboxOptions.vue
packages/scripts/src/components/ViewLayout/ViewLayoutCollapse.vue

**Problem**
within customized api reference, section title are sometimes lack of line height contraint affects the parent height + custom utility on transform is breaking the alignment of glass icon and filter button. 
**Solution**
this pr sets line height on section title + reset tranform on glass icon and filter button.
<details>
<summary>changes preview</summary>
`request auth`
| before | <img width="422" height="128" alt="image" src="https://github.com/user-attachments/assets/4d84d023-9de0-4889-a24b-7b05a2552ea7" /> |
| after | <img width="422" height="128" alt="image" src="https://github.com/user-attachments/assets/13c4d62e-4348-42cf-8808-19b158d5a4ab" /> |
`section title`
| before | <img width="422" …

fix(api-reference): custom reference fixtures

---

.changeset/stupid-years-sparkle.md
packages/openapi-parser/src/utils/upgrade-from-two-to-three.test.ts
packages/openapi-parser/src/utils/upgrade-from-two-to-three.ts

**Problem**
closes #6262 
Currently, we ignore application and access code auth types in swagger 2
**Solution**
With this PR we add them to the upgrader.
**Checklist**

feat(openapi-parser): add application and accessCode to Swagger 2.0 upgrade

---

.changeset/bright-numbers-report.md
packages/api-reference/src/features/example-responses/ExampleResponses.vue
packages/api-reference/src/v2/blocks/scalar-request-example-block/components/ExamplePicker.test.ts
packages/api-reference/src/v2/blocks/scalar-request-example-block/components/ExamplePicker.vue
packages/api-reference/src/v2/blocks/scalar-request-example-block/components/RequestExample.vue

**Problem**
Currently, we fixed the value problem in response examples.
**Solution**
With this PR we fix it in the request examples. ALSO changed the example picker to a dropdown, no need for a combobox there :). 
| Before | After |
| <img width="481" height="362" alt="image" src="https://github.com/user-attachments/assets/29c5db09-da61-45a3-af21-fae8dde1a076" /> | <img width="486" height="324" alt="image" src="https://github.com/user-attachments/assets/dda5a18c-2d18-4eb4-b990-311ade2c0e02" /> |
| <img width="356" height="250" alt="image" src="https://github.com/user-attachments/assets/315d07de-9101-4685-9b6c-1f3821cdb0b5" /> | <img width="445" height="294" alt="image" src="https://github.com/user-attachments/assets/1e1313d2-ae96-4226-bd37-386e1d854a81" /> | …

fix(api-reference): value in requeste example code block

---

.changeset/pretty-papayas-tell.md
packages/api-reference/src/features/Operation/layouts/ClassicLayout.vue
packages/api-reference/src/features/Operation/layouts/ModernLayout.vue

**Changes**
following new request example introduction, this pr removes the schemas prop still passes to it that might not be used anymore.
**Checklist**

fix(api-reference): removes unused prop from request example

---

.changeset/loud-dancers-greet.md
packages/api-client/src/views/Request/ResponseSection/ResponseBodyDownload.vue
packages/api-client/src/views/Request/ResponseSection/ResponseBodyRaw.vue

**Changes**
this pr updates the response body styling to bring back highlight scrolling that was not effective along utility typo fix. fixes #6283 
**QA**
- go to api client / api reference
- send request 
- highlight and scroll within the reponse body
**Checklist**

fix(api-client): highlight scrolling within response bodies not working

---

.changeset/tall-trainers-think.md
packages/themes/src/base/reset.css

**Changes**
this pr removes a line-height added at the reset.css level in themes package to prevent misalignment within reference. this will be handle better in #6286
**Checklist**

fix(themes): added line height in themes reset breaking alignment

---

.changeset/spicy-bugs-trade.md
packages/api-reference/src/features/Operation/layouts/ClassicLayout.vue
packages/api-reference/src/features/Operation/layouts/ModernLayout.vue

**Problem**
Currently, `hiddenClients` does not affect the request example code blocks
**Solution**
With this PR we add this functionality back.
**Checklist**

fix(api-reference): config.hiddenClients not affecting the request example code blocks

---

.changeset/tough-needles-film.md
packages/api-reference/src/components/Content/ClientLibraries/ClientLibraries.vue
packages/api-reference/src/components/Content/ClientLibraries/ClientSelector.vue
packages/api-reference/src/features/example-responses/ExampleResponseTab.vue
packages/api-reference/src/features/example-responses/ExampleResponses.vue

**Changes**
this pr adds the scalar combobox to the client libraries card and some style fixtures.
`client libraries`
| before | <img width="640" height="445" alt="image" src="https://github.com/user-attachments/assets/8b47451f-0b6f-4835-bd0c-77e4790b5603" /> |
| after | <img width="640" height="445" alt="image" src="https://github.com/user-attachments/assets/c2c56cc8-493a-4c8d-98c5-a5dae132a33f" /> |
**Checklist**

feat(api-reference): updates client libraries card

---

documentation/integrations/flask.md
package.json
scalar.config.json

This PR adds this OpenAPI package for Flask to our list of integrations.
I've also added a pnpm script to quickly preview the documentation.

docs: add Flask OpenAPI3

---

.changeset/itchy-dancers-prove.md
packages/api-reference/src/components/Anchor/Anchor.vue
packages/api-reference/src/components/Section/SectionHeaderTag.vue

**Changes**
this pr updates the api reference heading anchor to use latest icons.
| before | <img width="538" height="182" alt="image" src="https://github.com/user-attachments/assets/7854d1dc-d305-4bf4-8e20-f336f46cca0a" /> |
| after | <img width="538" height="182" alt="image" src="https://github.com/user-attachments/assets/6bc2b1ca-18ad-47dc-86ec-c271ce0ffe35" /> |
**Checklist**

feat(api-reference): updates heading anchor style

---

.github/renovate.json

This PR reduces the noise for the .NET packages. Renovate doesn't need to create PRs for major releases; we'll tackle this manually.
**Checklist**

ci(renovate): disable major updates for Microsoft.AspNetCore packages

---

.changeset/old-fishes-relax.md
packages/api-reference/src/components/Content/ClientLibraries/ClientLibraries.test.ts
packages/api-reference/src/components/Content/ClientLibraries/ClientLibraries.vue
packages/api-reference/src/v2/blocks/scalar-request-example-block/components/RequestExample.vue
packages/api-reference/src/v2/blocks/scalar-request-example-block/helpers/find-client.ts

**Problem**
Currently, we had the default set in the request example blocks but not the top.
**Solution**
With this PR we set the default at the top as well. It must be done this way because in the "unset" state we show the custom examples in the operations.
| Before | After | 
| <img width="616" height="487" alt="image" src="https://github.com/user-attachments/assets/f3b42d5f-27df-418e-a189-c8f45c20afff" /> | <img width="637" height="464" alt="image" src="https://github.com/user-attachments/assets/1f6ad3c1-84a3-4e27-af63-e96db05de693" /> |
**Checklist**

fix(api-reference): set the default client lib to shell/curl

---

.changeset/grumpy-taxis-switch.md
packages/code-highlight/src/css/code.css

**Changes**
this pr removes the inline block display utility set to `hljs` to prevent the caret from being hiddent when using codeblock input.
| before | <img width="640" height="83" alt="image" src="https://github.com/user-attachments/assets/6b3d0399-f603-48d4-9f72-a2a6a1102120" /> |
| after | <img width="640" height="83" alt="image" src="https://github.com/user-attachments/assets/6f33c4aa-08bd-400b-bbec-826b79c83d0a" /> | 
**Checklist**

fix(code-highlight): cursor not visible in codeblock when first added

---

examples/web/src/pages/ApiReferencePage.vue

**Problem**
This examples uses the new store and the `configuration` to provide content, but it’s not actually wired up and the example doesn’t even load:
**Solution**
This PR just loads Scalar Galaxy from an URL (through the configuration and through the store).
Editing doesn’t work yet, it requires #6319. 😬 
**Checklist**

fix(examples/web): Basic API Reference example does not load

---

.changeset/plenty-garlics-destroy.md
packages/api-reference/src/components/LinkList/LinkList.test.ts
packages/api-reference/src/components/LinkList/LinkList.vue
packages/api-reference/src/features/info-object/License.vue

**Problem**
Currently, the link list may need to scroll
**Solution**
With this PR we reduce it to icons only if scroll is needed.
| | Preview |
| Before | <img width="563" height="450" alt="image" src="https://github.com/user-attachments/assets/4e9170fd-aa4d-4268-a502-279b9a98cc5c" /> |
| After | <img width="578" height="463" alt="image" src="https://github.com/user-attachments/assets/c9e14208-e376-457a-b068-ff17db771a89" /> | 
**Checklist**

feat(api-reference): convert link list to icons when it scrolls

---

.changeset/pink-peas-taste.md
packages/themes/src/base/reset.css

Somehow I missed this in the original PR it was in but we really just want the reset to strip away the base styles not apply style (we use `<a>`'s for all kinds of buttons and stuff).
**Checklist**

fix(themes): don't style `<a>` in reset only in markdown

---

packages/react-renderer/src/components/ReactRenderer.test.tsx

**Problem**
The React tests fail every now and then, it seems to be a timing issue.
**Solution**
This PR allows Vitest to retry the tests 3 times, maybe that helps already.
**Checklist**

test(api-reference): retry flaky React tests 3 times

---

.changeset/light-turkeys-rush.md
packages/api-reference/src/features/example-responses/ExampleResponse.vue
packages/api-reference/src/features/example-responses/ExampleResponses.test.ts
packages/api-reference/src/features/example-responses/ExampleResponses.vue
packages/api-reference/src/v2/blocks/scalar-request-example-block/components/ExamplePicker.vue
packages/oas-utils/src/helpers/normalize-mime-type-object.ts
packages/oas-utils/src/spec-getters/get-request-body-from-operation.ts

EDIT: Tests are failing, need to look into that
**Problem**
```js
{
openapi: '3.0.0',
info: {
title: 'Example',
version: '1.0.0',
},
paths: {
'/hello': {
get: {
summary: 'Hello World',
description: 'Hello World',
// Operation *without* responses
// responses: {
//   200: {
//     description: 'Hello World',
//   },
// },
},
},
},
}
```
**Solution**
This PR deals with undefined responses.
And I’ve switched to the new workspace OpenAPI types. 👍 
We work with an upgraded document now, so we can remove all the code to support Swagger 2.0 or the old single `example` syntax from OpenAPI pre-3.1.
**Checklist**

fix(api-reference): can not render operation without responses

---

.changeset/tiny-flowers-yell.md
packages/api-client/src/components/Server/ServerSelector.vue
packages/api-client/src/components/Server/ServerVariablesForm.vue
packages/api-client/src/components/Server/ServerVariablesSelect.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuth.vue
packages/api-reference/src/components/Content/Introduction/Introduction.vue
packages/api-reference/src/components/Section/CompactSection.vue
packages/api-reference/src/components/ShowMoreButton.vue
packages/api-reference/src/features/Operation/components/ContentTypeSelect.vue
packages/api-reference/src/features/Operation/components/ParameterListItem.vue
packages/api-reference/src/features/Operation/components/callbacks/Callback.vue
packages/api-reference/src/v2/blocks/scalar-request-example-block/components/ExamplePicker.vue
packages/api-reference/src/v2/blocks/scalar-request-example-block/components/RequestExample.vue
packages/components/src/components/ScalarCard/ScalarCardHeader.vue
packages/components/src/components/ScalarMarkdown/ScalarMarkdown.vue

**Changes**
this pr increases caret icon usage and style consistency amongst reference / client.
| before | <img width="583" height="291" alt="image" src="https://github.com/user-attachments/assets/d860bc4b-2b33-4741-97d5-5148cb967d21" /> |
| after | <img width="583" height="291" alt="image" src="https://github.com/user-attachments/assets/1a1df402-3212-422c-842c-edf809c595f2" /> |
**Checklist**

feat(api-reference): make all chevrons look the same

---

.changeset/fifty-toys-remember.md
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.test.ts
packages/api-reference/src/components/Content/Schema/SchemaPropertyHeading.vue

**Problem**
The `min` and `max` field for `minLength` and `maxLength` can be misleading in two ways:
* When the field is a number that is formatted as a string (ex: `"2"`) the user may think that it's indicating a maximum value for the number, when it's actually indicating the maximum string length.
* Additionally, if both `maximum` and `maxLength` or both `minimum` and `minLength` are specified, the UI will show `min` twice and `max` twice, making it impossible for the user to know what each property is referring to without inspecting the actual OpenAPI spec.
Currently, …
This property definition
```
"message": {
"minLength": 2,
"minimum": 3,
"example": "Hello, world!",
"maximum": 8,
"maxLength":10
}
```
results in this being displayed
**Solution**
With this PR …
I …

feat(api-reference): better schema `minLength`/`maxLength` labels

---

.changeset/cuddly-buses-speak.md
packages/api-reference/src/components/Content/ClientLibraries/featured-clients.ts

**Problem**
Currently, the order of the client libraries got reversed as I was taking the options and filtering by featured. 
**Solution**
With this PR instead I am using a map of the clients then mapping the filtered clients from it.
**Checklist**

fix(api-reference): the order of the client libraries was reversed

---

.changeset/stale-squids-glow.md
packages/api-reference/src/components/Section/SectionAccordion.vue
packages/object-utils/package.json
packages/object-utils/src/mutator-record/handlers.ts
pnpm-lock.yaml

**Problem**
Currently, this actually never worked before either.
**Solution**
With this PR we now update the hash on scroll on the classic layout.
**Checklist**

fix(api-reference): update the hash on scroll for classic layout

---

examples/web/examples/openapi.json
examples/web/src/pages/ApiReferencePage.vue
examples/web/src/pages/StandaloneApiReferencePage.vue

Hey, I’ve got tons of ideas how to improve our manual and automatic testing setup, but here is a quick (and intermediate one):
It adds a few more sources to the deploy example, so you can quickly check popular OpenAPI files in the deploy example.

feat(examples/web): add more sources to the deployed example

---

.changeset/many-phones-hunt.md
packages/openapi-parser/package.json
pnpm-lock.yaml

E.g. validate and dereference from the parser return the OpenAPI.Document type from @scalar/openapi-types. Without the dependency if you install the parser and call one of these functions TypeScript will infer the type of their returned schema to be any.

fix(openapi-parser): depend on @scalar/openapi-types

---

.changeset/tender-days-sneeze.md
integrations/aspire/src/Scalar.Aspire/Extensions/DistributedApplicationBuilderExtensions.cs
integrations/aspire/src/Scalar.Aspire/ScalarResource.cs

**Problem**
Currently, the resource is excluded from publishing.
**Solution**
This PR includes the resource by default. The devs can optionally exclude the resource if they want.
Closes #6366
**Checklist**

feat(Scalar.Aspire): allow publishing and service discovery

---

.changeset/clean-paws-grab.md
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuth.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuthDataTable.vue
packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestAuthTab.vue

**Changes**
this pr handles in a better way unselected request auth in order to rely on the empty state + refactors style for header/description to fix missing borders, following up of #6346 
| before | <img width="543" height="246" alt="image" src="https://github.com/user-attachments/assets/80686346-bee6-4ee2-8edb-4d11b44158af" /> |
| before | <img width="543" height="246" alt="image" src="https://github.com/user-attachments/assets/06c3cfd9-58dd-4fd1-bf48-c34fa42e743e" /> |
| after | <img width="543" height="246" alt="image" src="https://github.com/user-attachments/assets/b70addc3-ff56-4ae2-b836-572d3cd17f8d" /> |
**Checklist**

fix(api-client): missing request auth border and empty state

---

.changeset/eighty-pets-dress.md
packages/components/src/components/ScalarTooltip/ScalarTooltip.vue

Turns out we we're getting weird css generated by using our `dark:` Tailwind variant in an `@apply` and it was creating a warning from our minifiers.
This cleans it up while doing the same thing :)
**Checklist**

fix(components): apply tooltip shadow without tailwind variant

---

.changeset/fresh-planes-grab.md
packages/components/src/components/ScalarMarkdown/ScalarMarkdown.stories.ts
packages/components/src/components/ScalarMarkdown/ScalarMarkdown.vue

Updates the markdown `<p>` line height to match the figma (more or less). We use a 16px font size for most of refs and we were hard coding the line height to 22px (supposed to be `26px`).
This just puts it back to using `1.625` which means at 16px font size we get `26px` line-height, however at `14px` is `22.75px` which isn't technically right (supposed to be 22px) but I think let's clean it up and figure out a more cohesive markdown line height approach once we get OSS released.
It's worth note since the font size is variable for markdown (and technically the rest of our app since it's themed?) we might need to move away from using pixel based line heights all together.
**Checklist**

fix(components): make paragraph line height variable

---

.changeset/famous-trainers-add.md
packages/api-reference/src/features/Operation/components/ContentTypeSelect.vue
packages/api-reference/src/features/Operation/components/ParameterListItem.vue

**Changes**
this pr decreases content type select font size back + fixes its position in parameter list item.
| before | <img width="553" height="261" alt="image" src="https://github.com/user-attachments/assets/3c49c360-f6c5-491e-81da-ce93e805c13a" />  <img width="378" height="147" alt="image" src="https://github.com/user-attachments/assets/2ddc0523-c0cd-4785-adde-cf61d22d1c3d" /> |
| after | <img width="553" height="261" alt="image" src="https://github.com/user-attachments/assets/971a1fc1-90f1-442c-bbc7-3f3cd274d537" /> <img width="378" height="147" alt="image" src="https://github.com/user-attachments/assets/884887d6-49d3-4142-8376-ca3f92117b39" /> | 
**Checklist**

feat(api-reference): updates content type select style

---

packages/components/src/components/ScalarMarkdown/ScalarMarkdown.vue

**Problem**
Currently, the block quotes were too big
**Solution**
With this PR we drop em to 16px aka font-size-2
**Checklist**

fix(api-reference): block quote font size

---

.changeset/poor-rocks-worry.md
packages/api-client/src/components/Server/ServerVariablesForm.vue
packages/api-client/src/components/Server/ServerVariablesSelect.vue

**Changes**
this pr updates the server variables dropdown utility used to rotate the icon that is always set on open due to conflicted state in the api client as being nested within another dropdown.
| before | <img width="525" height="298" alt="image" src="https://github.com/user-attachments/assets/c3c3153b-1c30-4aca-b682-537db65cd5c0" /> |
| after | <img width="525" height="298" alt="image" src="https://github.com/user-attachments/assets/650c1f82-8040-4ea5-955f-fcb9e911182a" /> | 
**Checklist**

fix(api-client): server variables dropdown always open

---

documentation/configuration.md

The current example for the `pathRouting` setting does not really work as I’d expect it to work. It looks like a routing regex pattern, but it’s actually just a string.
Found out when I wrote a e2e test for it.
I don’t know what the initial intention was, but a regular string does what it should do.

docs(api-reference): `pathRouting` example does not work as intended

---

.changeset/modern-pants-help.md
packages/api-reference/index.html
packages/api-reference/src/helpers/test-utils.ts
packages/api-reference/src/standalone/lib/html-api.test.ts
packages/api-reference/src/v2/ApiReferenceWorkspace.test.ts
packages/api-reference/src/v2/ApiReferenceWorkspace.vue
packages/api-reference/src/v2/helpers/get-document-name.test.ts
packages/api-reference/src/v2/helpers/get-document-name.ts
packages/api-reference/src/v2/helpers/normalize-content.test.ts
packages/api-reference/src/v2/helpers/normalize-content.ts
packages/workspace-store/esbuild.ts
packages/workspace-store/package.json

I only added the failing test, the actual PR is authored by @amritk. 🤝 
**Problem**
When using the `'scalar:update-references-config'` event, or the `app.updateConfiguration` API, or updating the `configuration` prop of `<ApiReference />`, the new store doesn’t listen to changes to `content` or `url` anymore.
**Solution**
**Checklist**

feat(api-reference): update the workspace store when the document changes

---

packages/api-reference/src/components/Content/Schema/Schema.test.ts
packages/api-reference/src/components/Content/Schema/SchemaObjectProperties.test.ts
packages/api-reference/src/components/Content/Schema/SchemaObjectProperties.vue

**Problem**
Currently, we don't order properties.
**Solution**
With this PR we order them by required then alphabetical
**Checklist**

feat(api-reference): order object properties required > alphabetical

---

.changeset/curly-waves-think.md
packages/api-reference/src/components/Content/Schema/Schema.test.ts
packages/api-reference/src/components/Content/Schema/Schema.vue
packages/api-reference/src/features/Operation/components/RequestBody.vue

**Problem**
Currently, we don't show the description from level 0 in schema.
**Solution**
With this PR we take the first description from allOf properties. A specific fix that we can later make more generic
**Checklist**

fix(api-reference): show schema description from allOf properties

---

.changeset/warm-pugs-switch.md
packages/oas-utils/src/helpers/operation-to-har/operation-to-har.ts
packages/oas-utils/src/helpers/operation-to-har/process-parameters.test.ts
packages/oas-utils/src/helpers/operation-to-har/process-parameters.ts

**Problem**
Currently, we omit query params with no value, we also show the path variable in the request example.
**Solution**
With this PR
- we show empty query params
- we replace the param variable with any example values
|  | Screenshot |
| Before | <img width="488" height="132" alt="image" src="https://github.com/user-attachments/assets/7342b36c-effb-462e-bcd9-8dd366800e86" /> | 
| After | <img width="506" height="130" alt="image" src="https://github.com/user-attachments/assets/683bacb9-d5fd-4577-bb5b-9babaa64041f" /> | 
**Checklist**

fix(api-reference): show empty query params and fill in path params in request example

---

.changeset/tasty-steaks-jog.md
packages/api-reference/src/features/api-client-modal/ApiClientModal.vue

**Problem**
closes #6441
Currently, we are double importing the client store.
**Solution**
With this PR we ensure theres actual changes to the content first. This won't be needed once we switch stores so I just put up the bandaid instead of looking for the cause. 
**Checklist**

fix(api-reference): empty test request modal

---

.changeset/kind-buckets-vanish.md
packages/api-reference/src/components/Content/Models/Models.test.ts
packages/api-reference/src/components/Content/Models/Models.vue

**Changes**
this pr updates the models component in order to use the getModels function to render schema models.
| before | <img width="640" height="460" alt="image" src="https://github.com/user-attachments/assets/ed5d9abb-253d-4aaa-b3a1-9a1b86a71472" /> |
| after | <img width="640" height="460" alt="image" src="https://github.com/user-attachments/assets/0fef99db-8609-41fd-9ea3-5c5c3c22d5a7" /> | 
**Checklist**

fix(api-reference): models with `x-scalar-ignore` show up again

---

.changeset/wicked-foxes-applaud.md
packages/api-client/src/components/CodeInput/codeVariableWidget.ts
packages/api-client/src/views/Environment/EnvironmentVariableDropdown.vue

**Changes**
this pr:
- updates the code variable widget according to recent tooltip component changes
- fixes color mode support
- update scalar icon usages
- enhances navigation logic
| before | <img width="603" height="110" alt="image" src="https://github.com/user-attachments/assets/ec8e6419-cbfc-45dd-b936-d6b8f748eab3" /> |
| after | <img width="603" height="110" alt="image" src="https://github.com/user-attachments/assets/36d7ad0c-e191-46e9-a557-c9466c72469a" /> | 
**Checklist**

fix(api-client): environment variable tooltip not displayed

---

.changeset/dull-glasses-wave.md
packages/api-reference/src/features/Operation/Operation.test.ts
packages/api-reference/src/features/Operation/Operation.vue
packages/api-reference/src/features/Operation/helpers/combine-params.test.ts
packages/api-reference/src/features/Operation/helpers/combine-params.ts
packages/api-reference/src/features/Operation/layouts/ClassicLayout.vue
packages/api-reference/src/features/Operation/layouts/ModernLayout.vue
packages/api-reference/src/helpers/test-utils.ts
packages/api-reference/src/vitest.setup.ts

**Problem**
closes #6472
Currently, we weren't passing the path parameters into the request example code.
**Solution**
With this PR we merge it into the operation. We can keep them separate if we have any reason to. 
|  | Screenshot |
| Before | <img width="876" height="728" alt="image" src="https://github.com/user-attachments/assets/1f63e6a6-dbda-4685-bc93-ca2a94a25b7f" /> |
| After |  <img width="1136" height="572" alt="image" src="https://github.com/user-attachments/assets/d4f8b5c6-4ec4-4ff3-9c72-9f2b4586d863" />| 
**Checklist**

fix(api-reference): path parameters not showing in request example code

---

.changeset/silly-experts-decide.md
.github/workflows/ci.yml
packages/galaxy/README.md

**Problem**
Currently, we’re publishing @scalar/galaxy on NPM and promote the jsdelivr URLs, but don’t have it in the Scalar Registry™.
**Solution**
With this PR the OpenAPI document is pushed to the Scalar Registry on release. It’s using the version from the package.json (which is also in the document).
The resulting URLs:
* https://registry.scalar.com/@scalar/apis/galaxy
* https://registry.scalar.com/@scalar/apis/galaxy/latest?format=json
* https://registry.scalar.com/@scalar/apis/galaxy/latest?format=yaml
I’ll replace the jsdelivr URLs in a different PR.
**Checklist**

feat(galaxy): publish in Scalar Registry

---

packages/api-reference/index.html
packages/galaxy/package.json

No deps, all convenience
**Checklist**

chore(galaxy): add live serving of galaxy for some convenience

---

packages/json-magic/package.json
packages/json-magic/src/bundle/bundle.test.ts
packages/json-magic/src/bundle/bundle.ts
packages/json-magic/src/bundle/index.ts
packages/json-magic/src/bundle/plugins/fetch-urls/index.ts
packages/json-magic/src/bundle/plugins/parse-json/index.ts
packages/json-magic/src/bundle/plugins/parse-yaml/index.ts
packages/json-magic/src/bundle/plugins/read-files/index.ts
packages/workspace-store/src/client.ts
packages/workspace-store/src/plugins.test.ts
packages/workspace-store/src/plugins.ts
pnpm-lock.yaml

**Problem**
Plugins currently only support resolving external documents (e.g. from URLs or files) and do not have access to the node processing lifecycle. This limits their ability to interact with or modify nodes during the bundling process.
Additionally, $ref values in non-standard locations—such as under the info object—are not currently supported, which can cause issues for non compliant documents.
**Solution**
This PR introduces a new plugin type that can hook into the node lifecycle during bundling. These lifecycle-aware plugins can inspect, transform, or clean up nodes as they are processed.
We also include a new built-in plugin that detects $refs in non-standard locations (e.g. info) and replaces them with their resolved content. This ensures that such $refs are removed before …

feat(json-magic): support node lifecycle hooks in bundler plugins

---

.github/renovate.json

We recently introduced the Java integration. Let`s add the integration to renovate.
**Checklist**

chore(renovate): add java integration

---

.github/actions/build/action.yml

**Problem**
I was blind and never tagged the actions/cache/restore GitHub action to a tag.
**Solution**
Now it's tagged to the same version as all actions/cache GitHub actions.
**Checklist**

chore(ci): pin actions/cache/restore to v4 tag

---

.changeset/honest-ladybugs-roll.md
documentation/integrations/aspire.md
integrations/aspire/playground/Scalar.Aspire.AppHost/Program.cs
integrations/aspire/src/Scalar.Aspire/Extensions/AsyncEnumerableExtensions.cs
integrations/aspire/src/Scalar.Aspire/Extensions/ResourceBuilderExtensions.cs
integrations/aspire/src/Scalar.Aspire/Mapper/ScalarOptionsMapper.cs
integrations/aspire/src/Scalar.Aspire/ScalarAnnotation.cs
integrations/aspire/src/Scalar.Aspire/ScalarHook.cs
integrations/aspire/tests/Scalar.Aspire.Tests/ScalarOptionsMapperTests.cs

**Problem**
Currently, it is not possible to do some async tasks inside the `WithApiReference` method.
**Solution**
With this PR, we add an async overload to the method.
Usage:
```csharp
scalar.WithApiReference(bookService, async (options, cancellationToken) =>
{
options
.AddDocument("v1", "Book Management API")
.WithOpenApiRoutePattern("/swagger/{documentName}.json");
// Example: load a dev API key asynchronously
var apiKey = await secretProvider.GetValueAsync("BOOKS_API_KEY", cancellationToken);
options
.AddPreferredSecuritySchemes("BookApiKey")
.AddApiKeyAuthentication("ApiKey", schema => schema.WithValue(apiKey));
});
```
**Checklist**
Closes #6422 

feat(Scalar.Aspire): support async configuration

---

.devcontainer/devcontainer.json
.gitignore
packages/api-reference/vite.config.ts
turbo.json

This PR introduces the initial `.devcontainer/devcontainer.json`, enabling:
- the usage of dev containers in VS Code
- the usage of GitHub Codespaces
Currently, the container only supports Node, which means that packages like the proxy (Go) or `Scalar.Aspire` (.NET) won't work. We can consider adding them later to this config or add dedicated dev containers for them.
Tested with the `pnpm dev:reference` command 👍 
**Checklist**

feat: initial support for dev containers

---

.changeset/tender-roses-reply.md
packages/json-magic/src/bundle/bundle.test.ts
packages/json-magic/src/bundle/bundle.ts
packages/workspace-store/src/client.test.ts
packages/workspace-store/src/client.ts
packages/workspace-store/src/helpers/apply-selective-updates.test.ts
packages/workspace-store/src/helpers/apply-selective-updates.ts
packages/workspace-store/src/plugins.test.ts
packages/workspace-store/src/plugins.ts

**Problem**
There were several bugs related to how we handle replacing documents and reverting changes, which caused the document state to fall out of sync.
**Solution**
This PR fixes those issues by ensuring the document state remains consistent.
Additionally, it introduces a new bundler plugin that restores the original references, which is useful when saving the working document to an intermediate state.
We’ve also enhanced the plugin hooks with additional context, making them more flexible and adaptable for different use cases.
⚠️ **Breaking changes**
- `store.replaceDocument` now returns a `Promise`
- `saveDocument` now returns a `Promise`
- `revertDocumentChanges` now returns a `Promise`
**Checklist**

fix(workspace-store): correctly propagate documents from one state to the other

---

.github/workflows/ci.yml

**Problem**
We try to deploy the component test reports in CI, but forks and bots don’t have access to the Netlify secrets, so it’ll fail.
**Solution**
With this PR we’ll skip it for bots and forks.
**Checklist**

ci: do not deploy component test report on forks

---

.changeset/honest-flies-burn.md
integrations/aspire/src/Scalar.Aspire/Extensions/DistributedApplicationBuilderExtensions.cs
integrations/aspire/src/Scalar.Aspire/ScalarHook.cs

**Problem**
Currently, it's not possible to run multiple scalar instances in .NET Aspire.
**Solution**
Now every resource will be configured, not only the first one.
Closes #6424 
**Checklist**

feat(Scalar.Aspire): support multiple scalar resources

---

.changeset/sixty-spiders-compare.md
documentation/openapi.md
packages/api-reference/src/components/Badge/Badge.vue
packages/api-reference/src/features/Operation/layouts/ClassicLayout.vue
packages/api-reference/src/features/Operation/layouts/ModernLayout.vue
packages/api-reference/src/features/x-badges/XBadges.test.ts
packages/api-reference/src/features/x-badges/XBadges.vue
packages/api-reference/src/features/x-badges/index.ts

**Problem**
We have a few badges for operations already, for webhooks, `x-scalar-stability` and `deprecated`. But we don’t support [`x-badges`](https://redocly.com/docs/realm/content/api-docs/openapi-extensions/x-badges) yet.
**Solution**
This PR adds support for `x-badges`, including docs and tests.
Fixes #6545
**Example**
```yaml
openapi: 3.1.0
info:
title: x-badges example
version: 1.0.0
paths:
/hello-world:
get:
summary: Hello World
deprecated: true
x-badges:
- name: 'Alpha'
- name: 'Beta'
position: before
- name: 'Gamma'
position: after
color: '#ffcc00'
```
**Preview**
**Checklist**

feat(api-reference): `x-badges`

---

.changeset/stupid-moose-tickle.md
packages/api-reference/src/v2/ApiReferenceWorkspace.vue

**Problem**
**TL;DR** We don’t load the document, if you switch between two configurations with the same `url` or `content`.
Details: #6528
**Solution**
* This PR adds a watcher for `slug` changes, as an addition to the `content` and `url` watcher.
* The slug is generated even if you only have a single document or didn’t define a slug yourself.
* This will be removed once we fully use the store.
Fixes #6528
**Checklist**

fix(api-reference): does not load document when the `url`/`content` stays the same

---

.changeset/orange-ties-relax.md
packages/api-reference/src/components/MobileHeader.vue

**Problem**
Currently, the API reference has horizontal scrollbars in a VS Code WebView.
**Solution**
The changes in this PR make them go away.
I’ve patched the VS Code integration already, so there’s no rush to get this in here. But I thought we might want to have the fix upstream.
**Checklist**

fix(api-reference): horizontal scrollbars in a VS Code WebView

---

.changeset/friendly-donuts-serve.md
packages/openapi-parser/src/utils/upgrade-from-three-to-three-one.test.ts
packages/openapi-parser/src/utils/upgrade-from-three-to-three-one.ts

**Problem**
closes #6537
Currently, the upgrader will remove all of the old schema properties.
**Solution**
With this PR we only remove format and keep the rest.
**Checklist**

fix(openapi-parser): ensure upgrader doesn't lose schema properties

---

documentation/guides/docs/components/tabs.md

**Problem**
Currently, there are mistakes in the tabs docs that are causing the first example to not render as intended, and after the next release from Scalar the new-lines after a `<scalar-[tag]>` will no-longer be required for successful markdown rendering.
~_Note: this PR is a DRAFT until the next release has been cut._~
**Solution**
With this PR I have fixed the syntax errors in the tabs example, and made it more compact and easier to read.
**Checklist**

feat(documentation): tabs custom-html syntax updates

---

.changeset/modern-balloons-lick.md
packages/workspace-store/src/client.test.ts
packages/workspace-store/src/client.ts

**Problem**
At the moment, the fetcher is only applied to the top-level document. As a result, when external references are bundled, they are fetched without the configured fetcher, which can lead to CORS errors and inconsistent behavior.
**Solution**
This PR ensures that the same document configuration and fetcher are consistently applied not just to the top-level document but also to all external references during bundling. This makes reference resolution more reliable and prevents CORS issues.
**Checklist**

feat(workspace-store): use the configuration fetcher to bundle the document

---

documentation/integrations/docker.md

**Problem**
A syntax error in the sample JSON in `API_REFERENCE_CONFIG` causing crash on startup (in browser).
**Solution**
Fixed
**Checklist**

docs(docker): fix syntax error in `API_REFERENCE_CONFIG` sample

---

packages/api-reference/index.html

**Problem**
Currently, we were pointing the first entry index.html in references to the registry. However galaxy.scalar.com uses another document and we normally compare the two.
**Solution**
With this PR we add the same document that galaxy.scalar.com uses as the first entry and move the registry document to the second entry.
No need for changeset as this only affects dev
**Checklist**

feat(api-reference): use galaxy.scalar.com as the first entry in index.html

---

.changeset/soft-chairs-change.md
documentation/integrations/aspire.md
integrations/aspire/playground/Scalar.Aspire.AppHost/Program.cs
integrations/aspire/playground/Scalar.Aspire.AppHost/Properties/launchSettings.json
integrations/aspire/playground/Scalar.Aspire.BookService/Program.cs
integrations/aspire/playground/Scalar.Aspire.BookService/Properties/launchSettings.json
integrations/aspire/src/Scalar.Aspire.Service/Dockerfile
integrations/aspire/src/Scalar.Aspire.Service/Endpoints/ProxyEndpoint.cs
integrations/aspire/src/Scalar.Aspire.Service/EnvironmentVariables.cs
integrations/aspire/src/Scalar.Aspire.Service/Extensions/ServiceCollectionExtensions.cs
integrations/aspire/src/Scalar.Aspire.Service/LoggerMessages.cs
integrations/aspire/src/Scalar.Aspire.Service/Program.cs
integrations/aspire/src/Scalar.Aspire.Service/appsettings.Development.json
integrations/aspire/src/Scalar.Aspire.Service/appsettings.Production.json
integrations/aspire/src/Scalar.Aspire.Service/appsettings.json
integrations/aspire/src/Scalar.Aspire/EnvironmentVariables.cs
integrations/aspire/src/Scalar.Aspire/Extensions/ScalarAspireOptionsExtensions.cs
integrations/aspire/src/Scalar.Aspire/Extensions/ScalarOptionsExtensions.cs
integrations/aspire/src/Scalar.Aspire/Options/ScalarAspireOptions.cs
integrations/aspire/src/Scalar.Aspire/Options/ScalarOptions.cs
integrations/aspire/src/Scalar.Aspire/ScalarResourceConfigurator.cs

**Problem**
Currently, Scalar only supports HTTP.
**Solution**
This PR adds support for HTTPS endpoints.
```csharp
var scalar = builder.AddScalarApiReference(options =>
{
options
.PreferHttpsEndpoint() // Use HTTPS endpoint when available
.AllowSelfSignedCertificates(); // For development environments
});
```
- **Protocol Selection**: HTTP is used by default. Use `PreferHttpsEndpoint()` to prioritize HTTPS when available
- **Automatic Configuration**: When HTTPS is preferred, both OpenAPI document routes and server URLs are automatically configured to use HTTPS endpoints
- **Automatic Redirects**: HTTP to HTTPS redirects are handled automatically with proper header rewriting (localhost only)
- **Certificate Validation**: Self-signed certificates can be trusted in development using …

feat(Scalar.Aspire): support HTTPS

---

packages/api-reference/cdn.html
packages/api-reference/test/data/sources.js

We can maybe make the implementation tidier here but this let's us test the CDN side by side with main using the same sources.
**Checklist**

chore(api-reference): add CDN dev page for api references

---

package.json

**Problem**
Currently, someone removed the old types check.
**Solution**
With this PR we add it back in under :raw. The raw pnpm call is almost twice as fast on faster CPU's than a full turbo call. Now we can choose which one to use. Its helpful when fixing type errors. 
```zsh
pnpm types:check:raw  266.00s user 11.75s system 1593% cpu 17.435 total
Tasks:  92 successful, 92 total
Cached: 92 cached, 92 total
Time:   30.482s >>> FULL TURBO
```
**Checklist**

chore: add back types check raw

---

.changeset/nine-roses-compare.md
packages/api-reference/src/features/example-responses/ExampleResponse.test.ts
packages/api-reference/src/features/example-responses/ExampleResponse.vue
packages/api-reference/src/features/example-responses/ExampleResponses.vue
packages/api-reference/src/v2/blocks/scalar-request-example-block/components/RequestExample.test.ts
packages/api-reference/src/v2/blocks/scalar-request-example-block/components/RequestExample.vue
packages/oas-utils/src/helpers/operation-to-har/process-security-schemes.ts

**Problem**
Currently, we didn't handle examples having deep refs.
**Solution**
With this PR we add support + tests for that. Also Buffer was unavailable (not sure why I was using that), changed it to `btoa` instead.
**Checklist**

fix(api-reference): two more deep ref bugs

---

.changeset/tender-clouds-think.md
integrations/aspnetcore/src/Scalar.AspNetCore.Microsoft/Scalar.AspNetCore.Microsoft.csproj

**Problem**
With the latest .NET 10 PR, I accidentally bumped the version of `Microsoft.AspNetCore.OpenApi` to the latest version.
**Solution**
This PR downgrades the version back to `9.0.0` for better compatibility.
**Checklist**

chore(Scalar.AspNetCore): downgrade package for better compatibility

---

.changeset/moody-avocados-rule.md
packages/oas-utils/src/spec-getters/get-example-from-schema.test.ts
packages/oas-utils/src/spec-getters/get-example-from-schema.ts

**Problem**
Const values are not considered for schema examples.
**Solution**
With this PR, const values are one of the sources of possible schema examples.
**Checklist**

fix(oas-utils): use const value as example

---

.github/workflows/ci.yml
integrations/docker/README.md

This PR updates the `useblacksmith/build-push-action` GitHub action to version 2 and fixes the breaking changes by configuring `useblacksmith/setup-docker-builder` before each action.
**Checklist**

chore(ci): bump useblacksmith/build-push-action action to v2

---

.changeset/quiet-goats-think.md
packages/workspace-store/src/client.test.ts
packages/workspace-store/src/client.ts

**Problem**
Currently, when a referenced part of a document is invalid, validation fails completely and says something about invalid refs. This makes the whole rendering fail.
**Solution**
With this PR, we show the exact validation error messages in the console and still add the document so it can be rendered.
Fixes #6644
The actual issue seems to be in the coerce, we’ll try to fix that in another PR.
**Example Document**
```
openapi: 3.1.0
info:
title: Test API
version: 1.0.0
paths:
/test:
get:
responses:
'200':
content:
application/json:
schema:
$ref: '#/components/schemas/Foobar'
components:
schemas:
Foobar:
type: object
required:
properties:
storage:
type: string
```
**Console**
**Checklist**

feat(workspace-store): don't throw on validation errors, add validation errors to the console

---

biome.json

**Problem**
I’m probably the only one with a webjar build, but it contains the bundled JS and Biome fails to check the file, because it’s too big.
**Solution**
Let’s ignore the bundle.
**Checklist**

chore: make Biome ignore the JS in the webjar

---

.github/workflows/ci.yml

With this PR we reuse the already built `standalone.js` (artifact of the API Reference package) instead of building it multiple times. This is faster and more efficient.
Thoughts?
**Checklist**

ci: use API Reference artifacts

---

packages/analytics-client/esbuild.ts
packages/analytics-client/package.json
packages/analytics-client/src/events.ts
packages/analytics-client/src/index.ts
packages/analytics-client/tsconfig.build.json
packages/analytics-client/tsconfig.json
pnpm-lock.yaml

**Problem**
Currently, there is no analytics client.
**Solution**
With this PR we can send analytic events using the new `analytics-client` package.
**Checklist**

feat(analytics): Add `analytics-client` package

---

.changeset/good-ads-rush.md
integrations/fastapi/scalar_fastapi/__init__.py

**Problem**
Currently, the following snippet fails type-checking with `pyright`:
```py
from scalar_fastapi import get_scalar_api_reference
```
Output from `pyright`:
```text
error: "get_scalar_api_reference" is not exported from module "scalar_fastapi"
Import from "scalar_fastapi.scalar_fastapi" instead (reportPrivateImportUsage)
```
This arose after the `py.typed` file was added - without that, it seems that `pyright` doesn't report the issue.
**Solution**
This PR adds a `__all__` export for each symbol imported into `__init__.py`, which satisfies the type checker.
**Checklist**

fix(integration-fastapi): export all from scalar_fastapi

---

scalar.config.json

Adds the login and register buttons to the guides introduction.
**Checklist**

feat(documents): add login links to introduction

---

.github/workflows/ci.yml

**Problem**
Forks and bots don’t have access to secrets, so we need to skip some steps. Looks like my if condition had an invalid syntax.
**Solution**
This PR should finally fix it, so CI is passing for forks again. 🤞 
**Checklist**

fix: deployments aren't skipped for forks

---

.github/renovate.json

This PR removes the `integration` and `package` labels. I also disabled updates for the node Dockerfiles inside the Aspire playground.
**Checklist**

chore(renovate): remove labels and disable aspire playground node updates 

---

.changeset/poor-steaks-watch.md
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/test/configuration/layout.e2e.ts

**Problem**
Currently, we try to grab the first tag from the document to open it. But if there's no tags defined on the document this doesn't work.
**Solution**
With this PR we use the side bar entries to grab a tag.
**Checklist**

fix(api-reference): grab first tag from sidebar if not defined

---

.changeset/nice-mangos-cheat.md
packages/galaxy/src/documents/3.1.yaml

**Problem**
Our wonderful `@scalar/galaxy` example doesn’t have a circular reference yet. 🫨 
**Solution**
This PR adds one between planets and their satellites.
**Checklist**

feat(galaxy): circular reference planet ↔ satellite

---

.changeset/smart-shoes-flow.md
integrations/nestjs/package.json
integrations/nestjs/src/index.ts
integrations/nestjs/src/nestJSApiReference.ts
integrations/nestjs/src/types.ts
integrations/nestjs/test/index.test.ts
pnpm-lock.yaml

Now all LTS versions of Node.js already support `require(ESM)` (see [Node.js docs](https://nodejs.org/api/modules.html#loading-ecmascript-modules-using-require)).
Therefore, we can safely use `@scalar/core` for this package.
This change should likely be released as a major version bump.
**Checklist**

feat(nestjs): pure ESM distribution 

---

.changeset/kind-ducks-speak.md
documentation/integrations/fastapi.md
integrations/fastapi/scalar_fastapi/scalar_fastapi.py

**Problem**
We just support a few of the configuration options in the FastAPI integration.
**Solution**
This PR adds most configuration options.
We don’t cover those that expect a JS function yet, though.
**Checklist**

feat(fastapi): cover more of the configuration

---

packages/api-reference/src/components/ApiReference.vue
packages/api-reference/src/v2/ApiReferenceWorkspace.vue

**Problem**
Currently, there are no slots exposed on the `ApiReference` component.
**Solution**
With this PR I'm exposing all the slots that are available in `<ApiReferenceWorkspace />`
**Checklist**

feat(api-reference): Expose slots to ApiReference

---

documentation/configuration.md
packages/api-client/src/views/Request/hooks/useOpenApiWatcher.ts
packages/api-reference/src/features/document-source/hooks/useDocumentFetcher.test.ts
packages/api-reference/src/features/document-source/hooks/useDocumentFetcher.ts
packages/api-reference/src/v2/ApiReferenceWorkspace.test.ts
packages/api-reference/src/v2/ApiReferenceWorkspace.vue
packages/oas-utils/src/helpers/fetch-document.test.ts
packages/oas-utils/src/helpers/fetch-document.ts
packages/types/src/api-reference/api-reference-configuration.ts

**Problem**
When the API document is behind an authentication wall, it can only be loaded if it’s prefetched. Additionally, there’s currently no way to use a custom proxy implementation, which limits flexibility for different environments and authentication flows.
**Solution**
This PR introduces support for providing a custom fetcher function. When supplied, this function will be used to fetch the API document with user-defined logic (e.g., handling auth or proxies). This makes the integration more flexible and adaptable to different setups.
Closes #2824
📝 **Notes**
In a future major release, once we fully migrate to the new store and configuration shape, we can discuss about supporting passing custom headers directly. This will provide an even simpler and more configurable way to handle …

feat(api-reference): custom fetcher to load opeanpi documents

---

.github/workflows/ci.yml

**Problem**
We use an action to make sure we only use actions pinned to a commit (for security reasons).
**Solution**
[GitHub introduced that as a checkbox](https://github.blog/changelog/2025-08-15-github-actions-policy-now-supports-blocking-and-sha-pinning-actions/), so we can just use that now.
**Checklist**

ci: replace pinned action job with repository setting

---

.changeset/violet-doors-unite.md
integrations/express/package.json
packages/analytics-client/src/events.ts
packages/api-client/package.json
packages/api-client/src/analytics.ts
packages/api-client/src/hooks/useClientConfig.ts
packages/api-client/src/layouts/App/create-api-client-app.ts
packages/api-client/src/layouts/Web/create-api-client-web.ts
packages/api-client/src/views/Request/RequestRoot.vue
packages/types/src/api-reference/api-reference-configuration.ts
pnpm-lock.yaml

**Problem**
Currently, there are no scalar analytics set up for api-client
**Solution**
With this PR I've made use of `@scalar/analytics-client` to send 2 events:
- `page-view`
- `client-send-request`
These events are sent by the api-client, but only for: `desktop` and `web` not `modal`.
**Checklist**

feat(analytics): Add `page-view` & `client-send-request` to api-client

---

.changeset/weak-countries-occur.md
packages/api-client/src/components/Sidebar/SidebarButton.vue

We changed up the hotkey so it uses a flex layout now (but this was overriding it with `block`).
Before:
After:
**Checklist**

fix(api-client): don't apply block layout on desktop

---

integrations/aspire/package.json
integrations/aspnetcore/package.json
integrations/docker/package.json
integrations/docusaurus/package.json
integrations/fastify/package.json
integrations/java/webjar/package.json
package.json
packages/build-tooling/package.json
pnpm-lock.yaml
pnpm-workspace.yaml
scripts/package.json

**Problem**
Currently, we have some inconsistencies across our dependencies.
**Solution**
With this PR, we:
- Use `vite-node` only from the catalog.
- Use `shx` in our root `package.json`, so it's available across all packages.
**Checklist**

chore(pnpm): use catalog in more places

---

.changeset/selfish-pets-float.md
integrations/java/webjar/src/main/java/com/scalar/maven/webjar/ScalarController.java
integrations/java/webjar/src/test/java/com/scalar/maven/webjar/ScalarControllerTest.java

**Problem**
When using a path with a trailing slash (e.g. just `/`), it breaks the JS URL (`//scalar.js`).
**Solution**
This PR removes the trailing slash of the path for the JS URL, if there’s one.
**Checklist**

fix(java): paths ending with a slash break the JS URL

---

documentation/integrations/spring-boot.md

Update documentation to reflect the change in default value for `scalar.enabled`, which is now false by default in java module via #6781

feat(docs): Update `scalar.enabled` default in spring-boot.md

---

.changeset/smooth-boats-kneel.md
packages/api-client/src/libs/find-request.test.ts
packages/api-client/src/libs/find-request.ts

**Problem**
Currently, the `findRequestByPathMethod` would not match if you have query params
**Solution**
With this PR we ignore the query params to find a suitable match. If we needed, we could extract the query params later like we do with the path.
**Checklist**

feat(api-client): ignore query params on findRequestByPathMethod

---

.changeset/fifty-teachers-laugh.md
packages/build-tooling/src/esbuild/build.ts
packages/build-tooling/src/vite/options.ts

Limits the type return of vite options to help with version mismatch compat.

feat(build-tooling): Improve vite return type

---

.changeset/tidy-flies-roll.md
packages/api-reference/src/components/ApiReference.vue
packages/api-reference/src/components/ApiReferenceLayout.vue
packages/api-reference/src/v2/ApiReferenceWorkspace.vue

Paves the way for the dev toolbar (which will use the `content-start` slot) and fixes a double footer issue.
Before:
After:
**Checklist**

fix(api-reference): render proper slots

---

.changeset/itchy-hotels-juggle.md
documentation/integrations/spring-boot.md
integrations/java/spring-boot/src/main/resources/application.properties
integrations/java/webjar/pom.xml
integrations/java/webjar/src/main/java/com/scalar/maven/webjar/ScalarActuatorEndpoint.java
integrations/java/webjar/src/main/java/com/scalar/maven/webjar/ScalarAutoConfiguration.java
integrations/java/webjar/src/main/java/com/scalar/maven/webjar/ScalarProperties.java
integrations/java/webjar/src/test/java/com/scalar/maven/webjar/ScalarActuatorEndpointTest.java
integrations/java/webjar/src/test/java/com/scalar/maven/webjar/ScalarPropertiesTest.java

**Problem**
> The current webjar does not support exposing the Scalar UI beneath actuator endpoints. 
**Solution**
This PR adds support for it. :)
**Checklist**

feat(java): actuator endpoint

---

documentation/guides/introduction.md

* tweaked copy
* SDK Generation -> Scalar SDK Generation (becomes a product - not a thing - when reading)
* more engaging CTA (some people read the CTA only)
**Before**
**After**

docs: update SDK section

---

documentation/guides/introduction.md

* tweaked the copy
* API Registry -> Scalar Registry (becomes a product when reading, not a thing)
* make the point that it’s hooking into any workflow
* more engaging CTA
**Before**
**After**

docs: updated Scalar Registry section

---

documentation/guides/introduction.md

* tweaking of the copy
* API Docs >  Scalar Docs (sounds more like a product offering)
* **The** Platform
* Make the point that the result is an always-up-to-date documentation
* reorder list
* more engaging call to action
**Before**
**After**
wdyt?

docs: updated Scalar Docs section

---

.changeset/sweet-chefs-work.md
integrations/aspire/src/Scalar.Aspire/Contract/ScalarConfiguration.cs
integrations/aspire/src/Scalar.Aspire/Enums/PropertyOrder.cs
integrations/aspire/src/Scalar.Aspire/Extensions/ScalarOptionsExtensions.cs
integrations/aspire/src/Scalar.Aspire/Mapper/ScalarOptionsMapper.cs
integrations/aspire/src/Scalar.Aspire/Options/ScalarOptions.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Contract/ScalarConfiguration.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Converters/PropertyOrderJsonConverter.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Enums/PropertyOrder.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarOptionsExtensions.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Mapper/ScalarOptionsMapper.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Options/ScalarOptions.cs
integrations/aspnetcore/tests/Scalar.AspNetCore.Tests/Converters/PropertyOrderJsonConverterTests.cs
integrations/aspnetcore/tests/Scalar.AspNetCore.Tests/Extensions/ScalarOptionsExtensionsTests.cs
integrations/aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarOptionsMapperTests.cs

This PR adds support for the `orderRequiredPropertiesFirst` and `orderSchemaPropertiesBy` configurations to the Aspire and AspNetCore integration.
**Checklist**

feat(Scalar.AspNetCore): support OrderRequiredPropertiesFirst and OrderSchemaPropertiesBy

---

.changeset/spicy-actors-build.md
packages/void-server/src/utils/createXmlResponse.ts

With the recent XML update, I broke the @scalar/void-server XML responses.
They have the XML declaration twice:

fix(void-server): duplicate XML declaration

---

.changeset/nine-bottles-greet.md
integrations/aspire/src/Scalar.Aspire/Enums/DocumentDownloadType.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Enums/DocumentDownloadType.cs

Follow-up of https://github.com/scalar/scalar/pull/6854. This PR adds the `direct` download type to the .NET integrations.
**Checklist**

feat(Scalar.AspNetCore): add download type direct

---

integrations/hono/package.json
packages/api-reference/package.json
packages/api-reference/playground/ssr/package.json
packages/mock-server/package.json
packages/openapi-to-markdown/package.json
packages/void-server/package.json
pnpm-lock.yaml
pnpm-workspace.yaml

Moves Hono to the catalog, upgrades to 4.9.7 (security). :)

chore: upgrade Hono to 4.9.7

---

.changeset/chatty-jars-glow.md

I’ve updated the name to use underscore and the changeset still has the dashes, this breaks CI in main.

fix(rust): changeset has outdated crate name

---

.changeset/unlucky-toys-hug.md
integrations/aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarEndpointRouteBuilderExtensions.cs

This PR improves the way the `etag` header for our static assets is generated.
**Checklist**

feat(Scalar.AspNetCore): content-based ETag generation

---

.devcontainer/devcontainer.json
package.json
pnpm-workspace.yaml
projects/scalar-app/todesktop.json
tooling/base-docker-builder/Dockerfile

**Problem**
Sometimes, npm packages have security issues. They are mostly removed/fixed quickly, but we might install them before they are fixed/removed.
**Solution**
This PR uses pnpm’s `minimumReleaseAge` to wait at least a day until it installs a new version of something.
**Checklist**

chore: `minimumReleaseAge` (requires pnpm 10.16)

---

.github/renovate.json

Follow up for https://github.com/scalar/scalar/pull/6879
**Checklist**

chore(renovate): add minimumReleaseAge rule for npm packages

---

pnpm-workspace.yaml

**Problem**
Currently, the Docker build is failing, because we’re using a 4 days old version of rollup (we require it to be published 7 days ago at least).
**Solution**
This is annoying already. So let’s ignore a few of the suuuper popular dependencies.
We might even remove this again, but this will fix the build in main _now_.
**Checklist**

chore: ignore a few super popular dependencies with `minimumReleaseAgeExclude`

---

.changeset/angry-baboons-juggle.md
integrations/fastify/src/fastifyApiReference.ts

**Problem**
Fastify is moving the ignoreTrailingSlash to routerOptions and this is generating route conflicts with the scalar plugin.
**Solution**
We should check https://github.com/scalar/scalar/blob/main/integrations/fastify/src/fastifyApiReference.ts#L180
and add second verification for the routerOptions.ignoreTrailingSlash
**Checklist**

fix(fastify): check for the new fastify `routerOptions.ignoreTrailingSlash`

---

.changeset/nervous-rings-shake.md
packages/api-reference/src/features/Operation/Operation.test.ts
packages/api-reference/src/features/Operation/Operation.vue
packages/api-reference/src/features/Operation/helpers/get-first-server.test.ts
packages/api-reference/src/features/Operation/helpers/get-first-server.ts

**Problem**
When using multiple servers (root servers and operation-level servers), the “Examples” code samples ignore the operation/path server selection and always use the first server from the root of the OpenAPI document. The “Test Request” button already respects operation-level (and path-level) servers, so Examples and Test Request can disagree.
Steps to reproduce:
1. Define root servers: `[https://root.example.com, …]`
2. For an operation, define servers: `[{ url: 'https://op.example.com' }]`
3. “Test Request” sends to https://op.example.com, but “Examples” shows code using https://root.example.com
**Solution**
With this PR, Examples now use the same precedence as Test Request:
1. Prefer `operation.servers[0]`
2. Else `pathItem.servers[0]`
3. Else fall back to the provided/active …

fix(api-reference): use operation/path servers for code examples

---

.changeset/gentle-apricots-kneel.md
integrations/rust/README.md

a happy search and replace accident,
let’s fix it swiftly
so all is good again
and people can read our documentation

docs(rust): update link to the documentation

---

.changeset/nine-wasps-dance.md
packages/api-reference/src/components/Content/Schema/SchemaObjectProperties.test.ts
packages/api-reference/src/components/Content/Schema/SchemaObjectProperties.vue

**Problem**
Currently, we add an asterisk on additional properties. This actually breaks the snippet as it becomes invalid JS
**Solution**
With this PR we remove the asterisk
**Checklist**

fix(api-reference): remove asterisk on additionalProperties

---

.changeset/large-pigs-sin.md
packages/workspace-store/src/schemas/v3.1/strict/schema.ts

**Problem**
For `format: 'custom-format'` we render `date` as the format. That’s because our schema is too strict. 
> It should be noted that format is not limited to a specific set of valid values or types. 
Source: https://json-schema.org/understanding-json-schema/reference/type
**Solution**
This PR allows any string to be passed.
**Before**
**After**
**Checklist**

fix(workspace-store): schema does not allow custom formats

---

integrations/rust/Cargo.toml
pnpm-workspace.yaml

When there’s a build of the Rust crate, pnpm fails. Cargo copies the package.json and then pnpm complains there are two packages with the same name.
We need to Cargo to please ignore the package.json and not bundle it.
Easy as that.

fix(rust): pnpm fails when there is a build

---

packages/json-magic/src/bundle/bundle.test.ts

There were some flaky tests which was passing when the fetch was not resolving fast, but failing if the fetch took a bit longer.
With this PR I fix the flaky tests
**Checklist**

test: fix flaky tests

---

documentation/assets/api-docs-static-zoom-dark.svg
documentation/assets/api-docs-static-zoom.svg
documentation/assets/scalar-dashboard-dark.svg
documentation/assets/scalar-dashboard.svg
documentation/assets/sdk-dashboard-static-dark.svg
documentation/assets/sdk-dashboard-static.svg
documentation/guides/docs/getting-started.md
documentation/guides/introduction.md
documentation/guides/pricing.md
documentation/guides/registry/getting-started.md
documentation/guides/sdks/getting-started.md

redesign subpages for scalar-docs/getting-started, scalar-sdks/getting-started, scalar-registry/getting-started
missing some copy which @marclave will add

feat(docs): subpages redesign for getting started docs/sdks/registry

---

packages/json-magic/package.json
pnpm-lock.yaml

**Problem**
The package @scalar/json-magic [includes `vue` as a dependency](https://github.com/scalar/scalar/blob/main/packages/json-magic/package.json#L63), but it doesn't seem to be used anywhere.
**Solution**
Remove the dependency
**Checklist**

chore(json-magic): remove unneeded vue dependency

---

.changeset/hot-glasses-own.md
packages/api-reference/src/components/Content/Models/ClassicLayout.vue
packages/api-reference/src/components/Content/Models/Models.vue
packages/api-reference/src/components/Content/Models/ModernLayout.vue
packages/api-reference/src/components/Content/Schema/Schema.test.ts
packages/api-reference/src/components/Content/Schema/Schema.vue
packages/api-reference/src/components/Content/Schema/SchemaComposition.test.ts
packages/api-reference/src/components/Content/Schema/SchemaComposition.vue
packages/api-reference/src/components/Content/Schema/SchemaObjectProperties.test.ts
packages/api-reference/src/components/Content/Schema/SchemaObjectProperties.vue
packages/api-reference/src/components/Content/Schema/SchemaProperty.test.ts
packages/api-reference/src/components/Content/Schema/SchemaProperty.vue
packages/api-reference/src/components/Content/Schema/types.ts
packages/api-reference/src/features/Operation/components/Header.vue
packages/api-reference/src/features/Operation/components/Headers.vue
packages/api-reference/src/features/Operation/components/ParameterListItem.vue
packages/api-reference/src/features/Operation/components/RequestBody.vue

**Problem**
closes #6921 
Currently, the sorting property options weren't working. Our tests work but we weren't actually passing the props down!
**Solution**
With this PR we pass around the props to schema at all depths
**Checklist**

fix(api-reference): correctly pass down schema options

---

documentation/configuration.md

This PR improves the structure of our configuration documentation.
This looks quite nice IMO:
Checkout the preview 🙂 
**Checklist**

docs(configuration): improve structure

---

documentation/guides/docs/components/images.md
documentation/guides/docs/getting-started.md
documentation/guides/introduction.md
documentation/guides/pricing.md
documentation/guides/registry/getting-started.md
documentation/guides/sdks/getting-started.md
scalar.config.json

**Problem**
Currently, we include `<h1>` tags in some of our documentation files that we then hide with custom CSS in order to prevent them from showing up and to prevent the auto-injection of metadata that would result from them not being present.
Also, the documentation for the dark-mode parameter for `image` is out-of-date.
**Solution**
With this PR we are able to remove the unwanted `<h1>` elements without page injection. It also corrects the documentation for `image`.
_after image of the intro page_
_after images of dark/light mode src toggling_
| dark | light |
| ---- | ----- |
| <img width="692" height="483" alt="image" src="https://github.com/user-attachments/assets/43849b51-2450-450f-835b-a8dd870029a4" /> |  <img width="698" height="488" alt="image" …

docs: headings and image documentation corrections

---

.github/renovate.json
biome.json
package.json

This PR:
- Transforms the comments in our renovate configuration to have a valid JSON syntax
- Adds the Rust integration to the configuration
- Disable Docker updates for the Aspire integration
- Adds the `renovate.json`to biome's radar
- Adds a `renovate:validate` command to the root of the project.
**Checklist**

chore: update renovate.json to enhance package rules

---

.changeset/bright-geckos-develop.md
pnpm-lock.yaml
pnpm-workspace.yaml
projects/scalar-app/package.json

We’re using the pnpm catalog version for the scalar-app, but toDesktop doesn't know about our pnpm workspace file (yet).
Let’s just use good old version numbers for the scalar-app to quickly fix the toDesktop build.
EDIT: Tested and it looks good. It’s just that the notarization fails (for another reason).

fix(scalar-app): toDesktop can't find Electron version

---

documentation/configuration.md

It looks like I accidentally removed the docs for the `tagsSorter` configuration in a recent PR.  Lets bring it back!
**Checklist**

docs(configuration): add tagsSorter back

---

.changeset/spotty-dryers-yell.md
integrations/aspnetcore/src/Scalar.AspNetCore/Enums/ScalarTarget.Generated.cs
integrations/aspnetcore/src/Scalar.AspNetCore/Mapper/ScalarOptionsMapper.Generated.cs
integrations/aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarOptionsMapperTests.cs

I ran the `pnpm generate:enums` command 🤝 
**Checklist**

feat(Scalar.AspNetCore): add F# client
